### ISSUE TITLE
Add to routes should not change background map

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1000]
## bug

Under "my shares" after clicking a specific share clicking and the + icons I expected the route to be added to those on the map without changing the base map. Instead it changed the base map to the original one shared. I expected that behavior to only occur with "present share"

**Comment by zstadler** [comment]
I find this in contradiction to the well established practice of distributing additional background maps. This was the way @valleyofdawn published the British Mandate topographic maps, the Newcombe map, and several other maps.

The intention of a share is to show the sender's view "as-is" (WYSIWYG - What You See Is What You Get).

As a viewer, you always have the option to restore your favorite background map and no harm is done.

**Comment by zstadler** [comment]
I find this request to create a difference in the behavior of opening shares beyond necessity.

In all other flows, all the share's contents are shown.

Changing the background map is a matter of 1-3 mouse clicks.

**Comment by HarelM** [comment]
There are two modes: 
1. See a share - this will change the base map etc.
2. Add the routes from another share to current "workspace" - im not sure what should be the right behavior in this case, both of you present valid user experience arguments.

**Comment by zstadler** [comment]
My point is that creating a difference betweenthe two modes will unnecessarily increase the complexity of the user experience.

**Comment by valleyofdawn** [comment]
I think we should either have just one option, or two that are sufficiently different.

**Comment by HarelM** [comment]
This button allows "mege" of shares, there's no other way to do it without using files.
I have implemented @valleyofdawn 's request.
