### ISSUE TITLE
Avoid URL-encoding of links in OSM tags

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1002]
## What I expect to happen
Successfully use links in OSM tags such as `image` by
1. When uploading to Wikimedia, use image names with 175 Unicode characters or less
2. Use Unicode characters in URL tags rather than URL-encoding them
3. When uploading to OSM, ensure that all tag lengths are 255 characters or less

## What really happened
OSM rejects tag values longer than 255 characters, including Unicode characters. The site uses URL-encoding which replaces every non-ASCII character with 6 ASCII characters. As a result, there are several images successfully uploaded to Wikimedia Commons that do not appear in OSM. Attempts to re-upload the same image, even using a shorter name, would fail for reasons described in #1001

## Thing I think the developers should know, images, links etc.
For a given image filename and suffix, Wikimedia direct link currently adds a 53-character prefix. The 175-character image filename limit is suggested to be on the safe side.

**Comment by HarelM** [comment]
I haven't tested it with a long title, but I unit tested the code to make sure it does as expected.
Results can be seen here:
https://www.openstreetmap.org/way/447978668
No escaping.
