### ISSUE TITLE
Offline download always downloads Orux maps format although Locus maps was requested

### ISSUE THREAD

**Issue by ohadhawk** [IsraelHikingMap/Site#1004]
## Bug
(Delete the non-relevant)

## What I expect to happen
When marking "Locus" I expect the Locus maps format to be downloaded

## What really happened
The zip file contains two files that are associated with Orux maps:
- Israel Hiking.otrk2.xml
- OruxMapsImages.db

## What I did that caused the issue - step by step
1. Go to "download maps for offline use"
2. Choose:
- Locus
- Open Map
- Any of "15 [750MB]" or "16 [2.2GB]"

For both, downloaded zip file still contain Orux maps format.

## My environment
* Operating System and version: Windows 10
* Web Browser and version: Chrome 73.0.3683.103 (Official Build) (64-bit)

## Thing I think the developers should know, images, links etc.
![image](https://user-images.githubusercontent.com/1254388/56764376-3a804a00-67ad-11e9-8fba-3988a9e400c9.png)
![image](https://user-images.githubusercontent.com/1254388/56764423-55eb5500-67ad-11e9-8cbb-9de6ebfa0ef3.png)
![image](https://user-images.githubusercontent.com/1254388/56764386-3e13d100-67ad-11e9-9d94-d3dbf68c7a63.png)
![image](https://user-images.githubusercontent.com/1254388/56764611-ceeaac80-67ad-11e9-9207-398e935f638b.png)

**Comment by ohadhawk** [comment]
@HarelM

**Comment by HarelM** [comment]
I don't see any issue with that as Locus supports oruxmaps format.
We do not want to generate files for both orux and locus to reduce resources usage.
When using the mobile device to download this will call the relevant protocol - i.e. `locus-actions://`.
Can I close this issue?

**Comment by ohadhawk** [comment]
This is confusing from a user perspective. 
I would join the two "Application" buttons into one: [OruxMaps or Locus Map], or even remove the button altogether and simply write a comment.

**Comment by HarelM** [comment]
Nope, sorry, there's a difference when using this screen from a mobile device depending on which application you have installed, which is the main usage. Also there are instructions.

**Comment by ohadhawk** [comment]
@HarelM , now I understand that it's only the instructions that differ between the two applications.
I still think it is confusing because all the buttons appear on top of the download buttons, so one may think that the downloaded file is different.
I'd like you to consider moving the "Application" buttons down to the instructions region, below the download button.
Maybe something like:
[Instructions for OruxMaps users]   [Instructions for Locus Map users]

**Comment by HarelM** [comment]
One should not care about which done is downloaded as long as it works, right? Only advance users can check that and I assume advance users have read the manual...

**Comment by ohadhawk** [comment]
I'm not sure, it could be that others simply didn't bother to report it or tried downloading through the app.
I made the extra effort to report because I care.
BTW, I'm an iPhone user, I've only used it once on a burrowed device, so whatever you decide will not benefit me in any way in the future.
Anyhow, I will nudge you no further.

**Comment by HarelM** [comment]
@ohadhawk , I greatly appreciate the time you took and effort you made to report this issue, don't get me wrong, I just don't feel there's an issue to address here.
Please don't be discouraged, any input is valuable for us and we would very much like to receive reports of things that don't work as expected.
I hope you will continue using our site and contribute to the mapping community. :-)

**Comment by ohadhawk** [comment]
Thank you for listening, Harel.
