### ISSUE TITLE
Sync private layers do not update exiting layer

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1005]
## What I expect to happen
When updating a layer address or properties I expect it to be reflected on my other devices

## What really happened
The layer does not get updated

## What I did that caused the issue - step by step
1. Create a layer
2. Open my phone to see it
3. Change the layer on my desktop
4. Open my phone again

## My environment
* Operating System and version: any
* Web Browser and version: any

## Thing I think the developers should know, images, links etc.
Sync layer only checks if the layer exists and doesn't check if the layers are equal in their properties.

**Comment by HarelM** [comment]
Another issue this raises is the ability of another user to update my personal information.
If a user sends me a share that has the same layer name it currently uses the layer I have - but it breaks the share, changing this will allow other users to change my personal layer which I believe is worse.
I have don't have a good idea how to solve this...

**Comment by zstadler** [comment]
Proposal:
When someone else's share layer has the same name like an existing later, it will be renamed with an increment number. For example, if both have a layer "MyMap", then the share's layer will be renamed to "MyMap_1".

**Comment by HarelM** [comment]
I thought about it too, but then we'll have to take into consideration what happens when I open my own share... In any case, this requires a deep design to see that we don't miss any use case...

**Comment by HarelM** [comment]
Current fix only addresses the private layers update when editing from different clients (mainly editing from mobile and expecting it to be synced with desktop and vice versa).
I don't have a good idea how to solve the other issue and I'm not sure it's worth spending time to solve it.
