### ISSUE TITLE
Can't use north up when GPS is active

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1014]
## What I expect to happen
Click north up and the map should rotate to north and keep north up

## What really happened
I'm not entirely defined - probably a race condition related to animation

## What I did that caused the issue - step by step
1. Activate GPS
2. Click north up

## My environment
* Operating System and version:
* Web Browser and version:

## Thing I think the developers should know, images, links etc.
Need to check the animation options for this.

**Comment by HarelM** [comment]
The problem is probably the use of `moveend` as it will fire on every map move end even if it was not rotated, I'll try to change it to `rotateend` and see if it works...

**Comment by zstadler** [comment]
FYI, I noticed that the zoom buttons are also responding intermittently when the map is following the GPS, probably for the same reasons.
