### ISSUE TITLE
Maps don't switch language

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1015]
## What I expect to happen
When I hit English I expected the MTB amd IHM maps to switch language

## What really happened
ONly the interface language changed

## My environment
Chrome on web

**Comment by HarelM** [comment]
Can you please add steps to reproduce? I was not able to see the problem in the beta site.
Video would be even better...

**Comment by valleyofdawn** [comment]
Can't reproduce. closing.
