### ISSUE TITLE
MTB: Add legend for scrub

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1016]
## Bug
The MTB legend is missing entries for several areas
- [ ] industrial
- [ ] commercial
- [ ] grassland
- [ ] scrub

**Comment by valleyofdawn** [comment]
Commercial: 31.914486°, 34.805036° zoom 16
Industrial not needed - looks like residential
Scrub: 31.545975°, 34.886007° zoom 15
Maddow: 32.971403°, 35.848163° zoom 16

I think we should unite commercial industrial and residential
as well as scrub and meadow (leaving other types of grass solid green). 
The first is non-consequential for hikers & bikers
The second is not well differentiated in Israeli OSM tagging
What do you think?

**Comment by zstadler** [comment]
Meadow is already part of `area grassland` and does not need a new legend entry.

I agree with the consolidation suggestion. It deserves a separate issue in the Map repository. I also think there is no need for special background color for quarries and construction sites. The icons should be sufficient, just like cemeteries.

**Comment by valleyofdawn** [comment]
You currently use a icon pattern for quarries, not a single one in the trail map.

**Comment by HarelM** [comment]
@valleyofdawn @zstadler I'm not sure what to do here.
@zstadler I'm guessing @valleyofdawn won't implement this so either assign it to you or let me know exactly what to do. Thanks! :-)

**Comment by zstadler** [comment]
Closed in favor of https://github.com/IsraelHikingMap/Map/issues/239
