### ISSUE TITLE
POI / Routes on map don't disappear from map when turned off

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#1017]
## What I expect to happen
when clicking on the public POI / routes lines on the menu on the left in order to turn them off, they should disappear from the map.

## What really happened
They disappear from the map only after updating the map (zooming in/out or panning)

## My environment
chrom, win 10

**Comment by HarelM** [comment]
@oriori can you confirm that this bug is the same as #1013?
If so, please close this one.

**Comment by oriori** [comment]
same as #1013
