### ISSUE TITLE
delays when zooming in and out - only relevant from laptop

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#1018]
## What I expect to happen
zoom in and out smoothly

## What really happened
There is a slight delay when switching zoom levels. When using the scroll gesture on the laptop touchpad like thing (It's a Lenovo laptop), I guess the requests to zoom in or /out accumulate and there's a very noticeable and sometimes annoying delay. Moreover, sometimes when zooming out all the way, this causes the user to accidentally zoom out way more than needed. The result is a zoom level where the map isn't visible at all (since there are only tiles for Israel, which is a tiny dot at this zoom level). It is impossible to zoom back in unless there is some active marker currently on the map (like a route endpoints) to guide the user where to zoom back into. For me, the only way out of this situation was to load a shared route.

## What I did that caused the issue - step by step
Zoom in or out with the touchpad scroll gesture (slide two fingers up or down).

## My environment
Lenevo laptop.
* Operating System and version:
Window 10
* Web Browser and version:
Chrome

**Comment by HarelM** [comment]
@oriori not sure there's much I can do here.
Do you experience the same behavior here:
https://docs.mapbox.com/mapbox-gl-js/examples/
Did you use the beta site when reporting this bug?
https://israelhiking.osm.org.il/beta/

**Comment by oriori** [comment]
Yes, same experience in the mapbox example.
Yes, used the beta site.

Perhaps limit the zoom level so in cases when users zoom out too much (for
whatever reason) they won't get lost.

**Comment by HarelM** [comment]
The zoom level is defined to be 7 at minimum but the framework seems to ignore it... I can't find a way to force it.
In any case, you can search for anything and the map will zoom to that location in case you are "lost".
I don't see anything valuable I can do here, can I close this issue?

**Comment by oriori** [comment]
yes
