### ISSUE TITLE
new version doesn't support strava heatmap

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#1020]
## What I expect to happen
Strava heatmap to show on top of map

## What really happened
nothing

## What I did that caused the issue - step by step
Strava heatmap layer: https://heatmap-external-a.strava.com/tiles-auth/ride/bluered/{z}/{x}/{y}.png?v=18&px=256

## My environment
Win 10 , Chrome

## Thing I think the developers should know, images, links etc.
I took all the necessary steps for the heatmap to load (logged in to my Strava account, displayed the heatmap on the Strava website, etc.)

**Comment by HarelM** [comment]
See my comments in our Facebook group. Legally there's nothing I can do, sorry.
Closing...
