### ISSUE TITLE
Zoom mismatch between address bar and map tiles

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1027]
## What I expect to happen
The zoom level in the address bar to match the zoom level of the tiles
## What really happened
Tiles of zoom level 7 are shown when the address-bar zoom is [5.50](https://israelhiking.osm.org.il/map/5.50/31.1712/35.4524)-[6.49](https://israelhiking.osm.org.il/map/6.49/31.1712/35.4524)
Similarly, tiles of zoom level 8 are shown when the address-bar zoom is [6.50](https://israelhiking.osm.org.il/map/6.50/31.1712/35.4524)-[7.49](https://israelhiking.osm.org.il/map/7.49/31.1712/35.4524), etc.

## What I did that caused the issue - step by step
Click on the links embedded in the above description

## My environment
* Operating System and version: Win 10 home
* Web Browser and version: Firefox 66.0.5 (64-bit)

## Thing I think the developers should know, images, links etc.
Also compare [OSM](https://www.openstreetmap.org/#map=6/30.695/36.870) and [IHM](https://israelhiking.osm.org.il/map/6.00/30.6906/36.8696) with the same zoom/lon/lat:

![image](https://user-images.githubusercontent.com/1304610/57571982-9ab5f380-741d-11e9-8714-6af2b061bdcf.png)

![image](https://user-images.githubusercontent.com/1304610/57571971-82de6f80-741d-11e9-8a6c-342bc9e67c36.png)

[OSM](https://www.openstreetmap.org/#map=7/30.695/36.870) with zoom+1 and same zoom/lon/lat:

![image](https://user-images.githubusercontent.com/1304610/57572062-87efee80-741e-11e9-9752-cc6a59ce51aa.png)

_Note:_ the 3 screenshots are of equal size and location

It seems like the address bar reports the map zoom minus one.

**Comment by HarelM** [comment]
Please read about mapbox zoom level. I decided to use it instead of adding "-1" or +1 everywhere in the code.

**Comment by Orrgvili** [comment]
blurry labels on zoom 16 and below 
cleaned the cache and tried in different browser 
looks the same

**Comment by zstadler** [comment]
@Orrgvili, 

I do not see a difference in label clarity between a screenshot of [the map](https://israelhiking.osm.org.il/map/15.00/31.8519/34.8514):

![image](https://user-images.githubusercontent.com/1304610/57620153-965e1780-7590-11e9-87db-819471d1f6a4.png)

and a screenshot of [the source tile](https://israelhiking.osm.org.il/Hebrew/mtbTiles/16/39112/26645.png):
![image](https://user-images.githubusercontent.com/1304610/57620225-d3c2a500-7590-11e9-9775-8fea78f938f6.png)

Things to consider:
1. The highest resolution for the source tiles is 16, and the address bar **currently** shows zoom 15 when zoom 16 tiles are not scaled.
2. On some screens, such as the one I'm using, screenshots add some scaling. For comparison, below is the 1:1 image of the source tile, taken directly from the map server:
![image](https://israelhiking.osm.org.il/Hebrew/mtbTiles/16/39112/26645.png)

**Comment by Orrgvili** [comment]
little more blurry  
but you rare right they don't look good  also in zoom 15 
the smaller one are sometime  almost unreadable
when asked about it on FB  @HarelM  thought there is connection to this 
but maybe its need separate thread  
the labels don't looks good  in higher zooms wasn't like that in the older version before the change

**Comment by HarelM** [comment]
@zstadler I have uploaded a version to production that contains this fix, please see if I have missed a place where the zoom is used and it is now incorrect.
