### ISSUE TITLE
CORS-anywhere redirect for HTTP maps address limitation

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1028]
## What I expect to happen
The site would show external `http` map sources
## What really happened
When there are many map views of `http` maps, the `cors-anywhere.herokuapp.com` gateway pauses further processing for a while. As a result, the site does not show the external map source.

## What I did that caused the issue - step by step
View an external `http` map source extensively or when other users look at other external `http` map sources.

## My environment
* Operating System and version: Any
* Web Browser and version: Any

## Thing I think the developers should know, images, links etc.
Apparently, `cors-anywhere.herokuapp.com` has a 200 requests/hour limit per referrer. When that quota is exceeded, the sites returns a `429 Too Many Requests` error. The response body is:

> The origin "https://israelhiking.osm.org.il" has sent too many requests.
The number of requests is limited to 200 per 60 minutes. Please self-host CORS Anywhere if you need more quota. See https://github.com/Rob--W/cors-anywhere#demo-server

According to the above explanation, an instance of service can be configured to serve only request from a given site. Moreover,
> This application can immediately be run on Heroku, see https://devcenter.heroku.com/articles/nodejs for instructions. Note that their [Acceptable Use Policy](https://www.heroku.com/policy/aup) forbids the use of Heroku for operating an open proxy, so make sure that you either enforce a whitelist as shown above, or severly rate-limit the number of requests.

**Comment by HarelM** [comment]
I'm not sure if I understand the suggested solution, can you please elaborate?
Running the server on the Heroku cloud in not an option as it requires a lot of resources to migrate to their cloud...

**Comment by zstadler** [comment]
https://github.com/Rob--W/cors-anywhere#demo-server was referring to running a separate instance of the `cors-anywhere` code on Heroku, provided that this instance would enforce a whitelist. 

That whitelist could include just the IHM site.

**Comment by davidih** [comment]
I had (probably) the same problem with maps I store on AWS S3. I had to configure the CORS policy to allow the origin to return the "Access-Control-Allow-Origin" header. as explained here: https://aws.amazon.com/premiumsupport/knowledge-center/no-access-control-allow-origin-error/
It works fine now. However, it doesn't work with some map resources which are not in my control and don't have this CORS policy.

Example: Access to fetch at 'https://secais.dfs.de/static-maps/icao500/tiles/11/1225/830.png' from origin 'https://israelhiking.osm.org.il' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Needless to say: all worked fine before.

**Comment by zstadler** [comment]
@davidih,

This issue is about the quota limitations of the CORS gateway currently in use for accessing all `http`-based external map sources. The assumption is that we have no influence on the CORS configuration of external map sources.

If you change the above map source to `http://secais.dfs.de/static-maps/icao500/tiles/{z}/{x}/{y}.png`, the CORS gateway will handle it well:

![image](https://user-images.githubusercontent.com/1304610/58047649-4d3e3280-7b51-11e9-9bad-aefa8ee6277e.png)

Clearly, you may experience the quota issue

**Comment by HarelM** [comment]
Seems like there are other server we might able to use:
https://hackya.com/us/list-of-free-cors-proxy-server/
Not sure if any or all of them have the requests limitation...

**Comment by davidih** [comment]
There is always the option of running your own cors proxy server. See here: https://github.com/Rob--W/cors-anywhere
You can also easily open your own proxy server on Heroku. See possible solutions here: https://stackoverflow.com/questions/43871637/no-access-control-allow-origin-header-is-present-on-the-requested-resource-whe/43881141#43881141

**Comment by HarelM** [comment]
@davidih if you have a server that can run this code I can redirect the custom maps traffic to use this proxy, otherwise, as far as I can see, the free account of heroku probably won't be enough for the site's production needs...
I'll see if I can easily use our server and the proxy library we are using to handle this.

**Comment by davidih** [comment]
I don't have a server (only running some simple sites on S3). I really appreciate the wonderful work you are doing at IsraelHiking. I'm only trying to help since I see that there are questions on external maps in the FB page.

**Comment by HarelM** [comment]
@valleyofdawn @zstadler @davidih can any of you provide me with an address that does not support CORS? I would like to try out the code I wrote but the above example returns 404 - not found error on all tiles - might be that the address no longer exists...

**Comment by davidih** [comment]
Maybe this one: http://connecttile.garmin.com/ROAD_CYCLING/{z}/{x}/{y}.png

**Comment by HarelM** [comment]
This will not resolve https maps that do not support CORS, but maybe using the http address of those maps can be a work around. I can't further support this request without breaking copyright laws...

**Comment by manavbhikadiya** [comment]
> I had (probably) the same problem with maps I store on AWS S3. I had to configure the CORS policy to allow the origin to return the "Access-Control-Allow-Origin" header. as explained here: https://aws.amazon.com/premiumsupport/knowledge-center/no-access-control-allow-origin-error/
> It works fine now. However, it doesn't work with some map resources which are not in my control and don't have this CORS policy.
> 
> Example: Access to fetch at 'https://secais.dfs.de/static-maps/icao500/tiles/11/1225/830.png' from origin 'https://israelhiking.osm.org.il' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> 
> Needless to say: all worked fine before.

https://youtu.be/hxyp_LkKDdk i think this video link will helpful for you
