### ISSUE TITLE
Problem with POI update

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1029]
## What I expect to happen
POI update should always succeed

## What really happened
POI update fails due to problematic OSM elements.
The following is currently the know ones, they may change as OSM changes:
https://www.openstreetmap.org/relation/9523249 Self-intersection (34.7809052,32.0799861) 
https://www.openstreetmap.org/way/28525695 Self-intersection (34.7555575707254,32.0383827176217) 
https://www.openstreetmap.org/relation/2246907 is an empty geometry - check for non-closed relations. 
https://www.openstreetmap.org/relation/1638363 Self-intersection (34.915475,31.818752) 
https://www.openstreetmap.org/way/309426113 Self-intersection (35.389572271925,31.4707912453707) 
https://www.openstreetmap.org/relation/1637968 Nested shells (35.1536779,32.9814501) 
https://www.openstreetmap.org/relation/3791784 Ring Self-intersection (35.1654217,31.8896851)

## What I did that caused the issue - step by step
Look at the site log

## Thing I think the developers should know, images, links etc.
While some may be incorrectly mapped features some are valid feature which the conversion from OSM element to GeoJSON fails for them.
There's a need to look in the GeoJSON conversion code once more, and maybe remove those that can't be converted.

**Comment by HarelM** [comment]
https://www.openstreetmap.org/relation/9523249 - bad polygon merge of inner polygons in multipolygon.
https://www.openstreetmap.org/way/28525695 - needed to ignore construction highways in order to create a valid polygon.
https://www.openstreetmap.org/relation/2246907 - Incorrect check for multipolygon
https://www.openstreetmap.org/relation/1638363 - same as the first one

https://www.openstreetmap.org/way/309426113 - not sure what to do here as the merge is done between the tunnel and the rest of the path creating a polygon that intersects itself...

https://www.openstreetmap.org/relation/1637968 - Seems like the following is also making trouble in OSM as one of the inner rings is ignore, @zstadler can you help me with this one?

Added after the fixes:
https://www.openstreetmap.org/relation/3791784 - Ring Self-intersection (35.1654217,31.8896851) - not sure what to do here too - the relation is too complex for me to understand...

**Comment by zstadler** [comment]
> https://www.openstreetmap.org/relation/1637968 - Seems like the following is also making trouble in OSM as one of the inner rings is ignore, @zstadler can you help me with this one?

One of the relation members was missing an `outer` role.

**Comment by zstadler** [comment]
> https://www.openstreetmap.org/relation/9523249 - bad polygon merge of inner polygons in multipolygon.

This is a valid case of [touching inner rings](https://wiki.openstreetmap.org/wiki/Relation:multipolygon#Touching_inner_rings): "This is the one case where OpenStreetMap use deviates from standard OGC Simple Features."

> https://www.openstreetmap.org/way/28525695 - needed to ignore construction highways in order to create a valid polygon.

This way is currently not a member of any multipolygon relation. It is a member of two `type=restriction` turn-restriction relations that should not be considered for multipolygon.

> https://www.openstreetmap.org/relation/2246907 - Incorrect check for multipolygon

The relation type is `waterway=river` and should not be considered for multipolygon

>https://www.openstreetmap.org/relation/1638363 - same as the first one

This is a different case. Here is a case of illegal ["Overlapping, unclosed member ways belonging to the same role"](https://wiki.openstreetmap.org/wiki/Relation:multipolygon#Overlapping.2C_unclosed_member_ways_belonging_to_the_same_role). Attempted a fix in [changeset 70152679](https://www.openstreetmap.org/changeset/70152679)

> https://www.openstreetmap.org/way/309426113 - not sure what to do here as the merge is done between the tunnel and the rest of the path creating a polygon that intersects itself...

It is unclear to me why sections of `highway=path`, which are not part of a relation, and happen to have the same name, are merged into a polygon. If a merge is required, it it would be into a multi-line.

> https://www.openstreetmap.org/relation/3791784 - Ring Self-intersection (35.1654217,31.8896851) - not sure what to do here too - the relation is too complex for me to understand...

This is a problem of creating legal multipolygons where 3 relations interact. Area B relation has several occurrences of outer areas touching each other in 8-figure shape. Moreover, Area A is on the right side of the "8" and Area C on the left side. 

The way to map the "8" and adhere to the "Exactly two unclosed ways, and no more should share an endpoint" condition in [Valid Multipolygon conditions](https://wiki.openstreetmap.org/wiki/Relation:multipolygon#Valid_Multipolygon_conditions) of OSM is to use 2 lines, one for the A-B boundary and one for the B-C boundary. However, this is probably not a standard OGC Simple Features.

**Comment by HarelM** [comment]
I now see that I was not clear...
https://www.openstreetmap.org/relation/9523249 - I fixed this in my code using polygon merge of inner ploygons and outer polygons separately - can be seen in the related commit.
https://www.openstreetmap.org/way/28525695 - The merge algorithm doesn't only merge according to relations it also merges by name, ways that are touching each other ends (probably since a relation is missing) - in this case a construction way and regular way created a very sharp polygon which caused an issue when converting to geojson - see my comment below on the possible issue with how I handled it.
https://www.openstreetmap.org/relation/2246907 - Fixed the code that check if a relation is a multipolygon - see in the related commit.
https://www.openstreetmap.org/relation/1638363 - Although this is an invalid case as opposed to the first one, the fix that I made also applies to this. I'd be happy if someone will fix the OSM element though :-)
https://www.openstreetmap.org/way/309426113 - As described above lines are merged to bigger shapes - a shape that is closed is treated as a polygon and not a multiline, it might be a bug, not sure, might be worth brainstorming on it a bit.
https://www.openstreetmap.org/relation/3791784 - I don't have a good idea how to fix it and am planning on keeping this as a know limitation right now...

**Comment by zstadler** [comment]
Some OSM tags, such as landuse, are meant for areas and would be an error not to be closed. Others, like most `highway` tags, are meaningless as areas.

Given a list of OSM tags that are allowed into the merge algorithm, we can define which must be areas and would be an error not to be, and which should be treated as possible-closed multi-/lines.
