### ISSUE TITLE
Site doesn't work on Edge

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1032]
## What I expect to happen
I expect to see a functional site when opening IHM on Microsoft edge.

## What really happened
It shows the logo and 3 dots and that's it.

## What I did that caused the issue - step by step
Open Edge.
Type https://israelhiking.osm.org.il/ at the URL
watch.

## My environment
Windows 10 enterprise on a PC
Microsoft Edge 41.16299.15.0

## Thing I think the developers should know, images, links etc.
Edge represents only 0.9% of our users (based on google analytics), so it's not a big issue. We did deal with a FireFox problem though, with 1.4% usage share.

**Comment by HarelM** [comment]
I'll see what I can do, but there's no promise, edge is a shity browser and even if it will work it will broadly be too slow...
