### ISSUE TITLE
Arrow cursor displaces icons on vector maps

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1034]
## What I expect to happen
When locating current position or recording a track I expect the arrow cursor to appear above point features in the vector map

## What really happened
When approaching a point feature (e.g. a gate or a tap) it disappears as the arrow passes over it and reappears when you go past it.

## What I did that caused the issue - step by step
Opened vector map. Opened current location, went to the nearest point feature, observed it on the map.

## My environment
latest app on android
## Thing I think the developers should know, images, links etc.
At least regarding features on the  map < "icon-ignore-placement": true > solves this

**Comment by HarelM** [comment]
Thanks for the tip, I'll try and add `icon-ignore-placement` to the cursor image, let me know if this solved the problem.

**Comment by valleyofdawn** [comment]
Solved, thanks!
