### ISSUE TITLE
Recurrent error message regarding snapping POIs with no reception

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1037]
## What I expect to happen
When I try to add a private POI without connectivity (off the grid)  I expect it to appear on the map with no error messages, or at least with a single error message.

## What really happened
The message "לא ניתן לקבל מידע לטותה הצמדה" pops up repeatedly as the app tries to figure out if an existing public POI is there for the private one to snap to.

## What I did that caused the issue - step by step
Loaded a map. Turned off Wi-Fi and mobile data on the phone.
Added a private POI.
Watched things unfold.
Deleted POI or turned on mobile data.
Watched the error messages go away.

## My environment
IHM app version 8.0.309 on android

![image](https://user-images.githubusercontent.com/689201/57986753-ab9be000-7a81-11e9-91ef-797ec15ce238.png)

 This is easily reproducible but let me know if you need a log file.

**Comment by HarelM** [comment]
You can't expect the app that is not designed to work offline to work correctly, right?
Please close this issue and open it after we finish #783.

**Comment by valleyofdawn** [comment]
Okay, please remind me to reopen it in time.
I think though that adding **private** POI's' unlike viewing maps, should not be connectivity-dependent, works off-line in other apps, requires relatively little work compared to other offline issues and may frustrate other beta-testers. We need to provide a smoother experience when reception is sketchy at the beta stage. Just making sure that the error message appears once and not 50 times would be an improvement.
