### ISSUE TITLE
Allow {-y} in URL of external map source 

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1038]
## What I expect to happen
Mapbox infrastructure to maintain support for external sources with URL containing `{-y}`.

## What really happened
After the transition to Mapbox infrastructure, external sources with URLs containing `{-y}` are not shown.

## What I did that caused the issue - step by step
1. Switch to Anonymous mode
2. Open the developer window in network mode
3. Define a new source with the URL `http://geoserver.4castdemo.com/geoserver/gwc/service/tms/1.0.0/Med_Topo_Map@EPSG%3A3857@png/{z}/{x}/{-y}.png`
4. Inspect one of the requests from cors-anywhere and see that `{z}` and `{x}` in the URL were replaced with a number while `{-y}` remained as-is:
   > `https://cors-anywhere.herokuapp.com/http://geoserver.4castdemo.com/geoserver/gwc/service/tms/1.0.0/Med_Topo_Map@EPSG:3857@png/13/4891/{-y}.png`

## My environment
* Operating System and version: All
* Web Browser and version: All

**Comment by HarelM** [comment]
See mabpox documentation here:
https://github.com/mapbox/mapbox-gl-js/blob/master/src/style-spec/reference/v8.json#L153-L165
