### ISSUE TITLE
First openned route is removed when second route is oppened

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#104]
To reproduce:
1. Save the following text files as kml files:
[יום ראשון סוכות 2015.kml.txt](https://github.com/IsraelHikingMap/Site/files/16176/2015.kml.txt)
[יום שני סוכות 2015.kml.txt](https://github.com/IsraelHikingMap/Site/files/16175/2015.kml.txt)

2. Open the first KML and then the second kml.

The first route is gone, leaving behind only the POIs.

**Comment by HarelM** [comment]
This is happening since the name inside the kml file defining the name of the route is the same for both files (path) - thus the route gets overwritten. this does not happen for the markers.
What would you want the behavior to be in this case? create another route name path_1?

**Comment by zstadler** [comment]
Yes. 
The rational is that since the contents of the file are given, the collision is not caused by anything the user has control over.

I assume that with such a change, different routes can have the same name/label
