### ISSUE TITLE
עיצוב מסלולים על המפה - צבע, נקודות קצה

### ISSUE THREAD

**Issue by ronhl** [IsraelHikingMap/Site#1041]
## Feature
עיצוב המסלול על המפה

## What I expect to happen
אני משתמש הרבה מאד במפות כדי להציג מסלולים לאחרים, לעיתים מסלול יחיד ולעיתים קבוצת מסלולים (למשל כשיש כמה אפשרויות, או בטיול רב-יומי).
בדרך כלל ההצגה אינה אונליין על מחשב, אלא צילום מסך של המסלול או אזור המסלולים.
לצורך כך אני צריך שהמסלול יראה רציף, וללא סימונים מסתירים.

## What really happened
צבע המסלול - במקום קו רציף, הקו עכשיו מקווקו. לא ניתן לראות את המסלול כולו, אלא רק מתווה כללי.
מסלולים חופפים - כאשר יש שני מסלולים שחופפים בחלקם, הקווים שלהם מוצגים אחד מעל השני, ולכן ניתן לראות רק את העליון שבהם. בעבר אפשר היה לשלוט איזה מסלול יוצג מעל, אך עכשיו התוצאה היא מסלול לבן. בתמונה מוצג המסלול הסגול מעל הכתום:
![image](https://user-images.githubusercontent.com/42948764/58818415-90f76880-8636-11e9-941e-bf3651c2098b.png)
נקודות קצה - תחילת המסלול וסופו מסומנים בנקודות ירוקה ואדומה. גודל הנקודות הללו קבוע, ללא תלות בקנ"מ המפה. לעיתים אני צריך להציג מספר גדול של מסלולים, והתוצאה היא אוסף של נקודות לא ברורות (במיוחד שקווי המסלולים אינם רציפים).
![image](https://user-images.githubusercontent.com/42948764/58818596-f5b2c300-8636-11e9-89fc-19a76d278098.png)

## What I did that caused the issue - step by step
שום דבר מיוחד

## My environment
* Operating System and version: Win 10 home, Ver. 1809, build 17763.503
* Web Browser and version: כרום, גרסה 74.0.3729.131 (גירסה רשמית) (64 סיביות)

**Comment by HarelM** [comment]
תודה רבה על הדיווח!
יש כמה אי דיוקים בכמה שכתבת.
1. רק מסלול בעריכה נמצא כקו לא רציף - גם בעבר וגם היום, בעבר הייתה אנימציה ועכשיו יש חיצים, לדעתינו נושא כיוון המסלול הרבה יותר חשוב מהיכולת לעשות צילום מסך - אנחנו מאמינים שאנחנו בעידן מודרני, והדרך הנכונה מבחינתינן לשתף מידע היא ע"י יצירת שיתוף ולא ע"י צילום מסך, מה שגם יביא תעבורה חזרה לאתר.
2. לגבי מסלולים חופים, נבדוק מה ניתן לעשות
3. לגבי נק' התחלה וסיום, גם כאן החוויה לא השתנתה משמעותית, בעבר היו איקונים עם התחלה וסיום ועכשיו יש עיגולים. מבחינתינו הרבה יותר חשוב שאם אתה עושה זום-אאוט תוכל למצוא את המסלול בקלות ולכן גודל העיגולים לא משתנה עם רמת הזום.

כבכול פיצ'ר צריך לזכור שאנחנו מייעדים את האתר להרבה משתמשים ולכל אחד צרכים שונים, אני מאמין שמה שאתה מתאר הוא שימוש מאוד מתקדם באתר (בעיקר החלק עם ריבוי המסלולים) ואינו רלוונטי לרוב המשתמשים, אם מסתכלים על התמונה הגדולה.

**Comment by ronhl** [comment]
תודה על הפירוט.
נדמה לי שדווקא במצב עריכה המסלול מתואר כקו רציף, ובמצב תצוגה מופיעים החיצים והמסלול הופך ל"בלתי נראה" בחלקו:
![image](https://user-images.githubusercontent.com/42948764/58912802-97174300-8723-11e9-9ab6-364f2bc60678.png)

מצורפים שני צילומי מסך מלפני שנתיים וחצי:
![30 יגור-עוספיא](https://user-images.githubusercontent.com/42948764/58912059-e9576480-8721-11e9-9b94-53b77b7448f8.png)
![34 מנחל מערות לכביש 7021](https://user-images.githubusercontent.com/42948764/58912061-e9effb00-8721-11e9-8d2a-068b1dcdb916.png)
וצילום מסך חדש:
![41 מחדרה לבית ינאי](https://user-images.githubusercontent.com/42948764/58912089-fbd19e00-8721-11e9-8490-2e75b41cccf6.png)
רואים את ההבדל.
אני בהחלט מסכים שבעידן המודרני הדרך הנכונה לשתף מידע היא שיתוף. 
לצערי, הדרך הזו אינה רלבנטית בהרבה מאד מקרים - עם קהל מבוגר (או סתם מאותגר טכנולוגית), במצבי אוף-ליין, בשימוש עם ניירות ולא עם מכשיר צורך סוללות, כשצריך לקבע מסלול או לשמר אותו ועוד.
נקודות ההתחלה והסיום הן היבט נוסף של אותו דבר - לפעמים באמת צריך למצוא את המסלול בקלות (יש לכך אפילו לחצן יעודי בחלונית המסלול), אבל לפעמים מה שחשוב זה להציג את המסלולים (למשל על נייר או באוף-ליין), ואז מקבלים את התופעה כמו בצילום שצירפתי במקור.

שתי הבעיות שלי מעידות על כך שהצרכים שלי כנראה שונים מהצרכים של מרבית המשתמשים האחרים באתר (המצויין מכל בחינה אחרת).
נדמה לי שיחסית, קל מאד לבצע את ההתאמות שאני צריך - במקום להתאמץ ולהציג משהו מתוחכם (חצים בגודל שמחושב לפי רמת הזום, הצגת נקודות שמיקומן משתנה לפי הזום), פשוט לאפשר למשתמש לבחור להציג קו פשוט ונקי מהתחלה ועד הסוף. בחלונית המסלול יש היום אפשרות לבחור את צבע, שקיפות ורוחב הקו, ויש מקום להוסיף גם בחירה בין קו פשוט לאנימציה ובחירה האם לסמן את קצות המסלול (אפשר גם לפתוח דף של ברירות מחדל לאופציות השונות, שיהיה רלבנטי לכל המסלולים).
אבל - אני מבין שיחסית לצרכים של מרבית המשתמשים, אלו אפשרויות שאינן נדרשות יותר מדי.
כנראה אמשיך להשתמש באתר (שבאמת מצוין מכל בחינה אחרת) עם כל הבעיות (עבורי).

**Comment by ronhl** [comment]
ראיתי את העדכונים החדשים.
עדיין לא הגשמת כל החלומות שלי :), אבל עשיתם מאמץ גדול בכיוון.
תודה רבה.

בהזדמנות אחרת אשמח אם בחלונית המסלול תינתן אפשרות לבחור, בנוסף לצבע, שקיפות ורוחב הקו, גם אפשרות בחירה האם לסמן את קצות המסלול (אפשר גם לפתוח דף של ברירות מחדל לאופציות השונות, שיהיה רלבנטי לכל המסלולים).

ושוב, תודה רבה על הקשב למשתמשים ועל העבודה הגדולה שאתם עושים

**Comment by HarelM** [comment]
שמח שהעדכונים מוצאים חן בעיניך.
לצעיר, אני לא מוצא סיבה לסבך את ממשק המשתמש (שהוא גם ככה די מסובך) ואת שאר הקוד (שכן לא מדובר רק בתצוגה אלא גם בשמירה לקובץ וגם בעת שיתוף) בפיצ'רים איזוטריים כאלה.
השרשור על נושא כיוון המסלול וכמה הוא בולט נמצאים בקריאה הבאה: #1030 
מאחר ועיקר ההתייחסות פה מדברת על זה אני סוגר את הקריאה הזו לטובת הקריאה השניה.
אתה מוזמן להצרף לדיון שם - תוכל לראות שם את מגוון השיקולים שעומדים בפינינו בנושא הזה ובתקווה תבין למה הנושא לא פשוט כמו שהוא נשמע :-)
תודה רבה על הזמן והסבלנות!
