### ISSUE TITLE
samsung health  קובץ רכיבה מ

### ISSUE THREAD

**Issue by zoharw** [IsraelHikingMap/Site#1043]
## What I did that caused the issue - step by step
לא מצליח לפתוח, בדפדפן כרום באתר במחשב ובטלפון "המייצר" באפליקציה ובאתר בדפדפן כרום,  gpx - samsung health  קובץ רכיבה מ

הקובץ נפתח ללא בעיות בגיפסיס סטרבה ובגרמין קונקט , כלומר תקין.

  מהקובץ שהועלה לגיפסיס יצרתי קובץ חדש שמצליח להפתח ותקין באתר ובאפליקציה.
לא מצאתי איפה להעלות פה את הקובץ שניסיתי להעלות לאתר אז אשלח להראל דרך הפסייבוק
## My environment
* Operating System and version:
* Web Browser and version:

## Thing I think the developers should know, images, links etc.

[20190609_065229.txt](https://github.com/IsraelHikingMap/Site/files/3269946/20190609_065229.txt)

**Comment by zstadler** [comment]
Unfortunately, the file has errors which makes it an illegal GPX file:

1. `metadate` is not a valid GPX tag

   ```
   <metadate>2019-06-09T03:52:30Z</metadate>
   ```
2. `exerciseinfo` is not a valid GPX tag

   ```
   <exerciseinfo>
     <exercisetype>11007</exercisetype>
     <distance>59838.74</distance>
     <elevationgain>534.4314</elevationgain>
     <avggradient>0.009005045565643162</avggradient>
     <duration>13953610</duration>
     <avgspeed>4.2885933</avgspeed>
   </exerciseinfo>
   ```

The Israel Hiking Maps site does not import illegal GPX files.

The GPX schema defined a simple proper way to extend it. However, Sumsung Health chose not to use that.

**Comment by HarelM** [comment]
I've opened a ticket to Samsung health.
I do not wish to start hacking the GPX file reader in order to make it work for this case, running the file though another site to create a valid GPX file that our site can read is a decent workaround.
I'm tending towards closing this issue.

**Comment by HarelM** [comment]
פתחתי קריאה לסמסונג, מקווה שהם יתקנו את זה.
אתה מוזמן לפתוח להם קריאה גם דרך האפליקציה אולי זה יגרום להם לתקן את זה יותר מהר...
אין לי איך להמשיך עם הקריאה הזו, מצטער...

**Comment by HarelM** [comment]
Seems like this will be fixed in next release as it caused the server to hang.
