### ISSUE TITLE
The Back button no longer exits

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1047]
## What really happened
When the back button is pressed, the app reloads instead of showing the message "press back again to exist"

**Comment by HarelM** [comment]
I have opened a ticket here, I hope they can direct me to the right approach.
https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/388

**Comment by zstadler** [comment]
Note that the message "Wrapping things up, please wait a few seconds..." no longer appears after the second press of the back button.

**Comment by HarelM** [comment]
It depends on the time it takes to wrap things up. Both messages appear, I have checked it several times.
