### ISSUE TITLE
שיתוף קובץ מסלול מאפליקציית האנדרואיד

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1054]
## What I expect to happen
כאשר לוחצים על אייקון שיתוף באפליקציית האנדרואיד, 
שניתן יהיה לשתף את קובץ הניווט עצמו בפורמטים שיש בתוך ה
Save As
יאפשר פתיחת מסלולים גם באפליקציות אנדרואיד אחרות כמו למשל
Garmin Connect, Trailze...

## What really happened
כרגע כאשר לוחצים על אייקון שיתוף באפליקציית האנדרואיד, עולה רק אפשרות לשיתוף לינק

## My environment
* Operating System and version:  אפליקציית אנדרואיד IHM

**Comment by HarelM** [comment]
תודה רבה על הפנייה.
עם זאת, זו אינה מטרת כפתור השיתוף.
באפשרותך לשמור את הקובץ בפורמט הרצוי ולשתף אותו בכל צורת שיתוף שהפלאפון מאפשר - מייל וואצאפ וכו'.
מטרת כפתור השיתוף היא שיתוף האפליקציה ולא רק המסלול

**Comment by HarelM** [comment]
No response was received for a week. Closing this issue.
