### ISSUE TITLE
 statistics graph accumulative height

### ISSUE THREAD

**Issue by olevi70** [IsraelHikingMap/Site#1055]
## What I expect to happen
when marking part of the height graph for sub-track statistics, i expect the point that travels on track (on map) and marking current track position according to position on height graph, to move along with the mouse movement over the height graph

## What really happened
the point on track disappear as soon as starting to mark part of the height graph.
I am definite that somewhere in the past, point indeed traveled on track while marking height graph 

## What I did that caused the issue - step by step
always happens with any track and any browser

## My environment
* Operating System and version: win10
* Web Browser and version: firefox 68.0.1, chrome 76.0.3809.100

**Comment by HarelM** [comment]
Thanks for reporting! It did used to work in the past. We'll take a look at it and keep you posted.

**Comment by HarelM** [comment]
@olevi70 the fix was published to the site. Thanks for reporting this!
