### ISSUE TITLE
 שם שדרה מוצג פעמיים באופן פחות קריא

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1056]
## Bug
שדרה המסומנת בשני קוים במפה אחד לכל כיוון
רואים את שם השדרה פעמיים באופן שגראפית לא נוח - ראה קובץ מצ"ב

![Capture](https://user-images.githubusercontent.com/49042192/63215861-70b75000-c135-11e9-8ecb-23ac3a8821a1.JPG)

## What I expect to happen
שיראו רק בכיוון אחד

**Comment by HarelM** [comment]
Closing, moved the Map's repository:
https://github.com/IsraelHikingMap/Map/issues/240
