### ISSUE TITLE
Road name not presented for "Primary Road"

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1057]
## Bug

See capture and highlight:

![Capture](https://user-images.githubusercontent.com/49042192/63215926-5336b600-c136-11e9-9a04-3ac5c4b4cea7.JPG)

## What I expect to happen
That its name will show

**Comment by HarelM** [comment]
Closing, moved the Map's repository:
IsraelHikingMap/Map#241
