### ISSUE TITLE
Is there a way to copy layer definitions?

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#106]
A few scenarios come to mind:

1. A person uses Israel Hiking on two different machines
2. A person migrating from www.osm.org.il/IsraelHiking to IsraelHiking.osm.org.il
3. A person uses different browsers on the same machine, say for testing Israel Hiking compatibility

**Comment by HarelM** [comment]
Can't really be done right now.
If this is something we want to do maybe we can use the short url to store all the user data to the database. This is a lot of work though for something that I'm not sure will be in use...

**Comment by HarelM** [comment]
Layers definition can now be viewed using new settings - assuming you don't have too many layers, copying by hand should be reasonable.

**Comment by zstadler** [comment]
Copying layer definitions can be done by sharing. 
The name of the layer can be modified on the receiving side using the layer's advanced mode.
