### ISSUE TITLE
Improving the track merge icon

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1065]
## What I expect to happen
The current icon for merging 2 tracks is a "+" sign. In this context, it is a bit unclear and ambiguous as it may suggest adding something to the track. Instead, I suggest using an icon like Android's phone call merge icon. 

I found two examples, and I'm quite sure there are plenty more:

1. [merge_type icon](https://material.io/resources/icons/?icon=merge_type&style=baseline) from material design: 
![](https://fonts.gstatic.com/s/i/materialicons/merge_type/v1/24px.svg?download=true)
2. Vespucci's [merge action icon](https://github.com/MarcusWolschon/osmeditor4android/blob/master/src/main/res/drawable-xhdpi/ic_action_merge_holo_light.png):
![](https://raw.githubusercontent.com/MarcusWolschon/osmeditor4android/master/src/main/res/drawable-xhdpi/ic_action_merge_holo_light.png)

**Comment by HarelM** [comment]
![image](https://user-images.githubusercontent.com/3269297/65456479-160ac580-de52-11e9-98a4-756ff84fd974.png)
