### ISSUE TITLE
Map would not zoom to max_zoom

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1066]
## What I expect to happen
The site to use tiles of the maximal zoom level possible

## What really happened
Tiles of maximal zoom level are never shown, even in over-zoom-in levels. For example, tiles of zoom level 16 are never used in the Hiking and Biking maps.

## What I did that caused the issue - step by step
1. Open a new private/incognito tab
2. Open the developer tools and choose its network tab. On Chrome, also select "Hide data URLs"
4. Open the [hiking map in zoom 18](https://israelhiking.osm.org.il/map/18.00/31.9312/34.9465) in the private/incognito tab

The network log shows that zoom level 15 is used instead of zoom 16 to show the map in zoom 18
![image](https://user-images.githubusercontent.com/1304610/65491337-85ff6700-deb7-11e9-87ea-267fa3477e2e.png)

## My environment
* Operating System and version: Win 10
* Web Browser and version: Firefox and Chrome

**Comment by HarelM** [comment]
I'm really confused about the zoom and max zoom stuff related to Mapbox...
When I tried to manually change the following line in the site from the console window it worked as expected and I got the zoom 16 tiles:
https://github.com/IsraelHikingMap/Site/blob/677f0c56d75ac5fe3a97d6717b222f8e88be2c8a/IsraelHiking.Web/sources/application/components/map/automatic-layer-presentation.component.ts#L95
I'm not sure if I need to remove the `-1` or not...
I can remove it and see what happens...
Any thoughts?

**Comment by HarelM** [comment]
Published.
@zstadler please make sure this works as expected, I have little faith in the fix I made...

**Comment by zstadler** [comment]
Everything seems o work just fine.

Thanks for the fix!
