### ISSUE TITLE
Run in Firefox Incognito mode

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1067]
## What I expect to happen
Be able to run in Firefox Incognito mode

## What really happened
Site will not complete its initialization.

## What I did that caused the issue - step by step
Open the site in Firefox incognito mode

## My environment
* Operating System and version: Win 10 Home
* Web Browser and version: Firefox 69.0.1 (64-bit)

## Thing I think the developers should know, images, links etc.
It seems like opening indexedDB fails in Firefox private mode

![image](https://user-images.githubusercontent.com/1304610/65837488-ab99cf80-e300-11e9-82da-ec34f4260de3.png)

Potentially relevant issues:

- PouchDB closed issue https://github.com/pouchdb/pouchdb/issues/740
- Firefox 3 year old bug https://bugzilla.mozilla.org/show_bug.cgi?id=781982

If there is no way for the site to work in Firefox private mode then please show a clear message. See [an example code](https://bugzilla.mozilla.org/show_bug.cgi?id=1506680#c6) that tests if opening the DB is successful

**Comment by HarelM** [comment]
I don't think I can fix Firefox. The site relays heavily on IndexDB.
Planning to add an alert to show the error, It will also help users app users to let us know why the initialization failed, I hope...

**Comment by HarelM** [comment]
There has been around 5 FF private mode report from different users.
There should be a clearer error message indicating FF private mode is not supported and that the user should use another browser/mode.
I'll reopen this.
The correlation between FF private mode users and how many of them are reporting bugs is amazing :-)
