### ISSUE TITLE
track failed to download due to waypoint

### ISSUE THREAD

**Issue by olevi70** [IsraelHikingMap/Site#1069]
## Bug
adding manual waypoint on existing point data copies that data to the new local waypoint.
If there is a hyperlink as part of that info when deleting the web address its impossible to save the track.

## What I expect to happen
track to download

## What really happened
error message received when saving the track

## What I did that caused the issue - step by step
here is an example sequence to recreate issue:
1. add waypoint at 32.87993°, 35.49525° (newly added waypoing at Hukuk "קו אופ" )
2. delete web address from waypoint "web" field.
3. try saving the track

## My environment
* Operating System and version:
* Web Browser and version:
recreated on firefox, Chrome and Opera

**Comment by HarelM** [comment]
Thanks for reporting this issue.
We are experiencing issues with the server in the last few days.
By saving do you mean click the save button? because if so, I'm unable to reproduce the issue.
Can you test it now and see if this issue still reproduces?

**Comment by olevi70** [comment]
still same issue, unable to save the track
took me a while to pinpoint the issue but this is consistent on more than one desktop, on every browser i used

![2](https://user-images.githubusercontent.com/38877633/66030389-e884e280-e509-11e9-9036-a9af08b4e3dc.jpg)
![1](https://user-images.githubusercontent.com/38877633/66030390-e884e280-e509-11e9-86b0-50592097beff.jpg)

**Comment by HarelM** [comment]
If you click the trash icon and then save, it works, right?
The problem might be that there's a link but the address is empty so the link is invalid.
A bug, nevertheless, but a workaround exists...

**Comment by olevi70** [comment]
indeed, once the waypoint is deleted everything works fine.
I agree with the "missing-link" observation
and the WA is very easy, subject that you know what is the problem

I had a long track with dozens of waypoints when hitting the issue.
it was not straight forward to understand this

**Comment by HarelM** [comment]
The fix will prevent from future mistakes, it won't fix existing problems if any exist.
Thanks a lot for pinpointing the problematic scenario!
