### ISSUE TITLE
Large fonts on android

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1070]
## What I expect to happen
App should look good regardless of phone settings or browser

## What really happened
App looks bad when setting large text in accesibility of an android device

## What I did that caused the issue - step by step
1. Go to phone settings
2. Set text size to max
3. Open the app

## My environment
* Operating System and version: android 8
* Web Browser and version: N/A

## Thing I think the developers should know, images, links etc.
There's an accessibility plugging for Cordova that can help with this.

**Comment by HarelM** [comment]
The following is the relevant plugin:
https://github.com/phonegap/phonegap-mobile-accessibility
Apparently it's abandoned... :-/
Looking at the issues I doubt it will work with Cordova 9.0:
https://github.com/phonegap/phonegap-mobile-accessibility/issues/47

**Comment by valleyofdawn** [comment]
![image](https://user-images.githubusercontent.com/689201/70371168-739ea200-18d8-11ea-8307-cfd951a90eaa.png)
![image](https://user-images.githubusercontent.com/689201/70371172-831deb00-18d8-11ea-8e33-1261b1b8bd09.png)

**Comment by HarelM** [comment]
The following fork might do the trick, I hope:
https://github.com/artifacthealth/phonegap-mobile-accessibility
@meirgottlieb Not sure if you are the owner of this, but in case you are, do you know if this plugin works with Cordova 9.0?
