### ISSUE TITLE
Noisy elevation signal

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1076]
## What I expect to happen
When recording a track, I expect the real-time elevation data presented in the height profile to approximate reality.

## What really happened
The height signal is very noisy, showing high frequency noise with an amplitude of 20 m’ and occasional outliers, and producing inflated figures for cumulative descent and ascent. 
Example
https://israelhiking.osm.org.il/share/UevXT3SPft

## What I did that caused the issue - step by step
Recorded a track in sub-optimal GPS reception (e.g. a forest).

## My environment
App (current public beta version) on  Xiaomi Redmi note 7 android phone

## Thing I think the developers should know, images, links etc.
Other apps working in parallel produce a smoother curve.
Possible solutions:
1)	Rely on DEM data instead of GPS data for elevation (maybe only in barometer-free phones)
2)	Apply a smoothing algorithm (moving average over 2 minutes maybe)

**Comment by HarelM** [comment]
I have no intentions of fixing this. I can stop showing elevation if the data is not good enough.
DEM is using 1GB of ram on the server so it's not an option.
Some averiging is already made to present the graph, I don't see a good reason to change this.
Showing what the device measured is important, IMHO.
I'm tending towards clothing this issue.

**Comment by valleyofdawn** [comment]
If you have no intentions to fix it than close it. I think that for people who care about their elevation gain it's more important that it's accurate than that it represents what the device is measuring, the overshoot can be very significant.
