### ISSUE TITLE
Problem sending issue report

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1077]
## What I expect to happen
Report should open mail client

## What really happened
Nothing

## What I did that caused the issue - step by step
1. Record a route
2. try to send a report.

## My environment
* Operating System and version: Android galaxy s8.
* Web Browser and version: N/A

## Thing I think the developers should know, images, links etc.
This does not happen if data is clean so it might be a problem with file size...

**Comment by HarelM** [comment]
The reason for this is caused by non Latin characters.

**Comment by valleyofdawn** [comment]
Works for me too now,

**Comment by HarelM** [comment]
@valleyofdawn which version are you using? version 8.0.450 has this fix and I have uploaded it this morning. Is this the version you are using?

**Comment by valleyofdawn** [comment]
Yes it is

**Comment by valleyofdawn** [comment]
Stopped working again. Same symptoms.
Version 8.0.450 of the app.

**Comment by HarelM** [comment]
Please provide full steps to reproduce.
I'm not able to reproduce the problem using the previous steps, i.e.:
1. Find gps location
2. Start recording
3. Stop recording
4. Click report an issue.

**Comment by valleyofdawn** [comment]
You are right, there is no problem after recording a route. 
When no route was recorded nothing happens. Maybe the user should be notified to expect nothing if this is intended.

**Comment by HarelM** [comment]
@valleyofdawn I don't understand.
Please simply write the expected behavior, current behavior and steps to reproduce.
Much like the template of an issue.
If the steps to reproduce in this issue does not match, please open another issue and close this one.

**Comment by valleyofdawn** [comment]
Couldn't re-create the bug after app data was cleared. Closing.
