### ISSUE TITLE
Problem with incorrect OSM to GeoJSON conversion

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1078]
## What I expect to happen
Features such as streets should not be converted to polygons

## What really happened
Some closed streets are converted to polygons which later causes merge warnings

## What I did that caused the issue - step by step
Part of the merging algorithm for search and POIs.

## Thing I think the developers should know, images, links etc.
It's worth noticing that the following conversion exists also in OSMSharp and it might be better to use it instead of using the current code or updating the current code.
Current code:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.API/Converters/OsmGeoJsonConverter.cs
OSMSharp:
https://github.com/OsmSharp/core/blob/develop/src/OsmSharp.Geo/DefaultFeatureInterpreter.cs

It's worth noting that it might not be possible to use OSM Sharp code due to the new issues with NTS and `CoordinateZ` class, but it might be a good idea to get some inspiration from there...

@zstadler I would appreciate if you could take a look at OSMSharp's code and let me know if the tags there seems correct to you in terms of what should be an area and what shouldn't be and if you think it cover most area elements.

**Comment by zstadler** [comment]
@HarelM ,
This is the standard approach when looking at closed ways and the tag list seems OK. The code also gives higher precedence to the [`area` tag](https://wiki.openstreetmap.org/wiki/Key:area), therefore allowing an override of the default behavior for specific map elements.

**Comment by HarelM** [comment]
Current implementation seems to be good enough for most cases.
I'll add relevant tags if I see that they help in conversion. 
Currently I don't see a value in this approach worth the risk of changing the converter.

**Comment by zstadler** [comment]
The solution proposed by @HarelM may also be useful for addressing #1203.
Let's have a discussion.

**Comment by HarelM** [comment]
I don't see how the two are related. If fixing #1203 will require a change in osm conversion to geojson so be it, but there's no reason to keep both issues open in any case.
Please close this one.
