### ISSUE TITLE
Support heatmap URL in custom overlays

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1079]
## Feature
A Facebook post has brought up the idea of showing information that is not tiled based but information based that will be able to create a heatmap.
The idea is related to cellular reception, but I don't see a limitation here.
Here's the relevant info related to mapbox implementation:
https://docs.mapbox.com/mapbox-gl-js/example/heatmap-layer/
A proposed schema for the url will be:
`heatmap://url-to-geojson-file` where the geojson file has to have features with a property of `value` with the relevant value.

**Comment by zstadler** [comment]
It will be nice if the site would be able to show GeoJSON sources in addition to showing a heatmap created by them.

**Comment by HarelM** [comment]
Please propose a schema for the url and a default presentation/convention for the data. Either in this issue or open a different one, whichever you prefer.

**Comment by Moshe81** [comment]
Hi,
So here are some ideas.
1. From the WebSite https://www.opencellid.org/downloads.php I was able to download 1 Gb of data regarding the Cell data in the world. I am attaching only the part that I record as an example of how the data is being stored on CSV file 
[OCID-diff-cell-export-2019-10-30-T000000.csv.gz](https://github.com/IsraelHikingMap/Site/files/3791443/OCID-diff-cell-export-2019-10-30-T000000.csv.gz)

Here is example of 3 lines:
radio,mcc,net,area,cell,unit,lon,lat,range,samples,changeable,created,updated,averageSignal
LTE,310,410,17664,77685263,0,-90.214894,44.618373,13347,4,1,1547678835,1572389675,0
GSM,262,3,11060,46509,-1,9.889202,53.609156,9411,605,1,1547659267,1572361103,0
LTE,310,410,17664,77685270,0,-90.271622,44.618251,17834,4,1,1547679174,1572389716,0
The important parameters are 
Radio : LTE is strong and GSM is poor
Lon, Alt - for Location
Unit - the strength of the signal

Other Application line Network Cell Info - 

Option 2)
Harel upload this link with a Layer of Cell reception https://israelhiking.osm.org.il/share/ZkKbBdUXJv?fbclid=IwAR3TnTd6Rl7nYVN7kSxk_1ofoFMM1K2RkUluFXQz2Ew49qQw7uvReuqJ8Kw

That looks  great - the question where the data is coming from and how we can contribute to collect and update the data in places without data

Option 3) I see some apps updating the Mozilla MLS respective site - I still need to check if its free and how its being update and if we can use it.
Moshe

**Comment by HarelM** [comment]
I now see that OpenCellID has a heat map, I'm not sure I fully understand the coloring but it is what it is.
Here's a link to it:
https://israelhiking.osm.org.il/share/KsrN3ObWUU
The data is open, much like OSM, as you figured it out, and I think this is the best option.
Open data can be later used and processed to each one's needs, but in general I think it is the best approach.
If the heatmap isn't great it can be improved much like what we did with the OSM map tiles.

**Comment by zstadler** [comment]
Great find!
From what I checked, for this source min_zoom=0 and max_zoom=10

**Comment by zstadler** [comment]
Earlier in this thread I wrote:
> It will be nice if the site would be able to show GeoJSON sources in addition to showing a heatmap created by them.

In retrospect, I believe JSON sources are irrelevant to this issue. If and when they are supported, they should be treated similarly to GPX, and KML/KMZ.

**Comment by Moshe81** [comment]
Harel,
Indeed this is a great find ? (How do you find all this secret layers??)
So when we talk about Cell coverage there are few properties which can effect the map.
1) What type of connection ? LTE/3G/2g/Emrgency only  for each one of the there could be a diffrent heat map
2) who is the provider - We can have different coverage for Cellcom then to Pelephon
3) For each Provider and network the signal is not only True or false but messured by it strength - so -110 is very bad a -70 is very good. 

Some web site like this (https://www.cellmapper.net/map?MCC=425&MNC=2&type=LTE&latitude=31.65714894416712&longitude=35.337766210099566&zoom=12.630788975435191&showTowers=true&showTowerLabels=true&clusterEnabled=true&tilesEnabled=true&showOrphans=false&showNoFrequencyOnly=false&showFrequencyOnly=false&showBandwidthOnly=false&DateFilterType=None&showHex=false&showVerifiedOnly=false&showUnverifiedOnly=false&showLTECAOnly=false&showENDCOnly=false&showBand=0&mapType=undefined&showSectorColours=true#)  allow you to filter for Radio type and provider before showing you the map. 

So I am also trying to understand what doe the heatmap you sent is representing - can you tell me where did you find it so I will try to dig on that website?
https://israelhiking.osm.org.il/share/KsrN3ObWUU

**Comment by HarelM** [comment]
I basically followed your lead - I googled OpenCellID and got to this site:
https://www.opencellid.org/#zoom=16&lat=37.77889&lon=-122.41942
Clicked F12 to view the network tab.
Moved the map a bit until I found the right image getting fetched, and from there I went to the site and tried all kinds of addresses until it worked, i.e.:
`http://opencellid.org/images/maps/opencellid/{z}/{x}/{y}.png`
![image](https://user-images.githubusercontent.com/3269297/67977267-6c70de00-fc20-11e9-9f0b-d1dcf3a7a3bb.png)
Feel free to continue the investigation.
There are sites for which this is their focus, I don't think that the focus of this site should be cellular reception.
Having said that, there's nothing stopping you from finding the right tiles and create overlays with the relevant name to toggle on or of (i.e Cellcom cellular heatmap, Orange cellular heatmap, etc...) and share with other users.

**Comment by HarelM** [comment]
@zstadler I think `.geojson` file is supported as a way to open a route (much like GPX), I haven't checked it lately, but I remember it is supported...

**Comment by Moshe81** [comment]
Harel,
I tried to do the same for this web site https://www.cellmapper.net/map?MCC=425&MNC=2&type=LTE&latitude=31.655199308090246&longitude=35.22662570079173&zoom=16.342994763479595&showTowers=true&showTowerLabels=true&clusterEnabled=true&tilesEnabled=true&showOrphans=false&showNoFrequencyOnly=false&showFrequencyOnly=false&showBandwidthOnly=false&DateFilterType=None&showHex=false&showVerifiedOnly=false&showUnverifiedOnly=false&showLTECAOnly=false&showENDCOnly=false&showBand=0&mapType=undefined&showSectorColours=true

But it seems like it send some API for each tile and then create it and its not a ready tile.
Can you take a look ?
https://api.cellmapper.net/v6/getTile?MCC=425&MNC=2&RAT=LTE&z={z}&x={x}&y={y}&band=0

**Comment by HarelM** [comment]
Use the following share. I can't write what I did since the method I used to solve it shouldn't be public knowledge, sorry.
https://israelhiking.osm.org.il/share/XANzmqOlTK

**Comment by Moshe81** [comment]
Hi Guys,
So far I used the CellMapper app and the layer that Harel Created for me and its very good - but will be slow to get lots of data.
I contact Adam Zamojski <mail@zamojski.info> he is the developer of the application Tower Collector https://play.google.com/store/apps/details?id=info.zamojski.soft.towercollector&hl=en 

And I tried to ask him how we can easely use the data that his application collect and add to the OpenCellID.org and Mozilla Location Services.
So Adam would be happy to learn how he can use the data on such a platform like the OSM - can we help him with that ?

**Comment by HarelM** [comment]
@Moshe81 I'm not sure what you suggest here... The data is collected and is open. There's a heatmap that is created from the data, and you can see it in IHM site.
This data should not be part of OSM the way I see it, much like whether shouldn't be part of OSM...
Can you elaborate on what you think is still missing...?

**Comment by HarelM** [comment]
This should in theory be supported using the infrastructure we added to support mapbox json style file as all the information can be defined in the style file - sources (geojson file somewhere in the internet and heat map layer/s).
@valleyofdawn I think this is worth a post, it's a nice feature if you can make it work :-)
See here for instructions of what needs to be defined in mapbox style for this to work:
https://docs.mapbox.com/mapbox-gl-js/example/heatmap-layer/
