### ISSUE TITLE
Seperating my activities from my routes

### ISSUE THREAD

**Issue by Kaplaboa** [IsraelHikingMap/Site#1080]
## Feature
I suggest clear sepration between recorded activities and between any other routes. I think the best way is to follow other tracking apps:  you can see activities which you tracked and recorded their gps data in one place. And other routes/tracks that either were uploaded or designed within the app in a different place.
I suggest also when you upload  to the app, gpx file(or any other forma that has timing data) you can either upload it as an activity you did or as a route that that you want to use for other mapping or follow route purposes. 
## My environment
* Operating System and version:android app
* Web Browser and version:

**Comment by HarelM** [comment]
@Kaplaboa Can you please share some screen shot from other app which you find useful and easy to use?
Please note that this app allows route planning which is not the case in most outdoor activity apps.

**Comment by Kaplaboa** [comment]
Clearly the main and greatest advantage of IHM is the route plannig, no
doubt about that.
Still my opinion, seperating between your activity log and planned routes
will make things easier and more useful for the users

Two examples from other sport apps:
Runtastic (now adidas runing) you can see your activity history (mostly
recorded but upload of gpx file with time data was also possible in the
past) or you can choose route from your routes to show (and follow) on the
map (routes planning was very limited to converted gpx file).
Another example is the most popular Strava. You can see your records
activity feed. But when you start new record you can select any of your
saved routes to see and follow on the map. Again routes are very limited to
gpx upload or convert activity into route.

An app that will combine nevigatoin/routes planning and a history record of
your own activities, is something I'm waiting for since my first galaxy
S2...

Hope it is clear
Thanks
Boaz

**Comment by HarelM** [comment]
@valleyofdawn, since this is important to you please add how you think the user experience should change, what windows should be and other UI/UX stuff, to explain. The description/discussion above is too vague for me and I can't think of a proper way to solve this beside what is currently implemented - in your profile you have recording and sharing which is what I understand of the above requirement.

**Comment by Kaplaboa** [comment]
היי הראל וגיא
לא בטוח שאני הנשאל (כנראה שלא), אבל מכיוון שזה חשוב גם לי אני אענה( הפעם
בעברית)
כמו שאני רואה זאת, בנוסף לכפתור "המסלולים שלי" שכבר קיים היום, צריך להיות
כפתור ה"הקלטות שלי" או "הפעילויות שלי".
1.ההקלטות ב"פעילויות שלי" אינן מוצגות על המפה כברירת מחדל
2. כאשר נכנסים להקלטות ולוחצים על פעילות ספציפית  שעשינו והקלטנו נפתחת מפה
עם המסלול המוקלט + הנתונים כמו משך/מרחק /מהירות/גובה מצטבר וכו'
3. ניתן להמיר הקלטה למסלול ואז אפשר יהיה להציג אותה יחד עם מסלולים אחרים,
ולהשתמש בזה לעריכת מסלול או עריכת מפה בדיוק כפי שזה פועל עכשיו.

משהו כזה

שבת שלום וישר כוח
בועז קפלן

**Comment by HarelM** [comment]
אבל זה כבר קיים היום:
![image](https://user-images.githubusercontent.com/3269297/70773473-3aef4480-1d80-11ea-96ec-06aac3b62e10.png)
יש הפרדה בין הקלטות שנעשו ע"י האפליקציה או הועלו כהקלטה לבין שיתופים שזה בעיקר תכנונים או קבצים שפתחת ושיתפת.
יכול להיות שאני מפספס משהו...

**Comment by HarelM** [comment]
@Kaplaboa Can I close this issue?

**Comment by Kaplaboa** [comment]
Please wait, I will give my last reply soon...
Thanks
Boaz

**Comment by Kaplaboa** [comment]
You can close it
SHBAT SHALOM
BOAZ
