### ISSUE TITLE
שרטוט מסלול לא עובר דרך חנייה

### ISSUE THREAD

**Issue by amiad** [IsraelHikingMap/Site#1081]
## What I expect to happen
נסיתי לתכנן מסלול שעבר דרך חנייה (אזור עם תגית amenity=parking) והשרטוט עבר מסביב.

## What really happened
המסלול יעבור דרך חנייה

## Thing I think the developers should know, images, links etc.
https://israelhiking.osm.org.il/share/1BHwwUGvpY

**Comment by HarelM** [comment]
<div dir=rtl>
אני לא חושב שיש לי איך לתקן את זה...
הניווט מתבסס על GraphHopper ואני ממש בספק אם הם יסכימו לפתור את הבעיה הנ"ל.

ניווט דרך איזור חניה ולא דרך דרכים לא נתמך וזה לא ממש מפתיע...
אני חושב שכדאי להוסיף כבישים, דרכי עפר או שביל הולכי רגל בתוך החניה על מנת לאפשר ניווט במקרה הזה.
כך התמונה נראית בעורך של OSM:

![image](https://user-images.githubusercontent.com/3269297/68800172-3f7deb80-0662-11ea-8338-116f03e83405.png)
</div>

**Comment by amiad** [comment]
מראש חשבתי להוסיף שביל בחנייה אבל העדפתי פתרון כולל.
אם אין כזה אז אוסיף שביל.

**Comment by amiad** [comment]
https://www.openstreetmap.org/way/745122914

**Comment by HarelM** [comment]
אולי עדיף שביל על גבול החניה? אולי אפילו להוסיף כביש או שביל עפר לפי הכביש שיש כשנוסעים בתוך החניה או שזו רחבה בלי סדר?
בכל מקרה זה לא קריטי. 
אני סוגר את הקריאה ברשותך.

**Comment by zstadler** [comment]
אני מסכים שזה נושא של מיפוי נכון ולא בעיה שצריכה להפתר באתר.

אפשר גם להשתמש ב 
[`service=parking_aisle`](https://wiki.openstreetmap.org/wiki/Tag:service%3Dparking_aisle)
כמו שנעשה בחניון הזה:
https://www.openstreetmap.org/way/734629148

**Comment by HarelM** [comment]
It was agreed that this is a mapping issue.
