### ISSUE TITLE
Missing edit in OSM button

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1085]
## What I expect to happen
See the edit in OSM button

## What really happened
The button is missing:
![image](https://user-images.githubusercontent.com/3269297/69156669-6fa70d80-0aec-11ea-9f35-9066f88ada8f.png)

## What I did that caused the issue - step by step
Nothing special...

## My environment
* Operating System and version: win 10
* Web Browser and version: Chrome 78.0.3904.97

## Thing I think the developers should know, images, links etc.
@zstadler @valleyofdawn are you guys experiencing this issue too or is it just me?

**Comment by valleyofdawn** [comment]
I have it present in advanced mode and not in basic mode, as intended.

**Comment by HarelM** [comment]
Right... Counter intuitive feature...
Closing...
