### ISSUE TITLE
Redesign current location arrowhead

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1093]
## Enhancement

We originally designed the arrowhead not to block the map view.
However, from my experience, it came out too subtle.
It's hard to locate the arrowhead in one glance, especially when the identically-colored recorded track is present (see example). 
I suggest making it solid. I can provide an SVG if you agree.

![image](https://user-images.githubusercontent.com/689201/69913263-6ef06e80-143e-11ea-9795-8e235dc4269f.png)

**Comment by HarelM** [comment]
I do not think this is the right solution add it doesn't solve the previous problem which is still valid, i.e. see the map.
I'm on favor of closing this issue.

**Comment by zstadler** [comment]
My experience is that the current location arrowhead is easily spotted as it is always in the center of the screen.

As far as I can tell, the issue with the above screenshots is that the zoom level does not match the user expectations. One or two clicks on the zoom-in button and the location would have been clear.

I'm also in favor of closing this issue.

**Comment by HarelM** [comment]
Closing as the majority had agreed this is not a required feature.
