### ISSUE TITLE
Require confirmation before a recording is stopped

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1095]
## What I expect to happen
As a user I would like the application to ask for user confirmation before stopping a track recording.

Maintaining a "recording" state is important. If a recording is accidentally stopped, information is lost, track statistics are reset and merging of separated tracks is possible only after the new recording ends. 

## What really happened
During off-roading it is very common that a wrong button is pressed because of a bump in the road. When such a wrong causes stopping of the recording, there is no simple "going back" as some of the GPS location information is already lost.

## Thing I think the developers should know, images, links etc.
The UI for confirmation can be similar to the "Continue interrupted recording" question, but not necessary.

**Comment by HarelM** [comment]
It is possible to do this in Orux? if so, how?
