### ISSUE TITLE
Polygon vs. auto-routing mode

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#11]
When switching to polygon mode, all the previously-constructed auto-routed track goes poly.
This makes it impossible to manually skip over missing portions or disconnected trails in OSM.
Since OSM mapping is far from complete, you'r bound to need manual portions when planning anything but very short routes.

**Comment by HarelM** [comment]
Currently I do not have a good idea of a simple way to allow the user to do this kind of logic - I want a clean and easy to use user interface.
This can be achieved with multiple routes - although this is not elegant, this does the job - and also encourage you to go and edit the OSM map :-)
If you have a suggestion or a site that does that which is both simple and powerful please share, otherwise I'll close this issue.

**Comment by valleyofdawn** [comment]
By simple you mean simple to code or simple to execute as a user?
If the latter than all of the rote planners that allow both modes  do it and it is totally transparent to the user.
Just 2 examples:
http://www.bikemap.net/en/route/create/
Switch the magnet tool on the left

http://ridewithgps.com/routes/new
Switch between "draw lines" and "follow roads" on the right.

How are those any less clean or simple for the user? If anything, the fact that all your past planning is gone once you disable auto-routing is non-intuitive.

**Comment by HarelM** [comment]
Just to make my self clear, I'm focusing on user experience and not about code.
I can't make the second site work even after signing-up - which is annoying but not relevant to this post.
Consider the following requirements (which the site you provided do not address fully).
1. The ability to share routes through address bar - address bar is limited and the more data I save on each route point the less points I can share - I can add more data if needed this is a lower issue.
2. Consider this user scenario: I draw 3 point using routing and now I want to change the routing from point 1 to point 2 to be non-routed.
3. The regular routing as can be made with the first site you sent: http://www.bikemap.net/en/route/create/
4. The ability to change routing type from foot to bike to 4x4 for all the scenarios above.

I can't think of a simple and elegant way to support all the above, and if I'm not supporting all of them I prefer to keep the code simple at the very least.

**Comment by valleyofdawn** [comment]
1) I don't know, mine connects. Many others, such as http://www.outdooractive.com/en/tourplanner/ and https://connect.garmin.com/course/create have this capability.
2) I'm not a coder, but if I understand you the address bar would store the info on the co-ordinates of each vertex and the method of routing for each segment. Many bytes to encode the coordinates, just 1 bit (auto-routing or polygon) for the method. Thus, the length of the track would be much more problematic than the mixed method issue. Why not produce a share icon, and upon clicking it store the route (can't be that many of them) on your sever, and use the address as a link? You don't need to manage accounts for that.
2) 
I - This site for instance:
http://www.routeyou.com/route/planner/2/walking-route-planner
Changes the sections adjacent to the vertex you move to a polygon if you switched to manual after initially auto-routing
IiI -  In bikemap you click undo twice, non-routed, point B, routed, point C.
III - You can't do that with your algorithm at all.
IV - Why would you want to do it anyway?
V - Consider the alternative scenario.  You clicked a hundred points to create a beautiful auto-routed  trip across the desert, now you click the next point 500 m away, and due to a disconnect it makes a 20 KM detour to reach it. Most of your users won't be aware of the multiple routes option and they'll curse you and leave the site never to return again. I often plan on Aerial photos, I use OSM when possible, and manual when it's not mapped.

**Comment by zstadler** [comment]
On Mon, Jul 27, 2015 at 7:07 PM, valleyofdawn <notifications@github.com>
wrote:
[...]

> V - Consider the alternative scenario. You clicked a hundred points to
> create a beautiful auto-routed trip across the desert, now you click the
> next point 500 m away, and due to a disconnect it makes a 20 KM detour to
> reach it. Most of your users won't be aware of the multiple routes option
> and they'll curse you and leave the site never to return again. I often
> plan on Aerial photos, I use OSM when possible, and manual when it's not
> mapped.
>

This is exactly the behavior I see at bikemap.net
<http://www.bikemap.net/en/route/create/> and outdooractive.com
<http://www.outdooractive.com/en/tourplanner/>. The user selects routing or
non-routing BEFORE the next point of the route. Once the user finds that
the routing adds the infamous "20km detour", he/she needs to delete the
last point, change to non-routing, and re-do the route. I didn't check the
two other sites that require registration.

By the way, routeyou.com
<http://www.routeyou.com/route/planner/2/walking-route-planner> does not
seem to have any way to avoid routing, at least not at my detective skills
level...

Let's bring concrete proposals for a user interface that enables change
routing on or off for an existing section of the route.

By the way, I think that capturing the non-/routed state of a segment in
the URL can by done using different separators between the point along the
route. For example:
http://osm.org.il/IsraelHiking/#/14/31.5031/34.8762?markers=&Route_0=hike:31.4841,34.8949:31.4954,34.8786|31.5058,34.8924
where the ":" separator means "routed segment" and "|" means "no-routed
segment."

**Comment by HarelM** [comment]
since I know there will be more route types I'll need to more character to describe the routing type.
I chose n - none, h - hike, b- bike - f -four by four.
I have already implemented it, I'm now testing it to see where it falls short - currently there's an issue I now see that when the user loads a file and I'm adding points - all the points have the same routing type
if the user wants to change routing he'll have to wither move every point so that the routing will change to current routing or delete and re-add the points.
currently the default for loading a file is hike routing for all segments.
I can upload it to the test site if you want to play around with it before I publish it.

**Comment by valleyofdawn** [comment]
Zeev, in routeyou you choose manually instead of OSM under the routing selector.

**Comment by zstadler** [comment]
I think it will be easier if changing the route type will affect the last modified route segment as well as subsequent new or modified segments.

In the case of the 20km detour, all the user needs to do after finding the detour is to choose no-routing, click on the next point along the way, and turn-on routing.

When modifying a route, the current routing mode should be applied to the segment **before** the new/modified point.

The current routing mode should also be used when loading a route from file. This way the user can choose not to route all segments or use a specific route type for the uploaded file.

Misc. comments:
"f" stands for "four wheel drive" since "four by four" is Hebrish :-)
This scheme can also allow "c" for "car"

**Comment by zstadler** [comment]
I stand corrected, A segment can be created as "Manually" in routeyou, but this site also does not allow changing the routing type after the segment is created.

**Comment by zstadler** [comment]
Please upload to the test site so we can get the feel of it.

**Comment by valleyofdawn** [comment]
regarding RouteYou, if you autotrack, switch to manual, ac

**Comment by valleyofdawn** [comment]
Nicely implemented in the trial site.  Can be closed.

**Comment by valleyofdawn** [comment]
This feature was changed so that pressing the manual editing icon changes the entire track.
This behavior can be changed to a segment by segment behavior in advanced editing by pressing the lightning icon.
I think it is not useful to change the wracking mode of the entire track. Why would anyone plan a walking trip and then change it all to a polygon or car route?
My suggestions:
Best: revert to the old solution.
Worse: add a global/local button at the top level.
Worst: replace the icon and tooltip with something more intuitive.

**Comment by HarelM** [comment]
The following scenario also applies for this site:
Open a file that has a track in it. 
Reroute the track to use osm data.
The way I see it this is the main scenario while your scenario is for an advanced user.

To answer your other suggestions:
Placing a global button will not allow the user to specify which route is affected.
If you have a better icon please attach it, I need an svg image.

**Comment by valleyofdawn** [comment]
I see your point. However, for me, and I believe most users the scenario necessitating the other behavior is more common. In fact it's very hard to plan a hiking or mountain biking trip without needing it. Car users don't need this site anyway with Google maps and waze available. A global button would work if it only affects the active route. I'm on a cellphone abroad so icon svgs will have to wait. Let's think about what the default should be first.

**Comment by valleyofdawn** [comment]
Please make sure the default behavior is "per-section"
Also a self explanatory button that toggles between local and global mode would be welcome. Do you have the ones I sent?

**Comment by HarelM** [comment]
No, please attach them.

**Comment by valleyofdawn** [comment]
[routing.zip](https://github.com/IsraelHikingMap/Site/files/536341/routing.zip)

**Comment by HarelM** [comment]
Can you split it into two files, I haven't found a good SVG editor yet...

**Comment by valleyofdawn** [comment]
Inkscape.
I'll split it though.

**Comment by HarelM** [comment]
I scaled it to 16 px, I'm using the same one. I think it'll be hard to tell what the image means, I'll try it out now.

**Comment by valleyofdawn** [comment]
Those were ment to be 2 toggle states.

**Comment by HarelM** [comment]
Of course...

**Comment by HarelM** [comment]
Please check, the site was updated,. I don't think the icon is very appealing, but since I don't have anything better I can't really criticize, can I?
Please close it if it's fine by you.
