### ISSUE TITLE
Miscalculating speed at stops

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1100]
## What I expect to happen
When I stop moving I expect the speed to go to zero.

## What really happened
The speed drops and than stops at some positive value (a few KMH) and stays there. 

## What I did that caused the issue - step by step
1) Opened the "dashboard table"
2) Drove/rode
3) Stopped
4) Watched the speed figure

## My environment
Latest app on Android

**Comment by HarelM** [comment]
Speed is what we get from the GPS. If there are no GPS reading (which is what I believe will happen when you stop moving) both speed and time will not be updated. I see no good reason in spending time fixing it as it has minimal value.

**Comment by valleyofdawn** [comment]
I agree it's not high priority, still it's an eyesore and it makes the user mistrust the app accuracy, so in time it should be fixed.
