### ISSUE TITLE
Cannot hide a shared location 

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1101]
## What I expect to happen
Be able to hide a position shared with the app after seeing it on the map

## What really happened
I was unable to hide or remove it. 

## What I did that caused the issue - step by step
1. Opened a location shared with me throu WhatsApp. 
![Screenshot_20191211-232631](https://user-images.githubusercontent.com/1304610/70661847-d3e16b00-1c6d-11ea-974b-2718fbf08810.jpg)

2. Unable to hide the location from appearing on the map
![Screenshot_20191211-232843](https://user-images.githubusercontent.com/1304610/70661980-08edbd80-1c6e-11ea-86c4-01bc37ac4bbc.jpg)

## My environment
* Operating System and version: Android
* Web Browser and version: App version 8.0.470

**Comment by HarelM** [comment]
Can you please share full steps to reproduce including the relevant link?
I'm unable to reproduce the problem.
From the screenshot it seems like you have converted the location share poi to a private poi.
Removing a share location poi is the same as removing public poi: by clicking on it and clicking the eye icon.

**Comment by zstadler** [comment]
Could not find the appropriate reproduction steps. Closing
