### ISSUE TITLE
Incorrect zoom used in Vector maps

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1103]
## What I expect to happen
Vector tiles of zoom 14 to be used when map is in zoom 14

## What really happened
Vector tiles of zoom 14 are used when map is in zoom 15

## What I did that caused the issue - step by step
1. Open the map at [zoom 14.99 here](https://israelhiking.osm.org.il/map/14.99/31.0490/35.3357) and notice that the contours are in 20-meter steps, as defined in zoom 13 vector tiles.
   ![image](https://user-images.githubusercontent.com/1304610/70862210-1347da00-1f42-11ea-9abc-b948dec3fb6d.png)
2. Open the map at [zoom 15.00 there](https://israelhiking.osm.org.il/map/14.99/31.0490/35.3357) and notice that the contours are in 10-meter steps, as defined in zoom 14 vector tiles.
   ![image](https://user-images.githubusercontent.com/1304610/70862212-1e9b0580-1f42-11ea-8b7c-17b20e0b50f0.png)

## My environment
* Operating System and version: All
* Web Browser and version: All

## Thing I think the developers should know, images, links etc.
- This issue may also be contributing to the lack of some details in lower zoom levels.
- This issue reduces the visibility of the https://github.com/IsraelHikingMap/openmaptiles/issues/17 issue

**Comment by HarelM** [comment]
Are you sure this is a site issue and not the Mapbox-leaflet different zoom convention issue?
The address bar of the site is always + 1 from Mapbox's zoom, which I think can explain this issue.
See here:
https://github.com/IsraelHikingMap/Site/blob/f872aaa3a11d2da033a339b1f16f274f8bcdc135/IsraelHiking.Web/sources/application/services/hash.service.ts#L81

Specifically - when the zoom in the address bar is 15 the Mapbox internal zoom is 14 and the style is rendered according to Mapbox's internal zoom.

**Comment by zstadler** [comment]
Makes sense.

It also corresponds well to the generalizations made in creating the vector tiles where the lines for zoom level n are generalised (smoothed) according to the resolution of zoom n+1.

P. S.,
I continue to belive that the zoom in the address bar needs to be compatible with OSM and Google rather than Mapbox.
