### ISSUE TITLE
Error opening a GPX file shared via WhatsApp

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1104]
## What I expect to happen
Open with Israel Hiking map to work when opening a gpx file shared via WhatsApp

## What really happened
Got the following error:
![WhatsApp Image 2019-12-16 at 15 32 07](https://user-images.githubusercontent.com/1304610/70912719-3d21ff00-201d-11ea-816f-11ac96ef5d37.jpeg)

## What I did that caused the issue - step by step
0. Uninstalled the app and installed the latest version
1. Created a short route using the app
2. Saved it as a GPX
3. Shared the GPX via WhatsApp
4. Clicked on the shared file in WhatsApp
5. Selected "Open with Israel Hiking Map"

## My environment
* Operating System and version: App version 8.0.480 on Android

## Thing I think the developers should know, images, links etc.
The saved GPX file with a `.txt` suffix:
[2019-12-16_13-41-27.353_מסלול_1.gpx.txt](https://github.com/IsraelHikingMap/Site/files/3968360/2019-12-16_13-41-27.353_._1.gpx.txt)

**Comment by HarelM** [comment]
Can you please elaborate on the share with WhatsApp step?
What app did you use to share the file?
Can you add a screen shot of how the file looks after sharing in WhatsApp?
Please add screenshots of the share process as much as possible.

**Comment by zstadler** [comment]
I used the attach (paperclip) button in WhatsApp, and navigated to the Israel Hiking directory where I found the saved file.
![image](https://user-images.githubusercontent.com/1304610/70918017-0c46c780-2027-11ea-8ec9-ade75e73c67d.png)

**Comment by valleyofdawn** [comment]
## Things I think the developers should know:
This **does** **not** happen:
When the same file is sent through email
When the file is opened from the WhatsApp download folder
When I use other apps to directly open the GPX sent through WhatsApp
This **does** happen:
Regardless of the type of GPX 
Regardless what app prodcuced the GPX

**Comment by HarelM** [comment]
@valleyofdawn @zstadler I have release a new version for internal testing.
I have made a few tests assuming I was able to reproduce and fix this error.
I'm closing this issue now.
Please see if you can reproduce in latest version - if so, please reopen if this is the same steps to reproduce or open another issue if this is a different scenario.

**Comment by valleyofdawn** [comment]
Works now for me too. Thanks
