### ISSUE TITLE
IOS crash when using iphone camera to add a picture to a point

### ISSUE THREAD

**Issue by MatanBenMoshe** [IsraelHikingMap/Site#1109]
## What I expect to happen
Camera will be open

## What really happened
Application crashed

## What I did that caused the issue - step by step
1. Add a new point.
2. Press on camera to add a picture.
3. Choose the option to take a picture with the camera (Not from gallery)
4. App crashed and closed.

## My environment
* Operating System and version: iphone7
* Web Browser and version: IOS 13.3

## Thing I think the developers should know, images, links etc.
Please let me know if you can't reproduce I'll add a video with screen recording

**Comment by HarelM** [comment]
Thanks for taking the time to open the issue!
I have just opened a similar one a few minutes ago: #1108.
I have found the root cause and the solution, I will upload the fix tonight.
