### ISSUE TITLE
Attribution link to MTBmap.no in Israel MTB map is broken

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#111]
The ```MTB_ATTRIBUTION``` definition in [LayersService.ts](https://github.com/IsraelHikingMap/Site/blob/master/IsrealHiking.Web/services/LayersService.ts) currently has an ```http=``` tag instead of an ```href=``` tag.

I believe the corrected code should be :
```
 private static MTB_ATTRIBUTION = LayersService.ATTRIBUTION + "Map style courtesy of <a href='http://mtbmap.no'>MTBmap.no.</a> ";
```

**Comment by HarelM** [comment]
You are welcome to fix it (You can use the github web UI to do so),
I'll publish it next time I change something.

**Comment by zstadler** [comment]
Thanks!

I was not aware of the web-based editing option.
