### ISSUE TITLE
[IOS] Cordova icon is shown before loading the app when firstly openening the app

### ISSUE THREAD

**Issue by MatanBenMoshe** [IsraelHikingMap/Site#1110]
## What I expect to happen
IHM icon will be shown

## What really happened
I see Cordova icon first

## What I did that caused the issue - step by step
Open the app and see the Cordova icon before IHM is loaded

## My environment
* Operating System and version: iphone7 IOS 13.3

**Comment by HarelM** [comment]
Relevant info to fix this issue can be found here:
https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-splashscreen/index.html
