### ISSUE TITLE
IHM edit causes incorrect mapping of Nature Reserves

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1116]
## Bug
The site creates malformed tagging.

## What I expect to happen
1. IHM edits of relations, such as trails and places, should not modify or add any tags except `description`, `website`, and `image*`.
2.  The site shouldn't add the `leisure=nature_reserve` tag to any element, as it does not follow the [Nature Reserves mapping standard in Israel](https://wiki.openstreetmap.org/wiki/Israel#Nature_Reserves).
3. The nature reserve category shouldn't be modified or assigned by the user to relations, ways, and nodes.

### סובב מכתש רמון
In [Changeset 74356379](https://www.openstreetmap.org/changeset/74356379) the user modified the "סובב מכתש רמון" trail relation using the IHM site.
![image](https://user-images.githubusercontent.com/1304610/71776363-1d855300-2f99-11ea-9428-3d4c11bacd29.png). 
The `route=hiking` tag was removed and a `leisure=nature_reserve` tag was added.
Both changes should not be allowed:
- The `route` tag is required for a `type=route` relation.
- The `leisure=nature_reserve` is inappropriate for a trail.

### שמורת טבע אירוס הביצות
In [Changeset 73705719](https://www.openstreetmap.org/changeset/73705719) the user added a [node for "שמורת טבע אירוס הביצות"](https://www.openstreetmap.org/node/6742900687) using the IHM site, although a proper relation already existed for it. The node was tagged with `leisure=nature_reserve`, which conflicts with the [Nature Reserves mapping standard in Israel](https://wiki.openstreetmap.org/wiki/Israel#Nature_Reserves). 

Interestingly, in a [subsequent edit](https://www.openstreetmap.org/changeset/73705766), the same used used the IHM site to add description, website and a few pictures to the [the proper
"שמורת טבע אירוס הביצות" relation](https://www.openstreetmap.org/relation/6077592). However, The IHM site could not be used to remove the previous node.

## What I did that caused the issue - step by step
The first user probably did:
1. Search for "סובב מכתש רמון"
2. Click the edit button
3. Change the category to "Other: Nature reserve, National Park"
4. Save

The second user probably added a new node and set its category to "Other: Nature reserve, National Park".

**Comment by HarelM** [comment]
Better if we discuss this on the phone...

**Comment by HarelM** [comment]
Proposed solution after the phone call: Do not allow editing of non point features' category and title.

**Comment by zstadler** [comment]
Also:
- Do not allow editing of non point features' classification (within .
- Remove the "Nature Reserve" classification from the possible options.
