### ISSUE TITLE
Sharing while hiding some tracks still revile the hidden tracks 

### ISSUE THREAD

**Issue by Moshe81** [IsraelHikingMap/Site#1121]
## Bug
(Delete the non-relevant)
Step to reproduce:
Open IHM and logging into the site
Create 2 new tracks A and B
Mark Track B as hidden
Press the share button
Create a link for sharing
Open the link on another browser that does not use your user

## What I expect to happen
The link will expose only track A and track B will not be display

## What really happened
Both track A and Track B are on the map (both are un hidden)

## What I did that caused the issue - step by step
Open IHM and logging into the site
Create 2 new tracks A and B
Mark Track B as hidden
Press the share button
Create a link for sharing
Open the link on another browser that does not use your user

## My environment
* Operating System and version: Windows 10 RS5
* Web Browser and version:Chrom

## Thing I think the developers should know, images, links etc.
Facebook post: https://www.facebook.com/groups/israelhikingmap/permalink/2663414410380402/

**Comment by HarelM** [comment]
Thanks for reporting this issue!
Should be fixed next release.

**Comment by Moshe81** [comment]
Confirm the Fix is working.
Thanks

**Comment by Moshe81** [comment]
Hi,
There is a new bug in this flow.
Multiple tracks appear again - can you please check the flow again?
Moshe

**Comment by HarelM** [comment]
Seem like the flow I'm testing is working as expected.
Please describe the steps you made and the share you created to reproduce the bug.

**Comment by Moshe81** [comment]
1) Open the Private Rout section
2) Press the Plus - > Add Track (Called MASLUL1)
3) make a short track
4) Press again on the Plus and add new Track
5) Set the second track as well (Called MASLUL 2)
6) Press the icon of the 2nd track until l it will be marked as hidden
7) Press the Save button 

Expected behavior :
saved file called MASLUL1.gpx will be generated which will contain only MASLUL1

Actual:
New file name is IsraelHikingMap.gpx which contain MASLUL1+MASLUL2 both visible

**Comment by HarelM** [comment]
Thanks for the info.
Can you please open a different issue to track this? This issue about sharing a hidden route while your use case is about storing hidden route to file.

**Comment by Moshe81** [comment]
https://github.com/IsraelHikingMap/Site/issues/1146
