### ISSUE TITLE
Init failed: RangeError: invalid string length

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1122]
## What really happened

Received "Init failed: RangeError: invalid string length" error when starting the app

   <img width="25%" src="https://user-images.githubusercontent.com/1304610/72250607-a25d1600-3604-11ea-813b-23461fbed135.jpg"/>

## What I did that caused the issue - step by step

- Open this [share](https://israelhiking.osm.org.il/share/W1wiOuHDaD)
   - It may take a several minutes
- Edit the route by adding 25 points to its end
   - Pause 10 seconds before adding each node
   - I created the nodes close to one another in the nearby town
      <img width="25%" src="https://user-images.githubusercontent.com/1304610/72253564-82305580-360a-11ea-9d82-0303fc823c5c.jpg"/>
- Close the app
- Open the app

## My environment
* Operating System and version: Android 10
* Web Browser and version: App version 8.5.47

## Thing I think the developers should know, images, links etc.
To recover from this error, reinstall the app or clear its storage

**Comment by HarelM** [comment]
I can't see the error message, but the app crashes on stratup when following the above steps. I'll see what happens on my debug device...

**Comment by HarelM** [comment]
Seems like the IPC message size was resolved (I hope, at least users have stopped reporting it).
I don't think this is a valid use case although possible. This bring the database to its limit and I don't think there's much I can do.
I'm in favor of closing this issue.

**Comment by zstadler** [comment]
Okay
