### ISSUE TITLE
Wikipedia entry does not have a POI

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1126]
## What I expect to happen
Same criteria to be used for showing Wikipedia entries as POIs.

## What really happened
[This Hebrew Wikipedia entry](https://he.wikipedia.org/wiki/%D7%9E%D7%A8%D7%9B%D7%96_%D7%A1%D7%95%D7%96%D7%9F_%D7%93%D7%9C%D7%9C) does not have a POI while its [English version](https://israelhiking.osm.org.il/map/20.00/32.0608/34.7642) has a POI.

**Comment by HarelM** [comment]
Need to investigate why, but the סוזן דלל wikipedia page was not mirrored - i.e. the following query to elastic returns not found:
http://localhost:9200/external_pois/feature/Wikipedia_he_8772
8772 is the page Id for the above wikipedia entry as can be seen here:
https://he.wikipedia.org/w/api.php?action=query&titles=מרכז סוזן דלל

**Comment by HarelM** [comment]
Looks like this is related to this a pagination max size as there are more than 500 wikipedia points in this area.
I have added to question here:
https://github.com/CXuesong/WikiClientLibrary/issues/57

**Comment by HarelM** [comment]
Can be tracked here on this newly opened issue:
https://github.com/CXuesong/WikiClientLibrary/issues/64
