### ISSUE TITLE
Broken redirection for the Israel MTB map

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#113]
For example, http://osm.org.il/IsraelHiking/IsraelMTBmap.html#13/31.7730/35.1200

**Comment by HarelM** [comment]
I'll probably change it for the new site so this is a temporary fix.

**Comment by zstadler** [comment]
That was the idea - to keep the link alive even if we change the
implementation or hosting

**Comment by zstadler** [comment]
When do you plan to publish the fix?
I think it would be useful in the Groopy thread

**Comment by HarelM** [comment]
Already published. is it still broken?

**Comment by zstadler** [comment]
Looks good now
