### ISSUE TITLE
Offline UX

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1135]
## Feature

This is a place-holder for discussion.

In a nutshell, it is about the value and the UX for the various operations that are currently dependent on network access.

Some features that fall under this topic:
- Type conversion when reading and and writing files
- Creating and editing public POIs
- Reading and writing saved routes, aka "shares"
- Creating and editing routes and private POIs

Also, no/handling of concurrent offline updates.

**Comment by HarelM** [comment]
I suggest to split this into separate issues so that we can prioritize them separately.

**Comment by zstadler** [comment]
Let's keep this issue for the global discussion and for tracking the specific components
