### ISSUE TITLE
Public POI created with no classification tags

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1136]
## What I expect to happen
All public POIs are created or updated with the appropriate OSM tags

## What really happened
[This POI](https://www.openstreetmap.org/node/6332833485) was created with name, description and website tags, but no tags for its class/category.
Similarly, I was able to create a [node with no tags at all](https://www.openstreetmap.org/node/7159996691/history)

## What I did that caused the issue - step by step
1. Add a private POI
2. Change its icon to a cup
3. Upload to OSM

There is an error message:
![image](https://user-images.githubusercontent.com/1304610/73133187-dd604000-402d-11ea-8c51-dffed2831d85.png)
but a new node is created in OSM

**Comment by HarelM** [comment]
Good catch!
I'll fix it so that adding a new point with "unsupported" type will be changed to default.

**Comment by HarelM** [comment]
Seems like there's another bug hidden here:
When creating a private POI and updating an existing POI there's a race condition which causes the already exiting POI to loose data.
