### ISSUE TITLE
Easier access to markers drawing

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#114]
Make all the available routing options as a toolbar that pops sideways once user clicks on the pencil button.

**Comment by zstadler** [comment]
Access to the POI editing mode is long and complicated.

A possible simplification is to add a POI icon. Clicking on that button will activate editing in the the markers layer. The route editing buttons, except for the pencil, will be hidden.

When in POI editing mode, a click on the pencil button will re-activate the editing of the last route later and will unhide the route mode buttons.

**Comment by HarelM** [comment]
Let me see if I can put it in my own words to see that I understand:
1. Below the route editing icons there should be a map-marker icon to allow the user to add POIs.
2. Clicking on that button will have the same effect as to clicking on the green markers in the layers control (it will no longer be in the layer control once moved to the right...).
3. When the user want to start editing the route again he will click on the pencil.

here are some issues/questions:
1. the context of the right editing menu is per route, I'm not sure I can make it to work for all routes.
2. some of the options like undo (round arrow) and clear all (x) will not be available?
3. Does this stand in one line with the reason I opened this issue? I would like to make the drawing control as simple and intuitive as possible.

**Comment by zstadler** [comment]
Clarification for item 1 in the description

- When a route is active, I suggest the existing right toolbar will have an additional "POI" button above the "pencil" button:
  <img width="21" alt="new toolbar route mode" src="https://cloud.githubusercontent.com/assets/1304610/15196011/109a07e4-17d3-11e6-8995-7faca102268a.png">
  The POI layer is activated by clicking on the above POI icon.

- When the POI layer is active, I suggest the existing right toolbar will have an additional "pencil" button below the "POI" button:
  <img width="21" alt="new toolbar poi mode" src="https://cloud.githubusercontent.com/assets/1304610/15196021/216df710-17d3-11e6-80e3-8ef032784afe.png">
  The previous route layer is activated by clicking on the pencil icon.

As for the questions/issues:
1. The right editing menu/toolbar remains for one layer at a time
2. Clear and undo buttons are also available today when the POI layer is selected. I don't see a reason to change.
3. I believe this proposal makes the switch between editing of the track and the POI's much simpler. There may be other ideas for simplifications. I suggest we go "one issue at a time". I don't mind making this a separate issue.

**Comment by valleyofdawn** [comment]
I agree to Zeev's suggestion. It's important to make the POIs more accesible.
It would be easier to understand if the pencil options open sideways, to show hiker, bike and car.

**Comment by zstadler** [comment]
@valleyofdawn,
I think that if the pencil options open sideways, to show hiker, bike and car, it will require two clicks to switch between routing and non-routing modes of route editing.
In the proposal above, only one click is required.
This user flow, I believe, is important to bikes where the map does not have all existing trails.

**Comment by HarelM** [comment]
My thought are as follows after thinking about it some more, I hope to get to it soon:
1. Completely remove the markers layer - to avoid confusion.
2. Allow the user to add POIs to every route by clicking the map-marker icon as described in @zstadler's suggestion (I agree with the number of clicks needed - less clicks is better UX in this case).
3. Once the user clicks the icon it will be highlighted and clicking on it again will exit POI edit mode - clicking on it while in route edit mode will switch to POI edit mode.
4. Change the database so that the POIs saved in the links will belong to the first route (to allow some backwards compatibility).
5. Allow the user to add POIs (While in POI edit mode) by clicking on a route point which will open the current POI's popup - POI will look different - it will have a label next to it. 
6. POI can also be a part of a route and not just a "stand alone" POI (this is the same as 5 basically).
7. In order convert a POI in a route to a regular point the user will need to delete the text.
8. Double click will delete a POI and a regular route point in the same manor (when user is not in edit mode of neither route nor POIs).
9. POI editing will not be possible when adding route points and vice versa.
10. Undo and clear operation will work per route to all route elements (POI and route points) - I'm not sure I'll be able to support text undo but I'll do my best.

I hope this covers all the use cases, if it doesn't please let me know.

**Comment by valleyofdawn** [comment]
I Think that the sideways option won;t require an extra click if it opens with one of the 3 modes already active (the last one used). It will make it conceptually clearer that these are all auto-routing options, and will keep the length of the toolbar constant when you go to POI mode.

**Comment by zstadler** [comment]
I meant to say that switching between the routing modes will require 2 clicks: to open the optional sideways and to choose one.
I also believe it is good to show the users all 3 routing options. How would a biker know that behind the hiker icon there is a bike option, or vice versa.
I also see no special value in keeping the button list constant.

**Comment by HarelM** [comment]
Hi,

First impression of new edit mode - mid point with label is a route point.
![edit](https://cloud.githubusercontent.com/assets/3269297/16968660/ec26306e-4e18-11e6-84d2-51f2ba50d3e9.png)
Non-edit:
![nonedit](https://cloud.githubusercontent.com/assets/3269297/16968723/4bc960fe-4e19-11e6-83f4-a87df362f9ed.png)

I'm thinking to add route direction so I might loose the big start and end points
See issue #178.

This is still in early stages of development but the core functionality seems to be working so I hope to finish it by the end of the week.

BTW, I'm not sure but I think the GPX format doesn't really support all this (route point with text and POI per route) so I'm still not sure how to save this data to file...

Thoughts/insights/improvements are welcome!

**Comment by zstadler** [comment]
It will be simpler for importing our traces if POIs are represented in the exported GPX as waypoints.

**Comment by HarelM** [comment]
They will be - those that are on a track but consider the following export:
route1 - a track with POI that is not on the track.
route2 - same as above but in different location.

GPX format has the following lists:
POIs
Routes: has a list of POI (creating a path)
Tracks: has a list of routes (currently used by our site as segments).

there is no room here for POI per track... :-/

**Comment by HarelM** [comment]
As far as I can tell the following solution is a valid GPX - note the ```RouteId``` I used in order to link between a way point and a track.
This is my current proposal for a solution, please let me know if you see any issues with it.
I can add more data to extensions if we want - for example routing type, color and other data that is not part of the GEO data.
"save as single track GPX" will still be available in case the user wants to save the track in order to open it in a different site, this format will not be changed by this feature of course.
I would really love to hear what you think as I don't feel totally comfortable with this solution.
```xml
<?xml version="1.0"?>
<gpx xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" version="1.1" creator="IsraelHikingMap" xmlns="http://www.topografix.com/GPX/1/1">
  <wpt lat="1" lon="2">
    <extensions>
      <RouteId xmlns="">a3bdaeba-4f00-4cc3-a589-b8ca48475d39</RouteId>
    </extensions>
  </wpt>
  <wpt lat="11" lon="12">
    <extensions>
      <RouteId xmlns="">0e21ee6d-0525-4f65-9397-3bae77731348</RouteId>
    </extensions>
  </wpt>
  <trk>
    <name>name1</name>
    <extensions>
      <RouteId xmlns="">a3bdaeba-4f00-4cc3-a589-b8ca48475d39</RouteId>
    </extensions>
    <trkseg>
      <trkpt lat="3" lon="4">
        <ele>5</ele>
      </trkpt>
      <trkpt lat="6" lon="7">
        <ele>8</ele>
      </trkpt>
    </trkseg>
  </trk>
  <trk>
    <name>name2</name>
    <extensions>
      <RouteId xmlns="">0e21ee6d-0525-4f65-9397-3bae77731348</RouteId>
    </extensions>
    <trkseg>
      <trkpt lat="13" lon="14">
        <ele>15</ele>
      </trkpt>
      <trkpt lat="16" lon="17">
        <ele>18</ele>
      </trkpt>
    </trkseg>
  </trk>
</gpx>
```

**Comment by valleyofdawn** [comment]
Good job on the toolbar.
I'm afraid I can't read the code and I wasn't totally clear on all the changes.
WPT= waypoints
POI = points of interest.
I think POI should always be drops, and always visible, editable when the drop icon is pressed. 
I think WPTs should be always round, with no editable text, they should not be visible in view mode.  Start and endpoint should be green/red also in edit mode. If you need a WPT with text, add a POI there.
For simplicity sake, only one set of POI. to be exported with each and any route. They should therefore be in a color not represented in the route palette.
Usually you need extra routes just for reference, not to export them all.

**Comment by zstadler** [comment]
I'm sorry I missed the implications of
> 4. Change the database so that the POIs saved in the links will belong to the first route (to allow some backwards compatibility).

Until I saw the comment on GPX.

The terminology I'll use is my interpretation of the GPX elements:

- A routepoint is used to define a route. Relocating or deleting a route point will change the geometry of the route.
- A waypoint is used to associate some information, such as name, elevation, and description with a location.

From a user view, when several routes are used or shares, there is a good probability that the routes are related: sequentially, forking, joining and crossing one another. It is also very likely that that locations where routes meet will require waypoints to explain what's there or what to do. Such waypoints do not seem to belong to one route more than the other.

Both GPX and KML file formats allow having multiple routes and waypoints in a single file. Neither of them is associating waypoints with routes. It is therefore unclear to which of several routes contained in a GPX file, for example, will the sit associate all the waypoints included in it.

Side note: The KML ability to group elements in a hierarchic applies equally to lines, points and groups.

**Comment by zstadler** [comment]
The proposed visualization of waypoints in non-edit mode is too large IMO.
