### ISSUE TITLE
Avoid showing an encouragement note when search results are empty

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1141]
## What I expect to happen
When search results on shares are empty show an appropriate message or no message at all.

## What really happened
When no results are found in the shares list, an encouragement note is shown:

<img width="264" alt="2020-02-01 11_04_16-Israel Hiking Map" src="https://user-images.githubusercontent.com/1304610/73589791-bac59f80-44e3-11ea-86af-d52b44e65ca5.png">

## What I did that caused the issue - step by step
- Search for some non-existent text in the shares list

**Comment by HarelM** [comment]
I don't see a reason to change this behavior - the user had searched for something that doesn't exist - the sentence starts with "אין שיתופים" which is basically true...
It also encourages the user to add more shares which might solve the non existing share with this name...
