### ISSUE TITLE
Hidden tracks included in the GPX file during Save (Download) of a route

### ISSUE THREAD

**Issue by Moshe81** [IsraelHikingMap/Site#1146]
Open the Private Rout section
Press the Plus - > Add Track (Called MASLUL1)
make a short track
Press again on the Plus and add new Track
Set the second track as well (Called MASLUL 2)
Press the icon of the 2nd track until l it will be marked as hidden
Press the Save button
Expected behavior :
saved file called MASLUL1.gpx will be generated which will contain only MASLUL1

Actual:
New file name is IsraelHikingMap.gpx which contain MASLUL1+MASLUL2 both visible

if needed I can create a video capture

**Comment by HarelM** [comment]
Looking at the code the following is the current behavior:
Save to file saves only the currently active route (the one with the pencil) or all of the routes if there's no one active, it does not act the same way shares are by saving all of the routes so you can't expect the same behavior.
I don't remember the decision made that led to this behavior but I don't see a good reason to change it...
We encourage using shares and not files.

**Comment by Moshe81** [comment]
Hi Harel,
Thanks for the fast respond and handling.
Once I know I need to set the Pencil on the desire route that solve my problems.

There is a different between sharing route and storing them regarding to the use case.
The use cases for storing are:
1) I want offline backup in case the server will be down in the future
2) I want to take the fie and move it to a device that does not have internet connection 
3) I want to edit the OSM map and I use the GPX file as my guide to draw new roads
4) I am taking the route to a different application such as TWO NAV/QSIG in order to get some of their capabilities.

But bottom line I am ok with the solution to mark the require route as Active 
Thanks
Moshe

**Comment by HarelM** [comment]
I can address most of the stuff you wrote from our perspective in case you are interested of hearing :-)
1. Well, offline backup is a good cause, but most of the things you have today are backed-up online - your e-mail, your phone contact, your photos. it's more likely that you'll loose your offline backup than loose an online one... I'm not saying that our server is rock solid, but its backup is probably better than most offline backups users use...
2. Less and less devices are found to not have any internet connection.
3. GPX files can be uploaded to "my recordings" in case you recorded it in a different app, or already there in case you record it with our app, there's no need to do anything besides upload the recoding to OSM. but that's not the case of export here.
4. Export to file should be possible, I'm not saying it shouldn't be, but we aim to remove the need to use files assuming you are using our site and our app, supporting other apps shouldn't be our objective or goal.
Closing this issue.
Thanks for taking the time to report it and this interesting discussion. :-)
