### ISSUE TITLE
Automatically upload a recording when finished

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1147]
## Feature
As a user I would like to prevent data loss by automatically upload my recordings to OSM when I decide to finish a recording.
I wouldn't like to be asked every time but rather it should happen seamlessly in the background.
There should be an option to disable this behavior (implemented in #1145).
In case of no connectivity I should still be able to manually upload it when I have cellular signal (Keep the current behavior).
The above behavior should be re-examined when implementing offline "queue" but is out of this scope for this feature.

**Comment by zstadler** [comment]
What would be the default [visibility of the GPS traces](https://wiki.openstreetmap.org/wiki/Visibility_of_GPS_traces)?
Can that also be changed using the configuration dialog?

**Comment by HarelM** [comment]
It should be private. I don't think it should be part of the configuration dialog.
