### ISSUE TITLE
Routes on the vector map prevent the display of map features

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1149]
## What I expect to happen
I'd expect to see point features such as springs and campsites when a route passes through them.

## What really happened
They are not shown.

## What I did that caused the issue - step by step
Plan a route on a vector map passing through a visible point feature
Watch it disapear

## My environment
Both website and app

## Thing I think the developers should know, images, links etc.

![image](https://user-images.githubusercontent.com/689201/73817714-53b22e80-47f4-11ea-8125-e2a22de89423.png)
![image](https://user-images.githubusercontent.com/689201/73817782-7f351900-47f4-11ea-8b26-ec246f67ec0a.png)

**Comment by HarelM** [comment]
This is probably due to mapbox decluter feature. Please check the mapbox spec and let me know if this is a route-site style issue or vector map style issue.

**Comment by valleyofdawn** [comment]
I agree it's the declattering feature.
We can put "icon-allow-overlap" on all the icons in the map styles to prevent this, but this would prevent declattering altogether.  We need the equivalent of "icon-ignore-placement" for the route, but I can't find one.
Here is the ref in the Mapbox spec:
https://pka.github.io/mapbox-gl-style-spec/#layout-symbol-icon-allow-overlap

**Comment by HarelM** [comment]
I think the best approach would to be open an issue for mapbox and see what they answer.
Any chance you can do it?
Can you reproduce it with a simple example (without drawing a route) by using a different layer order?

**Comment by valleyofdawn** [comment]
Not really, when I place a road on top of a point feature it still doesn't displace it.

**Comment by HarelM** [comment]
The road has the direction icon on top of it, might this be the case?
Although the icon has the relevant property.
See here:
https://github.com/IsraelHikingMap/Site/blob/df923f86b6107fb5045b892a4c3fbbb41bd75d2e/IsraelHiking.Web/sources/application/components/map/routes.component.html#L2
Let me know if there's a way for you to reproduce it...

**Comment by valleyofdawn** [comment]
Yes, this is the case, since once you go into edit mode and the direction icons are gone, the POI icon reappears.
I think all you need there is a "icon-ignore-placement=true" for the direction icons and it will be fixed.

**Comment by valleyofdawn** [comment]
Or maybe we can go back to your SDF solution, I personally think it looked better.
https://github.com/IsraelHikingMap/Site/issues/1030#issuecomment-520177081

**Comment by HarelM** [comment]
I have little interest in opening once again a discussion that was resolved.
I believe both options that were there were using symbol so the solution should be the same.

**Comment by valleyofdawn** [comment]
OK. so please implement ""icon-ignore-placement=true"" on the direction arrows and let me know if you need any testing and when.

**Comment by HarelM** [comment]
App build is now running, you should be able to test it using the latest app.
Please re-open in case my change did not fix it.

**Comment by valleyofdawn** [comment]
Fixed.
Thanks!
