### ISSUE TITLE
A report mail cannot attach a large log file

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1151]
## What really happened
When using "Report by mail" and the log file exceeds 25Mb, the attachment of the log to the mail fails, an error message from the mail is shown briefly, and the mail can only be sent w/o the log.

![image](https://user-images.githubusercontent.com/1304610/73870316-8d1a8680-4854-11ea-8dd2-291283e4afeb.png)

## What I did that caused the issue - step by step
Conduct a long activity, such a very long recording, and try to send a log that is larger than 25Mb

## My environment
* Operating System and version: Android
* Web Browser and version: App version 8.5.99

## Thing I think the developers should know, images, links etc.
I suggest:
1. Zip the log file
2. Save the zip file to Downloads and attach it to the mail from there. This can help by providing the user with access to the log so alternative ways can be used to send the file to the developers.

**Comment by HarelM** [comment]
I'm zipping the files, trying to attach them and saving them in the IHM folder just to be on the safe side.
I'm also adding the logs from the plugin, limiting it to 10,000 lines, I hope it won't give the same lines once it reaches 10000... This will need to be tested.
@zstadler maybe you can install the latest app that's currently being built without uninstalling the existing one to get the logs out.

**Comment by zstadler** [comment]
The log file is stored in the zip file without any compression

![image](https://user-images.githubusercontent.com/1304610/73924019-7451b580-48d4-11ea-860d-2056be14655c.png)

As is the default: https://stuk.github.io/jszip/documentation/api_jszip/generate_async.html

Compression options are described at https://stuk.github.io/jszip/documentation/api_jszip/generate_async.html#compression-and-compressionoptions-options
