### ISSUE TITLE
הצעה לשיפור שמירת מסלולים

### ISSUE THREAD

**Issue by Shaui77** [IsraelHikingMap/Site#1154]
שלום 
כפי שכתבתי בפייסבוק, נדמה שיש מקום לעשות שיפור בקטע של שמירת קבצי מסלול (פר יוזר)
הבה נבחן את המצב הקיים: 
בהקלטות שלי - 
1. יש אפשרות להעלות קובץ מסלול ולבחור אם ישמר כציבורי או פרטי - זה טוב
2. כאשר אני בוחר וצופה במסלול ששמרתי בהקלטות שלי - אין אפשרות לערוך אותו (לבצע תיקונים  במסלול עצמו על גבי המפה).
3. כאשר אני בוחר וצופה במסלול ששמרתי בהקלטות שלי - המסלול מוצג ללא הנתונים הבסיסים שלו בחלונית הרלוונטית (ק"מ וטיפוס מצטבר)
4. אין אפשרות לשתף 

בשיתופים שלי-
כל מה שיש מצויין
אופציית ה + הוסף למסלולים הפרטיים שלי מיותרת, כי ברגע שבוחרים בצפיה במסלול  זה ממילא קורה. מה גם שהכיתוב "הוסף למסלולים הפרטיים" - מבלבל ונותן תחושה שיש כאן שמירה של הקובץ באיזה מקום באתר שאולי נקרא מסלולים פרטיים ולא כך הוא הדבר

ההצעה שלי-
1. ליצור משהו אחד שנקרא: המסלולים שלי.
במסלולים שלי ניתן יהיה לשמור גם קבצי הקלטות שבוצעו בשטח וגם קבצים שנוצרים עי המשתמש באתר.
(אלא אם יש בעיה טכנית או חשוב במיוחד שתהיה קטגוריית הקלטות לקבצים שהוקלטו באמצעות האפליקציה) 
2. לאחד את כל מה שיש בשיתופים שלי עם האפשרות לשמור קובץ כציבורי או פרטי
3. להסב את אופציית המסלולים הפרטיים שלי לקישור במסלולים שלי שמפנה במידי לכל המסלולים שנשמרו כפרטי
4. לאפשר פתיחת תיקיות (אם רוצים אז עם הגבלה של 5 תיקיות למשתמש ) שהמשתמש נותן להם שם ושבהם אפשר יהיה לשמור מסלולים לפי קטגוריה מסוימת. לדוגמא:
אני שומר מסלולים שתיכננתי באמצעות האתר בתיקיות מסלולים מתוכננים ומסלולים שהקלטתי בשטח בתיקיית מסלולים שבוצעו

נידמה לי שעכשו אחרי שאיבדנו את GPsite משתמשים רבים ישמחו לראות שבאתר הנפלא שיצרתם יש אפשריות דומות שישמשו אותנו בתכנון ובביצוע מסלולי רכיבה
תודה רבה

שאולי כהן

**Comment by HarelM** [comment]
דבר ראשון, תודה רבה על שהקדשת זמן לפתיחת הקריאה.
אשתדל להתייחס לכל הסעיפים ואני מקווה שלא תמצא את הטון שלי תקיף.
אתחיל מזה שאני מסכים שחווית המשתמש בנוגע לשיתופים והקלטות אינה אידאלית.
עם זאת בערך כל מה שכתבת על מה ניתן לעשות עם הקלטות אינו נכון - שום אמנם החוויה אולי לא אידאלית אבל ע"י הפיכת מסלול מוקלט למסלול פרטי ניתן לקבל את כל היכולות.
לגבי השיתופים יש הבדל בין צפיה בשיתוף לבין הוספת מסלולים שכן במצב כזה ניתן למזג כמה שיתופים.
דבר נוסף הוא שלכל אחד יש משהו אחר בראש, אפליקציה שהוא רגיל\היה רגיל לעבוד איתה ונראית לו יותר הגיונית ולכן אין סיכוי שנצליח לספק את כל הדרישות.
דוגמא לכך ניתן למצוא פה: #1080
החלוקה בין מסלולים מוקלטים ובין שיתופים מבחינתי הגיונית שכן מסלול מוקלט הוא מידע אמין ואמיתי בעוד ששיתופים הם לא.
יתרה מזאת, הקלטות מועלות ומתוחזקות בחשבון האו.אס.אם של כל משתמש ואנחנו רק מציגים ממשק משתמש אחר לאותן הקלטות.
באו.אס.אם אין תכנונים או שיתופים אך חשוב לנו להעלות הקלטות לשם לטובת הקהילה.
זה אמנם תירוץ חלש, ברור לי, אבל הוא חלק ממצבור השיקולים.
האפשרות לשמור משהו כציבורי או פרטי הוא בהאתם למה שיש באו.אס.אם.
באופן כללי, אנחנו לא מעוניינים, כרגע, בשיתוף של מידע ציבורי כמו שיש\היה בגיפסיז. אנחנו מאמינים שבכל הקשור למסלולי טיול צריך מודרציה - מישהו שיסתכל על זה וישאר שזה אכן ראוי. כמות הזבל שיש באתרים כאלה אולי מתאימה לאנשים מסויימים אבל אנחנו מאמינים שאין לה מקום באתר שלנו.
הכיוון שלנו הוא לא להחליף את גיפסיז, אם זה לא היה ברור :-)

ולגבי הנושא האחרון - תיקיות:
אז תיקיות זה אחלה, ולי יש בבית על המחשב המון תיקיות, בעיקר עם תמונות מכל מיני מסלולים.
חיפשתי אתר שמאפשר שמירת תמונות בענן המאפשר שמירה על מבנה תיקיות.
לא מצאתי, אז התחלתי לנסות להבין למה והתשובה היחידה שהצלחתי לחשוב עליה היא כי זה מיושן ולא מתאים לזמננו, ואני כנראה משוגע.
מכאן הבנתי שהצורך שלי בסדר וארגון לא עולה בקנה אחד עם שאר העולם וכדי שאני אנסה לחשוב אחרת.
גם במקרה הזה אני חושב שאותה מחשבה תקפה.
אתה יכול בעזרת שמות לאפיין מסלולים ואח"כ לעשות חיפוש לפי שמות.
זה משיג את הפעולה העיקרית של תיקיות ולא יוצר סיבוך נוסף למי שזה לא מעניין אותו, (מעבר לכמות הקוד שצריך לרשום כדי לתמוך בזה, שזה בכלל לא ברור לי מי יעשה).

בקיצור, אני מעצבן ולא מעוניין לשמוע, וסתם מתכנת קרציה...
השורה התחתונה היא שיש כנראה מה לשפר, לדעתי איחוד של שיתופים והקלטות הוא לא הפתרון הנכון כי יש לדעתי משמעות הגיונית להפרדה ביניהם.
יש גם בעייתיות בהגדרה של שיתוף היום כי זו הדרך היחידה לשמור מסלולים בענן וזה גם לא אינטואיטיבי.
בקיצור, יש פה על מה לחשוב, ואני מודה שאין לי תשובות טובות...

סליחה אם זה לא מה שציפית לשמוע...

**Comment by HarelM** [comment]
אפשר לסגור את הקריאה?
