### ISSUE TITLE
Legend maps are empty

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1155]
## What I expect to happen
Legend should show relevant map parts

## What really happened
Legend maps are empty

## What I did that caused the issue - step by step
Open the legend

## My environment
* Operating System and version:
* Web Browser and version:

## Thing I think the developers should know, images, links etc.
Might be related to the mapbox infra upgrade.

**Comment by zstadler** [comment]
Point features are missing from the legend
![image](https://user-images.githubusercontent.com/1304610/77817327-1888f900-70db-11ea-9390-73aefcfe2701.png)

**Comment by HarelM** [comment]
This is not the same issue.
I'll open a separate one.
