### ISSUE TITLE
Show impact on route while its format dialog is open

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1157]
## What I expect to happen
When changing the format of a route, I would like to immediately see the impact of any changes before the dialog is closed

## What really happened
The changes are taken into effect after the dialog is closed. Any refinement, such as choosing a different route width or opacity needs re-opening the dialog and saving the changes.

## What I did that caused the issue - step by step
1. Set advanced mode
2. Create a route
3. Edit the route properties
4. Change the route to fully transparent and zero width
5. Save the new format
6. Edit the route properties
7. Increase the route width and opacity 

In the last step, there is no way to know what is the new look of the route until after the dialog is closed.

While editing:

![image](https://user-images.githubusercontent.com/1304610/74437685-34a94180-4e71-11ea-8f64-a8d7bb82afcb.png)

After closing the dialog:

![image](https://user-images.githubusercontent.com/1304610/74437764-5acee180-4e71-11ea-9f03-b5e69557c5e6.png)

**Comment by HarelM** [comment]
The concept of the dialog is not to show what's behind the dialog therefore is it both blocking and has a dark background.
The usage concept allows to cancel any editing when exiting the dialog without saving - changing the route appearance while the dialog is open might cause a user to close the dialog and expect the changes to apply without saving - this is in terms of UX.
Besides that, in the technical point of view, changing the route color/opacity/width is an operation which is undo-able so every change is "logged".
From the two aspects above I believe this enhancement should not be implemented.
A possibility to show a preview of the changes inside the dialog can be made, but I think it's an overkill...

**Comment by valleyofdawn** [comment]
I think it's a good idea, although not high priority.
To experience how it might work you can play with google my maps.
https://www.google.com/maps/d/u/0/
![image](https://user-images.githubusercontent.com/689201/74637709-2ca01900-5173-11ea-8ea1-efda2394b891.png)

**Comment by HarelM** [comment]
I don't think that's a good example. If you check out the google UX for a point where you can edit both title and color - the color change affects immediately while the title change requires you to save - while you might be used to it, I think it's not good.
Also this doesn't work in mobile browser at all...
Bottom line, I don't think this should be changed.

**Comment by valleyofdawn** [comment]
An in-dialog preview has been suggested before here:
#772
For me it sometimes takes a couple of iterations to get the route properties right, and a preview would save that.

**Comment by HarelM** [comment]
I'm guessing that a preview on white background might not achieve the required functionality, having said that, I don't mind adding it as I rarely change opacity or color.
@zstadler please approve the preview suggested above or suggest another solution base on my comment.

**Comment by zstadler** [comment]
None of the previews addresses my request.
I'd like to see the width and the transparency as it will show if I approve the change.

If the change is not approved it, then it should be aborted just like a change in color or name would be.

**Comment by HarelM** [comment]
If we can't agree on a middle ground I vote to close the issue. I have explained why technically it is almost impossible and why it has its UX drawbacks.

**Comment by valleyofdawn** [comment]
> None of the previews addresses my request.
> I'd like to see the width and the transparency as it will show if I approve the change.
> 
> If the change is not approved it, then it should be aborted just like a change in color or name would be.

You are supposed to see the width and transparency in the little window marked with "preview".
![image](https://user-images.githubusercontent.com/689201/75038248-ae1ee080-54be-11ea-888d-3584cb87b10f.png)

**Comment by HarelM** [comment]
Closing this issue as we couldn't agree on the solution. Moved this issue to the discussion board.

**Comment by HarelM** [comment]
To summarize phone conversation: preview area is better than nothing as it is today.
I'll add a straight line and use CSS to color it and define its width, hopefully this will be enough.
A possible improvement it to use one of the legend pictures as the background to show how the line will look on the map.

**Comment by zstadler** [comment]
1. The line preview is slightly away from the road
   
   <img width="45%" src="https://user-images.githubusercontent.com/1304610/113475472-9c0fbf80-947e-11eb-9939-bd2e6fb201c9.png"/>
2. Please consider showing the actual preview, with the arrows, rather than the edit-mode preview

**Comment by zstadler** [comment]
>     1. The line preview is slightly away from the road

Please add a `margin-top` style attribute. Its value should be `17-(height/2) px` where `height` is determined by the slider.

Browser screenshots:
- `height: 4px; margin-top: 15px`
![image](https://user-images.githubusercontent.com/1304610/115146852-0751b800-a061-11eb-8285-68ada5ee7127.png)
- `height: 20px; margin-top: 7px`
![image](https://user-images.githubusercontent.com/1304610/115146873-24868680-a061-11eb-8fde-e98a6a77fb1e.png)
