### ISSUE TITLE
Redesign the share window

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#116]
the window should show at first a "create shortcut" button, and nothing else.
After the button is clicked - show the URL and the "Embed" code. 
Add some explanation text.
Allow several size options for the embed - small, medium, large.

**Comment by HarelM** [comment]
@zstadler, I have update the site with a new design for the share control.
I couldn't find embed standard sizes when searching through google.
If you are familiar with these sizes (or your wife is) please let me know and I'll add them as "Small", "Medium", "Large" buttons instead of the height and width.

**Comment by zstadler** [comment]
Google Maps embedding sizes are:

   - Small - 300x400
   - Medium - 450x600
   - Large - 600x800
   - Custom

Here is a screen shot of the Google Maps Link and embed pop-up window:

[image: Inline image 1]

When the size is changes, so does the size of the embedded map preview.
For example, when Medium size is chosen looks like this

[image: Inline image 2]

To see the above, open https://www.google.co.il/maps/ and open the window
using "*==* Menu" -> "Share or embed map"

**Comment by HarelM** [comment]
Well... a designer could probably do a better job than I did, but I think it'll do.
