### ISSUE TITLE
Upload public POI based on photo not working without a description

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1160]
## What I expect to happen
A private geo-tagged photo could be uploaded as a new or existing OSM POI even without a description

## What really happened
Nothing

## What I did that caused the issue - step by step
Dragged a geo-tagged photo to the site
Pressed the photo
Did NOT fill anything in the description
Pressed the upload to cloud
Waited
Nothing happens

## Further info

I understand why we want a description but in many cases it is already in place and only a photo is missing.
Alternatively an error message should be added "please add a description" or the user does not understand what happened.

## My environment
Site in Chrome on PC

**Comment by HarelM** [comment]
Upload to cloud button only opens the right sidebar.
Can you please attach the image here?

**Comment by HarelM** [comment]
Never mind, this is cause by the following line:
https://github.com/IsraelHikingMap/Site/blob/2814f07c2c63acc201d467a74989f9e6f10a1fef/IsraelHiking.Web/sources/application/services/private-poi-uploader.service.ts#L35
Which was introduced as part of the fix for #1129
