### ISSUE TITLE
No access to advances options when logged out off-line

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1163]
## What I expect to happen
I want to access advanced features (spec. save battery) even if I am not a registered user.

## What really happened
When users are not registered, or are registered but logged out and offline, they cannot access this option

## What I did that caused the issue - step by step
Log out
Go into airplane mode
Tap the clous/login symbol
"unable to login" appears
You can't access these options.

## My environment
App for Android

**Comment by HarelM** [comment]
This is by design to make people sign up. I have no intention to change this.

**Comment by valleyofdawn** [comment]
I'd like to reopen the issue following the rearrangement of the interface.
I think the intuitive place for "advanced settings" would be under the hamburger menu.
Once you are offline this feature is inaccessible regardless of whether you are signed up or not.
I recently rode deep in the desert, wanted to turn on the route deviation alert, and couldn't.

**Comment by HarelM** [comment]
Sorry, I don't agree.

**Comment by valleyofdawn** [comment]
What part don't you agree with?

**Comment by zstadler** [comment]
I believe there are two non-conflicting viewpoints here:

- Harel would like the advanced settings to be available only to registered users
- Guy wants the advanced settings to be available to registered users also when offline

**Comment by zstadler** [comment]
**Edited:**
I believe there are two non-conflicting viewpoints here:

- Harel would like the advanced settings to be available only to registered users
- Guy wants the advanced settings to be available when offline

Perhaps we can find a way for the advanced settings to be available to registered users also when offline.

**Comment by HarelM** [comment]
Github issues is not the place to discuss this as we agreed long ago.
