### ISSUE TITLE
Recovery from network loss

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1167]
## What I expect to happen
Given a reasonable delay after resuming of network connectivity, the application would run as if there was no disconnect.

## What really happened
Hours after returning to land-based fast internet connection, the app's spinner is still active, the POI layer would not show on the map, and the recordings list would not show a new recording.

## What I did that caused the issue - step by step
The app was used in an area with intermittent network connectivity while recording was active. The recording was later stopped. The recording was automatically and successfully uploaded to OSM.

## My environment
* Operating System and version: Android 10
* Web Browser and version: App version 8.6.37

## Thing I think the developers should know, images, links etc.
Log files [are available](https://www.dropbox.com/sh/og0iyh81u8usjwk/AAABUF0YYRNnLR3Q4ClSTKDba?dl=0) for developer's access.

This issue is related to offline behavior, yet it also impacts users who do not have access to the offline resources.

**Comment by HarelM** [comment]
Can you create a short reproducible scenario? Or several ones?
I assume there might be a few scenarios that can cause this, but I would like to solve a specific one each time.

**Comment by HarelM** [comment]
As agreed in the phone conversation, the current solution will be to set a timeout for the public POIs requests from the server the see if this is the solves this issue.
