### ISSUE TITLE
Unable to find a new way in recording after deleting an inaccurate way

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1168]
## What I expect to happen
When I find an inaccurate way on the map, I would like to be able to delete it and then use the IHM missing ways analysis to map it correctly based on a GPS recording.

## What really happened
I have deleted this [inaccurate way](https://www.openstreetmap.org/way/639819477/history), waited more than 15 minutes in order for the site to pull the map update from OSM, and used the "find missing way" on a GPS recording.

The analysis found no missing ways in the recording.

## Thing I think the developers should know, images, links etc.
Please note the date/time of the deletion and use earlier map data for any debugging. Eventually, the mapping of the deleted segment was done by extending the nearby segment.

The GPS recording will be sent by e-mail.

**Comment by HarelM** [comment]
Nice catch! good job! The way was not deleted from the database due to incorrect ID creation, I think it was changed as part of some refactoring I did.
