### ISSUE TITLE
Associate all the site's URLs with the app

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1177]
## What I expect to happen
When the app is installed on a mobile device, all links to the site should be handled by the app.

This will also prevent showing the #1176 dialog when the app is already installed.

## What really happened
Currently, the app does not handle some of the links to the site, including
- The main URL: https://israelhiking.osm.org.il
- URLs with a map location: https://israelhiking.osm.org.il/map/16.00/31.8033/35.1654

Links to shares and POIs are handled by the app.

## What I did that caused the issue - step by step
Install the app and open the above links in a mobile browser.

## Thing I think the developers should know, images, links etc.

See https://github.com/IsraelHikingMap/Site/issues/653#issuecomment-390405104 for the list of possible suffixes. The list may be outdated.

**Comment by HarelM** [comment]
This needs to be tested as I can't test it on my device right now...

**Comment by zstadler** [comment]
Version 9.0.16 does not implement this feature. The above links are opened by the browser.

**Comment by HarelM** [comment]
I have added an empty pattern to the list, I'm not sure it will work.
Regardless, I think it's good enough, I don't know what is the browser logic, but my tests are from mail or whatsapp messages which is the case I would like to implement.

**Comment by valleyofdawn** [comment]
It works fine on my Android, but 3 of my friends have iPhones and links sent to them (at least using WhatsApp) open using the site instead of the installed app.
Similar links open directly with Waze on their devices, so we know it can be done.

**Comment by HarelM** [comment]
See #1196.
