### ISSUE TITLE
Add last updated date for offline maps

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1185]
## Feature
This is less verbose and will ensure the user that that map download was completed successfully
![image](https://user-images.githubusercontent.com/689201/77054417-71b8a480-69d8-11ea-8d39-1e81f3f7c47e.png)

**Comment by HarelM** [comment]
The verbosity is there for a reason. The subtle change between purchase and download is not enough from my point of view.
Last update is too vague.
I can add it so you'd have both if you want. I don't think it's very useful as you can simply click the update button when you want to update, but I don't mind adding it...

**Comment by valleyofdawn** [comment]
Yes I would, if you're OK with it.

**Comment by valleyofdawn** [comment]
Personally I don't think a large piece of text is a good cue. Either you want them to read it - than keep it short, or use another cue.
We can have it inside the button.

**Comment by HarelM** [comment]
Let's agree to disagree.
