### ISSUE TITLE
Fix existing bad Wikimedia Commons links

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1188]
## Bug
Resolving #1183 prevented the future creation of bad Wikimedia Commons links that were caused by multiple uploads of the same image.

This issue is about fixing the still existing broken links.
## What I expect to happen
OSM should not contain broken image links, and broken links created by this site in particular.

### Internals of the duplicate image removal mechanism in Wikimedia Commons
Wikimedia Commons uses a redirection mechanism in order to handle the removal of duplicate images without creating broken links accessible by the casual user. In particular, when an image is removed due to being a duplicate, its `File:` page is replaced with a page showing the original image.

For example, https://commons.wikimedia.org/wiki/File:Maar_Israel.jpg is showing the https://commons.wikimedia.org/wiki/File:Maar,_Golan_Heights.jpg page with a note about being the redirection target of File:Maar_Israel.jpg

   <image width="40%" src="https://user-images.githubusercontent.com/1304610/77538405-62d66400-6ea8-11ea-95bd-d3f06b6f415a.png"/>

Note that this duplicate was probably **not** caused by the site.

#### Finding the redirection target
The `File:` page for the removed image has a `rel="canonical"` link to the redirection target. For example:
```
>wget -q "https://commons.wikimedia.org/wiki/File:Maar_Israel.jpg" -O - | find """canonical"""
<link rel="canonical" href="https://commons.wikimedia.org/wiki/File:Maar,_Golan_Heights.jpg"/>
```

**Comment by zstadler** [comment]
## Thing I think the developers should know, images, links etc.
It is likely that both the original image and its duplicate(s) are used in `image*` tags created by this site for the same OSM element. In such cases, the `image*` tag(s) for the duplicate(s) should be removed rather than be updated with the redirection target.

For example, [version 7 of the "שן רמון" node](https://www.openstreetmap.org/api/0.6/node/274596897/7) had the following tags:
``` xml
<tag k="image" v="https://upload.wikimedia.org/wikipedia/commons/9/99/Israel_Hiking_Map_שן_רמון.jpeg"/>
<tag k="image1" v="https://upload.wikimedia.org/wikipedia/commons/1/17/Israel_Hiking_Map_שן_רמון_1.jpeg"/>
```
The `image1` tag should be removed because its underlying image was a duplicate of the image underlying the `image` link.

**Comment by HarelM** [comment]
Codewise, I have added multiple URLs to a single file hash.
I have sent a mail to explain how to fix current issues in OSM.
There's nothing else to do related to the code in this repository right now.
We'll need to see how this progresses after fixing the relevant OSM entities, hoping it won't degrade much over time...
