### ISSUE TITLE
Try to remove the location and zoom from the short URL

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#119]
Does the short URL have to contain the zoom & location? "http://israelhiking.osm.org.il/EeXcv7bacm" or even "http://israelhiking.osm.org.il/?s=EeXcv7bacm" look better.

It is also safer as it does not allow a conflict between the stored location and zoom and a _**modified**_ location or zoom in the URL.

**Comment by HarelM** [comment]
Published.
