### ISSUE TITLE
POI upload suggests updating a bus-stop

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1194]
## What I expect to happen
When the user uploads a new public POI, the site suggestions to update an existing node, should be limited to POI types that can be edited or created using the site.

## What really happened
When uploading a new public POI, the site may suggest updating of non-editable POI types, such as a bus stop, rather than updating a nearby IHM-editable POI, if exists. 

For example, when attempting to update a spring, the suggestion is to update a bus stop while the site does not allow creation or editing of bus-stops in ant other way:

![image](https://user-images.githubusercontent.com/1304610/77887688-b1eb1300-7273-11ea-8800-7e8c881a379b.png)

The casual user would not know what is the type of the suggested POI, just its name. The screenshot shows the location of the bus-stop for reference only. 

If the suggestion accepted, the bus-stop would be changed into a spring, which is not a kind of OSM edit the site should be enabling.

## How to reproduce
- Open [this share](https://israelhiking.osm.org.il/share/VvoU9ady7i)
- Click on the private POI called "עין אחוזה"
- Click "Upload" to make it a public POI 
   **DO NOT APPROVE THE UPDATE OR PERFORM THE UPLOAD!**

The site suggests updating "[ולנברג/שוויצר](https://israelhiking.osm.org.il/poi/OSM/node_1802988832?language=he)", which is a nearby bus-stop, rather than updating the existing "עין אחוזה" or any nearer IHM-editable POI.

**Comment by HarelM** [comment]
The original statement is incorrect: I can edit points I find in the search, not all of them appear on the map as POIs so I'm not sure I agree about the required experience, but I don't have a better suggestion so this was implemented as requested.
