### ISSUE TITLE
Opening Legend causes main map to disappear

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1199]
## What I expect to happen
I should be able to look at the legend without any problems

## What really happened
When opening the legend some legend items and the main maps stops working

## What I did that caused the issue - step by step
1. Open legend
2. Open water group

## My environment
* Operating System and version:
* Web Browser and version:

## Things I think the developers should know, images, links etc.
The problem is that there are too many web-gl contexts.
I think it was caused by the following fix #1190 which causes more context to be used when drawing the legend items.

**Comment by zstadler** [comment]
On Android, the legend is limited to a maximum of 8 entries at a time.
This was the case also before the fix for #1190, but we have not noticed it.

**Comment by zstadler** [comment]
Raster tiles needed for showing the legend were created from the IHM and ilMTB vector styles.
The tiles are available on the site server at `Documents\Maps\Legend`.

**Comment by HarelM** [comment]
I've checked in an initial fix that should reduce the severity of this issue:
I was able to migrate from using a map element to use an image - the image is created on the server using the current image creation service (same one the thumbnail uses) which will need to be improved since it's currently using the old raster tiles.
I'll publish this to the server to allow testing with android client, which is where we've seen the poorest behavior.

**Comment by HarelM** [comment]
This is basically "solved" by using the server which currently uses the old raster tiles.
It's far from ideal but it's a lot better than crashing.
Closing this in favor of #1200.

**Comment by HarelM** [comment]
https://github.com/mapbox/mapbox-gl-js/issues/9476#issuecomment-610633697
A possible solution can be found in this link.
