### ISSUE TITLE
Which datum is used for showing the lat/lon of a marker?

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#120]
<img width="257" alt="latlonmarker" src="https://cloud.githubusercontent.com/assets/1304610/11170560/a69cbcac-8be0-11e5-8b7c-5338136bbc46.png">

**Comment by HarelM** [comment]
New israeli grid. same one we use for the vertical and horizontal lines.
I can probably add the lat & lon as well if needed.

**Comment by zstadler** [comment]
The popup is completely gone now.

From [the commit history](https://github.com/IsraelHikingMap/Site/commits/54a652fc9c070bc1969c1331b58713e0b2f1e111/IsrealHiking.Web/views/templates/markerPopup.tpl.html) it looks like e7e885dd0832415fe8aab2b826e4788d873e0e41 has removed the above fix, then 3a77548946cab2ff747a563991e60cc7a8e4cef3 removed the popup altogether.

**Comment by HarelM** [comment]
This is currently supported only on markers and not on route points.
Please open another issue if you want it implemented although I'm not sure we want it since double click is removing and click-drag is for moving the point, adding a click event might not be a positive user experience...
