### ISSUE TITLE
Support vector style in legend items

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1200]
## Infra
In order to solve #1199 we have changed the legend to use server side image creation using raster tiles, this can be improved using the comment here:
https://github.com/mapbox/mapbox-gl-js/issues/9476#issuecomment-610633697

**Comment by zstadler** [comment]
Github is not the platform for this discussion.

**Comment by HarelM** [comment]
Phone conversation summary:
- [ ] Change component to use json file instead of hard-coded object - harel
- [ ] Generate legend images for both sytles and check the in to this repository - harel + zeev
- [ ] Supply a link to images creating and validate some of the images - zeev
- [ ] Use generated images in the legend - harel
- [ ] Create a small script to generate the images - harel

**Comment by HarelM** [comment]
The following script is a good start (need to change the style names probably and the url generation):
```js
"use strict";

var fs = require("fs");
var request = require("request");

var styleKeys = ["IHM", "IMTBM"];
var data = fs.readFileSync("legend.json");
var jsonData = JSON.parse(data);
for (let key in styleKeys) {
    for (let section in jsonData) {
        for (let item in section.items) {
            let width = item.type === "POI" ? 50 : 200;
            let uri = `http://10.10.10.11:8081/${key}/?lat=${item.latlng.lat}&lon=${item.latlng.lng}&zoom=${item.zoom}&width=${width}&height=50`;
            let fileName = `${key}_${item.title}.png`;
            request(uri).pipe(fs.createWriteStream(fileName));
        }
    }
}
```
If when this will work as expected I'll consider adding it to the legend folder where the images are for safe keeping...

**Comment by zstadler** [comment]
The same functionality in a python script with non-overlapping requests and retries:

```python
#!/usr/bin/env python

import json
import requests
import sys

from requests.adapters import HTTPAdapter
from requests.packages.urllib3.util.retry import Retry

session = requests.Session()
retries = Retry(total=5, backoff_factor=1, status_forcelist=[ 502, 503, 504 ])
session.mount('http://', HTTPAdapter(max_retries=retries))

with open("legend.json", "r") as read_file:
    jsonData = json.load(read_file)

styles = ["IHM", "ilMTB"]

for style in styles:
    for section in jsonData:
        for item in section["items"]:
            width = 50 if item["type"] == "POI" else 200
            uri = "http://10.10.10.11:8081/styles/{}/static/{},{},{}/{}x50@2x.png".format(
                    style, item["latlng"]["lng"], item["latlng"]["lat"], item["zoom"], width)
            filename = "{0}_{1}".format(style, item["title"].encode('utf-8'))
            sys.stderr.write("{} -> {} ".format(uri, filename))
            with open(filename, "wb") as f:
                response = session.get(uri)
                sys.stderr.write("{}\n".format(response.status_code))
                f.write(response.content)
```

**Comment by HarelM** [comment]
I have removed all legend items from non IHM/ilMTB base maps (not just satellite).
This is now available offline as well as a side effect which is cool :-)
