### ISSUE TITLE
Use the new vector map style in thumbnails of shares

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1202]
## What I expect to happen
Use the new vector map style in thumbnails of shares.

## What really happened
The share thumbnails are using the legacy Maperitive map style.

**Comment by zstadler** [comment]
The OpenMapTiles tileserver is capable of providing [static images](https://tileserver.readthedocs.io/en/latest/endpoints.html#static-images) for a given style id and bounding box using the URL template

```
/styles/{id}/static/{minx},{miny},{maxx},{maxy}/{width}x{height}[@2x].{format}
```

For example, `http://0.0.0.0:8082/styles/IHM/static/34.740135,30.623383,34.765712,30.639779/512x512.jpg` provides

<img width="33%" src="https://user-images.githubusercontent.com/1304610/97200232-9f10d080-17b9-11eb-9078-f49e22323998.jpg"/>

This can be a replacement for the current tile-based mosaic.

**Comment by zstadler** [comment]
There is also an option to draw a path on a static image using the URL template

```
/styles/{id}/static/auto/{width}x{height}[@2x].{format}?path=...
```

For example,
```
http://0.0.0.0:8082/styles/IHM/static/auto/128x128.jpg?stroke=rgba(255,0,0,0.5)&width=10&padding=0.4&latlng=true&fill=rgba(0,0,0,0)&path=32.16936,34.86319|32.16936,34.86319|32.16936,34.86319|32.16961,34.86324|32.16992,34.86319|32.17019,34.86400|32.17025,34.86405|32.17113,34.86448|32.17137,34.86453|32.17165,34.86464|32.17198,34.86469|32.17180,34.86528|32.17150,34.86646|32.17120,34.86754|32.17112,34.86806|32.17111,34.86827|32.17111,34.86847|32.17116,34.86883|32.17120,34.86908|32.17128,34.86943|32.17133,34.87007|32.17145,34.87132|32.17151,34.87171|32.17152,34.87209|32.17163,34.87268|32.17167,34.87280|32.17186,34.87308|32.17192,34.87319|32.17194,34.87329|32.17202,34.87492|32.17201,34.87517|32.17188,34.87555|32.17185,34.87553|32.17179,34.87555|32.17177,34.87558|32.17175,34.87565|32.16936,34.87535|32.16840,34.87527|32.16768,34.87525|32.16750,34.87534|32.16703,34.87589|32.16727,34.87623|32.16676,34.87672|32.16549,34.87788|32.16443,34.87636|32.16394,34.87577|32.16281,34.87415|32.16254,34.87384|32.16224,34.87387|32.16225,34.87403
```
provides this thumbnail for [this share](https://israelhiking.osm.org.il/share/UmhzE158pG)

![path](https://user-images.githubusercontent.com/1304610/97203934-26604300-17be-11eb-86b0-3eb7dd7eda7c.jpg)

compared to the current thumbnail

![image](https://user-images.githubusercontent.com/1304610/97204032-41cb4e00-17be-11eb-91d4-dac014a575b8.png)

However, this approach has a few issues:

1. The static image seem to use lower zoom level. This may be addressed by requesting a 256x256 image  
   <img width="128px" src="https://user-images.githubusercontent.com/1304610/97205399-2103f800-17c0-11eb-8db2-3fc0074ed88f.jpg"/>
1. Since the path is passed as part of the URL, it may have a limit on the length. This may be addressed by simplifying the trail to a reasonable number of points for a thumbnail.
1. There is probably no support for multiple trails in different colors, as currently exists.  
  ![image](https://user-images.githubusercontent.com/1304610/97204557-e3529f80-17be-11eb-9623-9432e71ac09f.png)

**Comment by zstadler** [comment]
The simplest replacement option is to use raster tiles from
```
/styles/{id}/{z}/{x}/{y}.png
```

For example, `http://0.0.0.0:8082/styles/IHM/15/19558/13288.png` provides

![tile](https://user-images.githubusercontent.com/1304610/97224904-84028880-17da-11eb-867d-d296cf109bb9.png)

**Comment by HarelM** [comment]
@zstadler thanks for the info! 
I'm not sure how this will work for overlay? i.e. the current solution to overlay is client side only so the tiles server doesn't know an overlay style...? So if the share is a hybrid map (IHM overlay over satellite imagery) what should be done?
If the above can be achieved, can you test the performance in term of response time of the tiles method? how much time it will take to get arbitrary 8 tiles for example? and if the second time we send the request is faster?

**Comment by zstadler** [comment]
Summary of the discussion with @HarelM:
1. The thumbnail creation mechanism is tile-based, and this would be the preferred preferred interface to the renderer of the vector sources.
2. As a perquisite to the actual implementation, the performance of the renderer needs to be evaluated. This may be done using a custom user layer in a browser on the IHM server.
3. The transparent layers require their own raster tiles.

@zstadler will do items 2 and 3 above.

**Comment by zstadler** [comment]
> 2. As a perquisite to the actual implementation, the performance of the renderer needs to be evaluated. This may be done using a custom user layer in a browser on the IHM server.

Latency [ms] when using map size of approx 540x540 px

| Zoom | Min | Max |
|---|---|---|
| 11 | 52 | 206 |
| 12 | 127 | 147|
|13| 155 | 239|
|14 | 68|163|
| 15| 69 | 193|
|16 |  62|154|
| 17 | 60 |156|

**Comment by zstadler** [comment]
> 3. The transparent layers require their own raster tiles.

1. Add `IHM-overlay` and `ilMTB-overlay` styles to the raster renderer
2. Use `jq '.layers |= map (select(.metadata."IHM:overlay")) | .sources |= {IHM, Contour}'` to create an overlay style from the corresponding base map, as part of `make refresh-styles` in the vector tile server

**Comment by HarelM** [comment]
I'll reopen and see if I can take case of item1.
I can make it configurable to start with to allow testing it on the production server, once this is working and we are satisfied with the results we can remove the code that uses the raster tiles.
