### ISSUE TITLE
https://israelhiking.osm.org.il/Tiles is no longer available for OSM editors

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1204]
## What I expect to happen
Continue to support the "Israel Hiking" map as a background for iD and Potlatch2 OSM editors.

## What really happened
When selecting "Israel Hiking" from the default background map list in these editors, the map does not show.
When selecting "Israel MTB", the map is shown well.

## What I did that caused the issue - step by step
- Open the [iD](https://www.openstreetmap.org/edit?editor=id) or [Potlatch2](https://www.openstreetmap.org/edit?editor=potlatch2) editor
- If needed, pan and zoom to somewhere in Israel
- Select "Israel Hiking" from the available map backgrounds
- The map does not show
- Select "Israel MTB" from the available map backgrounds
- The map is shown well

## My environment
* Operating System and version: any
* Web Browser and version: any

## Things I think the developers should know, images, links etc.
Both editors are using `https://israelhiking.osm.org.il/Tiles` for the Israel Hiking map and `https://israelhiking.osm.org.il/MTBTiles` for the Israel MTB map.

Opening [https://israelhiking.osm.org.il/Tiles](https://israelhiking.osm.org.il/Tiles) in a browser shows a "500 - Internal server error" page.
Opening [https://israelhiking.osm.org.il/MTBTiles/](https://israelhiking.osm.org.il/MTBTiles/) in a browser shows the directory contents.

**Comment by HarelM** [comment]
This was caused by an incorrect virtual directory settings in IIS (Might be related to recent clean up we did).
I don't believe these virtual directories are needed anymore since we are using the configuration file to allow folder browsing.
I'm planning on removing all the defined virtual directories in order to "keep the truth in one place".
