### ISSUE TITLE
The hiking map is not shown

### ISSUE THREAD

**Issue by boazmenis** [IsraelHikingMap/Site#1208]
The hiking map is not shown, only background.
The satellite map is shown, though.

**Comment by HarelM** [comment]
Can you please add a screen shot? And also see if it is working in chrome incognito mode?

**Comment by boazmenis** [comment]
![IHM](https://user-images.githubusercontent.com/35095977/78802792-e58e1180-79c6-11ea-8c8a-b6cf3ab0e297.JPG)

**Comment by boazmenis** [comment]
The problem exists in incognito mode as well.

**Comment by HarelM** [comment]
Thanks for the quick response!
Can you please press F12, switch to the console tab and take another screenshot so I can see the relevant error message there?

**Comment by boazmenis** [comment]
![image](https://user-images.githubusercontent.com/35095977/78805248-db214700-79c9-11ea-9b5c-9646c91210ee.png)

**Comment by HarelM** [comment]
Thanks again for the fast response.
It seems like some of the files are not available for some reason.
Can you please try and surfing to the following address and see if it returns some text
https://israelhiking.osm.org.il/data/TerrainRGB.json
If this works I'm not sure I understand the problem you are experiencing unfortunately as the console is explicitly saying the files are not available...

**Comment by boazmenis** [comment]
{"tiles":["https://israelhiking.osm.org.il/vector/data/TerrainRGB/{z}/{x}/{y}.png"],"name":"Israel_TerrainRGB","format":"png","basename":"Israel_TerrainRGB.mbtiles","id":"Israel_TerrainRGB","type":"overlay","description":"Israel_TerrainRGB","version":"1.1","bounds":[33.99986111111111,28.99985869776346,36.00005947536892,34.00013888888891],"maxzoom":12,"minzoom":5,"center":[34.999960293240015,31.499998793326185,8],"tilejson":"2.0.0"}

**Comment by boazmenis** [comment]
It's interesting because 2 days ago everything was working fine.

**Comment by boazmenis** [comment]
Hi,
it seems that things are working now.
I don't know what was the problem.

**Comment by boazmenis** [comment]
Thanks for the help

**Comment by HarelM** [comment]
No worries :-)
Might have been a temporary glitch...
