### ISSUE TITLE
The POI icon hide settlement name

### ISSUE THREAD

**Issue by amiad** [IsraelHikingMap/Site#1209]
## What I expect to happen
The name not hidden.

## What really happened
The name hidden sometimes.

## What I did that caused the issue - step by step
See image (especially Zohar)

## My environment
* Operating System and version: Arch Linux
* Web Browser and version: Firefox 76.0b2

## Things I think the developers should know, images, links etc.
![Screenshot_2020-04-09 Israel Hiking Map](https://user-images.githubusercontent.com/402108/78939121-359ad000-7abc-11ea-9aab-6b6804501ba2.png)

**Comment by HarelM** [comment]
Thanks for taking the time to report this issue!
The poi icon and the name are pointing to the same location and thus are very close, I'm not sure what is the right solution here as I wouldn't want to move the icon...
@zstadler do you think it would be a good idea to move the name down a bit?
In desktop you have tooltip and in all platforms you can hide the POIs, but those are just workarounds obviously...

**Comment by HarelM** [comment]
Will be resolved by the map style - see linked issue. closing.
