### ISSUE TITLE
"Last update" is not updated

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#121]
http://israelhiking.osm.org.il/Tiles/LastModified.js is
```javascript
function getLastModifiedDate() { return '15-11-2015'; }
```
but the site says "Last update: Fri Nov 06 2015" at the bottom right corner.

I think is is because index.html has 
```html
<script src="Tiles/getLastModifiedDate.js"></script>
```

**Comment by zstadler** [comment]
Checked-in

**Comment by HarelM** [comment]
Make sure you reference the issue when you commit. this is done by adding #<issue number> to the check-in comment.
