### ISSUE TITLE
App fails to launch

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1212]
## What really happened
This issue was reported by a user via e-mail.

- Recently, the app does not complete its launch. 
- The site works well on the device.
- There is 5.5 Gb of free memory after the installation.
- The app storage was cleaned, the app was removed and re-installed.
- There are no messages within 5 minutes of attempting to start the app.

## My environment
* Operating System and version: Android
* Web Browser and version: App 9.0.66

## Things I think the developers should know, images, links etc.
App screenshot:
<img width="33%" src="https://user-images.githubusercontent.com/1304610/79037230-b69aba00-7bd7-11ea-8165-c4cc216abe36.jpg" />

**Comment by HarelM** [comment]
It is unclear why but using a different version seems to have solved this issue.
I have no clue as to what might have caused it.
@zstadler can I close this issue?

**Comment by zstadler** [comment]
@HarelM 
The play store has version 9.0.66 while the problem was not reproduced with version 9.0.102.
Please update the store version and let me know. I will verify with the user that a new installation from the store works well.

**Comment by zstadler** [comment]
The user verified that the problem no longer exists with version 9.0.108 from the play store.
