### ISSUE TITLE
מיקום שגוי של  נקודת ציון במפה 

### ISSUE THREAD

**Issue by dovgazit** [IsraelHikingMap/Site#1213]
בנסיון ליצור מסלול, דקירת מיקום במפה ממקם את הנקודה במקום אחר במפה ולא היכן שהתכוונת למקמה

## My environment
Phone Samsung A70

* Operating System and version:
Android 10

**Comment by HarelM** [comment]
בעת תכנון מסלול הנקודות נצמדות לקווים הקיימים במפה.
תוכל להסביר יותר בפירוט מה בדיוק הבעיה? אני לא מצליח להבין ממש מהתיאור הנ"ל...

**Comment by dovgazit** [comment]
התקלה קיימת בתכנון מסלול באפליקציה בטלפון בלבד, במחשב תקין.
ברור שהנקודות נצמדות לדרך מסויימת כשהכל תקין. כרגע אתה דוקר נקודה ראשונה או נוספות הם מופיעות רחוק מאד מהמיקום שרצית לא קשור כלל לדרך.

**Comment by valleyofdawn** [comment]
משחזר את התקלה אצלי באתר בכרום על וינדוז.
קורה עם מסך המגע ולא קורה עם עכבר או touchpad.
קורה בתכנון מסלול, אבל לא בהצבעה על נקודת עניין.
לשחזור.
עבור למצב תכנון מסלול (לא משנה איזה)
גם בעזרת מסך המגע של המחשב בנקודה על המפה.
הנקודה הירוקה לא מופיעה בנקודת הנגיעה כי אם לכיוון מערב-צפון-מערב, ותמיד על הקצה השמאלי של החלון.

**Comment by valleyofdawn** [comment]
נפתר בעזרת ctrl-F5

**Comment by valleyofdawn** [comment]
ליתר דיוק הנקודה מופיעה בפינה העליונה שמאלית של המסך. 
x=0 y=0

**Comment by HarelM** [comment]
תודה רבה על הדיווח. הנושא בחקירה.

**Comment by HarelM** [comment]
Related to: https://github.com/mapbox/mapbox-gl-js/pull/9536
A fixed version will be uploaded tonight.

**Comment by valleyofdawn** [comment]
The fixes work for me, thanks
