### ISSUE TITLE
Make KM markers the default

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1214]
## Feature
Most people don't know how to operate this useful and cool feature and can't easily find it since it's tucked away in a non-obvious place.
We can consider making this the default and let people turn it off if they want to.

**Comment by HarelM** [comment]
I don't think this should be on by default. I also don't find this useful and or cool at all...
I'm planning on placing this button under a "..." button when more feature will be added to the height chart such as slope and terrain type.

**Comment by valleyofdawn** [comment]
It's a shame we disagree on its importance.
Maybe in the future general "..." button, since it has nothing to do with the height profile and that's why people can't find it. 
@zstadler, your opinion?

**Comment by zstadler** [comment]
People will gradually realize that they need to look under the "..." button for anything beyond the basic operations.

**Comment by zstadler** [comment]
To the issue itself, I think that the Km marks should not be shown on the route by default.
