### ISSUE TITLE
Purchase status not updated after login

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1216]
## What I expect to happen
As a subscriber, after I login, I expect to see "Download the maps"

## What really happened
I see "Buy the maps..."
![image](https://user-images.githubusercontent.com/1304610/80472803-e4a92980-894d-11ea-9e20-5353fa5b808d.png)

Clicking on "Buy the maps..." shows an error:
![image](https://user-images.githubusercontent.com/1304610/80472964-2508a780-894e-11ea-9ffd-952972293b83.png)

## What I did that caused the issue - step by step
- Clear the App memory
- Login with a subscriber's account
- Open the layers list
- See "Buy the maps..."
- Click on "Buy the maps ..."

## My environment
* Operating System and version: Android 10
* Web Browser and version: App 9.0.117

## Things I think the developers should know, images, links etc.
A bug report was sent from the app button with this issue number

**Comment by HarelM** [comment]
After successful login, does exiting the app and opening it again overcomes this issue?

**Comment by zstadler** [comment]
yes

**Comment by HarelM** [comment]
@zstadler I haven't tested the fix. Please test it with version 118 or greater.
I'm not sure this is totally related to the fix I made.
Also it's worth testing this with a version prior to 117 as this might have been introduced with the version update of the purchase plugin.

**Comment by zstadler** [comment]
Works fine in 9.0.121 :+1:
