### ISSUE TITLE
Automate the switching between online and offline maps

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1217]
## Feature

As a user I that had purchased the offline maps subscription and downloaded the maps I would like the app to automatically switch to use the offline maps when the app thinks it is offline.
Only when the state of the map is online.
When the state of the map is offline nothing should happen.
No changes to the current buttons and UI.

**Comment by HarelM** [comment]
I don't see how this suggestion covers all the required scenarios.
This will not solve the case when there's low connectivity - where you still got internet but not good enough and you want to manually switch to offline.
I believe a text letting the user know that he should switch to offline when he wants to at the end of the download will serve better.

**Comment by zstadler** [comment]
This improvement does not prevent the user from manually solving the uncovered scenarios.
Improvements on the proposal to cover the additional scenarios can be added if and when available.
Meanwhile, a significant part of the support requests is associated with this UX.
[Perfect is the enemy of good](https://en.wikipedia.org/wiki/Perfect_is_the_enemy_of_good)

**Comment by HarelM** [comment]
Then I don't understand the feature.
Please edit it to include screenshots and better explain what is the user flow, and how it will solve the problem I mention above of intermittent connectivity.

**Comment by HarelM** [comment]
## Feature

As a user I that had purchased the offline maps subscription and downloaded the maps I would like the app to automatically switch to use the offline maps when the app thinks it is offline.
Only when the state of the map is online.
When the state of the map is offline nothing should happen.
No changes to the current buttons and UI.

**Comment by valleyofdawn** [comment]
Very important.
I've heard from 4 new customers already (+ myself) that did't understand that they have to press the cloud icon to get the offline map.
If not that, than make the offline map state the default after downloading.

**Comment by HarelM** [comment]
I have made significant changes to layers presentation. I'm not sure this complexity is required given the pop-up that was added in previous commit (but was not released yet).
@valleyofdawn @zstadler please take latest version and check all functionality of custom layers inclusing ESRI, Raster and offline.
Current implementation is on branch, It will not be merged to master without thorough tests.

**Comment by valleyofdawn** [comment]
Where do I access the version? Current beta in Google play  is 9.0.254

**Comment by HarelM** [comment]
I have uploaded it right now to internal tester. It is available in the play store.

**Comment by HarelM** [comment]
Nope, Nevermind, this doesn't seem to work... I'll fix it and upload a new version...

**Comment by HarelM** [comment]
Closing for now as it seems to be working. I'll be merging it to master soon.
