### ISSUE TITLE
Failed to load external url file

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#122]
http://israelhiking.osm.org.il/#/?url=http://www.jeepolog.com/forums/attachment.php?attachmentid=103471

**Comment by HarelM** [comment]
Server can't know which file type it is... File extension is missing...

**Comment by zstadler** [comment]
Can you guess how does Amud Anan handle it?

**Comment by zstadler** [comment]
The extension is not part of the URL but the downloaded file has an extension - gpx.

The response for http://www.jeepolog.com/forums/attachment.php?attachmentid=103471
is a gpx file - ```yehuda-2015.GPX```

**Comment by HarelM** [comment]
I'll check the headers then, I might get the application/gpx and use that...

**Comment by zstadler** [comment]
I suggest also looking at the Content-Disposition header. 
In this case it is ```attachment; filename*=windows-1255''yehuda-2015.GPX```
By the way, the Content-Type header is ```unknown/unknown```
