### ISSUE TITLE
Current position is not recognized on the planned route

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1221]
## Bug

The fix of the recording to the planned route was lost more than 10 times during the session even though the current position was spot on the planned route on the display.
This is the share of plan and recording: 
https://israelhiking.osm.org.il/share/7NdT863tbs
A screenshot of such an instance:
![image](https://user-images.githubusercontent.com/689201/81537055-436e9a00-9375-11ea-822e-a13fc9a0bf71.png)
This specific glitch happened at 08:18. another one happened at 8:14, and many followed.
[geolocation-log.zip](https://github.com/IsraelHikingMap/Site/files/4608344/geolocation-log.zip)
[log.zip](https://github.com/IsraelHikingMap/Site/files/4608345/log.zip)

**Comment by HarelM** [comment]
Good catch!
This is probably related to this part of the code:
https://github.com/IsraelHikingMap/Site/blob/901e91f72e03b156148baab1df2059966585209e/IsraelHiking.Web/sources/application/services/layers/routelayers/selected-route.service.ts#L217L237
It takes the closest route based on closest point and not closest line segment.
So if the planned route has points which are far enough (more than 100 meter apart) and the location is not within 50 meter of either point you'll get the above bug, I think.
Can you check that you can reproduce this on places where there's a long straight street (like Rupin in this case)?

Related to #929

**Comment by valleyofdawn** [comment]
I will check it Thursday at the latest.

**Comment by valleyofdawn** [comment]
Went for another testing session. 
You were right. The unrecognized segments were all in the middle of long straight sections.

**Comment by valleyofdawn** [comment]
Works well now. Thanks!
