### ISSUE TITLE
Improving "follow route" when a planned route is circular or overlaps itself

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1222]
## feature
When a planned route is circular, at the starting position the current position "fix" sometimes goes to the end of the route rather than to its start. Similarly at the end of the recording it may fix to the start of the plan route. This is a common occurrence as probably most user routes would be circular.
Similarly, when the routes folds over itself like so:
![image](https://user-images.githubusercontent.com/689201/81537612-238ba600-9376-11ea-9bd5-7b3deb6e997a.png)
then the fix keeps skipping between the two relevant sections of the planned route.
An improved algorithm would look not only at the nearest point, but also at the sequence of waypoints along the planned route.
Two such examples where the fix goes to the end instead of the beginning and vice versa:
![image](https://user-images.githubusercontent.com/689201/81537870-85e4a680-9376-11ea-99f5-eb70582ee6cc.png)
![image](https://user-images.githubusercontent.com/689201/81537907-972db300-9376-11ea-98b6-f9a3859086c4.png)

**Comment by HarelM** [comment]
I don't see this as a showstopper for production for #929.

**Comment by valleyofdawn** [comment]
Maybe not, but it is bad user experience.
If you stand at the beginning of a circular route, half the time the app will tell you that you traveled far, have 0 km to go and will arrive now.

**Comment by HarelM** [comment]
True, but except for debugging purpose there's no good reason to stare at the app when you are not moving at the begging or end of the route.
Implementing it requires a lot of changes, maintenance, and the risks of new bugs which I'm not sure are worth the effort.

**Comment by valleyofdawn** [comment]
When my friends use other apps they often check how long the ride is going to be before leaving and how fast they rode when they are finished. I accept that it may be too complicated to code at this stage.

**Comment by HarelM** [comment]
The more I think about it the less I know how to solve this.
Please consider the following cases:
1. blue - GPS recording, green start of planned route, red - end of planned route.
![image](https://user-images.githubusercontent.com/3269297/81566816-15547e80-93a4-11ea-9d94-d1b0073dc243.png)
2. Planned route that goes and returns (green):
![image](https://user-images.githubusercontent.com/3269297/81567151-96137a80-93a4-11ea-94a0-dad783ebebb7.png)
And then the next point is:
![image](https://user-images.githubusercontent.com/3269297/81567230-b7746680-93a4-11ea-8043-cedecf8842ec.png)

When dealing with GPS positions you can't assume anything basically.
I can't think of an algorithm to solve these cases and I don't want to start a second "find unmapped routes" like algorithms which requires tons of effort to maintain and has little benefit to the user.

The above two are only those from the top of my head, I'm sure there are plenty more...

I'll be closing this issue soon, if you have an algorithm to solve these cases and can think of something simple enough let me know and I'll re-open.

**Comment by valleyofdawn** [comment]
I assume a planned route consists of points with consecutive index numbers.
1.	You start with “previous index=0” 
2.	Find all the points in the route which are within 50m of your current position.
3.	Choose the one whose “index” - “previous index” is smallest.
4.	Assign the “index” to “previous index”.
This should prioritize the start over the finish and follow the planned route in sequence

**Comment by HarelM** [comment]
While I understand the algorithm and agree it is simple enough to implement (everything you assumed is correct), I'm not sure what it solves...
Can you add a few diagrams like those I added above to illustrate which scenarios it solves?
A scenario it doesn't solve as far as I understand is the following:
There are two planned points that are part of a route that goes back and forth (5 points in total, indexed 0 to 4, index is on the circles).
In case of the current location (red) after point 1 in both going towards point 2 and going back from point 2 the point that will be selected is 1, right?
![image](https://user-images.githubusercontent.com/3269297/81595845-ccb0bb80-93cb-11ea-8a45-62d8b1eb83cb.png)

As I said, I have no objection implementing it, I'm just not sure what it solves...

**Comment by valleyofdawn** [comment]
To be more exact, you want to select the node whose index number is closest to the previous index +1. 
So look for the minimum of abs(“index”-“previous index”-1) 
That way, using your illustration, if your previous index was 0 than you’d select 1, that gives [1-0-1]=0 and not 3 which yields [3-0-1]=2. If your previous index was 2, you’d select 3 that gives [3-2-1]=0 and not 1 which yields [1-2-1]= 2

**Comment by valleyofdawn** [comment]
This solves a scenario in which a route repeats a section twice (no matter the direction) deciding if you are in the first or second passage through that section.
This is a common situation if you want to come back the way you came, want to go make a detour to a viewpoint and back or do two laps of the same route. A private case is a circular route, in which you'd know if you are at the start point or end point of the route.

**Comment by HarelM** [comment]
Previous index is the index of the closest point in the previous loop of the algorithm - i.e. the index that was chosen to the previous location of the GPS? This is stored between GPS position updates?

**Comment by valleyofdawn** [comment]
Yes.

**Comment by HarelM** [comment]
What will happen in case of route switching? It should be zeroed?
I'll try to implement this and see if it makes sense...

**Comment by valleyofdawn** [comment]
I think the suggested algorithm, as is,  would prioritize sticking with the existing route if there is a point within range - which is the preferred behavior.
If the **only** point within range belongs to a new route, you'd switch to it. No need to zero the index number in memory. The index number should be updated to reflect the new fixed point and then stored in memory for selecting the next one.

**Comment by HarelM** [comment]
Covered somewhat in #1473 I believe.
