### ISSUE TITLE
The app doesn't directly open GPX files sent through WhatsApp

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1225]
## What I expect to happen
When a GPX file is sent through WhatsApp I expect to open it directly in the app by clicking it

## What really happened
An error massage appears stating there is no geographical data in the file

## My environment
Latest app on Android

## Things I think the developers should know, images, links etc.
This **does** **not** happen:
When the same file is sent through email
When the file is opened from the WhatsApp download folder
When I use other apps to directly open the GPX sent through WhatsApp
This **does** happen:
Regardless of the type of GPX 
Regardless what app prodcuced the GPX

**Comment by HarelM** [comment]
Is this the same as #1104? If so, please close this one and add the relevant data there.
