### ISSUE TITLE
Add URL syntax for creating a labeled Marker for Wikipedia link

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#123]
Wikipedia's [GeoHack](https://tools.wmflabs.org/geohack/geohack.php?pagename=%D7%AA%D7%9C_%D7%A9%D7%A8%D7%A2&language=he&params=31.3911750_N_34.6815737_E_type:landmark) page allows all references to geographic coordinates to be opened in different online maps.

Ideally, links to the Israel Hiking map would open with a marker at the location with the appropriate title 

A similar example for ACME Mapper is:
http://mapper.acme.com/?ll=31.391175,34.681574&z=13&t=S&marker0=31.391175,34.681574,%D7%AA%D7%9C%20%D7%A9%D7%A8%D7%A2

We may adopt a similar URL syntax: 
```
http://IsraelHiking.osm.org.il/#/14/{latdegdec}/{londegdec}/?marker0={latdegdec},{londegdec},{title}
```
Note; I'm not sure there is a need for more than 1 marker

**Comment by HarelM** [comment]
I'm not sure I understand this issue:
does the following address achieves what you need?
http://israelhiking.osm.org.il/#/13/31.391175/34.681574?markers=31.391175,34.68157,%D7%AA%D7%9C%20%D7%A9%D7%A8%D7%A2

**Comment by zstadler** [comment]
That's perfectly fine.
