### ISSUE TITLE
Use alphabetical order for custom maps and layers

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1231]
## Feature
Use alphabetical order for custom maps and layers

I have many custom maps and layers.
The order they appear is semi-random and changes occasionally.
It therefore takes me a long time to find things.
If it's not too much work, please make them appear alphabetically.

**Comment by valleyofdawn** [comment]
Great! thanks

**Comment by valleyofdawn** [comment]
If possible, also apply this when renaming a map/overlay and when automatically adding one from a share. Thanks

**Comment by HarelM** [comment]
As a temporary work around, you can add and remove a layer I think...
