### ISSUE TITLE
Not being the only map carrying phone when buying the offline maps

### ISSUE THREAD

**Issue by roiros** [IsraelHikingMap/Site#1234]
## Feature
When I go hiking with my friends if I'm the only one who bought the offline maps, everyone have to use my phone all the time. which is a drag.
It would be great if I could grant my friends hiking with me, temporary permission for 8-24H (maybe by scaning QR code) to download offline the 20-30km next to the current location/ 2-3 KM around the defined hiking route.

## What I expect to happen
no to be the only one with offline maps

## What really happened
all my friend relied on me having the map, and my phone battery got depleted very fast.

## My environment
* Operating System and version:
Android

**Comment by valleyofdawn** [comment]
Thanks for your suggestion.
When it's only a few KM around a specific location a free way to get a "poorman's offline map" is to browse around the location when still online. As long as the app remains open and the map is not changed, you'll keep the relevant areas of the map in the app memory. I hope this helps.

**Comment by roiros** [comment]
Thanks for replying so fast, that's a pleasant surprise.

I know this workaround, but it doesn't provide a **reliable** solution - needing to keep the app open also hinder the solution reliability. nor is it extensive enough - because a few KM aren't enough, we are often threading into terrain without any cell reception (and even the process of looking for cell reception is very battery consuming).

Adding another perspective - I can't see 3-4 other people on my hiking group subscribing, so I don't think it will reduce subscription rate

**Comment by valleyofdawn** [comment]
I am sorry to disappoint. This is indeed not as reliable as a true offline map -- I guess you get what you pay for. 
We are not inclined to invest valuable coding efforts in a feature that would make the app more complex and will potentially reduce profits, if not within your user group, within others.
