### ISSUE TITLE
Allow adding "simple" POIs

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1236]
## Feature
As a user I would like to be able to easily add "simple" POIs without the need to add description, name or image.
The following tags are the relevant ones:
1. Drinking water (amenity=diriking_water)
2. barrier=gate access=yes/no, maybe more?

If possible, the gates POI should be added on a way and not "in the open".
This is the summary of the discussion related to #454 
The ability to highlight drinking water on the map is out of scope for this issue and won't be implemented as it requires further discussion.

**Comment by zstadler** [comment]
The maps show 4 types of point barriers. I suggest we keep these 4 levels an map them with the following tags:

| Icon| Barrier class | Tags for new POI |
|---| ---|---|
|<img src="https://raw.githubusercontent.com/IsraelHikingMap/VectorMap/master/Icons/SVGs/single%20SVGs/gate.svg" />| `open_gate` | `barrier=gate` `access=yes`|
|<img src="https://user-images.githubusercontent.com/1304610/83033858-4db0b980-a040-11ea-8ff1-f18a12dc45dc.png" />| `closed_gate` | `barrier=gate` `access=no`|
|<img src="https://raw.githubusercontent.com/IsraelHikingMap/VectorMap/master/Icons/SVGs/single%20SVGs/bollards.svg" />| `no_vehicles` | `barrier=yes` `motor_vehicle=no`|
|<img src="https://raw.githubusercontent.com/IsraelHikingMap/VectorMap/master/Icons/SVGs/single%20SVGs/cattle_grid.svg" />|`cattle_grid`|`barrier=cattle_grid`|

Clearly, many other tag combinations, as allowed by OSM, are mapped into the above classes.

When a user changes an existing barrier, I suggest we keep the original `barrier` tag and only modify the access, except for changing into a `cattle_grid`.

**Comment by HarelM** [comment]
Parking is also a point I find myself adding - mainly a point in the beginning of a route or near a POI which you can park your car.
Although parking can be mapped as area I think the ability to add a parking as a point is important.
`amenity=parking`

**Comment by valleyofdawn** [comment]
I add drinking taps (could be incorporated into water), peaks. We could also add "hazard points"

**Comment by HarelM** [comment]
What would be the OSM mapping for such a "hazard" point? When should the user use it?
I think it's too vague to be added to this list.
Drinking water is defined in my initial post, is there a different way to map it in OSM? If so please define the right OSM mapping. I don't want to add two different options to add basically the same thing.
