### ISSUE TITLE
Battery is drain fary fast

### ISSUE THREAD

**Issue by limelect** [IsraelHikingMap/Site#1238]
I have an s6 phone
I rode on my bike with IsraelHiking map
I hade an external battery hooked to the phone.
The external battery is APEX.
The drainage of the internal battery was slow but still,
it was drained. This means that the software uses a huge amount
of power not like other software.
Ridding with Endemondo for example
the internal battery is charging and NOT DISGARGING.
Any help?

**Comment by HarelM** [comment]
Have you used the battery optimization feature?

**Comment by limelect** [comment]
can you plz elaborate how to do it?

**Comment by HarelM** [comment]
Under your profile (top right), configuration, check the battery optimization. It will only darken the screen when idle though...

**Comment by limelect** [comment]
Thanks, I will try I will report in a few days.

**Comment by HarelM** [comment]
I'll be closing this issue now, feel free to report back if the above suggestion doesn't solve your issue.
