### ISSUE TITLE
Height profile doesn't work for saved tracks

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#124]
e.g. this one:
http://israelhiking.osm.org.il/#/12/31.8003/35.0423?s=8Hor0PzRFX

**Comment by HarelM** [comment]
Ignore this response as I write down information for development.
Loading data from server is not converted to latlng object and therefore stuff doesn't work.
```
Error: previousPoint.distanceTo is not a function
DrawingRoute/this.getRouteStatistics@http://israelhiking.osm.org.il/services/drawing/DrawingRoute.js:499:59
RouteStatisticsController/this.updateChart@http://israelhiking.osm.org.il/controllers/RouteStatisticsController.js:20:38
RouteStatisticsController/this.routeChanged@http://israelhiking.osm.org.il/controllers/RouteStatisticsController.js:14:21
RouteStatisticsController@http://israelhiking.osm.org.il/controllers/RouteStatisticsController.js:112:17
DrawingController/$scope.openStatistics@http://israelhiking.osm.org.il/controllers/DrawingController.js:74:42
anonymous/fn@http://israelhiking.osm.org.il/scripts/angular.min.js line 212 > Function:2:334
Jc[c]</<.compile/</</f@http://israelhiking.osm.org.il/scripts/angular.min.js:253:485
lf/this.$get</n.prototype.$eval@http://israelhiking.osm.org.il/scripts/angular.min.js:133:217
lf/this.$get</n.prototype.$apply@http://israelhiking.osm.org.il/scripts/angular.min.js:133:446
Jc[c]</<.compile/</<@http://israelhiking.osm.org.il/scripts/angular.min.js:254:34
n.event.dispatch@http://israelhiking.osm.org.il/scripts/jquery-2.1.4.min.js:3:6414
n.event.add/r.handle@http://israelhiking.osm.org.il/scripts/jquery-2.1.4.min.js:3:3224
```

**Comment by HarelM** [comment]
Please provide an example. The example above works.

**Comment by zstadler** [comment]
After loading a gpx file from local disk, the height profile is not updated. It is only updated after clicking (again) on its pencil icon from the layers list.

**Comment by HarelM** [comment]
Can you send me the file?
There are two places where the code adds elevation data in case it does not exists: one in the server when converting the file and the other in route manipulation.
If the file has elevation data (that is not 0) the data will not be overwritten.

**Comment by zstadler** [comment]
You may download and use the GPX from http://www.gpsies.com/map.do?fileId=xniyblqmpulnjjuw

**Comment by HarelM** [comment]
This is another issue: opened issue #131.
The height data is there but the selected route is incorrect after opening s file.
