### ISSUE TITLE
Migrate images to use wikimedia common File:...

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1240]
## Feature
Wikimedia common images are a bit fragile when it comes to renaming.
The following hotlink should fix this issue and allow getting an image in the client side without having the full address:
https://commons.wikimedia.org/wiki/Commons:Reusing_content_outside_Wikimedia/technical#Hotlinking
We should consider adding a tag of `wikimedia_common=...` instead of the image tag? not sure what should happen for multiple images... This is a second priority...

**Comment by amiad** [comment]
Maybe to use `wikimedia_commons1` for multiple images.
Officially, OSM not supported `image1` too but we use it.

Other option is to use `wikimedia_commons=Category:` and to add special category to all the images of the POI.

**Comment by HarelM** [comment]
After a phone conversation related to this topic we have decided that this is not the right approach.
When it comes to showing an image, the most intuitive way is to use a link to that image and use the image field. Other tags are less useful in our opinion.
Closing this, as the site and client do support using the `File:` prefix when inside an image but the site will continue to use the `image` tag.

**Comment by amiad** [comment]
I reopen the issue.
If we use image tag ,it is still better to use [hotlink](https://commons.wikimedia.org/wiki/Commons:Reusing_content_outside_Wikimedia/technical#Hotlinking) and not to link directly to the file.
Direct link is broken when the image name changed.
