### ISSUE TITLE
Distorted image ratio

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1245]
## What I expect to happen
The POI thumbnail to maintain the aspect ration of its origin image

## What really happened
Some images are distorted

## What I did that caused the issue - step by step
Open a relevant POI, such as [מזור](https://israelhiking.osm.org.il/poi/OSM/node_278478672)

## My environment
* Operating System and version: Windows 10 Home
* Web Browser and version: Firefox 77.0.1 (64-bit)

## Things I think the developers should know, images, links etc.
![image](https://user-images.githubusercontent.com/1304610/84587969-481ee600-ae2c-11ea-9e9f-238843e48363.png)
![image](https://user-images.githubusercontent.com/1304610/84587962-32a9bc00-ae2c-11ea-8e76-a9de5a0b7c66.png)

**Comment by HarelM** [comment]
Thanks for reporting this!
CSS is a nightmare.
I'll see if the following solutions solves this:
https://stackoverflow.com/a/59794395/2946662
Mainly:
```css
    height: auto;
    object-fit: contain;
```
