### ISSUE TITLE
Increase density of editing POIs for imported tracks

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#125]
With current low density of POIs, routing is deforming the track in highly dense trails areas.

For example, open http://israelhiking.osm.org.il/#/17/32.0001/34.9646?s=V5kzcINYu6 and see how the track changes after activating the bicycle routing option.
To see the original track, deactivate all routing and reload the page.

The original GPX can be found at http://www.gpsies.com/map.do?fileId=xniyblqmpulnjjuw

**Comment by HarelM** [comment]
The default is to split the track into ~20 segments, of minimum 500m between POIs.
If you have a better algorithm for that let me know as I don't really have a better idea how to solve this.
function is ```manipulateRoutesData``` in ```FileService.ts```.

**Comment by HarelM** [comment]
With the current solution to exporting and importing files created on our site I think the current mechanism is enough. Files that were created in other sites are in a lower priority and the user can manually edit them to his needs.
