### ISSUE TITLE
A third mode for the compass

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1251]
## 1250 Feature
This was requested by a facebook user.
He would like the compass icon to (also) rotate with the true north when the device is rotated.
The use case is when you get to a crossroads and turn on the app to see where to turn to. Currently you have to start moving to figure out the directions. I'm not sure it's worth the extra complication but I can see the utility of this. If implemented there should be a clearer indication of which mode the compass icon is currently at.

## Things I think the developers should know
Original post:
https://m.facebook.com/groups/994960670559126?view=permalink&id=3051636371558202

**Comment by HarelM** [comment]
I can't understand what you wrote.
Please describe the problem you would like to solve and not how the UI/UX should be.
Preferably by editing the above post.
The template of "As a user I would like to ... so that I ..." is the right way to describe a feature request.

**Comment by HarelM** [comment]
Nevermind, I'll do it myself.
