### ISSUE TITLE
Show map direction using the device compass

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1252]
## Feature
As a user I would like to be able to understand where I'm going using the device's compass.
i.e. when rotating the phone the map should turn to show the rotation.
This feature exists in Google maps as well as Trailze for example.

**Comment by HarelM** [comment]
The following stackblitz demonstrates the ability to show the phone's orientation:
https://angular-html5-orientation.stackblitz.io
0 is north when the device is pointing north.
Page's code can be seen here:
https://stackblitz.com/edit/angular-html5-orientation
There seems to be a lot of events triggering so there's probably a need to throttle them and see how the animation of the map will behave...

**Comment by zstadler** [comment]
I believe the map is oriented by the magnetic north. In Israel, it is about +5 degrees east or clockwise to the true north of the map.

```
true_bearing = magnetic_bearing + declination
```

The [geomagnetism npm package](https://www.npmjs.com/package/geomagnetism) can provide the declination in a given location.

**Comment by HarelM** [comment]
@zstadler 5 degrees seems to be the least of my worries.
Can you check with a few devices you have what are the reading for alpha you get in the following app:
https://angular-html5-orientation.stackblitz.io
It seems to be changing by 10 degrees when I lower my phone from 1.8 meter above the floor to 1 meter above the floor.
I have tested it with iPad (iOS need to click on request permission), Samsung 7, Xiomi Redme 3 and every device gives different results that can be 30 degrees apart...
I have tested it in house, it my be better outside, I don't know...
If the reading from the device compass are that bad I'll be removing this feature I believe.

**Comment by HarelM** [comment]
Seems like there's a problem when using the device compass in a car where the magnetic field is not correct.
GPS heading is more accurate in this case.
Reopening in order to make this work only when the speed is low or there's no speed.

**Comment by valleyofdawn** [comment]
With a bike the arrow was mostly aligned with the heading. Seemed consistently slightly to the right of it. 
The map direction was not as stable as I'd like.
Activating the compass only when the speed is zero seems like a good idea to me.
