### ISSUE TITLE
Outdated POIs are shown

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1259]
## What I expect to happen
POIs with the same name and nearby positions to show only once and deleted POI would not show.

## What really happened
https://israelhiking.osm.org.il/poi/Wikipedia/he_531491 and https://israelhiking.osm.org.il/poi/OSM/node_4974025556 were not merged

The [OSM POI](https://israelhiking.osm.org.il/poi/OSM/node_4974025556) has a link to the Wikipedia page, but the Wikipedia page also has a [separate POI](https://israelhiking.osm.org.il/poi/Wikipedia/he_531491).

## What I did that caused the issue - step by step
- Search for "מזבח הר עיבל"
- Check-out the first two result
   <img width="50%" src="https://user-images.githubusercontent.com/1304610/86022085-8e7e6280-ba32-11ea-9589-dd3cc886383f.png"/>

## Things I think the developers should know, images, links etc.

Nearby, there is an [POI for an OSM node]( https://israelhiking.osm.org.il/poi/OSM/node_4974025116)  that was deleted from OSM 6 days ago.

Potentially, there is a problem with the deletion of outdated POIs and that problem also caused the older, stand-alone Wikipedia POI, to remain after an OSM POI was created and merged with it.

**Comment by HarelM** [comment]
The points are marked correctly in the database, the problem is that they are returned from the server when searching and showing clusters since I forgot to filter them out in these requests...
Good catch!
