### ISSUE TITLE
Favicon is gone...

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#126]
http://israelhiking.osm.org.il

**Comment by HarelM** [comment]
If you are using firefox then sometimes the favicon does not appear.
refreshing the page helps.
The favicon is defined normally.
see the following articles:
https://support.mozilla.org/en-US/questions/933769
http://stackoverflow.com/questions/2409759/firefox-3-6-9-drops-favicon-when-changing-window-location/4630726#4630726
Not sure I really want to address this here...

**Comment by zstadler** [comment]
Refreshing the page does not help.

Are they suggesting an unsafe workaround?

**Comment by HarelM** [comment]
Not really unsafe more dirtyish...
What browser are you using? which OS?
Can you add the word ```shortcut``` and ```?``` to the icon line on the server and see if it changes anything - the line should look as follow.
```html
<link rel="shortcut icon" href="content/images/favicon.png?">
```
if it helps please check it in.

**Comment by HarelM** [comment]
Is this really the best way to do it? looks like a lot of icons...

**Comment by HarelM** [comment]
Seems that after your change the favicon had stopped working completely...

**Comment by zstadler** [comment]
Which browser are you using?
Did you try to reload the page?

Successfully tested on:
* Windows Firefox
* Windows Chrome
* Windows IE
* Android Chrome
* Android Firefox

**Comment by zstadler** [comment]
For the reason behind the different favicons, see http://realfavicongenerator.net/faq

**Comment by HarelM** [comment]
Windows 10 Firefox.

**Comment by HarelM** [comment]
Even after I cleaned the firefox database icon's cache the issue remains.
The favicon appears when the debug window is open but vanishes when closed and refreshed. :-(
here is a possible workaround to make firefox behave nice:
http://stackoverflow.com/questions/2409759/firefox-3-6-9-drops-favicon-when-changing-window-location/4630726#4630726
BTW it looks great on my android phone! kudos.
I'll see if I find the time later on this week to try it the workaround out.

**Comment by zstadler** [comment]
"Add to home screen" on Android also looks cool...

**Comment by zstadler** [comment]
The favicon is still gone from time to time on Firefox.
I'll try and see if the workarounds Harel gave above can help.
