### ISSUE TITLE
Erratic behavior in the slope algorithm

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1260]
## What I expect to happen
I expect relatively level routes to show a slope close to zero.
I expect overlapping routes to show similar slope graphs.

## What really happened
In some cases, the slope graph shows violent spikes upwards or downwards.

## What I did that caused the issue - step by step
As an example, open these two routes and examine the slope graph toward their finish:
https://israelhiking.osm.org.il/share/N4v6DnSIRC
https://israelhiking.osm.org.il/share/bQwhO5pi96

One is only slightly longer than the other. The terrain seems level near the spikes, and the original slope data seems reasonable.

![image](https://user-images.githubusercontent.com/689201/86140681-c69ca880-baf9-11ea-8ef4-bc5bc8f79fb4.png)

![image](https://user-images.githubusercontent.com/689201/86140569-a8cf4380-baf9-11ea-9b2d-9f36e4444d3a.png)

**Comment by HarelM** [comment]
This feature had cost more time than its value. I have no plans to invest any more time on this side feature.
