### ISSUE TITLE
Block not useful name of points

### ISSUE THREAD

**Issue by amiad** [IsraelHikingMap/Site#1265]
## Feature

Users adding points with not useful names like Cave, Spring, Tree and Viewpoint (or in Hebrew, מערה, מעיין ומצפה). The icon marking the type of point and the name isn't useful and create overload on the map.

I think when user adding point the site should block not useful names.

## Things I think the developers should know, images, links etc.
[מעיין](https://israelhiking.osm.org.il/poi/OSM/node_4942179001?language=he)
[מערה](https://israelhiking.osm.org.il/poi/OSM/node_3760732509?language=he)

## Image
Cisterns near Manof
![Cisterns near Manof](https://user-images.githubusercontent.com/402108/86943965-c599f580-c14f-11ea-8b38-1ecc8189b727.png)

**Comment by HarelM** [comment]
Thanks for taking the time to report this.
While I value your opinion and understand it I do not agree with it.
I would like to make sure I'm not discouraging any users from contributing in any way. Blocking such scenarios as described above can, in my opinion, discourage a user from adding data to OSM.
A simple bot can fix the cases above once a day/week/month/year.
See further related discussion here about user discouragement in a related scenario: #779

**Comment by amiad** [comment]
OK, maybe not block but remove the not useful name.
I worked today lot of time to fix wrong tags and wrong names. 

Bot can be good idea but I don't know how to write it.

**Comment by HarelM** [comment]
Not sure what's your code writing skill level but a few examples can be found here:
https://github.com/SafwatHalaby/osm-bot
If you can try and list the cases (OSM tag and redundant name) maybe @safwathalaby can help writing it. :-)
For example `natural=spring` and "מעיין".

**Comment by zstadler** [comment]
Overpass-Turbo is an easy way to search OSM data.

Here is an example for [finding all elements named "בור מים"](http://overpass-turbo.eu/s/VWr) in Israel. 

You can edit the search for other names and criteria and create links to your versions using the "share" button.

**Comment by amiad** [comment]
@HarelM  @zstadler I will check two options.

Now, I see iD warning about not useful names.
![well](https://user-images.githubusercontent.com/402108/87017030-23722000-c1d8-11ea-9fb5-319db424a15d.png)

**Comment by HarelM** [comment]
Thanks for important conversation.
Please don't take this as an encouragement not to open tickets or share your thought and ideas, we truly appreciate them. 
I'm not planning to address this as part of the site's code.
Feel free to ping me in case you would like to think together where to place such code.
Thanks and sorry.

**Comment by safwat-halaby** [comment]
I have fixed numerous useless names introduced by IHM. I think this issue shouldn't be closed.
