### ISSUE TITLE
רענון קישורים לתמונות וויקיפדיה

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1268]
## What really happened
As a result of a Wikipedia template bug, Wikipedia's "main picture" for rail stations in Israel was set to a map of the railway lines instead of the image of the specific railway. This Wikipedia bug was fixed, but IHM still shows the old image.

Please refresh the Wikipedia images cache in IHM and consider running such a refresh periodically.

## What I did that caused the issue - step by step
For example, the Wikipadia image for "[תחנת הרכבת ראש העין – צפון](https://he.wikipedia.org/w/index.php?title=%D7%AA%D7%97%D7%A0%D7%AA_%D7%94%D7%A8%D7%9B%D7%91%D7%AA_%D7%A8%D7%90%D7%A9_%D7%94%D7%A2%D7%99%D7%9F_%E2%80%93_%D7%A6%D7%A4%D7%95%D7%9F&action=info)" is

![](https://upload.wikimedia.org/wikipedia/commons/e/e7/Rosh_Hahyin_Railway_Station.jpg)

Yet, the IHM image for "[תחנת הרכבת ראש העין – צפון](https://israelhiking.osm.org.il/poi/OSM/node_2930682115?language=he)" is 

![](https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/%D7%9E%D7%A4%D7%AA_%D7%A8%D7%9B%D7%91%D7%AA_%D7%99%D7%A9%D7%A8%D7%90%D7%9C.png/800px-%D7%9E%D7%A4%D7%AA_%D7%A8%D7%9B%D7%91%D7%AA_%D7%99%D7%A9%D7%A8%D7%90%D7%9C.png)

**Comment by HarelM** [comment]
I'm not sure there's an easy way to do it.
I suggest to try and do a "blank edit" on this train station in wikipedia value and see if the image gets updated.
If it's not then there's no "simple" "manual" work around, but if there is we should consider our options accordingly.

**Comment by zstadler** [comment]
It appears like Wikipedia data is still not up-to-date and the main picture for many stations, such as ["תחנת הרכבת תל אביב – השלום"](https://he.wikipedia.org/w/index.php?title=%D7%AA%D7%97%D7%A0%D7%AA_%D7%94%D7%A8%D7%9B%D7%91%D7%AA_%D7%AA%D7%9C_%D7%90%D7%91%D7%99%D7%91_%E2%80%93_%D7%94%D7%A9%D7%9C%D7%95%D7%9D&action=info) is still the railway map. Therefore, it is not effective to refresh the IHM data at this time.

I suggest we wait 3 months, until the stale-bot reminder arrives, and check:
1. Did the Wikipedia data get updated
2. Did the picture of any of the the following stations got updated in IHM:
ירושלים – יצחק נבון • נמל התעופה בן-גוריון • תל אביב - ההגנה • תל אביב - השלום • תל אביב - סבידור מרכז
אשקלון • ראשון לציון – משה דיין בת ים – יוספטל • חולון – וולפסון • צומת חולון • תל אביב – ההגנה • תל אביב – אוניברסיטה • בני ברק – רמת החייל • פתח תקווה – קריית אריה 
בית שמש • רמלה • קריית גת • לוד  • לוד – גני אביב • כפר חב"ד
חדרה – מערב • חיפה – חוף הכרמל • חיפה – בת גלים • חיפה מרכז – השמונה • מרכזית המפרץ • קריית מוצקין • אחיהוד • כרמיאל
הרצליה • בית יהושע • נתניה – ספיר • נתניה • חדרה – מערב • קיסריה – פרדס חנה • בנימינה
מודיעין – מרכז • פאתי מודיעין
