### ISSUE TITLE
Add support for map print/save-as

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#127]
Two options mentioned on [stackoverflow](http://stackoverflow.com/questions/32981556/generate-screenshot-of-map):
* [leaflet-image](https://github.com/mapbox/leaflet-image) plug-in by mapbox
* Mapfish/Geoserver and a leaflet plug-in

The leaflet-image Github Readme has a [simple example](https://github.com/mapbox/leaflet-image/blob/gh-pages/README.md#example).
There is also a [more elaborated example](https://gist.github.com/wboykinm/9940828) on Github.

**Comment by HarelM** [comment]
All the markers are html and leaflet-image library doesn't support exporting this data.
Mapfish/Geoserver is not straight forward.
Is print screen not enough? I'm not sure the above libraries have better capabilities...

**Comment by zstadler** [comment]
Print screen is OK, but the buttons are irrelevant for a printed map
