### ISSUE TITLE
היי הוספתי שביל חדש לבתרא

### ISSUE THREAD

**Issue by onzd** [IsraelHikingMap/Site#1277]
ומשום מה כאשר אני מנסה לסמן אותו הסמן לא עוקב אחריו 
היכן טעיתי בסימון השביל?
https://israelhiking.osm.org.il/share/bQ11FyGNVv

**Comment by onzd** [comment]
![1](https://user-images.githubusercontent.com/43242549/88789994-21302f80-d1a0-11ea-83a9-84bc8612d15d.jpg)

**Comment by HarelM** [comment]
תודה רבה על הדיווח.
אני לא חושב שיש בעיה בשביל או במה שאתה מבצע.
כנראה בעיה במנוע ״הניווט״ בשרת.
נבדוק את העניין ונעדכן.

**Comment by onzd** [comment]
תודה

**Comment by zstadler** [comment]
השביל לא מחובר לדרכים שלידו ולכן **כנראה** לא נכלל בניווט

![image](https://user-images.githubusercontent.com/1304610/88844674-adb40f80-d1eb-11ea-8d88-9eaf831257e0.png)

**Comment by onzd** [comment]
אני חושב שתיקנתי עכשיו אם כך

‫בתאריך יום ד׳, 29 ביולי 2020 ב-22:35 מאת ‪zstadler‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by HarelM** [comment]
שים לב שהזזת את קצה האחו כשהזזת את השביל.
רשמתי הורדעה על כך בOSM.
הניווט כנראה יהיה זמין מחר.
אני סוגר את הקריאה, אם תיהיה בעיה נפתח אותה מחדש.
תודה על התרומה לOSM!

**Comment by onzd** [comment]
תודה רבה מצטער על הזזת שביל לא שמתי לב לכך אקפיד יותר בעתיד

בתאריך יום ה׳, 30 ביול' 2020, 8:02, מאת Harel M <notifications@github.com>:

**Comment by zstadler** [comment]
הזזת השביל היא בסדר גמור. הבעיה שהראל התיחס אליה היתה החיבור של שביל ההליכה לקו המתאר של שטח 
landuse=meadow
המודגש באדום בתמונה

<img width="960" alt="2020-07-30 08_26_53-OpenStreetMap" src="https://user-images.githubusercontent.com/1304610/88884107-88042600-d23e-11ea-8540-7e5a07a2d10e.png">


כשם שצריך לדאוג לחיבורים בין הדרכים השונות, אנחנו מתבקשים לדאוג שלא יהיו חיבורים בין אלמנטים לא קשורים

ניתקתי את החיבור המיותר והשארתי את החיבור בין הדרכים

![image](https://user-images.githubusercontent.com/1304610/88884460-4d4ebd80-d23f-11ea-95e6-b9160475aee6.png)
