### ISSUE TITLE
Cannot open a downloaded GPX file on Android

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#128]
This is strange!

# Summary: #
A Downloaded GPX file cannot be opened in the "Android Native" way, although the file was successfully loaded and can be opened from a file manager. There is no such problem for downloaded KML files.

# Details: #
After downloading a GPX file from the site to an android device, the file cannot be opened (i.e., there are no apps that handle this file). The failure to open the file happens is associated with the special behavior of the "Downloads" directory.

The "Can't open" error happens when attempting to open the file
* From the "Download Complete." notification after a successful Firefox or Chrome download
* From the "IsraelHikingMap.gpx downloaded - OPEN" pop-up dialog in Chrome
* From the "Downloads" (pseudo) app

However, there is no issue when 
* Opening the file from a file manager, after navigating to the "Downloads" directory
* Opening the file from an applicable application, such as Oruxmaps
* Opening the file from Tools -> Downloads in Firefox

My suspicion is that the file is not downloaded with a mime-type expected by the Android apps, and that the "Downloads" directory saves and uses such mime-types.  

For your reference, here is [a route](http://israelhiking.osm.org.il/#/?s=Z6YiP2YsQu) created on the Israel Hiking Map site that was used to explore this bug.

**Comment by HarelM** [comment]
Mime-type might be the issue.
The file is created in the client side and the download starts from there - no server side, so I'm not sure which mime-types are created, which might explain the issue.
I think that in order to fully address this we'll need to move the save to file to server side so that we'll add the appropriate headers.

**Comment by zstadler** [comment]
Does the server side create the KML file that works?

**Comment by HarelM** [comment]
Nope...

**Comment by zstadler** [comment]
If so, the solution to the GPX issue may not need a server-side mechanism

**Comment by HarelM** [comment]
I have changed the "togpx" code to add the relevant data but this is a shaky unmaintained library which might cause more issues in the future.
Please see if the issue can be reproduced.

**Comment by zstadler** [comment]
Unfortunately, the issue is not fixed yet...

Firefox now provides some "open with" options, but they seem to be general
and unrelated to gpx.

Chrome silently does nothing.

There is no change in Downloads' "can't open file" response.

**Comment by HarelM** [comment]
Can you check if you download the file from the convert dialog you get different results? The gpx file downloaded there is from the server.

**Comment by HarelM** [comment]
Well it partially work in my chrome on my android device (without any change).
Both kml and gpx behave the same when regularly downloading them (for me...).
When I use the convert button it does seem to work better.
I can switch to use server side download to get the right header so that applications associate the file type but I'm not sure it justifies the hassle...

**Comment by HarelM** [comment]
@zstadler Can you please check if my latest change (for issue #138) did anything regarding this issue? All files are now coming straight from the server, I'm not generating any files using javascript, due to IE incompetence...

**Comment by zstadler** [comment]
There are definitely changes here:
* It now works from the "Downloads" (pseudo) app: The relevant applications are shown (e.g., OruxMaps and Amud Anan) and the route is shown on both applications.
* From the "Download Complete." notification after a successful Firefox or Chrome download I do get a list of applications to handle the file, but they are not related to the GPX type.
* The "IsraelHikingMap.gpx downloaded - OPEN" pop-up dialog in Chrome shows the relevant application list. However, OruxMaps does not open the route and Amud Anan gets stuck with its splash screen.

**Comment by HarelM** [comment]
@zstadler Do we want to keep this issue open? I'm not sure what else can be done here...

**Comment by zstadler** [comment]
Please keep this open. Option are:
* Explore Android application association docs
* Use network traffic analysis to see the difference in HTTP headers between our site and other sites

**Comment by HarelM** [comment]
I have just done a test on my device:
Using Chrome everything works as expected and the file opens correctly in oruxmaps.
Using firefox for android does not yield these results and I sent them an issue about it.
When I use my file manager and select the file as text the right apps are presented.
I don't think there's anything else we should do here as it depends on implementation of other apps on the android device.

**Comment by HarelM** [comment]
Seems like every browser does something different with the file that the site offers to download, I even found a browser that blocks the download.
I don't think I have a way to fix this.
