### ISSUE TITLE
Improve merge rules

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1280]
## What I expect to happen
The following OSM entities should not be merged.
https://www.openstreetmap.org/node/7170393086
https://www.openstreetmap.org/node/7170421085

## What really happened
They are merged because they have the same name and are less than 1 minute apart

## What I did that caused the issue - step by step
1. Create two similar POIs with the same name but different images.

## My environment
* Operating System and version: Any
* Web Browser and version: Any

## Things I think the developers should know, images, links etc.
I'm not sure how to solve this. here are some options from the top of my head:
1. Define a different merge distance for OSM<->OSM entities merge and third party<->OSM entities merge
2. Do not merge OSM entities that have a different images
3. Both

@zstadler any thoughts are welcome to solve this.

**Comment by zstadler** [comment]
I believe that a merge should only be done between different sources using no more than one element from each.

The merge should assume that the sources do not have duplicates. In the case of OSM, potential duplicates should be handled at the source.

**Comment by zstadler** [comment]
In case OSM has a node, a way, and/or a relation for the same object, such as [`place=*`](https://wiki.openstreetmap.org/wiki/Key:place#Areas), a **closed way** will be preferred over a node, and relation will preferred over both.

**Comment by HarelM** [comment]
Thanks for the feedback, here are some thought about it:
Not sure what you mean by preferred but I'm not planning on changing the current logic - node should hold all the data related to a POI and use the way/relation for the geometry. 
Places merges have a dedicated code to solve them, but the data is stored on the node currently, again I have no plans to change this right now.
OSM entities are merged today and I think they should be - mainly to reduce search clutter. For example when searching for מחלף אליקים I would like to receive only one result and not 7 (I think it's 7, OSM is currently down so I can't check, but I believe it is mapped correctly, I might be wrong here. but there are mapping problems which this should solve as we are not planning on fixing all the mapping problems we know of).
Also streets are merged to create a single line instead of multiple lines of the same street, so I don't think we should stop merging OSM entities as a rule.
I can print out all the currently merged OSM entities if you want to go over it, it's about 15,000 merges...
In any case, I suggested a more subtle approach, let me know if you have an idea for something more general than I suggested, but less "offensive" than the current suggestion. i.e something in between the two approaches...

**Comment by zstadler** [comment]
Within the boundary conditions you described, my only suggestion is to enumerate the types of OSM entities that could be merged. The two examples you give above describe 2 classes:
- multiple [highway=motorway_junction](https://wiki.openstreetmap.org/wiki/Tag:highway=motorway%20junction?uselang=en) nodes with the same name within a predefined perimiter
- interconnected [highway=*](https://wiki.openstreetmap.org/wiki/Key:highway) ways with the same name

It will be useful to see which of the existing 15K merges do not fall within the above and decide if additional classes should be defined, or fewer merges should be done.

**Comment by HarelM** [comment]
You are welcome to review the report.
[2020-05-31-merge-report.html.txt](https://github.com/IsraelHikingMap/Site/files/5012223/2020-05-31-merge-report.html.txt)
I prefer to rule out merges and not rule in as I believe there are far more mapping errors than ruling problems...
In any case, thanks for the input. :-)

**Comment by HarelM** [comment]
In continue to our phone conversation, below is the extended merge report as requested:
[2020-08-07-merge-report.txt.zip](https://github.com/IsraelHikingMap/Site/files/5044674/2020-08-07-merge-report.txt.zip)
It has a few sections:
1. Nature reserves names - you can ignore it
2. Wikipedia merge to OSM by wikipedia tag - I don't think there's much to do there as it uses OSM wikipedia tag and the merge is OK by definition. finishes at line 2912
3. Places merges by name and tags - special case due to how it is mapped in OSM - Finishes at line 5460
4. Merging external to external start at line 69593 talks about merges from external sources to external sources that were not merged to OSM entities - i.e. there's probably an OSM location that need to be updated to link to wikipedia or added alternative name.
5. There was a problem merging the following feature - refers to merges that created an invalid geometry.
Let me know if you need anything else.

**Comment by HarelM** [comment]
Phone conversation summary:
1. Change distance threshold for external and OSM to OSM merges. external to OSM as today (I think it's 1 minute), OSM to OSM 100-200 meters (as it was before the change).
2. Place containers - there's a special method to identify containers for the search results and for places merge - Not sure I want to change it: https://github.com/IsraelHikingMap/Site/blob/dcaa429aa69e55e08ad0fc9a392b70e473ed5f54/IsraelHiking.Common/Extensions/GeoJsonExtensions.cs#L80
Although this can be changed only for places merge algorithm and not change for search and container property as can be seen here:
https://github.com/IsraelHikingMap/Site/blob/dcaa429aa69e55e08ad0fc9a392b70e473ed5f54/IsraelHiking.API/Executors/FeaturesMergeExecutor.cs#L175
I need to think about it.
3. Highways merge - do not merge nodes to ways and vice versa, we might want to do a special treatment like places
4. I'm not sure what to do with OSM node to OSM node merges, for now I'm inclined to keep it as it is today hoping item 1 will improve the current situation, if not, lets re-examine it in the future.

Thanks you @zstadler for a details a thorough analysis of the report! :-)

**Comment by HarelM** [comment]
All the above were done, there was no need to split highways to a separate code as there were already stuff related to it in current code.

**Comment by HarelM** [comment]
@zstadler can you check the following spring - I see that the merge had done a good job at merging it, but the map still shows two locations.
I'm not sure it is mapped correctly:
https://israelhiking.osm.org.il/poi/OSM/node_2319643913?language=he
![image](https://user-images.githubusercontent.com/3269297/90687165-1899b900-e275-11ea-93d6-2d7fbb379330.png)
