### ISSUE TITLE
היי ממש מצטער על הטרדה אבל שוב לא מצליח למפות נכון

### ISSUE THREAD

**Issue by onzd** [IsraelHikingMap/Site#1282]
הפעם הקפדתי בהקלטה לחבר שבילים ושוב אותה בעיה שהתיכנון לא עובר על השביל המסומן
לא מצליח להבין במה אני שוגה 
https://israelhiking.osm.org.il/share/czpJbjdAoS

**Comment by onzd** [comment]
![1](https://user-images.githubusercontent.com/43242549/89099925-8b90dc00-d3fb-11ea-9173-c97907ba2e22.jpg)

**Comment by HarelM** [comment]
כיוון שהמפה וקטורית ניתן להיכנס פנימה ולראות פרטים שבעבר לא היה ניתן.
לדוגמא שהשביל לא מסתיים בכביש אלא אחריו.
![image](https://user-images.githubusercontent.com/3269297/89100138-71f09400-d3fd-11ea-989b-26c5ac0b4111.png)
לחיצה על הכפתור הבא תביא אותך לנק' במפה לטובת עריכה, שם ניתן לראות יותר פרטים:
![image](https://user-images.githubusercontent.com/3269297/89100156-8fbdf900-d3fd-11ea-8303-6b074ff3037c.png)
מאחר והדרך הוספה רק אתמול ייתכן ויקח עוד קצת זמן עד שמנוע הנייוט יתעדכן.
בוא נראה מחר אם עדיין יש בעיה.
בלי קשר, הסתכלתי על קצת על הדרך שהוספת ואני לא בטוח כמה המיפוי מדוייק:
יש הרבה חלקים שהדרך חוצה כבישים ואין נקודות חיבור.
![image](https://user-images.githubusercontent.com/3269297/89100424-833aa000-d3ff-11ea-90ce-0cceb28c2def.png)
יש חלקים שהוא חוצה קירות הפרדה\תמך מה שמוזר לי.
![image](https://user-images.githubusercontent.com/3269297/89100419-75851a80-d3ff-11ea-9b1b-907783a83f08.png)

חלק הדרך שהולך לעין נמוס נראה כמו שביל אחד שבו עשית הלוך ואז חזור והוא ממופה כשני שבילים.
![image](https://user-images.githubusercontent.com/3269297/89100407-67cf9500-d3ff-11ea-817d-d0a42b34214d.png)

יש כמה חלקים שנראה שההקלטה היא על הכביש הקיים ובכל זאת נוסף שביל ליד.
![image](https://user-images.githubusercontent.com/3269297/89100398-59817900-d3ff-11ea-8f5b-91874fd49262.png)

אל תבין אותי לא נכון, זה מצויין שאתה מוסיף שבילים ואנחנו מעריכים את זה מאוד, אבל חשוב לעשות את זה נכון.
אני חושב שאתה נכס לפרוייקט ולכן חזוב לי להשקיע זמן בלתת משוב בונה כדי שתוכל להיות עורך מוביל ולעזור גם לאחרים.
מקווה שלא פגעתי, לא היית לי כל כוונה כזו.

**Comment by onzd** [comment]
מאד חשוב לי לעשות זאת נכון
אני ממש לא נפגע ההפך אני מעוניין ללמוד
אם יהיה לך זמן אשמח אם תשתלט לי על המחשב בעזרת anydesk ושתוכל לראות מה אני
עושה ולתקן אותי אוןליין

בתאריך שבת, 1 באוג' 2020, 14:04, מאת Harel M <notifications@github.com>:

**Comment by onzd** [comment]
אגב לא טיפסנו גדרות ויש מעט שבילים צמודים לאספלט גדר הפרדה אין במקום בגלל
סיבות שימור החקלאות

בתאריך שבת, 1 באוג' 2020, 14:23, מאת ofer kapon <oferkapon@gmail.com>:

**Comment by HarelM** [comment]
נוכל להמשיך את ההתכתבות במייל הפרטי שלי?
harel.mazor@gmail.com

**Comment by onzd** [comment]
בוקר טוב הבעיה במפה הסתדרה
תודה רבה

בתאריך שבת, 1 באוג' 2020, 14:24, מאת ofer kapon <oferkapon@gmail.com>:

**Comment by HarelM** [comment]
תודה על העדכון!
תוכל בבקשה לשלוח מייל ל israelhikingmap@gmail.com
על מנת שנוכל לראות כיצד לשפר את יכולות המיפוי שלך?
יום טוב! :-)

**Comment by onzd** [comment]
שלחתי מייל
תודה רבה לכם

בתאריך יום א׳, 2 באוג' 2020, 9:56, מאת Harel M <notifications@github.com>:
