### ISSUE TITLE
mege route when there is 3 or more close end or start point

### ISSUE THREAD

**Issue by Orrgvili** [IsraelHikingMap/Site#1286]
when mege route when there is 3 or more close end or start point  it merge all of them  
even when only the relevant ones are turned on 

## What I expect to happen
merge only the 2 active route 

## What really happened
all the routes in proxemity merged together

## What I did that caused the issue - step by step
i had 2 recording  with few overlaps that i wnated to combine  
i splited them to the section i whanted to combine 

at area whre there more then 2  close by it meged all the end/start together

**Comment by HarelM** [comment]
Thanks for the report.
Can you please elaborate a bit the steps to reproduce, they are not clear enough for me...? Maybe add a share of the before and after?

**Comment by Orrgvili** [comment]
i can't reproduce tried right now
ill try again this evening

i think you can close this if it will happens again  ill let you know

**Comment by HarelM** [comment]
Looking at the code - the merge only merges 2 routes, never 3, but I might be missing on something.
I'll close this issue and if this happens again let me know and I'll reopen.
