### ISSUE TITLE
Enable a font catalog for Maputnik

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1287]
# Feature
While exploring https://github.com/IsraelHikingMap/VectorMap/issues/45 I found that Maputnik does not show the font catalog of the site, unlike other font sources.

![image](https://user-images.githubusercontent.com/1304610/90007465-75103d80-dca3-11ea-9b03-36d956b07d52.png)

## Implementation details
The font catalog is available at the parent directory of the current publicly-accessible font directory.
Once the parent directory is made publicly-accessible, so will the font directory.

To allow smooth migration, the following steps need to be done in sequence:
- Add the `font-glyphs` parent directory to the `listingDictionary` map in [appsettings.Production.json](https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.Web/appsettings.Production.json) 
- Modify the map styles to use the new directory
- Allow a few months for the change to propagate to most app users. The stale bot can provide a reminder...
- Remove the old directory mapping from the `listingDictionary`

I've prepared a PR for the first step.

**Comment by HarelM** [comment]
@zstadler is anything else needed beside site deployment in this issue (I saw that the site is already updated so I think this is already deployed).
If there's nothing else please close this issue and delete the brach.
Thanks for submitting this PR! :-)

**Comment by HarelM** [comment]
Seems like the code is not using this link at all but uses the local copy that is checked in here:
https://github.com/IsraelHikingMap/Site/tree/master/IsraelHiking.Web/sources/fonts/glyphs
This is true for both online and offline - offline is using a local copy of this much like the entire copy of the site code.
I guess this was added as part of idea to use the fonts from the style and probably stayed there when this was removed.
I have no objection to keep it for maputnik though :-) I think the old link can be removed without waiting 90 days.

**Comment by zstadler** [comment]
Since the `glyphs` settings in the styles is overwritten by the site and the app, the IHM style can point to the glyphs' origin at the in `orangemug` git repository, as was done by the ILMTB style. 
The glyphs can also be removed from [`appsettings.Production.json`](https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.Web/appsettings.Production.json) and from the server.
