### ISSUE TITLE
Search to consider the alt_name tag of a place's area

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1291]
## What I expect to happen
The search is expected to consider the `alt_name` tag of a place's area.

## What really happened
The [residential area of `name=גבעת ח"ן`](https://www.openstreetmap.org/way/91039154) has `alt_name=גבעת חן`. However, the search for `גבעת חן` does not find the place.

## What I did that caused the issue - step by step
Search for `גבעת חן`

**Comment by HarelM** [comment]
https://www.openstreetmap.org/node/278474424 The node, which is considered the source of the tags does not have this `alt_name` tag.
Places merge only take the geometry from the area and nothing else.
See the code here:
https://github.com/IsraelHikingMap/Site/blob/dcaa429aa69e55e08ad0fc9a392b70e473ed5f54/IsraelHiking.API/Executors/FeaturesMergeExecutor.cs#L180
I'm not sure what should be the right approach, the nodes and areas for places in OSM is a mess...

**Comment by HarelM** [comment]
This exposes an inconsistent mapping as far as the site is concerned and it is an expected behaviour from the search to behave this way, much like other mapping issues.
Closing, sorry.
