### ISSUE TITLE
Add snappings to the map

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#13]
As a user I would like the cursor to hang on existing routes when I draw my routes so that my route points will be better placed.

**Comment by zstadler** [comment]
Snapping is also relevant to POIs and search results

**Comment by valleyofdawn** [comment]
Not sure about POIs. If you want to mark a tree or spring you see on GE next to a road, it better not snap.

**Comment by zstadler** [comment]
I refer to POI's uploaded to the site from a file, not any arbitrary POI on
OSM or the map...

**Comment by valleyofdawn** [comment]
Why would uploaded POIs be different from manually added ones? The point is, unlike roads, POIs are often selected carefully to point to offroad features, and snapping them may cause errors.

**Comment by HarelM** [comment]
I tend to agree with @valleyofdawn. I think snapping should be kept for route drawing only.

**Comment by zstadler** [comment]
I also agree. I probably misunderstood @valleyofdawn
<https://github.com/valleyofdawn>.

I meant to say we cannot query the OSM DB on the fly for points near the
mouse position.
