### ISSUE TITLE
עין ערבות

### ISSUE THREAD

**Issue by onzd** [IsraelHikingMap/Site#1302]
היי
היום הייתי בעין ערבות בדישון
המיקום במפה מעט מחטיא את המיקום בשטח
כיוון שאני לא רוצה סתם להעמיס את הנקודה על המפה האם מותר למחוק את המיקום השגוי?

**Comment by HarelM** [comment]
מאחר ולא ניתן למחוק נקודות דרך הממשק שלנו הדרך הטובה ביותר היא להזיז את הנקודה בעורך של osm.
בקרוב נוציא גרסה בה ניתן להזיז נקודה קיימת אך כרגע האופציה הזו אינה זמינה.
עדיף לא להוסיף נקודה אם כבר קיימת ועדיף לא למחוק שאז ההיסטוריה נמחקת גם.
מקווה שזה עונה על השאלה...

**Comment by onzd** [comment]
בהחלט תודה

בתאריך שבת, 29 באוג' 2020, 20:55, מאת Harel M <notifications@github.com>:
