### ISSUE TITLE
Not loading on Chrome / PC

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1307]
## Bug
Going to https://israelhiking.osm.org.il/ and the map is not loading

## What I expect to happen
For it to load

## What really happened
Just got the loading animated GIF.  If I wait "forever" like 5 min it may load
![Capture](https://user-images.githubusercontent.com/49042192/93024766-749bf700-f601-11ea-9698-6b7c925dcc51.PNG)

## My environment
* Operating System and version:  Win 10
* Web Browser and version: 

Google Chrome is up to date
Version 85.0.4183.102 (Official Build) (64-bit)

## Things I think the developers should know, images, links etc.
It loaded very fast on Edge (new one chromium based)

**Comment by HarelM** [comment]
Try clicking on the screen, if this helps loading please check your maps to find an invalid map and delete it (either base map or overlay).
I  believe there's a bad map somewhere in your list.
If I'm wrong please press F12, switch to the console tab and add a screenshot to this issue.

**Comment by Tsurha** [comment]
Thank you
