### ISSUE TITLE
מטמון נקודות נמחק והמשתמש מנותק לעתים קרובות

### ISSUE THREAD

**Issue by amiad** [IsraelHikingMap/Site#1308]
## Bug
לפני כשבועיים התחילה לי בעיה באפליקציה באנדרואיד.
בערך פעם ביום היא דורשת להוריד את כל המטמון של נקודות העניין ובמקביל המשתמש מתנתק.
ניסיתי לאפס את ההגדרות בתקווה שמדובר על בעיה חד פעמית אבל היא חוזרת שוב ושוב.

יש לי 3 ג״ב פנויים במכשיר ואני נותן לו כל פעם להוריד את הנקודות אבל אחרי יום הבעיה שוב חוזרת.

## My environment
Xiaomi Mi A2 with Android 9

**Comment by zstadler** [comment]
במקרים כאלו הכי טוב זה לשלוח דיווח מהאפליקציה בדיוק כשקוריית התקלה
ללא המידה מהמכשיר יהיה לנו קשה לברר מה קורה שם.
אם זה קורה פעם ביום, אנחנו מקוום שתוך ימים ספורים תוכל לשלוח לנו דיווח מתוך האפליקציה

**Comment by HarelM** [comment]
יש חדש? ללא דיווח מהאפליקציה יהיה קשה לנו לטפל בבעיה...

**Comment by amiad** [comment]
כרגע הבעיה לא חזרה. אני מקוה שפשוט נפתר מאיזו סיבה. אם יחזור אז אדווח.

**Comment by zstadler** [comment]
תודה
