### ISSUE TITLE
תמיכה ב Cycling Track

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1309]
## Feature

פאמפטרק הרצליה. מסומן היטב ב-OSM כ-Cycling Track. לא מוצג במפת האופניים. אם תוכלו לתמוך. בתודה.
כאן:
https://israelhiking.osm.org.il/map/19.00/32.1732/34.8270

**Comment by HarelM** [comment]
Moved to the vector map repository: https://github.com/IsraelHikingMap/VectorMap/issues/51
Thanks for reporting!
