### ISSUE TITLE
Access to device location in the background requires permission

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1313]
Background recording is blocked on Android since the move to SDK 29

See https://developer.android.com/about/versions/10/privacy/changes#app-access-device-location

**Comment by HarelM** [comment]
See here:
https://github.com/mauron85/cordova-plugin-background-geolocation/issues/688
I'll add it manually.

**Comment by HarelM** [comment]
The change for using target sdk version 29 was made after the release of version 9.3.136 which is the latest officially released version. Commit: https://github.com/IsraelHikingMap/Site/commit/0a9cae5c49ad75f04359bd5edbe5f63902130a04
However, looking at the documentation of what sdk version means, it doesn't look like this should matter.
I would advise to check if the officially released version (9.3.136) does suffer from the same issue just to be on the safe side.
Never-the-less, changing target sdk version is required by google so the change is mandatory and can't be reverted.

**Comment by zstadler** [comment]
| Build   | BG Loc | Commit   | Comment |
|---------|--------|----------|---------|
| 9.3.196 | yes    | 4fe9c1c5 | Access to device location in the background requires permission #1313 - initial fix.
| ... | ... | ... | ... |
| 9.3.138 | no     | 0a9cae5c | Update android target SDK version to be 29 as requested by google
| 9.3.137 | yes    | f1b504aa | Fixes #1289 - Increase accuracy of unmapped highways
| 9.3.136 | yes    | 476c02f2 | Fixes #1293 - geo scheme causes android app to crash - Fix traces and shares dialog behaviors.
