### ISSUE TITLE
GPSBabel doesn't run on linux or mac

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1316]
## What I expect to happen
GPSBabel should be able to run on linux (ubuntu) or macos as it is required for the site to operate

## What really happened
It fails - can be easily seen in the tests on a CI server

## What I did that caused the issue - step by step
Made the site work on a machine that doesn't run windows.

## My environment
* Operating System and version: Ubuntu 18
* Web Browser and version: Any

## Things I think the developers should know, images, links etc.
GPSBabel is a NuGet package I created by compiling the source code.
It might be a good idea to just make sure GPSBabel is installed on the machine that runs the server as a pre-requisite, preferably using docker when possible I guess...
See this image for example:
https://hub.docker.com/r/jamesmstone/gpsbabel

**Comment by HarelM** [comment]
Somewhat related in order to be able to build the apk on Ubuntu as well:
https://gist.github.com/guipmourao/3e7edc951b043f6de30ca15a5cc2be40

**Comment by zstadler** [comment]
I'm not sure we need to build GPSBabel by ourselves.
The docker-ized version works well on the Linux server:

```
$ docker pull jamesmstone/gpsbabel
Using default tag: latest
latest: Pulling from jamesmstone/gpsbabel
ff3a5c916c92: Pull complete 
678d4a0fbc90: Pull complete 
Digest: sha256:e102af5f94e6035be1ed67a9ad73f40e8806a2153aa7a5288b3b085b423611e2
Status: Downloaded newer image for jamesmstone/gpsbabel:latest
docker.io/jamesmstone/gpsbabel:latest
```
```
$ docker run jamesmstone/gpsbabel -V

GPSBabel Version 1.5.4

```

**Comment by zstadler** [comment]
On Ubunto you may also install the binaries with `sudo apt install gpsbabel`:
```
$ gpsbabel -V

GPSBabel Version 1.5.4

```

**Comment by HarelM** [comment]
The problem here, the way I see it is the variety of environments.
The server can't run docker and it runs windows, currently.
My dev env has docker for windows and mac but gbsbabel is a commandline tool so I can't place it on another server right now...
If I change the code on my dev env to use docker I still need to make sure it runs on the server...
I had a thought to use gpsvisualizer website instead of using a local executable to reduce the complexity of setting up an environment...
