### ISSUE TITLE
Reduce buttons footprint

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1319]
## Feature
As a mobile user I would like to be able to see more of the map at certain occasions.
There are times when I need the editing buttons available on screen and there are times when I don't need them.
In order to achieve this there's a need to rethink how the app interface looks and works.
The following presentation is an initial work on the subject.
[Mock-up.pptx](https://github.com/IsraelHikingMap/Site/files/5354768/Mock-up.pptx)
There are sill open issues and things we have discussed about this presentation but it has the gist of the solution to this issue.
This issue follows the #1180 which has the similar problem but a different approach to the solution.

Must before wider audience:
- [x] Align icons
- [x] Find a solution to intermediate menus - only files currently...?
- [x] Think about creating two menus - one for the profile and the second for all the other functionality
- [x] Add language and edit in OSM
- [x] Upload to beta for larger audience
- [x] Add css from OSM user controller
- [x] Simplify user menu: remove picture, remove rankings, remove edits
- [x] Change "edit" to "plan" or something else that is not edit to distinct it from map editing.
- [x] Remove download support link - i.e. download will only be available when using the info sidebar and not from `https://.../download`

Must before full release:
- [x] Persists UI state - Improve to use state and not current service (in memory only)
- [x] Close info button
- [x] ~Add minimize button to route statistics? Add it to the main menu like search and plan?~ will be added later or not at all
- [x] When selecting search - open to allow search
- [x] Close layers button - larger
- [x] Find a way to show what's currently is selected (Maybe make the menu bold)
- [x] Improve the look of the share and files dialog - align icons, scroll down when opening save-as
- [x] Close files dialog after successful file open
- [x] Fix report a problem work when there's no user
- [x] Define initial (and default) state of controls
- [x] ~Better support for desktop? this might need an issue of its own as I'm not sure this is a show stopper~ might be considered, but not a part of this issue
- [x] Remove margin in left opening panel and make it above the left location control
- [x] search should not be open on initial load if the button is shown.
- [x] Add create a share to my shares dialog
- [x] Make the last four menu items under "more..."?
- [x] Change share name in the files and share dialog to better explain that this is for uploading to the cloud as well
- [x] Make sure google analytics are configured correctly
- [x] Make search focus when opening it from the menu
- [x] Make statistics toggleable

**Comment by HarelM** [comment]
Initial Menu, offline, logged out.
![image](https://user-images.githubusercontent.com/3269297/95778721-5c3afd00-0cd1-11eb-8b5f-b19549372527.png)
When online the profile picture will appear or the frown face.

**Comment by zstadler** [comment]
The issue with the bottom has a strange gap. 
![Screenshot_20201014-235658.jpg](https://user-images.githubusercontent.com/1304610/96044526-36e8f300-0e79-11eb-97aa-adb86a4aee02.jpg)
Android 10

**Comment by zstadler** [comment]
The attribution link is missing from the "about" page. Perhaps it was intended to be where the layers icon appears now

![Screenshot_20201015-000320.jpg](https://user-images.githubusercontent.com/1304610/96045162-3e5ccc00-0e7a-11eb-8f8b-01232a0ada6a.jpg)

**Comment by HarelM** [comment]
Only the text is missing due to using the text from the regular site...

**Comment by HarelM** [comment]
>The the bottom has a strange gap.

I don't understand this statement, can you please elaborate?
Also please check if this exists in the regular site as well as I'm not sure I introduced something new here...

**Comment by zstadler** [comment]
Tested the latest version in the browser:

- I could not find how to remove the "search" or "edit" and return to the minimal screen. In the mock-up, it was done by clicking the menu button.
- I could not find a way to close the "about/legend" dialog.
- Reloading the page moves to the production site. This disrupts the ability to return to the initial view when confused or stuck.
- Already listed above, but IMO needs to be fixed before requesting public feedback: "when selecting search - open to allow search". In the new UX, there is no need for a "closed" search button like this
  <img width="33%"  src="https://user-images.githubusercontent.com/1304610/96216076-21aeba00-0f88-11eb-8518-30b692930b5e.jpg"/>
- When selecting edit there are 2 different visuals for "mode not selected" state: with blue buttons and with black buttons:
  <img height="100px" src="https://user-images.githubusercontent.com/1304610/96216608-6850e400-0f89-11eb-8185-6a2904fe996b.jpg"/> <img height="100px" src="https://user-images.githubusercontent.com/1304610/96216611-69821100-0f89-11eb-823c-8ae19d46ce5b.jpg"/>
- When selecting edit there are 2 different icons for the delete button. I suggest using the "trash can" icon
   <img height="100px" src="https://user-images.githubusercontent.com/1304610/96216870-017ffa80-0f8a-11eb-8f5e-cdee6e598373.jpg"/>  <img height="100px" src="https://user-images.githubusercontent.com/1304610/96216873-02b12780-0f8a-11eb-8d04-d911eb76cf40.jpg"/>

**Comment by HarelM** [comment]
Removing elements hasn't changed from previous version - selecting them again in the menu will remove them - this is the selected missing UX bullet above.
Edit mode hasn't changed and the color is coming from the selected route, which can be none (black) when the app starts. I don't have plans to change it as part of this issue/version.
I'll change the delete icon to be consistent.

**Comment by HarelM** [comment]
See linked PR.
Waiting on the above bottom while line to be verified and hopefully fixed to close this issue and merge the PR.

**Comment by zstadler** [comment]
![Screenshot_20201020-212220.jpg](https://user-images.githubusercontent.com/1304610/96634094-aac84700-1322-11eb-96c4-94a4e8d286ea.jpg)
Once the "more..." menu entry is selected, it never shows again

**Comment by zstadler** [comment]
![Screenshot_20201020-212608.jpg](https://user-images.githubusercontent.com/1304610/96634183-d1867d80-1322-11eb-9e52-8610215e2863.jpg)

The location arrow is shown when the GPS was deactivated.

When the GPS is reactivates, the arrow is gone.
![Screenshot_20201020-212741.jpg](https://user-images.githubusercontent.com/1304610/96634354-0db9de00-1323-11eb-96c2-c2b8b1e5856d.jpg)

**Comment by zstadler** [comment]
The green frames are not aligned with the buttons ![Screenshot_20201020-212353.jpg](https://user-images.githubusercontent.com/1304610/96634530-5376a680-1323-11eb-9615-4a32bfc6a63b.jpg)

**Comment by HarelM** [comment]
> Once the "more..." menu entry is selected, it never shows again

Please use the app to test and not the beta site. The app and therefore the version that should be released has a "less..." button that does not exists in the beta as I have stopped updating the versions shortly after the poll.

> The green frames are not aligned with the buttons

I didn't change that control. Are you testing it with firefox? If so it's probably another firefox bug that should exist in the regular site as well. Less than 2% are using firefox, probably even less are using firefox on mobile device, so I'm not planning on investing time in supporting this browser and mode, I don't think test should be made with it to be honest.

> The location arrow is shown when the GPS was deactivated.
> When the GPS is reactivates, the arrow is gone.

Location logic was not altered, probably not related to this issue, please test it with the regular site as well.

Please open separate issues as this issue was implemented and merged to master, I believe there's no need to continue this thread.
