### ISSUE TITLE
Facebook in-app-browser

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1320]
## Feature
As a user who installed the IHM app and uses Facebook on mobile device it is not intuitive to make the Facebook app open the IHM app when opening a link to IHM website such as shares etc.
There's a need for a banner to allow the user to open the link in the regular browser.

**Comment by HarelM** [comment]
Since there's already a banner for suggesting to use the mobile version I will use it to show a message about facebook.

**Comment by zstadler** [comment]
Is there a way for the site to know it is running in the Facebook browser and not in an "ordinary" browser?

**Comment by HarelM** [comment]
As far as I've read, but haven't tested, there should be a way as descrived here:
https://stackoverflow.com/questions/31569518/how-to-detect-facebook-in-app-browser/32348687
(I've forgot to attach this SO question to the start of the thread although I found it when looking for a solution).

**Comment by HarelM** [comment]
I have decided to create a new dialog, just for this, to avoid mixing not related code. I have used the same design and behaviour...
