### ISSUE TITLE
פתיחה של קישור באייפון באפליקציה ולא בדפדפן

### ISSUE THREAD

**Issue by orenschu** [IsraelHikingMap/Site#1322]
## Bug/Feature
(Delete the non-relevant)
מאוד מציק שכשולחים לי לינק למסלול ואני פותח באייפון הוא אוטומטית נפתח בדפדפן ואין דרך לפתוח באפליקציה. הבנתי שזה אולי מורכב אבל מה שחייב להיות פשוט זה לאוסיף פיצ׳ר באפליקציה שמאפשר להעתיק אליו לינק. זה היה פותר את הבעיה. כרגע יש וורקאראונד נורא מעצבן - שאני צריך לשמור בעצמי בדפדפן ואז יכול לפתוח באפליקציה.
תודה, אורן
## My environment
* Operating System and version:
* Web Browser and version:

**Comment by HarelM** [comment]
תוכל לפרט בדיוק את הצעדים שעשית?
על פניו מימשנו את זה בגרסה האחרונה.
אם הכוונה בפתיחת קישור ספציפית מהאפליקציה של פייסבוק אז יש קריאה פתוחה על הנושא.

**Comment by orenschu** [comment]
שלום הראל,
אני רוכב הרבה עם גיא (שחר). כשאני מקבל ממנו לינק למסלול בוואטסאפ ולוחץ על הקישור באייפון שלי, זה נפתח בדפדפן. לא מצאתי דרך (אולי פספסתי עדכון?) להעלות לינק דרך האפליקציה ולא מצאתי דרך לפתוח ישירות מתוך וואטסאפ.
נשמע כמו הקריאה הפתוחה בנושא - לא? אבל מכיוון ששמעתי מגיא שזה מורכב לפתוח ישירות מהאפליקציה של פייסבוק (דהיינו וואטסאפ), רציתי להציע שתוספו באפליקציה אפשרות לפתוח לינק. ואז copy/paste פשוט ו- voila. לא?
תודה
אורן


On 16 Oct 2020, at 16:14, Harel M <notifications@github.com<mailto:notifications@github.com>> wrote:



תוכל לפרט בדיוק את הצעדים שעשית?
על פניו מימשנו את זה בגרסה האחרונה.
אם הכוונה בפתיחת קישור ספציפית מהאפליקציה של פייסבוק אז יש קריאה פתוחה על הנושא.

**Comment by HarelM** [comment]
תוכל בבקשה לשלוח לי צילומי מסך או סרטון של הבעיה?
אני רוצה לראות מה התהליך.
אגב, אם שולחים לך קישור למייל זה עובד? או שגם לא?

**Comment by orenschu** [comment]
ואללה - כנראה שפשוט הייתי צריך לעדכן את האפליקציה! זה אכן עובד עכשיו - המון תודות!
אורן


On 16 Oct 2020, at 17:42, Harel M <notifications@github.com<mailto:notifications@github.com>> wrote:



תוכל בבקשה לשלוח לי צילומי מסך או סרטון של הבעיה?
אני רוצה לראות מה התהליך.
אגב, אם שולחים לך קישור למייל זה עובד? או שגם לא?

**Comment by HarelM** [comment]
בכיף! תהנה!

**Comment by HarelM** [comment]
Was implemented in #1276.
