### ISSUE TITLE
Can't get GPS position while inside a building

### ISSUE THREAD

**Issue by onzd** [IsraelHikingMap/Site#1323]
היי
אמנם לא קריטי אבל בחדר בבית או בכלל בתוך מבנה באפליקציה אין אפשרות לקבל מיקום לעומת זאת בו בזמן בלוקוס וויז ובאתר עצמו הgps  ננעל מיידית

**Comment by HarelM** [comment]
תודה על הדיווח.
נבדוק אם אפשר לשפר את המצב.

**Comment by onzd** [comment]
תודה רבה על כל המאמצים שלכם

‫בתאריך יום א׳, 18 באוק׳ 2020 ב-14:58 מאת ‪Harel M‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by HarelM** [comment]
Mainly notes to myself:
We are using a plugin to get accurate position from the device.
Accurate position requires actual GPS to work and not relay on other heuristics which might take long to get, especially inside a building.
While the scenario described is somewhat less interesting when you actually want to use the app in the field it is very relevant for getting a sense of trust when operating the app at home to see that it "works".
A solution to this issue can be supplied by only getting a course location when starting the GPS for the first time or after it was disabled.
The solution would be to ask for a position from the browser only once when starting to track as the browser gives course location by default.
