### ISSUE TITLE
Improve UX for Desktop users - keep the main menu options visible

### ISSUE THREAD

**Issue by amiad** [IsraelHikingMap/Site#1324]
## Feature

The menu in the beta site seen identical on PC and mobile.
I understand why to hide the menus in mobile but on wide screen have enough place to full menus.

I suggest to show all the menus on PC and "hamburger" menu on mobile only.
Maybe to load all the menus and use CSS media queries to hide them on narrow screens.
Search found some ideas for Angular too. [[1](https://material.angular.io/cdk/layout/overview)][[2](https://stackoverflow.com/questions/48628220/using-proper-css-media-queries-in-angular)]

**Comment by HarelM** [comment]
The following example is basically the solution to it without using any css:
https://stackoverflow.com/questions/57475919/angular-material-sidenav-always-open-on-desktop
The problem is that sidenav is not a menu and therefore will occupy the entire length of the screen when open... But it might not be so bad so it might be a possible solution. I'll need to play with it...

**Comment by HarelM** [comment]
I've thought about it some more and you are welcome to submit a PR.
Most of the menu items are not interesting.
Those that are interesting can be kept on the screen in latest version (search, planning, statistics).
So I see very little benefit in implementing this, moreover the fact that this is the same behavior between mobile app and desktop app has the extra effect of making things easy to orient when switching between the two.
Nevertheless, I'll keep this issue open until it automatically is closed by the bot or if someone will send a PR...

**Comment by amiad** [comment]
I know CSS (and more web developing) but not angular and so can't help now.
I think slight differences between PC to mobile make sense. Maybe someone want to stay the layouts sidebar open on PC.
