### ISSUE TITLE
sound back to segment 

### ISSUE THREAD

**Issue by nadavheimann** [IsraelHikingMap/Site#1326]
Feature

## What I expect to happen
when I back today segment some meters I want to hear sound (after I lost 50 meter before) 

## What really happened
nothing 

## My environment
* Operating System and version: android.... 
* Web Browser and version:

**Comment by HarelM** [comment]
Thanks for taking the time to request this feature!
Can you fully describe your scenario?
From my understanding, which might be very partial, once you hear a sound that you went off the track you'll need to look at the map and see that your driving in the right direction and look around to see your route in reality.
If so, why would you need a sound assuming you look at both the map and the surrounding?
I'm guessing my assumption are incorrect, so please elaborate on the scenario on which this feature is helpful.

**Comment by nadavheimann** [comment]
OK, also in Garmin you get alarm off /in track.
another sound approve me back 🛷 track.
at my first ride I was looked another 10 seconds to approve that.
may be also a ☑ box at advance settings

**Comment by HarelM** [comment]
לא בטוח שהבנתי...
מה ששאלתי זה אם תוכל לתאר את התרחיש בו הוספת הקול יועיל בשימוש באפליקציה.
למיטב הבנתי, כשאתה סוטה ממסלול אז יש צליל התראה.
בשלב הזה אתה צריך להסתכל על המפה ובשטח ולהבין איך לחזור חזרה למסלול.
אם גם ככה אתה מסתכל במפה איך צליל של חזרה למסלול יכול לעזור?
אני שואל כי אני באמת לא מבין.
אני מבין שיש את זה באפליקציות\מכשירים אחרים וזו לא שאלה של איפה לשים את זה.
אלא באמת למה זה נחוץ?

**Comment by nadavheimann** [comment]
כמו שכתבתי, אולי לא הצלחתי להסביר טוב באנגלית, סורי,
אם היה לי צליל חזרה 
א - הייתי יודע שאני בכיוון לחזור
ב- לא הייתי מאיך להמשך להסתכל שניות נוספות שאני נוסע בדיוק על השביל, בפועל טעיתיבשביל

בריצה עם גרמין זה עזרתך לי מאוד 
לדעתי גם ברכיבה זה יעזור, 
צריך כמובן צליל אחר

**Comment by HarelM** [comment]
אתה יכול להגדיר את החוויה ברמה יותר פרקטית?
כלומר אם אתה מקבל התראה 50 מטר מהמסלול על סטייה מתי תרצה לקבל התראה שחזרת? אם אתה בקרבת 50 מטר מהמסלול? כי נשמע שזה יכול לבלבל...
@valleyofdawn 
אשמח להבהרה לנחיצות של פיצ'ר כזה לדעתך

**Comment by nadavheimann** [comment]
הייתי שמח לקבל התראה כאשר אני מתקרב 20 מטר רק במקרה שיצאת 50 לפני, לא כל הרחקה מהמסלול תצפצף.

מקווה שהבנת
