### ISSUE TITLE
בית ברכה - ממוקם לא נכון

### ISSUE THREAD

**Issue by Oritk** [IsraelHikingMap/Site#1331]
## Bug/Feature
(Delete the non-relevant)

## My environment
* Operating System and version:
* Web Browser and version:

**Comment by HarelM** [comment]
תודה על הדיווח. ניתן דרך המחשב לעדכן את המיקום ע"י עריכת המפה. כל משתמש יכול :-)
יש קובץ שאלות נפוצות בקבוצת הפייסבוק ותחת אודות באפליקציה, אני ממליץ לעבור עליו.
מאחר וזו לא בעיה בקוד של האתר אני אסגור את הקריאה.
כמובן שאם יש עוד שאלות ניתן להמשיך להתכתב פה.

**Comment by Oritk** [comment]
אוקי - תודה על התשובה
אורית
