### ISSUE TITLE
Add shutdown button

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1336]
## Feature
Since iOS users do not have the back button currently there's no "safe" way to turn off the app (by safe I mean storing everything to the database and closing elegantly).
We should consider adding a shutdown button to allow shutting down the app when using an iOS device.

**Comment by HarelM** [comment]
Android can also benefit from it. vote here if you want this for Android as well

**Comment by HarelM** [comment]
Sorry for anyone who voted, but this can't be added since iOS can reject an app that implements this behavior.
In android you can press the back button twice so there's no real need for this feature.
Although it was implemented but not released, I will remove it.
Sorry...

**Comment by zstadler** [comment]
Waze on iOS has a shutdown button
![IMG-20201107-WA0005__01.jpg](https://user-images.githubusercontent.com/1304610/98444225-2c88e480-2119-11eb-8e9d-c0ff78ad1dbf.jpg)

**Comment by HarelM** [comment]
So their app can be rejected in theory, I'm not planning on taking that chance...
