### ISSUE TITLE
Unable to upload a new a public POI

### ISSUE THREAD

**Issue by onzd** [IsraelHikingMap/Site#1339]
אני מקבל הודעת שגיאה
![WhatsApp Image 2020-10-16 at 18 50 42](https://user-images.githubusercontent.com/43242549/97088354-de63e380-1638-11eb-9975-596654f56b5a.jpeg)

**Comment by HarelM** [comment]
תודה על הדיווח.
תוכל לתאר בדיוק מה הצעדים שביצעת?
ייתכן וזה קשור לעדכון האחרון של האתר...

**Comment by onzd** [comment]
בשטח ניסיתי להעלות נקודה חדשה וקיבלתי את ההודעה
וגם עכשיו באתר במחשב אני מקבל אותה הודעה בדיוק

‫בתאריך שבת, 24 באוק׳ 2020 ב-20:56 מאת ‪Harel M‬‏ <‪notifications@github.com
‬‏>:‬

**Comment by onzd** [comment]
שלחתי דיווח גם דרך האפליקציה עם מספר הפניה

‫בתאריך שבת, 24 באוק׳ 2020 ב-21:01 מאת ‪ofer kapon‬‏ <‪oferkapon@gmail.com
‬‏>:‬

**Comment by HarelM** [comment]
אני חושב שאני מצליח לשחזר את הבעיה.
תודה על הדיווח.
related to #1068.
