### ISSUE TITLE
Adding a barrier distorted the nearby highway

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1342]
## What I expect to happen
The addition of a barrier would not distort the nearby highway it was added to.

## What really happened
In [changeset 92985468](https://www.openstreetmap.org/changeset/92985468) a new ["cattle grid" node](https://www.openstreetmap.org/node/8041952273) was added to a nearby `highway=path`.

![image](https://user-images.githubusercontent.com/1304610/97120014-d4b3ac00-171c-11eb-8439-b2b7c4400694.png)
Green: new version. 
Red: old version

The new node was added between existing nodes 2 and 3. It should have been added between existing nodes 1 and 2. As a result, the path is now distorted.

## What I did that caused the issue - step by step
Added a new "simple POI".

## Things I think the developers should know, images, links etc.

[Achavi map of the changeset](https://overpass-api.de/achavi/?changeset=92985468&zoom=21&lat=33.0336&lon=35.41934&layers=B0FTTFT)

**Comment by HarelM** [comment]
Thanks for testing this and reporting here with all the information! This is very helpful! :-)

**Comment by HarelM** [comment]
@zstadler I can't seem to be able to reproduce this using my unit tests.
Is there a way for you to send me the coordinates of the old way and the coordinates of the gate so I can try and write a test as close to the problem as possible?

Feel free to also take a look at the code here, in theory it seems that the behavior you expect is what's written in the code:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.API/Executors/SimplePointAdderExecutor.cs#L157L179

**Comment by HarelM** [comment]
Hmm... Looking at the history it seems that there were two edit on the same way in the same day.
This might explain the miss-location in the second edit as adding a new node might cause this shift.
As far as I can understand the first open gate was places correctly and only the cattle grid suffered an incorrect location, right?
I'll continue to look at it tomorrow with that in mind.

**Comment by zstadler** [comment]
> @zstadler I can't seem to be able to reproduce this using my unit tests.
> Is there a way for you to send me the coordinates of the old way and the coordinates of the gate so I can try and write a test as close to the problem as possible?

Please use the "Export" button of the Overpass Turbo queries below to download the geometries as GeoJSON, GPX, KML, or raw OSM data.

- [way 446072284 before changeset 92985468](http://overpass-turbo.eu/s/Zsz)
- [node446072284 after changeset 92985468](http://overpass-turbo.eu/s/ZsA)

**Comment by zstadler** [comment]
> 
> 
> Hmm... Looking at the history it seems that there were two edit on the same way in the same day.
> This might explain the miss-location in the second edit as adding a new node might cause this shift.
> As far as I can understand the first open gate was places correctly and only the cattle grid suffered an incorrect location, right?
> I'll continue to look at it tomorrow with that in mind.

The code downloads the latest version of the way from the OSM server in order to get the latest version id. Otherwise the upload of the new version would have failed. It is unlikely that the code is using the version number from that download, but takes the geometry from a different source.

**Comment by HarelM** [comment]
Actually the geometry is taken from the highways database, which is a clone of OSM and might be outdated in this case.
What I can think of is that after closing the changeset the fetch from OSM retrieves an older version and not the updated version, this version is stored in the database and is used as the reference for the geometry the next time this code runs.
Checkout this lines:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.API/Executors/SimplePointAdderExecutor.cs#L50L54
They assume the way is already updated in OSM when requesting a complete way, I'm not sure this is a valid assumption...

**Comment by zstadler** [comment]
Does the code assume that a way was unchanged by anyone since it was last updated in the server's database?
