### ISSUE TITLE
Opening a share while recording

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1347]
## What I expect to happen
Needs discussion

## What really happened
If a share is opened when the app is recording, the recording is aborted and lost.

**Comment by HarelM** [comment]
As far as I remember, we agreed that this is not the place to add things we need to discuss about...

**Comment by HarelM** [comment]
Moved to wiki.

**Comment by zstadler** [comment]
Summary of an offline conversation:

The UX priorities in this context are:
1. Avoid data loss
1. Minimize user interaction

Other use-cases considered include opening a share while 
- other routes exist
- editing a route

The proposed UX is:
- The routes of a share will be added to the existing set of routes rather than replace them, as currently done when opening an external file.  In particular, similar handling of potential name collisions with existing layers.
- The visible layers will be replaced with the layers defined in the share, as currently done when opening a share. In particular, similar handling of previously-visible overlays.
- There is no need to make any changes in the GUI.

**Comment by HarelM** [comment]
This should also apply to selecting a share to show in the shares dialog - the current behavior will delete all routes including a recording.
Since there's another action to add the share's routes this action is specific to viewing and updating a share and therefore should clean the exiting routes. I will add a confirmation dialog to make sure the user understands that everything will be cleared after pressing this to avoid unintentional data loss.

**Comment by HarelM** [comment]
This probably needs better testing than I made.
i.e. 
* Open an external link share when a planned route is on screen, make sure the routes are there and the selected route was not changed
* Open an external link share when a recording is on screen, make sure the routes are there and the selected route was not changed.
* Open a share using the "eye" icon in the shares dialog and device what to do
* Use the "+" button in the shares dialog
* Open an external file url link and make sure it behaves the same as above (I think in groopy there are those kind of links).
* any other tests you can think of...
