### ISSUE TITLE
נעלם התפריט פתיחת או שמירת קובץ

### ISSUE THREAD

**Issue by Kingsfield59** [IsraelHikingMap/Site#1348]
נעלם התפריט פתיחת או שמירת קובץ

**Comment by HarelM** [comment]
תודה על הדיווח, אבל התפריט לא נעלם הוא הועבר למקום אחר.
תחת תפריט - שיתוף - קבצים.

**Comment by Kingsfield59** [comment]
תודה
מאוד מרוצה מהאפלקציה

**Comment by HarelM** [comment]
בכיף!
מקווים שמספיק מרוצה כדי לרכוש את מפות האופליין :-) אבל גם לא זה בסדר :-)
