### ISSUE TITLE
is it possible to add the OCM as additional layer/Overlay

### ISSUE THREAD

**Issue by eligrt** [IsraelHikingMap/Site#135]
i wonder if it possible to add the Open Cycle Map as another view/layer
i.e.
http://www.opencyclemap.org/?zoom=10&lat=31.67757&lon=34.95901&layers=B0000

**Comment by HarelM** [comment]
Sure, on the right side there is the layer manger, hover on it to expand it. Click on the yellow gear to open advanced options. Click the green add layer and insert the above address - replace the numbers with ...zoom={z}&lat={x}&lon={y}...

**Comment by HarelM** [comment]
Sorry, my bad, the right address for their tile server is the following:
https://b.tile.thunderforest.com/cycle/{z}/{x}/{y}.png

**Comment by zstadler** [comment]
Yes, you can add it yourself. The map is provided by http://www.thunderforest.com/

- Click the gear wheel "Advanced Setup" button at the bottom of the layers list.
- Click "+ Add Base Layer"
- Fill the form:
  - Name: Open Cycle Map
  - Address: https://c.tile.thunderforest.com/cycle/{z}/{x}/{y}.png
  - Min Zoom: 0
  - Max Zoom: 22
- Click the v "OK" button

**Comment by eligrt** [comment]
Perfect!
thank you all

**Comment by eligrt** [comment]
is it possible to add also the Google Terrain as a layer?
i.e.
https://www.google.co.uk/maps/@31.7627581,34.5379021,9.27z/data=!5m1!1e4

**Comment by zstadler** [comment]
You will have to do some reverse-engineering to find the address pattern for Google Terrain tiles.
We would not like to publish such addresses unless permitted by their supplier.
