### ISSUE TITLE
Missing display of areas 

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1351]
## Bug
לא מוצגים אזורים המסומנים כשטח למשל
* פארק בגין - פארק דרום
* גולף געש
* בית ברל

## What I expect to happen
שיוצג לפחות השם ועדיף גם השטח

## What really happened
לא רואים כלום. לפעמים השטח מוצג בצבע שונה
האזורים קיימים באואסאם

![בגין](https://user-images.githubusercontent.com/49042192/97789925-fdc8b680-1bcc-11eb-96d5-4121096c7c9f.PNG)
![גולף געש](https://user-images.githubusercontent.com/49042192/97789927-00c3a700-1bcd-11eb-9cde-90b094364d9f.PNG)

## What I did that caused the issue - step by step
עברתי על מגוון זומים לבדוק

## My environment
* Operating System and version: בחלונות 10
* Web Browser and version: כרום

**Comment by HarelM** [comment]
Thanks for taking the time to report this issue.
I have moved this to the relevant repository.
Closing it here...
