### ISSUE TITLE
Terminology change: share/save -> save/export

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1352]
#### Share &rarr; Save
The term _"share"_ for keeping private route/s, POI and layers on the server was coined when this was the primary intended use of this capability. In time, we've found that this capability is seen and used in a broader way - an ability to save in the cloud/server, not necessarily for sharing with other users. IMO, the terms _"save"_ and _"My saved routes"_ describe this capability more accurately.

#### Save &rarr; Export
Currently the terms _"save"_ and _"save as"_ are used for the conversion of route/s and POIs to an external format, such as GPX file. Despite our efforts to keep as much information as possible in the default GPX file, this conversion looses some of the information that is stores in a share: the visible layers are not includes and the POIs are disassociated from their respective routes. When using _"save as"_, additional information may be lost. IMO, the terms _"export"_ and _"export as"_ describe this capability more accurately.

**Comment by zstadler** [comment]
### Implementation
The terminology change will be done by changing the relevant texts in the translation - @zstadler 

The current icon for "שיתוף - קבצים" &rarr; "שמירה - יצוא" will be kept as-is, indicating the potential use of the operations for sharing with others. The "שיתוף" &rarr; "שמירה פרטית" icon in the control will be replaced with a cloud icon. It is in line with the other icons the describe the means for a save/export - @HarelM

**Comment by HarelM** [comment]
@zstadler please note that as part of #1350 there might be a change in the way the app works in terms of saving to files. i.e. the current direction is to share a file and not save it to the file system (relevant for both regular file and save-as functionality).
I'm guessing the terminology should reflect that somehow, and if not, you can ignore this comment.
Just wanted to make sure you won't miss this change in case it occurs, so please check with me before submitting the translations.

**Comment by zstadler** [comment]
The Hebrew and English translations have been updated according to the new terminology.

**Comment by HarelM** [comment]
Great! here's some screenshots:
![image](https://user-images.githubusercontent.com/3269297/99574872-95594200-29e0-11eb-9ece-71703ee2916a.png)
![image](https://user-images.githubusercontent.com/3269297/99574953-aefa8980-29e0-11eb-8a21-1a93485352f2.png)
![image](https://user-images.githubusercontent.com/3269297/99575007-c0dc2c80-29e0-11eb-8bbe-c0fa3c9674e6.png)
![image](https://user-images.githubusercontent.com/3269297/99575296-1a445b80-29e1-11eb-92f5-a001bb710b65.png)
![image](https://user-images.githubusercontent.com/3269297/99575354-31834900-29e1-11eb-8c2a-b2e16cba96e8.png)
![image](https://user-images.githubusercontent.com/3269297/99575388-3cd67480-29e1-11eb-9cdc-55aaeff94398.png)
![image](https://user-images.githubusercontent.com/3269297/99575451-54156200-29e1-11eb-8e18-df679c076ac8.png)
![image](https://user-images.githubusercontent.com/3269297/99575984-16fd9f80-29e2-11eb-9614-0ebeec30e25f.png)
![image](https://user-images.githubusercontent.com/3269297/99576129-3eed0300-29e2-11eb-876e-356684a6ba14.png)

**Comment by HarelM** [comment]
Proposed new icons where "save" will probably be "export"...
![image](https://user-images.githubusercontent.com/3269297/99587861-6a77e980-29f2-11eb-9d85-c8038c09f858.png)
![image](https://user-images.githubusercontent.com/3269297/99588302-086bb400-29f3-11eb-8d1a-46771217d634.png)
