### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by arielki** [IsraelHikingMap/Site#1354]
## Feature
keyboard shortcuts

## What I expect to happen
Now with the new UI, it takes more (mouse) clicks to use the different menu options.
Please add keyboard shortcuts (similar to the known CTRL-X, CTRL-V, etc.) for common needs when using the application on a PC, mainly for planning routes/tracks.
Some examples:
- Switch to biking Map
- Switch to hiking map
- Switch to next map in list
- Show/hide "Maps and Layers" menu
- Save track
- Others..

and add the shortcut description on the UI next to the function itself.

Thank you!

**Comment by HarelM** [comment]
Thanks for the suggestion. :-)
Just out of curiosity, do you know which shortcut keys exist right now?

**Comment by arielki** [comment]
Hi,
Not aware of any existing shortcuts..
If there are any, where are they documented?

**Comment by HarelM** [comment]
Things like ctrl+f for search, crtl+o for open, ctrl+s for save and ctrl + z for undo exist, or existed in the past.
There was a help tab that was never used and also they are common for all windows applications so there's no real need to document it.
But the fact remains: it's an extremely advanced feature which most users won't use so the ROI for implementing this is very low...
If you wish to implement this I won't stop you :-) Feel free to submit a pull request.

**Comment by arielki** [comment]
I think that with the new UI, keyboard shortcuts will be very helpful and
effective, and as long as people will know they exist, they will be widely
used.
I'm not a programmer, so i can't implement myself..
