### ISSUE TITLE
נקודה שסימנתי כאנדרטה לא מופיעה

### ISSUE THREAD

**Issue by onzd** [IsraelHikingMap/Site#1355]
אם אני לוחץ על חיפוש היא נמצאת

![1](https://user-images.githubusercontent.com/43242549/98079483-87ea7680-1e7c-11eb-8a88-8058caad2a5a.jpg)

**Comment by HarelM** [comment]
הנקודה סומנה במקור בתור אטרקציה תיירותית, ואני מניח שהיא הופיעה אז.
לאחר מכן נראה ששינית את הסוג שלה למשהו שאינו נתמך ע"י האתר:
![image](https://user-images.githubusercontent.com/3269297/98079936-57efa300-1e7d-11eb-929d-98c28a913731.png)
ניתן לראות במקרא באיזה תיוגים אנו תומכים ע"י ריחוף עם העכבר על סוג הרלוונטי
אני ממליץ אתר הנצחה במקרה הזה.
![image](https://user-images.githubusercontent.com/3269297/98080131-9d13d500-1e7d-11eb-95fb-2a3eee369ae6.png)

**Comment by HarelM** [comment]
כדי להימנע מבעיות, אני גם ממליץ לשנות את זה דרך העורך של 
OSM 
ולא דרך האתר רק ליתר ביטחון...

**Comment by onzd** [comment]
אוקי אשנה
תודה

בתאריך יום ד׳, 4 בנוב' 2020, 9:13, מאת Harel M <notifications@github.com>:
