### ISSUE TITLE
סינון זבל

### ISSUE THREAD

**Issue by onzd** [IsraelHikingMap/Site#1356]
היי
אולי תבקשו מתנדבים בעלי ידע שיהוו כמאשרים תוספות ושמות למפה לסנן קצת זבל?

**Comment by HarelM** [comment]
העלאת המידע היא דרך המנגנון של או.אס.אם
אין שם ענייני הרשאות וכד'. סביר שזה חסר אבל אין לנו השפעה על זה.
אנחנו כל כמה זמן שולחים פוסט בפייסבוק על זבל שאנשים מעלים בתקווה שאנשים יבינו את הרעיון.
אין לנו פתרון יותר רחב.
נשמח אם תתנדב להוביל מהלך כזה :-)
אני נכנס לאו.אס.אם ושולח הודעות פרטיות לאנשים שהעלו זבל, לרוב הם מוכנים לתקן. אם הם לא עונים אני מוחק או משנה בעצמי...
אני סוגר את הקריאה ברשותך...

**Comment by onzd** [comment]
הבנתי. תודה

2020-11-05 15:01 GMT‎+02:00‎, Harel M <notifications@github.com>:

**Comment by onzd** [comment]
ניסיתי למחוק מקווה שהצלחתי

‫בתאריך יום ה׳, 5 בנוב׳ 2020 ב-15:11 מאת ‪ofer kapon‬‏ <‪oferkapon@gmail.com
‬‏>:‬
