### ISSUE TITLE
הצעה לסינון

### ISSUE THREAD

**Issue by onzd** [IsraelHikingMap/Site#1357]
היי
אולי תבקשו מתנדבים בעלי ידע שיהוו כמאשרים תוספות ושמות למפה לסנן קצת זבל?

**Comment by HarelM** [comment]
אני מניח שניתן להוציא רשימות של שינויים שנעשו לאחרונה ולעבור עליהם.
אם תמצא לי מתנדבים שיהיו מוכנים לעזור אני מבטיח להוציא רשימה :-)
הדוגמא שנתת בפייסבוק היא דווקא דוגמא שלא נעשתה דרך האתר אלא דרך ממשק העריכה של OSM
שעליו אין לי השפעה, אבל אתה מוזמן לפנות אליהם ולכתוב להם בדיוק מה שכתבת פה :-)
אני ממליץ להיכנס לקבוצת הטלגרם של OSM
ולשאול מה נכון לעשות, אני לא חושב שפה זה הפורום המתאים לדיון הזה, כרגע...
אל תבין אותי לא נכון, אני לגמרי מבין את הבעיה, אבל אין לי את המשאבים לבנות תהליך כמו שאתה רוצה, אפילו אם אני חושב שהוא נכון.
