### ISSUE TITLE
Extend UI customization abilities

### ISSUE THREAD

**Issue by ylivny** [IsraelHikingMap/Site#1358]
## What I expect to happen
The new UI has minimal controls on the map but users can customize it by adding the חיפוש, תכנון מסלול and גרף גבהים if they choose to.

I suggest to extend the customization abilities and allow users to add to the map also מפות ושכבות and שיתוף - קבצים.
When users choose to add these items to the map, an icon will be added to the left bar of the map (under the navigation menu) and clicking on it will open the relevant overlay. This will allow users that heavily use these capabilities to access them more easily (I saw several "complains" about it in the Facebook group)

**Comment by HarelM** [comment]
Thanks for the suggestion, but after long discussion on the subject we have decided that the current level of complexity is enough and we don't want to complicate it further.

**Comment by Tsurha** [comment]
The current UI speaks in two different languages in opening and closing a pane. This is the extra complexity we would love to see eliminated. 
I also wanted this and totally second the idea. Urge you to reconsider. Thank you!

**Comment by zstadler** [comment]
I'll prepare a proposal soon

**Comment by HarelM** [comment]
Might be related to #1324 but doesn't have to be...
