### ISSUE TITLE
Show route length, accumulated ascents and descends also when the Statistics Graph is extended  

### ISSUE THREAD

**Issue by ylivny** [IsraelHikingMap/Site#1359]
## What I expect to happen
When the Statistics Graph is minimized, one can only see route length, accumulated ascents and accumulated descends statistics. When users extend the Statistics Graph is shows the route heights graph and only if the users clicks on the 'table' icon they can see route length, accumulated ascents and accumulated descends.

## What really happened
Present route length, accumulated ascents and accumulated descends together with the heights graph

**Comment by HarelM** [comment]
Actually, there was a version when it was as suggested but in mobile device there's a need to display the graph as big as possible and so we decided to remove the statistics when the graph is open.
We also adopted the mobile first approach to reduce the learning curve when switching between desktop and mobile, and the fact that we do not have the necessary resources to maintain a mobile version and a desktop version had led to choose the current state of the UI.
Sorry if this is not the answer you were looking for...
