### ISSUE TITLE
google terrain - can be added as additional layer?

### ISSUE THREAD

**Issue by eligrt** [IsraelHikingMap/Site#136]
hi, 
sorry if it's a re-post but my earlier post is close (and i'm not sure if additional comment are visible)
anyhow, i wonder if i can i add "Google Terrain" as a layer/overlay to the IsraelHikingMap

i.e.
https://www.google.co.uk/maps/@31.7674586,35.2080017,13.18z/data=!5m1!1e4

**Comment by zstadler** [comment]
You will have to do some reverse-engineering to find the address pattern for Google Terrain tiles.
We would not like to publish such addresses unless permitted by their supplier.
