### ISSUE TITLE
Add "Save As" to a specific route menu

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1361]
## Feature
Enhancement Request

## What I expect to happen
Add another entry in a specific route, with Save As שמירה כ. The saved file relates to one specific route, the user opened

![Save as](https://user-images.githubusercontent.com/49042192/98761838-f7adb380-23de-11eb-8e6d-ac9a20d37324.PNG)

**Comment by HarelM** [comment]
Thanks for taking the time to open this issue.
Save as menu is complicated and requires the relevant location for it and can't be easily added to where you pointed.
It is also counter productive to our product as it is only used for Garmin and other applications and does not bring traffic to either our site or our app.
While we still do support the global save-as, I don't see a valid reason to support this.
Nevertheless, if you want to submit a pull request, I won't stop you.

**Comment by Tsurha** [comment]
### הסבר על מוטיבציה
מבחינת תעבורה, האתר משמש גם לתכנון מסלולים עבור ניווט עם מכשירים חיצוניים בהמשך
עבורי ועבור רבים ללא שמירה כ אין מוטיבציה לשימוש באתר כלל
כל הקלה על שמירה כ כפי שהצעתי תומכת במשתמשים הללו, 
אישית זה מעציב אותי שמשתמשים אלה פחות נחשבים בעינך

### הסבר על אופן הפתרון המוצע
כאשר לוחצים שמירה כ גלובלי, קופץ החלון הרלוונטי לו באמצע המסך באופן צף
לא צריך למצוא מקום אחר עבור שמירה כ ספציפי למסלול
צריך רק להקפיץ את אותו חלון באותו מקום

**Comment by HarelM** [comment]
<div dir="rtl">
אני מאוד מעריך את הדעה שלך, ואני בשום שלב לא מתכוון להעליב, אז אנא קח את מה שאני הולך לכתוב בערבון מוגבל.

אתה לא חייב להתשמש באתר אם הוא לא ממלא את הדרישות שלך, זכותך להשתמש או לא להתשמש בו.
אני באמת מאמין (ואני משוחד) שאין לו מתחרה ראוי היום לתכנון בישראל, אבל אם יש אחד כזה והוא עונה על הדרישות שלך, אז לך על זה, באמת. :-)
קיימת היום פונקציונאליות של "שמירה כ..." אף על פי שאין לזה שום הגיון ברמה מסחרית-עסקית מאחר וכמו שאמרתי היא לא תורמת לאתר תעבורה לתוך האתר ואז לתוך האפליקציה.
עם זאת, ובניגוד להגיון המסחרי-עסקי, אנחנו משקיעים מאמצים גדולים בלהסביר איך להשתמש באתר שלנו על מנת לעבוד עם מכשירים חיצוניים. זה מעמסה מאוד גדולה ברמת התפעולית ולחלוטין לא מוערכת, כמו שאפשר לראות בקריאה הזו ובתכתובות בפייסבוק. אז המוטיבציה שלנו לעזור רק יורדת עם הזמן.
בראייה שלי, הסיבה לבעיה היא בכלל לא באתר עצמו, אלא באפליקציות החיצוניות והיכולת שלהן לתמוך בקבצים שהאתר מוציא (שהם תקינים ועומדים בכל הסטנדרטים). אז קשה לי להבין למה באים אליי בבקשות לפתור משהו שהוא לא בעיה אצלי באתר... למה לא ללכת ליבואן ולדרוש פתרון? כי אפשר? כי אנחנו פראיירים?
ברמה האישית, זה מאוד מאוד מכעיס אותי שבאים אלינו בדרישות לגבי תמיכה במכשירים חיצוניים ששילמו עליהם, והם לא עובדים כמו שצריך, בעוד שהאתר שלנו עודו ועתיד להיות חינמי לחלוטין, ואנחנו מקפידים אפילו לא לשים בו פרסומות כי אכפת לנו מהמשתמשים, אתר שלא באמת מרוויח שום דבר מזה. יש בזה משהו מאוד אבסורדי וחסר הגיון, שוב, בראייה שלי.

אתה יכול לפרש את מה שכתבתי בתור נקמנות אישית, או שאני סתם משוגע ומעצבן, וזו זכותך ואני לא יכול לבוא אליך בטענות. אבל בראייה שלי יש פה חוסר צדק וחוסר הגיון ברמה לא סבירה כלפי השירותים שאנחנו נותנים.

אבל בוא ניהיה פרקטיים.
על מנת לתמוך בפונקציונאליות כזו בצורה ראויה אני צריך את החומרה המתאימה. כלומר כמה שעוני גארמין או כל דבר אחר שבו הקבצים לא עובדים.
אם תוכל להשיג לי כמה שעונים כאלה לטובת בדיקות אז יש על מה לדבר.
פעם שעברה עשינו קמפיין מימון המונים על מנת לתמוך באייפון, אני לא רואה סיבה לא לעשות את זה גם פה.
שילמת על שעון יוקרתי או מכשיר יועודי? בואו תתרמו לאתר קצת על מנת לתמוך ביכולת הזו.
אם אתה באמת רציני בנושא, תרים קמפיין כזה על אותו סכום (10000 ש"ח), ואם הוא יצליח אני מתחייב לתמוך בנושא.

</div>

**Comment by Tsurha** [comment]
הי הראל

**Comment by Tsurha** [comment]
היי הראל,
מעריך את זה שענית תשובה ארוכה. לקח לי כמה ימים לחזור כי אני בקצת עומס. 

אתחיל בלהתייחס אל הפראקטי. יש אצלי GPS אופניים ישן של גרמין שבדרך לפרישה. ברגע שהוא יוחלף אשמח לתת לך אותו לכל צורך של פיתוח האתר. 

בנושא שמירה כ…  לא ביקשתי שינוי פונקציונאליות השמירה. בעיני היא בסדר גמור. כל מה שביקשתי כאן זה שינוי UI שיאפשר שימוש בפונקציונליות הזו בשביל מסלול בודד. כלומר להקפיץ את אותו חלון קיים ותקין. לא חושב שצריך לכך בדיקות מעמיקות של קבצים. עדיין הגרמין הישן שלי לרשותך ברגע שהוא ישוחרר.

בנושא מכשירים חיצוניים. נושא הסטנדרטיזציה חשוב, ביחד עם הכרה במציאות של המון משתמשים. גרמין היא מובילת שוק הניווט. גם אם יש באג בתמיכה שלהם ב GPX זה לא משנה. אין לאף אחד מהמשתמשים שלך יכולת לשנות את גרמין. אם לא תהייה תמיכה כזו, השימוש ב IHM יהפוך לגן סגור. סטנדרטי. אבל סגור. 
אם לקחת דוגמה מגוגל דוקס, גיליונות ומצגות. יש שם יצוא לטובת הפורמטים של מיקרוסופט אופיס. לא אתפלא אם מיקרוסופט בכוונה משאירים פורמטים לא סטנדרטיים. גוגל מכירה במציאות של הרבה משתמשי אופיס. אז אתה בחברה טובה.
ממה שאני זוכר אתה מנווט ברגל ולא רוכב? גיא שחר ניווט עם הטלפון ב HLC וכתב בפייסבוק שזה היה בעייתי. בגלל החומרה ולא האפליקציה. הניווט עם גרמין שהוא יעודי בחומרה עדיף בהרבה. אני מוביל שתי קבוצות אופניים בשטח כמעט כל יום בוקר ואחהצ. הטלפון חייב להישאר למצבי חירום עם סוללה שלא נזללת לצורך ניווט. גם התצוגה של מכשיר יעודי על הכידון מול השמש טובה הרבה יותר מאשר מה שחומרת מסך הטלפון מאפשרת לי בשלושים קמ"ש.
מוזמן לקרוא כתבה שלי על מכשיר ניווט אופניים של ליזיין, ולמה הוא לא נוח כמו גרמין. גם המלצתי שם על תכנון עם מפת האופניים כולל קישור לצורך טראפיק אליכם: https://bikepanel.com/lezyne-xl-nav


לגבי פונקציונליות האתר בהיי לבל. מה שהופך את האתר לכלי תכנון מצויין זה היכולת לתפור מסלול שמתעקל לפי המידע מ OSM. השילוב הזה שעשית הוא אדיר. זו הפונקציונליות הכי חשובה. בגלל זה אני כאן ובגלל זה אני משקיע לכתוב לך באופן מעמיק.
ברמת ה UI יש דברים שפחות זורמים והם ברי ניקוי באופן איטי. נושא הממשק הוא עניין של אלוהים שוכן בפרטים הקטנים. לצערינו זה לא זבנג וגמרנו עם פצצת אטום אחת אלא קרב חפירות מתיש. 

ברור לי לבד שאם IHM לא עונה על צרכי, אחפש אלטרנטיבה. חבל לי שהרגשת צורך לכתוב את זה כי זה לבוא בריגשי ומהבטן. עדיף שיתוף פעולה שבו נתרום אחד לשני בלי להיכנס לפינות האלה. אשמח לשוחח איתך, על בירה או בטלפון, על התסכול שזה מביא. כי כאן זה פחות עוזר. 
בכל מקרה אני מבין את הבאסה. אתה משקיע כל כך הרבה באתר, בתור מפעל חיים אפילו, ומרגיש מואשם. עכשיו רק לנקות את העצבים על זה, לקחת את המהות של מאיפה האנשים באים, ולהבין את הצורך הטכני בלבד.
אם לחזור להתחלה, לא היתה כאן טענה אליך או אל הקבצים הנוצרים אלא בקשה להקפצת ה-UI של שמירה כ גם למסלול בודד.

עם הרבה הערכה, 
צור 054-4536874

**Comment by Tsurha** [comment]
לא יודע איך לעשות 
RTL 
כאן
לצורך קריאת מה שכתבתי לעיל, עדיף קופי פייסט לאנשהו ויישור לימין

**Comment by HarelM** [comment]
<div dir="rtl">
על מנת ליישר לימין פה, (לצערי זה עוד לא נפתר אפילו שפתחתי להם קריאה על זה) יש לכתוב בראש הפסקה את הדבר הבא:
`div dir="rtl"`מוקף בסוגריים משולשים (אם אני כותב את זה מלא זה מעלים לי את זה מהפוסט ולכן ההסבר המוזר...)
את הפוסט שלך ערכתי גם על מנת שיהיה קריא, לי בעיקר... :-)
לפני שנמשיך את הדיון שבטח יעבור לטלפון יש לי שאלה אחת:
לפני שפתחת את הקריאה פה, פתחת גם קריאה באתר של גרמין עם תיאור הבעיה של פתיחה של קובץ ברירת המחדל של האתר?
ממה שאני רואה באתר שלהם צריך מספר סידורי, מה שאין לי, מכיוון שאין לי מכשיר של גרמין...

**Comment by Tsurha** [comment]
<div dir="rtl">

פתחתי עכשיו קריאה לגרמין כי זה חשוב לך. לפחות בשביל הניסיון ומה שנקרא
To humor us
עותק אצלך באימייל israelhikingmap@gmail.com 

אנחנו חוזרים לנסות ליישר אותם לתקן, וזה דון קישוטי
הרי כבר בנית יצוא שמתאים להם. גם 
Single Track GPX
Single Route GPX
עובדים היטב מולם

כל מה שרציתי זה איפשור ישיר שלהם מהמסלול הבודד
בכל מקרה היה לך הרבה מה לומר על האימייל שלי אז חופשי
