### ISSUE TITLE
Ease usage of Layers menu 

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1363]
Feature = Simplify the usage of the Layers menu on PC by easing the usage of it constantly open. This is done with a combination of small changes:
* Narrow its width by half to consume less map real estate
* Remove the indentation (the sections there give the same functionality already)
* Eliminate the slow opening animation

This will unify the behavior of the other items that can be constantly open

![Layers](https://user-images.githubusercontent.com/49042192/98763151-16fa1000-23e2-11eb-869d-094290a3f810.PNG)

**Comment by HarelM** [comment]
Thanks for taking the time to report this issue.
I don't see how this is helpful.
The indentation allows user to understand the hierarchy of the control.
The margin on the side is defined by google material design guidelines which becomes a standard. I don't see a good reason to break this standard...

**Comment by Tsurha** [comment]
כנראה קפצתי אל הפיתרון המוצע קודם ללא דיבור על מוטיבציה.
המוטיבציה היא להשאיר את השכבות פתוח כל הזמן. לצרכי תכנון
על מנת שלא לגזול שטח מפה חשוב, כדאי להקטין את השכבות לחצי רוחב
אני לא מבקש לוותר על השוליים שמשמאל לאיקס. הם תקינים
גם אם תתחיל עם הקטנת הרוחב לשני שליש שקל לביצוע ללא שינויי אינדנטציה, כבר הרווחנו

הפתרון המוצע לצורך עוד הקטנה: לחצי רוחב
כרגע העמודה הכי שמאלית מוקדשת רק לאיקס סגירה שלא שייך להיררכיה, מתחתיו יש שטח מבוזבז משמאל
הכותרות של כל קבוצת שכבות מופרדות באופן בולט מהשכבות שמתחתן וברור לגמרי כל שורה לאיזה אזור היא שייכת
לכן אפשר את העיניים לשים מתחת לפלוס ששייך אליהן

**Comment by HarelM** [comment]
<div dir="rtl">
בדקתי את הנושא וזה יוצר הרגשה לא רצוייה של צפיפות בפקד שאני רוצה להימנע ממנה.
בנוסף הפאנל הזה משמש גם לנק' עניין, ואודות ומקרא ואני רוצה שהוא יהיה בגודל זהה עבור כולם.
תודה רבה על הזמן שהשקעת בבקשה לשינוי אך אני נאלץ לסרב לה, לצערי.
