### ISSUE TITLE
Manage map and routing updates

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#137]
In order to reduce the setup time of a new server and in order to make everything under the same roof I think the server code (as in C#) should manage the update of the routing and trigger the tiles update.
@zstadler what do you think?
As I see it, the server should have a service with a timer (instead of relaying on windows scheduler) and once the timer is triggered the server should fetch the latest pbf file, update the routing cache and trigger the maperitive script for tile generation.
If we want to know what went wrong and when we will have one place to look at - the server logs.
Also I think that C# code can better handle errors and not swallow them.

**Comment by zstadler** [comment]
Here are my 2 cents:

I don't necessarily see the same value in moving working functionality from one mechanism to another. My general philosophy is for doing things [just in time](https://en.wikipedia.org/wiki/Just-in-time_manufacturing) for use, such as before setting-up a new server. This is very similar to the [YAGNI - You Ain't Going to Need It](https://en.wikipedia.org/wiki/You_aren't_gonna_need_it) approach in extreme programming.

Regardless of the above, I think it is important that the routing data, i.e. the pbf file, will be updated when and only when the map tiles are being updated.

**Comment by HarelM** [comment]
Well, after a few hours of playing around with timers and schedulers it seems that it is not the right approach. I do want the code that updated the routing to be in c# though, and write the status to logs, also the Windows service that runs graph hopper.
I'll see if I can finish it tonight. My current idea is to open a http call to the server and tell it to update the pbf file. I think the same call can initiate the map creation.

**Comment by HarelM** [comment]
I have moved the routing server to run as a service using NSSM.
I have added a small exe file that will update the cache and restart the service.
I have updated the task scheduler to run as administrator to be able to restart the service.
I have moved the graph hopper folder inside the Israel hiking site folder and added it to source control so if you don't need anything else besides getting the latest version from github.
@zstadler if you added any code to start up or anywhere else please remove it.
