### ISSUE TITLE
Text of grouped trails exceeds its background

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1371]
## What I expect to happen
Text of grouped trails to be condained in its white background

## What really happened
Some text prints outside of the white background

![image](https://user-images.githubusercontent.com/1304610/99970930-33645800-2da5-11eb-892c-6ed55a45a6f1.png)

## What I did that caused the issue - step by step
- Open https://israelhiking.osm.org.il/map/12.00/30.8959/34.7477
- Turn off all POIs and trails layesr, except Jeepolog
- Click on the group shown above

## My environment
* Operating System and version: Win 10 Pro, Android
* Web Browser and version: Firefox, Android App

**Comment by HarelM** [comment]
Probably needs some css massaging:
https://stackoverflow.com/questions/53497127/how-to-break-word-if-text-inside-angular-material-button-is-longer-than-the-widt
