### ISSUE TITLE
טעות בשם ובמיקום הר צפירה?

### ISSUE THREAD

**Issue by onzd** [IsraelHikingMap/Site#1372]
https://israelhiking.osm.org.il/share/oZj6Nlnt6K  במסגרת תכנון מסלול ראיתי באתר טבע ונופים שהיכן שממוקמת תצפית גבעה חרוטית מופיעה במפה הר צפירה
https://inature.info/wiki/%D7%91%D7%95%D7%A8_%D7%A2%D7%98%D7%99%D7%9F_%D7%95%D7%94%D7%A8_%D7%A6%D7%A4%D7%99%D7%A8%D7%94

**Comment by HarelM** [comment]
אני לא מכיר מספיק.
תוכל לפנות דרך הממשק של 
Osm
למי שהעלה את הנקודה ולשאול אותו.
מאחר ואני מכיר אותו, אני אהיה מופתע אם הוא סימן במקום הלא נכון, אבל הכל יכול להיות...
בכל מקרה, אני סוגר את הקריאה כי זו לא בעיה בקוד של האחר...
לנושאי מיקום נקודות ומיפוי לא מדוייק אני ממליץ לשלוח הודעה בפורום של
Osm
או בקבוצת טלגרם של osm..

**Comment by onzd** [comment]
אחלה

2020-11-23 16:47 GMT‎+02:00‎, Harel M <notifications@github.com>:

**Comment by onzd** [comment]
שלחתי לו הודעה אישית

בתאריך יום ב׳, 23 בנוב' 2020, 19:04, מאת zstadler <notifications@github.com
