### ISSUE TITLE
Improve panned map UX

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1380]
## Feature
As a user I would like the map to behave better in the following scenarios when the GPS is on:
1. When searching
2. When receiving a share/file/location/POI
The map should show the relevant item and only after a timeout return to the GPS position.
The behaviour should not be limited to map panning by hand but also to other scenarios as described above.
The "panned" state should be global and not reside only in the location component.
@zstadler let me know if there are other use cases that you encounter that requires improvement except for those that I wrote above.
We briefly talked about this feature on the phone.

**Comment by zstadler** [comment]
Also, aftrt showing and opening a recording.
