### ISSUE TITLE
בקשה להעלמת והחזרת המסלול

### ISSUE THREAD

**Issue by onzd** [IsraelHikingMap/Site#1384]
שאני במסלול הסימון של המסלול מכסה את צבע המסלול 
הייתי שמח אם אפשר להוסיף כפתור שיעלים לרגע את הסימון המסלול שנעשה שאוכל לראות את צבע המסלול ולהחזיר אותו מיידית

**Comment by HarelM** [comment]
אתה צודק.
יש קריאה פתוחה על מנת להגדיל את עובי הקווים בזומים יותר גבוהים כך שאם תגדיל את המפה הדרך תתרחב ותוכל לראות את הסימן:
https://github.com/IsraelHikingMap/VectorMap/issues/15
בלי קשר, בפקד השכבות, אם אתה לוחץ על העיפרון של המסלול הוא יעביר אותו למצב בלתי נראה.
לחיצה נוספת תחזיר אותו.

**Comment by onzd** [comment]
אז אם אפשר לגרור את העיפרון מהשכבות החוצה נגיד ליד כפתור הג'י פי אס
מאוד יעזור

בתאריך שבת, 5 בדצמ' 2020, 20:56, מאת Harel M <notifications@github.com>:

**Comment by HarelM** [comment]
מצטער, אני לא חושב שזה הפתרון הנכון בהינתם העובדה שעשינו מאמצים גדולים להפחית את כמות הכפתורים בממשק החדש.
הפתרון הנכון לדעתי הוא הנ״ל, כשהוא יפותח הבעיה תעלם.

**Comment by onzd** [comment]
סבבה

בתאריך שבת, 5 בדצמ' 2020, 23:20, מאת Harel M <notifications@github.com>:

**Comment by zstadler** [comment]
> אתה צודק.
> יש קריאה פתוחה על מנת להגדיל את עובי הקווים בזומים יותר גבוהים כך שאם תגדיל את המפה הדרך תתרחב ותוכל לראות את הסימן:
> [IsraelHikingMap/VectorMap#15](https://github.com/IsraelHikingMap/VectorMap/issues/15)
> בלי קשר, בפקד השכבות, אם אתה לוחץ על העיפרון של המסלול הוא יעביר אותו למצב בלתי נראה.
> לחיצה נוספת תחזיר אותו.

[הקריאה הנ"ל](https://github.com/IsraelHikingMap/VectorMap/issues/15) מתייחסת לרמות זום גבוהות ואילו הבעיה המתוארת כאן קיימת בכל רמות הזום.

אני מעדיף לקבוע את רמת השקיפות של המסלול כך שאפשר יהיה לראות את המפה שמתחתיו.

כך נראה מסלול בשקיפות מקסימלית

<img width="33%" src="https://user-images.githubusercontent.com/1304610/101272779-144bca00-3798-11eb-8ae8-d903e71e6238.png"/>

לעומת שקיפות מינימלית

<img width="33%" src="https://user-images.githubusercontent.com/1304610/101272761-ee262a00-3797-11eb-8b4b-a1f62e35bf67.png"/>

**Comment by onzd** [comment]
סבבה
לעניות דעתי עדיף כפתור כיבוי והחזרה אבל זו רק דעתי האישית כמובן
אשתמש בפיתרונות שהוצעו כאן
תודה

בתאריך יום א׳, 6 בדצמ' 2020, 8:04, מאת zstadler <notifications@github.com>:
