### ISSUE TITLE
פקד השקיפות מראה את רמת האטימות

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1386]
<div dir="rtl">
כאשר פקד ה"שקיפות" של מסלול נמצא ברמה המקסימלית, המסלול הוא אטום ביותר

<img width="25%" src="https://user-images.githubusercontent.com/1304610/101272749-df3f7780-3797-11eb-8b53-236d9e5e02fc.png"/> <img width="25%" src="https://user-images.githubusercontent.com/1304610/101272761-ee262a00-3797-11eb-8b4b-a1f62e35bf67.png"/>

וכאשר הוא ברמה המינימלית, השקיפות מקסימלית

<img width="25%" src="https://user-images.githubusercontent.com/1304610/101272819-760c3400-3798-11eb-8c13-7905612f9015.png"/> 
<img width="25%" src="https://user-images.githubusercontent.com/1304610/101272779-144bca00-3798-11eb-8ae8-d903e71e6238.png"/>

</div>

**Comment by HarelM** [comment]
It is unclear what is the problem definition and what is suggested solution...
Please advise.

**Comment by HarelM** [comment]
This was discussed in a phone call.
אטימות is not an ideal name and switching the slider "direction" is not ideal as well.
Current situation, while not ideal as well is the "lesser evil"...
