### ISSUE TITLE
Add "hide all" button for overlays

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1387]
## Currently
Active overlays may crerate confusion for the user. When there are several user-defines overlays, it is also not easy to spot and deactivate them.

## What I would like to happen
Add a button for hide all the overlays.

This button could be similar to the global visibility buttons for public POIs and trails. Unlike the public POIs and trails buttons, the requested button would perform only a "hide all", not followed by a "show all" action.

**Comment by HarelM** [comment]
Please create an image with how you think it should be UI/UX wise.

**Comment by zstadler** [comment]
![image](https://user-images.githubusercontent.com/1304610/101274215-d73a0480-37a4-11eb-9da2-8a08b4ddbaaf.png)

**Comment by HarelM** [comment]
Phone conversation summary updated UI:
Closed:
![image](https://user-images.githubusercontent.com/3269297/102715181-4dc61e80-42dc-11eb-8790-965c5ac45249.png)
Opened:
![image](https://user-images.githubusercontent.com/3269297/102715193-60405800-42dc-11eb-8ac0-77000417ad1b.png)

I'll keep hiding/showing all routes as a possible future enhancement as it has other things to be considered like what should be done with the selected route and it kinds of complicate things which I'm not sure are related to this issue and I'm not sure this is truly needed at this point.
