### ISSUE TITLE
Printing broken on Firefox

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1394]
## Bug
Thanks @Amirstad for spotting this!
## What I expect to happen
Be able to print that map using Firefox' print

## What really happened
The print is empty. Same as shown in the preview.

![image](https://user-images.githubusercontent.com/1304610/101786409-9294cd00-3b06-11eb-9e48-59dd332ad4b8.png)

## What I did that caused the issue - step by step
Use the prowser's print command

## My environment
* Operating System and version: Windows 10
* Web Browser and version: Firefox 83.0 (64-bit)

## Things I think the developers should know, images, links etc.
The solution is suggested at https://github.com/mapbox/mapbox-gl-js/issues/9810#issuecomment-647959562

**Comment by zstadler** [comment]
[Mapbox JS GL doc](https://docs.mapbox.com/mapbox-gl-js/api/map/#map-parameters) say:

Name | Description
:---|:---
**options.preserveDrawingBuffer**: boolean<br/>default: false | If  true , the map's canvas can be exported to a PNG using  `map.getCanvas().toDataURL()` . This is  false  by default as a performance optimization.

It may be worthwhile to enable this only on the desktop.

**Comment by HarelM** [comment]
Sorry, no plans to support this.
You can use a screen capture and print it.
Please open a bug for firefox as chrome shows this OK.
