### ISSUE TITLE
Printing broken on Safari - landscape and portrait

### ISSUE THREAD

**Issue by Amirstad** [IsraelHikingMap/Site#1395]
## What I expect to happen
Be able to print that map using Safari's print

## What really happened
The print is empty, as seen in the preview:
<img width="759" alt="image" src="https://user-images.githubusercontent.com/32457970/101787887-40ed4200-3b08-11eb-90b2-e8e393fbcdf2.png">

## What I did that caused the issue - step by step
At first the print looks good, as seen in the preview:
<img width="762" alt="image" src="https://user-images.githubusercontent.com/32457970/101787747-19967500-3b08-11eb-99d5-b33c5c5d5a00.png">
When attempting to change orientation (by clicking either radio button) the above example occurs

## My environment
* Operating System and version: macOS Big Sur 11.0.1
* Web Browser and version: Safari 14.0.1

## Things I think the developers should know, images, links etc.
Perhaps related to #1394

**Comment by HarelM** [comment]
Sorry, no plans to support this.
You can use a screen capture and print it.
Please open a bug for safari as chrome shows this OK.
