### ISSUE TITLE
UX improvements for slow network connection

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1401]
## Feature

The UX for some user scenarios depend on the speed of the network access. This issue is intended to list the scenarios for consideration. 

The _slow network_ UX is closely related to the _offline_ UX. It is possible that some of the _slow network_ UX scenarios could be addressed by the addressing the _offline_ UX. For the convinience of the discussion, the _offline_ mode is active when the heartbeat detects a disconnect. 

#### Slow network scenarios
- [x] Routing (related to offline routing - #1399)
- [ ] Uploading a public POI, including picture upload
- [x] New private POI
- [x] Trace upload at the end of the recording (#1397, #1398)

**Comment by HarelM** [comment]
Public POI upload will be handled in a separate issue according to priority I don't want to do a partial work as part of this issue.
Currently tracked in the topics to discuss...
