### ISSUE TITLE
Make offline map purchase more prominent

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1402]
## Feature
As a user who would like to use the offline maps it is not straight forward sometime how to do it.
The current location of the buy/download button can be hidden or not intuitive.
Possible solutions:
- [x] ~~Move it the main menu before the "more..." button.~~ Doesn't feel right...
- [x] Move it to the upper part of the layer control
- [x] ~~And/or show a banner when first installing the application~~ should be handled by other form of advertising (?)
- [ ] Initiate the map download and show the confirmation dialog only on app startup (?)

**Comment by zstadler** [comment]
A similar use-case, recently brought as a support e-mail, is when a user with an offline ,ap purchase has re-installed the app or installed it on another device. The situation is seimilar: the user has a license, but the offile maps need to be downloaded for the license to be useful.

I suggest that
> 4. Initiate the map download and show the confirmation dialog

is executed whenever the application is started, just as currently done for updating the offline POI list.

**Comment by HarelM** [comment]
Just to clarify: the suggestion above is in the user case of a user who never downloaded the map, as I wouldn't want to do it on startup if the user already had downloaded the map in the past (even if the map is getting old...)

**Comment by zstadler** [comment]
Right. The suggestion is that the offline map download dialog will be presented to the user:

1. After the completion of the purchace at the store
1. At the app startup, if all of the following conditions hold:
   - The user has an valid subscription
   - There are no offline maps on the device
   - There is a network connection

We can also consider showing monthly reminders for updating the offline maps, given that the users are purchasing a subscription:

3. At the app startup, if all of the following conditions hold:
   - The user has an valid subscription
   - _The offline maps dialog has not been shown for more than a month_
   - There is a network connection
