### ISSUE TITLE
Unable to edit properly - no points

### ISSUE THREAD

**Issue by galdanny** [IsraelHikingMap/Site#1404]
## Bug/Feature
(Delete the non-relevant)
Going to edit  mode on any GPX I load on both web and app, I don't see the points along the track , only the start and end.
GPX I use example
[Eshtaol-midweek nir2.zip](https://github.com/IsraelHikingMap/Site/files/5721008/Eshtaol-midweek.nir2.zip)

## What I expect to happen
See all points

## My environment
* Operating System and version: Win 10
* Web Browser and version:

## Things I think the developers should know, images, links etc.
PS
I have an enhancement wish - use the height graph to select cut / paste parts pf the track...
Please call me if need more exlanations - 054-4236266 Thanks :)

**Comment by HarelM** [comment]
Thanks for taking the time to open this issue.
There's currently an issue which was fixed but wasn't released that might address this issue, not sure: #1396
There's also a way to show all GPX point in the route in the advanced menu of a private route:
![image](https://user-images.githubusercontent.com/3269297/102715372-b235ad80-42dd-11eb-89e2-b19930cd6020.png)
I haven't checked the usage of this function as almost no one uses it, but it should work if this is what you need.
But in general, the best way to edit GPX routes is to click on the route while in editing mode and the add points as needed, and later on move/split/merge the relevant parts.
As for an enhancement request, I would advise to create a new issue and elaborate exactly what you need and we could discuss it separately.

**Comment by HarelM** [comment]
No response. Closing...
