### ISSUE TITLE
Duplicate trkpt in gpx file saved as a single track 

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1405]
## What I expect to happen
A saved GPX file should not contain duplicate points.

## What really happened
Almost every point in the GPX file was duplicated.

## What I did that caused the issue - step by step
- Planned a short [dummy route](https://israelhiking.osm.org.il/share/A0Yr2os1nQ) using straight line routing.
- Saved the route as "Single track GPX"
- All but the first and last `trkpt` in the GPX file were included twice. The first `trkpt` was included 3 times and the last `trkpt` was included once.

## Things I think the developers should know, images, links etc.
The duplication happens also when saving as a "Single route GPX."

<details><summary>The result single track GPX file:</summary>
<br/>

```
<?xml version="1.0" encoding="utf-8"?>
<gpx version="1.1" creator="IsraelHikingMap_single_track" xmlns="http://www.topografix.com/GPX/1/1">
	<metadata>
		<bounds minlat="32.85670309" minlon="34.98646523" maxlat="32.85761149" maxlon="34.98752547" />
	</metadata>
	<trk>
		<name>singletrack</name>
		<desc />
		<extensions>
			<Color xmlns="">#0000FF</Color>
			<Opacity xmlns="">0.4</Opacity>
			<Weight xmlns="">9</Weight>
		</extensions>
		<trkseg>
			<trkpt lat="32.85670309" lon="34.98646523">
				<ele>-26.26130434358538</ele>
			</trkpt>
			<trkpt lat="32.85670309" lon="34.98646523">
				<ele>-26.26130434358538</ele>
			</trkpt>
			<trkpt lat="32.85670309" lon="34.98646523">
				<ele>-26.26129323000123</ele>
			</trkpt>
			<trkpt lat="32.8569053" lon="34.9866793">
				<ele>-27</ele>
			</trkpt>
			<trkpt lat="32.8569053" lon="34.9866793">
				<ele>-27</ele>
			</trkpt>
			<trkpt lat="32.85710402" lon="34.98688712">
				<ele>-27</ele>
			</trkpt>
			<trkpt lat="32.85710402" lon="34.98688712">
				<ele>-27</ele>
			</trkpt>
			<trkpt lat="32.85725895" lon="34.98713607">
				<ele>-27</ele>
			</trkpt>
			<trkpt lat="32.85725895" lon="34.98713607">
				<ele>-27</ele>
			</trkpt>
			<trkpt lat="32.85740765" lon="34.98733187">
				<ele>-27.382063869994454</ele>
			</trkpt>
			<trkpt lat="32.85740765" lon="34.98733187">
				<ele>-27.382063869994454</ele>
			</trkpt>
			<trkpt lat="32.85761149" lon="34.98752547">
				<ele>-28</ele>
			</trkpt>
		</trkseg>
	</trk>
</gpx>
```
</details>

**Comment by HarelM** [comment]
While not a good excuse the reason for the issue is the following:
First segment is always a segment with a single point duplicated twice to create a valid segment (with two points) for editing purposes.
Straight lines create segments with two points: start and end point.
Every segment has the starting point of the previous segment's end point (for obvious reasons).
When converting to single route/single track all the point are dumped into the same route/trace and so the point are duplicated (I'm guessing this issue exists with regular routes as well).
Besides the duplication issue, has this causes any issues in any device that it's worth fixing?

**Comment by zstadler** [comment]
>  Besides the duplication issue, has this causes any issues in any device that it's worth fixing?
When importing the GPX to the OSM Potlatch editor, it creates duplicate nodes in the resulting OSM way.

**Comment by HarelM** [comment]
I'll fix the duplication, but I advise against using this for OSM since straight lines are created with extra points to allow showing the changes in heights along the line...
