### ISSUE TITLE
[iOS] Device orientation request permissions every time it is used

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1406]
## What I expect to happen
Permission should only be asked once

## What really happened
Permission is asked every time with the "localhost" as app name, which is a bad UX.

## What I did that caused the issue - step by step
1. Click on the location icon to show my current location

## My environment
* Operating System and version: iOS 13 and above
* Web Browser and version:

## Things I think the developers should know, images, links etc.
The following link describes the issue:
https://developer.apple.com/forums/thread/128376
The following plugin seems to address it:
https://github.com/apache/cordova-plugin-device-orientation
With:
https://ionicframework.com/docs/native/device-orientation

**Comment by HarelM** [comment]
@arielhasidim I saw that you replied to the thread above with the apple issue.
How did you end up solving this in the Cordova app? Did you use the orientation plugin? Can you share a code that uses it by any chance?

**Comment by arielhasidim** [comment]
Hello,
Yes I did use the plugin.
You can check this issue for more information:

https://github.com/apache/cordova-plugin-device-orientation/issues/52#issuecomment-626294121

I will try to add some sample code later.

**Comment by HarelM** [comment]
Thanks for the info! 
I think I managed to integrate it properly (had a `360 - x` change compared to browser orientation, I think...).
Feel free to review the commit :-)
Fixed via 4506f1fb90affdf2333cc202545a10f9134b45c2
