### ISSUE TITLE
KM Markers are presented outside the route

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1409]
## What I expect to happen
KM Markers should only be visible on the route

## What really happened
The KM Markers are presented outside the route (and it looks like the route start is calculated wrong and the markers are presented from end to start)

## What I did that caused the issue - step by step
1. Load the attached file
[ערד נחל סדום נווה זוהר.gpx.txt](https://github.com/IsraelHikingMap/Site/files/5739384/gpx.txt)
2. Open height chart
3. Click on show KM Markers

## My environment
* Operating System and version: any
* Web Browser and version: any

## Things I think the developers should know, images, links etc.
Reported by two customers

**Comment by zstadler** [comment]
This may be related to the fact that the GPX file does not have an initial dummy `trkseg`.
The issue no longer exists if that `trackseg` is added, as can be seen when [WithDummyTrakseg.gpx.txt](https://github.com/IsraelHikingMap/Site/files/5740289/WithDummyTrakseg.gpx.txt) is opened.

**Comment by HarelM** [comment]
I thought I had tested it with the latest code before I opened this issue, apparently I didn't. :-(
This is cause by the same root cause as #1396 and is already fixed but wasn't published yet...
Closing this as duplicate of #1396 (although not the same use cause but the same root cause)
