### ISSUE TITLE
Avoid overlap between attribution and layers pane

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#141]
The layers pane should be shorter in order to avoid overlap with the attribution, which makes the "advanced" button hard to access:

<img alt="2016-02-29 18_49_46-israel hiking map" src="https://cloud.githubusercontent.com/assets/1304610/13401612/796f6576-df15-11e5-80a4-19ec5539818f.png">

It's even worse on Mobile portrait mode and a touch screen:

<img width="321" alt="screenshot_20160229-184231" src="https://cloud.githubusercontent.com/assets/1304610/13401322/59de60be-df14-11e5-8058-f10e64e3ec89.png">

**Comment by HarelM** [comment]
I see your point but I'm not sure what to do - the size of the control is almost minimal. the only thing that comes to mind is to change the order of the buttons so that the layers control will be at the top. but then every time you open it the buttons below it will move. what do you think?

**Comment by zstadler** [comment]
I thought of two options:
1. Have the layers control on top of the attribution
2. Shorten the layers control

**Comment by zstadler** [comment]
On second thought, shortening the pane is not such a good idea as on some screens, especially on mobile browsers and in landscape mode, there isn't much room for anything:

![screenshot_20160301-190516](https://cloud.githubusercontent.com/assets/1304610/13434973/a20ef606-dfe0-11e5-81bf-2a384eaf08ea.png)

Perhaps this should be a floating pane, with an "X" (close pane) button?

**Comment by zstadler** [comment]
Another option for the initial issue:
3. Add some white gap AFTER the "Advanced" button so that scrolling the layers will allow the button to be fully accessible.

**Comment by HarelM** [comment]
OSM is using panes instead of pop-up/tooltip menus.
You can have a look here:
http://www.openstreetmap.org/#map=10/49.5395/9.0143
Clicking on the layer menu opens a pane from the left on desktop and fills the entire screen on mobile.
Do we want to duplicate this behavior?
This can be easily done with the framework we are already using, check this tutorial:
http://mgcrea.github.io/angular-strap/#/asides
"Click to toggle aside".
What do you think?

**Comment by HarelM** [comment]
@zstadler @valleyofdawn I would love your input here...

**Comment by zstadler** [comment]
I think that's better, especially as it provides the ability to scroll when the pane does not fit the screen height. This is an issue I also have on the desktop, having many additional map sources.

**Comment by zstadler** [comment]
A similar approach could also solve the cropping of the "i" and "?" panes on mobile devices.
