### ISSUE TITLE
No tooltip for the hamburger button

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1414]
##  Feature
Please consider adding a tooltip, such as "preferences" "settings" or "further options" to the button to conform with the behavior of other buttons

**Comment by zstadler** [comment]
**If** a tool tip is added, I suggest "Menu".

**Comment by HarelM** [comment]
I haven't seen any site that has a tooltip for this kind of menu, I don't see a good reason to add one for something so straight forward...

**Comment by HarelM** [comment]
Simple as this may be, I don't believe there's a good reason to implement this...
