### ISSUE TITLE
Fix, Single Adulam coordinate 31.632926°, 34.969041° 197125 / 615639

### ISSUE THREAD

**Issue by nirpacl** [IsraelHikingMap/Site#1418]
The Adulam trail at this point has changed a bit - I can send my recording if needed. I am not sure how to fix the map.
Thx, NirP

**Comment by HarelM** [comment]
The FAQ page has some tips. A better place to report this is our Facebook group or the OSM forum/telegram group.

**Comment by HarelM** [comment]
@nirpacl did you manage to solve this?

**Comment by nirpacl** [comment]
@HarelM  - I will report via FB, Thx.

**Comment by HarelM** [comment]
Thanks for the info and willingness to help!
Let me know if you require more assistance.
I'll be closing this issue now but you can still comment on this thread if needed.
