### ISSUE TITLE
Cliff indication needed in height chart

### ISSUE THREAD

**Issue by Yaniv125** [IsraelHikingMap/Site#1421]
A small but useful features, when planning or hiking,
it will help the user to understand where are the dangerous parts on his route, so he can change or organize accordingly.
Sound alert is also an option.

I'm adding a screenshot example, on how I think it should be implemented
![hiking](https://user-images.githubusercontent.com/75670380/104128198-cfa2e800-536e-11eb-8cb5-b2ddec031f85.jpg)

**Comment by HarelM** [comment]
I have no clue how to do it - both in terms of identification of such cases and in terms of how to draw it on the chart.
Feel free to submit a pull request... :-)
