### ISSUE TITLE
Preserve line breaks in cloud-saved routes' description

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1422]
## What I expect to happen
1. Show line-breaks in the descripion od a saved route
2. Separate the title from the description by a double line-break

Applies to the following places:

#### In the list of saved routes

<img width="35%" src="https://user-images.githubusercontent.com/1304610/104443895-b16ffe80-559f-11eb-80c8-f7a2e9c31c2f.png"/>

#### In the messsage following a successful save

<img width="35%" src="https://user-images.githubusercontent.com/1304610/104448931-7d4c0c00-55a6-11eb-8c32-4eb5f5f4990b.png"/>

#### In the intermittent message shown just after the saved route was loaded

I was unable to create a mockup. See the last screenshot below

#### In the list of saved routes

<img width="35%" src="https://user-images.githubusercontent.com/1304610/104449056-b08e9b00-55a6-11eb-8baa-752924a60e4a.png"/>

#### In the messsage following a successful save

<img width="35%" src="https://user-images.githubusercontent.com/1304610/104441306-29d4c080-559c-11eb-8b4d-e04a3202deea.png"/>

#### In the intermittent message shown just after the saved route was loaded

<img width="35%" src="https://user-images.githubusercontent.com/1304610/104441882-f6466600-559c-11eb-9c5c-40dd4e2fac19.png"/>

## What I did that caused the issue - step by step
Use line breaks in the description of a cloud-saved route

## Things I think the developers should know, images, links etc.
1. The example is available at https://israelhiking.osm.org.il/share/uXPOfXpadq.
2. The mock-ups are using the `white-space: pre-line;` style directive.

**Comment by HarelM** [comment]
I prefer not to touch the toast message style (black pop-up from the button). I have fixed the others.
