### ISSUE TITLE
Limit the size of the log file in a user report

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1424]
## What I expect to happen
Increase the probability of a successful in-app issue report by limiting the number of recent log lines sent, such that the zip file will be less than 25Mb

## What really happened
Sometimes the size of a zipped 72-hours log file is beyond the limitation of the email and the report cannot be sent.

## My environment
* Operating System and version:
* Web Browser and version:

**Comment by HarelM** [comment]
I'll try to limit it to 50,000 lines for testing, let's see what's the size of this case and we'll adjust accordingly.
Maybe I should do the same for the deletion - i.e. remove according to number of lines and not according to last three days...
Let me know what you think...

**Comment by HarelM** [comment]
I'm concerned about app initialisation performance in case I need to keep the last 50K lines and I need to go through the entire log and then delete the relevant lines.
I'll change it for only keeping last three days in case there are more than 50K lines, this way it might solve the issue of keeping longer history while not taking much more to load, or it might even shorten the load time when not deleting...

**Comment by HarelM** [comment]
Version 9.6.155 will have this... We'll need to see how to test this as this is a bit tricky...

**Comment by HarelM** [comment]
Closing for now, I'll reopen in case there are issues with the implementation.
