### ISSUE TITLE
Ignore hidden routes when selecting a route to follow

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1426]
## What I expect to happen
The route that is chosen for the statistics info to be based on the most valuable route as defined by the following criteria, given in decreasing order of importance:
1. Hidden routes have lower value than shown routes
2. Routes routes with opposite direction have lower value than routes in the same direction
3. Recordings have lower value than edited routes

## What really happened
Sometimes the statistics is shown for a hidded route or a route that is going in the opposite ditection.
The user has no control over which of several routes is chosen as the basis for the statistics window.
Temporarily removing routes from the app in order to control this random selection is not applicable when traveling for a few days in bad reception areas.

## My environment
* Operating System and version:
* Web Browser and version:

**Comment by HarelM** [comment]
Route statistics now ignores hidden routes.
Starting to do wighting in order to implement this is an over kill for this feature, IMO.
So I'm wrapping the implementation of this only for hidden routes...
