### ISSUE TITLE
Transaction-based access to the GPS positions buffer

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1427]
## What I expect to happen
The GPS recording should not include duplicate/replayed sections.

## What really happened
Under some unclear circumstances, probably related to device performance, the recorded GPS route has repeated sections. This may be limited to a few GPS points repeated, and up to massive repeats that can bring the application to a near-freeze condition, as shown in this example:

![image](https://user-images.githubusercontent.com/1304610/105319116-12658b00-5bcd-11eb-977c-4d559e9d4408.png)

## Things I think the developers should know, images, links etc.
Currently, the GPS plugin maintains a buffer of past location. After the application recieves a "new position" event, is sent a "get buffer" request to the plugin followed by a separate "erase buffer" request.

In addition, a delayed "erase buffer" request may remove from from the buffer some GPS positions that were added after that buffer was last sent to the application, as demonstrated by the missing sections in the above GPS recording.

We believe that this could enable the above behaviour. If, for some reason, the handling of the "erase buffer" request is delayed and a subsequent "get buffer" request arrives, the plugin may send the same GPS postion more than once.

The proposed solution is to use transaction-based access of the application to the plugin's buffer. A "get and erase buffer" request replace the separate "get buffer" and "erase buffer" requests. As a result, any GPS position that is sent from the buffer to the application cannot be sent again.

 The plugin will take care to remove only the GPS positions that are sent to the application, because the plugin itsels may recieve new GPS positions from the device while performing the "get and erase buffer" request.

**Comment by HarelM** [comment]
Grouped maintenance in the following fork:
https://github.com/HaylLtd/cordova-background-geolocation-plugin
Added an issue there and linked it here.
