### ISSUE TITLE
Remove the association of the Android app with sharing of images

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1428]
## What I expect to happen
The Israel Hiking Map application would not be listed when trying to share an image on Android

## What really happened
Such a sharing always ends up with an error, even when the shared image has geolocation. Recently, Andoid began to remove the location inpormation when a picture is shares. This was probably done for privacy reasons.

ref: https://www.facebook.com/groups/israelhikingmap/permalink/3654503927938107

![image](https://user-images.githubusercontent.com/1304610/105387253-05bd5300-5c1e-11eb-9d33-1f7e3be83fe7.png)

**Comment by HarelM** [comment]
This still works for android 9 and below so I prefer to keep it currently.
Can you check if there are configurations that can be changed in images or file app that will allow sharing the image location as well?

**Comment by zstadler** [comment]
No, there arn't any.
Can you check if this configuration can be added only for Andoid 9 and below?
BTW, I don't remember seeng this change in the Android 10 documentation. Do you?

**Comment by HarelM** [comment]
The file association is in the manifest, I couldn't find documentation on how to condition it...

**Comment by HarelM** [comment]
I think the relevant permission is the following:
https://developer.android.com/reference/android/Manifest.permission#ACCESS_MEDIA_LOCATION
Seems like this permission is a runtime permission added in api 29.
I'm not sure it's worth asking for it...
In a few years when most of the phones will run android 10 and above we should consider removing this... I don't think the majority of the users have android 10 at the moment...

**Comment by zstadler** [comment]
[Here](https://developer.android.com/training/data-storage/shared/media#location-info-photos) are some explanations and a code example for accessing the location information of a photograph. I'm not sure if it is applicable in the "share with..." flow.

**Comment by HarelM** [comment]
@zstadler I've created a branch and pushed the extra permissions in it.
Let me know if this is something you can test once the build will complete:
https://ci.appveyor.com/project/IsraelHikingHost/site/builds/37430847/job/je6meqn8p4vaxvdg

**Comment by HarelM** [comment]
Seems like adding it to the manifest is not enough and one needs to ask for it at runtime.
Since this is not possible without adding another plugin I think we'll keep the current behavior until most of the users are using android 10 or above, and then remove it.
More data can be found here:
https://developer.android.com/training/data-storage/shared/media#media-location-permission
I believe this issue can be closed...

**Comment by HarelM** [comment]
According to our data in google play store it seems like most users are using android 10 and 11 (71%).
I was wrong this would take more years to get there...
I'll remove the file association for next version.
