### ISSUE TITLE
Disconnect from a cloud save when all routes are deleted

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1429]
## What I expect to happen
After I open a saved route ("share") and use the "delete all routes" button, I expect the next "save to cloud" to be new and disconnected from the saved route I opened earlier.

## What I did that caused the issue - step by step

1. Open a saved route
2. "Delete All Routes"
3. If done in the browser, the saved route's ID remains in the address bar
4. Plan a new route
5. "Upload to Cloud and Share"
6. See the "Update current saved work"

**Comment by HarelM** [comment]
I'm not sure this is the required behavior as a user may want to change a share by removing all the routes and drawing them again which won't be possible if the above is implemented.
I think the main question here is:
When and how to clear the currently "selected" share.
And I believe this requires a discussion.

**Comment by HarelM** [comment]
Moved to the discussion wiki page.
Closing here until the required behavior is defined. We'll probably reopen this afterwards...

**Comment by HarelM** [comment]
The scenario of editing a cloud save, clearing all the routes and updating it is probably less important than just clearing the currently seen cloud save.
Reopening according to the discussion that was made.

**Comment by HarelM** [comment]
Somewhat related to #1443 although from a different point of view - i.e. this should allow an easy way to clear selected cloud save.
