### ISSUE TITLE
New GPX file format has issues in other applications.

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#144]
See the first report at:
http://groopy.co.il/forummessage.aspx?messageid=413507

**Comment by HarelM** [comment]
The GPX file the site allows the user to download is a valid GPX file, although this file has segments in it.
A possible solution will be to allow the user to convert this file a single track/route GPX file in the convert window for external applications. I do not want to revert back to previous version of GPX file as the format does not allow the user to save his work to a file and be able to continue working on it later with the exact same state. @zstadler, @valleyofdawn do you have another idea how to solve this?

**Comment by valleyofdawn** [comment]
I think it's more important to have a single-segment GPX by default than to be able to continue editing it "in the exact same state".
What do you mean by that, BTW. What was lost in the previous version when you saved a GPX?

**Comment by zstadler** [comment]
The issue with Amud Anan can be the segments, the use of <rte> vs <trk>, or
both.

I'd also like to look into enabling "waypoint navigation" in Oruxmaps for
routes created by the IHM site.

**Comment by zstadler** [comment]
1. Amudanan ignores <rte> and <wpt> entries.
2. Amudanan is looking for a <trk> entry. if not found, it hangs...
2. Amudanan accepts only the first <trkseg> of the <trk>

It seems like Amudanan only accepts gpx files in the format it creates...

**Comment by HarelM** [comment]
When saving to a file in previous GPX version, If you load the file after you save it the application will add points on the route in places that are not what you clicked when you created the route originally...
I can't control Amudanan, you can try and open an issue there...
Since the GPX format is correct my main priority is to allow the user to save the current state of editing since my goal is to keep users on our site and not to let them wonder off to other sites.
Having said that I know we're not the only site in the world so supporting other sites can be a lower priority using the convert dialog.

**Comment by valleyofdawn** [comment]
Actually even in IHM the saved GPXs render imperfectly. Note the stiches between the routed and manual sections here. 
[http://israelhiking.osm.org.il/#/16/30.8557/35.0160?s=9aUTVW1fpx](http://israelhiking.osm.org.il/#/16/30.8557/35.0160?s=9aUTVW1fpx)

**Comment by HarelM** [comment]
This is a bug, not an example :-) Can you make a shorter example and add the file here (either add the content here or send it to me by mail).
I tried to reproduce it but couldn't, I found another bug #145 and fixed it and also made a small fix related to this bug/feature, so I hope you won't be able to reproduce it but the fix is not that extensive so you'll probably would.
But this is a bit of topic (although important nevertheless).

**Comment by valleyofdawn** [comment]
[IsraelHikingMap (20).gpx.txt](https://github.com/IsraelHikingMap/Site/files/164611/IsraelHikingMap.20.gpx.txt)

Remove the .txt

**Comment by HarelM** [comment]
I've added an option to the convert dialog to support other applications, I have briefly tested it...
I know it's a bit hidden as I see it it is not different than any  other application where save just saves the file and "save as" allows the user to convert the format.
Let me know if you find any issue. I'll leave this issue open for the coming week, If no comment will be added I'll close it.
