### ISSUE TITLE
Add indication for currently selected cloud save

### ISSUE THREAD

**Issue by onzd** [IsraelHikingMap/Site#1443]
האם ניתן להוסיף נקודה על איזה מסלול מוצג כעת במפה? יש לי לדוגמא כמה מסלולים שתכננתי עם אותו שם פשוט יש להם שינויים קלים ואני רוצה למחוק את השאר יקל עלי אם יהיה איזה שהוא סימן על המסלול המוצג כעת ברימת המסלולים
תודה

**Comment by HarelM** [comment]
כרגע אין סימון למסלול הנבחר. אני מסכים שחסר.
אני אחשוב מה הדרך הנכונה לנהל את זה.
בכל מקרה אתה יכול לעדכן את השם כרגע, קצת מסורבל אבל אפשרי...

**Comment by onzd** [comment]
סבבה אולי נקודה ליד

**Comment by HarelM** [comment]
@onzd It would be great if you could sketch something up and attach it here, otherwise I'll need to think of a good way and it may take longer...

**Comment by onzd** [comment]
‫בתאריך יום ד׳, 24 בפבר׳ 2021 ב-18:20 מאת ‪Harel M‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by HarelM** [comment]
Image attachments to email do not work here unfortunately... :-(

**Comment by HarelM** [comment]
I've decided to mark the shown route as bold as it is the simplest solution.
#1429 allow the ability to clear the currently selected share by pressing the delete all routes button.

**Comment by onzd** [comment]
Thanks!

בתאריך יום ו׳, 2 באפר' 2021, 16:06, מאת Harel M ***@***.***>:
