### ISSUE TITLE
Add POI of drinking water

### ISSUE THREAD

**Issue by amiad** [IsraelHikingMap/Site#1444]
## Feature
Drinking water shown on the map but it is hidden sometimes. Picnic site or gate hide its.
If you add POI then it will more prominent. Users will be able to add images, descriptions and links.
Drinking water less important in city but very important in the desert.

**Comment by HarelM** [comment]
Sorry to disappoint, but this was discussed thoroughly and decided there's no real meaning in adding image, description or title to drinking water.
You can zoom in to avoid hiding drinking water and you may open an issue in the VectorMap repository if you think the priority of features is not correct and things should not be hidden in some cases.
But the bottom line is that I don't think drinking water should be a "full" POI...

**Comment by amiad** [comment]
עברתי לעברית.
לפעמים צריך הסבר איך להגיע לברז או איך לפתוח אותו. קרה כבר כמה פעמים שמשתמשים הוסיפו נקודת אטרקציה ליד ברזים בשביל תמונות והסברים, אפשר להבין שהסימון במפה בלי נקודה לא מספיק להם.

**Comment by HarelM** [comment]
אשמח לראות דוגמאות למקומות כאלה וסטטיסטיקה של כמה ברזים יש לעומת כמה מהם עם מידע נוסף.
ההנחה שלי היא שזה לא מצדיק את המאמץ...
יתכן שאני טועה... :-)

**Comment by amiad** [comment]
לדעתי לפחות בכל מקורות המים בשביל ישראל מחוץ ליישובים צריך להיות הסבר ובמיוחד בעוקבים של רט״ג (יש כיום חמישה ואם המים שם נגמרים כדאי שיהיה מספר טלפון להתקשר).
הישראל יש כיום [1323 ברזים מסומנים](http://overpass-turbo.eu/s/15KT) ומתוכם[ 42 עם תיאור או תמונה](http://overpass-turbo.eu/s/15KR) למרות שהממשק של IHM לא תומך בכך. אני מניח שאם הממשק יתמוך יהיו יותר.

**Comment by HarelM** [comment]
בעוד שאני מכבד מאוד את דעתך, אני חושב שזה רק יהפוך את המפה לעמוסה מידי, אני לא מצליח להשתכנע שזה יועיל יותר משזה יעיק...

**Comment by amiad** [comment]
טוב, תודה.
אתה המפתח
