### ISSUE TITLE
Drawing of highway 90 is fragmented in coordinates: 31.681734°, 35.441759°

### ISSUE THREAD

**Issue by arielgee** [IsraelHikingMap/Site#1448]
## Bug
The drawing of highway 90 is fragmented in coordinates: 31.681734°, 35.441759°

## What I expect to happen
Road 90 should be continuous.

## What really happened
The drawing of road 90 in coordinates: 31.681734°, 35.441759° is fragmented.

## What I did that caused the issue - step by step
Zoom in on 31.681734°, 35.441759°

## My environment
* Windows 10
* Firefox v86

## Things I think the developers should know, images, links etc.
![image](https://user-images.githubusercontent.com/5435780/109636923-d3740f00-7b54-11eb-85d1-c8563679dda0.png)

**Comment by HarelM** [comment]
Thank you very much for taking the time to report this issue!
This looks like a mapping issue.
![image](https://user-images.githubusercontent.com/3269297/109638796-1e8f2180-7b57-11eb-876d-b0a552feb14e.png)
Would you like to try and solve this yourself?
https://www.openstreetmap.org/edit#map=17/31.68170/35.43992
Closing this issue as there's no real issue with the code.
Feel free to continue the conversation here nevertheless... :-)

**Comment by zstadler** [comment]
שלחתי הערה לעורך שמחק את הקטע, כנראה בטעות

https://www.openstreetmap.org/changeset/93736533

**Comment by zstadler** [comment]
<div dir="rtl">
תיקנתי את הטעות ב

https://www.openstreetmap.org/changeset/100295824
</div>
