### ISSUE TITLE
מדוע השביל האדום בארבל לא ניתן לתכנון?

### ISSUE THREAD

**Issue by onzd** [IsraelHikingMap/Site#1453]
כאשר ניסיתי לתכנן את המסלול על האדום הסימון לא ניתן להעשות הסמן בורח לשבילים אחרים https://israelhiking.osm.org.il/share/bCmBEblU0t

**Comment by zstadler** [comment]
<div dir="rtl">
בעיות ניתוב נובעות כמעט תמיד מבעיות במיפוי ולא מבעיות בתוכנת הניתוב. כיוון שהאתר והאפליקציה מאפשרים רמות זום גבוהות מאד, זו דרך אפקטיבית לבדוק את נכונות המיפוי. 

אפשר גם להשתמש בעורך של OSM על מנת לבדוק מי מהצמתים אינו מחובר, על ידי גרירתו, מעקב אחרי הדרכים שזזות בעקבות כך, ולתקן אותו. חשוב גם לוודא שהתיוג נכון. למשל, לא יתבצע ניתוב דרך קו שאין לו תג highway מתאים. 

הגיטהב של האתר מתאים לדיווחים על מצבים שבהם אין ניתוב למרות שהמיפוי תקין. 
אפשר לבקש עזרה בענייני מיפוי ממשתמשים אחרים בקבוצת הפייסבוק שלנו או [בקבוצת הטלגרם OSM_Israel](OSM_Israel
https://t.me/OSM_Israel)

לפני שאתה פונה שם, אנא בדוק שהקישור שהכנת עובד, כי אני לא מצליח לפתוח אותו.
</div>

**Comment by zstadler** [comment]
Resolved by
1. [Correcting](https://www.openstreetmap.org/changeset/100550962) invalid `sac_scale` tag of the section
2. [Replacing](https://github.com/IsraelHikingMap/graphhopper-docker/commit/e25ab5a20581eb8f33c99af55091c5bf2f99dc8d) `foot` routing profile with `hike` routing profile
