### ISSUE TITLE
עזרה בתיקונים בנחל יבניאל

### ISSUE THREAD

**Issue by onzd** [IsraelHikingMap/Site#1458]
מעתיק לכאן הודעה שרשמתי בטלגרם

עדכנתי  כמה דברים בנחל יבניאל וגם שני שבילים שחורים קצרים אם העלתי אתמול האם לוקח קצת זמן עד שאפשר לעבור עליהם עם  הסמן ושאלה שניה האם טעיתי בעורך מפה ואם טעיתי אפשר לומר לי היכן ומה עלי לעשות
https://israelhiking.osm.org.il/share/qG32M2dIoX

**Comment by HarelM** [comment]
הקישור לא תקין...

**Comment by onzd** [comment]
https://israelhiking.osm.org.il/share/50AKhJZ7ug

‫בתאריך יום א׳, 14 במרץ 2021 ב-14:55 מאת ‪Harel M‬‏ <‪
***@***.***‬‏>:‬

**Comment by HarelM** [comment]
חכה למחר... אולי לוקח לשרת עוד זמן להתעדכן מבחינת הניווט.
בלי קשר, אני ממליץ להוריד את כמות הנקודות בקווים שהעלית, הם יכולים להיות יותר ״פשוטים״...

**Comment by onzd** [comment]
תודה

בתאריך יום א׳, 14 במרץ 2021, 15:00, מאת Harel M ***@***.***>:

**Comment by zstadler** [comment]
היתה תקלה בעדכון המידע עבור הניווט. התקלה תוקנה והניווט תקין
