### ISSUE TITLE
Barrier POI mapping doesn't comply with OSM guidelines

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1460]
## What I expect to happen
POI mapping by IHM to comply with OSM guidelines.

## What really happened
Simple barrier POIs are placed at the junction while the [OSM guideline](https://wiki.openstreetmap.org/wiki/Key:barrier#How_to_map_barrier_nodes) is
> Place on a highway or a barrier way or at the common node between a highway or a barrier way (if it's part of both). Do not place a barrier tag on a junction between highways. 
> ![image](https://user-images.githubusercontent.com/1304610/111805843-14e91600-88da-11eb-96ff-95815a37e318.png)

## What I did that caused the issue - step by step
Added a simple barrier POI on a way leading to a junction in [changeset 101314074](https://www.openstreetmap.org/changeset/101314074). The barrier was added as a tag on the existing node of the junction.

## My environment
* Operating System and version: Android 10
* Web Browser and version: App version 9.6.177

## Things I think the developers should know, images, links etc.

**Comment by HarelM** [comment]
Related to code written here:
https://github.com/IsraelHikingMap/Site/blob/8a4e8e7a8c9b68c9a116b6b6ba05a1c6a09bebd1/IsraelHiking.API/Executors/SimplePointAdderExecutor.cs#L157
Since the GPS location can be anywhere around the junction there might not be a easy solution for this issue...

**Comment by zstadler** [comment]
As far as I understand the code, If the closest node is a start/end node of a highway, it does not have to be within 5 meters of the requested position. 

In a T junction, at least one of the connecting highways connects using its first or last node, which means that the barrier is likely to be put on the junction even when the requested location was more than 5 meters away from it.

I believe an existing node can be tagged as a barrier if it is not a junction and it is within 5 meters.

@HarelM 
I tried nooking at the code performing elastic search on highways and nodes, and I'm not sure what is the best way to identify a junction node. Any ideas?

**Comment by HarelM** [comment]
The first part of the code gets the closest highway, and this highway must be close enough, so the condition about start or end is reasonable, I think.

The simplest thought about identifying a T junction is to find the closest 2 lines to a point and testing if the end point of one exists in the other.
But again, I'm not sure this covers all the cases and complicating this code can cause more bugs in this process which I prefer to keep simple. 
for example what should happen for this scenatio: `.T` where the point (gate measured by the GPS, T is the existing lines) is close enough to both lines but not on either of them and within the GPS error it can be on either line in theory...

**Comment by zstadler** [comment]
Summary of off-line discussion:

- Use the current algorithm to find the candidate `highway` and the candidate node.
- If the candidate node is not a junction, place the new `barrier` tag on it.
- Otherwise, use a nornal from the point to the `highway` and insert a new `barrier` node at their intersection.

Notes:
- A junction is not necessarily an edge of a way. 
- An internal point of a way is a junction if it is also part of other way. 
- If the edges of a way are identical, all of its nodes are internal.
- If a node is not internal to any way, it is a junction if it belongs to 3 ways or more.

**Comment by HarelM** [comment]
I'm not sure what should be the right behavior in the following case:
![image](https://user-images.githubusercontent.com/3269297/114363921-8cc8fa00-9b81-11eb-8b44-772ec0d10996.png)
Also there might not be a close enough node and the normal might not be on the line, for example the following case - in this case the current code throws an exception and doesn't add the gate, not sure this is the right behavior.
![image](https://user-images.githubusercontent.com/3269297/114364216-d7e30d00-9b81-11eb-8d99-45d6f20b6b72.png)
Feel free to post use cases here and proposed solutions (expected behavior) to make sure we cover most of the cases we can think of.
I usually write a unit test for each one, to make sure it is covered, here are the tests that I wrote in the previous effort to write this, I believe these tests are partial and we should add as many different cases we can think of:
https://github.com/IsraelHikingMap/Site/blob/57a771632515e4804ecf6ac329314617a864cb5e/Tests/IsraelHiking.API.Tests/Executors/SimplePointAdderExecutorTests.cs#L22

**Comment by zstadler** [comment]
### Example 1
![image](https://user-images.githubusercontent.com/3269297/114363921-8cc8fa00-9b81-11eb-8b44-772ec0d10996.png)
Both ways are at the same distance from the requested location, and that location is a junction. In such a case, it should give an error. It can be the same error as if there is no `highway` within the allowed distance.

Similarly, when the normal does not intersect with an existing segment of the way
![image](https://user-images.githubusercontent.com/1304610/114371932-ae2de400-9b89-11eb-877f-4928a0a4dd1e.png)

Therefore:
- Use the current algorithm to find the candidate `highway` and the candidate node.
- If the candidate node is not a junction, place the new `barrier` tag on it.
- Otherwise, find the intersection location of a normal from the point to the closest `highway`
  - If the normal is not intersecting an existing line segment, issue an error
  - If the normal is intersecting at the junction node, issue an error
  - Otherwise, insert a new `barrier` node at the intersection of the normal and the way segment.

### Example 2
![image](https://user-images.githubusercontent.com/3269297/114364216-d7e30d00-9b81-11eb-8d99-45d6f20b6b72.png)
the barrier should be put on the edge node because it is not a junction
> If the candidate node is not a junction, place the new barrier tag on it.

**Comment by zstadler** [comment]
@HarelM ,

Please also check this situation:

![image](https://user-images.githubusercontent.com/1304610/114611833-183daa80-9caa-11eb-8f20-8e3a4ed2da15.png)

If I read the code correctly, the barrier can be place quite far from the requested location.

**Comment by HarelM** [comment]
I would like to take the given position (from the server's request parameter) and not use the place on the way (normal interception) for two reasons:
1. I hope the location is coming from the GPS and it is accurate, also it can come from adding a private POI but in this case the user sees where he places the point
2. Easier to implement

I'll push the changes I made in the code.
It would be helpful for me if you could review the code and tests to see if I missed a case or not.

**Comment by HarelM** [comment]
Need to add line projection support.

**Comment by HarelM** [comment]
@zstadler I'll let you know when I publish this so you can test it.
I have only tested it using a unit test...
