### ISSUE TITLE
Unable to change cloud save name

### ISSUE THREAD

**Issue by onzd** [IsraelHikingMap/Site#1462]
ניסיתי לשנות שמות מסלולים בענן
למשל הירדן ההררי ל הירדן הררי-קיץ
והשמות אינם נשמרים

**Comment by HarelM** [comment]
תודה על הדיווח, 
תוכל לפרט בבקשה בדיוק מה הצעדים שעשית ואיפה אתה רואה שהשם לא השתנה?
שים לב שיש שם מסלול המופיע במסלולים הפרטיים ושם השמירה בענן שהם בלתי תלויים אחד בשני.

**Comment by onzd** [comment]
1: לוחץ על איקון של האיש הקטן ורואה את המסלולים
2: בוחר מסלו שאני רוצה לשנות את שמו
3:לוחץ על עריכה מצד ימין למטה
4: עורך את השם החדש
5: לוחץ על הוי מצד ימין
6: השם מופיע בלי בעיה 
7: לוחץ שוב על האיש הקטן מצד ימין לראות את המסלולים ואז השם הנכון מופיע לשניה ומיד נעלם

**Comment by HarelM** [comment]
תוכל לצרף תצלומי מסך או סרטון?
לא ברור לי איפה אתה עורך את השם, האם מדובר בהקלטות או שמירות בענן או בכלל במסלולים ציבוריים שמופיעים על המפה...
מצטער על ההצקה, אני פשוט רוצה לוודא שאני מבין בדיוק מה הבעיה...

**Comment by HarelM** [comment]
תודה על הזמן, הצלחתי לשחזר את הבעיה ולהבין את הסיבהת אעבור לאנגלית לצורך תיעוד פינימי ברשותך.
Problem statement:
Unable to update the name of a could save when editing it though the cloud saves dialog.
Steps to reproduce:
1. Click the user icon
2. Click cloud saves
3. Click on a save
4. Click the pencil at the bottom to edit
5. Edit the name
6. Click the "v" icon to save
7. --> Error can be seen in the console and no data is sent to the server.

**Comment by onzd** [comment]
כל הכבוד ..תודה

בתאריך יום א׳, 28 במרץ 2021, 21:54, מאת Harel M ***@***.***>:

**Comment by HarelM** [comment]
בכיף, יקח עוד קצת זמן עד שזה ישוחרר...
תודה רבה על הזמן שאתה משקיע בדיווח על הבעיות! זה עוזר לנו מאוד! (לא ציני)
