### ISSUE TITLE
POI update happened twice

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1466]
## What I expect to happen
POI update to happen once

## What really happened
Two pictures were arred wtice to the OSM object

## What I did that caused the issue - step by step

- חיפשתי נקודת עניין ציבורית ונכנסתי לעריכה שלה - https://www.openstreetmap.org/way/334894225
- עברתי מהאפליקציה למצלמה, צילמתי תמונה, חזרתי לאפליקציה והוספתי את התמונה לנקודת העניין
- הוספתי תמונה נוספת לנקודת העניין
- שמרתי את העריכה והמשכתי בנסיעה

## My environment
* Operating System and version: Andoid 10
* Web Browser and version: App ver 9.8.1 

## Things I think the developers should know, images, links etc.

- The update probably happened when there was no network access
- The first picture was taken at 30.3.21 10:17:41 local time
- The way history: http://osm.mapki.com/history/way.php?id=334894225
- First changeset: http://osm.org/browse/changeset/101964223
- Second changeset: http://osm.org/browse/changeset/101966263
- The client and server log files are in the mail

**Comment by HarelM** [comment]
Seems like I forgot to do run a "distinct" on added and removed urls and images...
Other than that, it seems like the mechanism is working great - the server got the request but the client timed out, so later on the client sent the request again.
The server who already uploaded the images to wikimedia did not upload them again.
Seems like it took the server around a minute to upload the images to wikimedia which is the timeout time in the client.
I'm considering increasing the timeout in the client to 3 minutes, what do you think?

**Comment by zstadler** [comment]
> I'm considering increasing the timeout in the client to 3 minutes, what do you think?

If it is all happening in the background, and the user continues to use the app as usual, I think increasing the timeout would be an improvement.
