### ISSUE TITLE
Since 8.3.16 - I can't save multiple points treks !  Something has changed on 3.8.16 !!

### ISSUE THREAD

**Issue by yehielgl** [IsraelHikingMap/Site#147]
Save trek has changed : 
1. Used to be 2 options: save to gpx and save to kml. Now - only gpx
2. New GPX saved file is segments only, no multiple points regular trek.

As a result, the downloaded GPX file can not be used by GPS devices and can not be imported to other navigation programs such as Amud Anan.

I am using OSM on a daily basis and I am very much sorry that this great program is no longer working.

Could anybody help ?

Thanks !
Yehiel Goldstein,   elrad@netvision.net.il   +972 52 627 8883

**Comment by HarelM** [comment]
See issue #144 - I'm looking for ideas how to solve this.

**Comment by HarelM** [comment]
BTW, Thanks for taking the time to report this issue, we appreciate it :-).

**Comment by zstadler** [comment]
I suggest we do not close a duplicate issue until the primary issue is closed. This will allow the opener to know when he/she should expect the resolution, and will enable us to verify that all duplicate issues are indeed resolved when the primary issue is closed.

**Comment by HarelM** [comment]
Sure thing!

**Comment by HarelM** [comment]
I have added an option in the covert dialog (the two arrows button in the right pane) called Single Tack GPX.
This should allow you to use the application in order to convert the files it outputs to other applications.
This might not be the final version but it should allow you to continue working.
Sorry for the inconvenience.

**Comment by yehielgl** [comment]
Hi Harel,

 

Thank you SO MUCH for responding to my email and for adding the “missing link”.



As I am a “very heavy duty” user of your OSM web site, and works with many “trekkers”, would it be possible to call you on the phone for just very few minutes ?  I would appreciate it very much.



I am a bit confused due to the major change on 8.3.16.   The former version was just great. Now, I can still work somehow (due to your kind help) but it is very much different from what it was just few days ago.



In the former version, when pressing “Save”, I could have selected between GPX and KML, so, I didn’t have to save it in one version and then go again and convert it to the desired version.



I normally clicked twice: one time on the GPX and one time one the KML and could immediately use them – and go for the trek immediately. 



The GPX format was the good “single trek” version.



I am matching here 4 files, to demonstrate the situation.



1.      1. Trek-1 – ORIGINAL.    This is a short part of Israel Trail. This is the file which I received after I pressed “SAVE”. This format could not be imported into other applications and is not so useful with GPS units.



2.      2. Trek-1 Single Trek GPX converted by OSM from ORIGINAL Trek-1 - WORKS GOOD

This file is a result of using the last feature you have added. I used it to convert the ORIGINAL file into Single Trek GPX. 

This file is useful and can be imported to other applications, THANK YOU !!!



3.      3. KML -  Coverted by OSM from THE original '' Trek-1 '' -  Not the usefull KML format

This is a KML file. I used the conversion feature to convert the ORIGINAL file. Well, this gave a strange KML file, which is definitely not Single Trek GPX and therefore, Google Earth will not support all the useful functions such as “Elevation Profile”.

In fact, Google Erath will not let you “Right Click” on the trek to open the special Google Earth functions.



4.      4. KML -  Coverted by OSM from ''Trek-1 Single Trel GPX'' - Not the useful KML format

Here I tried to convert the GOOD GPX file (#2). It didn’t work. It converted the GOOD GPX format (Single Trek GPX) into the same KML file format as in number 3.



5.      5. KML - Converted by Amud Anan from the ORIGINAL Trek-1 - THIS WORKS GOOD



Here I converted the GOOD Single Trek GPX in Amud Anan – into GOOD KML file.

 

Please click on the file to see the difference between KML formats 3,4 to the GOOD KML #5.

 

So, thank you so much to allow the conversion and let me work somehow with OSM.



I really hope you can restore the OSM GREAT web site to the way it was until 8.3.16



I will appreciate very much if you will let me call you on the phone for just very few minutes.  Would you be kind to send me your phone number ?

 

I look forward to hearing from you.

 

With kind regards

Yehiel Goldstein

Petach-Tikva

052-627-8883

elrad@netvision.net.il <mailto:elrad@netvision.net.il>

**Comment by yehielgl** [comment]
Hi Harel,

Thank you SO MUCH for responding to my email and for adding the “missing link”.
As I am a “very heavy duty” user of your OSM web site, and works with many “trekkers”, would it be possible to call you on the phone for just very few minutes ?  I would appreciate it very much.

I am a bit confused due to the major change on 8.3.16.   The former version was just great. Now, I can still work somehow (due to your kind help) but it is very much different from what it was just few days ago.

In the former version, when pressing “Save”, I could have selected between GPX and KML, so, I didn’t have to save it in one version and then go again and convert it to the desired version.

I normally clicked twice: one time on the GPX and one time one the KML and could immediately use them – and go for the trek immediately. 

The GPX format was the good “single trek” version.

I am matching here 4 files, to demonstrate the situation:
1.	1. Trek-1 – ORIGINAL.    This is a short part of Israel Trail. This is the file which I received after I pressed “SAVE”. This format could not be imported into other applications and is not so useful with GPS units.
2.	2. Trek-1 Single Trek GPX converted by OSM from ORIGINAL Trek-1 - WORKS GOOD

This file is a result of using the last feature you have added. I used it to convert the ORIGINAL file into Single Trek GPX. 

This file is useful and can be imported to other applications, THANK YOU !!!
3.	3. KML -  Coverted by OSM from THE original '' Trek-1 '' -  Not the usefull KML format

This is a KML file. I used the conversion feature to convert the ORIGINAL file. Well, this gave a strange KML file, which is definitely not Single Trek GPX and therefore, Google Earth will not support all the useful functions such as “Elevation Profile”.

In fact, Google Erath will not let you “Right Click” on the trek to open the special Google Earth functions.
4.	4. KML -  Coverted by OSM from ''Trek-1 Single Trel GPX'' - Not the useful KML format

Here I tried to convert the GOOD GPX file (#2). It didn’t work. It converted the GOOD GPX format (Single Trek GPX) into the same KML file format as in number 3.
5.	5. KML - Converted by Amud Anan from the ORIGINAL Trek-1 - THIS WORKS GOOD
Here I converted the GOOD Single Trek GPX in Amud Anan – into GOOD KML file.

Please click on the file to see the difference between KML formats 3,4 to the GOOD KML #5.

So, thank you so much to allow the conversion and let me work somehow with OSM.

I really hope you can restore the OSM GREAT web site to the way it was until 8.3.16

I will appreciate very much if you will let me call you on the phone for just very few minutes.  Would you be kind to send me your phone number ?

I look forward to hearing from you.

With kind regards
Yehiel Goldstein
Petach-Tikva
052-627-8883
elrad@netvision.net.il

**Comment by HarelM** [comment]
I understand your issue, as I said, this is a temporary solution for you to be able to continue working until we implement a proper solution, hopefully this week.
The KML file is generated by a third party application called GPSBabel. There is little I can in order to change the resulting file without completely stop using GPSBabel. Fixing this will require more time and will probably not be fixed in the coming week.

**Comment by yehielgl** [comment]
Thank you so much !  i am already working with the "Single Trek GPX"  conversion that you have added -  for this coming week's treks.    THANKS !!

**Comment by HarelM** [comment]
![image](https://cloud.githubusercontent.com/assets/3269297/13725896/6531503a-e8b9-11e5-8d7b-7c6a40721b35.png)

Coming soon... no more convert button.
