### ISSUE TITLE
Recording is stopped and deleted by delete all routes

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1471]
## What I expect to happen
- When all routes are deleted, the active recording should continue
- If a recording is active, the user can only delete it after the recording is stopped

## What really happened
When all routes are deleted, the active recording is also stopped and deleted.

## What I did that caused the issue - step by step
1. Load a saved route
2. Activate track recording
3. Record for a while
4. Delete all routes

**Comment by HarelM** [comment]
While it's possible to delete all other routes which is not the recording, I'll use the existing code that will ask to simply stop the recording before deleting all routes...
