### ISSUE TITLE
Add more images for apple app store

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1472]
There are currently not enough images in apple app store for the app and the image that exists there is old...

**Comment by HarelM** [comment]
Seems like the process of creating images takes a lot of time and effort and I tend to believe someone professional should do it and I'm willing to pay for it.
@zstadler please assign this to you in case you would like to do it.

**Comment by zstadler** [comment]
@HarelM,
While I'm at it, what screenshots do you propse we should have?

I was thinking of:
- Hiking Map, at a soom that shows the trails, together with the minimal statistics
- MTB map, sat a soom that shows the trails, and the height graph
- Layers pane, showing the POI types and public trails
- Public POI pane example
- Save to cloud dialog
  ![image](https://user-images.githubusercontent.com/1304610/114263062-08913e00-99ec-11eb-9d64-398e5503fc86.png)

**Comment by HarelM** [comment]
Currently the android store has a few good examples: 3d inside Tel Aviv,
Trails over satellite imagery, a screenshot wuth the menu fully open (?), a screenshot while recording (?).
I'm not sure the save to cloud is a good looking dialog to show, your call.
In any case, everything is better than now, and we could always add more... :-)

**Comment by HarelM** [comment]
Phone discussion summary - try and out source it using fiverr or other service.

**Comment by HarelM** [comment]
The following is the instruction I gave for image creation:
1. Open the following address using the app: https://israelhiking.osm.org.il/map/13.32/32.6025/35.1447 
1.1. Click on one of the green circles with a number to show the points of interest grouping 
2. Open https://israelhiking.osm.org.il/map/17.00/32.0811/34.7968 
2.1. Use two finger swipe (like when you scroll in touchpad) to tilt the map and get the 3D view of the buildings, you can rotate the map using two fingers to get a good angle 
2.2. Click Menu (Hamburger button top right) -> מסלולים - מפות - שכבות (4th button) -> Click on the eye icon next to "נקודות עניין" To turn off all the wikipedia icons on the map 
3. Open: https://israelhiking.osm.org.il/poi/OSM/way_484395176?language=he and take a screen shot of the panel after it opens: 
4. Open: https://israelhiking.osm.org.il/poi/OSM/way_484395176?language=he and close the panel (x at the top left) to see the map 
5. Open: https://israelhiking.osm.org.il/share/VYgzXU94B1 
5.1. use two finger swipe to tilt the map back to the original top view (i.e. no "3D" mode) 
5.2. Click menu -> "תכנון מסלול" to present the plan route menu 
6. Open: https://israelhiking.osm.org.il/share/Wovk7ylvzW 
6.1. Click menu -> "גרף גבהים וסטטיסטיקות" (third button) to present a statistics bar at the bottom -> click the right most button in the bar at the bottom of the screen to open the height chart 
7. Click the menu -> "עוד..." (last button) to create a screenshot with the entire menu open 
8. Open https://israelhiking.osm.org.il/share/1B6gFnbnVC

**Comment by HarelM** [comment]
The following is the initial response, I've asked to add the following text:
1. מפה וקטורית
2. בניינים בתלת מימד
3. נקודות עניין
4. תכנון מסלול
5. הצללה דינאמית
6. סטטיסטיקות
7. נוחות שימוש
8. תצלומי לווין

Besides that the only changes needed are:
6: I would like it to have the route planning bar open (like image 4) and the statistics open: see the attached image:
7: I think it would be better to have the menu popup effect moved to the other side (left) in order not to have it cut between the images as it's hard to read...

![Sample design 1](https://user-images.githubusercontent.com/3269297/116963943-e5884000-acb2-11eb-93fe-fc3c8a281973.jpg)

I think it looks great. I'll probably upload them to the stores once the last required changes are made.

**Comment by HarelM** [comment]
@zstadler comments:
Images 4 and 8 are too tilted.
Image 8 link was updated in the above list and was sent to the designer.

**Comment by HarelM** [comment]
Latest:
![Sample design 2](https://user-images.githubusercontent.com/3269297/117105717-45501b00-ad87-11eb-88d5-a1429f7a27ec.jpg)
Looks a lot better.
I'll ask to change the frown face to smiley face in all the images.

**Comment by zstadler** [comment]
#### Image 4
Show the planned routes more visibly
   <img width="35%" src="https://user-images.githubusercontent.com/1304610/117110251-84359f00-ad8e-11eb-8934-dcc3de93d0dd.png"/>
#### Image 5
A different location would better show the dynamic hill-shading - https://israelhiking.osm.org.il/share/FgbQbAb3jc
<img width="35%" src="https://user-images.githubusercontent.com/1304610/117110888-7af90200-ad8f-11eb-839e-bb84817d094c.png"/>
#### Image 6
- Show the MTB map background as in the link, not the Hiking map
-  Add the statistics table in addition to the height graph - click the table icon after the graph is shown
<img width="35%" src="https://user-images.githubusercontent.com/1304610/117111338-1ab69000-ad90-11eb-8b91-a31a77dd6cb8.png"/>
#### Image 8
Show the updated image - https://israelhiking.osm.org.il/share/4he5XmUDQ3
<img width="35%" src="https://user-images.githubusercontent.com/1304610/117109975-21dc9e80-ad8e-11eb-86e6-fa0e35bea705.png"/>

**Comment by HarelM** [comment]
I've requested to change image 8 and image 4.

**Comment by HarelM** [comment]
[Design.zip](https://github.com/IsraelHikingMap/Site/files/6445835/Design.zip)
This is the last delivery.
It's not perfect, the iPad images were not taken on an iPad and have some incorrect images but I've reached my patience limit, this is good enough for my needs and a lot better than what it used to be...
