### ISSUE TITLE
Improve current location on route algorithm

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1473]
## What I expect to happen
When following a route that is looping over itself or crossing the algorithm should find the right place I'm current at.

## What really happened
When following a route that is looping over itself or crossing the algorithm to find the current location on the route misses sometimes

## What I did that caused the issue - step by step
1. Plan a route back and forth
2. Enable GPS
3. Watch ETA

## My environment
* Operating System and version:
* Web Browser and version:

## Things I think the developers should know, images, links etc.
 The current algorithm only relays on current location and not past location and general direction which should be used to improve it.

**Comment by HarelM** [comment]
I'm having a hard time defining the right steps to find the current location on a route:
Possible relevant data:
1. Previous location
2. Current direction
3. None of the above

Pseudo code algorithm:
1. Find the closest route
2. Find the closest segment
3. Compare segment direction to current direction
--> here's where I got stuck as finding another segment is by definition not the closest one and I'm not sure what should be the criteria here to select a different segment...

Any help would be appreciated...

**Comment by zstadler** [comment]
Alternatively, the problem can be viewed as selecting the best fit from a set of candidates.

For example:
- Find all routes within a radius `R`, say 50 meters.
- Find all route segments within the radius R where the route direction is within an allowed difference `D`, say 30 degrees, from the GPS direction.
- Select the segment with the lowest (distance [meters] + angular difference[degrees])

**Comment by HarelM** [comment]
Thanks for the idea!
Two questions:
1. What to do in case of no segments that match the 30 degrees threshold? Do I just take the closest segment i.e. I "stop" following in the same way I do when there's no close enough route?
2. This is somewhat related to the above question - what do you think should be the formula for selecting the best segment? i.e. what should be the weight of the distance and the weight of the angular difference in the above equation?

I suggest the following to solve both cases:
if angle < 30 use the closest
if angle > 30 use your formula as is (weight = 1 to both): min(distance[meter] + angle[degrees])

Closest routes are currently defined as routes with distance that is less than 50 meters, so the first step is aligned with what exists today in the code and I think 50 meters is a good threshold.

**Comment by HarelM** [comment]
I used the following algorithm in the end:
Find a route that has a line segment with minimal (distance + angle) and that (distance + angle) < (50 + 30).
In that route - use the above segment to calculate the current position in the route.
When there's no provided heading related to current position (when standing for example) the algorithm returns to ignoring the angle and using only distance with a threshold of 50 meters (like it was up until now).
I have done some basic sanity tests like taking the following opposite lines and checking with a heading of 0 to see that moving the GPS sideways still locks on the same route:
![image](https://user-images.githubusercontent.com/3269297/115784454-ccd07e00-a3c6-11eb-86b5-d206a58dd564.png)
And the same with a line that goes back and forth:
![image](https://user-images.githubusercontent.com/3269297/115784599-03a69400-a3c7-11eb-9267-2c0a0369313e.png)
But this feature probably requires more testing on more subtle cases...

When standing still and turning the phone to see the direction - there's no effect.
If this is required, it will require more changes to location and orientation services to place the data in the state in order to handle it in a single place. Currently out of scope...
