### ISSUE TITLE
מחיקת מסלולים פרטים

### ISSUE THREAD

**Issue by galdanny** [IsraelHikingMap/Site#1474]
## Feature
כדאי להוסיף אפשרות לבחור מס' מסלולים פרטיים ולמחוק אותם.
הם מיתרבים כשמתחילים לחתוך...
ללכת אחד אחד , ללחוץ על שלוש נקודות וללחוץ על פח האשפה מעייף...
או לפחות לשים X קטן ליד כל מסלול.

## What I did that caused the issue - step by step
Same file opens in IHM ok from WhatsApp for example.

## My environment
* Operating System and version: Android S10
* Web Browser and version:

**Comment by HarelM** [comment]
היי, תודה על פתיחת הפניה.
לשים פח אשפה ליד כל אחד עלול ליצור מצב שאתה לוחץ על פח אשפה בטעות, ואז חייבים לשים דיאלוג של אישור ואז לא חסכת קליקים...
אני לא רואה אפשרות לעשות בחירה מרובה בנייד ולכן בחירה מרובה שוברת את הרעיון של mobile first 
וגם פה ההצדקה לעשות זאת היא מאוד חלשה מכיוון שרוב המשתמשים לא מתעסקים עם הרבה מסלולים כך שלסבך לכולם לטובת מיעוט משתמשים זה לרוב לא רעיון טוב.
אני מצטער אם אני נשמע לא רספטיבי לרעיונות חדשים, אבל אני מאוד עסוק בלהשאיר את הממשק פשוט ולא לסבך אותו.
הדברים שאתה מעלה הם רעיונות מצויינים אבל למשתמשים מתקדמים, מה שלא המצב ברוב המקרים - הרבה מהמשתמשים הם אנשים שטכנולוגיה היא לא פשוטה לה, שאפילו לפתוח פה קריאה נשמע להם משימה מאוד מסובכת והם מעדיפים פשוט לכתוב בקבוצה בפייסבוק מאשר להבין איך לפתוח פה קריאה...

**Comment by galdanny** [comment]
הי,
אני מבין לגמרי. זה בסדר גם ככה. מצאתי גם את פח האשפה בסרגל הכלים הראשי "מחק
את כל המסלולים" שיכול לעזור.
אני הרבה פעמים גורר כמה מסלולים של אותו אזור כדי לראות אותם אחד על השני ,
מתחיל לחתוך והם מתרבים מהר.. :)
תודה, ובכלל, תודה ענקית לכם על הפרויקט IHM המדהים הזה !!
דני

**Comment by HarelM** [comment]
בכיף,
אני סוגר את הקריאה ברשותך...
