### ISSUE TITLE
בחירה ומחיקת מקטע  ממסלול על גבי גרף הגבהים

### ISSUE THREAD

**Issue by galdanny** [IsraelHikingMap/Site#1475]
## Feature
(Delete the non-relevant)

## What I expect to happen
היה נחמד אם על גרף הגבהים היה אפשר לבחור מקטע ולמחוק אותו 
זה עוזר למשל כשהמסלול חולף בהלוך ובחזור באותו מסלול , קשה לבחור בדיוק בהלוך או בחזור

## My environment
* Operating System and version:
* Web Browser and version:

**Comment by HarelM** [comment]
זה מקום מאוד לא אינטואיטיבי לחפש מחיקה של מקטע של מסלול.
כל פעולות העריכה של מסלול נעישות על המפה ע״י לחיצה על המפה או על סמנים שעל המסלול.
אשמח להבין מה הבעיה שאתה רוצה לפתור ואולי אצליח לחשוב על פתרון יותר מוצלח מבחינת חווית משתמש...

**Comment by galdanny** [comment]
כתבתי שיש בעיה למשל כשמסלול הלוך וחזור חופפים על אותו תוואי , איך בוחרים
בנכון?
גרף הגבהים הוא סריאלי ושם קל לבחור כל סגמנט לפי ציר הזמן.
מצרף מסלול כזה .
במצב עריכה בחרתי נקודה.  אין לי שליטה אם זה תפס את ההלוך או את החזור...
[image: image.png]

מצד שני אם אני בוחר בגרף הגבהים מקטע ברור לגמרי אם זה בהלוך או בחזור..
במיוחד אם הייתם מציגים את הסגמנט על המפה (כמו שמראים סגמנט בסטראבה)
[image: image.png]
כאן ברור שבחרתי בהלוך..

וזה החזור:
[image: image.png]

מחיקה תיצור שני מסלולים נפרדים כמו אחרי פעולת חיתוך עם המספרים.

אם אני לא מצליח להסביר את עצמי טוב, אשמח לדבר אתך להתחבר מרחוק ולהדגים לך
למה הכוונה.
תודה,
דני

**Comment by HarelM** [comment]
תוכל לצרף את התמונות שלא דרך המייל אלא דרך האתר? הם לא עוברות בצורה הזו לצערי...
כל נושא העריכה של מסלול שחוזר על עצמו הוא מסורבל, לא מצאתי לזה פתרון טוב שלא מסרבל את העריכה הבסיסית שהיא מבחינתי יותר חשובה.
גרף הגבהים הוא לא מקום הגיוני לחפש בו כלי עריכת מסלול מה גם שלא הגיוני להכניס אליו את כל היכולות.
הדרך הכי טובה שמצאתי לעבוד עם מסלול שחוזר על עצמו היא לחלק אותו לשתיים ולעבוד על כל חלק בנפרד ובסוף לאחד אותם חזרה...
אם יש לך רעיון אחר לעבודה עם מסלול שחוזר על עצמו, שלא דרך גרף הגבהים, שלא דורש לחצן ימני ושלא מסרבל את היכולת ליצור נק' באמצע קטע קיים או לגרור את המסלול שיעבור דרך התוואי המבוקש אשמח לשמוע.
אני לא הצלחתי למצוא, לצערי... :-(

**Comment by galdanny** [comment]
איך מעלים תמונות דרך האתר ? מהאתר אני מופנה ל GIT . אולי התכוונת לפייסבוק ?
לגבי גרף הגבהים - לא צריך את כל היכולות , רק צביעה של המקטע הנבחר על המפה
ואפשרות מחיקת המקטע.. (אולי בעצם לאפשר CUT ו PASTE למסלול חדש...) - קצת
מזכיר עריכה של קבצי שמע WAV אם אתה מכיר.
מסלול שחוזר על עצמו יכול להיות גם כמה סיבובים של אותו הדבר , לדעתי רק גרף
הגבהים יכול לאפשר בחירה של סיבוב מסויים אחד.
אם חייבים לעבוד עם העכבר במפה - אולי לחיצה על CTL או TAB וקליקים חוזרים
באותו מקום יבחרו בצורה ציקלית כל פעם מעבר אחר, אבל זה כמובן לא מתאים
לאפליקציה.

**Comment by HarelM** [comment]
<div dir="rtl">
בתחתית המייל, יש הפניה לאתר של github דרכו ניתן להעלות תמונות ע"י גרירה של תמונה לתוך התיבה של הטקסט או פתיחה של תמונה מהמחשב.
ניתן לעשות זאת בעיקר מהמחשב השולחני, פחות מהנייד.

לגבי גרף הגבהים, אז כל מה שאתה מתאר אלו רעיונות נהדרים אבל אלו יכולות שאף אחד לא ידע למצוא לצערי.
הרעיון של mobile first שהאתר מנסה לשמור עליו מתאר עבודה עם אתר שבראש ובראשונה הוא מתאים לעבודה מהנייד מה שנכון לרוב המשתמשים (75%).
לחיצות על מקשים נוספים במקלדת לא רלוונטי לעבודה מהנייד, כמו גם כפתור ימני ולכן הם בשימוש מועט עד לא קיים באתר.

זה נשמע כאילו אני מנסה למצוא תירוצים למה לא לפתח את זה, אבל בפועל זה מה שמבדיל את האתר הזה מאתרים אחרים - הפשטות שבתפעול.
נושא המסלול שחוזר על עצמו הוא בעיה קשה לפרון מבחינתי בחווית משתמש שמדברת על אפשרות לכפתורים על המסך בלבד.
בלי כוונה לפגוע או להוריד מהמוטיבציה שלך לפתוח קריאות ייתכן מאוד שאתה צריך כלי יותר חזק על מנת לערוך מסלולים ממה שהאתר נותן, וזה לגיטימי, אבל צריך לקחת את זה בחשבון...

היום יש אפשרות לבחור קטע ממסלול ע"י גרירה של קטע, גרירה זו פותחת תפריט אפשרויות. אם אתה חושב שאפשר להוסיף לשם כפתור וזה יכול להועיל להרבה משתמשים אפשר לשקול את זה:
![image](https://user-images.githubusercontent.com/3269297/114298457-2c718400-9abf-11eb-817d-fd5e491afdaf.png)
בינינו, אני בספק אם הוספת כפתור אחד שם יעזור לך, אבל זה מה שאני מוכן להקצות :-)
