### ISSUE TITLE
Add Ctrl+Y for redo

### ISSUE THREAD

**Issue by galdanny** [IsraelHikingMap/Site#1476]
## Feature
(Delete the non-relevant)

## What I expect to happen
תוך כדי עריכה נורא חסר לי קיצור המקשים CTL-Z ל UNDO
הריצה כל פעם לחץ המתאים בתפריט מעייפת...

בכלל חסר  REDO , CTL-Y 

תודה !

## My environment
* Operating System and version:
* Web Browser and version:

**Comment by HarelM** [comment]
תודה רבה על פניה.
קיצור המקשים ctrl+z
קיים ועובד באתר.
אפשר להוסיף ctrl+y
אבל זה כנראה לא יהיה בשימוש רחב מאחר ואין באמת דרך לדעת שזה קיים.
מאחר ולהוסיף את זה זה לא הרבה עבודה אין לי התנגדות, אבל ביטול פעולה כבר קיים עכשיו...

**Comment by galdanny** [comment]
הי הראל,
תודה על התשובות.
ניסיתי אבל אצלי    ctrl+Z לא עובד באתר  (משתמש בדפדפן כרום)
מה עושים ?
האמת, תכלס לא צריכים את ה ctrl .. אפשר רק לחיצה על Z ו Y
יש לכם HELP ששם יש את קיצורי המקשים אם יש עוד ?
אגב, עוד קיצור מקשים יעיל יכול להיות  TOGGLE בין מצב עריכה ללא עריכה ,
במקום לרוץ עם העכבר לאייקון של העיפרון...
הייתי בוחר לחיצה על E  כמו Edit , או F2 (כמו rename)
תודה !!
דני

**Comment by HarelM** [comment]
<div dir="rtl">
היום לחיצה על esc אמורה להוציא ממצב עריכה.
כל help שאי פעם ראיתי היה לא רלוונטי, לא מעודכן, או לא יעיל ולכן אני לא רואה כל סיבה ליצור אחד כזה.
היה אחד בעבר והוא מאוד מהר לא היה מעודכן למצב האפליקציה, אפילו האתר של שאלות נפוצות שאנחנו מפנים אליו לא מתאים ב100% לממשק המשתמש הנוכחי כך שזו מלחמה שאי אפשר לנצח בה.
הפתרון הוא ממשק משתמש שלא דורש מסמך עזרה ואת זה אני מנסה ליישם...

בדקתי עכשיו וראיתי שctrl+z
לא עובד כשאתה בעברית אבל עובד כשאתה באנגלית, תוכל לבדוק שזו הבעיה אצלך?
אם כן אני אפתח קריאה נפרדת לפתור את הבאג...

**Comment by zstadler** [comment]
<div dir="rtl">

> אפשר להוסיף ctrl+y
> אבל זה כנראה לא יהיה בשימוש רחב מאחר ואין באמת דרך לדעת שזה קיים.

לדעתי אין מקום ליצור קיצור דרך לפעולה שלא זמינה דרך הממשק.
כיום אין להבנתי כפתור או אפשרות אחרת לחזור על הפעולה האחרונה שבוצעה אא לבטל פעולת ביטול.
