### ISSUE TITLE
Invalid state when updating a POI twice

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1477]
## What I expect to happen
I should be able to update a POI twice and that both additions should be updated in OSM

## What really happened
Only the last update is done and the upload queue gets fuller

## What I did that caused the issue - step by step
1. Update POI with no reception
2. Update the same POI with no reception
3. Go to a place where there's reception and wait for the POIs to upload
--> error

## My environment
* Operating System and version: Any
* Web Browser and version: Any

## Things I think the developers should know, images, links etc.
When storing the POIs in the queue and in the database the item in the database gets updated and not added again.
I need to find a way to make sure this doesn't happen as the following is a super valid use case.

**Comment by HarelM** [comment]
Need to identify timeout error from other errors:
```js
} catch (ex) {
      if (ex.name === "TimeoutError") {
        console.log("timeout");
      } else if (ex.name === "HttpErrorResponse") {
        console.log("server error", ex.message);
      }
}
```

**Comment by zstadler** [comment]
Also need to figure out the desired user interaction in case a timeout is later followed by a "real" error.

**Comment by HarelM** [comment]
UX of failure to upload a POI will be handled as part of #1478.
Keeping this issue only for queue issues.
