### ISSUE TITLE
Enable HTTPS and embedding in other HTTPS sites

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#148]
Currently, shared IHM maps cannot be embedded as iframes in https-based sites because of mixed contents error.

Chrome, for example, says:
index):79 Mixed Content: The page at 'https://nakeb.pythonanywhere.com/' was loaded over HTTPS, but requested an insecure resource 'http://israelhiking.osm.org.il/'. This request has been blocked; the content must be served over HTTPS.

We can get an HTTPS certificate for free from the [Let's Encrypt](https://letsencrypt.org/getting-started/). Let’s Encrypt is a free, automated, and open certificate authority (CA), run for the public’s benefit. Let’s Encrypt is a service provided by the Internet Security Research Group (ISRG).

**Comment by zstadler** [comment]
Made some progress:
* Installed Let's encrypt for ISS from https://github.com/Lone-Coder/letsencrypt-win-simple/wiki
* Received a certificate using   
```letsencrypt.exe --accepttos --manualhost IsraelHiking.osm.org.il  --webroot C:\IsraelHiking\IsraelHiking.osm.org.il```
* I have set HTTPS binding (port 443) manually

Open issues: 
* Connection to https://IsraeHiking.osm.org.il fails.
* When allowing a certificate exception white connecting to https://localhost on the server machine, the map is not shown and it looks like some JS scripts were not run such as setting the default layers.

**Comment by HarelM** [comment]
You'll need to contact the server admin in order to open port 443 to be able to use https://israelhiking.osm.org.il.
The issue you see on the server according to the browser console is due to the javascript unable to get the google tiles. since this is a 3rd party code I'm guessing we won't be able to fix this...
We might be able to remove the google layer when the site is on https but I'm not sure how easy it will be.
Did anyone contact you about it or this is just a thought you had?

**Comment by zstadler** [comment]
I didn't understand how Google tiles are related to not seeing the IH and MTB tiles

**Comment by HarelM** [comment]
The code fails to load the google tiles on startup and everything fails afterwards, maybe a "try-catch" can help with that...

**Comment by HarelM** [comment]
@zstadler https://localhost now works on the server. The next step is on you :-)

**Comment by zstadler** [comment]
Port 443 was also opened at the site

**Comment by HarelM** [comment]
@zstadler Can you please update the server setup instruction (readme.md) with the above instructions so that if we ever switch a server we won't forget how to do it?

**Comment by zstadler** [comment]
I didn't do it myself.
As far as I could see, the server firewall was ready and the change was at the network level.
