### ISSUE TITLE
קווים ישרים הניווט נכשל

### ISSUE THREAD

**Issue by onzd** [IsraelHikingMap/Site#1484]
קרה לי ב9:20
ניסיתי לתכנן מסלול ברכב מעין דישון לחניון הגיאולוגי דרך נוף נפתלי

שימוש בדפדפן כרום דרך המובייל lg v20

**Comment by HarelM** [comment]
Duplicate of #1480
Thanks for the update!
We are working to understand the root cause of this issue...
Please use the link to the issue above to report more appearances of this phenomenon so we can further debug this.
