### ISSUE TITLE
Adding a gate inside a polygon fails to find the closest highway

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1485]
## What I expect to happen
When adding a gate it should find the closest highway

## What really happened
The gate was added on a polygon who contains the point but is not the closest highway

## What I did that caused the issue - step by step
1. Add a gate inside highway that is a polygon (can be caused by bad mapping)

## My environment
* Operating System and version: Any
* Web Browser and version: Any

## Things I think the developers should know, images, links etc.
![image](https://user-images.githubusercontent.com/3269297/115453357-36665600-a228-11eb-96cd-46671171ac7a.png)
in the following change set a barrier was added to the wrong highway - later the highway tags were removed to correct bad mapping.
https://www.openstreetmap.org/changeset/103052683

This issue is related to this question where distance returns 0:
https://github.com/NetTopologySuite/NetTopologySuite/issues/517

**Comment by zstadler** [comment]
In this example, the `highway` tag of the polygon is a mapping error, as it does not exist in the real world. However, a barrier can be put on a closed (circular) road.

**Comment by HarelM** [comment]
True, this is a great catch by you, thanks!! :-) I had no idea the Distance function could behave like that, and I would probably never have found this bug without your help!
