### ISSUE TITLE
Adding option to remove points markers

### ISSUE THREAD

**Issue by MatanBenMoshe** [IsraelHikingMap/Site#149]
When the route is signed not over existence route I have to create a lot of close points.
Due to the point markers it's hard to see the route itself and it's not so nice design.

See for example this route:
http://israelhiking.osm.org.il/#/?s=wiEqsytQ0A

It would be nice if will be an option to see only the route itself without the points markers

**Comment by HarelM** [comment]
Well, we'll need to think on how to allow it, but there is a workaround you can use only to see the route: create a route with dense points, create a second route, switch to editing this route and the points on the first one will disappear.
Also you can zoom in to better edit the route and you can simplify the route to be a bit less accurate but better seen.

**Comment by zstadler** [comment]
Alternatively, the icons used for creating a route chan be different than POI icons, and smaller. 
Perhaps the small blue circles, currently used when adding a point to the route.

**Comment by HarelM** [comment]
See issue #81 discussion.

**Comment by MatanBenMoshe** [comment]
For me the work around you suggested is good enough. Thanks!
I'm pretty new in web developing but it seems to me pretty simple to add javascript code for adding button to remove specific icon.

**Comment by HarelM** [comment]
You are right, adding the button is the easy part :-). there are other stuff that needs to be taken into account - for example multiple platforms such as mobile/tablet/desktop, how to keep the user interface clear and simple while the application gets complex, etc... those are the difficult stuff that many developers forget when implementing a site or an app...

**Comment by HarelM** [comment]
Same decision as previous issue.
