### ISSUE TITLE
No height data when adding a site's trail

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1490]
הגיע במייל:

לאחרונה נתקלתי בבעיה שנתוני הגובה לא מופיעים ואין אפשרות לראות גרף גבהים (בדקתי על שבילי האופניים)

התהליך הוא כזה - אני משתמש באפליקציה ולפעמים גם דרך המחשב. אני נכנס לסינגל במפה (סימון של אופניים) ומבקש לעלות את הסינגל למפה (כאשר נפתח עמוד הסינגל לוחץ על פלוס) כך שהוא מסומן במפה  מופיעים למטה נתוני  האורך שלו (קמ) ,ועד לפני שבוע בערך הופיעו גם נתוני הגובה של המסלול (כאשר לחצתי על גרף הגבהים הופיע גרף גובה ועכשיו מופיע קו ישר בגובה אפס).

**Comment by zstadler** [comment]
The above behavior was verified by me.
The height graph shows as usual when planning the trail from scratch.

**Comment by HarelM** [comment]
We both opened the same issue :-)
Closing this one as duplicate of #1491
