### ISSUE TITLE
Incorrect route direction for "Hertzel single"

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1495]
<div dir="rtl">
ההגדרה של קקל היא נגד כיוון השעון. 
אם מישהו יעשה לפי המפה ויתנגש עוד יבואו בטענות

![Capture](https://user-images.githubusercontent.com/49042192/117245683-e7353d80-ae43-11eb-906f-f1308180a4bd.GIF)

**Comment by HarelM** [comment]
<div dir="rtl">
זו בעיית מיפוי לדעתי.
יש לעבור על כל הקטעים שיש עליהם סימון של oneway=yes ולוודא שהם בכיוון הנכון, אני מניח שיש אחד שהוא לא בכיוון הנכון ולכן האתר מחבר את כל הקטעים בכיוון הלא נכון.

להבנתי, ניתן לעבור על היחס פה:
https://www.openstreetmap.org/relation/2093275
ושם יש סימון במפה הבסיסית של OSM לכיווניות של קטע, אולי שם יהיה ניתן לראות זאת בקלות.

@valleyofdawn

**Comment by HarelM** [comment]
אני לא מצליח להבין בדיוק מה היה השינוי, אבל לדעתי הבעיה נוצרה מהשינויי הזה:
https://www.openstreetmap.org/changeset/102878588

**Comment by HarelM** [comment]
My mistake, ignore my last comments about bad mapping, this is not the case in this issue.
This bug was introduced about 5 month ago as part of #1296.
Thanks for the report @Tsurha!

**Comment by HarelM** [comment]
Resolved by a8bd644

**Comment by zstadler** [comment]
<div dir="rtl">
לחלק מהקטעים אין כיוון oneway, ולחלק גם לא יכול להיות כיוון כזה כי אלו דרכי עפר שמשמשות גם כלי רכב.

שני סניגלים שונים יכולים לעבור באותו קטע אבל בכיוונים הפוכים. זה, להבנתי, המצב [בקטע המשותף לסינגל הרצל וסינגל הרצל](https://www.openstreetmap.org/way/857803845).

עד כמה שאני מבין, המיפוי היחיד שיכול לייצג את המקרים האלו הוא סידור של הקטעים בתוך היחס כך שהוא יהיה תואם את סדר וכיוון הנסיעה בכל סינגל. מצד שני, לא כל משתמש OSM ידע איך לבצע את המיפוי בצורה הזו.

ערכתי ב JOSM את היחס כך ש:
1. סדר הקטעים ביחס תואם את סדר וכיוון הנסיעה בסינגל
2. הכיוון של הקטעים תואם את כיוון בסינגל הרצל. מטבע הדברים, יש סתירה מובנית עם כיוון הרכיבה בסינגל ענבה

![image](https://user-images.githubusercontent.com/1304610/117266240-b6fa9880-ae5d-11eb-9156-315c9124e898.png)

**Comment by HarelM** [comment]
מספיק שיש קטע אחד חד כיווני כחלק מהיחס והסינגל יסודר לכיוון הנכון.
אם יש קטע ששייך לשני סינגלים עם כיוונים מנוגדים אז אסור שהוא יתוייג כחד כיווני, כיוון שזה מיפוי לא נכון.
אין צורך בעריכה מתקדמת בהקשר הזה.

**Comment by Tsurha** [comment]
<div dir="rtl">
חברים עשיתם כאן ריזולבד אבל כשאני גולש למפת הטיולים והופך את הרצל למסלול, הוא עדיין עם כיוון השעון.
אם זה עניין של לחכות עד שהנתונים יתעדכנו אז סבבה, אבדוק מחר.
בכל מקרה מדובר על סינגלים שמופיעים במסלולים של מפת הטיולים. תהיתי אין כאן משהו שמחוץ לאוסאם והוא רק אצלכם.
אני רואה שאותה בעיה עדיין קיימת גם בסינגל חדיד.  
, רק בשביל שיהיה לכם מסודר או רשמי, ההגדרות של קקל שכיוון הרכיבה הנכון בשני הסינגלים האלה הוא נגד כיוון השעון מופיעות באתר שלהם כאן:

חדיד:
https://www.eyarok.org.il/bike/trip.aspx?id=1961

הרצל:
https://www.eyarok.org.il/bike/trip.aspx?id=1964

![חדיד והרצל צריכים להיות נגד כיוון השעון](https://user-images.githubusercontent.com/49042192/117280648-7ace3480-ae6b-11eb-9212-fdd16fe4f2b0.PNG)

**Comment by HarelM** [comment]
עשיתי תיקון בקוד, קישרתי אותו לפה והעברתי את הקריאה ל
waiting for release.
אם אתה רוצה לבקר תוודא שאתה קורא את כל המידע לפני...
