### ISSUE TITLE
Avoid endless "Ending HttpMessageHandler cleanup cycle" messages

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1506]
## What I expect to happen
Avoid useless messages from showing in the Docker logs of the website.

## What really happened
When the website is idle, the Docker log is repeatedly filled with messages like
```
website_1               | dbug: Microsoft.Extensions.Http.DefaultHttpClientFactory[101]
website_1               |       Ending HttpMessageHandler cleanup cycle after 0.0029ms - processed: 0 items - remaining: 1 items
```

## What I did that caused the issue - step by step
- Run the website in a docker container
- Open the website in a browser
- Avoid further activities in the browser
- Watch the docker logs using `docker-compose logs website --tail=5 -f`. Use Ctrl-C to abort.

## Things I think the developers should know, images, links etc.
The [analysis of the this behavior](https://github.com/aspnet/HttpClientFactory/issues/165#issuecomment-418232922) indicates that the behavior is correct and the messages reflect the reality.

The [proposed solution there](https://github.com/aspnet/HttpClientFactory/issues/165#issuecomment-418469563), and [here](https://stackoverflow.com/a/63228575) is to reduce the log level of the `DefaultHttpClientFactory` component in the `appsettings.json` file:

```
  "logging": {
     "LogLevel": {
       "Microsoft.Extensions.Http.DefaultHttpClientFactory": "Information"
     }
  }
```

**Comment by tmp1k** [comment]
does that remaining count ever change or does it stay at 1? i'm having this issue where the remaining count keeps increasing. using `httpClientFactory.CreateClient("myApiClient")` registered at startup using something like
```
services.AddHttpClient("myApiClient", o =>
            {
                var baseUrl = Configuration["ApiConfig:BaseUrl"];
                o.BaseAddress = new Uri(baseUrl);
                o.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", Configuration["ApiConfig:AccessToken"]);
            })
```

**Comment by HarelM** [comment]
As far as I remember it didn't go up but remain on 1, but this was a long time ago...
