### ISSUE TITLE
Difference between contour lines and DEM interpolation

### ISSUE THREAD

**Issue by galdanny** [IsraelHikingMap/Site#1512]
## What I expect to happen
ראו מצ"ב GPX
גרף הגבהים רועש ועצבני - 304מ' מצטבר בטיפוס ל 80 מ'. - לא נראה הגיוני.. אולי משהו במפה ?
[YardenHarari.zip](https://github.com/IsraelHikingMap/Site/files/6511227/YardenHarari.zip)

## What really happened
-

## What I did that caused the issue - step by step
-

## My environment
* Operating System and version: Win
* Web Browser and version:
Chrome
## Things I think the developers should know, images, links etc.
-

**Comment by zstadler** [comment]
Looking at this section of the route
https://israelhiking.osm.org.il/share/WjF9KrE2aX there seems to be a  difference between the map's contour lines and the statistics

![Screenshot_20210519-234753.jpg](https://user-images.githubusercontent.com/1304610/118882247-a71e9200-b8fc-11eb-8215-732af1d161d1.jpg)

**Comment by zstadler** [comment]
The same section in [graphhopper.com](https://graphhopper.com/maps/?point=32.981865%2C35.624573&point=32.981216%2C35.623136&locale=en&elevation=true&profile=car&use_miles=false&selected_detail=Elevation&layer=TF%20Cycle): 14 meters incline, 2 meters decline.

![image](https://user-images.githubusercontent.com/1304610/119008564-f4e9d780-b99a-11eb-87c2-4f0f0d88d8f7.png)

Notice that the height graph does not correspond to the contour lines of the OpenCycleMap base map.

**Comment by zstadler** [comment]
To be on the safe side, I compared the heights in the height graph with the heights of several nodes long this section.
The title of each point is its height, as shown using "show coordinates".
As expected, they match, meaning that the use the same DEM source.

![image](https://user-images.githubusercontent.com/1304610/119009740-1d260600-b99c-11eb-8fe4-dd7df10f0334.png)

**Comment by HarelM** [comment]
I have deployed the elevation service with the more accurate DEM and this issue no longer exists.
The difference in the elevation along the route is about 3 meters and the contour difference is +-3 meters.
Bottom line, this was solved by #1642
