### ISSUE TITLE
אין סימוני שבילים

### ISSUE THREAD

**Issue by onzd** [IsraelHikingMap/Site#1528]
בדפדפן כרום גם במחשב וגם בנייד

**Comment by onzd** [comment]
המפות הישנות עובדות בסדר גמור

**Comment by HarelM** [comment]
אתה תיהיה חייב לפרט הרבה יותר כדי שנבין על מה אתה מדבר... :-)

**Comment by onzd** [comment]
‫בתאריך יום ב׳, 7 ביוני 2021 ב-11:35 מאת ‪ofer kapon‬‏ ***@***.***
‬‏>:‬

**Comment by onzd** [comment]
הסתדר פתאום 
מבחינתי חזל"ש 
וסליחה רק שלא הבנתי למה זה קרה 
ובדקתי גם במצב איקוגיניטו וגם במצב רשום
גם בנייד וגם בדפדפן
