### ISSUE TITLE
תפריטים גדולים יותר

### ISSUE THREAD

**Issue by baobabprince** [IsraelHikingMap/Site#1531]
## Feature
תפריטים גדולים יותר
## What I expect to happen
בשימוש באפליקציה, כשאני לוחץ על שם המשתמש או תפריט ההמבורגר אני מקבל תפריט די קטן אבל כזה שמכסה את המפה בצורה שלא באמת מאפשרת להשתמש בה.
אני חושב שיהיה הרבה יותר נוח לקבל תפריט גדול בו יותר קל ללחוץ על הדברים
גם בתפריט של השכבות הסמל של העין ממש קטן מדי וקשה ללחוץ עליו תוך כדי תנועה.
אולי גם בתפריט של עריכת המסלול כדאי שיהיו סמלים גדולים יותר, אבל בזה אני לא משוכנע, כיזה מסתיר את המפה בצורה שעלולה להפריע.
## My environment
google pixel.
## Things I think the developers should know, images, links etc.
תודה רבה, אחלה אפליקציה שבעולם.

**Comment by HarelM** [comment]
גודל התפריטים, הפונטים, הכפתורים, ועוד הרבה אלמטים נקבע ע"י סטנדרטים של גוגל:
Material design
הוא שם הסטנדרט.
אני לא מעצב והגדלה של התפריט אינה פעולה פשוטה שכן צריך לקחת בחשבון את שאר האלמנטים.
היו בעבר קריאות בנושא ואף אחד לא התנדב לעשות עבודה רצינית בעניין:
#366, #444, #1363
אשמח לתנדבות של מעצב לצורך כך, אבל אני כבר לא אופטימי...
אם אתה רוצה לקחת את הקריאה עליך אני אשמח, אם לא אני אסגור אותה כי אין לי דרך לפתור אותה כרגע...

**Comment by zstadler** [comment]
בהגדרות של אנדרואיד, לפחות במכשיר שלי, ניתן לשלוט במידת מה על גודל הכפתורים דרך הגדרות התצוגה.

כך נראה המסך עם הגדרת הכפתורים. קטנה ביותר

![Screenshot_20210608-174330.jpg](https://user-images.githubusercontent.com/1304610/121206875-7b4e5680-c881-11eb-86fb-ec88a2fbe20c.jpg)

וכך הוא נראה עם הכפתורים הגדולים ביותר.

![Screenshot_20210608-174302.jpg](https://user-images.githubusercontent.com/1304610/121207050-a46ee700-c881-11eb-88ac-154b3dd2e122.jpg)

אתה מוזמן לבדוק אם המכשירשלך תומך בזה ואיך אתה מעדיף את גודל הכפתורים.

**Comment by valleyofdawn** [comment]
@zstadler 
תחת איזה תפריט הגדרות גודל המקשים?
זה ספציפי לאפליקציה או גלובלי?

**Comment by zstadler** [comment]
It's a global settings for the device:  Settings -> Display -> Display Size
