### ISSUE TITLE
שוב נעלמו סימוני שבילים בשעה13:00

### ISSUE THREAD

**Issue by onzd** [IsraelHikingMap/Site#1533]
## Bug/Feature
(Delete the non-relevant)

## What really happened
לא מופיעים

## What I did that caused the issue - step by step
רק פתחתי את המפה העלתי משהו מהענן ואז שמתי לב שאין סימוני שבילים

## My environment
* Operating System and version:
* Web Browser and version:

**Comment by onzd** [comment]
![Untitled](https://user-images.githubusercontent.com/43242549/121803218-27f55300-cc49-11eb-816f-5332837c9324.jpg)

**Comment by HarelM** [comment]
כרגע עשינו הפעלה מחדש לשרת האריחים, לא ברור למה הוא הפסיק לעבוד.
במידה והעניין יחזור על עצמו אפתח את הקריאה מחדש ונראה איך פותרים שורש העניין.
כרגע אני בוגר את הקריאה, המידה ואתה נתקל בבעיה שוב אנא דווח פה.
