### ISSUE TITLE
Captions: use "הצג שיפועים"+"Show slopes" instead of "גרף שיפועים".

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1539]
## Feature
(Delete the non-relevant)

## What I expect to happen
1. A wider spread of graph. Higher and lower. 
2. Translate גרף שיפועים - should be Profile (its a term)

## What really happened
Currently when the % difference is up to 5%, can't see how much.
![image](https://user-images.githubusercontent.com/49042192/122715593-c4cf7600-d271-11eb-9378-334a33b202a9.png)

**Comment by HarelM** [comment]
This is by design.
The idea is that slopes that are moderate will not look as if they are "hard" - and will correlate to the color on the map - i.e. when you see green you should not see a slope chart that is extending all the way up/down, but when you see red or blue you will.
See the discussion here: #1337.

**Comment by Tsurha** [comment]
Understood.
So its just the גרף שיפועים - that translates to Profile (its a term)

**Comment by HarelM** [comment]
Not sure what you mean by "profile", but if my answer satisfies you please close this issue :-)

**Comment by Tsurha** [comment]
<div dir="rtl">
פרופיל של מסלול זה מה שקראתם לו בעברית גרף שיפועים
הקו השחור בגרף
הדוגמא להלן היא הפרופיל של סטייג' מסויים בטור דה פראנס 2014
צריך יהיה לסגור את האישיו אחרי שבאנגלית במקום גרף שיפועים יהיה כתוב
Profile

![image](https://user-images.githubusercontent.com/49042192/122739158-62836f00-d28b-11eb-8959-98c7ca33a0d2.png)

**Comment by zstadler** [comment]
<div dir="rtl">

לפי מה שאני רואה גרף הפרופיל שלמעלה מציג את הגובה בהתאם למרחק ולא את השיפוע בהתאם למרחק

**Comment by Tsurha** [comment]
<div dir="rtl">
צודק זאב. 
אכן הפרופיל זה הקו הכחול. 
בעצם גם גרף שיפועים בעברית לא מתאר את כל הפונקציונליות שם כי יש גם את הצבעים על המסלול עצמו וזה לא גרף
מציע להחליף את הכיתוב שיהיה:
שיפועים בעברית.  
Slopes באנגלית.

**Comment by zstadler** [comment]
"Show slope"

**Comment by Tsurha** [comment]
בוא נהייה קונסטסטנטיים עם יחיד רבים. 

הצג שיפועים  Show slopes

**Comment by zstadler** [comment]
בנושא הזה אין אחידות בין אנגלית ועברית

**Comment by Tsurha** [comment]
אנחנו מדברים כאן על השיפועים של מסלול מסויים שיכול לכלול הרבה עליות וירידות.  
לכן עקב הפונקציונליות ולא עקב השפות זה צריך להיות ברבים.

**Comment by zstadler** [comment]
מדובר כאן על הוספה של קו לגרף

**Comment by Tsurha** [comment]
נראה לי חוסר הבנה ביננו. אשמח לשוחח טלפונית  
אני נמצא ב 054-4536874
להבנתי כרגע הדיון הוא רק על שינוי מינוח של מה שמסומן בעיגול. באמת בקטנה  

![image](https://user-images.githubusercontent.com/49042192/122810527-232f3f80-d2d8-11eb-835d-980c9d147696.png)

**Comment by HarelM** [comment]
So the bottom line is the translation and label.
I have no objection to "Show slopes" and "הצג שיפועים" as the button's text.
@zstadler would you like an alternative label?
