### ISSUE TITLE
Shared map should not be editable after loading

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#154]
In order to avoid modification by mistake.
Currently there is always one editable layer. Perhaps there should always be such an empty layer also when loading a shared map

**Comment by HarelM** [comment]
Not sure I understand... can you elaborate?

**Comment by zstadler** [comment]
- Open IHM
- Load a track
- Share the map
- Load the result, such as http://israelhiking.osm.org.il/#/?s=vlF2NfmkHv

The shared track is in edit mode. Any change, such as clicking on the routing modes, adding or deleting a node, immediately changes the saved track.

I propose that the default, empty route will also be added, and become the active route, after a shared map is loaded.

Alternatively, you can add an option to set all routes in visible, yet non-active state.

**Comment by HarelM** [comment]
Sounds like a lot of work, refreshing the page will delete all changes, I'm not sure how useful your suggestion is...

**Comment by zstadler** [comment]
Adding a blank layer after loading the saved map is a lot of work!?

**Comment by HarelM** [comment]
Depends, the logic in layer service is not straight forward. I'll think about it... :-)

**Comment by zstadler** [comment]
It should be the same as a user's click on "new route" after loading the layers from the server is completed.

**Comment by HarelM** [comment]
Hopefully will be done as part of issue #114
