### ISSUE TITLE
Corrupt offline database file when download doesn't finish successfully 

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1542]
## Feature

<p dir="rtl">
ארנון צעירי כתב במייל:

<blockquote><p dir="rtl">
 רכשתי את המפות לשימוש offline ואני חושב שאפשרות העדכון לוקה במקצת. קרה לי שההורדה (לצורך עדכון) נקטעה ונשארתי ללא קבצי offline בכלל. האם הקבצים הקיימים נמחקים ברגע הלחיצה? אם כן, אני חושב שכדאי לשנות כך שיימחקו רק לאחר שההורדה הושלמה בהצלחה.
</blockquote>

## What I expect to happen
Any existing offline maps will be preserved until the download of their update is completed.

## What really happened
If a download of a offline map update is interrupted, the offline map is no longer available.

## What I did that caused the issue - step by step
1. Activate the offline map in the Layers pane
2. Start an update of the offline maps
2. Interrupt the download by killing the app
3. Re-launch the app
4. Reactivate the offline map in the Layers pane
5. Close the Layers pane

The offline map is no longer available.

## My environment
* Operating System and version: Android 11
* Web Browser and version: App version 9.9.76

**Comment by zstadler** [comment]
Thanks for the quick fix! 👍

**Comment by HarelM** [comment]
This didn't work, the last part of moving the file fails for some reason...
I'll give it another go and if this doesn't work I'll drop revert the changes...
