### ISSUE TITLE
Simplify working with several routes 

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1550]
## Feature
Simplify usage when several private routes are presented on the left. Ease the UI and relation between the routes and the edit menu. 

## What I expect to happen
1) Highlight the current selected route
2) When the editing menu on the right is closed, the user cant edit. In this situation, show its route with an 'eye' icon in the routes menu, not with the 'pen' that says edit.
3) When a route is marked with a 'pen', open its editing menu on the right. To unify the behavior of pen=editing
4) When a route on the left side is selected, do not immediately mark is with a pen. Only with an eye.

## What really happened
Confusing behavior and relation between the pen on the right and the routes on the left with their pen

![image](https://user-images.githubusercontent.com/49042192/125803760-c3304929-6cae-4ce3-9f3a-e28b21271854.png)

**Comment by HarelM** [comment]
Please provide more detailed description. I'm unable to understand this based on the text above.
Preferably with more images to better explain which click does what.
A ppt with the relevant UX would be the best.

**Comment by Tsurha** [comment]
See the first design draft for our discussion:
https://docs.google.com/presentation/d/1q-3q-8085ueVfpdIjeZGa_M7j786HEGf5ypS6Yk8A4E/edit?usp=sharing

**Comment by HarelM** [comment]
Thanks a lot for taking the time to prepare this presentation, it's very clear and informative.
I have a few questions related to it.
1. What should be the sequence now to hide a route?
2. What should happen if I edit route 1 and then click on route 2 (which is visible but not selected and not in edit mode)?
3. Edit mode has two modes - route, poi, which mode should be used when clicking on the left pane to edit?
4. When in poi edit mode what should appear in the left pane?
5. Can you think of other scenarios that were not covered in the presentation?

Thanks again! I understand the narrative behind this suggesting.

I hope you don't mind that I won't be using a dark gray background to present the selected route... (I'll probably use bold font). :-)

**Comment by Tsurha** [comment]
Glad you look positively into this improvement. I'm sure it will remove usage barriers for users.  BTW, a course that has recently finished in Wingate for מובילי קבוצות אופניים started with other SW options. The trainees needed an enhancement and it all ended up in endorsing IHM as the course preferred option. I have lectured there in different subjects but contributed to this change.

**Back to our discussion:**

I have now edited and enhance the presentation. This should answer your points 1+2 and maybe more like 5.  
The presentation endorses the usage of bold font. I'm assuming its in line with the existing UI language. I did not change existing pictures there to save time.

Sorry, but I do not understand the POI mode mentioned in 3+4. Never used it cos section headline is "Private Routes". This never suggested to me to add a point.  If you have a tutorial text or video or can just explain about points, I'd be happy to learn and look into it.

**Comment by HarelM** [comment]
https://youtu.be/EZ9jqQgpAXY
The above video, around 2nd minute has a video on adding a private POI (point of interest), while this video talks about how to add a public POI from private POI the concept of private POI (which is part of the route) is presented there.
The idea is that a route has two different edit modes - one to add and extend the "line" and the other to add info such as text and pictures to it.
Hope this make it clearer, if not, key me know...

**Comment by Tsurha** [comment]
Got it. Added a last slide in the presentation with POIs. Have a look

https://docs.google.com/presentation/d/1q-3q-8085ueVfpdIjeZGa_M7j786HEGf5ypS6Yk8A4E/edit?usp=sharing

**Comment by HarelM** [comment]
Thanks for the updated presentation! but it's still not clear what sequence of clicks is needed in order to move a route from edit to viable to hidden. I.e. When a route is visible and I click on it should it go top edit mode or hidden mode?

**Comment by Tsurha** [comment]
Right. It was not defined well. Please see a newly added slide 3 and let me know if it closes whatever was left in the dark.

**Comment by HarelM** [comment]
אני עדין לא מצליח להבין מהמצגת איך להסתיר מסלול...?

**Comment by Tsurha** [comment]
כי זה לא היה מוגדר טוב. 
נסה עכשיו את שקף 3.
הדגשתי באדום את התהליך החדש.

**Comment by Tsurha** [comment]
כמוכן תוספת לקונסיסטנטיות ועוד שיטה להסתרה: עין לסגירת כל המסלולים יחד
ראה שקף 8

**Comment by HarelM** [comment]
Option 1 - green frame like other buttons have in the UI:
![image](https://user-images.githubusercontent.com/3269297/129057911-7b7a62c3-c457-4a8e-8cf9-5b6584221a6e.png)
Option 2 - Bold - feels too subtle to me, I think option 1 is better, only if there is more than one route...
![image](https://user-images.githubusercontent.com/3269297/129059872-406caf8b-18f2-46d7-9460-46c2b90cae44.png)

**Comment by HarelM** [comment]
I've played around with the UX a bit, I don't want to allow moving to edit mode in another place besides the right drawing menu.
So I'll be publishing a version to the site shortly so you would be able to play with it.
The main change in the UX is the differentiation between selected (green frame) and in edit mode (pencil icon) which I think makes it more intuitive in the new version.

**Comment by Tsurha** [comment]
While Option 2 is indeed too subtle, Im afraid option 1 is too much.  I do not know of such selection elsewhere in the SW.  I know about a checkbox that simboizes a selection like here: 
![image](https://user-images.githubusercontent.com/49042192/129074084-002faad7-2b3b-4ede-b106-76fa8e5a1f7a.png)

Change to edit in the right drawing menu should indeed be kept. I'll play of course but it seems right that it will edit the currently selected route.

**Comment by Tsurha** [comment]
You could also consider a selection like the one now while hovering.  Just that it will stay, in addition to the hover that disappears.

![image](https://user-images.githubusercontent.com/49042192/129074976-819bc44a-29b9-4f06-83d1-bf93afb4a479.png)

**Comment by HarelM** [comment]
This indication is used for hover, not selected so it can't be used.
Most buttons in the ui has a border when active, so this is not entirely "new" feel...

**Comment by HarelM** [comment]
Neo is the one, no argue here :-)
I've published the changes to the site temporarily, I'm not sure how long I'll keep this version available (Might be reverted within a day or two) so see if you can find the time to test and see if it makes sense to you...
Thanks for the effort of creating the presentation etc!

**Comment by Tsurha** [comment]
My reply was only after I saw it live. Good job!
No problem if the solution only appears permanently later. Just out of interest why not keep it?

**Comment by HarelM** [comment]
To keep better track of what was released when, and since this is currently not available in mobile  I would like to avoid the questions of "why is it in the site and not the app?"...
Releasing to mobile is more complex and time consuming than updating only the site...

**Comment by Tsurha** [comment]
🙏

------ Original Message ------
From: "Harel M" ***@***.***>
To: "IsraelHikingMap/Site" ***@***.***>
Cc: "VELOCITY Cycling Club" ***@***.***>; "Author" 
***@***.***>
Sent: 13/08/2021 06:30:26
Subject: Re: [IsraelHikingMap/Site] Simplify working with several routes 
(#1550)
