### ISSUE TITLE
Add elevation to route splitting point

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1557]
## Bug/Feature
Based on the reproduction scenario provided by @ErezNahoum in [#1554](https://github.com/IsraelHikingMap/Site/issues/1554#issuecomment-884021348)

## What I expect to happen
When a route is split, the new end points should have an elevation.

## What really happened
Neither parts have elevation for the split point.

## What I did that caused the issue - step by step
1. Plan a short route anywhere. No need for intermediate points, just start and stop.
2. Split the route.
3. Export the first half as GPX and see that its last `trkpt` does not have an `ele` value
4. Export the second half as GPX and see that its first `trkpt` does not have an `ele` value.

**Comment by HarelM** [comment]
I think I added it recently as I thought this could've caused this issue.
This needs to be tested on latest version. I think this can be tested on latest mobile.
@zstadler any chance you can test this scenario?

**Comment by zstadler** [comment]
It looks OK in the internal testing version of the app.

**Comment by HarelM** [comment]
Cool! I'll reference the relevant commit and close with your permission.

**Comment by zstadler** [comment]
In fact, the problem is introduced when an internal point is added to the route unrelated to splitting the route.

**Comment by HarelM** [comment]
It is unclear if there is now another scenario which causes an issue that is not solved in the internal testing app... please elaborate.

**Comment by HarelM** [comment]
Relevant commit: d605cfa5d7ca66dd69c98a0f08296d06bca581d7 
in file: `spatial.service.ts`

**Comment by zstadler** [comment]
The new and simpler scenario is also OK in the internal testing version of the app.

**Comment by HarelM** [comment]
Resolved by d605cfa
