### ISSUE TITLE
Problem uploading a path to the cloud

### ISSUE THREAD

**Issue by ophirh2** [IsraelHikingMap/Site#1560]
Getting an error as described in the pic.
Attempts to change the name of the path, the name of the upload and so, didn't help.

![image](https://user-images.githubusercontent.com/3269421/127364572-e9f3ffb1-3e21-4a3b-954a-5f3a37658265.png)

**Comment by ophirh2** [comment]
Sorry. Contrary to what I wrote in Telegram, there is a real problem with the attached file.

[
[MigdalorBosmatTivonFinal.zip](https://github.com/IsraelHikingMap/Site/files/6895201/MigdalorBosmatTivonFinal.zip)
](url)

**Comment by ophirh2** [comment]
This is the original file, that was the base for the path creation. It was created by OruxMap while riding my bike.

[2021-07-27 1833__20210727_1833.zip](https://github.com/IsraelHikingMap/Site/files/6895627/2021-07-27.1833__20210727_1833.zip)

**Comment by zstadler** [comment]
## Bug/Feature
(Delete the non-relevant)

## What I expect to happen
I'd like to be able to import a GPX file with HTML in its `<desc>` elements and use it freely in IHM

## What really happened
- Such an imported route cannot be saved to the cloud
   
   ![image](https://user-images.githubusercontent.com/1304610/127441839-41219ecb-def2-4710-9c27-7c1a6fed13f7.png)
- The route properties can get distorted
   
   ![image](https://user-images.githubusercontent.com/1304610/127443586-e869f2ca-2f07-402e-adca-e94fa4b3ce9b.png)

## What I did that caused the issue - step by step
1. Download [2021-07-27.1833__20210727_1833.zip](https://github.com/IsraelHikingMap/Site/files/6895627/2021-07-27.1833__20210727_1833.zip)
2. Extract the GPX in it
3. Read the GPX to IHM
4. Observe the route properties
5. Save to the cloud

## My environment
* Operating System and version: any
* Web Browser and version: any

## Things I think the developers should know, images, links etc.
Strictly speaking, the GPX schema does not allow HTML in the `<desc>` element
- The content of the `<desc>` element for `<wpt>`, `<rte>`, and `<trk>` is defined as `string` in https://www.topografix.com/GPX/1/1/
- The XML definition of a `string` does not allow it to have sub-elements, such as HTML XML - https://www.w3.org/TR/xmlschema-2/#string

On the other hand, if such GPX files are acceptable, it will enable the site and app to read OruxMaps recordings, which I think was possible in the past.

**Comment by HarelM** [comment]
I guess this is related to the change of opening a file in the client side as apposed to opening it (in the past) on the server.
The xml is begin translated to json, and this is what probably causes this issue...
I don't think this is a big issue to fix so I don't mind fixing it.
I do think however it's worth contacting OruxMaps and let them know that they create an invalid GPX file.
There was another issue in the past that the `version` that was written was the version of the OruxMaps app and not `1.1` or `1.0` as the schema dictates. I'm not sure if this was ever solved or not, but OruxMaps usually listen to users concerns...
I'm not sure if this was ever fixed or not, but Oruxmaps usually

**Comment by HarelM** [comment]
The above scenario that is described does not cause the original bug.
As far as I understand the following is the full scenario that causes the bug:
1. Import a GPX file from oruxmaps (...1833.gpx) in our case
2. Look at the properties - they look fine, with a lot of xml tags but still valid.
3. Export the route to file
4. Look at the file - the file is created incorrectly with xml tags inside the description instead of the "CDATA" that was there before
5. If you import the exported file you get the [Object Object] issue.

There are two problems here: The export which is creating an invalid GPX file and an import who's having a hard time parsing this file...
