### ISSUE TITLE
Allow Let's encrypt access to acme-challenge

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1563]
## What I expect to happen
Be able to install and renew the SSL certificates from Let's Encrypt

## What really happened
The site verification step in the renewal process fails

## Things I think the developers should know, images, links etc.
This is the renewal log:
```
2021/08/06 01:59:32 [ Crypt::LE client v0.36 started. ]
2021/08/06 01:59:32 Loading an account key from account.key
2021/08/06 01:59:32 Loading a CSR from domain.csr
2021/08/06 01:59:32 Checking certificate for expiration (local file).
2021/08/06 01:59:32 Expiration threshold set at 30 days, the certificate expires in 19 days - will be renewing.
2021/08/06 01:59:33 Registering the account key
2021/08/06 01:59:34 The key is already registered. ID: 124065303
2021/08/06 01:59:34 Current contact details: zeev.steed.stadler@gmail.com
2021/08/06 01:59:35 Successfully saved a challenge file '/acme-challenge/AeHw2zEl5kGTYzxjrCkY6rSh2OqsUuomoWhRq1n1L2I' for domain 'israelhiking.osm.org.il'
2021/08/06 01:59:38 Domain verification results for 'israelhiking.osm.org.il': error. Fetching http://israelhiking.osm.org.il/.well-known/acme-challenge/AeHw2zEl5kGTYzxjrCkY6rSh2OqsUuomoWhRq1n1L2I: Connection refused
2021/08/06 01:59:38 Challenge file '/acme-challenge/AeHw2zEl5kGTYzxjrCkY6rSh2OqsUuomoWhRq1n1L2I' has been deleted.
2021/08/06 01:59:38 All verifications failed
```

I've verified that a file placed in the `.well-known/acme-challenge` directory is visible externally in a browser. However, using `curl` or `wget` with the same address results in a `connection refused` error.

My hypothesis of the root cause is this:
- The Let's Encrypt site attempts to access the challenge file using HTTP.
- The Israel Hiking site redirects the request to the HTTPS equivalent.
- The Let's Encrypt site interprets this redirection as a failure, probably due to security concerns.

Removing the http-to-https redirection for `.well-known` will also enable installing a certificate when there is no valid certificate.

**Comment by HarelM** [comment]
The following is the part that takes care of .well-known folder:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.Web/Startup.cs#L242L252
I guess moving it before the https redirect should solve this issue...?
The redirect part is the first thing that runs on a request:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.Web/Startup.cs#L146
Similar issue with nginx is described here, I'm not sure I'm able to fully read it:
https://superuser.com/questions/1615014/https-connection-refused-after-redirect-on-my-nginx-server
If we'll move to nginx we'll probably have the same/similar issue - so it might worth considering to look for a solution to this problem in nginx as well...
I can try and create a version using the above suggested code change as a temporary solution.

**Comment by HarelM** [comment]
I've pushed an attempt to fix the issue. I don't know if it will work, but I don't have a better idea how to solve this at the moment so this is worth exploring:
Once the appveyor build will finish uploading the docker image the procedure to test this fix will be to change the docker-compose file on the server to use `latest` instead of the current version (I think it's 9.9.99) of the website. If this will work I'll see what other features can get into the version and release a version accordingly.
Relevant build:
https://ci.appveyor.com/project/IsraelHikingHost/site/builds/40325815/job/ttcd40hfdbs6raae

**Comment by HarelM** [comment]
I've removed the redirect, published it to dockerhub, updated the server and tried again with not luck. :-(
It seems that surfing to http://localhost/ on the server is not returning anything while surfing to https://localhost on the server brings up the site, So I think http is not working even internally on the server, probably related to some definitions in the docker-compose and the code related to initialization, I'm not sure though...

**Comment by HarelM** [comment]
When the server loads it seems to say the following:
```
warn: Microsoft.AspNetCore.Server.Kestrel[0]
website_1        |       Overriding address(es) 'http://+:80, https://+:443'. Binding to endpoints defined in UseKestrel() instead.
website_1        | dbug: Microsoft.AspNetCore.Hosting.Diagnostics[4]
website_1        |       Hosting started
website_1        | dbug: Microsoft.AspNetCore.Hosting.Diagnostics[0]
website_1        |       Loaded hosting startup assembly IsraelHiking.Web
website_1        | Hosting environment: Production
website_1        | Content root path: /israelhiking
website_1        | Now listening on: https://[::]:443
```

It's clear that it is only listening to 443 and not 80, I just don't know why... :-(
I'll try to find more about the overriding warning...

**Comment by HarelM** [comment]
Seems like `PreferHostingUrls` suggested here:https://github.com/aspnet/KestrelHttpServer/issues/1851 helped solve this issue. I couldn't get it to reproduce on my local env unfortunately without docker, didn't get to try it with docker though...
@zstadler See if you can run the acme-challenge now...

**Comment by HarelM** [comment]
After deploying this fix iOS devices stopped working properly. It might be related to the following report:
https://blog.todaydata.com/2020/01/22/https-redirection-problem-with-ios-and-net-core-2-1/

**Comment by HarelM** [comment]
Seems like when using the latest version with the `PreferHostingUrls(true)` http1 flag is ignored and instead http2 is used which causes the issue on iOS devices.
I've opened a bug for aspnetcore: https://github.com/dotnet/aspnetcore/issues/35362
I hope someone would pick it up.
I can probably hardcode http1 in the code, but I prefer not to if I have another option...
If we are adding headers using nginx to the tiles server we might be able to remove unwanted headers too and enable back http2 and maybe solve this issue this way, I don't know...

**Comment by HarelM** [comment]
After reading the response in the above issue and to summarize the phone conversation, my approach will be to try and move all the configuration to the appsetting.json file including the protocol, ports and certificate. If this will work we can close this issue now and revisit the http/2 issue as part of the nginx migration attempt.

**Comment by HarelM** [comment]
I'm not entirely sure the change made here is relevant, it might be that the redirect was missing.
In any case, I have changed the production appsettings.json file to include the relevant parts and removed the `PreferHostingUrls` and the URLS usage from the code and settings.
The only thing relevant to this issue is ignoring the well-know folder for https redirect, which again, I'm not sure matters if the certificate update process can handle the redirect, never the less, I'll keep it for now...
