### ISSUE TITLE
Improve issues screen

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1564]
## What I expect to happen
That the text will be aligned RTL and LTR as needed and some punctuations improved baktana

## What really happened
My eye caught some minor points as shown with suggested improvements:
![שכבה בעייתית](https://user-images.githubusercontent.com/49042192/128546942-536db3fa-d972-4905-a20d-2593e45448a4.png)

## My environment
This is one on the PC with chrome

**Comment by HarelM** [comment]
I don't agree with the grammar fixes, sorry...

**Comment by HarelM** [comment]
שקלתי :-) לדעתי זה פחות יפה...

**Comment by Tsurha** [comment]
<div dir="rtl">
תכלס אני נגעתי בקטנה כי לי כל מה שהציק זה היישורים לימין ולשמאל. 
תוהה אם כן תרצה לתקן גם את שגיאה הברורה
reccomend
בקריאה יותר נינוחה רואים שזה ניסוח ישראלי שרוצה שיעבירו אותו דרך כתב טכני עם שפת אם אנגלית.
