### ISSUE TITLE
Route relation in OSM is not reflected well in IHM

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1566]
## What I expect to happen
שכשאני מייצר מסלול משביל החורש ברמת הנדיב כאייקון, הוא יהיה טוב
כנראה הבעיה שיש עם קטע צוואר בקבוק שצריך הלוך חזור. אבל זו הגדרת השביל כפי שתוכנן
אם הייתי מייצר מסלול הייתי ידנית תופר הלוך חזור. אבל כשהגדרתי ריליישן פשוט שייכתי גם לקטע המרכזי.

## What really happened
יש קפיצות מוזרות - ראה מסלול אדום
![image](https://user-images.githubusercontent.com/49042192/129238175-cfc0c512-59c8-45b1-82d9-742049dbe8fa.png)

ההצגה שלו על המפה ללא הפיכה למסלול תקינה
https://israelhiking.osm.org.il/poi/OSM/relation_13082537?language=he

## What I did that caused the issue - step by step
העליתי ריליישן של שביל החורש ברמת הנדיב (התכלת)
הפידיאף של רמת הנדיב הגדיר אותו בול והדרכים כבר היו   
 https://www.openstreetmap.org/relation/13082537

מקור המידע עליו כאן
https://www.ramat-hanadiv.org.il/wp-content/uploads/2020/03/%D7%A2%D7%9C%D7%95%D7%9F-%D7%90%D7%95%D7%A4%D7%A0%D7%99%D7%9D_2018_%D7%A2%D7%93%D7%9B%D7%A0%D7%99-%D7%A2%D7%9D-%D7%A6%D7%91%D7%A2%D7%99%D7%9D-%D7%A0%D7%9B%D7%95%D7%A0%D7%99%D7%9D_%D7%A7%D7%95%D7%A0%D7%91%D7%A8%D7%98_1-2.pdf

## My environment
Win10+chrome

**Comment by HarelM** [comment]
I'll look into the conversing between the OSM relation and the multiline shape.
But there are some things that can cause the algorithm to behave badly:
1. The roundabouts are used fully and not only part of them, this will cause the algorithm to split the line at this position at best, which is not ideal our cause this straight lines.
2. The lower part is creating an up side down Y shape, this is again not ideal.
3. To improve the algorithm chances to succeed it is best to order the ways of the relation.

While it might look like a decent solution, relations are not the best approach to storing bike routes database.

I have posted a post in Facebook to try and get someone to maintain a bike google sheets database which would be ideal for this but no one volunteered, so this is what you get...

Let me know when you finish fixing the relation and I'll take a look at the results...

**Comment by HarelM** [comment]
This is how it will look after the fix - without the incorrect long straight lines but still not perfect due to the definition of the relation.
![image](https://user-images.githubusercontent.com/3269297/129261712-9a5fd007-eb46-4556-8fee-cf41a0b1b5e0.png)

**Comment by Tsurha** [comment]
1. I fixed the relation with the roundabouts.  Indeed it has improved to route created.
2. The lower part if a full circle (closed Y?). The rider is supposed to cycle south, circle it, cycle north. That's how this route was actually planned in that area.
3. How do I order the ways of the relation?  
* Let me know what is needed re the Google sheet and cycling routes. I'll consider if its something I can take or not.  Had no idea about it.
* I do not understand the POI migration to geojson bug. If I learn it will it help our discussion?

![image](https://user-images.githubusercontent.com/49042192/129344984-df2a8f2e-30e9-4f5f-b784-0e919cae22ae.png)

**Comment by Tsurha** [comment]
The lower route I circled in yellow is the orange one on the map. Its wrongly located on the map. Not where its starts. That's another bug from my user point of view. Let me know what to do to change in OSM if it helps

**Comment by Tsurha** [comment]
Its fine now. This is after:
1. Making sure the relation is continuous
2. Adding a line just to allow the IHM algorithm to go north again on something.   This is not a clean solution but a workaround. But hell, it works...

![image](https://user-images.githubusercontent.com/49042192/129386051-8d174422-c93f-42ee-94c1-f15f8e70cd4c.png)

**Comment by HarelM** [comment]
We have reverted the version of the site due to ios issues. So the algorithm is not currently after the fix.
I would advise to wait for an official release before continuing to test this...
