### ISSUE TITLE
Preserve line breaks in descriptions of private POIs

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1568]
## What I expect to happen
If the description of a private POI includes line breaks, the line-breaks should be used when showing the POI description
## What really happened
The editor allows and preserves line-breaks, but they are not shown when clicking the POI.

## What I did that caused the issue - step by step
1. Create a new private POI and use line-breaks in its description
    ![image](https://user-images.githubusercontent.com/1304610/129439220-967fe395-bc48-46d5-8059-e4247c24e949.png)
2. Exit POI edit mode
3. Click on the new POI - the line-breaks are not shown
    ![image](https://user-images.githubusercontent.com/1304610/129439256-f80d65da-2d00-4a42-988b-f0f26003d85a.png)

**Comment by HarelM** [comment]
From a comment posted in the wrong place:
The implementation is probably similar to 807a60f
