### ISSUE TITLE
Icons for future non existing routes are presented.

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1570]
## What I expect to happen
Not show icons for future routes.  

## What really happened
Future routes are presented with an icon on the map. Current examples are from OfneiDan:
https://israelhiking.osm.org.il/poi/OSM/relation_12501861?language=he
https://israelhiking.osm.org.il/poi/OSM/relation_12938651?language=en

When clicking the + "Convert to Route" a messy one is created.

## What I did that caused the issue - step by step
Just realized a non useful icon is on the map

![image](https://user-images.githubusercontent.com/49042192/129457889-0f46ac6f-a15b-4a0f-9d98-b31d0748d441.png)

## For discussion
* Maybe we should add to the relation a tag like highway=proposed and then not present these?
* Maybe non continuous relations should not have a +"Convert to Route" icon?

**Comment by zstadler** [comment]
IMO the tagging of these relations should be changed to include a `construction:` [lifecycle prefix](https://wiki.openstreetmap.org/wiki/Lifecycle_prefix#Stages_of_birth). For example, replace `type=route` with `type=construction:route`.

**Comment by HarelM** [comment]
The straight line is the bug you already reported and will be released when the next version will be out.
I'm not sure I mind that construction bicycle roads will be part of the search... It's a very edge case from what I understand... How many of those do we currently have in the map?

**Comment by Tsurha** [comment]
Thanks Zeev for the right tag on those 2.  They are still on the IHM map.  
There should be 7 Ofnei Dan routes per the Ayalon site. I'll be happy to tag the other 5 properly once it makes a difference. 
Should they be on the map?  At this point while one can create an impossible route from them, I'd say no. Its misleading.  If the point bug makes the + create several separate segments, I would not mind either.  
There is another point that we should deciding where would the icon appear (the start I guess). Seems arbitrary now. 

https://www.ayalonhw.co.il/projects/%D7%90%D7%95%D7%A4%D7%A0%D7%99%D7%93%D7%9F/

**Comment by HarelM** [comment]
Besides what I wrote above, is there anything related to the site's operation that needs to be addressed here?
@zstadler should I transfer this issue to the vector map repo?

**Comment by HarelM** [comment]
Under construction routes should appear on the map based on a previous request made by @Tsurha.
Converting from a POI to route is also available for other entities such as streams.
You should plan a route based on what you see on the map and not just by converting a public POI, preferably also by asking around.
If some would like to know where the route is going to be, even if it's not there yet that a valid user experience - to go and see how it looks today before the change etc.
If there was a compelling number I would consider otherwise, but changing the code for 7 route is not a good ROI.
Sorry, closing...

**Comment by Tsurha** [comment]
@HarelM - I hope you meant that I asked that they "should NOT appear* and was referring to this one:
https://github.com/IsraelHikingMap/VectorMap/issues/119

**Comment by HarelM** [comment]
I honestly got confused with all the request changes around constriction...
In any case, the vector map repo has its issues. What ever is documented there is fine...

**Comment by zstadler** [comment]
> The tagging of these relations should have included a `construction:` [lifecycle prefix](https://wiki.openstreetmap.org/wiki/Lifecycle_prefix#Stages_of_birth). In [changeset 109690433](https://www.openstreetmap.org/changeset/109690433) I've changed the `type=route` tag to `type=construction:route`.

By the way, that is [not the appropriate tagging](https://wiki.openstreetmap.org/wiki/Relation:route#Tags). In [changeset 130834886](https://www.openstreetmap.org/changeset/130834886) I've used `state=proposed` instead

**Comment by Tsurha** [comment]
Thanks Zeev for pointing at the right tag.  Can you explain how to properly tag these in the ID editor?
For example here its still wrongly showing red halo over nothing: https://israelhiking.osm.org.il/map/16.60/32.0647/34.8404

![image](https://user-images.githubusercontent.com/49042192/210578589-aa724926-f2fa-42f9-b9ef-0bdd2f1bddb4.png)


How should it look in ID? Now it looks like this:

![image](https://user-images.githubusercontent.com/49042192/210578981-6d51d8b2-79d4-45c3-a70e-5d852f03d8d2.png)
