### ISSUE TITLE
Enable GPS tracking on first app entrance

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1575]
Summary of phone call:
- After first installation of the application, the GPS tracking will be active. 
- In any later application activation, the GPS tracking will be as it was at the end of the previous activation. 
- The desktop version will always require an activation of the GPS tracking. 

TBD: Will the mobile browser version work like the app or like the desktop?

**Comment by HarelM** [comment]
Code had two flags: isMobile and isCordova.
I can check of one of them is true, but I think I prefer to check only isCordova (I.e. App and not website) as you already have the banner to download the app if you are using the mobile browser...

I'll remove the comment on the initial intro issue and edit "slides".

**Comment by HarelM** [comment]
I've implemented this, but changed a lot related to recording, position, tracking etc. so this needs thorough testing that I have yet to do. I'll publish the app to internal testing once build will complete.
