### ISSUE TITLE
Clean up functionality that moved to Nginx

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1582]
## Infra

We have moved to using nginx as the front facing server.
The following are no longer required to be handled by this website:
- [x] Directory listings + Code around improving the look of the directory listing
- [x] Proxy definition and nuget library
- [x] Https redirect

**Comment by zstadler** [comment]
We may also decide to remove HTTPS support after the HTTP-to-HTTPS redirection is removed and nginx switches to uses HTTP.

**Comment by HarelM** [comment]
Resolved by 2599d9c
