### ISSUE TITLE
Turn by turn navigation instructions

### ISSUE THREAD

**Issue by mbartov** [IsraelHikingMap/Site#1586]
## Feature
(Delete the non-relevant)

## What I expect to happen

Add turn by turn instructions to the exported GPX (waypoints with name and description) so bike navigation computers, as well as other GPX unit, can provide instructions to the next turn as well as the distance to the next waypoint.

## What really happened

No waypoint/instructions are exported. Tried exporting on the web interface in all GPX varients - nothing comes out.

## My environment
* Operating System and version: MacOS
* Web Browser and version: Chrome

## Things I think the developers should know, images, links etc.

some discussion on the topic:
https://burlycross.wordpress.com/2019/07/23/wahoo-help-guide/

**Comment by HarelM** [comment]
I think you can manually do this by creating a private points with the relevant description.
I'm not familiar with wahoo, so feel free to experiment...
I see very little ROI for supporting this from our end, but feel free to submit a PR or design document before implementation.

**Comment by mbartov** [comment]
Shalom Harel,

  This is not a wahoo-specific feature. As far as I understand many mapping devices require the waypoints for the turn by turn instructions (some can calculate it by having the correct map metadata)

  Think of it as exporting a cue sheet of instructions to the mapping device. If the routing engine used can provide the list of turns (and the associated waypoint) it should be a fairly easy task to map it to a list of waypoints when exporting.

  Private waypoints are nice if there are 2-3 points, but when planing a 100km-200km bikepacking trail it will not do.

  As for ROI - not sure how many devices require the cue sheet (I think etrax need it for example) and how many dont (I believe the newer garmins and wahoos dont need it) - but its a nice feature to have. Also, you can extend on this feature as currently most turn-by-turn route produced are just the turns, you can also add waypoint some as climb ahead, summit in x km. etc.
