### ISSUE TITLE
Hebrew typo in maps splash screen - 'מכוון' instead of 'מקוון'

### ISSUE THREAD

**Issue by EranGeo** [IsraelHikingMap/Site#1590]
![image](https://user-images.githubusercontent.com/47955227/131267998-5462c698-fb5d-4e31-817d-c962b9614832.png)

**Comment by HarelM** [comment]
Thanks for reporting this!
This was fixed by 45cd0dd8234da6fa82c133bde8a2af84300bb6d7
Will be published ASAP.
