### ISSUE TITLE
Height graph

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#16]
As a user I would like to be able to see the current route's height data presented on a graph. this graph should be visible only when I need it - i.e. a pop-up like info or help.

**Comment by valleyofdawn** [comment]
Some sites code the type of road (path/track/paved road) in the hight map, color coded, which is nice.
e.g http://osm.santolibre.net/

**Comment by HarelM** [comment]
I used the color according to route's color...
