### ISSUE TITLE
התמצאות בשמירות בענן

### ISSUE THREAD

**Issue by onzd** [IsraelHikingMap/Site#1603]
היי
הייתי שמח אם אפשר היה שבענן תהיה אפשרות לlist כמו בwindoes או אפשרות לייצר ספריות ששם אוכל למיין מסלולים
כמו כן שתהיה אפשרות לחמוק כמה מסלולים בבת אחת ולא אחד אחד כפי שקורה כיום
תודה

**Comment by HarelM** [comment]
תקיות זה חווית משתמש לא מוצלחת למרות שאנחנו רגילים אליה והיא לא ממולצת בתעשייה.
אנא נסה לתאר את הבעיה ולא את הפתרון.
על פניו החיפוש היום מאפשר את רוב מה שצריך למיטב הבנתי.

**Comment by Tsurha** [comment]
<div dir="rtl">
אולי הבעיה היא התמצאות בערימת המסלולים שנשמרו?
החיפוש הקיים לפי שם הוא תכלס טוב.  אבל אפשר לחשוב על עוד שיטות:

* כבר נתמך מיון לפי תאריך שמירה
* אפשר מיון לפי אורך המסלול (סהכ של המסלולים באותה שמירה)
* אפשר מיון מצפון לדרום (של נקודת ההתחלה)
* הוספת סינון לפי הנ"ל

אני אישית מגלה שבסוף אני מעדיף לתפור מסלול כל פעם מחדש. אפילו אם יכולתי לחזור על משהו מהעבר.
כאשר מתכננים מסלול, זה רק מרפרש במוח מה התכוונו לעשות, ואפשר גם לעשות וריאציה חדשה ולגלות מקומות חדשים.

**Comment by onzd** [comment]
לפי תאריך שמירה זה לא מועיל לי
אני יכול לתכנן כמה מסלולים באותו יום למקומות שונים
דירוג מצפון לדרום אהבתי מאד

בתאריך יום ו׳, 17 בספט' 2021, 15:43, מאת VELOCITY Cycling Club ‏<
***@***.***>:

**Comment by zstadler** [comment]
<div dir="rtl">
במקום מיון מצפון לדרום ההיתי מעדיף מיון לפי מרחק המסלול ממרכז המפה או הסמן. כך אפשר לחפש מסלולים שעברו ליד כל מקום שמעניין אותנו.
<br/><br/>

ברור לי שמיון לפי מרחק ממסלול עצמו (לנקודה הקרובה ביותר לאורך המסלול) הוא לא מעשי ולכן אני מציע שהמרחק ימדד אל מרכז המלבן החוסם של המסלול. כמובן שיש בכך חסרון למסלולים ארוכים ולכן ישפיע יותר על הג'יפאים מאשר על מטיילים ברגל.
</div>

**Comment by onzd** [comment]
הבעיה שלי שאני מתכנן מסלולים הם בעיקר לפי מזג אויר כלומר אם יש שטפונות
גשמים בחורף או מסלולים מוצלים בקיץ
צפון דרום יכול לעזור בעת מיון המסלולים שאני שומר בענן
השאלה אם יש אפשרות לעשות סינונים נוספים מעבר לתאריך שמות, צפון דרום, מרחקים

בתאריך יום ו׳, 17 בספט' 2021, 16:07, מאת zstadler ***@***.***

**Comment by HarelM** [comment]
אני רואה פה המון רעיונות לפתרונות ולא מספיק הגדרות בעיה.
אם יותר קל ליצור מסלול חדש במקום למצוא מסלול קיים זו בעיה, אבל כזו שאין לי פתרון אליה, כי זה תמיד יהיה נכון. תמיד יהיה יותר קל ליצור חדש מלמצוא קיים.
אנא נסו לתאר את הבעיה או את המצב שבו שאתם מנסים לפתור ולא את הפתרון.

**Comment by zstadler** [comment]
<div dir="rtl">

> הבעיה שלי שאני מתכנן מסלולים הם בעיקר לפי מזג אויר כלומר אם יש שטפונות
> גשמים בחורף או מסלולים מוצלים בקיץ

</p>
אם תכניס את המילה "שטפון"  לתאור של כל מסלולי השטפונות שלך לא תהיה לך בעיה לחפש ולמצוא אותם אח"כ. כנל לגבי "צל" או כל מאפיין שמעניין אותך. זה לא מצריך שום דבר שלא קיים כבר.
<br/><br/>

> השאלה אם יש אפשרות לעשות סינונים נוספים מעבר לתאריך שמות, צפון דרום, מרחקים

אתה יכול לסנן לפי כל מילה שמופעיה בכותרת או בתאור של המסלולים

**Comment by onzd** [comment]
ככה: אני מייצר כמה מסלולים לפעמים ביום
שומר בענן לפעמים שוכח או מייצר מסלול דומה וקורא לו בשם נגיד נטפים או פעם
נחל נטפים או נטפים ומפלים המסלול נשמר. שאני פותח את השמירות בענן אני מקבל
עם מסלולים שתכננתי וגם זהים לפעמים בשם ואני לא מפסיק לגלול וממש טובע
במסלולים שתכננתי ולא תמיד אני זוכר שכבר תכננתי אותו ( אני מכין את עצמי
להרבה זמן מראש ומעדיף לשלוף מסלול)
גם מעייף אותי לגלול ללא סוף לראות עוד מסלולים שלפעמים הם זהים רק שמרתי
פעםמב2018 ופעם ב2020

בתאריך יום ו׳, 17 בספט' 2021, 16:23, מאת Harel M ***@***.***

**Comment by HarelM** [comment]
לא הצלחתי להבין מה החוויה הבעייתית מבחינתך? שאתה צריך לגלול הרבה?
בלי להבין מה בדיוק הבעיה יהיה לי קשה מאוד לפתור אותה לצערי...

**Comment by onzd** [comment]
אשתמש בתאור מסלול למיון
סבבה
תודה ושנה טובה

‫בתאריך יום ו׳, 17 בספט׳ 2021 ב-16:36 מאת ‪Harel M‬‏ <‪
***@***.***‬‏>:‬

**Comment by Tsurha** [comment]
<div dir="rtl">
אנחנו משוחחים כאן על הבעיה של איך למצוא מסלול.  
ככל שההמלצה היא יותר ויותר להשתמש בענן, ולא בתיקיות במחשב, יהיו יותר משתמשים עם ערימת מסלולים בענן.

חלק מהיוזרים סבבה עם חיפוש טקסטואלי אבל חלק יעדיפו לפי שיטות אחרות. 
הלייבל אינבאליד בגיטהאב אולי יש לו משמעות של תהליך העבודה אבל ברמת המילה אני חושב שהתמצאות זה ואלידי.
אולי זה לא קוסט אפקטיב לתכנת משהו כאן ואולי הטיימינג הוא לא כרגע. אבל אם יש משהו קל למימוש כמו הוספת מיון אלפבתי או אפילו גאוגרפי כלשהו שווה לשקול. 

בגרמין קונקט למשל, הם מוצגים על מפה, יש אפשרויות נרחבות לסינון, ויש סימון מועדפים. 
אני לא חושב שצריך עד כדי כך כאן, אבל זה צורך שהתעשיה עוסקת בו.
![image](https://user-images.githubusercontent.com/49042192/133881835-bbd27cb0-c6e0-48f3-bae7-9a1498b5bb91.png)

**Comment by HarelM** [comment]
אפשר לסבך הכל, אני מעדיף לא לקבל רעיונות מתוכנה שלא מסוגלת לפתוח קבצים.
תשווה את גוגל דוקס ושיטס, אין שם סינונים מורכבים וסיבוך שלא לצורך.
בטח שמדברים על מובייל אז אין הרבה מקום במסך.
אפשר לעשות את החיפוש יותר חכם, אבל לדעתי כרגע הוא טוב מספיק.
אפשר גם לחפש לפי תאריך למיטב זיכרוני.
חשוב לזכור, שברוב המקרים אנשים לא באמת מעוניינים להשקיע הרבה זמן בחיפוש.
אני לא רואה משהו שאי אפשר לפתור כרגע, ואני לא חושב שצריך לסבך את ממשק המשתמש שלא לצורך.
