### ISSUE TITLE
Unselect a hidden route

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1604]
## Bug 
But its a design bug and my bad.
We now have a situation where a route is hidden (closed eye) but is still selected. 
Please see the pic where only the blue 16Km route is presented. However, The 9Km is selected and also it's stats show in the bottom right. Confusing.

## What I expect to happen
When a user hides a route, it will also unselect it. We can decide if another route gets selected by default or none do.
When no routes are selected, the stats pane should not show.  
I marked the yellow graph icon, suggesting that it would be colored by the selected route color. This one is a cute nice to have that helps in route association.

## What really happened
![image](https://user-images.githubusercontent.com/49042192/133627490-72e9e3f2-1195-4a83-975d-b18fbc8b4f74.png)

## What I did that caused the issue - step by step
Hidden the selected route.

## My environment
win10+chrome

## Things I think the developers should know, images, links etc.
Gmar Hatima Tova

**Comment by HarelM** [comment]
Seemed like I removed the unselect route when it gets hidden in the previous feature #1550, I'm not sure why...
In any case, it seems to be OK after adding back the line...
