### ISSUE TITLE
Add handles to externally imported file or recording

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1607]
## Current behavior
A recording uploads without points besides start/finish. 
If one starts editing it as is, he will get an undesirable result

## Discussion
An experienced user may add anchor points. An newbie may say the SW sucks.
How about adding say 10 points along the route in equal distances? This is just to an uploaded GPX that only has a start/finish.

## Upload 
![Recording](https://user-images.githubusercontent.com/49042192/133808269-27e1b44f-13ea-4318-a0ec-63de7a6136a1.PNG)

## Undesirable first edit
![1st-Edit](https://user-images.githubusercontent.com/49042192/133810922-4a866a2f-6dc5-43dd-b57d-9bb58cd32c68.PNG)

## Possible solution
![Possible](https://user-images.githubusercontent.com/49042192/133816020-570ae502-c756-4850-9a0a-68a6b95eebc8.PNG)

**Comment by HarelM** [comment]
I had this in the past where I ran Douglas Packard algorithm on a route to find the 20 "most important" points and added them as markers to allow better editing of files that were not created in the site, feels like an overkill when looking back at this, but maybe 10-20 points spread equally is good enough and easy to implement.
