### ISSUE TITLE
Fetch images from wikidata item

### ISSUE THREAD

**Issue by yotamN** [IsraelHikingMap/Site#1609]
Wikidata can have more information that we don't have at openstreetmap, maybe we should fetch that data too.

I've looked at the API, it seems that we can easily get the images from this endpoint: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=ID&props=claims&format=json

Is it something we want?

**Comment by HarelM** [comment]
We are currently merging data from Wikipedia to OSM. Can you give an example of a point that can be improved?
I'm not sure what's the difference between eikipedia and wiki data honestly...

**Comment by yotamN** [comment]
Wikidata is a knowledge graph. Unlike Wikipedia which is for humans, Wikidata is for projects like Openstreetmap and IsraelHikingMap to fetch data from. It could give us more information than just images, like famous people born in the selected town (probably not for this map) or population history.

Is there a reason not to use it? I personally edit both Openstreetmap and Wikidata and don't see a reason to duplicate the effort.

**Comment by HarelM** [comment]
The only reason not to is ROI. implementing this is not trivial.
If you would like to implement this then obviously I have no objections.
What I'm missing is a concrete example to better understand what you are talking about since I'm not familiar wikidata...

**Comment by yotamN** [comment]
Well, I will look into it. I played a bit with the API and it seems possible without a lot of work, for example:

```
wget -O - "https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q96240618&props=claims&format=json" | jq -r '.entities.Q96240618.claims.P18 | .[].mainsnak.datavalue.value' | xargs -d '\n' printf "https://commons.wikimedia.org/wiki/File:%s\n"
```

The problem I have (except of figuring out how to pass it to the image-scroller component because it's not editable) is with credits, it seems you don't show credits on the photos either. Is it because everything people upload is CC0 or did you just miss it?

**Comment by HarelM** [comment]
For images that are merged we supply a link to the wiki page where the full info is and the attributing is, for images upload from our site I don't think we need...

**Comment by yotamN** [comment]
I don't think there is a reason for or against Wikidata in oppose to Openstreetmap. It's just a different open data source that can have more images (I personally add there but I will probably add to Openstreetmap too, others not necessary).
