### ISSUE TITLE
צבע שביל לא נכון

### ISSUE THREAD

**Issue by yehoramc** [IsraelHikingMap/Site#1612]
## Bug/Feature
צבע שביל לא נכון בשביל אמיר מי-טל שליד מערת קשת
מיקום:
33.076205, 35.195349

## What I expect to happen
לפי המפה השביל בצבע אדום

## What really happened
במציאות הוא בצבע ירוק

**Comment by HarelM** [comment]
תודה על הדיווח!
כולם יכולים לערוך ולשנות את הצבע :-)
יש סרטוני הסבר בדף של התשובות לשאלות הנפוצות.
אם לא תסתדר אשמח לעזור.

**Comment by yehoramc** [comment]
אני אנסה, תודה על תשובתך

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yehoramc** [comment]
ניסיתי לערוך ולשנות את צבע השביל מאדום לירוק. אני מקווה שהצלחתי. הייתי רוצה שתסתכל בבקשה לוודא שעשיתי את זה נכון
בברכה
יהורם

________________________________

**Comment by HarelM** [comment]
זה אמור להתעדכן במפה בתוך כמה דקות, נסה להסתכל באתר בעוד חצי שעה, אם זה לא עבד אני אבדוק מה עשית.

**Comment by yehoramc** [comment]
זה אכן התעדכן. אגב, המשך השביל לכיוון מזרח והמשך השביל לכיוון מערב הם גם בצבע ירוק בפועל, אך לא רציתי לשנות כי טיילתי רק בקטע הקצר. אני מאוד מודה לך על עזרתך

________________________________

**Comment by HarelM** [comment]
בכיף, פעם הבאה שתיהיה באיזור תוכל לעשות את המשך בשביל ולעדכן :-)
