### ISSUE TITLE
Add Wikipedia coord text to POI popup

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#162]
Wikipedia coordinate templates ("coord") provide a location for use in articles. The suggested templates for Hebrew articles is of the form
`{{coord|31.847524|35.079346|display=title|type:landmark}}`
It would be useful to add this text, with a title similar to "מיקום עבור וויקיפדיה", to the popup of POI's.

The user scenario for adding coordinates to Wikipedia:
- Add a POI in the appropriate place
- Click on the POI icon
- Copy the Wikipedia "coord" template to the Wikipedia article

Notes:
- Details of the coord template are available at https://en.wikipedia.org/wiki/Template:Coord
- For Google Maps and Amud Anan, The Hebrew Wikipedia provides [this bookmarklet](https://he.wikipedia.org/wiki/%D7%9E%D7%93%D7%99%D7%94_%D7%95%D7%99%D7%A7%D7%99:Common.js/coords.js). [This article](https://he.wikipedia.org/wiki/%D7%95%D7%99%D7%A7%D7%99%D7%A4%D7%93%D7%99%D7%94:%D7%91%D7%95%D7%A7%D7%9E%D7%A8%D7%A7%D7%9C%D7%98%D7%99%D7%9D) explains is how to use the bookmarklet. IMO, it is not easy to understand and to use.

**Comment by HarelM** [comment]
I'm not sure if I like it or not...
![image](https://cloud.githubusercontent.com/assets/3269297/14413407/8b9b2226-ff81-11e5-8aa2-ff8983e992d0.png)

**Comment by zstadler** [comment]
Is it possible to put the text in a text box, and possible select it, such that copy for pasting will be easier?
I would also suggest to put it last - after the coordinates.
