### ISSUE TITLE
שמירה כפולה

### ISSUE THREAD

**Issue by onzd** [IsraelHikingMap/Site#1621]
<div dir="rtl">

מופיעים לי שמירות כפולות של מסלולים תחת אותו שם ותאריך
שמרתי פעם אחת וכך זה הופיע
התופעה הזו קרתה גם מזמן וישבתי וניקיתי את כל המסלולים בשמירות כפולות 
עכשיו קרה שוב

![Untitled](https://user-images.githubusercontent.com/43242549/135967843-7c1388bc-2f80-4eeb-815c-5392e5843ede.jpg)

**Comment by HarelM** [comment]
תוכל לנסות להבין מה גרם לזה?
אני לא רואה את הבעיה אצלי ולכן אשמח לדעת מה גורם לה.

**Comment by onzd** [comment]
אני לא יודע לומר זאת הכל היה מצויין עד אתמול
אולי בגלל ששכנעתי מישהו לקנות את המפות אתמול  קיבלתי בונוס מסלולים? :) אנסה לעשות מסלול פיקטיבי ולעלות אותו כמה פעמים אולי אתפוס

**Comment by onzd** [comment]
עדכון :באפיקציה בנייד תקין במחשב לא תקין בכרום בדקתי באדג גם תקין אז כרגע נראה לי שהבעיה בדפדן כרום במחשב

**Comment by HarelM** [comment]
מה הכוונה הבעיה בדפדפן של כרום?
רק שם אתה רואה מסלולים כפולים?
אם כן, אולי שווה לנסות לעשות logout login, לראות אם זה עוזר...?

**Comment by zstadler** [comment]
<div dir="rtl">
שווה גם לנסות במצב incognito בכרום

**Comment by onzd** [comment]
יצאתי וניכנסתי לא עזר

‫בתאריך יום ג׳, 5 באוק׳ 2021 ב-11:24 מאת ‪zstadler‬‏ <‪
***@***.***‬‏>:‬

**Comment by onzd** [comment]
טוב.. נכנסתי ממחשב אחר הכל תקין חזרתי למחשב שלי ונכנסתי לכרום כאורח
והתחברתי לאתר שוב והכל תקין כנראה בעיה פרטית שלי אני חושב שאפשר לסגור את
הקריאה

‫בתאריך יום ג׳, 5 באוק׳ 2021 ב-11:28 מאת ‪ofer kapon‬‏ ***@***.***
‬‏>:‬
