### ISSUE TITLE
Incognito mode and embedded maps

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1638]
## What I expect to happen
A page that embeds an IHM map would be visible when embedded in a 3rd-party site

## What really happened
![image](https://user-images.githubusercontent.com/1304610/137622996-491ca433-7b68-4f6b-b740-40ce2fd1cf5c.png)

## What I did that caused the issue - step by step
Open [שביל המעיינות on inature.info](https://inature.info/wiki/%d7%a9%d7%91%d7%99%d7%9c_%d7%94%d7%9e%d7%a2%d7%99%d7%99%d7%a0%d7%95%d7%aa) in Chrome's incognito mode

## My environment
* Operating System and version: Win 10 Pro
* Web Browser and version: Version 94.0.4606.81 (Official Build) (64-bit)

## Things I think the developers should know, images, links etc.
From the browser's console:

```
main.a4f90befedd5b5c40a3b.js:1 2021-10-17 13:21:37 | ERROR | Failed IHM Application Initialization: OpenFailedError: UnknownError The user denied permission to access the database.
 UnknownError: The user denied permission to access the database.
e.error @ main.a4f90befedd5b5c40a3b.js:1
main.a4f90befedd5b5c40a3b.js:1 2021-10-17 13:21:37 | ERROR | Cannot read properties of undefined (reading 'getState')
TypeError: Cannot read properties of undefined (reading 'getState')
```

**Comment by HarelM** [comment]
Yes, we can avoid showing this alert message in case of iframe usage.
