### ISSUE TITLE
Image creation problem for routes outside view area

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1644]
## Bug
What I circled in red, was supposed to show a small map:
![image](https://user-images.githubusercontent.com/49042192/138911857-82c28d6a-4309-40ed-b601-933b4ad53f1a.png)

## What I expect to happen
See a little map in that dialog box

## What really happened
Looks like its missing something there

## What I did that caused the issue - step by step
Used the following https://israelhiking.osm.org.il/share/aMWkVQ6rUY
Saved it to cloud. 
Dialog did not show map

## My environment
Win10+chrome

**Comment by HarelM** [comment]
This is a hack to solve this, I'm not sure entirely how this will affect the images but it seems to solve this issue reasonably well.

**Comment by HarelM** [comment]
@Tsurha I have deployed the fix only on the website (not in the mobile apps).
Please let me know if you encounter this issue in other routes.
Thanks for reporting this!! :-)

**Comment by Tsurha** [comment]
Thanks for solving. A quick test shows its fine.  
To me the small map is a nice to have. Simply deleting it in the mobile app, is also a valid solution.

![image](https://user-images.githubusercontent.com/49042192/144699327-efb16172-59d9-4bf5-a090-4bd2c4c8ebc6.png)
