### ISSUE TITLE
Hight graph smoothing for computing total climb & descent

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#165]
There is a concern that the total climb & descent provided by the site is higher than needed because of noise in the DEM data.

One option for a smoothing is the algorithm used for smoothing GPS and other ways by Potlatch 2

**Comment by zstadler** [comment]
Potlatch's ["Simplify" source code](https://git.openstreetmap.org/potlatch2.git/blob/233799c18c25b0f6aeec8c99c603ea9e02afa1d9:/net/systemeD/potlatch2/tools/Simplify.as) says it is "using the Douglas-Peucker algorithm". 

The [Wikipedia article](https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm) also has a clear explanation, animation, and pseudo-code of the algorithm.

[Google finds several JavaScript implementations](https://www.google.co.il/#q=douglas-peucker+algorithm+javascript) of the algorithm.

**Comment by zstadler** [comment]
This [JavaScript implementation](http://mourner.github.io/simplify-js/) claims to be taken from Leaflet. Perhaps the client already has that code as part of implementing the [smoothFactor](http://leafletjs.com/reference.html#polyline-smoothfactor) for Polylines.

**Comment by HarelM** [comment]
Found it: ```L.LineUtil.simplify(...)```
I'll see if I can modify the gain and loss calculations.
