### ISSUE TITLE
Unable to delete map layer if the name is very long

### ISSUE THREAD

**Issue by Moshe81** [IsraelHikingMap/Site#1650]
## Bug
(Delete the non-relevant)

I added a new map layer but I was wrong and I set the layer name to be the URL 
"https://a.tiles.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}.jpg?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA"

After I realized its the wrong name I wanted to delete it but I could not as the GUI does not show the 3 dots
![image](https://user-images.githubusercontent.com/29856634/139821766-e8924232-3b7f-4ee2-83fc-0beca24518ec.png)

## What I expect to happen
To be bale to delete this layer

## What really happened
unable to delete

## What I did that caused the issue - step by step
adding new layer with the name to be :
"https://a.tiles.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}.jpg?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA"
"

## My environment
* Operating System and version: Windows 10 , Chrom
* Web Browser and version:

**Comment by HarelM** [comment]
Thanks for taking the time to report the this issue!
I guess this is a css issue where the text is overlapping the button.
As a workaround, until this bug is resolved, you can edit the html using chrome developer tools to allow you to click the button to edit the name of the layer...

**Comment by Moshe81** [comment]
thanks - I was able to delete from the HTML
![image](https://user-images.githubusercontent.com/29856634/139849468-5b3252fa-0124-406d-ba23-d36d946808e3.png)
