### ISSUE TITLE
Increase search ranking for trail segments

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1652]
## What I expect to happen
Names of trail segments to have higher search ranking in order for them to be included in the "trop-10" list

## What really happened
Trail segment names are ranked lower as do all street names.

## What I did that caused the issue - step by step
- Search for "[מעלה שרב](https://israelhiking.osm.org.il/map/15.00/30.7466/34.9070)" path
- Search for "[מעלה זיק](https://israelhiking.osm.org.il/map/16.00/30.7915/34.8550)" track and ignore results that are not OSM highways.

## Things I think the developers should know, images, links etc.
Please increase the ranking for names of `highway=path` and `highway=track` objects. 
At this stage I suggest not including `highway=steps` and `highway=footway` as they are used more often in urban areas.

**Comment by HarelM** [comment]
After the change the search results appears as follows:
![image](https://user-images.githubusercontent.com/3269297/142632861-1cc261c5-57c4-476b-b586-39a1875806f9.png)
![image](https://user-images.githubusercontent.com/3269297/142632904-03b1a596-4fd0-4a99-9dd8-2143a7c1f630.png)
