### ISSUE TITLE
Improve UX after location access is denied

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1654]
## What I expect to happen
- Turn-off GPS tracking if location access is denied.
- If the user activates the GPS tracking and location access is denied, let the user know how to enable it.

## What really happened
Once location access was denied, there is no indication for it when returning to the app. GPS location spinner is turning forever.

## What I did that caused the issue - step by step
Step 1:
- Exit the app if needed.
- Open app permissions settings for the app and "Deny" location access.
- Open the app.
- Activate GPS tracking, if needed.
- "Deny" location access, if asked.
- The GPS location spinner continues to turn.

Step 2:
- Exit the app while the GPS location spinner is turning.
- Re-enter the app.
- The GPS location spinner is turning and there is no indication that the location access is denied.

## My environment
* Operating System and version: Android
* Web Browser and version: Latest app version

## Things I think the developers should know, images, links etc.
It would be nice if the explanation will have a button that opens the app's settings page, as described in [this stackoverflow topic](https://stackoverflow.com/questions/32822101/how-can-i-programmatically-open-the-permission-screen-for-a-specific-app-on-andr)

**Comment by HarelM** [comment]
Interestingly enough, currently, we don't listen to the `error` event.
Let's start with listening to this event and see where we are.
Opening the permissions menu is relevant only to Android and requires deeper changes which I'm not sure is not an overkill in this use case.

**Comment by zstadler** [comment]
Recent Android releases _may_ have made this scenario more likely than before. Andoid 11 will remove the location access permissions, by default, if the app isn't used.  It is not clear if the user is asked to enable the permissions again after such a removal.

![image](https://user-images.githubusercontent.com/1304610/140922345-d64ff781-a0dd-407f-88a2-aee183e105b5.png)

**Comment by zstadler** [comment]
>  Opening the permissions menu is relevant only to Android and requires deeper changes which I'm not sure is not an overkill in this use case.

Yes, this issue/scenario is applicable only to Android devices.

**Comment by HarelM** [comment]
Listening to `error` event didn't solve this issue... reopening... maybe `authorization` will help...
