### ISSUE TITLE
Failed to create hike in Nakeb

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1659]
## Bug
Clicked the Nakeb icon after saving to cloud and got a Nakeb error. Note that its a save with several routes, which may be a thing.
![image](https://user-images.githubusercontent.com/49042192/144699639-433e3de1-e394-4bd0-a8c7-305f31f1147d.png)

## What I expect to happen
I wish I could tell. Its the first time I clicked this...

## What really happened
Got this:
![image](https://user-images.githubusercontent.com/49042192/144699690-674c42df-0704-40da-a2c9-3541331886fc.png)

Here is the actual bug ling for your reference 
Internal error
Ticket issued: nakeb/176.231.93.40.2021-12-04.07-58-05.f8e83e36-30bd-4fdb-a414-46412463f223

## What I did that caused the issue - step by step
Created this map: https://israelhiking.osm.org.il/share/5zELeIDEdq

Clicked this:
![image](https://user-images.githubusercontent.com/49042192/144699772-7bf6221d-384c-416c-8726-b707d63ced80.png)

BTW "Save in the Cloud and Share" is cumbersome. I'd go for simply: "Save & Share".
You could consider also changing:
* "Open a File" to "Open File"
* "Export" to "Export File"

Then clicked the green button:
![image](https://user-images.githubusercontent.com/49042192/144699875-e4036497-ad70-46a6-b1a8-166bad6bee7a.png)

Here I'd change its wording to "Save to Cloud & Share".
After clicking it I got the link and was happy with the new map preview. So went to an unknown territory (to me) in Nakeb, This is when things got messy. 

## My environment
Win10+Chrome

## Things I think the developers should know, images, links etc.
Harmony and understanding

**Comment by zstadler** [comment]
@Tsurha,

It looks like an internal issue of Nakeb which was caught by their website and a ticket was created.
Could you [get in touch with them](https://www.nakeb.co.il/contact)?

**Comment by Tsurha** [comment]
<div dir="rtl">
לבקשתך שלחתי אליהם את זה:

היי,
יש קישור מ IHM אליכם שלא עובד כרגע. אנא הציצו בקריאה להלן.  הכי טוב אם תגיבו שם:
https://github.com/IsraelHikingMap/Site/issues/1659#issuecomment-985980409

However, since I'm not a Nakeb user, pls let me reduce my involvement. To me a good solution in IHM would be to remove the link icon altogether.  I'll stay within IHM and would appreciate if you could have a look at the captions suggested above.

**Comment by HarelM** [comment]
FYI @matanbenmoshe

**Comment by MatanBenMoshe** [comment]
Thanks for finding this issue.
It was an issue in Nakeb website. I fixed it now.

**Comment by HarelM** [comment]
Thanks @MatanBenMoshe ! I'll close this issue for now.
@Tsurha feel free to report back if this is not fixed and I'll reopen.

**Comment by Tsurha** [comment]
Nakeb now allow opening their submit form.  So the only thing we are left with here, are captions that do not exactly reflect the functionally. It does not create, and its only about hiking, not cycling:

![image](https://user-images.githubusercontent.com/49042192/144981035-1530c9c7-2e17-4694-9e66-c6a3c7e23264.png)

My recommendation is to change to "Submit hike to Nakeb" and "הצעת מסלול הליכה לאתר נאקב"
In addition I guess the whatsapp link is the most used nowadays and should be first.
