### ISSUE TITLE
Allow routing through ford=yes

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#166]
This issue was raised in the Facebook forum.

For example:
![12967992_10207767425137714_4033025213582325055_o](https://cloud.githubusercontent.com/assets/1304610/14564295/7fe2b696-032e-11e6-9fe4-766664b17b55.jpg)

It is also one of the reasons for switching the routing on/off per-segment. http://israelhiking.osm.org.il/#/?s=BDt5uxo0KS is another example where 6 ford crossings needed to be found and applied with no-routing in order to complete a route.

See graphhopper/graphhopper#236 for the discussion on the Graphhopper default and some hints about the required change.

We need to see how we keep this change while enabling easy integration of Graphhopper updates. Perhaps we should create our own branch and merge the changes from the main branch periodically.

**Comment by HarelM** [comment]
As you said, this will probably require forking the GH repository here and creating propiotary FlagEncoders.
I'm also interested in the following issue https://github.com/graphhopper/graphhopper/issues/193 which in theory could also solve this problem and any other we might have but probably requires a lot more changes than we have time to code. never-the-less it might be worth in terms of open source and world peace :-)

**Comment by HarelM** [comment]
@zstadler,  Please make sure my fix is working, I think I found an example in your link but I'm not 100% sure. Also you can ask @valleyofdawn to post the fix on facebook in case this truly solves this issue.

**Comment by HarelM** [comment]
Thanks @karussell for pointing me to the right direction, wouldn't hurt to add it in the example properties config file though, took me a bit of backwards engineering to find it :-)
