### ISSUE TITLE
Cannot delete website links

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1661]
## Bug
Reported by @oriori

## What I expect to happen
Updating an OSM POI by deleting website links should work

## What really happened
There is no changeset in OSM

## What I did that caused the issue - step by step

1. Open https://israelhiking.osm.org.il/poi/OSM/node_9256123218
2. Enter edit mode
3. Delete both website links
   <img width="30%" src="https://user-images.githubusercontent.com/1304610/144803361-cb0b0a9f-aab1-4464-86a0-3669cffe3783.png" />
4. Save
5. Open the node in OSM - https://www.openstreetmap.org/node/9256123218
6. The website links are still there and the last edit was unchanged.

## My environment
Browser: Chrome 96.0.4664.45
OS: Windows Server 2008 R2 / 7 64-bi

**Comment by HarelM** [comment]
Thanks for the taking the time to report and reproduce this issue.
The problem is due to how the site handles wikipedia links.
As a workaround you can go to the OSM editor and remove the wikipedia tags.
