### ISSUE TITLE
Feature inconsistency

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1662]
## Feature inconsistency
When there are no routes, trying to export (save file) rightfully fails with a red "יש להוסיף נקודות למסלול"
![image](https://user-images.githubusercontent.com/49042192/144983355-b46cf540-de33-4c84-bfaf-a61d05f849b7.png)

However saving nothing to the cloud does work. 
![image](https://user-images.githubusercontent.com/49042192/144983752-fc03bacb-a21b-4737-963c-e7e70c6e8aa8.png)

## What I expect to happen
I'd not allow saving nothing so its consistent

## What really happened
The nothing spams the cloud...

**Comment by HarelM** [comment]
A share is not only a route but also the maps.
It makes perfect sense to share an "empty" route.
