### ISSUE TITLE
Preserve timestamps of uploaded trace 

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1663]
## Feature

The options used in IHM, "Public" and "Private", do not provide timestamps via the API. This prevents access to important information that can be useful for IHM users and in general. For example:

-  View GPS trace points in order of the recording
   - This is how a trace uploaded from the app looks when downloaded from the API:
     ![image](https://user-images.githubusercontent.com/1304610/143567595-2458cc69-8ce7-4d9d-a380-d3dfed095c88.png)
- Filter traces by age
- Speed analysis

OSM defines 4 [trace visibility options](https://wiki.openstreetmap.org/wiki/Visibility_of_GPS_traces):

> ![img](https://user-images.githubusercontent.com/1304610/145682669-2ccdaca6-4749-47f2-9954-69f93c1adc42.png)

The "Trackable" and "Identifiable" options preserve timestamps via the API and should be used for uploaded traces. Unfortunately, these terms are not good for a UX. I suggest keeping the IHM terms and changing their mapping to the OSM options:

| IHM term | Current OSM option | New OSM option | Note |
|---|---|---|---|
| Private | Private | Trackable | Default |
| Public | Public | Identifiable | |

**Comment by HarelM** [comment]
Updating the server in this case is enough to make the default change. There will be a time between the server update and the client update where trace will be shown in the UI as "public" and not private. This doesn't concern me as much as changing the default for new traces, i.e. the importance of this change is at a higher priority than the exact term in the UI (which might be buggy until the new version is released and upgraded to).
