### ISSUE TITLE
GPS accuracy issues on android 12

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1679]
## What I expect to happen
GPS location should be as accurate as possible

## What really happened
GPS location is not accurate and accuracy degrades if using another more accurate app.

## What I did that caused the issue - step by step
1. Start locating tracking
2. Look at the blue circle

## My environment
* Operating System and version: Android 12
* Web Browser and version: n/a

## Things I think the developers should know, images, links etc.
This started after I upgraded my phone to android 12.
When I use the app without any other app the locating is not very good.
I used GPS test app to see if it gives better results.
When GPS test is active the accuracy is high. Also when using the browser. The problem is when this app is "alone".
The code for gps test can be found here:
https://github.com/barbeau/gpstest
I need to investigate using a simpler app than IHM.
The issue is also tracked here:
https://github.com/HaylLtd/cordova-background-geolocation-plugin/issues/59

**Comment by HarelM** [comment]
Might worth ac read:
https://android-developers.googleblog.com/2020/12/improving-urban-gps-accuracy-for-your.html?m=1
Especially the fused location client

**Comment by zstadler** [comment]
Support emails related to this issue are labeled "GPS@Android12"

**Comment by HarelM** [comment]
I've found the root cause of this issue. more info can be found in the plugin issue thread.
