### ISSUE TITLE
Add "X" button for dismissing the offline download confirmation

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1680]
## What I expect to happen
Be able to dismiss the offline download confirmation dialog and avoid the the download by touching an "X" button.

## What really happened
I believe this is the only dialog that does not have an "X" button.
On android, it is possible to dismiss the dialog with the "back" action.
On iOS, the dialog cannot be dismissed.

## My environment
* Operating System and version:
* Web Browser and version:

## Things I think the developers should know, images, links etc.
iOS screenshot, for reference

![image](https://user-images.githubusercontent.com/1304610/149651624-d06fca56-8045-4f90-82bb-a9588e5960ac.png)

**Comment by HarelM** [comment]
I've added a cancel button instead of an "x" due to lack of patience to deal with css issues...
