### ISSUE TITLE
POI merge fails to find an existing Wikipedia page

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1690]
## What I expect to happen
The POI pane to show a link to the Wikipedia page according to the `wikepadia` tag

## What really happened
Some POIs do not show the Wikipedia link

## What I did that caused the issue - step by step
[This node](https://www.openstreetmap.org/node/8194077655) has the following wikipedia tags

| tag | value|
| --- | --- |
| wikipedia | [he:שביל רמות מנשה](https://he.wikipedia.org/wiki/he:%D7%A9%D7%91%D7%99%D7%9C%20%D7%A8%D7%9E%D7%95%D7%AA%20%D7%9E%D7%A0%D7%A9%D7%94?uselang=he)|
| wikipedia:he | [שביל רמות מנשה](https://he.wikipedia.org/wiki/%D7%A9%D7%91%D7%99%D7%9C%20%D7%A8%D7%9E%D7%95%D7%AA%20%D7%9E%D7%A0%D7%A9%D7%94?uselang=he) |

OSM recognized them as valid tags and creates the above links to Wikipedia.

IHM shows a Wikipedia marker in the POIs layer, but there is no Wikipedia icon and link in the POI info pane

![image](https://user-images.githubusercontent.com/1304610/152940111-3f0c20c4-a1d3-44c2-a1cd-c22f22d9dd97.png)

## Things I think the developers should know, images, links etc.
`logs/daily-update.log` lists `שביל רמות מנשה` in the following error:
```
fail: IHM[0]
      Unable to get wikipedia pages for: טמבור,משק האוצר,נחל לוז,מגנוליה (חברה),ReBar,אבן גבול,חורבת בית סילה,עבדה,הגדר הטובה,גת (משטח דריכה),עוצבת השרון,תל קילא,מבצע צרצר,באר לימון,צבי ים,מגדלי שמירה בריטיים (ראש העין),שביל רמות מנשה,נואמיס,גביעונית הלבנון,מאיר הר-ציון,זיף,נחל סעדיה,ואדי דליה,בית הבק,פארק המעיינות#השביל הרטוב,חורבת צלית,אירוס הסרגל,אנדרטת המתנדבים העברים ליחידות הצבא הבריט%D7%,קרית גת,נחל געתון,בית הקברות בהר הזיתים,כרמלית,מרכז רפואי אסף הרופא,נחל בית עריף,חמי טבריה,נחל שקמה,מרכז פרס לשלום ולחדשנות,(בר גיורא (מושב,נחל ברקן,מכרות נחושת תמנע,איתנים
```

Related to #1688

**Comment by HarelM** [comment]
The above error message is due to a bad character in the wikipedia name (%7D).
I've updated the error to be more informative.
Having said that, there are reference to wikipedia pages that do not exist (the page not found errors) which indicate on a bad wikipedia link.
I've done some fixes tonight, let's monitor the next few rebuilds.

**Comment by HarelM** [comment]
Since the code here is only server side I advise to deploy these changes and monitor the log after the changes I made.
It should solve this issue without any need to do something special, I hope.
