### ISSUE TITLE
Handling of subscription expiration

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1699]
## What I expect to happen
Notify Urge the customer to renew 
When a subscription expires, notify the customers and urge them to renew.  For example,

> Your subscription to the offline maps has expired. Please consider renewing through the store.
> The last update of the offline maps may still be available temporarily.

## What really happened
The customers see a message that their offilne maps are up-to-date.

## What I did that caused the issue - step by step
- Wait for the subscription expiration
- Download an update of the offline maps

## Things I think the developers should know, images, links etc.
[Related Fovea issue](https://github.com/j3k0/cordova-plugin-purchase/issues/1254#issuecomment-1059527506)

**Comment by HarelM** [comment]
I'm planning to try and address this by retuning a different response from the server (403) when the user does not have a valid subscription, I hope this will improve this as I don't have a good way to test this...
