### ISSUE TITLE
urls too long

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#17]
With the current scheme you can only share a 150 point long route.
Worse yet a url with hundreds of characters is unwieldy. Hard to paste and ugly.
Buy http://ihm.org.il for 50 nis a year. (I'll chip in)
Shorten the url locally with software such as yourl. 
http://yourls.org/

**Comment by zstadler** [comment]
Using ihm.org.il would save the 11 characters currently taken by
"IsraelHiking" while each additional route path takes 17 characters (e.g.
":h32.1337,34.8077").
Therefore, this proposal will allow increasing the path by 1-2 point -
which are about 1% longer.

According to the FAQ <http://yourls.org/#FAQ>, the yourls.org solution
requires:

   1. A server with *mod_rewrite* enabled
   2. At least *PHP 5.2*
   3. At least *MYSQL 4.1*

**Comment by valleyofdawn** [comment]
The ihm.org.il only addresses the ''ugly'' part.
Does the second part means it's possible or not?

**Comment by HarelM** [comment]
Currently we do not have a good server side, Also, route sharing this way will require either logging in or that everyone will be able to edit the route you share.
150 points is more than enough for simple sharing, you can use a file if you want to share more.
I'd like to keep the site login free if possible.
