### ISSUE TITLE
Handle OSM server failure during public POI upload

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1703]
## What I expect to happen
Uploads of public POI to handle temporary errors of the OSM server

## What really happened
A user successfully uploaded a public POI to the IHM server. The server successfully uploaded the pictures to Wikimedia Commons, but the upload to OSM resulted with an "The response ended prematurely" error.

As a result, the upload of the public POI was aborted.

## What I did that caused the issue - step by step
Uploaded a new public POI

## My environment
* Operating System and version: Android 11
* Web Browser and version: App version: 9.12.54

## Things I think the developers should know, images, links etc.
The public POI flow is built with failure-recovery between the client and the IHM server. It assumed that the OSM server is always available. Apparently, this is not always the case.

Does the trace upload flow handle potential OSM server failures?

**Comment by HarelM** [comment]
In traces it's even more complicated because the OSM server returns 200 even on failure due to background processing.
This is currently out of scope for this issue.

**Comment by HarelM** [comment]
I've added retries and some logging for future monitoring of this issue.
