### ISSUE TITLE
Save application state better

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#172]
no matter in what state you closed it.

**Comment by HarelM** [comment]
State is not fully saved. Currently the only things that are saved are the routing per point (bolt icon), the maps and overlays you are using(not their state) and the position.
Saving more data costs in maintenance and hard to read code so I prefer to do it as less as possible.
You want to add to this list the last viewed map and the last routing type used in the last route that was in edit mode (meaning this will be saved when you change the routing type no matter which route you are editing)?

**Comment by valleyofdawn** [comment]
Last viewed map and overlay, and last routing mode. Certainly.

**Comment by zstadler** [comment]
Active map overlays, in plural, please.

**Comment by HarelM** [comment]
Now saving last selected base layer and all visible overlays.
I'm still not sure what to do about the routing...

**Comment by zstadler** [comment]
Overlay layers do not seem to be saved.

- Open [this map](http://israelhiking.osm.org.il/#/?s=vqpBWP0Trh) to add OpenSeaMark overlay.
- Open the site in a separate tab, and the overlay layer is not there.

**Comment by zstadler** [comment]
Also, unlike a base layer, when an overlay layer is added based on a shortcut, it cannot be edited in advanced mode.
