### ISSUE TITLE
POIs do not appear in external search engines

### ISSUE THREAD

**Issue by nonZero** [IsraelHikingMap/Site#1720]
## Bug
POI URLs do not appear in (Google's) search results.

## What I expect to happen
When searching for a known OSM POI:
<https://www.google.com/search?q=%D7%94%D7%A8+%D7%A9%D7%A7%D7%93>
This url should appear in the results:
<https://israelhiking.osm.org.il/poi/OSM/node_8420568854>

## What really happened
It does not appear :-)

## Things I think the developers should know, images, links etc.
A `sitemap.xml` exists:
<https://israelhiking.osm.org.il/sitemap.xml>
But apparently it is not enough to be picked by google.

Related Google SEO article:
https://developers.google.com/search/docs/advanced/javascript/javascript-seo-basics

**Comment by HarelM** [comment]
I also implemented some logic to return a page when the Google crawler scans the content of the sitemap (this page can be easily improved if needed, it only returns some open graph headers).
But there's probably more to it.
As far as I know in order to properly support SEO there's a need to do server side rendering as IHM is a single page application.
Server side rendering is a huge effort for this  project unfortunately...
Also there's a need for people to use these links in blogs and other places for Google to actually show it in the search results, which I don't think is happening a lot, but this is only a guess...

Any help in this area would be greatly appreciated.
If you know SEO experts that can give us some pointers that could help too :-)

**Comment by nonZero** [comment]
@HarelM : I have added a small commit which sets the `<title>` of the page when viewing a POI.

1. Can you please check (and maybe send) some information regarding the site stats on [Google's Search Console](https://search.google.com/search-console)?  
2. Let's try to see if this changes anything :-)

(P.S. I did not check how the commit above affects the Mobile App.)

Udi

**Comment by HarelM** [comment]
Also checkout the following issue: #699

**Comment by HarelM** [comment]
What do you need from the search console?
There's a lot of information there...

**Comment by nonZero** [comment]
> What do you need from the search console?
> There's a lot of information there...

How many urls are found via the sitemap?

Is there any 'duplicate title' report?

Anything else related?

Udi.

**Comment by zstadler** [comment]
I've tried to see how Google shows the results from the site to better understand the end result.

When [searching the IHM POIs for "הר"](https://www.google.com/search?q=הר+site%3Aisraelhiking.osm.org.il%2Fpoi), Google shows only 8 out of the 28 results it has kept. The short descriptions of most of the results are identical:

![image](https://user-images.githubusercontent.com/1304610/167241944-7798d42a-843a-4993-989e-1db4a9003a63.png)

#### Note: The following is just guesses!

I suspect that using "בין אם אתם יוצאים..." when serving the search engines reduces the uniqueness and value of many POIs.
Google may also not see much value in including entries like "הר שקד" that do not have a special description or an image.

**Comment by nonZero** [comment]
@7f5f390d8b4640b5df628d426a25378bb6188466 adds descriptions to POIs (previously it was somewhat broken).

**Comment by HarelM** [comment]
@nonZero Can you point to where it was broken? The only thing that might have beed missing is the "external description" from what I see in the code you changed and the original code, but points that are not "external" (their url has OSM as the source and the OSM entity has a description) should have the description right.

**Comment by nonZero** [comment]
> @nonZero Can you point to where it was broken? The only thing that might have beed missing is the "external description" from what I see in the code you changed and the original code, but points that are not "external" (their url has OSM as the source and the OSM entity has a description) should have the description right.

Correct. Maybe also fallback when language querystring param wasn't specified.

**Comment by HarelM** [comment]
It might be that the external description was the case in most of the above results.
I see that google crawler can find the description if this is a "regular" point:
<img width="1452" alt="image" src="https://user-images.githubusercontent.com/3269297/167252142-6a87a020-d8dc-441b-b6f2-2704aca4aa7e.png">

**Comment by nonZero** [comment]
Regarding branding:
1. After some more thought -- it might be better to use BOTH Hebrew and
English in the title for the name of the site.  Your thoughts?
2. What would be the official translation to Hebrew? The all uses מפת
הטיולים הפתוחה.

**Comment by HarelM** [comment]
1. Besides being a mouth full, I think it's OK. IDK @zstadler?
2. Yes

We could consider removing מפת הטיולים הפתוחה all together as the brand name is IHM basically...

**Comment by HarelM** [comment]
It doesn't have to be a part of this PR/issue, but we decided that מפת הטיולים הפתוחה is no longer relevant for this project, as the current brand name is Israel Hiking Map and no one really uses the Hebrew "nickname".
