### ISSUE TITLE
Evaluate the "Simplify" algorithm when importing a route

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#173]
When a track/route is imported, it automatically gets a reduced set of ~20 "anchor" points that would be used for further routing. It looks like the reduction process may be improved if it would use the ```L.LineUtil.simplify(...)``` algorithm used in #165.

[This example](http://israelhiking.osm.org.il/#/?s=AWIV3rs821) shows 3 stages in applying trail-based routing on an imported route:
* Pink: The original (TWL) route
* Green: The route after applying "Hiking" routing. The 15 green points are the selected "anchor" points.
* Orange: Manually edited route to achieve the target 4wd route.

It looks like the "anchor" selection algorithm does not consider the "extremity" of the points along the original route. As a result, we can see sections where the original route was ignored when routing is applied. For example, [here](http://israelhiking.osm.org.il/#/?s=pKeYqqxX7P) and [here](http://israelhiking.osm.org.il/#/?s=thzZLgHyqT).

Clearly, not all differences between the target route and the automatic route are a result of the reduction mechanism because (a) The point selection of the original route may not be the best selection for defining the route, and (b) we don't true 4wd routing mode (yet).

**Comment by HarelM** [comment]
Implementation can be found here:
http://www.codeproject.com/Articles/18936/A-Csharp-Implementation-of-Douglas-Peucker-Line-Ap

**Comment by HarelM** [comment]
This was fun :-) read a few papers on line simplification algorithms.
Routeing is still an issue for 4wd vehicle as was written in issue #166.
Not planning to solve this here...

**Comment by zstadler** [comment]
The results are so much better!!

For your reference, attached is the original (zipped) twl file for the above example.
[בעקבות הלהl.zip](https://github.com/IsraelHikingMap/Site/files/260051/l.zip)
