### ISSUE TITLE
display "saved in cloud" name in private routes

### ISSUE THREAD

**Issue by Shemesh** [IsraelHikingMap/Site#1735]
## Feature request
when displaying or adding an item from "saved in cloud" it is added to private routes with some arbitrary name.
instead please give the private route the same name it have in the cloud

**Comment by HarelM** [comment]
A "cloude save" is a bundle of routes. Every route can be named as needed.
When converting a route back to be a private route the original name is used unless this name already exists, in this case a different name is given.
I suggest to rename your private routes before saving them to the could...

**Comment by Shemesh** [comment]
oh, cool! i didnt knew that.
