### ISSUE TITLE
working on a "saved in cloud"

### ISSUE THREAD

**Issue by Shemesh** [IsraelHikingMap/Site#1736]
## Feature request
working on a "saved in cloud" is somehow cumbersome and can be better...
my suggestion: think of it as working on a file...
- when opening from cloud display the name of the work in a visible location.
- let the user make any changes
- click on a visible button will update the "saved in cloud" that is currently opened.

when in that 'edit' state maybe show a mini toolbar with: work name, save button, share button etc.

**Comment by HarelM** [comment]
Easier said than done :-). There are many use cases that simply don't fall into this category.
The main usage is viewing the map, the second one is drawing a route and sharing it. Editing and updating an existing route is not even in the top 10... 
Making the experience around "files" and files editing (even if it's around online "files") is not aligned with our product and where some money is gained (offline maps).
While I understand this concept and I took a lot of ideas from Google sheets and Google docs, this is not the main purpose for this product.
