### ISSUE TITLE
Do not show a warning if there are no open routes

### ISSUE THREAD

**Issue by amiad** [IsraelHikingMap/Site#1739]
## What I expect to happen
When I open a track from the cloud and there is no other track open a warning should not be displayed.

## What really happened
The warning is displayed.

**Comment by HarelM** [comment]
תודה על הדיווח.
ננסה להוסיף את זה בגרסה הקרובה.
אם בא לך, אתה מוזמן לשלוח PR עם התיקון :-)

**Comment by amiad** [comment]
יש באג והתנאי הפוך. אם אין מסלולים אז מופיעה בקשת האישור ואם יש מסלולים פתוחים אז לא.
צריך להוסיף not לתנאי. נראה לי שככה:
`if (! this.selectedRouteService.areRoutesEmpty())`

**Comment by HarelM** [comment]
אני חושב שזה כבר לא רלוונטי לאחר התיקון האחרון.
בלי קשר, תוכל לשלוח קישור למיקום בקוד שאתה חושב שיש בו באג?

**Comment by amiad** [comment]
כן, הקוד השתנה אבל מצאתי את הבאג.
https://github.com/IsraelHikingMap/Site/blob/d8b43812266b7e9ac4e5d460c4015528a8d68ab7/IsraelHiking.Web/src/application/services/selected-route.service.ts#L75

צריך להיות
```
return this.routes.length == 0;
```

**Comment by HarelM** [comment]
Ahh, thanks!!

**Comment by HarelM** [comment]
I've just changed that.
I'm having a big issue with google now where I can't publish new versions which I have no idea how to solve.
I hope to be able to push a new version soon, but the problem with google is almost a month old now with no solution in sight...
