### ISSUE TITLE
Site slow down due to automatic tiles download

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#174]
Seems like someone is using an automatic script to download tiles which casues the site to be slow.

**Comment by HarelM** [comment]
The following article might help:
http://www.iis.net/learn/media/bit-rate-throttling/bit-rate-throttling-configuration-walkthrough
there is a section about jpg there that might be similar to our png issue.

**Comment by zstadler** [comment]
First, [IIS Media Services ](http://www.iis.net/learn/media/iis-media-services/iis-media-services-readme) must be installed for Bit Rate Throttling.

Some additional items, based on the above article:
* Many [64-bit downloads](http://www.iis.net/downloads?tabid=34&g=6&i=1641 ) of IIS extensions including:
  * Microsoft extensions such as:
    * [Bit Rate Throttling](http://www.iis.net/downloads/microsoft/bit-rate-throttling)
    * [Advanced Logging](http://www.iis.net/downloads/microsoft/advanced-logging)
    * [Dynamic IP Restrictions](http://www.iis.net/downloads/microsoft/dynamic-ip-restrictions) allows temporary and permanent IP-based blocking.
    * [FastCGI for IIS](http://www.iis.net/downloads/microsoft/fastcgi-for-iis)
 * Community contributed extensions, such as:
    * [Web Performance Monitor](http://www.iis.net/downloads/community/2007/01/web-performance-monitor)
    * [Ultimate Directory Listing Module for IIS6 and IIS7](http://www.iis.net/downloads/community/2007/02/ultimate-directory-listing-module-for-iis6-and-iis7)
* Walkthroughs
  * [Bit Rate Throttling Configuration Walkthrough](http://www.iis.net/learn/media/bit-rate-throttling/bit-rate-throttling-configuration-walkthrough). In particular:
    * [Configure throttling at the virtual directory level](http://www.iis.net/learn/media/bit-rate-throttling/bit-rate-throttling-configuration-walkthrough#directory) allows setting of Bit Rate Throttling for the different Tiles directory and potentially add stricter limitations on zoom level 16
  * [Bit Rate Throttling Extensibility Walkthrough](http://www.iis.net/learn/media/bit-rate-throttling/bit-rate-throttling-extensibility-walkthrough)

We need to verify that Bit Rate Throttling indeed affects multiple concurrent connections, as happens in tile downloads, or just individual connections that retrieve large contents.

**Comment by HarelM** [comment]
I don't think this issue is still relevant, at least I couldn't feel slowness lately.
Let's reopen/open a new issue if this returns.
