### ISSUE TITLE
Cannot select a segment of the height graph

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1767]
## What I expect to happen
Be able to select a segment of the height graph

## What really happened
The selection works at the site, but not in the app

**Comment by HarelM** [comment]
This is not only in the app but in mobile devices running a browser as well.
The root cause of this is that the API changed but the migration documentation was not clear enough, and I only tested it on the browser.
Relevant issue:
https://github.com/d3/d3-selection/issues/245

**Comment by HarelM** [comment]
There's still a weird offset on mobile for some reason...

**Comment by HarelM** [comment]
Also related to this: https://github.com/d3/d3-selection/issues/270
