### ISSUE TITLE
Update OSM trace visibility

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1769]
## Feature

Issue #1663 did not handle previously-uploaded traces.

## What I expect to happen
Timestamps of old traces should also be available via the API

## What really happened
The timestamps of traces uploaded as "Private" prior to #1663 are not available via the API.

## Proposed solution
When the list of traces for "My Traces" is downloaded, any trace with an old OSM option will be updated to the new OSM option, following the table used in #1663:

| IHM term | Old OSM option | New OSM option | Note |
|---|---|---|---|
| Private | Private | Trackable | Default |
| Public | Public | Identifiable | |

**Comment by HarelM** [comment]
This needs to be tested obviously... I didn't test it yet...
