### ISSUE TITLE
Streamline UX for recording without following the GPS location

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1774]
## What I expect to happen
If during recording the GPS tracking is turned off, the GPS should be inactive when the recording is stopped, as was until recently.

## What really happened
After the recording is stopped, the GPS is active and the location cursor is shown although the GPS tracking and the GPS recording buttons are inactive.

## What I did that caused the issue - step by step
1. Activate the GPS tracking
2. Wait for GPS fix
3. Activate GPS recording
4. Deactivate GPS tracking
5. Finish the GPS recording

## My environment
* Operating System and version: Android 11
* App version: 9.14.86

## Things I think the developers should know, images, links etc.

<img width="33%" src="https://user-images.githubusercontent.com/1304610/197847282-29c250cf-5b27-4dca-bc67-5eac5076c17f.png"/>

**Comment by HarelM** [comment]
The expect behavior doesn't make a reasonable UX.
I also don't think this was introduced recently as active gos state was not altered during latest changes.
In any case, the possible UX from my point of view are:
1. Raise a warning to the user that GPS can't be deactivated during a recording (preferred from my point of view)
2. Do nothing and don't turn off GPS (ignore the click)
3. Same as clicking the stop recording button + stop GPS button right afterwards.

@zstadler please let me know which of the above 3 seems the best UX from your point of view.

**Comment by zstadler** [comment]
Let's discuss it on the phone

**Comment by zstadler** [comment]
#### Discussion summary:
Some parts of the code did not consider the possibility of recording without following the GPS location.

When in this state and the recording is stopped, the "Follow GPS position" button should be turned on. Recentering the map on the current GPS position can be done in either way:
- The map should be centered immediately on the GPS position.
- The map should show the "recenter" button and its timer activated, as if the map was just moved while "Follow GPS position" is active.

We also learned that currently, if the map is moved when recording without following, the "recenter" button is shown, but clicking it has no effect.

Possible resolutions with equal priority:
- Avoid showing the "recenter" button if the map is moved when not following the GPS position.
- Recenter the map to the GPS position. Do not resume following the GPS position.

**Comment by zstadler** [comment]
I [wrote](#issue-1422864226) incorrectly:
> ... as was until recently

I've checked a very old version and it also showed the GPS cursor after the scenario at hand.

**Comment by HarelM** [comment]
Seems like there are more weird stuff there, like the fact that the border is removed when not following even though the GPS is on.
While when panning the border is left but the icon turns from green to black.
I'm keeping the second behavior for both types: "not following" (while recording) and after panning the map to align the UX.
When recording and "not following" the center me button will not be presented.
The only way to get to "not following" is record and press the GPS button.
When recording is completed the "not following" will be disabled.

I'll check in the code and close this issue, in case one of the above scenarios will not be solved we can reopen.
