### ISSUE TITLE
Route direction

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#178]
Add either in route settings or always the ability to see the route direction.
Maybe the following plug-in can help:
https://github.com/bbecquet/Leaflet.PolylineDecorator

**Comment by zstadler** [comment]
The [Leaflet Ant Path](https://github.com/rubenspgcavalcante/leaflet-ant-path#leaflet-ant-path) can create an animated "ant" movement along the path and avoid issues where arrows are covering nearby objects or seems to be outside of the route:

> <img width="41" alt="2016-08-07 18_12_39-israel hiking map" src="https://cloud.githubusercontent.com/assets/1304610/17463252/ae654038-5cca-11e6-88a4-0bd27585acdc.png">

[A demo](http://rubenspgcavalcante.github.io/leaflet-ant-path/) is also available where several parameters can be changed. I suggest we use the following options settings:

- Use a 2000 (ms) **delay** to create slow movement of the ants.
-  Use "transparent" as the **color** and assign the required track color to **pulseColor**. This will enable seeing what's under the route and show "return on the same path" sections of the route.
