### ISSUE TITLE
Always show the first picture when clicking a POI

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1781]
## What I expect to happen
Always see the first picture when clicking on a different POI.

## What really happened
Sometimes the picture of the POI is not shown and you have to scroll the pictures back in order to to see it.

## What I did that caused the issue - step by step
- Show the POI layer
- Open https://israelhiking.osm.org.il/poi/OSM/node_8930610917
- Scroll to the second picture
- Click on the other nearby border stone
- See the info for the second POI: no picture is shown
- Scroll back to the first picture of the POI

## My environment
* Operating System and version:  Windows 11
* Web Browser and version: Firefox 106.0.2

## Things I think the developers should know, images, links etc.

<img width="100%" src="https://user-images.githubusercontent.com/1304610/199657350-3ccefd1e-ae11-44cd-b5e9-be74c7d7e047.png"/>

**Comment by HarelM** [comment]
Nice catch! probably related to the image index not being initialized.
I'm also missing the number of images i.e. 1/2 in case of multiple images, I'll see if I can solve both as part of this issue.
