### ISSUE TITLE
Add IIS log analysis

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#179]

**Comment by HarelM** [comment]
The first match on google was [WebLog Expert](http://www.weblogexpert.com/download.htm)
I installed the lite version on the server.
I have added a profile for the website and configured it to analyze the current month (*1610*.log).
It takes some time to run and the results appear in the browser.
Let's see if this does what we need, maybe we'll be able to run it once a month to see the statistics.

**Comment by HarelM** [comment]
Created a folder under israelhiking.osm.org.il called reports to store the report results after every time we run the report generation.
The report generation process takes about 20-30 minutes.
