### ISSUE TITLE
Merge by mtb:name ways like we do for other POIs

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1797]
## Feature
As a user who looks at the map for cycling routes that has `mtb:name`, I see some places where the merge could've created a better POI, for example the גהינום which has multiple appearances although they could've been merged to a single one.
https://israelhiking.osm.org.il/map/17.00/31.9378/34.9648
cc @tsurha

## Things I think the developers should know, images, links etc.
The merge algorithm is only working currently on the `name` tag for OSM to OSM merges which is what causes this issue.
This also means that streams that have different name tag due to passing in places where the name is in Arabic will also suffer from the same problem.

There was also the conversation about which segment to use when storing the data in OSM for a merged entity (which should be the "first" entity that we add the other info from other entities. I'm not sure I remember what we decided should be the simplest approach though. It might be an opportunity to fix this as well since I'm touching this code anyway. @zstadler do you remember?
Also worth noting that, I already looked at the code and I'm not sure I have a solution to this problem that will perform good enough.

**Comment by HarelM** [comment]
After merge the following are the search results and the POIs (two were not merged as I they are not close enough - they need to be less than 100m apart and they are around 200m apart):
![image](https://user-images.githubusercontent.com/3269297/202928249-daddc9cb-6e50-40e5-aa30-618119133281.png)
Changing the names of the other ways will also get them merged (i.e. גהינום 1,2).

**Comment by Tsurha** [comment]
Thanks for looking at it as these are currently cluttering the map.  Notes:
* Hope/assume we are talking about lines (routes) not points as the name POI may suggest. 
* I think points and routes should not merge together. So in the above picture rather leave the table as a separate point and merge just the singletrack.  
* Being an MTB enhancement, 100 meters is too small a criteria. With routes I suggest increasing it. 300m maybe.
* Adding screen example. But there are many more: 

![Screenshot_20221112_222807_Israel Hiking Map](https://user-images.githubusercontent.com/49042192/203040435-604462b6-8225-4a7f-91c2-a29e547c2c25.jpg)

**Comment by HarelM** [comment]
With the new code it looks better, but not perfect:
<img width="1574" alt="image" src="https://user-images.githubusercontent.com/3269297/203126917-dff6007d-969e-4a10-b042-fe7a08481ad7.png">

**Comment by HarelM** [comment]
As a side note, we use 100 meters because we have entities that shouldn't be merged that are close, an example for that is the following place:
https://israelhiking.osm.org.il/map/18.14/31.8158/35.1370 - אבן גבול
which are ~200 meters apart.
If you think the single should continue, I suggest to either add mtb:name to the places that are connecting these singles (assuming it's correct, I honestly don't know) or creating a relation to group them.

**Comment by Tsurha** [comment]
Once the new code is in production, it would be interesting to see what happens here https://israelhiking.osm.org.il/map/15.82/32.8652/35.2459
As this picture is too much...
![image](https://user-images.githubusercontent.com/49042192/203578801-69abb2b5-4b24-40ea-9680-792f233e9651.png)
