### ISSUE TITLE
Missing lwn trails as part of the POI hiking layer

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1800]
## What I expect to happen
I would expect for example שביל הדסה to be available in the POIs layer as it is a relation in OSM with a name.

## What really happened
It is only available in the search but not as a POI

## What I did that caused the issue - step by step
1. Search for שביל הדסה
2. Select the first results
3. or surf to https://israelhiking.osm.org.il/poi/OSM/relation_6436605?language=he

## My environment
* Operating System and version: Any
* Web Browser and version: Any

## Things I think the developers should know, images, links etc.
This is related to #546 where these trails were removed.
@zstadler please update on your findings before we remove the code to change their category.
Relevant code is here, removing it should be fairly simple I believe:
https://github.com/IsraelHikingMap/Site/blob/8646dbc29fd1daf962c3a711207942a912402313/IsraelHiking.API/Executors/OsmGeoJsonPreprocessorExecutor.cs#L123

**Comment by zstadler** [comment]
Overall, the vast majority of `network=lwn` relations with a `name` tag had appropriate names.
I have removed a 7 trail names with names like "KKL red/blue/black" and "שביל מקשר צהוב".
I think we're good for implementing this enhancement.
