### ISSUE TITLE
point-to-point routing cannot be changed

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1804]
## What I expect to happen
After finding a point-to-point route I can change the destination and get a route to the new destination.

## What really happened
The route does not change.

## What I did that caused the issue - step by step
1. Create a 4wd route from "חניון שער אורון, מועצה אזורית רמת נגב" to "חניון לילה נחל חווה תחתון, מועצה אזורית הערבה התיכונה"
   
   ![image](https://user-images.githubusercontent.com/1304610/204864053-08d2f781-998d-43ad-861d-3d4e3169a655.png)
2. Change the destination to "חניון לילה הר ההר, מועצה אזורית הערבה התיכונה" and click the left arrow
3. The pop-up shows the new end point, but the route is unchanged
   
   ![image](https://user-images.githubusercontent.com/1304610/204865894-280a5a34-3a66-4831-932d-e567bf27b1a4.png)

**Comment by HarelM** [comment]
I've changed some things that are not related to this feature as part of the fix.
There was a use of `RouteData` which has segments and in most cases the need was just for the lat-lng array and not all the extra data that was returned with the segments.
I did a big refactoring which touches a lot of places in the code which needs to be tested before a version can be released:
1. This bug
2. Adding a route from it
3. Adding a route from public POI
4. Navigate here feature
5. Recording (when it ends)
6. Route planning
7. Loading of a gpx file from the device and/or while offline

I think these are most of the things.
