### ISSUE TITLE
When clicking the +, create a single route out of same mtb:name grouped segments 

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1809]
## What I expect to happen
Several nearby segments are nicely grouped into one icon as they have the same mtb:name. Users should now be allowed to click the + and have a single route created for them.

## What really happened
Several routes are create, per their OSM segments as shown here: 

![image](https://user-images.githubusercontent.com/49042192/205460718-a7af1153-a405-42aa-8329-c259c5186c80.png)

The good news is that when the icon is selected, a single blue line is presents as shown here: 

![image](https://user-images.githubusercontent.com/49042192/205460694-46e995f7-bb83-4cbb-9e41-b45305ce6d9a.png)

## What I did that caused the issue - step by step
1. Selected Reim Singletrack or clicked its map icon or selected this link: https://israelhiking.osm.org.il/poi/OSM/way_812580711?language=en
2. Clicked the + to create a private route.

## Things I think the developers should know, images, links etc.
The new grouping mechanism reduces the number of icons nicely!

**Comment by HarelM** [comment]
Why not simply create a relation for it and avoid all these hacks? The merge algorithm is merging ways, but if all that exist in OSM are multiple ways, which way should receive the description and the image? The first? The last? Arbitrary? I think better mapping should be applied in this case...
I'm good with the fact that converting the public route to a private route indicate the mapping problem.

**Comment by Tsurha** [comment]
I just appreciated the grouping and though it was good. Then since the blue line was presented so nicely, its seemed a good idea to allow it as a private route. If not, nevermind.
Its a good point re which way should receive the description and the image. 
I wonder where did these mtb:name tags came from. Is it a from some other mapping renderer program? In such case we can not expect them to create a relation so it works better in IHM.

**Comment by HarelM** [comment]
Seeing history is fairly easy :-)
https://www.openstreetmap.org/way/812580711/history
You can click on the OSM icon when opening the POI in IHM site
Then click "Show History" in OSM to see what happened to this way.
The `mtb:name` was a migration we did to move the names of the ways (that are only related to bike routes) from the "main" name to only "mtb" (you can see it in the history, about 2 years ago).
The original name was added by users just like you and me :-)
In any case, I'll be closing this issue for now, we can always reopen it in the future if we can't think this should be improved by the site code and not by "better" mapping.

**Comment by Tsurha** [comment]
Right now even the unified blue line does not show.  I thought that should work so when converting the public route to a private route we can see the mapping problem, and maybe fix it.  Have a look:
https://israelhiking.osm.org.il/poi/OSM/way_812580711?language=he

**Comment by HarelM** [comment]
Can you elaborate on the changes you made, if any?

**Comment by Tsurha** [comment]
I have straightened a part here:
https://www.openstreetmap.org/edit#map=18/31.36213/34.46566

![image](https://user-images.githubusercontent.com/49042192/205617194-251faebb-f9be-4ba1-9d2b-5ad62009af39.png)



The segments that were grouped in the past are all still tagged mtb:name:he=סינגל רעים. Now they arn't.
