### ISSUE TITLE
Elastic search - the "מצדה" historic place is not found

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#181]
When searching for "מצדה" only one result actually has the "מצדה" string while the historic place and many street named "מצדה" are not included:

<img width="171" alt="2016-06-22 09_37_57-israel hiking map" src="https://cloud.githubusercontent.com/assets/1304610/16256885/b63e1492-385d-11e6-8281-e1690430e353.png">

For reference, see the list from [Nominatim](http://nominatim.openstreetmap.org/search.php?q=%D7%9E%D7%A6%D7%93%D7%94&polygon=1&viewbox=&accept-language=he-il).

**Comment by HarelM** [comment]
historic=archaeological_site is not boosted up in our search results.
searching for גן לאומי מצדה does yield the correct results.
I'll add it to:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.API/Services/GeoJsonFeatureHelper.cs
