### ISSUE TITLE
Remove flexbox-layout due to deprecation

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1810]
Flexbox was in beta and now discontinued. There's a need to remove it before continuing to update other libraries such as angular. 

https://github.com/angular/flex-layout/issues/1426#issuecomment-1302184078

**Comment by HarelM** [comment]
Relevant article:
https://levelup.gitconnected.com/angular-upgrade-26d331837012

**Comment by HarelM** [comment]
As an initial step for this upgrade I think the removal of flexbox is needed.
This is a first step towards Angular 15.
The following shows an initial guide on how to do that:
https://github.com/angular/flex-layout/issues/1426#issuecomment-1302184078

**Comment by HarelM** [comment]
@DuncanFaulkner thanks for this! Truly appreciated!
Having said that, reading what the Angular team is writing I think I should align with industry standard, which is using classes for styling.
I'll try to convert a screen at a time since I can keep flexbox while moving to tailwind. Once all the flexbox detectives are removed I can remove this dependency.
My app isn't that big and I really need to be better at CSS, so this is an opportunity.

**Comment by DuncanFaulkner** [comment]
@HarelM 

I fully understand, I just wanted to let you know that the library will be continuing so there's no rush to convert if you didn't want to or have the time to.
