### ISSUE TITLE
Remove IBT source

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1811]
## Introduction
The old IBT Yahel-Ketora route was changed.  It is now a combination of the north part of the old Bulbusim singletrack and the Ketora ascend that was always a part of Yahel-Ketora.  This change is not yet reflected in IBT's site but was announced in IBT's facebook page.  It has become this winter's new and exciting destination.
I have edited the relevant OSM relations to reflect that. Now two relations represent IBT's Yahel-Ketora segement.

## Bug
Changing the OSM relation is not enough for editing an IBT segment. 
Currently IBT routes are a join of an OSM relation and the spreadsheet in https://docs.google.com/spreadsheets/d/1nfLObizKqg7v78ELC313SGIk8Tw5t1WNE8o5twATvvs/edit#gid=1454906510

Line 5 of the IBT spreadsheet is now not correct but is still presented in
https://israelhiking.osm.org.il/poi/IBT/5?language=he

![image](https://user-images.githubusercontent.com/49042192/206385933-cec35ea8-924c-4096-ae71-7716f50f0ea3.png)

## What I expect to happen
That the following link will not be a route
https://israelhiking.osm.org.il/poi/IBT/5?language=he

## What really happened
Its still presented

## What I did that caused the issue - step by step
I deleted the OSM relation that was used here: https://israelhiking.osm.org.il/poi/IBT/5?language=he
I have split the old Bulbusim to two:

1. https://israelhiking.osm.org.il/poi/OSM/relation_12468443?language=he
2. https://israelhiking.osm.org.il/poi/OSM/relation_14981013?language=he

I have shortened the old Yahel-Ketora to become just Ketora Ascend, as the boring part along route 90 is not part of IBT anymore: https://israelhiking.osm.org.il/poi/OSM/relation_4242901?language=he

I have rerouted the whole IBT relation to be on the new route: https://israelhiking.osm.org.il/poi/OSM/relation_6639060?language=he

**Comment by HarelM** [comment]
I guess the problem here is with the name.
The merge algorithm is doing the merge by name, and those routes do not have the same name.
I suggest asking the IBT folks to update their site, later on we can update the sheets to reflect that, or we can simply do the same as what we did with KKL, your call.

**Comment by HarelM** [comment]
No problem, I'll add the icon like I did for KKL.
Let me know when you are done editing the OSM relations so I can remove the IBT source.

**Comment by Tsurha** [comment]
Done adding the info to ISM.  No need for the IBT spreadsheet anymore. It will be easier for me to QA it after its removal.  
Note that the new website icon is not clear. The one you manually added a while ago is nicer.

![New and Old Icons](https://user-images.githubusercontent.com/49042192/209442301-f6651540-23e0-4d8a-b20b-73467258df3b.PNG)

**Comment by HarelM** [comment]
Please check the status tomorrow morning. Should be fixed.

**Comment by Tsurha** [comment]
Looks good.

If someone asks, most IBT sections are represented by a single relation. Some however are split to 2 relations. This is due to history reasons when one was built and only later another. It's easy to concatenate them in IHM if needed.

**Comment by HarelM** [comment]
Thanks!!
