### ISSUE TITLE
Improve links logos

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1812]
## Feature
As a user that opens a POI and looks at the links, if there's more than one link, it's almost impossible to know where the link will lead (assuming it's not wikipedia, OSM, etc).
According to the following article there is an elegant solution for this - use google search icons:
https://dev.to/derlin/get-favicons-from-any-website-using-a-hidden-google-api-3p1e
I've tested the other stuff mentioned there and they are not giving good results unfortunately.

Thanks @tsurha for the idea!

**Comment by HarelM** [comment]
@tsurha this is now deployed in the site (not the app).
You can see it here for example:
https://israelhiking.osm.org.il/poi/OSM/node_4466681520?language=he

**Comment by Tsurha** [comment]
Cute. Looks good!
