### ISSUE TITLE
Improve performance for long recordings

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1820]
### What is the problem this feature will solve?

When there's a long route that is being recorded the performance of the app degradates, this can be solved my improving the performance.

### What is the feature you are proposing to solve the problem?

Split the recorded route to smaller pieces to avoid heavy processing by the app

### What alternatives have you considered or tried?

Stopping and starting a new recording every now and then

### Additional information

The app is using geojson to present the current recording.
This geojson gets updated every new point that arrives (around once every second).
This update sends all the data to a worker thread and split the geojson into tiles to be presented later.
When the recording has thousands of points this process becomes a bottle neck.
In order to improve performance, it might be possible to split the recording so that every let's say 5000 points a new segment is created and thus only this segment is part of the processing, and this should allow better performance.

**Comment by HarelM** [comment]
I've set the number of points to 100, around 2 minutes.
Once this is tested I think the number should be around 3000 or 10000, I don't think it matters much, what I had in mind is that for "not-so-long" recording (up to 3 hours - ~10000 points) the mechanism will be similar to what it is today - a single source and this will only kick in for longer routes.
The reasoning for that is that I don't have a good way to measure the performance and I'm not 100% sure the code I wrote is better, I hope it is and that our testing will raise issues sooner than later.
We can always change the number later on.

**Comment by HarelM** [comment]
Last commit created recording "gaps" in the visualization... Need to fix it.

**Comment by zstadler** [comment]
It looks like gaps are created when the app is brought to the foreground and returned to the background.

![image](https://user-images.githubusercontent.com/1304610/216828777-b5289a44-4257-440b-973b-0cd5b986fad9.png)

**Comment by HarelM** [comment]
It seems that the current solution causes some blinking of the recording line.
I believe this is due to the fact that the source is removed and added for each new point that arrives (for the last segment of the line only).
To fix this there's a need to keep the last segment separately and only change it's data to avoid adding and removing the source from the map.
This will cause blinking, but only when splitting a route (every 1 hour or 3 hours as mentioned above which is negligible) 
I don't see a way to avoid blinking as a whole due to the fact that the line needs to be broken, and these breaks will cause blinking using the current UI infrastructure.
