### ISSUE TITLE
Preserve latest state of hidden/visible routes

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1822]
### What is the problem this feature will solve?

Currently when reopening the app, or a new browser tab, all the suggested route types are visible or none at all. This depends on the last state of all suggested routes. A user who is interested in hiking only / cycling only / 4x4 only, has to turn off the visibility of the types he is not interested in.  When reopening a tab, refreshing it or reopening the app, he has to do so again.

Example, 
I would like to only see cycling routes as shown:
![1 type](https://user-images.githubusercontent.com/49042192/209955422-6dac66a0-6592-4944-a8d0-c38fe8591554.PNG)

When coming back to it, I get all three:
![3 types](https://user-images.githubusercontent.com/49042192/209955596-fb5f67c6-7201-443e-9c33-45aaaf6c5523.PNG)

### What is the feature you are proposing to solve the problem?

Preserve latest state of hidden/visible routes, per type. In the above example, keep cycling only.

### What alternatives have you considered or tried?

Manually going back to Routes, Maps, and Overlays, and adjusting as needed. Time and time again.

**Comment by HarelM** [comment]
Thanks for taking the time to report this!
This is a bug as I believe this used to work... I wonder when I broke it.
Nevertheless, I'll fix it shortly.

**Comment by HarelM** [comment]
This is working in the app which uses the sabe code, very strange.
This issue exists in both mobile and desktop browser, some parts of the state get deleted, I'm not sure why though :-(

**Comment by Tsurha** [comment]
When I just select cycling routes, close the app, reopen, I see all three.
Wish I could help you with the code...

**Comment by HarelM** [comment]
Nope, my mistake, it doesn't work in the app as well.
This was caused by a bug I introduced while fixing this issue: #1789
