### ISSUE TITLE
Add scrolling to list of clustered POIs

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1832]
### What is the problem this feature will solve?

When clicking on the icon a large cluster of POIs, only 7 POIs are accessible.

### What is the feature you are proposing to solve the problem?

Add a scroll option if the cluster is bigger than 7 items

### What alternatives have you considered or tried?

- Zoom-in and click the multiple smaller POI clusters
- If applicable, hide irrelevant POI and trail categories

### Additional information

For example:
1. Restore the default of showing all POIs and trails
2. Open the MTB map at https://israelhiking.osm.org.il/map/12.90/29.7610/34.9603
3. In an effort to identify the trail of the yellow route, click the "23" cluster
4. Only 7 of the 23 POIs are shown
   ![image](https://user-images.githubusercontent.com/1304610/211493016-ecc1d387-7570-4d04-aa03-ed5195f2c4cc.png)

**Comment by HarelM** [comment]
I don't think scrolling is a good UX.
I don't mind adding a "zoom in for more" text at the bottom, but presenting only 7 is by design, not by mistake.

**Comment by zstadler** [comment]
OK. This is just another topic were we have different views.
