### ISSUE TITLE
Consolidate logging configuration to a single file

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1835]
### What is the problem this feature will solve?

There are two places where logging are configured nlog file and appsettings file. It should be in a single file.
See here:
https://github.com/NLog/NLog.Extensions.Logging/wiki/NLog-configuration-with-appsettings.json
Also there's a need to remove debug logging in production but keep it when developing.

### What is the feature you are proposing to solve the problem?

See above

### What alternatives have you considered or tried?

Mess around with the configuration to understand which one wins...

### Additional information

Related to this issue:
https://github.com/NLog/NLog/issues/3731

**Comment by zstadler** [comment]
Production settings are also partially  configured using environment variables in the Docker `.env` file:
```
Logging__Console__LogLevel__Default=Critical
```

**Comment by HarelM** [comment]
I'll remove console logging from the configuration in production if that's OK with you.
