### ISSUE TITLE
Let the user know how to disable tracking when planning a route

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1843]
### What is the problem this feature will solve?

When planning a route and GPS tracking is on, the GPS will return to the center of the screen after a time out.
A lot of users are reporting that they don't know how to solve this issues.

### What is the feature you are proposing to solve the problem?

I propose to add a toast after the GPS is centered and the planning is enabled to let the user know that he can either disable the GPS or stop editing.
Text:
העקיבה מופעלת בזמן עריכה, לטובת ביטול מרכוז המפה למיקום הנוכחי יש ללחוץ בפינה השמאלית עליונה על הכוונת
GPS tracking is enabled while editing, in order to avoid map centering to current location please click the cross on the top left corner

### What alternatives have you considered or tried?

Couldn't think of a better solution to this, this question keeps being asked.

**Comment by zstadler** [comment]
Alternatively, we can think of conditions for disabling the recentering timeout.

For example:
- Disable the recentering timeout if either the pencil or POI button are active. 
- Disable the pencil and POI buttons when the map is re-centered in any of the currently available scenarios.

**Comment by HarelM** [comment]
The first options to disable recentering suffers from the probability that the user "forget" to exit edit mode.
Editing should be possible when tracking is on, I use it a lot while in a route and I want to get an ETA, I quickly plan a route through were I'm currently walking.
Let's start with a simple toast and see if people continue to find this confusing.

**Comment by zstadler** [comment]
> The first options to disable recentering suffers from the probability that the user "forget" to exit edit mode. Editing should be possible when tracking is on, I use it a lot while in a route and I want to get an ETA, I quickly plan a route through were I'm currently walking. Let's start with a simple toast and see if people continue to find this confusing.

There was nothing in my proposal that would disable recentering. Only the **automatic** recentering was proposed to be disabled. The user could still click on the "recenter" button or the GPS button, just like in the first 20 seconds of the timeout.
