### ISSUE TITLE
Keep edit mode when switching between private routes

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1844]
### What is the problem this feature will solve?

A common use when creating a route, is to have it split to several routes and then joining. For example when going back and forth on the same path.  
Currently when editing a part of the route and moving to editing another, the editing state is turned off.  

I am working on editing the red. This is the initial state:
![image](https://user-images.githubusercontent.com/49042192/214802342-874f139b-15de-46f7-9c11-9497b735c075.png)

Just moving to another part, turns the editing state off, into viewing state, which is confusing:
![image](https://user-images.githubusercontent.com/49042192/214802499-8bac328d-4e94-435c-8a1d-6edfc06dfbd3.png)

### What is the feature you are proposing to solve the problem?

When moving to the blue, I would rather keeping the editing state on.  So without further user operation, it would show this:
![image](https://user-images.githubusercontent.com/49042192/214803368-5159f39c-f834-4b89-91af-388a2ed97d05.png)

### What alternatives have you considered or tried?

The current UI does work. To me Its just a bit confusing.

### Additional information

Let me know if its worth our while in your view.
Maybe there are other considerations that you think we should have.  I'd be happy to do more thinking and designing the behavior as needed.

**Comment by HarelM** [comment]
I feel like we already had this conversation... 
Might be somewhat covered in this comment, not sure though:
https://github.com/IsraelHikingMap/Site/issues/1550#issuecomment-896950061
https://docs.google.com/presentation/d/1q-3q-8085ueVfpdIjeZGa_M7j786HEGf5ypS6Yk8A4E/edit#slide=id.ge44ea22457_0_0

It might be that this wasn't an intended side effect of the above feature implementation.
Please read the other issue and let me know what you think.
I don't think this is a lot of work either way.

**Comment by HarelM** [comment]
@Tsurha any comments regarding what I wrote above?

**Comment by Tsurha** [comment]
Indeed this is continues the discussion we had then.  After extensive use of the current implementation for ~1.5Y that is left as a point that I feel should improve.

The way I see it / the concept:
- When a user selects a route, its because he is interested in it.  Either just to view it or to edit it . 
- I'd like to expand the concept of "edit mode / view mode" from just a route's state to the user's current activity and mindset.  This is where my need to improve comes from.  I was editing and working. Then when trying to work on another part of the route, the SW suddenly moves to view mode. 

This means / UI implementation:
- When in view mode, and selecting a different route, change that route to view mode too. This is regardless if the newly selected route was hidden or visible earlier. 
- When in edit mode, and moving to a different route, change that route to edit mode. This is regardless if the newly selected route was hidden or visible before.  Change the previously edited route to just visible.
- Only one route, the currently selected route, can be in edit mode.  Several other routes can be visible and several can be hidden.

Just thinking:
- Maybe cycling routes tend to be longer than walking and this is more of a need in the cycling use case.

**Comment by HarelM** [comment]
Bottom line, the change is to keep the editing mode when switching a route, right? All the rest should be the same?
I.e: when in edit mode and clicking a different route, stop edit mode for the current and start for the other,
When not in edit mode don't start editing?

**Comment by Tsurha** [comment]
Exactly
