### ISSUE TITLE
Potential improvement in daily-update

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1848]
### What is the problem this feature will solve?

During the daily update all pictures are checked if their source has a new version. This process takes about 45 minutes.

### What is the feature you are proposing to solve the problem?

Improve the performance of the daily update and reduce the processing in IHM and potentially in Wikimedia by using the `etag` response header to enable receiving `304 Not Modified` status codes from Wikimedia rather than comparing file length on our side.

- Store the received `etag` response value with each picture. 
- When refreshing a pictures, send an `If-None-Match` request header with the value of the previous `etag` received. 
- If the picture on the server has not changed, the server will respond with a "304 Not Modified" status code, indicating that we can use the currently stored image.

### What alternatives have you considered or tried?

The current mechanism requests the file length from Wikimedia and compares it with the on the length in IHM.
This mechanism 
- Requires additional processing at the IHM side, and potentially also at the Wikimedia side
- Is blind to content changes that do not change the length (probably very rare)

**Comment by HarelM** [comment]
I have experimented with the etag and the performance seems to be the same so there's no real added value in using it for performance and it's not worth the effort for the rare case of different file with the same size.
The following is the relevant code if I'll need it in the future:
```cs
        public async Task<bool> HasFileChanged(string url, string tag)
        {
            var client = _httpClientFactory.CreateClient();
            client.DefaultRequestHeaders.UserAgent.ParseAdd(Branding.USER_AGENT);
            var request = new HttpRequestMessage(HttpMethod.Head, url);
            if (!string.IsNullOrEmpty(tag))
            {
                request.Headers.TryAddWithoutValidation("If-None-Match" ,tag);    
            }
            var response = await client.SendAsync(request);
            return response.StatusCode != HttpStatusCode.NotModified;
        }
```

The following is the tests I ran 200 requests for file size, and 200 for etag, both run around 21 seconds:

```cs
        [TestMethod]
        //[Ignore]
        public void TestGateway_FileChanged()
        {
            var start = DateTime.Now;
            for (var i = 0; i < 200; i++)
            {
                var response = _gateway.GetFileSize("https://upload.wikimedia.org/wikipedia/commons/d/d5/Khan_al-Ahmar_school_building%2C_2015.jpg").Result;    
            }
            Console.WriteLine(DateTime.Now - start);
        }
        
        [TestMethod]
        //[Ignore]
        public void TestGateway_FileSize()
        {
            var start = DateTime.Now;
            for (var i = 0; i < 200; i++)
            {
                var response = _gateway.HasFileChanged("https://upload.wikimedia.org/wikipedia/commons/d/d5/Khan_al-Ahmar_school_building%2C_2015.jpg", 
                    "0dc84a37187927221a4d4da70ab51b8c").Result;
            }
            Console.WriteLine(DateTime.Now - start);
        }
```

Closing...
