### ISSUE TITLE
A route created using the search has no elevation data

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1849]
### What happened?

I've used the search to create a route between two coordinates and the resulting route had no elevation information

### What steps will reproduce the bug?

1. Use the search to create a hiking route from `29.587820908637198,34.884894480967176` to `29.587847654205163,34.89730155305108`
   
   ![image](https://user-images.githubusercontent.com/1304610/216106635-c5a765c9-dc78-46b7-8e21-9454b62823da.png)
2. Click the "+" button
3. Open the elevation graph
4. The elevation graph is empty
   
   ![image](https://user-images.githubusercontent.com/1304610/216107089-9e0ce080-0c07-4d18-9b6b-5ce0a135947b.png)

### What I expect to happen

A route created by IHM should have elevation information.

### Platform

- [ ] Israel Hiking Map app
- [X] Israel Hiking Map site in a browser

### OS Name and Version

Windows 11

### Browser Name and Version

Firefox 109.0

**Comment by zstadler** [comment]
This may explain the recent report from Ron.

To reproduce:
1. Use the search to find a hiking route from "חניון לילה הר יהורם" to "מצפה הר יהורם", similar to the original reproduction.
2. Create a route from the search result
3. Slightly move the start point of the route
4. Slightly move the finish point of the route
5. Slide the mouse along the elevation graph
6. See that the point on the map does not always follow the route
   ![image](https://user-images.githubusercontent.com/1304610/216109805-bbfd1353-70e3-42b1-b491-3e99ee916655.png)

**Comment by HarelM** [comment]
Seems like this was accidentally introduced as par of the fix of #1804 which included a simplification of the API when using routing, about 2 month ago.
