### ISSUE TITLE
Car/4WD does not pass through gate w/o any restrictions

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#185]
This is no appropriate for Israel where may villages have an entrance gate.

For example, the entry to Almagor - http://israelhiking.osm.org.il/#/?s=aUhQ0SBk9d

**Comment by HarelM** [comment]
I think we should better define gates before fixing this routing issue as some gates can't be driven through.
Also in this case I think there should be a routing issue so that you'll know there's a gate there that might be closed...
You can also switch to None-routing for this leg.
I don't think this bug should have high priority...

**Comment by zstadler** [comment]
The gates are well classified. A gate provides access unless it has an access restriction, such as access=no and motor_vehicle=no.

We also map the gates accordingly:
- Inaccessible gates are ![](https://github.com/IsraelHikingMap/Map/blob/master/Icons/SJJB/barrier_gate.n.32.png?raw=true) 
- Accessible gates are ![](https://github.com/IsraelHikingMap/Map/blob/master/Icons/SJJB/barrier_gate.glow.32.png?raw=true)

That's why I think this is a high priority issue.

**Comment by HarelM** [comment]
Let's see what the guys at GH answer first...

**Comment by karussell** [comment]
@zstadler why do you think it is 'well classified'. Do you have link to the wiki? I have interpreted the defaults as access=no, especially for gate

**Comment by HarelM** [comment]
One could argue that in order to prevent access you'll need to add a tag to the element restricting access otherwise there is no restriction. The wiki of both gate and access are not defining the default though.

**Comment by zstadler** [comment]
I don't see why a barrier=gate with no access tag would allow bicycle or foot access but not for cars. Unlike a cycle_barrier or a stile, there is nothing in a gate's structure that is specifically built to restrict or allow a certain type of access.

**Comment by zstadler** [comment]
See [new comment on **Routing through gates that don't have restrictions for car profile** graphhopper/graphhopper#754 ](https://github.com/graphhopper/graphhopper/issues/754#issuecomment-250953384)

**Comment by HarelM** [comment]
See relevant check-ins, pull request and forked repository.
