### ISSUE TITLE
Improve text and UX for expired subscription

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1858]
### What happened?

My offline subscription has finished.  I could still select offline:

![WhatsApp Image 2023-02-28 at 15 15 28](https://user-images.githubusercontent.com/49042192/222886227-358a8313-8108-409c-91ff-ee8625c8eb41.jpeg)

### What steps will reproduce the bug?

Find a user close to yearly renewal.  Remove the credit card from his google account.  Wait for the his subscription to expire.  I realize its cumbersome. Maybe you could simulate the situation.

### What I expect to happen

Not allow selection of the cloud icon.  
Present only a cloud icon without a crossed out line.  

### Platform

- [X] Israel Hiking Map app
- [ ] Israel Hiking Map site in a browser

### OS Name and Version

Android 13 on Samsung S22

**Comment by HarelM** [comment]
Thanks for opening this issue, can you please either attach here or send us by mail the log from your app (by using report an issue)? This will help us better see where the problem is.

**Comment by Tsurha** [comment]
email sent from app

**Comment by HarelM** [comment]
Actually, looking at the logs and at the state you sent in the screenshot, this is the expected behavior:
If you purchased in the past a subscription and downloaded the maps you can use them (if you didn't clean the app's data), this is what the cloud icon is for.
Since the subscription expired, you can't download a new version, in order to do so you'll need to renew the subscription by using the "buy" button.
While we may decide to change this behavior in the future, the current state of things are "working as designed".

**Comment by Tsurha** [comment]
Good point. I didn't realize I had offline, just a bit outdated. 
Now I also see that the current behavior is fine.  If someone bought it, it should still be his. Without updates.
Maybe the text should just change in this situation to something like:
<div dir="rtl">  
המפות ללא חיבור לרשת אינן מעודכנות. ניתן לרכוש עדכון.

But its really a remote case and you may not even bother about it.

**Comment by HarelM** [comment]
Actually, if someone purchased a subscription in the past I believe he has better chances to buy it again than someone who never purchased one.
Since this info is valid, I'll see if I can get the best of it and see how to place the right message in the right place.

**Comment by HarelM** [comment]
> המפות ללא חיבור לרשת אינן מעודכנות. ניתן לרכוש עדכון.

This is a bit too long for the button text, can you think of something shorter?

**Comment by Tsurha** [comment]
<div dir="rtl"> חידוש מנוי למפות לא מקוונות

**Comment by Tsurha** [comment]
BTW, currently the button does not look like a button, more like a header.  
With a shorter text it would be narrower than the screen and will be more button like.

**Comment by HarelM** [comment]
Yeah, I heard that too lately, I'll think how to solve this...

**Comment by Tsurha** [comment]
I'd like to add English.  Let me know if you are adding text above the button, or using the longer text.

**Comment by HarelM** [comment]
I'm not sure I like the text and button look. I'll think of a better way to present this.
There's also a need to add the ability to purchase from the main menu as well, or only there, I'm still not entirely sure, so the text might need to change accordingly, or be the same considering both options.
Bottom line, I need to try out a few things and see how they look, and according to that decide, if you would like to propose using paint or power point feel free to do so.

**Comment by Tsurha** [comment]
Looks good. 
Just please lets refine the text on them:
* רכישת מפות לצפיה ללא חיבור לרשת
* חידוש מנוי לעידכון מפות לא מקוונות
* Purchase offline maps
* Renew subscription of offline maps

**Comment by HarelM** [comment]
הטקסט לא מדוייק, לא רוכשים מפות, רוכשים מנוי. :-)
בכל מקרה, תמיד אפשר לשנות את הטקסט בעתיד, עיקר העניין פה מבחינתי הוא ההפרדה בין מצב שהיה מנוי ומפות הורדו למצב שלא היה מנוי או שאין מפות על המכשיר.

**Comment by HarelM** [comment]
אני רואה שכבר היום הוא לא מדוייק... נו טוב... שיהיה...

**Comment by Tsurha** [comment]
The button looks better.  However the text does not explain what subscription are we talking about.  
I would suggest חידוש מנוי למפות לא מקוונות

![Screenshot_20230330_222414_Israel Hiking Map](https://user-images.githubusercontent.com/49042192/229063809-4f64fb25-ba50-42ad-b4e4-ec9629ece2d6.jpg)
