### ISSUE TITLE
When a POI does not have a picture, a credit is still given according the last picture shown

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1859]
### What happened?

I looked at POIs and when one did not have a picture, a credit was still given:

![image](https://user-images.githubusercontent.com/49042192/222918456-be66e682-f706-4807-b812-346af3af7021.png)

### What steps will reproduce the bug?

1. Find a POI with a picture, note who uploaded it
2. Move to a another POI, without closing the description pane
3. If the next POI does not have a picture, the last credit is still presented 

### What I expect to happen

No picture should show no credit

### Platform

- [ ] Israel Hiking Map app
- [X] Israel Hiking Map site in a browser

### OS Name and Version

Win 10

### Browser Name and Version

Chrome

**Comment by HarelM** [comment]
Yes, I've noticed this too, thanks for taking the time to report this.
