### ISSUE TITLE
Circular route is hard to plan

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#186]
When your click on the starting point again the app tries to change it instead of navigate to it.

**Comment by valleyofdawn** [comment]
I suggest to adopt Strava's solution:
The cursor cahnges to a dragging mode, But if clicked and not dragged, the route continues to the indicated point.
https://www.strava.com/routes/new
Requires registration.

**Comment by HarelM** [comment]
Click on a route in our site will open an POI editor, I don't want to introduce another type of click.
Do you have any other idea besides adding a button in the route pop-up window?

**Comment by valleyofdawn** [comment]
Isn't it a double click for the POI editor?

**Comment by HarelM** [comment]
No, double click is for delete and I want to remove this behaviour

**Comment by valleyofdawn** [comment]
In many interfaces a long press would edit attributes. A short press could be to lengthen the route to this point.

**Comment by HarelM** [comment]
Long press is probably the least intuitive UX. I don't have a better solution though. probably one of those things that you'll need to work around as I don't see it as an important enough feature that is worth complicating the user interface and experience...
