### ISSUE TITLE
Improve background text when offline

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1861]
### What happened?

I did not understand what should I do, based on this text

![WhatsApp Image 2023-02-28 at 14 59 53](https://user-images.githubusercontent.com/49042192/222920461-14343863-eecb-4898-8abb-fc629a2ba4bf.jpeg)

### What steps will reproduce the bug?

1. Use a phone without offline maps
2. Disconnect the internet (both wifi and cellular)
3. Open the app

### What I expect to happen

I suggest using the following wording:

<div dir="rtl">
כשאין חיבור רשת, יש להשתמש במפות לצפיה ללא חיבור לרשת. מפעילים אותן מהתפריט הראשי, ואז מסלולים - מפות - שכבות. את המפות יש לרכוש מראש ולהורידן אל המכשיר, מומלץ בחיבור WiFi.

### Platform

- [X] Israel Hiking Map app
- [ ] Israel Hiking Map site in a browser

### OS Name and Version

Android 13 on Samsung S22

**Comment by HarelM** [comment]
There are a lot of situations not taken into account in this issue.
Having said that, I agree the text can be improved in this particular situation.

**Comment by HarelM** [comment]
Current texts, flows and parameters:
offlineAvailable = user has a valid subscription
lastModifiedDate = the modification date of the maps that were downloaded (none if they were never downloaded).
The first part of the text is static (אם אתם מצליחים לקרוא... up until the hamburger).
The second is dynamic, and probably can be improved, feel free to suggest how:
1. offlineAvailable is true and lastModifiedDate is something other than none:
אתם יכולים לאפשר את המפות הלא מקוונות בתנאי קליטה גרועים ע״י לחיצה על סמליל הענן ליד השכבה המתאימה.
2. offlineAvailable is true and lastModifiedDate is none:
המפות נרכשו אך עדיין לא הורדו, אנא הורידו אותן, כנראה לא עכשיו כי אין קליטה טובה...
3. offlineAvailable is false:
אם ברצונכם לראות מפות ללא חיבור לרשת יש לרכוש אותן ראשית...


Looking at all the above and the possibility that the maps were downloaded but there's no valid subscription the first clause is incorrect.
Having said all that, the text can be improved I guess...
The hanburger is creating a weird effect that is not needed I think so I guess regular text are in place here and not this weird separation of static and non static text.
@zstadler @Tsurha feel free to let me know what you think can work here instead.

**Comment by zstadler** [comment]
I think this is an excellent idea!

Here are my suggestions:

-  Opening the layers from the menu is applicable only in use-case 1. Therefore the static message should be shorter
<p dir="rtl">
אם אתם קוראים את זה, סימן שתנאי הקליטה גרועים.
<p>

- For use-case 1, the dynamic message would be

<p dir="rtl">

אתם יכולים להציג באופן קבוע את המפות הלא מקוונות<br>ע״י פתיחת התפריט הראשי מכפתור <img width="20px" src="https://user-images.githubusercontent.com/1304610/222972705-e704a81a-497c-44d4-9676-a6c20e0e150a.png"/><br>לחיצה על "מסלולים - מפות - שכבות"<br>ולחיצה על <image width="20px" src="https://user-images.githubusercontent.com/1304610/222974734-acf17091-84cf-4f1d-8330-470f3c83fb9f.png"/> ליד המפה המתאימה
<p>

- Use case 3 also requires network access:
<p dir="rtl">
    אם ברצונכם לראות מפות גם ללא חיבור לרשת, יש לרכוש אותן כשהקליטה תשתפר...
<p>

- Is it possible to hide the spinner when the text is shown and avoid this?
![image](https://user-images.githubusercontent.com/1304610/222973766-664e2470-d9a4-4250-9302-60db71bc4598.png)
Perhaps using a box with white background for the text

**Comment by Tsurha** [comment]
Its getting there.  I'm also for changing the static part.
BTW once its all set, English should also change accordingly. 
Just in general prefer shorter, to the point, wording. For example:

Static message:
תנאי הקליטה גרועים.
Use-case 1, dynamic message: 
ניתן לצפות במפות לא מקוונות ע״י פתיחת התפריט הראשי <המבורגר>, בחירת "מסלולים - מפות - שכבות" ולחיצה על <ענן> ליד המפה המתאימה.
Use-case 2, dynamic message: 
 כשהקליטה תשתפר יש להוריד לטלפון את המפות הלא מקוונות שרכשת.

Use case 3, dynamic message:
כשהקליטה תשתפר מומלץ לרכוש מפות לא מקוונות, ולהורידן לטלפון.

**Comment by HarelM** [comment]
The icons are creating a line break which is not optimal for reading and can change the location based on screen size, I would suggest to avoid using the icons.

**Comment by HarelM** [comment]
I also don't see a significant value to keep a static message. I would recommend to simply define a different text for every situation...

**Comment by HarelM** [comment]
Also worth considering that this text is always behind the map, so it should be a bit long so that if you manage to read it fully, it means there's a bad reception, if the text is short enough you might be able to read it even though the map just took a bit longer to load...
This is some of the UX consideration of the current text...

**Comment by Tsurha** [comment]
So you are welcome to use these:

Use-case 1: 
<div dir="rtl">
תנאי הקליטה גרועים. ניתן לצפות במפות לא מקוונות ע״י פתיחת התפריט הראשי, בחירת "מסלולים - מפות - שכבות" ולחיצה על סמליל הענן ליד המפה המתאימה.

Use-case 2:
<div dir="rtl">
 כשהקליטה תשתפר יש להוריד לטלפון את המפות הלא מקוונות שרכשת.

Use case 3:
<div dir="rtl">
כשהקליטה תשתפר מומלץ לרכוש מפות לא מקוונות, ולהורידן לטלפון. 

All 3 these sentences are fine even if eventually the map loads. 
Let me know if we are good to go and I'll translate.

**Comment by HarelM** [comment]
Well, you might be able to see this text even if reception is OK, so I'm still looking for a longer text or the notion of "if you manage to read this..."

**Comment by Tsurha** [comment]
Let me rephrase them so even when there is good reception and they are read, each sentence is true

Use-case 1: 
<div dir="rtl">
ניתן לצפות במפות לא מקוונות ע״י פתיחת התפריט הראשי, בחירת "מסלולים - מפות - שכבות" ולחיצה על סמליל הענן ליד המפה המתאימה.

Use-case 2:
<div dir="rtl">
יש להוריד לטלפון את המפות הלא מקוונות שרכשת. מומלץ בחיבור WiFi. 

Use case 3:
<div dir="rtl">
עבור צפיה במפות ללא חיבור לרשת, ניתן לרכוש מפות לא מקוונות.  
יש להוריד אותן אל הטלפון, מומלץ בחיבור WiFi.

**Comment by HarelM** [comment]
These look good to me.

**Comment by Tsurha** [comment]
To 2+3 I could add a menu explanation. Let me know if you'd like that too.  If yes, please:
2. Tell me the exact key press sequence for 2, as I can't remember
3. Finalize the approach for [#1858](https://github.com/IsraelHikingMap/Site/issues/1858) 

I'll add English once we are set.

**Comment by Tsurha** [comment]
### Use-case 1:
Bold words should be **bold** in the app

ניתן לצפות במפות לא מקוונות ע״י פתיחת **התפריט הראשי**, בחירת **מסלולים - מפות - שכבות** ולחיצה על **סמליל הענן** ליד המפה המתאימה.
To view offline maps from the **main menu**, tap **Routes, Maps, and Overlays** and tap the **cloud icon** of the required map.


### Use-case 2:
יש להוריד לטלפון את המפות הלא מקוונות שרכשת. מומלץ בחיבור Wi-Fi.
Download the offline maps you purchased previously, preferably via Wi-Fi.


### Use case 3:
מומלץ לרכוש מפות לצפיה ללא חיבור לרשת. את המפות מורידים לטלפון, עדיף ב Wi-Fi.
It is recommended to purchase maps for offline usage. The maps will be downloaded to the phone preferably via Wi-Fi.

**Comment by HarelM** [comment]
I would like to avoid adding bold text due to translation technical limitations.
Here is how this would look now, I've changed the texts a bit where I saw issues:
Wi-Fi word was in english and create a break in line, changed it to Hebrew...
<img width="332" alt="image" src="https://user-images.githubusercontent.com/3269297/225925090-489d56e4-fd73-4fb1-b200-782cb14eb4d9.png">
<img width="332" alt="image" src="https://user-images.githubusercontent.com/3269297/225923161-4393f843-0458-4874-9b84-961326a087f2.png">
<img width="332" alt="image" src="https://user-images.githubusercontent.com/3269297/225924786-ae302187-6524-444a-bc77-4737c06dc60d.png">

**Comment by Tsurha** [comment]
Should have a different message on a desktop (win, mac) that can't buy maps:

![image](https://user-images.githubusercontent.com/49042192/229290574-d3aa0b00-618c-4f2b-ab33-d9bf8ed94256.png)

**Comment by HarelM** [comment]
How did you get to this condition in the desktop?

**Comment by Tsurha** [comment]
I just stumbled on it so thought to let you know.  After refreshing or reopening it was fine.  I do not know how to reproduce.  Maybe it could show if there was a temporary mapping issue on site?  Just a guess

**Comment by HarelM** [comment]
Well... It's not accurate, but chances for getting this on desktop are not high, and it can serve a a commercial for the offline maps.
I'll keep it as is for now.
