### ISSUE TITLE
Add attribution to all Wikipedia images

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1863]
### What is the problem this feature will solve?

Some Wikipedia pictures, such as pictures in the public domain, do not have an attribution.

### What is the feature you are proposing to solve the problem?

Add attribution to all Wikipedia pictures, where the author is known.

### What alternatives have you considered or tried?

None

### Additional information

For example, the Wikipedia picture for https://israelhiking.osm.org.il/poi/Wikipedia/he_1393399 was put in the public domain by its author.

**Comment by Tsurha** [comment]
Note this, may be related: https://israelhiking.osm.org.il/poi/OSM/node_278473946?language=en


![image](https://user-images.githubusercontent.com/49042192/223474781-47078a7f-d547-485b-9245-9d4b48d86d37.png)

**Comment by HarelM** [comment]
Thanks! This is a different issue. I'll fix that too.
