### ISSUE TITLE
Route colors too dim

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#187]
The routes are hard to see on bright maps.
Consider having them solid, rather than semi transparent.
Maybe control transparency (an overkill).
Also 1 or 2 bright colors are needed, white or orange, to work with dark aerial images.

**Comment by HarelM** [comment]
See issue #39 
Please let me know which colors to replace - I don't want to change the total number of colors due to UI appearance.

**Comment by valleyofdawn** [comment]
I'll let you know.  What's your take on the transparency issue?

**Comment by zstadler** [comment]
We can consider adding a transparency slider

**Comment by HarelM** [comment]
Slider is an easy to implement option, would it do?

**Comment by valleyofdawn** [comment]
It would. Will you make the default opaque, though?

**Comment by valleyofdawn** [comment]
9C7f00  ->  FFFF00
7F9900  -> 00FF00

**Comment by HarelM** [comment]
Can't use the second one - the color is reserved for markers (green).

**Comment by valleyofdawn** [comment]
Do bright cyan then. 00FFFF

**Comment by valleyofdawn** [comment]
Do bright cyan then. 00FFFF
