### ISSUE TITLE
Image attribution show too many characters

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1872]
### What happened?

The **Image by** here does not look elegant:

![Screenshot_20230330_222538_Israel Hiking Map](https://user-images.githubusercontent.com/49042192/229062162-70432b5e-9e35-4e87-b7f2-9a526377f373.jpg)

### What steps will reproduce the bug?

Check it here: https://israelhiking.osm.org.il/poi/Wikipedia/en_24018808?language=en

### What I expect to happen

I suggest to limit the **Image by** field to 25 characters.  This would still give the appropriate credit, limit to one line,  and if someone is really interested he could click that link 

### Platform

- [X] Israel Hiking Map app
- [ ] Israel Hiking Map site in a browser

### OS Name and Version

Android 13 on Samsung S22

**Comment by HarelM** [comment]
Thanks for the info, I'll look into it to find the best solution, the problem is that it is generated by wikipedia and there are probably other value which are hard to foresee...

**Comment by Tsurha** [comment]
Thanks for working on it. Once its released we should also have a look on the following link:
https://israelhiking.osm.org.il/poi/OSM/way_599884893?language=he
