### ISSUE TITLE
Peak is not a POI

### ISSUE THREAD

**Issue by amiad** [IsraelHikingMap/Site#1875]
### What happened?

לפי מיטב זיכרוני פסגות היו בעבר נקודות עניין עם תמונות.
עכשיו הן לא מוצגות כך. רק אם מחפשים אותן אז הן מוצגות.

### What steps will reproduce the bug?

כיפת עשוש לא נקודת עניין
https://israelhiking.osm.org.il/map/16.39/30.4303/35.0014
רק אם מחפשים אותה
https://israelhiking.osm.org.il/poi/OSM/node_5882330268?language=he

### What I expect to happen

שהיא תוצג כנקודת עניין

### Platform

- [X] Israel Hiking Map app
- [X] Israel Hiking Map site in a browser

### OS Name and Version

All

**Comment by zstadler** [comment]
Potentially, add a peak to the nature POI layer only if it has a description or an image

**Comment by HarelM** [comment]
I don't think they ever were, only maybe if merged with a wikipedia/iNature value or if the peak is also a viewpoint.
Usually, peaks are not interesting to visit so they were never part of the layer, much like streams I guess...

**Comment by amiad** [comment]
אז אני חושב שהן צריכות להיות נקודות עניין אם יש מידע נוסף.
נחלים הם ארוכים ולכן לא מתאימים להיות נקודה.

**Comment by HarelM** [comment]
מצטער, אני לא מסכים, לא קיבלתי פה טיעון מספיק חזק כדי להוסיף והסברתי למה אני חושב שהן לא צריכות להיות (הן מעולם לא היו דרך אגב).
בודמה לנקודות אחרות, ניתן לחפש פסגות, אבל אני לא רואה סיבה להוסיף אותם לשכבות.

**Comment by HarelM** [comment]
See here as well: #798 this is an old issue which confirms that this was a search results POI and not a regular POI.

**Comment by HarelM** [comment]
הוספתי קוד שמציג פסגות עם תיאור או תמונה, ורוב הפסגות שמצאתי לא מאוד מעניינות.
אין לי בעיה להוסיף את זה לנקודות העניין, זה לא שינוי קוד גדול, אבל אני באמת חושב שאין פה הרבה עניין למשמתשים.
אולי לגבעה הספציפית הזו כדאי להוסיף עוד תגית כמו תצפית או אטרקציה תיירותית.
הנה כמה שמצאתי לדוגמא שנראה שאין בהם הרבה עניין לציבור:
https://israelhiking.osm.org.il/poi/OSM/node_278478102?language=he
https://israelhiking.osm.org.il/poi/OSM/node_8541834517?language=he

**Comment by HarelM** [comment]
מבדיקה אקראית של כ-5-10 נקודות מהרשימה הנ״ל מסתמן, לדעתי, שיותר נכון להעביר את המידע שבפסגה לנקודת העניין הקרובה שלרוב עליה מדברת הפסגה או להוסיף לפסגה שהיא גם נקודת תצפית, יש גם חורבות וכו׳, אבל על פניו נראה יותר כמו מיפוי לא נכון של הפסגות.
אני לא נחרץ בדעתי, ואשמח לשמוע דעות אחרות בהינתן המידע הנ״ל, אשמח לקבל מספיק דוגמאות שבהן המיפוי מרגיש נכון והוספת נקודות העניין האלה נראה כפתרון היחידי.

**Comment by zstadler** [comment]
I found 44 peaks that have an image or a description and are not tagged with "tourism" or "historic" - https://overpass-turbo.eu/s/1y0F

It included
- [הר עצמון](https://israelhiking.osm.org.il/poi/OSM/node_3221962446?language=he)
- [הר צפת](https://israelhiking.osm.org.il/poi/OSM/node_1411207100?language=he)
- [הר קנאים](https://israelhiking.osm.org.il/poi/OSM/node_278478319?language=he), שבו [התצפית](https://israelhiking.osm.org.il/poi/OSM/node_8082215621?language=he) נמצאת במקום אחר מהפסגה
- [הר בוקר](https://israelhiking.osm.org.il/poi/OSM/node_278477237?language=he)

I think they are valuable. 

Certainly no less than some of the Wikipedia POIs I happened to see near הר צפת😄 
![image](https://github.com/IsraelHikingMap/Site/assets/1304610/268a0760-fc70-441f-9611-39b2fd9533dc)

**Comment by HarelM** [comment]
Looking at the map and images:
הר עצמון - נראה כמו תצפית לפי זה שעולה למקום שביל עפר
הר צפת - נראה כמו מנומנט
הר קנאים - אותן תמונות נמצאות גם בתצפית וגם בפסגה, כך שבפועל זה מדבר על אותה נקודה, אם לא היו תמונות בפסגה אלא רק בתצפית לא חושב שלמשתמש זה היה "מפריע" - מה שזה ייצור זה כפילות.
הר בוקר - גם ככה מופיע כנקודת עניין היום כי הוא ממוזג עם נקודה של ויקיפדיה.

אשמח לעוד דוגמאות, אלא אם הטענות שלי לגבי מיפוי יותר מדויק מרגישות לכם חלשות.

**Comment by zstadler** [comment]
ראשית עלי לאמר שהנושא לא מאד חשוב בעייני ונשאבתי חזרה לדיון לבקשתך, @HarelM 😆 

בכללי, אני מעדיף להיות טולרנטי לטעויות תיוג כמו חוסר של תגית תצפית/מונומט או העלאה של אותן תמונות לשתי נקודות OSM שלא ניתן למזג אותן. לדעתי, בהנתן כמות נקודות העניין שיש לנו, עוד 44 נקודות הן טיפה בים ועדיף שתהיינה שם.

**Comment by HarelM** [comment]
סבבה, אולי ככה זה יעלה את המודעות לנקודות ויותר אנשים ישפרו את המיפוי שלהן (במקום רק פסגה יוסיפו עוד תגיות, כמובן רק ע"י עורכים מתקדמים).

**Comment by HarelM** [comment]
This should be available now.
