### ISSUE TITLE
"Upload recording" button is barely seen

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1877]
### What happened?

When automatic upload is turned off, and a local recoding is selected from the list, the "upload" button is barely seen.

### What steps will reproduce the bug?

1. Disable automatic recording upload
2. Record something
3. Open the recordings list
4. Select the new recording

### What I expect to happen

The upload button is fully visible 

### Platform

- [X] Israel Hiking Map app
- [ ] Israel Hiking Map site in a browser

### OS Name and Version

Android 12

### Additional information

![IMG_20230408_224547](https://user-images.githubusercontent.com/1304610/230739941-29c06a20-5038-475e-b7fa-e9fc5b0121c5.jpg)

**Comment by HarelM** [comment]
Yup, this is due to recent changes caused by #1810.
There are other places like public POI upper menu and places that use the `no-padding` class.
I haven't got around to fix it due to my mac being dead :-(
This is only in the internal version though, this is not how other users see this.
