### ISSUE TITLE
Improve startup time and reduce logging clean time

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1878]
### What is the problem this feature will solve?

Under some circumstances, app startup is slow, buttons are yet unavailable, and it is not clear which internal operation is causing the delay.

### What is the feature you are proposing to solve the problem?

Add on-screen debug information to assist in such an identification to be captured using screenshots.

### What alternatives have you considered or tried?

None

**Comment by HarelM** [comment]
@zstadler please let me know if the latest version I uploaded works as expected.
If so, please close this issue.

**Comment by zstadler** [comment]
Checked the log deletion, and it looks like the oldest records are indeed deleted.
