### ISSUE TITLE
After reading a POI, map does not show all other POIs

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1879]
### What happened?

Most POIs disappear:

![image](https://user-images.githubusercontent.com/49042192/232024813-a8249792-124e-4877-a7b7-c1bfff46b079.png)

### What steps will reproduce the bug?

On PC:
* Enable viewing all POI types.  
* Click to browse a specific POI. For example: https://israelhiking.osm.org.il/poi/OSM/way_98475151?language=he
* Close the POI pane with X
* Zoom out. 
* Something only nearby POIs are presented, as if there are no more in Israel

### What I expect to happen

When zooming out, I expect all the enabled POI types to show in the presented map area. Not just those that were nearby the last one.

### Platform

- [ ] Israel Hiking Map app
- [X] Israel Hiking Map site in a browser

### OS Name and Version

Win 10

### Browser Name and Version

Chrome

**Comment by HarelM** [comment]
POIs show only from a certain zoom, when you select a POI that zooms out, you might receive this behavior, I guess...

**Comment by Tsurha** [comment]
I'm not sure what do you mean a POI that zooms out...

Anyway, have a look at this capture with lots of POIs grouped to green circles:

![image](https://user-images.githubusercontent.com/49042192/232049240-48309ffe-d6df-4cb0-8e5b-970b74ffa6ad.png)


I now select one of them from within a green circle. The map zooms to it which is perfect:

![image](https://user-images.githubusercontent.com/49042192/232049564-34e991b3-c60f-4fa0-8a40-dd21cc7a5a50.png)


I'll now zoom out to see what is around it.  All the previously visible green circles are gone:

![image](https://user-images.githubusercontent.com/49042192/232050016-2c8a0e6b-41ef-4547-8403-15f79e392eeb.png)

Its a confusing behavior

**Comment by HarelM** [comment]
I agree, when you zoom out "too much" the POIs are no longer being received from the server.
Once you zoom in "enough" you'll start receiving them again.
This is to prevent receiving too many. It's an optimization on traffic which is counter productive to UX, but I don't have a better solution for this...

**Comment by Tsurha** [comment]
When zooming out, dont you generate traffic in bringing more map data?  If yes, than bringing the basic POI metadata (name, coordinates, type...) should not be much.  Just guessing.

If the above is wrong, and the zoom out map data is presented from cache, maybe it would be good to include the POI metadata in that cache.  

???????

**Comment by HarelM** [comment]
It's more complicated than that.
While this can probably be improved, it's not that easy.
The map data and POI data are generated differently, for example in the map you can't see wikipedia points, as those are coming from a different source, are being merged and then served from a database.
In the phone the entire POIs file is downloaded and then presented (and updated every time you open the app), but it's a lot harder to do that in the desktop, so this is a good enough solution from my point of view for desktop users (less than 25%), as all you need to do is zoom in to see more points.

**Comment by Tsurha** [comment]
Thank you for the explanation!
