### ISSUE TITLE
Waypoint text formatting

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#188]
1. Formatting of long waypoint text such as "מפגש שבילים כחול אדום שחור" need not introduce line warps.

 [For example](http://israelhiking.osm.org.il/#/?s=k2tDaiFzUv):

 <img width="199" alt="2016-07-24 13_28_24-israel hiking map" src="https://cloud.githubusercontent.com/assets/1304610/17083265/9e111bfe-51a2-11e6-8a6f-70b2551fc4cb.png">

 is better, in my opinion, than

 <img width="87" alt="2016-07-24 13_09_15-israel hiking map" src="https://cloud.githubusercontent.com/assets/1304610/17083205/f03d8e92-519f-11e6-9d4d-cb66591d5716.png">

2. Add the ability to embed a line warp when editing the waypoint text and allow:

 <img width="162" alt="2016-07-24 13_37_17-israel hiking map" src="https://cloud.githubusercontent.com/assets/1304610/17083292/d297ab6c-51a3-11e6-8285-f80b7f78db4f.png">

 Currently, the _Enter_ key aborts the editing, which is counter-intuitive.

**Comment by HarelM** [comment]
See issue #177
I have used this library:
https://github.com/Leaflet/Leaflet.label
I couldn't figure out how to do it, and believe me it annoyed me as well.
Let me know if you figure out how...

**Comment by zstadler** [comment]
For the first request, I believe adding `white-space: nowrap;` to[`.marker-label` in app.css](https://github.com/IsraelHikingMap/Site/blob/master/IsrealHiking.Web/app.css#L13) would do the job.

I would also suggest adding `border: 1px solid black; opacity: 0.8;` in order to see some of the map behind the label:
<img width="169" alt="2016-07-24 14_19_16-israel hiking map" src="https://cloud.githubusercontent.com/assets/1304610/17083451/aca15c36-51a9-11e6-94aa-52474f429c74.png">


Note that the opacity is currently set in the element itself, rather than in the app.css file.

What about the second request?
