### ISSUE TITLE
Improve opening the site from an embedded iframe

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1881]
### What is the problem this feature will solve?

When opening the site from an embedded iframe, using the IHM logo at the bottom left, some user experience may get lost.

For some users, this would be their first encounter with IHM.

### What is the feature you are proposing to solve the problem?

1. When the iframe is opened with a track URL the background map should be preserved. For example, [this Groopy trail](http://www.groopy.co.il/trackinfo.aspx?pid=2697) should always be opened with the MTB map rather than with the user's previously-used map.
2. When the iframe is opened with a map location only, such as 
   ```
   <iframe src="https://israelhiking.osm.org.il/map/17.49/32.0914/34.8083" ... />
   ```
   the site should open with the position and zoom level at the time of the click. For example:
    - Open [Tel Gerisa at biblical-archaeology.org](https://biblical-archaeology.org/?focused_location=10578)
    - Scroll to the bottom of the "Tel Gerisa" pane
    - Pan and zoom the map
    - Click on the IHM logo

### What alternatives have you considered or tried?

None

**Comment by HarelM** [comment]
Seems like the following is the place to fix this issue:
https://github.com/IsraelHikingMap/Site/blob/e854120951fe8f32057f2d6f2f3611d4c6f5dee6/IsraelHiking.Web/src/application/services/hash.service.ts#L92
Base layer can be added to the file url for completeness.
