### ISSUE TITLE
Waypoint info too busy

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#189]
Consider simplifying the WPT edtting window.

I would just have the text window, a trashcan button, an OK button and an info button.
This can be with a globe icon or info icon.
Pressing it would reveal the co-ordinates and the wikipedia link.

**Comment by HarelM** [comment]
A picture is with a thousand words...?
What would you have the globe do? Reveal information below it? Pop it up?

**Comment by valleyofdawn** [comment]
Just unfold the bottom part of the window as it looks now
Can also be with one of these small triangles that tells you the window can be expanded.

**Comment by HarelM** [comment]
Please pick an icon from the following list and let me know which is it.
http://fontawesome.io/icons/

**Comment by HarelM** [comment]
related to #188.
