### ISSUE TITLE
Improve experience when sending a report

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1899]
### What is the problem this feature will solve?

When sending a report it sometime takes time to prepare the logs, and the user doesn't know if it is still running or there was a problem

### What is the feature you are proposing to solve the problem?

Add some indication that the report is still in process

### What alternatives have you considered or tried?

Just waiting for it to finish.

**Comment by zstadler** [comment]
If such a mechanism is added to the app, it would be nice to also use it when opening a file or a link takes a long time.

**Comment by HarelM** [comment]
I didn't plan to create an elaborate infrastructure for this, simply add a toast saying "not yet..." every 5 second or so until the processing is complete. I'm not sure this is the right solution for other cases...

**Comment by zstadler** [comment]
I'm not sure that is the right solution for this case :wink:
