### ISSUE TITLE
No overlays should be selected when loading from local storage

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#19]
Does not work

**Comment by HarelM** [comment]
Do you mean that when you add a base map the next time you open the browser this base map is not present?
or you mean that the selected base map is not stored in cookies?

**Comment by valleyofdawn** [comment]
The maps are stored. The last map and overlay used should be the ones it opens with. Right now it opens with the last overlay added (not used).

**Comment by HarelM** [comment]
This was never implemented. marking as enhancement.

**Comment by HarelM** [comment]
Thinking on it again, I'm not sure I want the site to be used by users who finds this site collectable - When the site sets the base layer as Israel Hiking map it tells the users that this is what they should be using when surfing here, if they want to use other maps by default they should use other sites.
I'm not sure I want to change this behavior.

**Comment by valleyofdawn** [comment]
Then open it with IHM and no overlays, but not with the last layer added, as now.

**Comment by HarelM** [comment]
IHM is the selected base layer no matter how many base layer I have. This issue is only about overlays, am I correct? So this bug is just about turning off all the overlays I have added, right?

**Comment by valleyofdawn** [comment]
Right.

**Comment by valleyofdawn** [comment]
It still opens with my custom overlay on.

**Comment by HarelM** [comment]
Yup, when I close an issue it means I changed the code here, when I create a release I accumulates all changes and then I update the site.
