### ISSUE TITLE
improve loggin of POI upload

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1900]
### What is the problem this feature will solve?

When we receive a user report, it is hard to track the OSM side of an upload given the information such as this in the log file:

```
2023-05-12 19:51:32 |  INFO | [POIs] Uploaded successfully a feature with id: OSM_node_2494337273, removing from upload queue
2023-05-12 15:42:28 |  INFO | [POIs] Uploaded successfully a simple feature with id: f4c638fd-fa3c-4a3c-a8e7-a6370aba0272, removing from upload queue
2023-04-30 12:11:29 |  INFO | [POIs] Uploaded successfully a feature with id: OSM_relation_3752079, removing from upload queue
```

### What is the feature you are proposing to solve the problem?

Add the OSM changeset to the logging of every successful upload

### What alternatives have you considered or tried?

Look at the user's online changeset list and find a changeset with the approximate time in the log.

**Comment by zstadler** [comment]
If the client's request times-out, will there ever be a "Uploaded successfully" message in the log file? For example, after a retry?

**Comment by HarelM** [comment]
Yes, in case of a timeout the client will try again later and if the server already handled the request it will immediately return.
I can log in the client the feature ID that was returned from the server which I believe should help get to the relevant feature in OSM, from that to getting the relevant changeset there shouldn't be a problem I think.

**Comment by HarelM** [comment]
I've added the feature ID in case of a "full" feature to client side logging and the location in case of a "simple" feature. 
Server side logging already writes all the information about the upload process, so I didn't see a need to add more logging there.
