### ISSUE TITLE
Can't add new POIs

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1908]
### What happened?

I can't add new POIs

### What steps will reproduce the bug?

1. Upload a new POI
2. Get error 500 in the logs

### What I expect to happen

A new POI should be added

### Platform

- [X] Israel Hiking Map app
- [X] Israel Hiking Map site in a browser

### OS Name and Version

Any

### Browser Name and Version

Any

### Additional information

Related to the changes made in #1837

**Comment by nyhhkho** [comment]
I quit and I don't want to continue the relationship and correspond.
Thanks

‫בתאריך יום א׳, 28 במאי 2023 ב-22:02 מאת ‪Harel M‬‏ <‪
***@***.***‬‏>:‬
