### ISSUE TITLE
Ability to have search results ordered by distance

### ISSUE THREAD

**Issue by roiros** [IsraelHikingMap/Site#1918]
### What is the problem this feature will solve?

Hard to find near by spots. Searching for unspecified חניון לילה would produce results all across, instead of focusing on nearby spots. 

### What is the feature you are proposing to solve the problem?

It would be easier to locate the relevant sites

### What alternatives have you considered or tried?

I've used other sites

**Comment by HarelM** [comment]
This is an interesting idea.
The current solution to this issue is basically using the side panel for the points of interest and  filter to see nearby points that are only "base camps".

**Comment by roiros** [comment]
Using the sidebar is possible but it's a hassle, and isn't trivial (I haven't thought of it, probably others as well)

Context aware map search is the standard, if you'll search הלסינקי when viewing Israel/Tel aviv you'll get the street rather than the city in Finland. Or if you search for a gas station at Waze

Example:
![image](https://github.com/IsraelHikingMap/Site/assets/5019543/c45d016c-1531-446a-8f59-8e00d21feaab)

**Comment by HarelM** [comment]
We are already doing some sorting according to the feature type and it's name, adding sorting by distance won't necessary improve results.
If I'm looking for "עין מחוללים" getting the first result as "בית החולים עין גדי" even if it's closer, doesn't make any sense, you might argue that it doesn't make sense to receive it in general, but the current search algorithm is already very complicated and I'm not sure I can improve it, believe me, I tried.
I would recommend using the site's search and see if ordering the results makes sense, my guess is that it wouldn't.
This is not the same as generally searching for anything close by, as the focus of this app is very specific.
