### ISSUE TITLE
Incomplete merge

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1925]
### What happened?

On one hand, [inature's שמורת בית ציידה](https://inature.info/wiki/%D7%A9%D7%9E%D7%95%D7%A8%D7%AA_%D7%91%D7%99%D7%AA_%D7%A6%D7%99%D7%99%D7%93%D7%94) is included in [OSM-based שמורת טבע הבטיחה](https://israelhiking.osm.org.il/poi/OSM/relation_12941438) entry in IHM.
![image](https://github.com/IsraelHikingMap/Site/assets/1304610/aa9c8a30-4926-4560-aca5-923da76ce4e1)

On the other hand, it also has [an independent entry](https://israelhiking.osm.org.il/poi/iNature/2177) in IHM.
![image](https://github.com/IsraelHikingMap/Site/assets/1304610/511cf544-219c-4694-88b8-34d10be14400)

The inature link in both entries is the same.

### What steps will reproduce the bug?

Open the above links

### What I expect to happen

The independent entry should not exist.

### Platform

- [X] Israel Hiking Map app
- [X] Israel Hiking Map site in a browser

### OS Name and Version

All

### Browser Name and Version

All

### Additional information

Potentially, this is because the `website` tag [in OSM](https://www.openstreetmap.org/relation/12941438) is the inature page.

**Comment by HarelM** [comment]
The merge is done only on names, not on the website field.
These points were never merged and thus there are two points.
The point in OSM has a website link and thus you see it in the "see also".
In order for the merge algorithm to apply in this case there's a need to add to OSM the name in iNature.
For example:
`alt_name = שמורת בית ציידה` or `name:he1 = שמורת בית ציידה`
Both will work.
