### ISSUE TITLE
Misssing margin in the "About" panel

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1945]
### What happened?

There is no gap between the text and the right edge of the "About" panel.

### What steps will reproduce the bug?

Open the "About" panel

### What I expect to happen

Have some margin on the right side of the text

### Platform

- [X] Israel Hiking Map app
- [X] Israel Hiking Map site in a browser

### OS Name and Version

All

### Browser Name and Version

All

### Additional information

- The margins on the "Legend" tab look good.
- Desktop screenshot:
![image](https://github.com/IsraelHikingMap/Site/assets/1304610/90f87da0-4cea-472c-9c3d-44a7c0b022e0)
- On my mobile, it looks like there is no margin also on the left side. It is probably due to different line breaks.
![image](https://github.com/IsraelHikingMap/Site/assets/1304610/d3f51fb8-40fe-4683-aa78-b0ab6fd16d45)

**Comment by HarelM** [comment]
Missing `mat-card-content` html tag basically...
This is also the case for POI edit mode, but I find it better that the current input boxes do not have any margin from the sides so I'm keeping the POI edit panel as is, without `mat-card-content`...
