### ISSUE TITLE
Splitting a recording doesn't split the statistics well

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1955]
### What happened?

When I split a recording somewhere in the middle by adding a middle point the total time of the split part is cleared.

### What steps will reproduce the bug?

1. Open a recoding
2. Click on the line to create a middle point
3. Click on that point to split the route into two
4. Look at the total time of the route

### What I expect to happen

The total time should reflect the part that was cut out.

### Platform

- [ ] Israel Hiking Map app
- [ ] Israel Hiking Map site in a browser

### OS Name and Version

Any

### Browser Name and Version

Any

### Additional information

This is related to the fact that when splitting a route the time is not interpolated on the newly created middle point and the calculation of total time and average speed takes into account the first and last point of a route.

**Comment by zstadler** [comment]
תודה!!! 🙏
