### ISSUE TITLE
Trim blanks when updating OSM

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1956]
### What is the problem this feature will solve?

the `name*` and `description*` tags often include blanks that need manual trimming
- Multiple consecutive blank characters
- Blank characters at the beginning or end of the strings

For example, [changeset 144519036](https://www.openstreetmap.org/changeset/144519036) trimmed 87 such OSM elements

### What is the feature you are proposing to solve the problem?

When a user submits an update to OSM, the `name*` and `description` tags of the update will be trimmed of the redundant blanks.

### What alternatives have you considered or tried?

I have an [Overpass query](http://overpass-turbo.eu/s/18RA) that finds such elements. I download the query results, trim the blanks and upload the update to OSM.

### Additional information

Potentially, the values of _**all tags**_ in the osmChange XML can trimmed just before uploading it.

**Comment by HarelM** [comment]
I have replaces multiple spaces with a single space and trimmed the string.
This applies to all the tags, not just name and description.
