### ISSUE TITLE
Exporting to a GPX file

### ISSUE THREAD

**Issue by ronmishael** [IsraelHikingMap/Site#1958]
### What is the problem this feature will solve?

When exporting to a GPX file, add the route name to the tag <name> and also for the file name.

### What is the feature you are proposing to solve the problem?

Allows you to know the contents of a file saved by its name or loaded by other applications

### What alternatives have you considered or tried?

change manually by the user

**Comment by zstadler** [comment]
As far as I can see, the name of the route is used as the name of the GPX file and it is used for the `<name>` tag in the GPX file itself.

For example:
#### The name of the route
![image](https://github.com/IsraelHikingMap/Site/assets/1304610/3230a95e-3c8b-45d7-a200-3b18626845e5)

#### The exported GPX file
![image](https://github.com/IsraelHikingMap/Site/assets/1304610/157cae90-2c25-4f3a-be92-6f3620e18bda)

If you are unable to reproduce this behavior, please describe the steps we can use to reproduce the issue
