### ISSUE TITLE
Use PMTiles for offline maps

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1961]
### What is the problem this feature will solve?

As the number of subscribers grow, I see an increase in the issues they have with the availability of the offline maps. Most issues are with offline maps not showing while some have SQL issues while downloading maps.

In both cases, the only available solution is to remove and re-install the application. In some cases, a data cleanup was also required.

### What is the feature you are proposing to solve the problem?

Replace the use of SQLite-base MBTiles format for the offline maps with PMTiles, and avoid the need to use SQLite adapter/plugin.

### What alternatives have you considered or tried?

None that I can think of...

**Comment by HarelM** [comment]
The following use cases needs to be considered and tested:
1. An old client should continue to work
2. A new client that has mbtiles and still did not download new pmtiles
3. A new client after downloading the new pmtiles
4. Download a new version of pmtiles (make sure the move overrides the previous file)

Also worth thinking about removing the old databases after downloading the pmtiles to reduce disk usage

**Comment by HarelM** [comment]
Additional consideration:
When downloading with the new client, the client is requesting a files by date.
This means that it might get only the IHM pmtiles files and not the contours and terrain, meaning it will operate with both pmtile and mbtiles.
Code wise, this is supported right now, but I'm not sure how we want to remediate this going forward.

**Comment by HarelM** [comment]
I've added a state parameter to indicate that pm tiles were ever downloaded to the device.
If this is not the case, it behaves similar to how the app behaves after you purchase a subscription but you haven't downloaded the files - i.e. when the app starts it prompts you to download the files.
This will make the migration period much sorter hopefully.
