### ISSUE TITLE
Remove patch-package for capacitor-android

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1965]
### What is the problem this feature will solve?

I need to update the patched package every time I upgrade a version of capacitor android.
This patch is solving the following bug:
- #1947 

### What is the feature you are proposing to solve the problem?

According to the following rejected pull request response:
https://github.com/ionic-team/capacitor/pull/7194
The proposal is to override the `onShowFileChooser` method.

### What alternatives have you considered or tried?

The above PR comment also suggests creating a plugin, but this seems like an overkill for this.

### Additional information

The above PR was trying to solve the following issues:
https://github.com/ionic-team/capacitor/issues/7220
https://github.com/ionic-team/capacitor/issues/6943
And the response to it suggested to open an issue for google, which I opened here:
https://issuetracker.google.com/issues/322839802

As a side note, @jcesarmobile, locking a conversation is not very welcoming, when all I'm trying to do is help solving a bug.

**Comment by jcesarmobile** [comment]
Please, can you not harass me?

**Comment by HarelM** [comment]
Can we please keep it professional? I'm not harassing anyone.
