### ISSUE TITLE
4wd is preferring track "too much"

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1967]
### What happened?

In the following route:
https://israelhiking.osm.org.il/share/IoepPEems4
Which I added points in order to show the order of the waypoints, the routing is deciding to use the tracks a bit "too" much according to some users, and I can relate to that:
![image](https://github.com/IsraelHikingMap/Site/assets/3269297/9a41bd64-3a9b-41bd-b5db-c451fea3b302)

### What steps will reproduce the bug?

See the route above

### What I expect to happen

It should use more paved roads than it does.

### Platform

- [X] Israel Hiking Map app
- [X] Israel Hiking Map site in a browser

### OS Name and Version

Any

### Browser Name and Version

Any

### Additional information

This is related to the following issue, see second comment about the change in routing.
- #1773

**Comment by zstadler** [comment]
דוגמה נוספת היא ניווט ג'יפים מבור קצינים לבורות לוץ
https://israelhiking.osm.org.il/share/bDe9QYww56

הדוגמה מעניינת בעייני כי יש בה גם בחירה במסלול שיורד למכתש רמון ועולה ממנו בעבירות קשה 
![image](https://github.com/IsraelHikingMap/Site/assets/1304610/ebeb2c6d-c14b-4ea2-a561-4612a57e8f03)

ויש בה גם בחירה לירידות לדרכי עפר שמקבילות לכביש, בתחילת המסלול - [בחלקו המערבי](https://israelhiking.osm.org.il/map/16.62/30.6504/34.7903)
![image](https://github.com/IsraelHikingMap/Site/assets/1304610/09f6c6fa-8039-46a2-bb8c-5da0d13de49f)

במקרה זה, ההיתי מצפה שניווט הג'יפים ישתמש בכביש 171 מצמת הכבישים 40 ו-171 ועד הירידה מ 171 לשביל הכחול לבורות לוץ

**Comment by HarelM** [comment]
Generally speaking there's conflict of interests between using the 4wd to plan a route that uses non paved roads and using paved roads.
In the past, there was a request for the routing to prefer tracks instead of roads (I can't find the facebook post unfortunately...).
I've changed the modifier to be x2 instead of x20 for the tracks, which moves most of the routing towards paved roads instead of tracks.
I personally don't use this navigation profile so my testing ability is limited.
If anyone would like to play with it to fine tune the values feel free to do so.

**Comment by meliahu** [comment]
היי הראל,
אז אני לא בטוח שאני מבין מה אתה אומר.

היו כל מיני בקשות בעבר לתת העדפה לדרכי עפר ואז נתת לזה יחס גבוה ומאז האלגוריתם מתנהג באופן הנ"ל.
אם כך אני חושב שמי שביקש את הבקשה לא ממש הבין את ההשלכות.
כרגע התכנון עובד באופן מאוד לא אינטיאוטיבי.
לדעתי שווה להחזיר למצב של לפני השינוי @zstadler  מה אתה חושב ?
משה

**Comment by HarelM** [comment]
אני לא חושב שמי שביקש את הבקשה לא הבין את ההשלכות, אלא פשוט היו לו דרישות אחרות מלכם, וזה מה שכתבתי לגבי התנגשות בין הדרישות.
בכל מקרה, כרגע הכיוון הוא להחזיר את זה למצב דומה למצב המקורי, ואם בעתיד יהיו פניות להעדפה לדרכי עפר אקשר לקריאה הזו ואסביר שיש עם זה בעייתיות.
מקווה שזה יותר ברור עכשיו.

**Comment by meliahu** [comment]
מעולה,
תודה רבה.
(אולי יש מצב לחשוף משתנה למשתמש קצה משתנה  שיוכל לשנות היחס המדובר ממש כמו שהוא משנה את סוג הניווט - רגלי, אופניים וכו ?)

**Comment by zstadler** [comment]
עשיתי כיוונונים נוספים בפרופיל 4x4 והם זמינים עכשיו באתר ובאפליקציה.
ככל שבדקתי, יש איזון לא רע בין שימוש בכבישים לעומת שימוש בדרכי עפר.
הוספתי גם העדפה של שבילים מסומנים.

אם, @meliahu תמצא מקרים לשדעתך ניווט ג'יפים עדיין לא אינטואיטיבי, אנא שלח דוגמה עם המסלול המחושב, המסלול שלדעתך יותר אינטואיטיבי ולמה.

**Comment by HarelM** [comment]
אין סיבה לחשוף למשתמש משהו כזה כשכל מה שצריך כדי להזיז מסלול זה לגרור אותו לאן שרוצים שהוא יעבור... זה מוסיף סיבוכיות בלי לתת ערך שמצדיק את הסיבוכיות.
אבל תודה על הרעיון! 😃

**Comment by Moshe81** [comment]
זה נראה יותר טוב, בדקתי את זה על אותם שתי מסלולים שגם היו בוידאו בפייסבוק https://www.facebook.com/groups/israelhikingmap/posts/7099780100077122/
אז לדוגמא הראשונה זה עבד טוב.
אבל בדוגמא השניה רואים שוב תכנון לא כלכך יעיל - https://israelhiking.osm.org.il/share/jyG7yPSBYa
המסלול הזה הוא רק משני נקודות, התחלה וסיום. ולכאורה היה אמור להעדיף את הקו הישר.
יכול להיות שאין נוסחה מנצחת. ובכלל כיוונון מרויחים בצד אחד ומפסידים בצד השני
![image](https://github.com/IsraelHikingMap/Site/assets/29856634/d2cc97d0-314a-4961-8927-fb766308fb98)

**Comment by zstadler** [comment]
בדוגמה הזו לא מעורבות דרכי עפר ולכן זה לא קשור לניווט ג'יפים.  זה הניווט שמתקבל גם עבור מכונית רגילה [באתר Graphhopper](https://graphhopper.com/maps/?point=31.804029%2C35.470629&point=31.810027%2C35.446449&profile=car&layer=OpenStreetMap)

![image](https://github.com/IsraelHikingMap/Site/assets/1304610/1cbef339-3f14-423b-8535-cb405ab9e15b)

מדובר על נסיעה על כביש איטי לעומת נסיעה בכביש יותר מהיר ולכן היה שווה להוסיף 2 ק"מ ולהגיע יותר מהר.
