### ISSUE TITLE
Parent eye should be closed when its kid's eyes are closed

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1969]
### What happened?

When closing all the kid's eye, the parent should also close their eye
![image](https://github.com/IsraelHikingMap/Site/assets/49042192/de15d706-1e1e-4708-91e4-60a6ea1cbf66)

The current behavior may show the following closed eye while the user expects to see route icons on the map
![image](https://github.com/IsraelHikingMap/Site/assets/49042192/28971c6f-fa85-4d91-9834-48a29b48dd54)

### What steps will reproduce the bug?

turn each route off

### What I expect to happen

That the parent eye gets closed too

### Platform

- [X] Israel Hiking Map app
- [x] Israel Hiking Map site in a browser

### OS Name and Version

Android 13 on Samsung S22

**Comment by zstadler** [comment]
The mechanism works well for the transparent layers and the private routes.

It doesn't work for the POIs and the public routes.
