### ISSUE TITLE
When opening a cloud save the selected route is not updated

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1970]
### What happened?

See below

### What steps will reproduce the bug?

1. Open a cloud save
2. The selected route did not change

### What I expect to happen

I expect the selected route (showing the statistics) to be the selected one

### Platform

- [X] Israel Hiking Map app
- [ ] Israel Hiking Map site in a browser

### OS Name and Version

Any

### Browser Name and Version

Any

### Additional information

There is a question of what should we do when sharing multiple routes and not just a single one, but in case of a single one it's clear that we should open it, focus on it and set the selected route to be it, probably exiting edit mode if edit more was on.
In case of multiple routes, we can use the last one I guess.

**Comment by zstadler** [comment]
I believe the original e-mail brings an additional issue

> 
> היי אנשים יקרים
> בעיה קטנה: אני מתכנן מסלול ושולח לחברים בקבוצה
> והם מעלים לנייד שלהם את המסלול 
> הבעיה היא שנשאר אצלם המסלול הקודם וכאשר הם מעלים את המסלול החדש הגרף גבהים והקילומטרים  נשארים עם המסלול הישן ולא מתעדכנים. **אני צריך על פעם לתזכר אותם שלמחוק את כל המסלולים ורק אז להעלות את התיכנון החדש**😄
> 

When a share link is opened, all current routes remain in the app. As a result, when many shares are opened by a "read-only" user, who is not very familiar with the app, the app accumulates a large number of concurrently-opened routes.

**Comment by HarelM** [comment]
Fixing the broader issue of what should we do if a user has "too many" private routes is out of scope for this issue.
A proper UX discussion should be made before we decide how to solve it.
