### ISSUE TITLE
Missing and fake locations in Wikipedia POI layer

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1972]
### What happened?

Following a phone discussion and a user bug report

The current algorithm for adding Wikipedia POIs to IHM has a few issues:
1. It may drop Wikipedia pages that should be shown or merged with OSM POIs.
2. It may show Wikipedia pages that do not have a location.
3. It is not scalable

This issue proposes to reverse the search direction. Rather than searching Wikipedia for pages that exists within a given bounding box, the new approach would identify the relevant Wikipedia pages based on OSM tags.

The down-side for such a change is that the IHM POI layer will no longer show Wikipedia pages that do not have an OSM element.

The identification could use the the `wikipedia`, `wikipedia:he`, and `wikipedia:en` tags, as used in the POI merge algorithm, or it can rely solely on `wikidata` tags, similar to [openmaptiles](https://github.com/openmaptiles/openmaptiles-tools/blob/master/bin/import-wikidata).

Note: The current search-and-match algorithm could be used for periodic bulk OSM edits that will add the missing tag/s.

### What steps will reproduce the bug?

The POI layer does not include a Wikipedia POI for זיתן, and the [OSM-based POI for זיתן](https://israelhiking.osm.org.il/poi/OSM/node_278470149?language=he) does not have a Wikipedia link

Hebrew Wikipedia has a page for [זיתן](https://he.wikipedia.org/wiki/%D7%96%D7%99%D7%AA%D7%9F) with a location.
![image](https://github.com/IsraelHikingMap/Site/assets/1304610/0dca03d2-7017-44c8-9f17-674b26f530b9)

The [Hebrew Wikipedia API](https://he.wikipedia.org/w/api.php?action=query&format=json&list=geosearch&gsbbox=31.9757|34.89|31.9756|34.8906) returns that page

```json
{
  "batchcomplete": "",
  "query": {
    "geosearch": [
      {
        "pageid": 44693,
        "ns": 0,
        "title": "זיתן",
        "lat": 31.9756126464499,
        "lon": 34.8905390342779,
        "dist": 22.9,
        "primary": ""
      }
    ]
  }
}
```

There is also an opposite case where a Wikipedia page that does not have a location is shown as a IHM POI
The Wikipedia page  [בית הכנסת צלאת בן שאיף](https://he.wikipedia.org/wiki/%D7%91%D7%99%D7%AA_%D7%94%D7%9B%D7%A0%D7%A1%D7%AA_%D7%A6%D7%9C%D7%90%D7%AA_%D7%91%D7%9F_%D7%A9%D7%90%D7%99%D7%A3) does not have a location, it is not returned by the [Wikipedia API](https://he.wikipedia.org/w/api.php?action=query&format=json&list=geosearch&gsbbox=31.9799|34.8936|31.9797|34.8938), but it exists as an [IHM POI](https://israelhiking.osm.org.il/poi/Wikipedia/he_1893502?language=he).

### What I expect to happen

Use OSM tags to identify Wikipedia pages

### Platform

- [X] Israel Hiking Map app
- [X] Israel Hiking Map site in a browser

### OS Name and Version

All

### Browser Name and Version

All

### Additional information

These problems with the contents of the Wikipedia POI layer, may also be related to #1971.

**Comment by Tsurha** [comment]
Note that many Wikipedia POIs are not exactly at the right coordinates. This is natural for an encyclopedia that is mostly text based and less about exact geo like osm.  When merging, my recommendation is to rely on OSM for location.

**Comment by HarelM** [comment]
If the POI exists in OSM and merged to it, the location is from OSM, not Wikipedia.
