### ISSUE TITLE
Missing item in legend

### ISSUE THREAD

**Issue by tamuz-o** [IsraelHikingMap/Site#1975]
### What happened?

The following grey-white line doesn't appear anywhere in the legend:
![image](https://github.com/IsraelHikingMap/Site/assets/13677289/eca840b9-af29-428a-a5f1-580aecdd521d)

It can be found for example here (Highway 6, one km southwest of the Yokneam tunnel)
https://israelhiking.osm.org.il/map/18.56/32.6542/35.0954

### What steps will reproduce the bug?

In the legend it doesn't appear under any of the sections

### What I expect to happen

.

### Platform

- [X] Israel Hiking Map app
- [X] Israel Hiking Map site in a browser

### OS Name and Version

Windows 11

### Browser Name and Version

Chrome 122

**Comment by HarelM** [comment]
Thanks for taking the time to open this issue!
Looks like a rendering bug to me, in terms of OSM this is a tunnel with highway=track and we have that on the legend and it looks as expected here:
https://israelhiking.osm.org.il/map/18.81/31.7209/34.8206
![image](https://github.com/IsraelHikingMap/Site/assets/3269297/d533bdc4-4953-487a-9804-7a0ccf5a7bec)

CC: @zstadler

**Comment by zstadler** [comment]
The [above track tunnel](https://www.openstreetmap.org/way/85389023) is made of concrete
![image](https://github.com/IsraelHikingMap/Site/assets/1304610/a127c72a-3415-4a7c-b503-1ec8c3c4694f)

Therefore it is shown as a paved road, similar to this unclassified road that goes under the interchange.
https://israelhiking.osm.org.il/map/19.00/32.2557/34.8939
![image](https://github.com/IsraelHikingMap/Site/assets/1304610/091c35a9-ab16-42cd-b641-b82347351cbd)

**Comment by zstadler** [comment]
@tamuz-o
Thanks to the screenshot in this issue, I found a minor bug in the style: the tunnels were incorrectly drawn above some other map elements. For example, here:
![image](https://github.com/IsraelHikingMap/Site/assets/1304610/af27d093-2b65-48ce-b265-6a486df74018)
Now, it is fixed:
![image](https://github.com/IsraelHikingMap/Site/assets/1304610/5edaf300-f994-4bbb-9985-b850a562eb7c)

**Comment by zstadler** [comment]
I hope it is clearer now
![image](https://github.com/IsraelHikingMap/Site/assets/1304610/7acf7aff-f201-482c-bd2b-e5180b85ea9e)
![image](https://github.com/IsraelHikingMap/Site/assets/1304610/37f83d7f-5f0a-4ef4-a3e3-f713ed4c4443)
