### ISSUE TITLE
In case of a lot of traces the UI hangs for a bit

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1980]
### What is the problem this feature will solve?

It takes more than 10 second for the "My Recordings" list to be ready., i.e., the spinner stops.

### What is the feature you are proposing to solve the problem?

Allow the client to cache the pictures it receives from the server

### What alternatives have you considered or tried?

None

### Additional information

![image](https://github.com/IsraelHikingMap/Site/assets/1304610/9be75194-fcef-49df-a4da-d8130086c98c)

**Comment by HarelM** [comment]
The browser should cache those, shouldn't it?

**Comment by zstadler** [comment]
It does not look like it uses the cache.

**Comment by HarelM** [comment]
Might be some missing cache control headers...

**Comment by zstadler** [comment]
Indeed. I'm reading about the [`Cache-Control`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) header and the [underlying mechanism](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#see_also).

Stay tuned...

**Comment by zstadler** [comment]
Now that caching is enabled, the opening still takes a long time.

There seem to be two consecutive "batches" of thumbnail requests delayed by about 9 seconds. Until the second batch is completed, the track list does not respond to the user. The images requested of the first and second batches are identical

![image](https://github.com/IsraelHikingMap/Site/assets/1304610/46939d0c-6381-4dee-9bc2-dcd5438e3562)

**Comment by HarelM** [comment]
I'll add those in the backend API definition, it won't be configurable, but it shouldn't change much.
I've set it to 10 hrs for cloud saves and 1 year for recordings.

If you think there should be other numbers let me know before I commit and close this issue.

**Comment by HarelM** [comment]
I've added cache control, but the problem is in the UI when syncing the traces.

**Comment by HarelM** [comment]
Testing this locally shows good improvement, but I think my machine runs faster.
I'll deploy this once the docker is ready so you can test if the performance improvements are enough.
