### ISSUE TITLE
Recording line has a jump when returning from background

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1999]
### What happened?

When recording a long line, while in the background it is possible to see a recorded line that has a jump.
It happened to me today but I didn't do a screenshot.

### What steps will reproduce the bug?

Not an easy task, but I think the following:
1. Start a recording
2. Move to background
3. Wait for a long time with a lot of measurement
4. See how the line is not "linear"

### What I expect to happen

Line should be "linear"

### Platform

- [X] Israel Hiking Map app
- [ ] Israel Hiking Map site in a browser

### OS Name and Version

Android 14

### Browser Name and Version

N/A

### Additional information

This is only a presentation issue, when stopping the recording the line is fine and there are not jumps.

This is related to the following issues:
- #1897
- #1796 (mainly)
- #1820 (initial change)

**Comment by HarelM** [comment]
@zstadler did you encounter such a behavior when recording a long trip?
I have a vague memory that you've seen this issue in the past...

**Comment by zstadler** [comment]
> @zstadler did you encounter such a behavior when recording a long trip? I have a vague memory that you've seen this issue in the past...

I'm not sure what you mean, but I sometimes see a "jump" when returning from a long recording in the background to the foreground. **If I'm not mistaken**, the jump is from the location where the app was put in th ebackground, to the current location and then back to the beginning of the trace that was saved while the app was in the background.

**Comment by HarelM** [comment]
Sounds similar, when stopping the recording the data is correct though, right?
I.e. this is only a presentation issue when the recording is running, and there's no way to "fix" it without stopping the recording, right?
