### ISSUE TITLE
map and overlay behavior beyond max zoom

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#20]
Right now they disappear or block further zooming.
Could be useful if you could see it enlarged at half the resolution.
Marked trails could still be useful on Google Earth at Z17 or 18.
limit max zoom to 20 or 21 though.

**Comment by HarelM** [comment]
Framework limitation, there's nothing much I can do about it, this is how leaflet works.

**Comment by zstadler** [comment]
http://gis.stackexchange.com/questions/78843/zoom-further-in-with-leaflet-javascirpt-api
