### ISSUE TITLE
Change the way IHM-uploaded images are tagged in OSM

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#2004]
### What is the problem this feature will solve?

Currently, IHM-uploaded images have a hard-coded full URL in the OSM `image*` tags. This requires IHM software to find an use that URL given the image name that was uploaded to Wikimedia commons

### What is the feature you are proposing to solve the problem?

According to the [OSM Wiki on Photo linking](https://wiki.openstreetmap.org/wiki/Photo_linking), there is another way to link to Wikimedia Commons image - the [`wikimedia_commons` key](https://wiki.openstreetmap.org/wiki/Key:wikimedia_commons).
For example: `wikimedia_commons=File:Eiffelturm.JPG`.
When there are several images, a Wikimedia Commons Category can be used: `wikimedia_commons=Category:Eiffel Tower`

Access to the image can be done using [hotlinking](https://commons.wikimedia.org/wiki/Commons:Reusing_content_outside_Wikimedia/technical#Hotlinking) based on the file name. For example:
[`https://commons.wikimedia.org/w/index.php?title=Special:Redirect/file/Eiffelturm.JPG`](https://commons.wikimedia.org/w/index.php?title=Special:Redirect/file/Eiffelturm.JPG)
[`https://commons.wikimedia.org/w/index.php?title=Special:Redirect/file/Eiffelturm.JPG&width=300`](https://commons.wikimedia.org/w/index.php?title=Special:Redirect/file/Eiffelturm.JPG&width=300)

### What alternatives have you considered or tried?

Keep the system as-is

**Comment by HarelM** [comment]
> When there are several images, a Wikimedia Commons Category can be used: wikimedia_commons=Category:Eiffel Tower

Who will create these categories? What happens to places that don't have a name?

Besides the above, there's a need to open a bulk edit announcement in the OSM forum.

I'm good with this idea as long as we solve the above issues.

**Comment by zstadler** [comment]
> Who will create these categories?

If we can do that through the API, _**and if it would simplify the handling of multiple images**_, we may create the categories ourselves. BTW, there is already a [Category:Israel Hiking Map](https://commons.wikimedia.org/wiki/Category:Israel_Hiking_Map)

> What happens to places that don't have a name?

I believe there is already a mechanism that sets the image names. That need not change.
For example: [File: IHM Cave*](https://commons.wikimedia.org/w/index.php?search=%22IHM+cave%22&title=Special:MediaSearch&gtype=image&type=image)
 
> Besides the above, there's a need to open a bulk edit announcement in the OSM forum.

IMHO, this is optional, assuming we will want to continue and use `image*` tags that were or will be added to OSM by means other than IHM.

**Comment by HarelM** [comment]
This is already supported for `image*=File:xxx.png` as can be seen here:
https://github.com/IsraelHikingMap/Site/blob/b919bb3faa217e47cd388f47c4f00f83a2ce9ee7/IsraelHiking.Web/src/application/services/resources.service.ts#L1006
We use it for image caching here too:
https://github.com/IsraelHikingMap/Site/blob/b919bb3faa217e47cd388f47c4f00f83a2ce9ee7/IsraelHiking.API/Executors/ImagesUrlsStorageExecutor.cs#L78
There is currently no support for `wikimedia_commons` though...

In theory, we may remove the code that translates the file name to an image url here:
https://github.com/IsraelHikingMap/Site/blob/b919bb3faa217e47cd388f47c4f00f83a2ce9ee7/IsraelHiking.DataAccess/WikimediaCommonGateway.cs#L115
and store the image in the wikimedia_commons tag, but if we plan to support both the "old" image tag and the new `wikimedi_commons` then this will only complicate the code without a significant improvement, so I'm not sure I understand the motivation behind this issue...
