### ISSUE TITLE
Add support for wikidata

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#2007]
### What is the problem this feature will solve?

Improve best practices when it comes to Wikipedia links with multiple languages.

### What is the feature you are proposing to solve the problem?

Replace Wikipedia related code with wikidata

### What alternatives have you considered or tried?

Doing nothing.

### Additional information

The following are the steps that we need to take in order to support this:
1. Make sure we can create a database in addition to current flow
2. Make a bulk edit in OSM to reduce the need for the merge between Wikidata, Wikipedia and OSM.
3. Move the server code to use Wikidata 
4. Move the client code to use Wikidata

Flows to consider:
- [x] Linking a wikipedia website - currently creates a wikipedia tag - added support for wikidata links at this point only.
- [x] Returned updated points should now return zero
- [x] Merge algorithm - add wikidata reference (and iNature)

**Comment by amiad** [comment]
נראה שנקודות ללא תיאור ותמונה אבל עם קישור לוויקינתונים מקבלים סימן של נקודה בפינה כאילו יש להן תוכן. האם זה קשור לנושא הזה?
