### ISSUE TITLE
Replace the legend thumbnail generaion method

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#2009]
### What is the problem this feature will solve?

Enable the retirement of `tileserver-gl-legend` and remove the last remaining dependency on [tileserver-gl](https://github.com/maptiler/tileserver-gl).

### What is the feature you are proposing to solve the problem?

Following https://github.com/zstadler/maptiles/issues/21#issuecomment-2155982592, replace The current [legend thumbnail generation process](https://github.com/IsraelHikingMap/Site/blob/45c0f82b94932a90b18c5b03e11bb474cb20311c/Scripts/generate-legend.py#L12-L17) with a process similar to the [image generation for the MapLibre documentation](https://github.com/maplibre/maplibre-gl-js/blob/a44906688699d6edd552f6a64dac05204c346ddf/build/generate-doc-images.ts).

### What alternatives have you considered or tried?

Keep the dependency on tileserver-gl.

### Additional information

Once the new process is deployed, please open an issue for retiring `tileserver-gl-legend`.

**Comment by HarelM** [comment]
Resolved by 8db243e31b3e36974196dbac4c4dcd4b519573fd
