### ISSUE TITLE
remove leisure=nature_reserve from map

### ISSUE THREAD

**Issue by amiad** [IsraelHikingMap/Site#2012]
### What is the problem this feature will solve?

לא פעם leisure=nature_reserve משמש לאזורים שהם לא שמורות מוכרזות. לפעמים רק מאושרות או מוצעות ולפעמים סתם פארק טבע. לעומתו protected_area=nature_reserve מציין שמורות מוכרזות חוקית.

### What is the feature you are proposing to solve the problem?

לכן כדאי להתעלם מ־leisure=nature_reserve.

### What alternatives have you considered or tried?

אין

### Additional information

יש גם [ויכוח בוויקי של OSM](https://wiki.openstreetmap.org/wiki/Talk:Tag:leisure%3Dnature_reserve#leisure=nature_reserve_vs._boundary=protected_area) לגבי הנחיצות של leisure=nature_reserve.

**Comment by HarelM** [comment]
אתה מתכוון למפה עצמה או לנקודות העניין ש"צפות" מעל המפה?

**Comment by amiad** [comment]
לנקודות העניין. במפה עצמה השמורה לא מופיעה.
אין לי הרבה דוגמאות כי אני משתדל למחוק אותן.

אבל הנה למשל נקודה. לפעמים יש גם קו.
https://israelhiking.osm.org.il/poi/OSM/node_5615795435?language=he

**Comment by HarelM** [comment]
אני לא בטוח שתיוג "proposed:leisure" הוא חוקי או תקני, אבל פה גם לא המקום לפתוח דיון כזה, לדעתי.
מאחר ובמפה עצמה השמורה לא מופיעה, אני לא לגמרי מבין את ההתנגדות להציג את נקודת העניין המתאימה, בעיקר כי יש נקודה של טבע ונופים במקום, ונשמע לי הרבה יותר אינפורמטיבי להציג את השטח של איזור כזה אם הוא יש עליו מידע נוסף באתר טבע ונופים.

**Comment by amiad** [comment]
כי זו לא שמורה מוכרזת ואתה מציג סמל רט״ג שאמור ליצג שמורה. לשמורה מוכרזת יש משמעות חוקית, לשמורה מתוכננת או מאושרת אין. יש סיבה למה אתם לא מציגים אותה במפה.

**Comment by HarelM** [comment]
אני יכול להחליף את הסמל אם זה מה שמפריע לך...
אנא עשה את ההפרדה בין המפה לבין נקודות עניין.

**Comment by amiad** [comment]
הסמל אכן מפריע, אבל כדאי לשמור אותו ל־protected_area=nature_reserve.

בכל מקרה, אשתדל להמיר את leisure=nature_reserve ל־protected_area=nature_reserve או proposed:leisure=nature_reserve לפי המצב החוקי.

**Comment by HarelM** [comment]
אני ממליץ להעלות את הנקודה בקבוצת הטלגרם של OSM, שימוש בתגית לא מקובלת הוא לא נתון להחלטתי...

**Comment by HarelM** [comment]
הנקודות נמצאות בטבע ונופים ובכל מקרה יהיו על המפה. אני מעדיף שיהיה להם סמל יותר מוצלח מהסמל של טבע ונופים שאינו ברור או אינפורמטיבי, ואני גם מעדיף שיהיה להם קשר לOSM מבחינת פוליגון.
אם יש לך הצעה לסמל יותר מוצלח אשמח לשמוע,

**Comment by zstadler** [comment]
> אני ממליץ להעלות את הנקודה בקבוצת הטלגרם של OSM, שימוש בתגית לא מקובלת הוא לא נתון להחלטתי...

הקידומת proposed היא קידומת מקובלת ב OSM, יחד עם planned, construction, disused, abandoned, demolished, historic:

https://wiki.openstreetmap.org/wiki/Lifecycle_prefix

אישית, אני לא משתגע על זה שיש לנו נקודות עניין על הצעות לשמורות שאין לנו שום ידיעה כמה שנים הן בסטטוס הזה והאם אי פעם הן תוכרזנה.

**Comment by Tsurha** [comment]
לטעמי נקודות שיש בהן עניין למטייל, הן אחלה. מבחינת המטייל שנהנה בטבע, משמעות ההכרזה של מדינת ישראל לא גדולה עבורו. חשוב הערך הנופי, העניין, הצמחיה... גם אם השטח בעייתי מסיבות סטטוטוריות להכרזה או שמשרדי הממשלה לא מתפקדים.

**Comment by amiad** [comment]
> לטעמי נקודות שיש בהן עניין למטייל, הן אחלה. מבחינת המטייל שנהנה בטבע, משמעות ההכרזה של מדינת ישראל לא גדולה עבורו. חשוב הערך הנופי, העניין, הצמחיה... גם אם השטח בעייתי מסיבות סטטוטוריות להכרזה או שמשרדי הממשלה לא מתפקדים.

להכרזה יש משמעות חוקית, למשל איסור טיול מחוץ לשבילים מסומנים. אם אתה רוצה לסמן נקודת עניין אז תתייג אותה נכון (למשל פארק).

**Comment by HarelM** [comment]
זה לא המקום לדיוני תיוג.
כמו שכתבתי, אני מסכים עם @Tsurha שיש ערך לנקודות.

**Comment by zstadler** [comment]
@Tsurha 
דיון התיוג התחיל לפני כמה ימים בקבוצת הטלגרם https://t.me/OSM_Israel
אתה מוזמן להצטרף ולהסביר שם את ההצעה שלך

**Comment by HarelM** [comment]
הדיון פה, והדיון על תיוג הם שני דיונים נפרדים.
ברשותכם, אסתיר את כל ההערות הנוגעות לתיוג.
