### ISSUE TITLE
When recording, a maximized elevation graph cannot be restored

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#2025]
### What happened?

When recording a track, the elevation graph can be maximized to the full width of the screen. At this point, the stop-recording button hides the graph's restore-width button, and the graph is maximized until the recording is stopped

### What steps will reproduce the bug?

1. Load a saved route
2. Show its elevation graph
3. Activate recording
4. Put the device in landscape orientation
5. Maximize the width of the elevation graph

### What I expect to happen

I would like to be able to restore the width of the elevation graph without stopping the recording

### Platform

- [X] Israel Hiking Map app
- [ ] Israel Hiking Map site in a browser

### OS Name and Version

Android 11

### Additional information

![Screenshot_2024-08-22-14-15-45-92_a7f83ac72205e460c5812fb7b368a407](https://github.com/user-attachments/assets/f6b149a3-ea1f-409f-a26e-96adca58a5df)

https://github.com/user-attachments/assets/61be07ca-e045-4e96-b4c7-e9521634d386

**Comment by HarelM** [comment]
Is this a phone or a tablet?

**Comment by zstadler** [comment]
phone

**Comment by HarelM** [comment]
In that case you can turn the phone and close the graph. 
Landscape mode has a lot issues, and it's not really supported...

**Comment by zstadler** [comment]
Most issues in landscape mode can indeed be worked-around by temporarily turning the phone to portrait mode. This is not the case here. The expand/narrow button does not show in portrait mode. As a result, there no way to restore a narrow graph view without stopping the recording.

I suggest to move the buttons from the top-left corner of the graph to the bottom-right or the bottom left. 

![Screen Shot 2024-09-15 at 10 13 41](https://github.com/user-attachments/assets/a3c175d3-9ea1-40bd-a9bc-061a6586a382)

![Screen Shot 2024-09-12 at 15 05 03](https://github.com/user-attachments/assets/99767a4d-23a6-4beb-a463-50fbfb8ca6ac)

These is a relatively simple changes in the CSS for which I'll be happy to send a PR

**Comment by HarelM** [comment]
Ah, I see.
In that case I think it would be better to limit the width of the graph in landscape mode to have the full screen minus the width of the left buttons, the other suggested options are less intuitive from the user perspective, I think.
It should also be a simple CSS change, hopefully.

**Comment by zstadler** [comment]
Is this what you had in mind?

![Screen Shot 2024-09-15 at 17 55 19](https://github.com/user-attachments/assets/a3ec0854-3f37-4647-80de-d4a221294265)

**Comment by HarelM** [comment]
Yes, exactly.
