### ISSUE TITLE
Update OruxMaps Download page in the repository

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#204]
@zstadler please let me know if there are files that are not in the repository and should be there or files that needs to be updated according to what's on the server, I want to be sure the only file that I need to make sure I don't delete is the sqlite database file.

**Comment by HarelM** [comment]
@zstadler the only files I now make sure I don't delete are the oruxdownload files. I intend to delete them soon after we advertise the new links in facebook.
Besides the database of course.

**Comment by zstadler** [comment]
I'm not sure I understand the question, as there are files from 2 repositories and generated files.

You are welcome to delete any file in the server location. 
Please do not delete files taken through the virtual directories from the Map installation and operation location.

**Comment by HarelM** [comment]
I'm talking about files that were added manually to the site and were not checked-in to the site repository, not talking about generated files.
The only files I know of are the ```Oruxmapsdownload.html``` and ```OruxmapsMTBdownload.html```.
Did you by any chance added other files I'm not aware of?
I know you advertised those files somewhere so I'm giving you a heads up that I'm planning on deleting them...

**Comment by zstadler** [comment]
```OruxMapsDownload.html``` was published [in several places](https://www.google.com/search?q=Oruxmapsdownload). I suggest the Download page for OruxMaps offline maps will use this name rather than ```Oruxmaps.html```. 
Otherwise we'll need to create a redirection or leave broken links in the forums.

A google search did not find any reference to OruxmapsMTBdownload, so I assume it was never published.

**Comment by HarelM** [comment]
The link you have supplied doesn't show anything relevant for my google account.
I can't continue supporting these redirections. Let's discuss publishing of new pages next time before posting them in all kinds of forums...
I'll change the file name to ```OruxmapsDownload.html```. which will work with the relevant postfix of the map type for direct download (I tested the direct download last night and it only works for firefox in android, other browsers have a security restriction to prevent this from happening without a click).
Note that now the download won't begin automatically for this address as it did before, instead only when adding the "#" postfix it will.

**Comment by zstadler** [comment]
I've corrected the search link above. It should show that the link was published on Facebook, Groopy, Jeepolog, and other sites.

[This StackOverflow topic](http://stackoverflow.com/questions/24571548/javascript-how-to-detect-if-the-custom-url-scheme-is-available-or-not-availabl) describes a way to determine in JavaScript if a URL Scheme is available or not. Please see if you can adapt it to our need to use http/https download of the zip file if the "orux-map:" scheme is not available.

**Comment by zstadler** [comment]
I think this issue can be closed.

**Comment by HarelM** [comment]
You wrote about the option to check if the schema is available, this is the only reason I kept this open.
If your last commit handled that then you can close the issue.

**Comment by zstadler** [comment]
The OruxMaps download page seems to be working fine for Android and non-Android browsers after [Updated oruxmaps download page](9625d3a8d71155bdeed281349625c9122dc70503) #204.

In retrospect, I think the current approach is better than checking for the registration of the scheme because it will give an error when downloading to an Android device where the orux-map scheme is not registered.

**Comment by HarelM** [comment]
Closing then.
