### ISSUE TITLE
Trace title doesn't match the planned route name when adding a trace to the map

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#2043]
### What happened?

I have renamed one of my traces and then added it to the map. The name of the route was the original name of the trace.

### What steps will reproduce the bug?

1. Profile -> My Traces
2. Select a trace
3. Edit
4. Rename it (you may add extra text that can be erased later)
5. Approve
6. Click the "+" button
7. Open "Routes, Maps, and Overlays"
8. Check the name shown in the Routes section

### What I expect to happen

The name shown in the routes list should be the new name

### Platform

- [ ] Israel Hiking Map app
- [X] Israel Hiking Map site in a browser

### OS Name and Version

Win 11 pro

### Additional information

Renamed trace to add:
![image](https://github.com/user-attachments/assets/50c383f4-7e87-49c3-b1b7-dfc4c15aa715)

Name of added route:
![image](https://github.com/user-attachments/assets/153d8517-383c-43bb-84bd-d278914c18d3)

**Comment by HarelM** [comment]
I don't think it has anything to do with rename... The name of the recording isn't really it's name, because you can't use special characters in OSM (hebrew characters for example), so the description is being used as the name, which caused some bugs in the past, and apparently this big as well I believe.
Unless I'm missing something here - even if you don't rename you get this "unwanted" behavior, right?

**Comment by zstadler** [comment]
You are right. one. The traces list shows the only the trace description while the route list shows only the trace name.
When looking at IHM-created traces, both have the same date and time, which allows you to correlate them.

When the user edits the trace description, the ability to correlate the trace and route is lost

![image](https://github.com/user-attachments/assets/ad0dcb2b-3ba3-4aff-b26c-b0bc5cb30eec)

**Comment by zstadler** [comment]
One option to improve the situation, is to copy the description from the OSM trace to the route description.

For example, the OSM trace has this description

![image](https://github.com/user-attachments/assets/1f5451aa-3c30-4cc6-985f-eaf001dd2178)

Yet, the route created from it does not have a description

![image](https://github.com/user-attachments/assets/7fa72d4a-4e42-46d2-bd6a-5639fe1b141c)

If I copy (by hand) the description from the OSM trace to the route, it would show during mouse hover or long press
![image](https://github.com/user-attachments/assets/f8faf629-f1ce-46fa-aaa4-6c6b85d29029)

It's not an optimal solution, yet it provides some way of associating the route with the trace it represents.

**Comment by HarelM** [comment]
In all places related to traces we use the trace description as its title, this case shouldn't be different.
It's a question if this should be done in server side or client side, and what should happen for traces that were not recorded using our app, but I think that's a minor issue to take into consideration.
Right now I think a good solution would be the following using client side only code:
![image](https://github.com/user-attachments/assets/4e63f4f6-d268-4997-b5e7-3f812efcb0c0)
