### ISSUE TITLE
Error when using the iOS app without network connection

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#2045]
### What happened?

When there is no network connection, the iOS app shows an error message.

![Untitled](https://github.com/user-attachments/assets/6ffa45fb-b39e-4fcd-bd28-dfbba80ddc7e)

If I understand correctly, the "לא ניתן לפתוח את הקובץ: lookup" is shown repeatedly/when switching to show the app, which makes the use of the app very difficult.

### What steps will reproduce the bug?

1. Clean install of the app on an iPhone
2. Start the app and complete the initialization dialog and process.
3. You may or may not login
4. Exit the app
5. Start flight mode and turn-off the WiFi
6. Start the app
7. The above error message is shown
8. Restore network connection
9. The map would not show, although the dot is green. Panning, zooming in and out and activating the GPS don't have an impact

### What I expect to happen

Same as on Android - No such error message

### Platform

- [X] Israel Hiking Map app
- [ ] Israel Hiking Map site in a browser

### OS Name and Version

iOS 17.6.1

### Additional information

User report with logs was received [by mail](https://mail.google.com/mail/u/1/#label/Support/FMfcgzQXJkXrrJtkhXfsFpcKqgWjfhxB)

**Comment by HarelM** [comment]
Seems like this is related to the latest addition of the application update check when the app starts.
I have opened an issue here:
https://github.com/capawesome-team/capacitor-plugins/issues/317

I have tested that wrapping the call with try-catch solves this issue, but I would like to wait and see what is the response from app-update maintainers on this matter.
