### ISSUE TITLE
Missing style-layer in style-based personal-layer

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#2052]
### What happened?

A personal overlay layer is using a MapLibre style with two style layers.
1. A fill layer for polygons
2. A symbol layer for the polygons' names.

However, when used with IHM, the names are not shown. Only the fill style layer is seen on the map.

### What steps will reproduce the bug?

1. Open the map [here](https://israelhiking.osm.org.il/map/13.80/30.8423/34.7988)
2. Create a new overlay using `https://raw.githubusercontent.com/IsraelHikingMap/VectorMap/master/Styles/park.json`

Alternatively, open [this share](https://israelhiking.osm.org.il/share/PfLLE4TIhZ)

### What I expect to happen

I expect to see the NP name, [as provided by the second style layer](https://github.com/IsraelHikingMap/VectorMap/blob/c4e0ad56dc00bcd20b899f082ed93835bf6b6e17/Styles/park.json#L31) of the added overlay

![image](https://github.com/user-attachments/assets/3bbba969-8665-43a6-a4b7-9945f7643b17)

Instead, I see the name from the base map, covered by the overlay's fill

![image](https://github.com/user-attachments/assets/cfb68613-3296-4bd8-ab6b-375a171492de)

### Platform

- [X] Israel Hiking Map app
- [X] Israel Hiking Map site in a browser

### OS Name and Version

All

### Browser Name and Version

All

**Comment by HarelM** [comment]
In the style it says: ""metadata": {"IHM:overlay": false}," for the name layer...
![image](https://github.com/user-attachments/assets/73c38e44-f82b-47ad-8bc6-34d3eec5f6e4)

**Comment by zstadler** [comment]
Ooops...
