### ISSUE TITLE
Can't get the GPS marker menu

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#2057]
### What happened?

Clicking the GPS marker did not bring up the relevant menu.

### What steps will reproduce the bug?

1. Click on show my location
2. Click on it again to deactivate location tracking
3. Click on it again to enable it again
4. Click on the GPS marker -> Menu doesn't show up

### What I expect to happen

The menu should popup when clicking the GPS marker, always.

### Platform

- [X] Israel Hiking Map app
- [ ] Israel Hiking Map site in a browser

### OS Name and Version

Android 14

### Browser Name and Version

N/A

### Additional information

@zstadler reported this bug while recording, so it might be a different scenario.
@zstadler do you remember if the steps defined here were made by any chance? and that this was the second recording after disabling the location and enabling again without exiting the app?
I'm trying to figure out if the steps to reproduce here were made in your case as well.

**Comment by HarelM** [comment]
I see the following issue in the console:
<img width="829" alt="image" src="https://github.com/user-attachments/assets/c70cc3e3-4de8-4ac7-81cf-ffe9a81b4c05">

This looks very similar to the following reported issue:
https://github.com/maplibre/ngx-maplibre-gl/issues/193

**Comment by zstadler** [comment]
I do not remember the scenario that caused this issue for me.
All I remember is that the only way to recover was to exit the app.

**Comment by HarelM** [comment]
This was fixed by using a version of ngx-maplibre that fixes this issue.
