### ISSUE TITLE
לא ניתן להגיע לנקודות רבות מהחיפוש

### ISSUE THREAD

**Issue by amiad** [IsraelHikingMap/Site#2059]
### What happened?

חיפשתי נקודה (למשל עין עקב). היא מופיעה בחיפוש אבל כשאני לוחץ עליה אני מקבל הודעה „אין אפשרות למצוא את נקודת העניין המבוקשת... ”
ניסיתי מקומות נוספים וחלק עובד וחלק לא. למשל עין עקוב, מדרשת בן גוריון, בית חורון, אילת לא עובדים.

### What steps will reproduce the bug?

1. חפש עין עקב
2. לחץ עליו בחיפוש
3. קבל שגיאה

### What I expect to happen

מעבר לנקודה

### Platform

- [ ] Israel Hiking Map app
- [X] Israel Hiking Map site in a browser

### OS Name and Version

Arch Linux

### Browser Name and Version

Firefox 132

### Additional information

![תמונה](https://github.com/user-attachments/assets/5ebbc023-0dd6-4965-814b-b402a60f78ee)

**Comment by HarelM** [comment]
בדיוק העליתי תיקון לזה, לדעתי.
תוכל לרענן את הדפדפן ולנסות שוב?

**Comment by amiad** [comment]
תוקן, איזה טיפול מהיר!
