### ISSUE TITLE
Search and route updates should run with map update.

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#206]
A single windows scheduler task should update the legend, tiles, routing and search. currently this task is based on two tasks.
Updater should start the process and know what to do when.

**Comment by zstadler** [comment]
There is some existing functionality that we need to preserve:

1. Legend update, just like updates for icons and the Map file, is done as part of pulling updates from Map repository. Currently, the [Git Fetch script](/IsraelHikingMap/Map/blob/master/Scripts/Batch/Git Fetch.bat) is launched before the map update, and it avoids the fetch if there is already an active Maperitive process.

2. The [map update Maperipy script](/IsraelHikingMap/Map/blob/master/Scripts/Maperipy/CreateAllMaps.py) also includes recovery from incomplete map creation processes.

We need to consider if the Updater will invoke them or replace them.

**Comment by HarelM** [comment]
I think that the first phase should be to reduce script to a single language - no more batch and python scripts calling to one another - only python should be used.
as part of this process some definitions should be added to reduce typos and enhance re-usability of strings etc.
We need to define which scripts need maperitive and which don't - those that do not use maperitive can be the candidates for migration to the updater process.
I think the legend part is no longer relevant, right?

**Comment by zstadler** [comment]
The legend update is no longer needed.

Is the Updater process also written in Python?

**Comment by HarelM** [comment]
No, The updater process is written in C# much like the server, they use common classes and technology, I meant that current update is written in C#, bstch and Python and first phase should be C# and python.
Second phase C# and maperitive (mapritive will use the relevant scripts since we can't and don't want to replace them).

Some clarifications about the updater: You can see the starting operations under ```IsraelHiking.Updater```, but this is mainly the program initialization, the code is under ```IsraelHiking.API``` and the main service is ```OsmDataService``` which is mostly focused on the elastic search database since the GH is written in Java and can be updated from command line while ES requires some pre-processing.

**Comment by zstadler** [comment]
If the goal of reducing the number of languages is clarity, I'm not sure how successful this will be.

For example, this [segment of the Git Fetch.bat](https://github.com/IsraelHikingMap/Map/blob/master/Scripts/Batch/Git%20Fetch.bat#L6-L10) script is clear and simple:
```bat
@ECHO Check if Maperitive is running
@TASKLIST /FI "IMAGENAME eq Maperitive.exe" | find "Maperitive.exe" && (
  @ECHO ==^> No Git pull
  @GOTO :END
)
```

I wonder how clear is the equivalent written natively in C# or python.

**Comment by HarelM** [comment]
The goal is better maintainability, when you have less languages it's easier to maintain.
Also, and it might be only my opinion, batch files are good when it comes to happy flow but are very bad when something is not working right.
The avove line can be easily written almost the same in both c# and python using the processes windows API.

**Comment by zstadler** [comment]
It's a matter of preferences where we differ, and that's OK.

**Comment by HarelM** [comment]
@zstadler, Assigned it to you as discussed over the phone as part of incremental tile update task.

**Comment by zstadler** [comment]
We agreed that triggering of all OSM DB updates is part of the "Incremental Tile updates" - IsraelHikingMap/Map#108 issue.

There are no plans to reduce the number of implementation languages as part of that issue.

**Comment by HarelM** [comment]
Closing in favor of #350.
