### ISSUE TITLE
Searching for coordinates doesn't add a point on the map

### ISSUE THREAD

**Issue by Shemesh** [IsraelHikingMap/Site#2077]
### What happened?

אחרי חיפוש קורדינטות בשדה החיפוש לא מתווספת נקודה חדשה. בעבר כן היתה מתווספת נקודה אבל זה הפסיק לעבוד.

### What steps will reproduce the bug?

- חפש קורדינטות בשדה החיפוש

### What I expect to happen

מצפה שיתנהג כמו בעבר - תתווסף נקודה שניתן לערוך בקורדינטות שחיפשתי

### Platform

- [X] Israel Hiking Map app
- [X] Israel Hiking Map site in a browser

### OS Name and Version

all

**Comment by HarelM** [comment]
תודה רבה על הדיווח! נבדוק את הנושא.
