### ISSUE TITLE
Add elevation profile to public routes

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#2079]
### What is the problem this feature will solve?

A user wrote us an e-mail requesting to see the elevation profile of public routes.

To reproduce:

1. Open a public route, such as [סינגל עינב](https://israelhiking.osm.org.il/poi/OSM/relation_1283315)
2. Click on the "+" button
3. The statistics shows its length, but the elevation profile is empty

![image](https://github.com/user-attachments/assets/b1b115d1-5315-4903-bfa4-4fb780f5da76)

![image](https://github.com/user-attachments/assets/2b2b9dba-c3b5-4cf9-8110-a1c58e011162)

### What is the feature you are proposing to solve the problem?

When a public route is converted to a private route, add its elevation info.

### What alternatives have you considered or tried?

As far as I know, the only alternative is to re-trace the route.

### Additional information

What should be done with public routes that already have elevation information? Should that information be overwritten?

**Comment by HarelM** [comment]
For external routes the data is coming from the server where elevation is added when returning the feature.
For OSM related entities this was solved in the past by the server too, but now since OSM related entities are coming straight from OSM there's a need to enrich the height profile when converting to a route.
Current elevation API supports only GET request which is limited to a maximum amount of characters, so there's a need to add a server side POST call to get the relevant elevation for the relevant "missing" points (all of them in case of OSM).

I'll see if I have an idea how to solve this better as I have my concerns about scaling this solution...

**Comment by zstadler** [comment]
Is it possible to do that on the client side, potentially using the DEM source?

**Comment by HarelM** [comment]
I think the accuracy of this won't be good for long routes, or will be too slow...

**Comment by zstadler** [comment]
As far as I understand, the accuracy is based on the accuracy and resolution of the underlying DEM and the client gets the best DEM data we have.

**Comment by HarelM** [comment]
No, that's not true, the client shouldn't get all the tiles from Israel for example in order to calculate the elevation of שביל ישראל, when rendering it gets only the zoom 7-8 DEM tiles, which is good enough for rendering, but otherwise horrible for elevation graph...

**Comment by zstadler** [comment]
Currently, IHM downloads DEM tiles at the max zoom level: 12, where the resolution is about [40 m/px](https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Resolution_and_Scale). 

![image](https://github.com/user-attachments/assets/1faf319e-d064-4473-9db6-576e7b3096e6)

The global DEM is available up-to zoom level 11, where the resolution is about 75 m/px.

**Comment by HarelM** [comment]
It downloads them when the map's zoom is higher, but when looking at שביל ישראל, it can't download all these tiles in a reasonable time, much like the render can't and it will use a lower resolution, as can be seen here:
![image](https://github.com/user-attachments/assets/5986e679-211d-4919-b365-2b004e8bddbd)

We should probably discuss this on the phone, I'm not sure we are talking about the same problem...
