### ISSUE TITLE
Gaps are created in a route when using mixed-snapping mode

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#208]
The route created on the site should be fully connected. Currently, gaps can be created when changing from snapping to non-snapping segments and when changing from non-snapping to snapping.

For example, there are gaps between all 3 segments of [this sample route](http://israelhiking.osm.org.il/#/?s=vFCOwaVQMP).

**Comment by HarelM** [comment]
Routing can work only for known OSM paths. meaning that if I click in a place where there are no ways the routing will succeed bug will create a dot that is not part of the route.
for example here:
http://israelhiking.osm.org.il/#/?s=Gz66lthmfl
When you edit this route you'll see that the route points are not on the track themselves.
And this is not a mixed mode.
What do you think we should do? add a straight line from the route point to the routing line?

**Comment by zstadler** [comment]
This is an excellent example. It shows that when routing is used, the points the user adds are "hints" or "handles" for the route to be created. 

IMO, There is no need to go through points added in routing/snapping mode, as the user expects the site to look for the nearest OSM way using the handle position as a hint.

As for mixed mode, I suggest that route is created without any gaps in the following manner:
- When changing from a routed to a non-routed segments, the end point of the produces route, i.e., the snapped position of the point, should be used as the starting position of the non-routed segment.
- when changing from a non-routed to routed segments, I prefer the final route to connect the end of the non-routed segment to the snapped beginning of the routed segment. The alternative where the non-routed segment should end in the snapped beginning of the routed segment is problematic IMO.

**Comment by HarelM** [comment]
This is not entirely true for the first point, I don't remember why, but there was a reason to make the first point a segment of its own (the first point route is two points one on top of the other - you can event see a small blue dot there). but let's leave this issue a side for a moment.

I think I agree with your suggestion about which point to take although this will mean that when I change from non-routed to routed and create anther segment the position of the end of the non-routed segment will move a bit to the starting position of the routed segment.
Are we comfortable with this nuance?

**Comment by zstadler** [comment]
For a routed segment after a non-routed segment, I suggested a different approach: the poly-line path of the segment will be created by taking the poly-line result of the routing and prepending the end-point of the previous segment.

Terminology clarification:
I assume each segment entity is defined by a single user-provided end point ("handle"). Each segment, except the first segment, also has a computed poly-line path. The path is created using the segment's end point and the routing mode together with the end of the previous segment's path.

**Comment by HarelM** [comment]
I see. That could probably work too. I guess my concern now is that the routed segment has a part that it did not get from the routing server, which I'm not sure is good or bad.
This assumes will be applied only when the previous segment is non-routed and the current segment is routed, it will not apply when changing routing types, right?

**Comment by HarelM** [comment]
I think I managed to fix the routed after non-routed and non routed after routed when handle is not on a way.
Published to site, please make sure it works for you as expected.
We can discuss the start point if you want.

**Comment by HarelM** [comment]
This just created a whole mess when dragging a point... I'll see what I can do...

**Comment by HarelM** [comment]
I hope this will solve it, but 2am is not a really good time to do it...

**Comment by HarelM** [comment]
Ran a script on the database to find such cases and fix them, looks OK, but hard to tell.
I'll Update the site and hope for the best.
