### ISSUE TITLE
Some public routes don't show on the map

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#2080]
### What happened?

Some external routes from Jeepolog, iNature and Nakeb are not shown on the map as POIs

### What steps will reproduce the bug?

1. Show all public routes on the map
2. Open any of the following URLs
   - https://israelhiking.osm.org.il/poi/iNature/6072
   - https://israelhiking.osm.org.il/poi/Jeepolog/3784
   - https://israelhiking.osm.org.il/poi/Nakeb/477
3. Hide the POI
4. There is no POI from the public layers

### What I expect to happen

The POIs should be visible with the public POIs layer

### Platform

- [X] Israel Hiking Map app
- [X] Israel Hiking Map site in a browser

### OS Name and Version

Any

### Browser Name and Version

Any

### Additional information

This seems to affect public routes that have a LineString geometry

**Comment by HarelM** [comment]
This is related to the change made in the migration to tiles POIs here:
- #1979

Returning non points to the cluster is what caused this issue.
