### ISSUE TITLE
A gray rectangle

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#211]
A gray rectangle covers the top of the browser window for a second when the map loads.
Chrome on windows 10.

**Comment by HarelM** [comment]
Related to the heights graph. I'll see if I have time to fix it, but since it happens before loading the page it doesn't really bother me...

**Comment by zstadler** [comment]
On the other hand, it looks unprofessional. 
I vote to increase the priority.
Perhaps it would be combined with displaying a "loading" animation

**Comment by HarelM** [comment]
nitpickers...
