### ISSUE TITLE
Improve directory listing format

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#212]
For example, the directory listing for http://israelhiking.osm.org.il/oruxmaps:
- Shows the date in MM/DD/YYYY format rather the Israeli standard D/M/YY
- Shows integer size numbers, such as 2 Gb, 732 Mb while showing 2 significant digits, such as 2.2 Gb and 730 Mb would be more appropriate.

**Comment by zstadler** [comment]
What do you think about using [toPrecision(2)](http://www.w3schools.com/jsref/jsref_toprecision.asp)?

**Comment by zstadler** [comment]
What do you think about using [toPrecision(2)](http://www.w3schools.com/jsref/jsref_toprecision.asp)?

**Comment by HarelM** [comment]
Didn't you want a better percision? I did ToString("F2") for mega and giga.

**Comment by zstadler** [comment]
The request was for "showing 2 significant digits", and included an example of changing from 732 Mb to 730 Mb. I think more than 2 significant digits is too much.
Actually, showing the seconds in the modification time is also too much.
