### ISSUE TITLE
Support for drag-and-drop of URLs

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#215]
It would be nice to be able to drag a URL and drop it on the map to see it.

For example, [Jesus Trail – Nazareth to Capernaum v5.0](http://jesustrail.com/downloads/gps_downloads/Jesus-Trail-Nazareth_to_Capernaum-v50-detailed.gpx), posted on [GPS on the Jesus Trail](http://jesustrail.com/route-maps/gps).

Currently, the file needs to be downloaded to a temporary location and dragged or opened from there.

**Comment by HarelM** [comment]
That's not entirely correct, you can use the ?url= and paste the url.
How would you drag and drop a url? Drag and drop a file I can understand but where would you drag the url from?

**Comment by zstadler** [comment]
Drag-and-drop is much more easy than copy-and-type-and-paste.

You can drag a URL from one web page to another web page , just as you would for a file. This works with Firefox, Chrome, IE, and probably other browsers too.

The "http://IsraelHiking.osm.org.il/#?url=" prefix has several disadvantages compared to drag and drop:
- It is long, and cumbersome to type.
- It is a well kept secret. 
- Even when someone shares such a URL, potentially with an arbitrary test, it will not show after the map is loaded.
- For the same reason, you cannot use it in a bookmark aimed at avoid re-typing.

**Comment by HarelM** [comment]
I was not aware of the ability to drag and drop a url (which kinda tells something about this feature request).
I also don't see an easy user experience that I can think of.
With files you'd have another windows with the file on top of the browser where you would drag the file into the browser, but with a url you'd need another browser window which is not taking the full screen and drag it from there - I just don't see why a user would do it.
Seems to me like a feature no one would use...

**Comment by zstadler** [comment]
The user scenario is much simpler and useful. There is no need for a
separate browser window:
- You browse through some hiking sites and find a GPX for a trail you'd
like to see on the hiking map.
- You open Israel Hiking on another tab, if it is not already open.
- You drag the URL of the GPX from to the IHM tab on the tabs bar/ruler
- When the IHM tab is shown, drop the link on the map.

Having just heard of the URL drag and drop, I assume you also didn't know
that you can switch between tags by hovering the dragged URL over the tabs
bar/ruler.

**Comment by HarelM** [comment]
Doesn't work in Firefox and IE.
