### ISSUE TITLE
Multiple attributions for multiple layers

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#218]
Also if the text can be shortened and reduced in size. It's ugly.

**Comment by zstadler** [comment]
I see "ugly" text because URLs are printed, but I don't see any duplication

<img alt="credits screenshot" src="https://cloud.githubusercontent.com/assets/1304610/18208485/5c055efe-7138-11e6-93c5-d3b2cd1d5401.png">

**Comment by HarelM** [comment]
which browser? which os? 
doesn't look like it happens on chrome, 
firefox doesn't have a preview and I don't want to print anything right now...
IE is not even on my check list I hope no one is still using this browser...

**Comment by valleyofdawn** [comment]
Chrome on windows 10.
I'll produce a demo pdf when I can.

בתאריך 3 בספט׳ 2016 12:58 PM,‏ "Harel M" <notifications@github.com> כתב:

**Comment by zstadler** [comment]
The doubled attribution is unrelated to printing. It shows also on the interactive map with Chrome on Win 10:

<img width="564" alt="2016-09-03 20_32_12-" src="https://cloud.githubusercontent.com/assets/1304610/18226581/913ab35c-7215-11e6-957b-2ee8b2be6f97.png">

It seems it does not hide the IHM attribution, not even on Google Earth of custom maps.

**Comment by HarelM** [comment]
No sure there's much I can do, this looks like a leaflet bug...

**Comment by HarelM** [comment]
The only thing I can think of is to remove the attribution from overlay layers (olny the IHM trails is relevant in this bug) since I can't remove the attribution after a layer is created.

**Comment by HarelM** [comment]
This happens only when using MTB map and hiking trails since they don't share the same attribution.
I can't fix this without changing the attribution and I don't think I should change it.
So closing this for lack of public interest.
