### ISSUE TITLE
Remove leaflet from the attribution

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#220]
Just as the Bootstrap was removed from the attribution in ebc5a18401d4c8de8c02fe081876d7b1fefca9e7

**Comment by HarelM** [comment]
Since this is the main framework we are using I'm not sure we can remove their attribution, doesn't feel right...

**Comment by zstadler** [comment]
Many respected sites, such as Facebook and Foresquare, use leaflet and do
not have attribution for it.

IMHO We have 3 main value engines behind the site: map presentation,
routing, and search. Yes, Leaflet was our first love :-)

**Comment by HarelM** [comment]
It appears I never added leaflet, it is added by the framework itself, I'm not planning on writing extra code to try and override it...

**Comment by zstadler** [comment]
Fair enough
