### ISSUE TITLE
"Locate me" icon is misleading

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#221]
A compass arrow is usually for map rotation by the compass, which I wish we had.

A "locate me" button is usually something like
http://www.flaticon.com/free-icon/target-with-circle_76992#term=circular%20target

**Comment by HarelM** [comment]
Redesign was based on:
http://www.openstreetmap.org/
I thought about keeping it as similar as possible, but now I see there are other icons there that are not very well picked (mainly the share).
Do you have another source? this source explicitly requires to place an attribution on each icon for the author and site...

**Comment by zstadler** [comment]
I've created one. What do you think?
[Target.zip](https://github.com/IsraelHikingMap/Site/files/457733/Target.zip)

**Comment by HarelM** [comment]
Very nice, I'll try and add it in the next publish.

**Comment by HarelM** [comment]
Initially I used this icon:
http://fontawesome.io/icon/crosshairs/
But I didn't like it much...
Unfortunately the third party control I'm using is not very friendly and does not allow me to add an img tag inside the button, this makes adding the above icon very hard.
Please see which Icon in fontawesome suits you best.
I can switch it back to crosshairs if you prefer.

**Comment by zstadler** [comment]
I think http://fontawesome.io/icon/bullseye/ would be a bit better.

**Comment by HarelM** [comment]
I don't think people will think this represents a location button, IMO this is even more misleading than the first icon.

**Comment by HarelM** [comment]
I'm pleased with the current icon (crosshairs), what about you? Close this issue if it suits your needs.

**Comment by zstadler** [comment]
The current icon is great
