### ISSUE TITLE
Add gradient to height profile

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#224]
Either as an alternative graph (going from say -25% to +25%)
or as a tip when hovering over the graph.
Hight difference/horizontal distacne *100
=שיפוע

**Comment by HarelM** [comment]
The easiest way will be to add it inside the tooltip.
Is the formula above calculated between two consecutive points?

**Comment by valleyofdawn** [comment]
Yes. But it pertains to a point, like instantaneous velocity.

**Comment by HarelM** [comment]
Added although I don't got the feeling it works correctly, can you test it a bit to see if it shows somewhat correct results, if not I'll remove it...
