### ISSUE TITLE
Simpler way to export GPX to orux

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#225]
Ideally, through the share icon.
Maybe it can be transferred to the OruxMaps personal track DB on the cloud?
Worth contacting Jose Velasquez.

**Comment by HarelM** [comment]
I've sent him an e-mail, let's see what he reply.

**Comment by HarelM** [comment]
From the communication with Jose:

> OruxMaps uses some APIs, like gpsies or everytrail to allow users to search/download tracks from those sites.
The app can also manage links to .gpx or .kmz files. 

I understood the following:
Orux doesn't have a cloud database just a local one.
Orux can search GPSies site (and others) to download a route.
From the below forum I understand that the import of GPX files to GPSies is not public:
https://groups.google.com/forum/#!topic/gpsies/O_5hliNWcac
I'm starting to think that there's no easy solution here and whatever I'll add just make the share dialog more complex without a good reason.
