### ISSUE TITLE
Add support for reading kmz files

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#226]
They are just zipped kml files, but gpsbabel does not read them.
We can use [7-zip](http://www.7-zip.org/), which is already installed on the server, to do on-the-fly unzip.

**Comment by HarelM** [comment]
There's no need to use 7-zip we have "DotNetZip" reference in our code that can be used in memory instead of running a process, are you sure GPSBabel does not support this?
Can you link to a kmz url so I'll be able to test it once implemented?

**Comment by zstadler** [comment]
Yes, GPSbabel does not have KMZ support.

As an example we can use [חורבת דנעילה](http://www.eyarok.org.il/uploads/files/%D7%93%D7%A0%D7%A2%D7%99%D7%9C%D7%94.kmz) taken from [this e-yarok page](http://www.eyarok.org.il/trip.aspx?id=26).

Note that GPSbabel by itself does not recognize file extentions. it's [our code](https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.API/Services/DataContainerConverterService.cs#L107-L121) that does it, for a subset of the types.

**Comment by zstadler** [comment]
If we ever want to automate file extension recognition for GPSbabel, we can use its ```-^[0-4]``` flag (```-^^[0-4]``` on DOS-based systems)  to extract details of all supported formats.

**Comment by HarelM** [comment]
@zstadler I now see how URL drag-and-drop is useful, it was a real treat to test it using this feature, sorry for doubting :-)
