### ISSUE TITLE
KM marks

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#23]
Can be useful. Should be minimal and optional.

**Comment by HarelM** [comment]
This is not clear, please elaborate.

**Comment by valleyofdawn** [comment]
Add a marker with the number of kilometers so far every 1KM along the route. Should be optional and not obstruct the view too much.

**Comment by HarelM** [comment]
I don't think this it is necessary if you'll have the total route length - I think it will clutter the map.
I also don't want to add more buttons, I think we have enough as it is.

**Comment by valleyofdawn** [comment]
Some route planners have it. We can definitely live without it.

**Comment by valleyofdawn** [comment]
You can have a look at how it's implemented in http://gpsies.com and in https://connect.garmin.com/course/3112782

**Comment by HarelM** [comment]
Shouldn't be hard to implement, I'll think of an elegant way to add it to the UI, probably another button in the drawing panel, although it's getting very crowded over there...
Marking as "Low".
