### ISSUE TITLE
Route "Upload" is stuck if an error is found

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#230]
As an example, "upload" a text file and the spinner keeps on spinning.
This is also the case if a "real" problem is found while running GPSbabel.

**Comment by HarelM** [comment]
Can you share such a file? can you also elaborate a bit on the steps to reproduce?

**Comment by zstadler** [comment]
Turned out to be a problem on the server

**Comment by HarelM** [comment]
Duplicate of #231
