### ISSUE TITLE
Cannot load a gpx file created by GPSbabel

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#231]
The gpx file in the attached zip was produces by GPSbabel from a twl file.
It looks like a good GPX file, but it would not load.

[GPSbabel.zip](https://github.com/IsraelHikingMap/Site/files/468470/GPSbabel.zip)

**Comment by HarelM** [comment]
Can you also attach the original twl file?

**Comment by HarelM** [comment]
I think there's an issue with permissions on the server since GBSBabel had stopped working completely.
I tried to fix it and now it looks like it is working, can you check?
If it's OK now I'll close both bugs.
