### ISSUE TITLE
Improve About menu

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#232]
I propose 

- Learn how to add and edit OpenStreetMap maps with our {{link}}YouTube tutorials{{linkend}} 

- למד איך להוסיף פרטים ולערוך את מפת OpenStreetMap בעזרת {{link}}סרטוני היוטיוב{{linkend}} שלנו

**Comment by HarelM** [comment]
Looks good to me.

**Comment by zstadler** [comment]
The link is to
https://www.youtube.com/playlist?list=PL8pYDecWd7EjQIyJpPAwSH3UbeZzzQpNo

**Comment by valleyofdawn** [comment]
OpenStreetMap >>OSM
Already explained in the text.

**Comment by zstadler** [comment]
I deliberately changed OSM to OpenStreetMap becausd the use of TLAs is a barrier for new comers. 

We all know that TLA is a Three Letter Acronym, right... :-)

**Comment by valleyofdawn** [comment]
Yes but 2 lines up you explain what it is, unnecessarily long text is also
a barrier.

**Comment by HarelM** [comment]
@zstadler, @valleyofdawn I want to add some info about us and to make the about text better.
zstadler suggested to add the project goals as listed in the facebook group.
I think a short paragraph on each of us can be nice, either in the same window or add a dialog with all this data using a "see more..." link, what do you say?
Also I think the link above should be in the help menu and not in the about...?

**Comment by HarelM** [comment]
@zstadler @valleyofdawn any updates on this?

**Comment by zstadler** [comment]
I'm not sure I'd like this sharing. 
Can you give an example of what you thought you'd write about yourself?

**Comment by HarelM** [comment]
I don't know, I had a few thoughts, something short like:
The people behind this project:
Harel Mazor: Hiker, "It's on the web out there, you can use it from anywhere".
Guy Shakhar: Biker, "Every pixel counts!"
Zeev Stadler: Rider, "With our map you wont get lost".
But I must admit I haven't complete thought about it.
The above might be a bit too much so we can limit it to something more distinguish like:
Harel Mazor: Hiker, main focus: IHM web site.
Guy Shakhar: Biker, main Focus: Appearance and social networks.
Zeev Stadler: Rider, main Focus: IHM map.

**Comment by HarelM** [comment]
@valleyofdawn @zstadler any comments on this? are you against or for it?
I was also thinking about adding profile images, but it might be too much.
I really need your input on this as I can't make the decision on my own.

**Comment by HarelM** [comment]
Closing this without implementing anything due to lack of public interest.
