### ISSUE TITLE
The height graph should not be able to move outside of the map area

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#233]
For example, if the top of the height graph is moved outside of the map area, it is no longer moveable.
In addition, some of the graph titles and info are hidden.

<img width="532" alt="2016-09-14 16_48_00-israel hiking map" src="https://cloud.githubusercontent.com/assets/1304610/18514730/61cfa5bc-7a9b-11e6-8eac-47c6b2b7be95.png">

**Comment by zstadler** [comment]
I guggest that moving the other 3 edges outside of the map area will be impossible

**Comment by HarelM** [comment]
Left and top might be easy, I'm not sure how easy right and bottom will be so I kept it simple and just made sure you'll always be able to move it...
