### ISSUE TITLE
Increase accuracy of POI lat/lon

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#235]
The current Lat/Lon resolution is about 100 meters,

For example, see http://israelhiking.osm.org.il/#/?s=KF67yzI22k. The two edges of the route have the same lat/lon value white the are 141 meters apart.
- The NE point is at Lat 32.629°, Lon 35.119° (E 211478 m, N 726121 m)
- The SW point is at Lat 32.629°, Lon 35.119° (E 211386 m, N 726015 m)

It looks like the internal resolution is sufficient to show the 140 meter distance between the points using the ITM coordinates.

I suggest we use the standard OSM resolution: 7 decimal digits for the faction of a latitude degree and 6 decimal digits for the faction of a longitude degree:
  lat: nn.nnnnnnn, lon: nnn.nnnnnn

**Comment by HarelM** [comment]
I've noticed it today as well when trying to use the coordinates for the legend feature.
Can you think of other places we need this accuracy besides the POIs?

**Comment by zstadler** [comment]
The request was for 6 fractional digits (right of the decimal period) for Latitude and 7 fractional digits for the Longitude. Please see the [comment on committed code](/IsraelHikingMap/Site/commit/6dff78f0600d24fae3ad1a6cae636efafd68ae16#commitcomment-19067303)
