### ISSUE TITLE
Search does not find the city/place "חיפה" 

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#236]
Just a few roads with this name:

<img width="171" alt="2016-09-18 00_41_05-israel hiking map" src="https://cloud.githubusercontent.com/assets/1304610/18611100/ade4d892-7d38-11e6-8a1c-8b9e6422b542.png">

**Comment by HarelM** [comment]
Nice catch man! took me a while to figure out that a relation that is a place (only happens on big cities I guess) does not get booted up like places that are ways or nodes. good one!
