### ISSUE TITLE
Improve search experience

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#239]
* Add the place in case of a street name.
 * Improve current icons and add missing icons

**Comment by HarelM** [comment]
@valleyofdawn do you have a link to the icons you used for the legend? I think some of them can be beneficial to the search.

**Comment by zstadler** [comment]
Could we also enable search for short names, like "דן", perhaps only after an "enter" or a space character?

 BTW, I'm repeatedly surprised and confused when the search results are hidden after hitting "Enter".

**Comment by HarelM** [comment]
Yes, I agree about the enter... it confuses me too...
Currently the minimal number of characters allowed in the search is three, should it be reduced to two?

**Comment by zstadler** [comment]
My suggestion is that it will search for two characters if followed by a space or the enter is pressed

**Comment by HarelM** [comment]
I'll try and push the new site tonight after I'm done translating, I changed the enter function to search when there's nothing selected instead of closing the search, I think I'll be better now.
