### ISSUE TITLE
Improve sidebar vertical scroll

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#243]
Always show sidebar vertical scroll to avoid text jump when legend is expanded.

**Comment by zstadler** [comment]
It would be even better if the "Legend | Help | About" header of the sidebar will be excluded from scrolling so it will always be visible.

**Comment by zstadler** [comment]
Can you keep the title of the expanded section visible after the scrolling? It will enable closing the section and keep reminding what the section is about.

**Comment by HarelM** [comment]
No, doing this was difficult enough, not planning on doing a subheader too.

**Comment by zstadler** [comment]
It looks like you've fixed this, right!?
