### ISSUE TITLE
Green "start of route" circle is gone after reversing a route direction

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#244]
To reproduce:

- Create a simple route containing just a start and an end points.
- Exit edit mode. 
- The route would have a green and red circles marking its start and end:  
  <img width="100" alt="2016-09-28 12_48_49-israel hiking map" src="https://cloud.githubusercontent.com/assets/1304610/18908918/3e031fee-857a-11e6-9e14-71b70543d73b.png">
- Open the layers pane, edit the route, reverse the route direction, and confirm. 
- The newly reversed route does not have a green circle where the new start is:  
  <img width="106" alt="2016-09-28 12_49_11-israel hiking map" src="https://cloud.githubusercontent.com/assets/1304610/18909013/a0e9ac5e-857a-11e6-9135-e45ba80f4ad8.png">

**Comment by HarelM** [comment]
Good catch!
