### ISSUE TITLE
Allow specifying city names in search text

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#248]
Currently, adding a city name in the search removes the correct result.

For example, searching for "ויצמן" yields several results, including "ויצמן, תל אביב". However, searching for "ויצמן, תל אביב" does not yield "ויצמן, תל אביב" as part of the results.

**Comment by HarelM** [comment]
I'm not sure we want to go this road. This is not waze - I'm not searching here for an address, I'm searching for a geo-location.
Implementing it would require a lot of logic which I'm not sure I'm happy to add. the current search logic is complicated enough and I don't think it will yield better results after taking the above into consideration...

**Comment by HarelM** [comment]
Same problem to implement as #249.

**Comment by HarelM** [comment]
Maybe a pre-processing step can be done before sending the request to elastic - something like splitting the search term...? I don't know...
