### ISSUE TITLE
Use visibility within current map extent to prioritization of search results

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#249]
Give higher priority to search results that are included in the bounding box of the current map position.

For example, when searching for "ויצמן", while looking at the Rehovot map, it would be good to see
"מכון ויצמן" and "קבר ויצמן" in the list instead of the "ויצמן" streets in Tel-Aviv and Nahariyya.

Note, this is different than using the distance from the map center location. When using zoom 7, since all visible locations should be treated equally, all of Israel will have similar priority.

**Comment by HarelM** [comment]
I'm really don't want to touch the search logic as I don't feel comfortable enough with it. The fact that I managed to make it bend to my needs is nothing less than a miracle :-).
So I tend to pass on features that want to change the logic as I feel that every time I touch it I have a bigger chance of getting garbage instead of better results.
If you want to play with the elastic search engine on our server - running queries on it please go ahead.
if you find a good search query I can translate it to c#.

**Comment by HarelM** [comment]
Here is the current request we are sending:
You can use firefox on the server to do the following:
1. open filefox -> menu -> developer -> network
2. surf to: http://localhost:9200/osm/_search?pretty
3. click on the green request line or the right side "door" icon.
4. Click Edit and Resend
5. Change to "POST" 
6. Click send to get search results (in the response tab).
7. Play around with the body to achieve different results.
![image](https://cloud.githubusercontent.com/assets/3269297/19172027/76ae5fe8-8c28-11e6-942e-24f38a91200d.png)

```
{
	"size": 10,
	"query": {
		"function_score": {
			"query": {
				"dis_max": {
					"queries": [
						{
							"multi_match": {
								"query": "מנות",
								"fields": ["properties.name", "properties.name:*", "properties._name"],
								"type": "best_fields",
								"fuzziness": "auto"
							}
						},
						{
							"query_string" : {
								"fields" : ["properties.name"],
								"query" : "מנות",
								"boost": 1.2
							}
						}
					]
				}
			},
			"field_value_factor": {
			  "field": "properties.search_factor"
			}
		}
	}
}
```

**Comment by HarelM** [comment]
Do we still need this? Current implementation of POI (which is what we believe is relevant to the user) is presented on the current map, other search results are directed to the relevant place.
I believe this feature is no longer needed, if you agree please close, if you don't let's discuss this in private.

**Comment by HarelM** [comment]
Closing since there was no response...
