### ISSUE TITLE
POI behavior

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#25]
IMO, when clicked once, the text input box for naming should open in the edit mode and accept input without requiring 2 more clicks. Enter should also close the input box. Maybe the text should then hover above the POI?

**Comment by valleyofdawn** [comment]
Or maybe just tooltips, [like so] (https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-label/)

**Comment by HarelM** [comment]
This is the best I can do for now, seems like there is an issue with leaflet popup focus:
Opened an issue there:
https://github.com/Leaflet/Leaflet/issues/3766
