### ISSUE TITLE
Add note / report a problem button missing

### ISSUE THREAD

**Issue by yrtimiD** [IsraelHikingMap/Site#250]
I see more and more people become familiar with this map, hence more people can submit corrections to the map.
Will be very nice to add "Add note" button as original openstreetmap.org has.

**Comment by HarelM** [comment]
I don't see a lot of value for this feature, feels like "todo" or "fixme" comments in the code.
I looked over some of the comments described there and many of them doesn't really have a value.
The current site have an edit button for those cases - if you see a problem click this button and fix it :-).
But that's my current opinion, if you can convince me it's worth implementation I'll add it.

**Comment by yrtimiD** [comment]
Well, sometimes it's easier to add a short note about missing feature like drinking water, picnic site or camping. Editing isn't that simple yet. Even me as osm contributor sometimes prefer adding notes and editing later.

**Comment by zstadler** [comment]
Implementation-wise it would probably be quite easy to add a button & dialog that create a note on the OSM servers through the [dedicated API](http://wiki.openstreetmap.org/wiki/API_v0.6#Map_Notes_API).

However, as far as I can see, OSM notes are not an effective way to improve the map. [Browse the map notes](http://www.openstreetmap.org/#layers=N), and you can see many [notes that are a years old](http://www.openstreetmap.org/note/17355), [spam notes](http://www.openstreetmap.org/note/131205), and [notes left unresolved for months](http://www.openstreetmap.org/note/312651).

Adding a "add note"/"report a problem" button to the Israel Hiking Map would create a false expectation that the problems will be resolved by "someone", which is not the case.

Instead, as @HarelM wrote above, the site users are encouraged to fix the problems by editing the map.

**Comment by yrtimiD** [comment]
just found interesting statistics about notes:
http://resultmaps.neis-one.org/osm-notes
For Israel we have 423 open and 534 closed notes, and last one was opened today. So, I think, we do use notes, and better note than nothing.

On "Browse the map notes" you see only open notes, so this doesn't give you the right feel of note usage.

**Comment by zstadler** [comment]
I respectfully disagree with the statement that "better note than nothing". Notes create that false expectation that the problems will be resolved by "someone", while the "edit map" creates the expectation that "if you don't do it, no one else will". You can probably see that I like the later expectation...

We also don't have a feel for the contribution of the closed notes to the quality of the map...

**Comment by HarelM** [comment]
I agree with Zeev on this. 
If somebody really wants to do it he can easily use the regular OSM site, which is getting better and better as the time goes by, I assume that it will be even better than this is site soon as it seems that who ever is in charge on it has more time than I have :-).
Closing this... 
Thanks for the suggestion though, if you have any more ideas please feel free to open issues here.
I know that the process and discussion might not seem fair but we try to be very picky on feature we implement in order to keep the user experience focused and simple. feature that we feel can improve the user experience without complicating it are our top choices.
