### ISSUE TITLE
POIs from one GPX file are lost after opening another GPX file

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#251]
For example, after opening the GPX file from [Waypoints_20-SEP-16.zip](https://github.com/IsraelHikingMap/Site/files/512429/Waypoints_20-SEP-16.zip) we get 2 POI:
<img width="236" alt="2016-10-06 01_04_00-israel hiking map" src="https://cloud.githubusercontent.com/assets/1304610/19133433/d8dcdece-8b60-11e6-8f4e-123d783094e2.png">

After opening also the GPX file in [Waypoints_22-SEP-16.zip](https://github.com/IsraelHikingMap/Site/files/512428/Waypoints_22-SEP-16.zip) we get 3 new POIs, but the first two POIs are lost:
<img width="236" alt="2016-10-06 01_08_29-israel hiking map" src="https://cloud.githubusercontent.com/assets/1304610/19133537/71caec7a-8b61-11e6-8698-0581c9da40fc.png">

**Comment by zstadler** [comment]
Thanks!

**Comment by HarelM** [comment]
You are welcome! nice catch.
