### ISSUE TITLE
Google search results yields no site description

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#255]
![image](https://cloud.githubusercontent.com/assets/3269297/19327727/132d2ebc-90d9-11e6-8cfe-3eb3aa451aea.png)

**Comment by HarelM** [comment]
@zstadler @valleyofdawn the following text is what I added, it will appear in anywhere a link will be shared. If you have something better let me know:
Whether on foot, riding a bike or driving a 4WD vehicle, you'll find everything you need here in order to plan an outdoor trip.

**Comment by zstadler** [comment]
I think the description should be in Hebrew, with or without an English equivalent.

Minor change to the English - there should be a comma after "riding a bike"

**Comment by HarelM** [comment]
As far as I can tell, grammar-wise, there should not be a comma before the last "or" or "and" when listing stuff, but it might only apply to hebrew.
Is the description any good? would the following work for you:
בין אם אתם יוצאים לטיול רגלי, רכיבה על אופניים או נסיעה ברכב שטח, כאן תוכלו למצוא כל מה שאתם צריכים על מנת לתכנן את הביקור הבא שלכם בטבע.

**Comment by zstadler** [comment]
The Hebrew writing looks good!

You are also right about the comma rule applies to Hebrew. As for English, [see here.](https://en.oxforddictionaries.com/punctuation/comma#commas_in_lists)
