### ISSUE TITLE
Avoid exporting empty tracks

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#256]
This issue was [reported on Facebook](https://www.facebook.com/groups/994960670559126/permalink/1128032113918647/?comment_id=1128116870576838&comment_tracking=%7B%22tn%22%3A%22R3%22%7D)

To reproduce:
- Search for "עדולם שחור"
- Select the hiking trail from the search results
- Add the trail as a track with the "+" button
- Export the map as GPX

The resulting GPX has an empty track that causes the rejection of the GPX by the [suunto movescount](http://www.movescount.com/) site:
```
  <trk>
    <name>מסלול 1</name>
  </trk>
```

Please avoid exporting empty tracks **in all export formats** and treat them same as hidden layers.

**Comment by HarelM** [comment]
@zstadler Please thank Dani Peri for reporting this issue and let him know that we think we managed to fix it.
Please continue to encourage him to report issue he finds, it is very helpful.
I'll look into his other reported issues about סינגל רכסים.
I couldn't find an issue with סינגל חרובית.
