### ISSUE TITLE
Support Locus offline map download 

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#261]
Use ```locus-actions://http/Israelhiking.osm.org.il/... ``` URLs that will provide an xml file such as

```xml
<locusActions>
  <download>
    <source>
      http://israelhiking.osm.org.il/oruxmaps/IsraelHiking.zip
    </source>
    <dest>/maps/IsraelHiking.zip</dest>
    <after>extract|deleteSource|refreshMap</after>
  </download>
</locusActions>
```

It would probably be easier to add the required links to the offline download page, currently used for Oruxmaps.

**Comment by HarelM** [comment]
I don't understand the requirements.
Also do you want to create another page for Locus or to group both download to a single page?
I prefer to remove this external download page and provide a dialog with all download options inside the regular site - either inside the about menu or in a new button with a download icon or something similar.

**Comment by zstadler** [comment]
My intention is to change the Offline maps download page to support OruxMaps and Locus.

It is independent from any future UI change.

@HarelM , do you have any preferred location for the 4 ```Israel*.xml``` files required for the Locus integration?

**Comment by HarelM** [comment]
I prefer to change the UI instead of adding Locus text to a page called oruxmapsdownload.html mainly because oruxmapsdownload is not a suitable name for it anymore and I don't want to create a page for every app we support. And if we change the link we might as well move it into the site. IMO.

I think a folder called offline or offline maps should be created instead of the current one to support both orux and locus. This folder will have everything in it. This requires some changes though.

**Comment by zstadler** [comment]
Would you like to assign yourself to this issue then?

**Comment by HarelM** [comment]
I'll create a download offline maps button some where, and allow the user to choose to which application to download the offline map to.
Do you need it soon?

**Comment by zstadler** [comment]
It is not a bug, it's an enhancement.

It is high priority since we have a momentum with Locus, and we can supply them with the offline maps with no added effort on the map.

If you cannot change the download mechanism soon, then I'd rather add Locus links to the existing page and the two applications can migrate to the new mechanism when it's ready.

**Comment by HarelM** [comment]
Never said it's a bug...(?) 
Assuming I create a dialog instead of the current page, where do you think its button should be? outside along all the other buttons or inside the info somewhere? or in other place?
Creating this dialog should not take long as the logic there is fairly simple.
The only question here is where to put it - it also doesn't have to be a dialog.

**Comment by zstadler** [comment]
I think the main window is already crowded, and OSM integration will cost additional "real estate".
It is therefore my suggestion that a download link/button will be part of the "info" tab, as is today.

The surrounding text should change to include Locus support, not just OruxMaps.

**Comment by HarelM** [comment]
Here is the initial form I want to present.
Note that the mobile big buttons are not by mistake.
I'm still not sure where to put all the instructions text...
![image](https://cloud.githubusercontent.com/assets/3269297/20078786/ab2dcfd4-a54a-11e6-8f1b-013e29c217c2.png)

**Comment by zstadler** [comment]
Looking good!

Proposed changes:
- Both applications are relevant on an android device. Please use "Zip file" with no other alternatives on other devices.
- "Map" rather than "Map Type"
- "Details level" rather than "Max Zoom", with "Up to zoom 15 [...Mb]" and "Up to zoom 16[...Gb]" as values
- "Map" choice before "Details level" because it impact the map size.

**Comment by zstadler** [comment]
Android instructions can be placed after the title, and after the "Start Download" button, similar to how the text is arranged in Android part of the static page.

The detailed PC installation instructions can be shown after clicking the "Start Download", waiting to the user to press a "Close" button.

**Comment by HarelM** [comment]
Do you have install instructions for Locus? where to copy to etc...?
I'm planning on updating the site tomorrow along with the OSM changes.

**Comment by zstadler** [comment]
With locus, all one needs to do is click the link.

**Comment by zstadler** [comment]
It would be good to show the last update date of the file to be downloaded.

**Comment by HarelM** [comment]
Last update date is not out of the box, I added a text which I'm sure no one will read saying it updates every two weeks. instructions and link are based on the size of the screen I hope it will do what it should.
I kept the most important part in the beginning to make sure the download button does not go below the "fold line".

**Comment by zstadler** [comment]
I think OruxMaps should be the default, not Locus.

**Comment by HarelM** [comment]
I respectfully disagree. The bottom line is that the download in Locus is more user friendly - the download opens the application and show exactly what it does, it will in time reduce the questions as to why users can't see the offline map, which is a very common question with Orux.

**Comment by zstadler** [comment]
You have the "power of the pen"...

The new design is missing the link to Google Play for OruxMaps.
Please also add the link for Locus - https://play.google.com/store/apps/details?id=menion.android.locus

**Comment by HarelM** [comment]
Added "Get it on play store" - the button will take the user to the selected application.
I think this screen is complete unless you have anything else you think is missing.
