### ISSUE TITLE
slope calculation too noisy

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#263]
Values vary wildly. Some averaging along greater distances is needed.

**Comment by HarelM** [comment]
Please share a route so I can debug it.

**Comment by valleyofdawn** [comment]
http://israelhiking.osm.org.il/#!/?s=AqLXiaz8H1

**Comment by HarelM** [comment]
@valleyofdawn - please check if this fix is good enough for you. I didn't average the slope when presenting it in the graph but instead I added interpolation in the elevation service, Also the routing elevation is now comming from our site and not from graphhopper.
http://israelhiking.osm.org.il/#!/?s=Qm0GT5vYMI
Please close this issue if this is good enough.

**Comment by HarelM** [comment]
@valleyofdawn any updates on this? I want to close this issue if possible.

**Comment by valleyofdawn** [comment]
Fixed well, thanks.
