### ISSUE TITLE
bugs on mac

### ISSUE THREAD

**Issue by EitanBusheri** [IsraelHikingMap/Site#265]
הראל שלום,

ראשית אני עובד על מק
מערכת הפעלה 10.6.8
גולש בכרום

בעיה ראשונה:
יצרתי מסלול חדש - לקחתי את את הכלי שהאיקון שלו עפרון ויצרתי מסלול
המסלול מופיע על המפה
ברגע שאני יוצא מהמצב של עריכת המסלול, המסלול נעלם, אמי יודע שבמצב תקין הייתי רואה את המסלול עם אנימציה של תנועה, המסלול נעלם מהמפה
אני לוחץ על סטיסטיקת מסלול, גרף הגבהים של המסלול מופיע ומראה לי את הגבהים של המסלול האמיתישיצרתי
אני לוחץ על הכפתור נ"צ לק"מ, אני רואה את סימוני הק"מ על המסלול, מבלי שהקו שמתאר את המסלול קיים על המפה

בשלב הזה אני כבר לא יכול להזיז את המפה ימינה שמאלה למעלה למטה, המפה תקועה
אני כן יכול להגדיל ולהקטין את המפה

לחיצה על הכפתור נקה מסלול לא נותנת שום תגובה

גם האפשרות להמשיך לערוך את המסולל לא יוצרת שום תגובה

לחיצה על שמירת קובץ פועל - שומר את הקובץ של מסלול
מאתחל שוב את הדף

פותח את הקובץ ששמרתי - על המפה מופעים - נקודות ההתחלה והסוף של המסלול, ללא הקו שמתאר את המסלול
הגרף גבהים של המסלול ריק ולא ניתן גם לראות נקודות ציון של הק"מ
מה שכן היה ניתן לראות מקודם
כן ניתן להזיז את המפה ימינה שמאלה וכו

שאני פותח קובץ ישן לפעמים הוא מופיע על המפה לפעמים לא
הגדלה והקטנה של המפה תוציא את המסלול שפתחתי מהתוואי שלו על המפה
כלומר: המסלול לא יהיה מסוכרן על השבילים/ דרכים שהוא היה אמןר לנוע בהם

**Comment by HarelM** [comment]
ראשית תודה על הדיווח.
שתי שאלות:
האם יש לך אפשרות להתקין פיירפוקס ולבדוק האם אתה נתקל באותן בעיות שם?
אתה יכול לפתוח את כלי הפיתוח של כרום לעבור לconsole 
ולראות אם מופיע שם משהו באדום?
הבעיה העיקרית שאתה חווה לדעתי היא שהאנימציה של המסלול לא מוצגת בדפדפן ולכן המסלול נעלם.
אני בספק אם אני אוכל לפתור הכל שכן אני משתמש במוצרים שאחרים כתבו, אבל תמיד אפשר לקוות.

**Comment by HarelM** [comment]
תוכל לבדוק האם אתה רואה שביל עם אנימציה בכתובת הבאה:
http://rubenspgcavalcante.github.io/leaflet-ant-path/
ייתכן ויש בעיה עם כרום על מאק לפי השרשור הבא:
http://stackoverflow.com/questions/33589896/css-animation-does-not-work-on-mac-chrome-but-works-fine-for-ipad-chrome
לא בטוח שזו הסיבה.

**Comment by EitanBusheri** [comment]
בלינק הראשון ששלחת אני רואה את האנימציה דרך בכרום

בפיירפוקס אני גם חווה את אותן בעיות

אני אבדוק על מק אחר ואכתוב לך, יכול להיות שבהבעיה היא בכלל במחשב האישי שלי ולא קשור למק

שיהיה ערב טוב
והמון תודה

**Comment by EitanBusheri** [comment]
אוקי יש חדש
כנראה זה תוצאה של מערכת ההפעלה
ניסיתי על עוד שני מקים נוספים
אחד עם מערכת הפעלה כמו שלי - התגלו אותם בעיות
על מק עם מערכת הפעלה חדשה יותר 10.10.6
זה עבד ללא בעיות

לילה טוב
