### ISSUE TITLE
Confusing search results for "שביל ישראל לאופניים"

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#268]
Two results are shown, one is a subset of the other:
<img width="191" alt="2016-11-22 00_04_16-israel hiking map" src="https://cloud.githubusercontent.com/assets/1304610/20502576/5794799c-b047-11e6-9a60-58abe7188643.png">

The search results were captured in http://israelhiking.osm.org.il/#!/?s=5PbsSQYA1u
<img width="191" src="http://israelhiking.osm.org.il/api/images/5PbsSQYA1u">

Note that second result is added as 6 different layers.

**Comment by HarelM** [comment]
Not sure why there are two results, I'll check it.
Check out the following - the relation is not complete (there is a missing gap).
![image](https://cloud.githubusercontent.com/assets/3269297/20621125/ca88b5d8-b305-11e6-80b2-2ec3f345d4ce.png)

Places where the pre-processing was not able to create a single track it creates multiple tracks like this one and the above:
![image](https://cloud.githubusercontent.com/assets/3269297/20621219/2c806e2a-b306-11e6-9696-57e842478452.png)

**Comment by HarelM** [comment]
@zstadler
Can you please check for me if the following is not a mapping mistake:
http://www.openstreetmap.org/relation/4246795
http://www.openstreetmap.org/relation/6639060
Both have the same name but I'm not sure one how they are related if at all...
I believe this might cause the duplicate results, see if you can fix it and check the search a day afterwards.

**Comment by zstadler** [comment]
Removed http://www.openstreetmap.org/relation/4246795.
It was an abandoned attempt to represent the Israel Bike Trail as a relation of relations.

**Comment by HarelM** [comment]
Issue is no longer present in latest search results.
