### ISSUE TITLE
Hiding routes or markers

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#27]
Add a view (eye) button beside the route name, so that routes can be hidden but not deleted.

**Comment by HarelM** [comment]
I don't see much usage to hiding a route - why not just delete it or save it to file? can you elaborate on a user scenario that would require to hide a route?

**Comment by HarelM** [comment]
My concern is that the layers UI is already a bit too cluttered, I would prefer not to add more button to it if possible.

**Comment by zstadler** [comment]
I can see scenarios where the user upload or create a few routes, and would
like to view each alternative separately, or compare different subsets of
alternatives.

For example, the user wants to plan a 3 day trip with 2 alternatives for
each day. Each alternative will be created as a separate route, and the
user would like to see some of the 8 combination without deleting and
reloading the alternative routes.

**Comment by valleyofdawn** [comment]
Or when I upload 3 routes I want to base a new route on, using different sections from each. They cross each other and sometimes overlap. It's a mess unless I can hide some at will. This only affects the advanced map and route panel which already has the view icons on maps anyhow. So it wouldn't complicate the life of basic users.

**Comment by HarelM** [comment]
Suggestion: 
In advanced mode: 3-state radio button - pressed (eye sank) - selected, unpressed (eye) - visible, hidden (eye with slash) - hidden - every click will change to next step?
