### ISSUE TITLE
Truncated text in facebook post

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#270]
When using quotation marks in the text box for a FB post, the text gets truncated

**Comment by HarelM** [comment]
Can you share an example?

**Comment by valleyofdawn** [comment]
Try to share this on FB
http://israelhiking.osm.org.il/#!/?s=Ap5G0Hk0Vw

**Comment by HarelM** [comment]
I see, I now understand the issue, the '"' is closing the tag so facebook reads only the first part before it.
This open a whole issue that is related to javascript injection that can be done using the description.
I'll look into it with a security perspective.
Thanks for finding it out.
The quot fix is easy, maybe I'll fix just that before implementing a full security aware fix.

**Comment by HarelM** [comment]
The fix will be available next time I'll upload a new version, this will probably happen only after I'll finish playing with the missing route finder algorithm.
