### ISSUE TITLE
Add more site insights

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#273]
Add buttons clicks to be able to better understand which features are used more than the others.
http://angulartics.github.io/#/getting-started

**Comment by HarelM** [comment]
@zstadler if you have some buttons you would like to know how many users click either let me know and I'll add the relevant event or add it to the code using the example in the above commit (editOsm,html file).
This can lead to a better discussion UX wise - saying how many users really use a feature/button/menu...

**Comment by zstadler** [comment]
Wouldn't it be better to automatically track clicks on all buttons and links using class definitions?
Who knows what data we will need for the next UI discussion...

**Comment by HarelM** [comment]
probably, but I don't know how to do it for all buttons in the code, so I need to gradually add this.
