### ISSUE TITLE
Project installation error: AppveyorCIScripts

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#274]
The error message is:

> Unsupported
> 
> This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 
For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
>
> 	 - AppveyorCIScripts, "..\AppveyorCIScripts\AppveyorCIScripts.pssproj"

Alternatively, update README.md's ["Setting up this project"](/IsraelHikingMap/Site#setting-up-this-project) section.

**Comment by HarelM** [comment]
Probably related to PowerShell vs extension. How did you get this error? 
It's not critical for development.
If you manage to fix it, can you update the readme file?

**Comment by HarelM** [comment]
I updated the documentation, please install power shell tools from the extensions and updates dialog.
If this solves it, please close this issue.

**Comment by zstadler** [comment]
AppveyorCIScripts now loads correctly.

However, there is still another persistent error:
`bower angular-loading-bar#*                   ECMDERR Failed to execute "git clone https://github.com/chieffancypants/angular-loading-bar.git -b 0.9.0 --progress . --depth 1", exit code of #-532462766`

Is this a good description for updating TypeScript, Web Essentials, and Chutzpah:
>   * Click "Tools" -> "NuGet Package Manager" -> "Manage NuGet Packages for Solution ..."
>   * Select "Update", search for TypeScript, Web Essentials, and Chutzpah. For each search select "Select all packages" and click "Update". Confirm the proposed updates in the "Review Changes" window.

After doing the above, there were still 6 updates that were not installed: Elasticsearch.net, NEST, and System.Data.SQLite*. Perhaps the update instructions should be more general:
>   * Click "Tools" -> "NuGet Package Manager" -> "Manage NuGet Packages for Solution ..."
>   * Select "Update", then "Select all packages" and click "Update". Confirm the proposed updates in the "Review Changes" window.

After we cleanup the remaining issues and updating the README, I plan to uninstall Visual Studio and the Site repository, and install them from scratch.

**Comment by HarelM** [comment]
No, that is incorrect. NuGet is used to get packages for the compilation and running of this project while type script web essentials etc are visual studio plugins which are not related to a specific project.
When you try and compile the solution NuGet packages should be downloaded. Updating them means to change the code, which is not what you want to do.

**Comment by zstadler** [comment]
These are the two possible ways I could understand the new instruction:
> * Using nuget install/update the following: TypeScript, Web Essentials, Chutzpah (both runner and context menu), Power Shell Tools.

I suggest this explanation gets elaborated to clarify the correct way to do the install/update, complete with menu and button names, as I've tried in the above descriptions.

Also, I could not find the Power Shell Tools update through Nuget, but rather through
> * Using Tools -> Extenstions and Updates -> Online, install/update "Power Shell Tools for Visual Studio"

**Comment by HarelM** [comment]
Again, you are confusing between NuGet and Visual Studio updates.
I'll be happy to clarify the difference so you could write something that is easier to follow.

**Comment by HarelM** [comment]
Any updates on this?

**Comment by zstadler** [comment]
Still waiting for your clarification.

**Comment by HarelM** [comment]
Everything related to setting up the development is done using "extension and updates" menu item from the "tools" menu in visual studio, you don't need anything beside VS (you don't need the code at this point)
Everything that is related to code compilation that depends on third party software is done using NuGet.
So when you need to compile the code after you got it from git you'll need to use NuGet, but in practice NuGet packages are downloaded automatically when you start the compilation of the code, so just for compilation you don't really need to know that NuGet exists.
Does this make any sense?
