### ISSUE TITLE
Reopening the OSM pop-up - restore its state

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#277]
When re-opening the OSM pop-up, restore the previous traces/shares selection and the previous scroll position

**Comment by HarelM** [comment]
Scroll is a pain, search and traces/share can be done.

**Comment by HarelM** [comment]
I have implemented it using cache to avoid a usage problem where you enter a search term and forget about it and you can't find your shares or traces. 
The state is saved within the current session - up until you hit the refresh button.
