### ISSUE TITLE
Bike icon missing from search results for cycling relations

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#278]
e.g. דרך הסוכר

**Comment by HarelM** [comment]
Have you removed the icon from the map repository? the bike.png and the hiker.png?
If so that is the reason...
I'm relaying on these icons for search results.
Not sure it's a very good practice but I didn't feel like duplicating them...

**Comment by valleyofdawn** [comment]
I think Zeev did a cleanup of icons that weren't used in the maps.
