### ISSUE TITLE
Mishandling in viewing multiple OSM traces

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#279]
When an OSM trace is already viewed, and another trace is selected for viewing, the first trace remains visible, but it cannot be deleted. Clicking the "setting" button for the trace opens the pop-up, but clicking the delete button does not work.

**Comment by HarelM** [comment]
This does not exists in the latest version of the code (still not published). the behavior is like search results once you select a different one the previous one is removed from the map.
