### ISSUE TITLE
Better "middle marker" support

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#28]
As I user I would like to be able to add a mid route point from any exiting route position, not just from specific points like it is now.

**Comment by zstadler** [comment]
I think this is a low priority issue, as long as the user have a hook to
insert a route point, it's good enough.

**Comment by HarelM** [comment]
This is more of an infrastructure issue for me as it is working now but it is not elegant, also when the routes are long there will be a lot of middle marker points which might cause the site to work slower.

**Comment by zstadler** [comment]
See the smooth mid-point support in Brouter web client for a very long path:
http://brouter.de/brouter-web/#zoom=16&lat=33.30692&lon=35.77126&layer=OpenStreetMap&lonlats=34.903178,29.491142|35.772042,33.307577&nogos=&profile=trekking&alternativeidx=0&format=geojson
