### ISSUE TITLE
Customize page not found 

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#284]
Current page not found is the IIS default which is hideous - need to override this definition with a more elegant page.

**Comment by HarelM** [comment]
Can be tested here for example:
http://israelhiking.osm.org.il/abcdefg/

**Comment by zstadler** [comment]
Would it be possible to switch the sides of the Hebrew and English text such that English is on the left?

**Comment by HarelM** [comment]
There is a problem with mobile if I switch. I prefer to keep it this way...
