### ISSUE TITLE
Accessiblity to tourists

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#285]
Following issue IsraelHikingMap/Map#8, use the English versions of the Hiking and Biking maps when the interface is in English.

Maps tiles are now available at `/<Language>/<Tile set>` where `<Language` is either `Hebrew` or `English` and `<Tile set>` is either `Tiles`, `mtbTiles`, or `OverlayTiles`. Currently, `OverlayTiles` for both languages are identical.

The existing paths for Hebrew tiles will be kept for compatibility.

**Comment by HarelM** [comment]
Map language can now be changed from the language menu along with the site's language.
