### ISSUE TITLE
Error when trying to upload a gpx file downloded from strava

### ISSUE THREAD

**Issue by bermaneyal** [IsraelHikingMap/Site#292]
[834159359.zip](https://github.com/IsraelHikingMap/Site/files/710798/834159359.zip)

**Comment by HarelM** [comment]
Thanks for reporting! I'll take a look at it tonight.

**Comment by HarelM** [comment]
I have no issues opening it assuming I took the gpx file and not the zip file:
![image](https://cloud.githubusercontent.com/assets/3269297/22019283/960a40c6-dcbb-11e6-920b-9a9577ac740c.png)

**Comment by bermaneyal** [comment]
the problem is when i try to upload it from 
![capture](https://cloud.githubusercontent.com/assets/1392548/22019517/94ea9492-dcbc-11e6-851f-7e9f1e629bc3.PNG)

**Comment by HarelM** [comment]
I see now.
This file is sent to OSM using their API.
It seems that uploading it from their site works so it might be an issue with how I implemented the API call. I'll try to debug it later today/tomorrow.
As a workaround you can upload it from here:
https://www.openstreetmap.org/trace/create
