### ISSUE TITLE
Black route is not visible in current color scheme

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#298]
When the route is selected to be black you can't see its details in the layers side-panel.

**Comment by HarelM** [comment]
What would you suggest as a fix to this issue?
avoid black color?

**Comment by valleyofdawn** [comment]
No.  It's very useful.
Use light gray text for all.
Use gray background for the eye/pencil icon

**Comment by zstadler** [comment]
My 2 cents: white background

**Comment by valleyofdawn** [comment]
All over?
Light grey is easier on the eyes.

**Comment by HarelM** [comment]
So, what's the final statement? I think the color of the route in the layers control is very important when working with multiple routes - It's easier to understand which route name belongs to which route...
I'm not sure adding a border will look good but I can try. I can change the entire coloring of this panel to white, but I kinda like it this way...

**Comment by valleyofdawn** [comment]
Agreed, leave the icon color as is. Change the background of just the icon
or the whole panel to gray.
personally I don't like the totally black background.

**Comment by HarelM** [comment]
Everything just looks ugly...
I'll see what I can do, but the easiest solution is probably to change the background of the entire panel to white, as @zstadler suggested. :-/

**Comment by valleyofdawn** [comment]
Light gray please.

**Comment by HarelM** [comment]
I'll need to redesign the color scheme of this entire window since the font is currently gray :-(
Help would be appreciated if you have the patience for it... 
Need hex colors for:
 * background
 * text
 * text highlighted (on hover)
 * text highlighted's background (on hover)
 * link
 * link highlighted (on hover)

**Comment by valleyofdawn** [comment]
What do you think?
![text4138](https://cloud.githubusercontent.com/assets/689201/23850969/5abaef8e-07ea-11e7-834c-0cff5e09056e.png)

**Comment by valleyofdawn** [comment]
•	Background	ececec
•	Text	000000
•	text highlighted (on hover)	000000
•	text highlighted background (on hover)	cccccc
•	link	0645ad
•	link highlighted	0645ad
•	link highlighted background (on hover)	cccccc

**Comment by HarelM** [comment]
The above background color hides yellow now :-/
changed it to dddddd this is how this looks now:
Not sure it looks good in terms of design, but it's more functional, although haven't tested this outside...
I'll commit it, we can always change it.
@zstadler iIf your wife could have a look it might help in this case.
![image](https://cloud.githubusercontent.com/assets/3269297/24322123/7930b6dc-116e-11e7-8bc7-9293827e7d23.png)
