### ISSUE TITLE
Layers don'r respond to touch screen

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#299]
Layer selection doesn't work with a laptop touchscreen. Works fine with the mouse or touchpad.
Chrome on windows 10

**Comment by valleyofdawn** [comment]
Same thing with Wikipedia links (would open but wouldn't send you to the wiki article)

**Comment by zstadler** [comment]
Both work well for me.
Chrome and Firefox on Windows 10

**Comment by valleyofdawn** [comment]
Seems to be working now. Strange.
