### ISSUE TITLE
Routing mode on by default

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#3]
I suggest Routing mode would be enabled by default when entering edit mode.
Edit mode needs to stay disabled when entering the site, as is now.

**Comment by HarelM** [comment]
Assuming soon we will have move than one routing type, which one should be the default?

**Comment by zstadler** [comment]
IMO, the default should be the most permissive - hiking

**Comment by valleyofdawn** [comment]
Agreed.

**Comment by HarelM** [comment]
addressed in check-in 866ecf7b2b083722b108ca4a6420ea6588736da7
