### ISSUE TITLE
Icon options for POIs

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#300]
Could be useful to select meaningful icons, such as car, water, viewpoint etc. when annotating a route with POIs.

**Comment by HarelM** [comment]
Not sure I know where to keep this info, but assuming I figure this out, can you suggest a UX for this?

**Comment by valleyofdawn** [comment]
Alongside the globe trashcan and V sign icons place a gear icon.
It would open a table of say 16 or 25 useful icons.
Can be put in a drop, like the iD editor point icons.
<img width="960" alt="id - google chrome 1_30_2017 11_53_46 am" src="https://cloud.githubusercontent.com/assets/689201/22418723/e05cfcbe-e6e2-11e6-8a39-6ba02c8e0f4f.png">

**Comment by HarelM** [comment]
16 to 25? Are you crazy? Pick 3-7. I'll try to see how it looks and if I can make it look good, I current have issues making the drop icons look the way I want them to...

**Comment by valleyofdawn** [comment]
4x4 would look nice. How about
regular drop, Car, bike, food, water, coffee cup, viewpoint, turn right,
turn left, tent, star, bed, groceries, flag, info, toilet.

בתאריך 30 בינו׳ 2017 12:06 PM,‏ "Harel M" <notifications@github.com> כתב:

**Comment by HarelM** [comment]
Too many of them are too bike specific.
3-7 items, otherwise it will feel too crowded.
Can you use emoji in the text?

**Comment by valleyofdawn** [comment]
Only bike is bike-specific.  Half the site is bike oriented.  Please
suggest specific ones to replace.  Or we can go with 25.

בתאריך 30 בינו׳ 2017 12:21 PM,‏ "Harel M" <notifications@github.com> כתב:

**Comment by valleyofdawn** [comment]
16 can look compact
http://previews.123rf.com/images/wisaanu99/wisaanu991505/wisaanu99150500073/40294398-Map-navigation-icons-set-vector-Stock-Vector.jpg

**Comment by zstadler** [comment]
I agree 16 icons would be good.

However, IMO the proposed set of icons icons contains icons that are less relevant for route annotation.
<img width="25%" src="http://previews.123rf.com/images/wisaanu99/wisaanu991505/wisaanu99150500073/40294398-Map-navigation-icons-set-vector-Stock-Vector.jpg">
For example: satellite, compass, search, balloon, and a few more.

**Comment by valleyofdawn** [comment]
Of course.
It's just an example of the arrangement.

**Comment by HarelM** [comment]
Currently the only icons I can present are those available in font awesome. Let me know if the icons there are relevant to what you need.

**Comment by valleyofdawn** [comment]
16 and extra ones is you think 25 are OK

   1. http://fontawesome.io/icon/car/
   2. http://fontawesome.io/icon/bicycle/
   3. http://fontawesome.io/icon/home/
   4. http://fontawesome.io/icon/arrow-left/
   5. http://fontawesome.io/icon/arrow-right/
   6. http://fontawesome.io/icon/heart/
   7. http://fontawesome.io/icon/star
   8. http://fontawesome.io/icon/bed/
   9. http://fontawesome.io/icon/binoculars/
   10. http://fontawesome.io/icon/fire/
   11. http://fontawesome.io/icon/flag/
   12. http://fontawesome.io/icon/coffee/
   13. http://fontawesome.io/icon/cutlery/
   14. http://fontawesome.io/icon/shopping-cart/
   15. http://fontawesome.io/icon/tint
   16. http://fontawesome.io/icon/tree

   17. http://fontawesome.io/icon/shower
   18. http://fontawesome.io/icon/asterisk/
   19. http://fontawesome.io/icon/glass/
   20. http://fontawesome.io/icon/beer/
   21. http://fontawesome.io/icon/eye/
   22. http://fontawesome.io/icon/motorcycle/
   23. http://fontawesome.io/icon/leaf/
   24. http://fontawesome.io/icon/paw/
   25. http://fontawesome.io/icon/map/

**Comment by zstadler** [comment]
Suggesting http://fontawesome.io/icon/map-signs/

**Comment by HarelM** [comment]
I would focus on 9. I think 16 is too much, and 25 will just frustrate the user...
The following API can help with the issues I'm facing with font awesome and the map markers stacking and positioning which is just a nightmare, but it might slowdown the site, I'm still looking for the code that does that and maybe host it on our server.
https://mapmarker.io/documentation

**Comment by valleyofdawn** [comment]
GPSies do it through a list. Maybe that's easier. They have some 30 icons.
[image: Inline image 1]

**Comment by HarelM** [comment]
Please upload the image again, I can't see it.
Too many choices create what's called a cognitive exhaustion - which will in turn make the user avoid dealing with it and not select anything, for this feature to be good we need to select the most helpful icons and present only them.

**Comment by valleyofdawn** [comment]
GPSies
<img width="479" alt="_ gpsies - google chrome 1_30_2017 6_51_30 pm" src="https://cloud.githubusercontent.com/assets/689201/22432687/65cd46f2-e71e-11e6-9677-bef2bfed0a74.png">
MapMyRide
<img width="644" alt="map a bike ride on our bike route planner draw on bike paths - google chrome 1_30_2017 6_59_29 pm" src="https://cloud.githubusercontent.com/assets/689201/22432692/6ab4881a-e71e-11e6-960e-1b1cab2b3afb.png">

**Comment by valleyofdawn** [comment]
A text-based list would makes sense because you'd be browsing for what you need, say "water", rather than inundated by lots of icons.

**Comment by HarelM** [comment]
These are the site you surf? They look atrocious... 
4x4 is better than a never ending dropdown list, but both cases are just bad UX. I don't understand why you would need so many icons? You can write whatever comes to mind...

Regardless, if I use the above API I can allow any icon they support, I can direct the user to look at the FA icons and let him write the icon he wants. This gives the ultimate flexibility but it's very complex and I doubt users will actually use it...

**Comment by valleyofdawn** [comment]
I'm just looking, I only have sex with IHM.
To me it's more aesthetically pleasing to have 3 drops along the way than
POIs spelling out "drinking water". There is very little functionality in
having just a few icons, it's frustrating to look for an icon you need and
not find it and it is ugly to have some of your POIs as icons and some in
text. I'm not a cognitive psychologist but I think people can cope with 16
icons without having a mental meltdown. Letting the users design their own
icons is silly, just like you said.

**Comment by valleyofdawn** [comment]
If it wasn't clear, I think the icon palette should remain hidden unless
clicked, and most users would keep using the default one with text.

**Comment by HarelM** [comment]
It was clear. :-)
I'm not talking about design the icons, just selecting it using the following page as instructions:
http://fontawesome.io/icons/
Allowing the user to write the icon name and present it while typing can allow a very rich variety.
We can add it in the bottom of the POI edit popup, something like:
![image](https://cloud.githubusercontent.com/assets/3269297/22473158/927f1c44-e7e0-11e6-89f1-327c5692d60b.png)

We might consider using "more..." link that will open the FA page link above - I still think 16 is too much, 8 feels a lot simpler.
Check out how less crowded and easier to look this popup feels:
![image](https://cloud.githubusercontent.com/assets/3269297/22473664/4435395e-e7e2-11e6-8aeb-4c6b9a8d1a77.png)



Regardless, the following question might help with some implementation issues:
http://stackoverflow.com/questions/11426172/add-custom-icons-to-font-awesome

**Comment by valleyofdawn** [comment]
I beg to differ with regard to the number. Function over form. 
Will you be able to use synonyms?
The icon tint for instance should be used for water, tap, faucet, drinking, etc.

**Comment by valleyofdawn** [comment]
Is there a way I could help? BTW think of emogees, could you suggest to texters to use 8 instead of the hundreds at their disposal?

**Comment by HarelM** [comment]
I use only about 8 most of the time, I don't like wasting time for endless emojis search...
I'm currently working on improving the finding unmapped parts algorithm, it'll take me some time to get to this enhancement...
If you could provide a PowerPoint presentation that will allow to get a feeling of the UX like the one I sent sometime ago it might help. I'm still having issues with the amount of data we present to the user...

**Comment by valleyofdawn** [comment]
![map icons](https://cloud.githubusercontent.com/assets/689201/22688619/be52520a-ed35-11e6-80f8-7ff699db0e30.png)

**Comment by HarelM** [comment]
So this means a user who selects a symbol can't add text?

**Comment by valleyofdawn** [comment]
No. After the icon is selected the window would collapse and you'd see the
text window again. Most users won't bother with the icons.

בתאריך 7 בפבר׳ 2017 01:22 PM,‏ "Harel M" <notifications@github.com> כתב:

**Comment by HarelM** [comment]
I'm redesigning the entire marker appearance on the map, here is an initial example:
I want to make all the markers have the same shape (as opposed to now) and place an icon over every type of marker (added the "arrows" icon in the example below).
![image](https://cloud.githubusercontent.com/assets/3269297/23107544/9d1d381c-f707-11e6-9fc9-59f1dfd8c563.png)
I'm using [icomoon](https://icomoon.io) to create a font that allows placing any type of icon on top of the marker (which now will not have a hole in the middle).
@valleyofdawn do you have the "jeep" in svg format and not png, I would like to move all the icons to the same library so everything will be loaded at once.
I'll reduce the size of the markers a bit so you'd stop nagging about it... :-)
I'm still not sure if and how to make this scale-able - if I'll need to update the font for every new icon we'll support in the POI it won't work well...
Thoughts and comments are welcome!

**Comment by valleyofdawn** [comment]
The icon in the drop looks excellent. I would stick to one color, not necessarily the track color.
Attaching the jeep SVG. Let me know how else to help.
[Jeep.zip](https://github.com/IsraelHikingMap/Site/files/787372/Jeep.zip)

**Comment by HarelM** [comment]
Getting closer :-)
![image](https://cloud.githubusercontent.com/assets/3269297/23144288/3fdd7c48-f7cf-11e6-9ae4-b943e421c56a.png)

**Comment by valleyofdawn** [comment]
Looking good! Perhaps the same color for icon and text.

**Comment by HarelM** [comment]
@zstadler @valleyofdawn 
Uploaded to test site. 
Thought, ideas and comments are welcome!
https://israelhiking.osm.org.il/test/

**Comment by valleyofdawn** [comment]
Very nice!
Drinking water icon greatly missed. The most common POI I use.
It can replace the flag or heart which are less critical.
Also fire icon a bit ambiguous.

**Comment by valleyofdawn** [comment]
Missing Hebrew tooltip. Only "select icon" appears now.

**Comment by valleyofdawn** [comment]
It would also be nicer if the icon in the drop changed immediately when you click the icon, not when you hit OK.

**Comment by HarelM** [comment]
This is on purpose to allow canceling.
Hebrew will be fixed on production site.
I'll add the relevant svg, note that the list of icons is what you asked 😊

**Comment by valleyofdawn** [comment]
Nope, I didn't have a jeep and I had water (tint icon), also in the simulation.
You could still cancel and go back to the default star even if it shows you what it would look like when you select, or re-select icons.
