### ISSUE TITLE
Remove legend for google earth layer

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#301]
Otherwise results are confusing:
<img width="960" alt="israel hiking map - google chrome 1_30_2017 9_46_45 pm" src="https://cloud.githubusercontent.com/assets/689201/22438759/d36fe7ca-e735-11e6-8d7f-c74b7f142de2.png">

**Comment by HarelM** [comment]
@zstadler and I had the same discussion in the issue related to the Legend, I think we agreed that what we want.
If you are looking for a legend for satellite images you are confused, doesn't matter what we do...

**Comment by zstadler** [comment]
The idea is to automatically create a legend for 3rd party maps, such as maps.wikimedia.org:

<img width="170" alt="2017-01-31 09_28_14-settings" src="https://cloud.githubusercontent.com/assets/1304610/22455877/cb660f66-e797-11e6-98fc-6885e8edf85c.png">

I agree that the legend is not very useful for the builtin satellite imagery, and we should consider disabling the legend.

There is also the question about legends for the builtin overlay layers. It would be nice to show the Trails Overlay legend, when it is active. On the other hand, I don't think the Wikipadia Overlay requires a legend.

**Comment by valleyofdawn** [comment]
I see your point.  In that case leave it.  We can doable the legend in
Google Earth mode but it's not high priority.

**Comment by HarelM** [comment]
I don't see a legend for google earth layer, moreover, the code removed the legend in this case.
@valleyofdawn can you please check if you still see it? Is it a custom satellite layer? If so please code this bug as the default is with a legend. I'll check-in small style changes.

**Comment by HarelM** [comment]
No response, and can't reproduce. closing.
