### ISSUE TITLE
4x4 routing prioritizes long asphalt roads over short gravel ones

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#302]
Is this how we want it?
Could we choose another algorithm?
https://israelhiking.osm.org.il/#!/?s=TKpYEnrVdN

**Comment by zstadler** [comment]
The route is calculated based on the assumed speed at each road type. For example, 4WD and 2WD cars are assuming 15 Km/h for "grade2 tracks" and 30 Km/h for "unclassified" roads. If we want the 4WD routing to have higher preference for tracks, we just need to assume higher speeds.

By the way, slightly moving the end point, and the route is done through the track - https://israelhiking.osm.org.il/#!/?s=fUGGbx4S1R
