### ISSUE TITLE
Using the mouse scroll wheel

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#303]
With my mouse it zooms 2 map levels for each click.
Is that a general behavior?
If so, one zoom level per click would be preferable.

**Comment by HarelM** [comment]
Problem with chrome and leaflet. I assume you experience it with chrome, right?

**Comment by valleyofdawn** [comment]
Yes,
I also have Microsoft Edge installed. There is zooms in single jumps all right but the images pan left before zooming in.

**Comment by HarelM** [comment]
Not much I can do, see here:
https://github.com/Leaflet/Leaflet/issues/4538

**Comment by valleyofdawn** [comment]
Now it works fine.
