### ISSUE TITLE
Migrate to .Net Core

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#310]
Will allow cross platform capabilities.

**Comment by HarelM** [comment]
Tried to move elastic search to ```BulkAll`` but the exception part is not well and the callback are not so elegant (need to use manual reset), decided to keep it as is with minor refactoring.

**Comment by HarelM** [comment]
I'll wait a day or two before merging this to master in order to facilitate for a few more bug fixing.The site now uses the code in the net_core branch hence the motivation.

**Comment by valleyofdawn** [comment]
The facebook posts no longer show the intended thumbnail and text.

**Comment by HarelM** [comment]
Merged to master. I'm closing this for now as I'm not aware of any other issues currently.
@valleyofdawn if you find other issues, please open a separate issue, Thanks for helping with the QA effort!
