### ISSUE TITLE
Better OSM traces support

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#314]
Cannot set trace information, similar to OSM upload:

- Description
- Tags
- Visibility

<img width="675" alt="2017-03-11 09_57_44-openstreetmap _ upload gps trace" src="https://cloud.githubusercontent.com/assets/1304610/23821639/936bda82-0641-11e7-8959-d724b96c9ff8.png">

**Comment by HarelM** [comment]
This is by design. I want the process of uploading a trace simple and fast.

**Comment by zstadler** [comment]
Opinions may vary...

IMO, showing the fields, with the currently pre-assigned values and a grey "(Optional)" for the tags, is not going to make things more complicated.

On the other hand, this will enable users who bother to upload traces, but not force them, to avoid having a list of unfamiliar traces, such as

![image](https://cloud.githubusercontent.com/assets/1304610/23824842/ee91648c-0686-11e7-8c3f-ef49e9fa6ec5.png)

**Comment by HarelM** [comment]
I think that the simplicity of just selecting a file and uploading it is very good experience right now and I prefer to keep it this way.
I can't introduce another dialog so there are two options:
1. Allow the user to update the data after the upload is complete.
2. Move the entire dialog to the left pane, and allow editing similar to route edit dialog.
Note that currently you can't delete a route as well as the above requirements.

Which do you think is better? Do you have another suggestion?

**Comment by zstadler** [comment]
We can also show the three fields and an "Upload" button in the existing dialog, similar to the way share details are edited now:
![image](https://cloud.githubusercontent.com/assets/1304610/24235634/cfbcd8c4-0fa6-11e7-88af-5a1fbac6d9e1.png)

Similarly, add the visibility drop-down.

**Comment by HarelM** [comment]
I'll try to play with it and see if I can make something similar to what you said.
Bare in mind that most users will not know what to put in these fields and therefore might not upload traces because of them.
I'm thinking I might use the "advanced" setting to decide whether to show the extended version of this form or the simple one, what do you think?

**Comment by HarelM** [comment]
I want to do the following:
 - [ ] Allow user to delete a route
 - [ ] Allow user to edit tags
 - [ ] Allow user to edit private/public state
This should supply the original demand since you can upload a trace and then edit its properties - which facilitate for both demands - quick upload and enhance editing.

**Comment by zstadler** [comment]
I meant for the dialog to show prior to uploading a new trace to the server, similar to uploading a trace in the OSM site, not as a metadata editor for uploaded traces.

The current implementation requires an extra step that few users, if any, will use.

Also, the translations seem to be missing, so the field titles and the drop-down values are missing:
![image](https://user-images.githubusercontent.com/1304610/28921392-71abb1b2-785e-11e7-9012-d2b7d3416ae2.png)

**Comment by HarelM** [comment]
I find it consistent with the shares editing experience.
I know what you meant and decided this flow is less important and so I moved it to require more clicks only if the user really wants.
Translation is always missing in test site, don't worry about it.
I think it still has a really easy to use main flow while advance flow is supported but requires more click.

**Comment by HarelM** [comment]
See my comment from 8 days ago, I tried to open a discussion but there no one replied...
I don't mind removing the ability to modify visibility and tag if you think it doesn't help - editing the description and deleting a trace is important IMO.
I don't understand which "nudge" you want to achieve as I see no value in tags and visibility.
As I said, the ability to upload a file in a single click is, IMHO, the most important flow.

**Comment by zstadler** [comment]
The essence of the feature request, or "the nudge", is asking the details as part of the upload. 
The features listed 8 days ago are nice-to-have additions, but IMO not valuable as a replacement.

**Comment by HarelM** [comment]
As you said, we do not agree :-)
