### ISSUE TITLE
Feature suggestion: draggable margin for left window

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#319]
A movable margin separating the map and the layers/info window would allow the user to keep the layer window open for selecting and de-selecting layers and routes while keeping most of the map visible.
You could keep only the eye/pencil icons peeping out, which is the useful bit of the window.
This is especially important on small screens such as laptops and tablets.
Right now, some 75% of this is wasted real-estate.

![image](https://cloud.githubusercontent.com/assets/689201/23945259/8bc116e0-097e-11e7-9109-90f9e272385c.png)

**Comment by HarelM** [comment]
Do you have an alternative solution?
Storing the last size of this window and dealing with a responsive design is very hard for a feature that doesn't help a lot.

**Comment by valleyofdawn** [comment]
I think is would help a lot.
You can open it fully the first time, regardless of the last position.
I have no idea how much coding this requires. But if it's reasonable I would prioritize it.

**Comment by HarelM** [comment]
Can now be tested in the test site:
https://israelhiking.osm.org.il/test/
Part of #349.
I think there's a bug the if you drag it over 400px to the right side the `right` attribute is updated but the size isn't so when you try to drag it back left it doesn't look like it's working.
@moshfeu, will you be able to see if this can be fixed so I can close this issue?

**Comment by moshfeu** [comment]
I made this in way that the maximum width will be 400 px. I can't see a reason that the side bar will be grater than that. But it could be different if you want..

**Comment by valleyofdawn** [comment]
Well done.
Consider losing the text altogether when the margin is too narrow to show it, as well as setting a minimum to the width so that the icons are always shown.

**Comment by HarelM** [comment]
400px is enough I think although I'm not sure I see a good reason to limit the user.
There's still a but there - when you drag it past 400px and then try to drag it back, it doesn't work well. this probably needs a fix in the directive code itself rather than in the css...
