### ISSUE TITLE
Include first paragraph and image from Wikipedia

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#320]
As is done here:
https://www.bikemap.net/en/route/create/

**Comment by HarelM** [comment]
This is a great idea!
The following should help with the image:
http://en.wikipedia.org/w/api.php?action=query&prop=pageimages&format=json&piprop=original&titles=India
And this with the intro:
https://en.wikipedia.org/w/api.php?format=json&action=query&prop=extracts&exintro=&explaintext=&titles=Stack%20Overflow

**Comment by HarelM** [comment]
Closing in favor of #330
