### ISSUE TITLE
Keep route length visible at all time

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#322]
This is very useful information and should not require opening the height profile.
Keeping the height profile constantly open is bad because:
1. It is not interesting to some planneres, such as motorists
2. It blocks the view

Showing this can take minimal space, say in one of the corners of the screen

There is good reason why practically all other route planners, such as Google maps, Strava, GPSies, and all the others I checks permanently show this parameter.
An alternative place would be next to the route name in the layer window (for all routes).

**Comment by HarelM** [comment]
Please include a screen shot of how you would like to see it on the map.
Please include one for mobile and one for desktop (you can shrink your browser to create a mobile like screen on your desktop).
Let me know how you are planning to address the map's background not affecting the visibility of this new label.
I don't think the layers menu will help, you'll have the same problem but just in a different place...

**Comment by valleyofdawn** [comment]
![israel hiking map - google chrome 3_20_2017 3_04_23 pm](https://cloud.githubusercontent.com/assets/689201/24101187/f97fff02-0d7f-11e7-9fdc-39d71007774b.png)

**Comment by HarelM** [comment]
I'm not sure 3 digits will fit on the button without making it look ode, I'll see if I can squeeze it up there, I doubt it though, do you have a backup plan in case it won't look good or won't fit?
Did I understand you correctly - you want the distance to be in the same color as the currently selected route (sound like a good idea to indicate which is the currently selected without opening the layer sidebar)?

**Comment by valleyofdawn** [comment]
Yes. This was the general idea.

**Comment by valleyofdawn** [comment]
We should also decide what to do in the rare case when a route exceeds 1000km

**Comment by valleyofdawn** [comment]
Another option. This could work well with opening the height profile at the bottom.
![hight](https://cloud.githubusercontent.com/assets/689201/24241250/d689fda6-0fbc-11e7-8179-d9493833f4bb.jpg)

**Comment by HarelM** [comment]
This looks nice! Can you try and create an image for mobile? I feel like it might make the app too crowded...

**Comment by valleyofdawn** [comment]
I'll try.
BTW, can save real estate by putting the copyright info under "i".

**Comment by valleyofdawn** [comment]
![screenshot_20170323-114707](https://cloud.githubusercontent.com/assets/689201/24242060/55c042ea-0fbf-11e7-9d82-73ef3e74c1cc.png)

**Comment by valleyofdawn** [comment]
I didn't remove the extra height button.
Maybe we can lose the "+" "-" "edit" and "print" buttons for the mobile version? should I open an issue?

**Comment by HarelM** [comment]
This is part of the framework, maybe I can keep just the leaflet there and add all the rest to the info. Good call.

**Comment by HarelM** [comment]
Please open a separate issue to address invalid buttons on mobile.

**Comment by valleyofdawn** [comment]
Also the user info takes up too much scarce space. could it be one collapsible button?

**Comment by HarelM** [comment]
Not sure what you mean, but let's talk about real estate in another thread, let's assume we have less buttons on the mobile device for this discussion.

**Comment by valleyofdawn** [comment]
Opened one

**Comment by valleyofdawn** [comment]
I think it would be nice if the track info buttons disappear when you open the height profile. You don't need them both. this could work well if the profile appears at the bottom right.

**Comment by HarelM** [comment]
What are the "track info buttons"?

**Comment by valleyofdawn** [comment]
The 3 suggested ones showing information on the length, elevation gain and
loss in the track.

**Comment by HarelM** [comment]
Please approve, I have ground to understand the significance of route statistics and in the proposed solution the affect on map size is reasonable.
Should I hide the new control in case the route length is 0?
![image](https://cloud.githubusercontent.com/assets/3269297/24579423/02f57e90-16fe-11e7-813a-68309b48297e.png)

**Comment by valleyofdawn** [comment]
Looking good. I thought you could keep the old design of the height profile (with stats) and hide the new stats when you open it. That way you could attach it fully to the bottom. Also the "-" in the descent field looks strange because of the double negative.

**Comment by HarelM** [comment]
I have no issues with the double negative. I think the design is good enough, don't want to move too many text around, in case we would like to change it in the future it's always possible...

**Comment by valleyofdawn** [comment]
Go ahead then.

**Comment by zstadler** [comment]
Some background is needed:

![image](https://cloud.githubusercontent.com/assets/1304610/24588058/e18857d8-17c9-11e7-8d89-de9a492d4553.png)

![image](https://cloud.githubusercontent.com/assets/1304610/24588060/f439bade-17c9-11e7-90e9-5ce11dfadc78.png)

**Comment by HarelM** [comment]
Please refresh your browser cache, this is the old design...

2017-04-02 17:30 GMT+03:00 zstadler <notifications@github.com>:
