### ISSUE TITLE
Keep map static when opening the layers/info window

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#323]
Would be less visually disturbing.
If overruning the action buttons is a problem, It could be done by placing the buttons left of the window, as done in the OSM edit window.
http://www.openstreetmap.org/edit#map=15/32.5432/34.9512

**Comment by HarelM** [comment]
They have found a very good workaround to the problem, I'm impressed, thanks for sharing.
This should be easy to implement assuming we're not supporting the ability to change the sidebar menu size, which is an overkill IMHO.
It's funny but they didn't implement it in the regular site (www.openstreetmap.org) just in the editor :-)

**Comment by zstadler** [comment]
"Download offline maps" pane needs to be re-positioned to the right:
![image](https://cloud.githubusercontent.com/assets/1304610/24579953/4fa97e8a-1708-11e7-930d-c22c493e440c.png)

Column widths in the help are too wide, causing text warp:
<img width="206" alt="2017-04-01 18_21_14-israel hiking map" src="https://cloud.githubusercontent.com/assets/1304610/24579945/2c947e18-1708-11e7-883b-e1c3566cceb6.png">

**Comment by HarelM** [comment]
Fixed the above two issues, thanks for bringing it to my attention.
Is there anything else or I can close this issue?

**Comment by zstadler** [comment]
Centering to a track should be done according to the currently visible section of the map, excluding the part covered by the left pane.
Currently, when a new track is loaded, the west 1/3 of it is hidden.

**Comment by HarelM** [comment]
Well, this is the downside of not shirking the map pane - the map is hidden and not smaller.
Not sure I have a way of overriding this behavior without complicating this too much.
I'm probably not going to fix this...

**Comment by zstadler** [comment]
I assume both the window width and the left pane width are known. 
The conditional arithmetic that can be encapsulated in methods.

**Comment by HarelM** [comment]
I'm not aware of the windows width and pane width in the code, those are css properties which I would like to know as little as possible about when writing against leaflet framework.
I'm using ```panTo``` method and it does not get any argument that is related to pixel stuff:
http://leafletjs.com/reference.html#map-panoptions

**Comment by zstadler** [comment]
When centering to a track, the appropriate zoom level needs to be set. ```panTo``` does not seem to be able to change the zoom.

More likely, the code uses [```fitBounds```](http://leafletjs.com/reference.html#map-fitbounds) that sets the appropriate zoom and accepts [padding options](http://leafletjs.com/reference.html#map-fitboundsoptions). The top-left and bottom-right margins can be set such that the track would not overlap with the buttons on both sides, the user name on the top-right, the length/up/down counter on the bottom right, or the optional info pane on the left.

**Comment by HarelM** [comment]
Your right, I looked at the wrong place.
Unfortunately, this requires that every ```fitbounds``` call will get the relevant information about the state of current application (open windows etc), which is somewhat distasteful in terms of code.
I can hardcode it on all calls but that's not a lot better.
Since the user can move the map around I don't feel like this is something that needs to be added considering the ugliness it will bring to the code...

**Comment by zstadler** [comment]
I think that's why you create services , controllers, etc. - so that such activity will be defined once and used everywhere...

**Comment by HarelM** [comment]
@zstadler 
Can't believe I ended up implementing it... I hate that my OCD is being amplified by yours...
Anything else? Please close if not.

**Comment by zstadler** [comment]
Thanks! it's looking great!
