### ISSUE TITLE
Improve "Save as" UX

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#325]
From the critical to the petty:

1) The bottom of the format list is invisible on a mobile screen and  can't be scrolled to - solution: shorten the names so they fit in one line (nobody cares what KML means) and reduce space between lines
2) It is not intuitive that you have to press the icon again to save the route after you've chosen the format. Solution: save as soon as you choose the format.
3) The parentheses get jumbled up in Chrome - solution: you don't need them.
4) The icon looks too much like the layers icon (stacked sheets). I keep mistaking them. - solution: perhaps two stacked diskettes?

**Comment by HarelM** [comment]
Can't argue with your comment. I'll do them after I finish the current effort of .Net core, most comments are pretty easy to implement.

**Comment by HarelM** [comment]
@valleyofdawn
1. Don't see I how squeeze all the data in the same line, also note the different GPX types, placing 3 buttons that says GPX is not a good idea...
2. Fixed the parentheses - also this is standard window style save as, I prefer to keep it this way.
3. Can you get me a svg file of the two diskettes?
To summarize:
 - [ ] Fix parenthesis
 - [ ] Allow save on drop-down click
 - [ ] Fix mobile devices ability to see all options
 - [ ] Change Icon

**Comment by valleyofdawn** [comment]
how about:
**KML**
**CSV**
**TWL**
Separate routes **GPX**
Combined routes **GPX**
Active route **GPX**

Please send me the single diskette CSV and I'll double it. It needs to be in the same style.

**Comment by HarelM** [comment]
[floppy-o.svg.txt](https://github.com/IsraelHikingMap/Site/files/873880/floppy-o.svg.txt)
Enjoy!
I'm not sure the above definitions are clearer than what is written now, I'm not sure which should be used when... :-)

**Comment by valleyofdawn** [comment]
Not clearer, shorter.
The scrolling in the mobile version doedn't work for me on chrome in
android 6.

**Comment by HarelM** [comment]
Yes, I've noticed, thanks for reminding me.

**Comment by HarelM** [comment]
I think I'll keep the current name, shorter is good but if the user doesn't understand what he's choosing it misses the point.
Can you send me the double floppy icon - I believe this is the only thing that is preventing this item from getting closed.

**Comment by valleyofdawn** [comment]
See if this works.

[floppies.svg.txt](https://github.com/IsraelHikingMap/Site/files/880284/floppies.svg.txt)
