### ISSUE TITLE
Route colours are not preserved by sharing

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#327]
For example, share http://israelhiking.osm.org.il/#!/?s=ExF4GI0D4A was created with routes in green, blue and orange:
![image](https://cloud.githubusercontent.com/assets/1304610/24103074/cbbbd026-0d86-11e7-94cb-3f158d5ceb92.png)
![image](https://cloud.githubusercontent.com/assets/1304610/24103101/e57ba00e-0d86-11e7-8fb3-827cf742e3a0.png)

When the above link is opened, the colors are different:

![image](https://cloud.githubusercontent.com/assets/1304610/24103157/17d45a50-0d87-11e7-8a6c-36695a863e9d.png)
![image](https://cloud.githubusercontent.com/assets/1304610/24103187/24b3a870-0d87-11e7-86b7-4715e63ec4b8.png)

If the sender refers to a "green" route, the receiver may not know which route is it.

**Comment by HarelM** [comment]
Up until now I tried to save only the pure data without the presentation but I agree with you that it's somewhat counter intuitive and break our rule of WYSIWYG...
I don't think that it should be saved to the GPX files though, I don't want to add more custom attributes (we already added the routing type).
This however opens the question if we should use KML as our default saved file since it contains this information.
I think GPX is more wildly used and therefore should be the default even if we loose the colors when saving to file.
What do you think?

**Comment by valleyofdawn** [comment]
Definitely GPX! You'll lose all the non-sophisticated users if you use exotic options.

**Comment by zstadler** [comment]
Please also preserve the original opacity.

Currently, the opacity for shared routes is overwritten by the last opacity level set.

For example, after creating a route with opacity=0.4 in a different window, above share link now looks like this:
![image](https://cloud.githubusercontent.com/assets/1304610/24342056/045ba358-12c7-11e7-8c50-c7c671cb9741.png)

While the originally shared route (as seen above) was:
![image](https://cloud.githubusercontent.com/assets/1304610/24103157/17d45a50-0d87-11e7-8a6c-36695a863e9d.png)

**Comment by HarelM** [comment]
Then you'll also probably want the line width as well, right?

**Comment by zstadler** [comment]
Yes. WYSIWYG

**Comment by zstadler** [comment]
Route attributes are not reflected in the thumbnail. For example, the thumbnail for 
http://israelhiking.osm.org.il/#!/?s=PmWmXA6ujt

<img width="600" alt="2017-03-29 14_36_51-israel hiking map" src="https://cloud.githubusercontent.com/assets/1304610/24452752/61215d22-148d-11e7-9017-6b41da64b1a8.png">

is

![pmwmxa6ujt](https://cloud.githubusercontent.com/assets/1304610/24452633/cff89c0c-148c-11e7-9579-c5af23e3b686.png)

**Comment by HarelM** [comment]
At some point I thought about updating the thumbnail since now the color is saved in the server but I forget.
Thanks for reminding me.
Note that POIs are still missing because the text is hard to do, and also it's a thumbnail and should be small.

**Comment by valleyofdawn** [comment]
Preserving the color would be nice but keep the tracks thick or they won't be visible.

**Comment by zstadler** [comment]
The example I've given has 0.5 opacity and a thinner line.

This is a screenshot of the same route with the standard colour, width, and opacity:

<img width="600" src="https://cloud.githubusercontent.com/assets/1304610/24458367/64d2baa6-14a1-11e7-86fc-5ab02605e5fb.png">

I think we need to have 200% of the width and preserve the opacity:

<img width="600" src="https://cloud.githubusercontent.com/assets/1304610/24458605/0c73b3d2-14a2-11e7-8cbf-cec9c2cceba3.png">

By the way, is there something to be done about the oval shape of the start and end points?
For example, can they be added after the image aspect ratio is modified, or added as a vertical oval with the reverse aspect ratio that will turn into a circle?

**Comment by HarelM** [comment]
I couldn't make it round, feel free to try... 😊
