### ISSUE TITLE
Invalid buttons on mobile

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#328]
To save space on the mobile version I suggest removing the following, less useful, buttons:

"+"
"-"
"edit"
"print" 
and the name of the OSM user, Use just a profile icon instead.

**Comment by zstadler** [comment]
The buttons are hidden also on half desktop (960px for my screen).

![image](https://cloud.githubusercontent.com/assets/1304610/24848801/48042926-1dd1-11e7-8032-f6309ef52ea4.png)

While the [Bootstrap documentation](http://getbootstrap.com/css/#responsive-utilities-classes) say the threshold for the ```.hidden-xs`` class is 768px, the actual minimum window width for showing the buttons is 1150px - a medium size in Bootstrap terms:

![image](https://cloud.githubusercontent.com/assets/1304610/24848702/a55d314a-1dd0-11e7-9902-c677f982da35.png)

**Comment by HarelM** [comment]
I don't have this issue on my PC: see the size of the window in the upper right corner.
In any case, I'm not planning on fixing bootstrap code...
![image](https://cloud.githubusercontent.com/assets/3269297/25058872/fe4e5fcc-2186-11e7-98c9-778322a73fad.png)
