### ISSUE TITLE
Export of new highway to OSM fails

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#333]
At the last stage, the procedure for exporting un-mapped segments to OSM fails with "לא ניתן לשלוח את המסלול" when pressing the "+" button.
Report from 2 separate users.

**Comment by HarelM** [comment]
I can't reproduce with my tracks, can you writes the steps to reproduce?

**Comment by valleyofdawn** [comment]
[problematic.gpx.txt](https://github.com/IsraelHikingMap/Site/files/887496/problematic.gpx.txt)
example file

**Comment by valleyofdawn** [comment]
Thanks!
