### ISSUE TITLE
Following link takes the map to zoom 0 for some reason http://israelhiking.osm.org.il/#!/?s=fLlar3V5ox

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#334]
http://israelhiking.osm.org.il/#!/?s=fLlar3V5ox
after opening it the address is:
http://israelhiking.osm.org.il/#/0/31.9522/35.1563?s=fLlar3V5ox
Notice the 0...

**Comment by zstadler** [comment]
Works well on Firefox.
Breaks on Google Chrome and MS-Edge.

**Comment by HarelM** [comment]
Might be related to this:
https://github.com/Leaflet/Leaflet/issues/941
Might need to call invalidateSize, might be related to the ng-cloak I added.
I'll try to play around with it...

**Comment by HarelM** [comment]
Ended up related to ng-cloak which delays the creation of the map div so the map is initialized with zero height and width.
