### ISSUE TITLE
Small improvements to height graph

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#337]
1) it bounces up and down when the buttons are hovered over
2) the title סטטיסטיקת מסלול is not longer valid. גרף גבהים.
3) probably no need for a title to the graph. It's self explanatory, especially given what the icon suggests

**Comment by HarelM** [comment]
1. Noticed, couldn't find a way to fix it, something colliding with angular-UI and leaflet, didn't try a lot though...
2+3. Title is needed so you can move the chart around using the title, text can be changed if needed.

**Comment by valleyofdawn** [comment]
It would be easier to drag a vertical line along the profile than a dot. You won't have to be exactly on the line.

**Comment by HarelM** [comment]
True, you need to click it now. somewhat related to #318.
I'm not sure what to do about this, the chart is not very good but other options I tested were even worse at the time when I added the chart, things might have changed since, but I really don't want to start from scratch and search for another chart framework.

**Comment by valleyofdawn** [comment]
As long as you can see it it's Okay. Not obvious to the user though.

**Comment by valleyofdawn** [comment]
I think Strava do it well:
![image](https://cloud.githubusercontent.com/assets/689201/24582569/533e0ff6-173b-11e7-8e60-4c1fdaaddcc5.png)

**Comment by HarelM** [comment]
I agree, This is indeed useful, note that you can't hover the route and see it on the chart though.
I think this deserves a different issue, maybe even reopen an old one...

**Comment by HarelM** [comment]
@valleyofdawn, please check if issue #318 covers what you need here assuming the implementation will be according to the above linked SO question.
If so, please close this issue.

**Comment by valleyofdawn** [comment]
I believe it does.

**Comment by HarelM** [comment]
Closing in favor of #318
