### ISSUE TITLE
Cannot add search result as a track

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#338]
To reproduce:
1. Search for "[סינגל ענבה](http://israelhiking.osm.org.il/#/?q=סינגל%20ענבה)" 
2. Select it from the search results
2. Click on the "+" button

The single is not added as a new track.

Reproduced on both Firefox and Chrome.

**Comment by HarelM** [comment]
Server side code issue, will happen in any browser. I'll take a look at it tonight, probably an issue with translating the search results.

**Comment by HarelM** [comment]
Code on server was not fully deployed, not sure why.
