### ISSUE TITLE
Use the title of the share in Whatsapp preview

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#339]
When sharing [this map](http://israelhiking.osm.org.il/#!/?s=PDJhQWbIE6) on WhatsApp
![image](https://cloud.githubusercontent.com/assets/1304610/24600156/fcf60262-185b-11e7-99ca-021d0c1d0a0b.png)

WhatsApp would show the generic title and description of Israel Hiking:

![image](https://cloud.githubusercontent.com/assets/1304610/24600101/d0510518-185b-11e7-8d6a-fff47849f1fd.png)

I suggest we supply the share's title, description (if exists), and thumbnail to WhatsApp. If the description does not exist, the generic description can be used.

**Comment by HarelM** [comment]
Can't, WhatsApp doesn't support the escape fragment protocol...

**Comment by zstadler** [comment]
Is "escape fragment" referring to ["AJAX Crawling (Deprecated)"](https://developers.google.com/webmasters/ajax-crawling/docs/specification)?

**Comment by HarelM** [comment]
I guess it does. I think google is deprecating it since they have no problem crawling the page using css and javascript, I believe this is not the case with Facebook and Whatsapp, I might be wrong though but I didn't manage to make it work without the ```_escape_fragment_``` specifications.

**Comment by zstadler** [comment]
If I understand correctly, the share mechanism is using the ```#``` annotation in order to activate client-side code. This code eventually requests the the share info from the server. The goal of the ```#!``` notation is to make third party servers to query the server directly. Right?
