### ISSUE TITLE
Smoother map switch

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#34]
While switching to a new map source, it would be more visually appealing to temporarily keep displaying existing map tiles rather than wait for the new ones to load with gray background.

**Comment by HarelM** [comment]
Not sure it's possible using Leaflet (the site's framework). I'll look it up, if I won't find I'll close this issue.

**Comment by zstadler** [comment]
When zooming in and out in the same map source the existing tiles are not
cleared. Instead, they are scaled and the new tiles just override them.
In the case of switching maps, perhaps all it takes is to avoid clearing
the map, and the tiles of the new map will just override the tiles of the
previous map.

**Comment by HarelM** [comment]
I'm not sure we want to go there...
