### ISSUE TITLE
GPX files without namespace definition cannot be imported

### ISSUE THREAD

**Issue by tallavi** [IsraelHikingMap/Site#340]
A GPX file without namespace definition (something along these lines:)

`<gpx xmlns="http://www.topografix.com/GPX/1/1" creator="CompeGPS" version="1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd http://www.garmin.com/xmlschemas/GpxExtensions/v3 http://www.garmin.com/xmlschemas/GpxExtensionsv3.xsd http://www.garmin.com/xmlschemas/TrackPointExtension/v1 http://www.garmin.com/xmlschemas/TrackPointExtensionv1.xsd" xmlns:gpxtpx="http://www.garmin.com/xmlschemas/TrackPointExtension/v1">`

cannot be imported.

Recreation of the issue - a minimal example of a GPX file that cannot be imported (but imports correctly in other tools):

`<?xml version="1.0" encoding="UTF-8" standalone="no"?><gpx creator="tallavi" version="0.31"><trk><trkseg><trkpt lat="31.9911112852259" lon="34.96162572"><ele>66.2</ele></trkpt></trkseg></trk><rte/></gpx>`

**Comment by HarelM** [comment]
Not sure what you expect, this is by design - we do not support bad formatted GPX files...
Where did you get the bad GPX file form? I suggest to open a bug there...

**Comment by HarelM** [comment]
@tallavi waiting for you comment, the issue will be closed if this doesn't get answered soon.

**Comment by tallavi** [comment]
Sorry for taking so long. I'll try to deal with it at the source. Thanks.
