### ISSUE TITLE
Allow changing the transparency of the height graph

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#341]
The graph is over the map and not clear.

Suggestions:
 * Add a transparency adjustment
 * Enable to move the graph window out of the main window.

Thanks,
Copy from: https://github.com/IsraelHikingMap/Map/issues/130

**Comment by HarelM** [comment]
To answer @Eli-Leshem 
1. The graph is transparent, can me more but then it might collide with the map.
2. Browsers doesn't work this way no more, this is not a desktop application with multiple windows that you can't say which window is related to which app. The graph is draggable and resizable so you can play with it as much as you like.
With the new design that leaves the statistics outside I think there's not much to polish here besides issue #318

**Comment by Eli-Leshem** [comment]
I didn't know about #2.
What I suggested on #1 is to put a slide on the graph that will enable to change the transparency as I wish.
Thanks

**Comment by HarelM** [comment]
I'm not sure how useful it will be to all the users, I try to keep the user interface as simple as possible so the user won't get confused with all the buttons.
I think this should only be visible in advanced mode (after clicking the yellow cogs in the layers menu) and should not allow the user to reduce it below 0.1 since both the slider and the graph will be transparent assuming I can control the slider's transparency and the graph's.
Can't promise anything since this sounds like a lot of work for very little benefit. 
Nevertheless, I'll keep this issue open.

**Comment by Eli-Leshem** [comment]
I was using before the statistics of Google earth. I feel it is more friendly. It is not transparent, so it takes some map area (can be adjusted), you can run smoothly across the graph and it provides the info w/o clicking.

![google earth statistics](https://cloud.githubusercontent.com/assets/26922824/24739113/fa79d196-1aa2-11e7-86ef-cabbe11ebf8b.JPG)

**Comment by HarelM** [comment]
Regarding hover, see issue #318.

**Comment by valleyofdawn** [comment]
I think controlling transparency is an overkill. We should't let the interface become too complicated.
I think that a fixed narrow non-transparent height profile would work better. Make it removable, though.
If it obscures the track, just drag the map and zoom out.

**Comment by Eli-Leshem** [comment]
I have no idea about solution's complexity.
I am using the height profile a lot when I plane a route.
I cannot use the map under the height profile anyway. Cannot click on the map as well as cannot see. Always I make the map small and above the profile.
I do drag the map when I which to make a snap shot of the height profile.
So, my bottom line likes the google earth way: separate, sizeable and removable.
Thanks

**Comment by zstadler** [comment]
Perhaps a short (small hight) graph shown take over some area in the lower part of the screen, similar to the way the layers pane take on the left side of window?

**Comment by HarelM** [comment]
We are conducting two separate discussion on the same topic.
Closing this in favor of #346.
