### ISSUE TITLE
Support for opening KML/KMZ files with areas

### ISSUE THREAD

**Issue by Eli-Leshem** [IsraelHikingMap/Site#342]
Will enable to add a layer of areas to the map, like military zones where it is not allowed to travel.

**Comment by HarelM** [comment]
Can you share such a file?

**Comment by Eli-Leshem** [comment]
I am on my phone, please find one in the files of the facebook.  "שטחי אש".

**Comment by Eli-Leshem** [comment]
[שטחי אש.zip](https://github.com/IsraelHikingMap/Site/files/906079/default.zip)

**Comment by Eli-Leshem** [comment]
![layer in google earth](https://cloud.githubusercontent.com/assets/26922824/24808241/a67b738e-1bc3-11e7-8ea2-d64fdfee0840.JPG)

**Comment by HarelM** [comment]
Can you better define the problem?
I took the kml file you sent and opened it using the open file and I can see all the zones (they do not have a fill but the border is visible) as can be seen in the image below:
![image](https://cloud.githubusercontent.com/assets/3269297/24827516/0eb88dde-1c54-11e7-960e-d9a487829a24.png)

**Comment by zstadler** [comment]
I think the request here, at a minimum, is to take the polygon style from the the KML/KMZ in order to allow area fill and avoid drawing of the a polygon outline. 

The style in the above example is:
```
    <Style id="style0">
      <LineStyle>
        <color>00000000</color>
        <width>0</width>
      </LineStyle>
      <PolyStyle>
        <color>3f2e1fbf</color>
        <fill>1</fill>
        <outline>1</outline>
      </PolyStyle>
    </Style>
```
It sets the polygon fill colour to ```3f2e1fbf``` and effectively removes the outline by setting its width is zero.

Links:
* [KML/KMZ reference](https://developers.google.com/kml/documentation/kmlreference)
* [PolyStyle definition](https://developers.google.com/kml/documentation/kmlreference#polystyle)

**Comment by HarelM** [comment]
KML are not the site standard format the site uses, therefore, as it does to any non-standard file, it convert it to GPX which looses all styling.
I don't see how to support this feature without migrating to KML. Since we concluded this is not what we want I don't see how to support this.

**Comment by Eli-Leshem** [comment]
My friend that provided the file will try to convert it to gpx with criss
cross lines (I am sure there is a name for this). If he succeeds, then will
it be possible to add it as a layer like strava?

On Apr 8, 2017 10:52 PM, "Harel M" <notifications@github.com> wrote:

KML are not the site standard format the site uses, therefore, as it does
to any non-standard file, it convert it to GPX which looses all styling.
I don't see how to support this feature without migrating to KML. Since we
concluded this is not what we want I don't see how to support this.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/IsraelHikingMap/Site/issues/342#issuecomment-292741560>,
or mute the thread

**Comment by HarelM** [comment]
No, you can convert it to GPX with the site right now, you don't need your friend's help.
But that won't take vector lines and convert them to a tile layer.
Sorry, There's not much to do here besides creating a tile server that returns tiles from the given KML file, which is extremely hard to do...
I think the best approach will be to find a reliable source for fire-zones and add those zones to OSM, this way all of us win.

**Comment by Eli-Leshem** [comment]
My friend asked me once, I think you didn't get it, about "stronger" formats like e00 shp mdb, that he can provide. Can they help?

**Comment by HarelM** [comment]
No, no other format besides tiles server will help with what you would like to achieve currently. Sorry...

**Comment by HarelM** [comment]
Closing since I don't have a good way to support this. Sorry...
