### ISSUE TITLE
Directory listing uses incorrect timezone

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#344]
The time in the directory listing seems to be 3 hours earlier than expected. Perhaps it is using GMT time rather than local time.

The actual times:
![image](https://cloud.githubusercontent.com/assets/1304610/24836532/1aca3982-1d27-11e7-9605-b242874c1a07.png)

The listed times:
![image](https://cloud.githubusercontent.com/assets/1304610/24836534/349740e4-1d27-11e7-8ebc-424a45670b86.png)

**Comment by HarelM** [comment]
My computer is dead, waiting for repair. Feel free to fix this:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.API/Controllers/BootstrapFontAwesomeDirectoryFormatter.cs

**Comment by zstadler** [comment]
My environment is not set-up yet.
I change the code, but I cannot test or deploy it.

The changes are:
* ```SpecifyKind(subdir.LastModified, Local).ToString``` instead of ```subdir.LastModified.ToString```
* ```SpecifyKind(file.LastModified, Local).ToString``` instead of ```file.LastModified.ToString```
