### ISSUE TITLE
Allow direct download of OruxMaps .db file

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#345]
An internal server error occurs when trying to download [OruxMapsImages.db](http://IsraelHiking.osm.org.il/Hebrew/OruxMaps/Israel%20Hiking/OruxMapsImages.db) from the [IsraelHiking.osm.org.il/Hebrew/OruxMaps/Israel Hiking/](http://http://IsraelHiking.osm.org.il/Hebrew/OruxMaps/Israel%20Hiking) directory.

Required for completing IsraelHikingMap/Map#127

**Comment by HarelM** [comment]
This is the relevant article - at the bottom there's a provider.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files
I'm currently setting up the environment.
