### ISSUE TITLE
Upgrade angular to 4.0.x

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#349]
This will probably require a few steps:
 - [x] Upgrade to latest angular (1.6.x)
 - [x] Migrate to components with angular-material as UI framework

**Comment by HarelM** [comment]
This requires an almost complete rewrite of the entire UI, I think it will be better to move to a branch if I won't be able to finish it in the next couple of days.

**Comment by HarelM** [comment]
Branch created. most of the rewriting is finished. looking into systemjs to bundle to fix cache issues and other leftovers.

**Comment by HarelM** [comment]
Mobile devices are not supporting all this cutting edge technology apparently :-(
Not sure how to proceed here... Firefox is crashing due to missing component. Chrome is not not doing what it should...

**Comment by HarelM** [comment]
Probably need to use angular-cli with visual studio in order to compile, AoT, tree shake and bundle.
Here is a reference:
http://candordeveloper.com/2017/04/12/how-to-use-angular-cli-with-visual-studio-2017/
Also this tutorial from angular documentation:
https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

**Comment by HarelM** [comment]
Following these issues:
https://github.com/marcj/angular2-localstorage/issues/80
https://github.com/angular/flex-layout/issues/270

**Comment by HarelM** [comment]
Both above issues are solved. 
There's still an issue with Chrome on android mobile, not sure how to solve this currently.
https://github.com/angular/angular/issues/17039
Also better styling is needed for the dialogs.
This covers most of what's needed in order to finish the migration.

**Comment by HarelM** [comment]
Most issues are now solved, merge the angular branch to stable.
Things that are still open - mainly UI:
 * Sidebar doesn't have margins the text is starting at the edge of the dialog.
 * Buttons don't have colors - some buttons should to indicate their importance.
 * Some dialogs appear bad on mobile devices.
 * The image at the OSM user screen is stretched.
 * When searching in the above dialog the change in the size is annoying.

**Comment by moshfeu** [comment]
Tooltips direction is `ltr` even if the selected language is Hebrew. It looks strange:

![direction](https://user-images.githubusercontent.com/3723951/27299897-80d455ae-5536-11e7-9840-fe81fd0a543d.jpg)

**Comment by moshfeu** [comment]
Wrong direction in the snack-bar-container too.
Also, it never disappearing never and it cover a part of the map.

![snack](https://user-images.githubusercontent.com/3723951/27300190-83ac3462-5537-11e7-86c0-b46ceb63cd8f.jpg)

**Comment by moshfeu** [comment]
The button "Upload a trace" under "My traces" doesn't do anything when click.

**Comment by HarelM** [comment]
Both were fixed, are you using the latest version?

**Comment by moshfeu** [comment]
I'm using the production test URL https://israelhiking.osm.org.il/test/#!/16/32.0572/35.3402

**Comment by HarelM** [comment]
Material beta 6 should fix most of the issues, I'll check the my traves button issue.

**Comment by HarelM** [comment]
I see. I haven't updated it with the latest fixes from yesterday. I'll do it tonight, good call!

**Comment by moshfeu** [comment]
When using the find directions option. What is the priority? The length of the track or the quality of the trail (e.g road vs unmaintained track)

**Comment by moshfeu** [comment]
The link "Download map for offline use" Should be decorate as link.


![link](https://user-images.githubusercontent.com/3723951/27301457-ed922b80-553b-11e7-9c43-e02530ba85db.png)

**Comment by HarelM** [comment]
I agree about the link.
Not sure I understand the directions question - there are mainly 3 routing profiles, each of them have a different set of parameters - foot is using the shortest route, other have other restrictions. 
We are using GraphHopper as the routing engine with their profiles.

**Comment by moshfeu** [comment]
By direction I mean => `dir: rtl` in css, right?

**Comment by HarelM** [comment]
I was referring to
> When using the find directions option.

**Comment by HarelM** [comment]
@moshfeu Thanks for the pull request! I'm proud to congratulate you on being the first contributor to IHM!
I have committed a few corrections myself to the dialogs so please make sure to take them before you continue to work.

Below is a screen shot from my mobile which I'm not sure how to resolve.
It's not a critical bug, but still.
I have updated the code on the test site with latest changes.
Also, we probably don't need the embedded text when using the mobile, right?
![image](https://user-images.githubusercontent.com/3269297/27460534-027f64bc-57bd-11e7-92a6-0a04bce540c2.png)

**Comment by HarelM** [comment]
I think the major issues are now resolved, mainly thanks to you. let me know if you see something that is preventing from publishing, I'll ask in the FB group for a small effort to test the new site.

**Comment by moshfeu** [comment]
About the embed code, I don't know. If user want to get the code and send it to somebody else who can embed it..

**Comment by valleyofdawn** [comment]
I would reduce the font size in the left window (layers, info and legend). It is disproportionately and unnecessarily large.

**Comment by HarelM** [comment]
I never received an embedded code message :-).
In any case, I think it should be part of a wiki for web clients, see issue #361.
Do we want to keep the help tab? I see no real benefit in keeping it since you have tooltip... I doubt someone really goes to read what written there and it get out dates every few changes...

**Comment by valleyofdawn** [comment]
I agree. The help tab is useless.

**Comment by moshfeu** [comment]
After quick QA it seems that the site can be published.

**Comment by HarelM** [comment]
I have found a bug in opening a shared route and am debugging another bug that is related to old API to send routes to the map using get request.
@zstadler @valleyofdawn can we remove the support for sending route through URL, e.g.:
https://israelhiking.osm.org.il/#!/?route2=h,31,34;h31.1,34.1
I tested it and it doesn't work any more, also it's an old API which I believe is no longer relevant.
Please approve.

**Comment by HarelM** [comment]
@moshfeu Thanks for QAing the site!

**Comment by zstadler** [comment]
> @zstadler @valleyofdawn can we remove the support for sending route through URL, e.g.:
https://israelhiking.osm.org.il/#!/?route2=h,31,34;h31.1,34.1

I have no objections.

**Comment by HarelM** [comment]
Keeping this issue open until I fix the CI and migrate the tests.

**Comment by SwiftFast** [comment]
Although the "help" tab was removed, the message pop up was not updated.

![screenshot from 2017-06-24 12-57-27](https://user-images.githubusercontent.com/28669244/27507684-c4f241e8-58dc-11e7-95cb-c41f30de9714.png)

**Comment by HarelM** [comment]
Good catch! I'll fix this.

**Comment by zstadler** [comment]
Additional issues related to the user data interface (shares and traces):
1. Personal OSM Traces are no longer sorted by descending time
2. When deleting a shared map, it is still shown in the list until it is closed and opened again
3. Opening the user data interface is significantly slower. 20 seconds or more for me, Firefox and Chrome.
4. The share URL should not be subject to the search. For example, nothing is filtered out if you type any character from in the string "http://israelhiking.osm.org.il/#!/?s=" or any of its sub-strings.

**Comment by HarelM** [comment]
Dialogs on mobile should look better, not like this:
![image](https://user-images.githubusercontent.com/3269297/27512037-e477d482-593c-11e7-9bd0-3f2c6298efad.png)

**Comment by zstadler** [comment]
Following the above screenshot and where applicable elsewhere:
- Different color for selected and non-selected buttons
- Text should warp within the buttons area
- Add some visual separation between different selections. In the above example: application, map and details level. In the example below: between the scrolling part and the rest of the dialog, between elements of the list

For the personal traces dialog:
![image](https://user-images.githubusercontent.com/1304610/27514296-50e37cb4-598f-11e7-9d9c-2f5480f08b5f.png)

- Reduce the thumbnail size in the personal traces dialog to the same height as the thumbnails in the shared maps tab of the dialog.
- Put all the header info of the personal traces dialog in one line: name, level, no. of updates, the search, and the "X" button.
- Remove the "close" button for the personal traces dialog. There already is an "X" button in the header.
- The buttons of an individual share should be evenly spaced vertically:
  ![image](https://user-images.githubusercontent.com/1304610/27514347-6baebe18-5990-11e7-8721-802c3d95b85b.png)

**Comment by zstadler** [comment]
![image](https://user-images.githubusercontent.com/1304610/27514488-c7f6ad8a-5994-11e7-9ebd-b63de960cce7.png)

- Reduce the truncation of text by decreasing the font size and increasing the width of the list.
- Allow viewing more results (without the need to scroll) by decreasing the gaps between the search results and allowing the bottom of the list to reach the bottom of the screen.

**Comment by zstadler** [comment]
Search URL no longer works. for example: [http://israelhiking.osm.org.il/#!/?q=עין שריג](http://israelhiking.osm.org.il/#!/?q=עין%20שריג)

**Comment by HarelM** [comment]
I can argue that it's no longer documented due to the fact that I removed the help :-).
I think this thread is too long.
Can you please open another issue for this?
I'll try to split the rest of the issues in order to keep record of each one separately.

**Comment by HarelM** [comment]
Closing this in favor of all the others I opened.

**Comment by zstadler** [comment]
Numeric-only node labels are written incorrectly in Hebrew mode:

![image](https://user-images.githubusercontent.com/1304610/27525295-3b3e65ca-5a45-11e7-903a-4f0f7629dcbf.png)
"30.6, 34.5" became "34.5 ,30.6"
- Lat and Lon where transposed
- Comma was moved after the space

The same node looks fine in English mode:

![image](https://user-images.githubusercontent.com/1304610/27534623-546b3d7c-5a70-11e7-9098-f6250d6a9d9f.png)

**Comment by valleyofdawn** [comment]
As an alternative to the comma, I would also accept a slash. Some sources use 30.632/34.543

**Comment by HarelM** [comment]
Please move this discussion to the POI feature.
