### ISSUE TITLE
Do not show SVGs in wikipedia popup POIs

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#354]
SVGs usually show a map of the area which is superfluous. Skip to the first PNG/JPG/GIF which is the illustrative image.

**Comment by HarelM** [comment]
The entire concept of POI will be revised under issue #363.
Closing this in favor of #363, hopefully we'll have good POIs in the near-far future.

**Comment by valleyofdawn** [comment]
I sincerely hope that the Wiki layer isn't terminated even if other POIs are introduced. A very useful layer because of depth of info and peer review.

**Comment by HarelM** [comment]
This will be revised then, can't promise anything. I see your point.
