### ISSUE TITLE
Add a POI using coordinates

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#356]
Following a ["כיצד ניתן לדקור נקודה לפי נ.צ?"](https://www.facebook.com/groups/994960670559126/permalink/1370503133004876/) post on Facebook.

To implement this feature, I suggest to extend the search interface. When the search phrase matched one of the following coordinate systems, the result would be a new marker:

- [Israeli Transverse Mercator (רשת ישראל החדשה)](https://en.wikipedia.org/wiki/Israeli_Transverse_Mercator) (ITM)
- [Israeli Cassini Soldner (רשת ישראל הישנה)](https://en.wikipedia.org/wiki/Israeli_Cassini_Soldner) (ITM)
- [World Geodetic System](https://en.wikipedia.org/wiki/World_Geodetic_System#WGS84) (WGS84)

Similar to the current handling of results of a location search, a new marker will be shown on the map and this marker can later be added as new POI.

Regular expressions may be used to check and classify coordinate-based search for POIs. Multiple regular expressions may be needed as the coordinates can be copied from sources using different formats.

ITM:
- `(\d{6})(?:\s*,?\s*)(\d{6})` where \2 <850000 and \2 >350000

ICS:
- `(\d{6})(?:\s*,?\s*)(\d{7})` where \2 >850000 - the latest unambiguous convention
- `(\d{6})(?:\s*,?\s*)(\d{6})` where \2 >850000 or \2 <350000 - 1 meter accuracy earlier convention
- `(\d{5})(?:\s*,?\s*)(\d{5})` where \2 >85000 or \2 <35000 - 10 meter accuracy earlier convention
- `(\d{4})(?:\s*,?\s*)(\d{4})` where \2 >8500 or \2 <3500 - 100 meter accuracy earlier convention
- `(\d{3})(?:\s*,?\s*)(\d{3})` where \2 >850 or \2 <350 - 1000 meter accuracy earlier convention

WGS84:
[Here](https://stackoverflow.com/questions/3518504/regular-expression-for-matching-latitude-longitude-coordinates#18690202) is a starting point for the geographic coordinates regexp. IMHO, there is still room for improvements in the suggestions there:
- Allow the use of  ͦ, ', " to denote degrees, minutes and seconds.
- Allow the use of `(?:\s+|\s*,\s*)` as a separator between latitude and longitude instead of a comma.
- Allow the use of `[NS]` and `[EW]` to denote latitude and longitude.
- Allow the use of a leading zero in 3-digit longitude degrees, as used in maritime navigation.

Note: The above regular expressions are using [.NET RE syntax](https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference)

**Comment by HarelM** [comment]
I generally agree with this concept. I think supporting ICM is an overkill - we don't present it in any of our views so the user can't really know for sure the point generated is in the right place...
Other than that, this is pretty simple and should be handled by the server.

**Comment by zstadler** [comment]
Still need to implement the missing WGS84 formats and ICS.

**Comment by HarelM** [comment]
As I said, I don't think we should support ICS.
Feel free to update the regex code in searchcontroller and the relevant tests.

**Comment by zstadler** [comment]
Fix the title of search result
![image](https://user-images.githubusercontent.com/1304610/27525295-3b3e65ca-5a45-11e7-903a-4f0f7629dcbf.png)

**Comment by HarelM** [comment]
what's wrong with the title?

**Comment by zstadler** [comment]
This is is actually a Hebrew/RTL issue. https://github.com/IsraelHikingMap/Site/issues/349#issuecomment-311017796

**Comment by zstadler** [comment]
@valleyofdawn [requested ](https://github.com/IsraelHikingMap/Site/issues/349#issuecomment-311019229) adding "/" as a separator

**Comment by zstadler** [comment]
Remaining issue: IIS routing definitions does not invoke the `GetSearchResults` task when the "+" character is present in the coordinate term.

A [workaround](https://github.com/IsraelHikingMap/Site/blob/04b6a0fc1f7f748f9189412e38fa29e6562a1eff/IsraelHiking.API/Controllers/SearchController.cs#L54-L60) was implemented for a similar issue with the "/" character

**Comment by HarelM** [comment]
I've fixed the issue with the "+" sign.
I removed the "/" in the client side code instead of trying to solve this in the server code (seems more elegant since we are changing the search term any way).
I have moved some code around to create a small loop around all the regular expressions.
I don't like the tuple much and I think the code can be event better if split each regex to a class, much like what I did with the conversion flow.
In any case, I did find that the following number is not handles correctly: "+32" and added a failing test for it, I would appreciate if you could take a look at it.
Also split the tests with names I thought were relevant, feel free to change the names of the tests.

**Comment by HarelM** [comment]
I have finished my refactoring. Now that it's complete, changing the delimiter for all expressions can be done in a single place. every class has only one responsibility and the tests are actually testing the coordinates.
@zstadler I'd be happy if you could go over the tests and see if it covers all the required scenarios (I used your tests and added a few of my own according to the code).
Tests are now under `converters/coordinatesparsers`

**Comment by HarelM** [comment]
Published to site and seems to be working. I'll fix the tests and close this issue.
