### ISSUE TITLE
Add an option to download GPX Route

### ISSUE THREAD

**Issue by davidih** [IsraelHikingMap/Site#358]
The current download for GPX files uses the Track trkType option only and not the Route rteType.
The GPX standard specifies Track as a recording of the activity and Route as the planed one.
Therefore, there are navigation apps which do not support tracks as planned routes.

The request is to add an option of GPX Route to the download menu.

**Comment by zstadler** [comment]
It is worth checking if "Route" formats can be used instead of the "Single Track" formats. Both "Single Track" variants can to be considered.
