### ISSUE TITLE
Control the space taken by C:\inetpub\logs\LogFiles\W3SVC3

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#360]
The space taken by the log files is growing by ~ 10Gb/mo.

Currently, there is no control over its growth.

References:
[MS Article](https://docs.microsoft.com/en-us/iis/manage/provisioning-and-managing-iis/managing-iis-log-file-storage)

**Comment by HarelM** [comment]
I have added a task to windows scheduler to support this and added a script to this repository.
