### ISSUE TITLE
Improving the appearance and behavior of the left layer window

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#365]
A few ideas on how to  improve readability and usability:

1. Font size could be reduced
2. Line spacing could be increased
3. The width should not be reduce when resizing the entire window
4. A minimum width could be set to show the layer icons to the right of the tool icons
5. Below a minimum width the text should not be shown. Only icons.

**Comment by moshfeu** [comment]
3. It happens after you resize the sidebar because the resize function set the `right` css prop instead of the `width`.
4. 5. Which icons the user should see?

**Comment by HarelM** [comment]
UX wise, big fonts and spacing creates a feeling of space and is defined as good UX, I wouldn't hurry up and change the font size.

**Comment by valleyofdawn** [comment]
4. The essential icons to see are the eye/pencil ones. These would allow you to turn on and off features without losing map space.

1+2. The fonts should be big, but not too big. I think the size and spacing in the search results is good.
To me the layers feel crowded as it is now.

**Comment by moshfeu** [comment]
4. But the problem is that all the user will see is a list with ,almost, the same icons so we will not know of which layer he will affect. I think that the minimum width should let the user to see the layer name. 

I think that the most disturbing thing is the wrong padding. We should set that equally to all sides.
![screenshot-newtab-2017-06-25-13-13-20](https://user-images.githubusercontent.com/3723951/27515279-43211564-59a8-11e7-94f1-57ca0f17e131.png)

**Comment by valleyofdawn** [comment]
The idea is to initially have full length where everything is visible. Only if you want to maximize working space would you minimize it to see just the control icons. This is especially useful with a mobile screen.

**Comment by moshfeu** [comment]
@valleyofdawn, About the font size. Now I can see that the size in your computer is bigger than in my computer. Maybe you changed the settings in your browser.. 
As much as I can see, the font in sidebar never set so it taken from the browser settings (unlike the search input, for example). Also, again as I can see, your browser doesn't render the font correctly, right? So the basic size of the font is bigger in your computer.

![screen shot 2017-06-25 at 2 05 29 pm](https://user-images.githubusercontent.com/3723951/27515594-81a6697c-59af-11e7-9200-055c0c07ccad.png)

**Comment by HarelM** [comment]
I see different fonts as well on chrome win 7.
![image](https://user-images.githubusercontent.com/3269297/27515648-1a62a878-59b1-11e7-8ce8-49d48c268a9a.png)

**Comment by valleyofdawn** [comment]
Indeed.  I'll check if I have accessibility set to larger fonts.

**Comment by valleyofdawn** [comment]
Issue was indeed due to my browser settings
