### ISSUE TITLE
Standardize font sizes 

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#366]
Maybe we should think of consistent font sizes in the site.
We have a very wide range right now from tiny tool-tips, through small track stats and search terms, medium search results and big layer elements.
It would look more clean and professional to have just 2 font sizes: small and medium.

**Comment by HarelM** [comment]
Current UI mainly follows the design rules of material design described by Google.
2 sets of fonts is not enough IMO.

**Comment by HarelM** [comment]
Sorry, This is too vague for me to address and too complicated to solve.
