### ISSUE TITLE
Sidebar drag right and then left is not working well

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#367]
due to the `max-width=400px` when trying to open the sidebar more than 400px and then try to reduce its size it doesn't do any thing.
I tried to fix it in the draggable-resizable derective but found it too complicated to I removed the max-width which causes the sidebar to be too large when opening it on the info tab.
I believe the info tab should be limited and not the who sidebar maybe, not sure...

**Comment by HarelM** [comment]
@moshfeu can you help with this?

**Comment by moshfeu** [comment]
I will take a look. The main problem is that the resize directive change the `right` property instead of the `width`. I will try to change it. Where are we using this directive except the statistics dialog?

**Comment by HarelM** [comment]
Only there. The reason why it uses right and not width is related to the hebrew support and the fact that the window is fully resizable and draggable.

**Comment by moshfeu** [comment]
I see. So, if we limit the info window width, it will be ok. Right?
We need to set `min-width` to the `#sidebar-wrapper` (to avoid all the panel shrink without proportion) and `max-width` the the info panel.

**Comment by HarelM** [comment]
I think this might solve it.
May be width and not max-width to still allow the user to extend the panel?

**Comment by valleyofdawn** [comment]
In the test site, reducing the window size when the side bar is open banks up the side bar.

**Comment by HarelM** [comment]
"banks up the side bar" - I don't understand what that means, can you send a screenshot?

**Comment by valleyofdawn** [comment]
Bangs. I can't recreate it.

**Comment by HarelM** [comment]
https://overpass-turbo.eu/ has a sidebar that does not restrict max-width - I'm guessing I can do the same or prevent from changing the sidebar width as I believe it is a feature that is not in use.

**Comment by zstadler** [comment]
Why make a change if there is no reproducible issue?

**Comment by HarelM** [comment]
The scenario is totally reproducible - the original one.

**Comment by HarelM** [comment]
Totally an overkill but this issue was open a long time ago and I wanted to close it.
I'll probable remove the ability to change the size of windows in general and particularly of the height graph and sidebar in the future, but for now the I just fixed this bug...
