### ISSUE TITLE
Remove old route GET API

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#368]
There's an API that probably no one uses that can tell the site how to draw a route by sending a request from in the URL.
This was good when the site did not have a server side, now it does and there's no reason to keep this API alive.

**Comment by HarelM** [comment]
@zstadler @valleyofdawn
Can I remove the baselayer Get API as well?
Currently we "support" this:
https://israelhiking.osm.org.il/#!/?baselayer=Israel_MTB_Map
Since no user in the right mind will try to use this and since you can share everything using a site share including base layer, I don't see a good reason to continue supporting this.
I can across this while removing the route get API...

**Comment by zstadler** [comment]
I also dislike the syntax of this "API", but I think the need to link to a specific maps is still there.

**Comment by HarelM** [comment]
I now remember why we needed to keep it - when you want to share a map and not share your other private maps...
We probably need to invest in "advanced" share options before we can remove this API.
I doubt anyone is actually using it though, I needed to reverse engineer the code before I managed to make it work for the MTB map... and I wrote this code... :-/

**Comment by zstadler** [comment]
It's more than that. I think we need a separate "landing page" URL for bikers. @valleyofdawn !?

**Comment by HarelM** [comment]
I'm not sure "more" is the right definition. Supporting a URL that will act as a landing page for bikers is different (and a lot simpler, much like the download URL) from supporting an API which can get any address a user wants to send to another user...

**Comment by zstadler** [comment]
> I now remember why we needed to keep it - when you want to share a map and not share your other private maps...

As far as I remember, a sharing link does not share a private map unless it is visible. At least that used to be the case.

**Comment by HarelM** [comment]
You're probably right, this makes more sense.
Which leads up back to not needing this API anymore...

**Comment by zstadler** [comment]
The download URL does not look better :-( 
Luckily, there is less of a need to send it by a message or email.
