### ISSUE TITLE
When deleting a shared map, it is still shown in the list until it is closed and opened again

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#370]

**Comment by HarelM** [comment]
@zstadler I can't reproduce the issue. can you elaborate what you did?
Make sure you refresh the browser prior to your test as something appear as if working but actually they don't...

**Comment by zstadler** [comment]
1. Create a share
2. Open "My shares" list
3. Click on te delete icon of the newly created share

No matter how many times you click, or how long you wait, the deleted share is not removed from the screen:
![image](https://user-images.githubusercontent.com/1304610/27537786-f3882480-5a7d-11e7-90e7-544ee80ca0d3.png)

**Comment by HarelM** [comment]
Published.
