### ISSUE TITLE
Improve the dialog appearence

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#371]
* Different color for selected and non-selected buttons
 * Text should warp within the buttons area
 * Add some visual separation between different selections.
 * Improve the appearance of images - no stretch - especially on mobile.

Maybe the solution is to remove the header and place all the content inside the body of the dialog to avoid big headers...?

Related to this as well:
angular/material2#4574

![image](https://user-images.githubusercontent.com/3269297/27512037-e477d482-593c-11e7-9bd0-3f2c6298efad.png)

**Comment by valleyofdawn** [comment]
To my eyes the map share dialog uses too small icons and too much white space.

**Comment by HarelM** [comment]
Can you please share a screen shot and maybe mark on top of it what you think should be fixed? The description is a bit vague...

**Comment by moshfeu** [comment]
@HarelM  I will try to take it if it's not argent (My availability it's quite limited)

**Comment by HarelM** [comment]
Please do! 😊

**Comment by HarelM** [comment]
I have published the fix. it looks a lot better, thanks @moshfeu. but I can't close this issue until the OSM user dialog looks better too...
One issue that I now saw is the case where you have no image. The site upper right is working good but when opening the dialog it has the nasty image broken link icon:
![image](https://user-images.githubusercontent.com/3269297/27662114-445d3506-5c65-11e7-94b6-53595f20d948.png)

**Comment by zstadler** [comment]
Also, the trace's images are too large. An image with the height of the 4 buttons is large enough.

**Comment by zstadler** [comment]
Also, it's better to keep the tab selection and "uploading a trace" visible at all times by taking them out of the scrolled area

![image](https://user-images.githubusercontent.com/1304610/27673292-8b32abd0-5ca8-11e7-829c-db9831aaa60b.png)

**Comment by moshfeu** [comment]
I'm on it..

**Comment by HarelM** [comment]
Dialog looks a lot better, thanks! especially the thumbnail frame for the traces!
The action buttons in the mobile view are to die for :-)
The only thing that caught my eye was the size of the upload button which is not aligned to anything. I think it either needs to be image wide or take the whole horizontal space.
I think the shares can benefit from these improvement as well.
Is this the only thing left in order to close this issue?

**Comment by moshfeu** [comment]
:) Sure..

https://github.com/IsraelHikingMap/Site/pull/393 - for aligning the button to center.

I think we covered all the dialogs. I will see what can I do for the share dialog. Definitely, reduce the size of the image and add the frame style.. I will see..

**Comment by HarelM** [comment]
@moshfeu any updates one this?

**Comment by moshfeu** [comment]
Sadly not. I'm little busy these days. I will try to push it when I will have some time to breath :)

**Comment by HarelM** [comment]
Closing in favor of #444.
