### ISSUE TITLE
Copy link doesn't work

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#374]
The "copy link" button doesn't work though the Facebook button works fine.
Also the design can be improved as the icons are smallish and there is too much white space.

**Comment by HarelM** [comment]
They have different actions, it makes sense that one button is working while the other doesn't.
Having said that, it's still a bug. I wonder if this issue exists in the OSM traces dialog as well as it uses the same infrastructure.

**Comment by HarelM** [comment]
Please use #371 for reporting design and appearance issues with the dialogs.
