### ISSUE TITLE
Avoid searching within the URLs of the shared maps list

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#377]
The share URL should not be subject to the search. For example, nothing is filtered out if you type any character from in the string "http://israelhiking.osm.org.il/#!/?s=" or any of its sub-strings.

**Comment by HarelM** [comment]
The mechanism now converts the entire share object into string and searches in it:
`JSON.stringify(object).toLowerCase().indexOf(searchTerm.toLowerCase()) !== -1;`
I don't think complicating this code is worth in order to support this feature, you can always refine your search, it's reflected instantly...

**Comment by zstadler** [comment]
I respectfully disagree. It is a nuisance if you search in English.

**Comment by HarelM** [comment]
Although we do not agree, I'll see if I can make a non hard coded fix to this. I do not want to add properties of classes and stuff that can break later on.

**Comment by HarelM** [comment]
I now see that the site shares have a lot of data stored behind and the search is not really doing what it should. I'll create two different methods for traces and shares.

**Comment by HarelM** [comment]
Since date is tricky I decided not to allow searching for it. If you think it's important feel free to add it.

**Comment by zstadler** [comment]
Which fields are being searched after the fix?

**Comment by HarelM** [comment]
description, title and number of watches.

**Comment by zstadler** [comment]
IMO, the number of watches should not be searched.

**Comment by HarelM** [comment]
It might help to some people, I don't see a good reason to remove it... I assume users will not search for numbers most of the time, but it is presented so why not?

**Comment by zstadler** [comment]
I don't think this is expected by any user. 
- This data changes without the user's control
- Including it prevents efficient search of numbers within the title or the description

**Comment by HarelM** [comment]
I have no real objection, I'll remove it next check-in...
