### ISSUE TITLE
basic keyboard navigation should work (arrow panning and zooming)

### ISSUE THREAD

**Issue by hesher** [IsraelHikingMap/Site#380]
Leaflet maps are usable with a keyboard by default (check out http://leafletjs.com/)
For some reason, this functionality was removed for Israel Hiking Map.

It should be un-removed :)

**Comment by HarelM** [comment]
Can you specify a scenario that you think should be useful and is currently not working (I'll use it to test that I have fixed the issue)?
The reason why the keyboard was disabled is due to a bug in leaflet that I thought should be solved by it.
It doesn't solve the bug but I left the code with keyboard disabled (probably my mistake).
The following is the relevant bug:
https://github.com/Leaflet/Leaflet/issues/5499

**Comment by HarelM** [comment]
It appears a new version of leaflet was released yesterday with the relevant bug fix (1.10).
I'll see if I can upgrade to it to get this bug fixed.

**Comment by hesher** [comment]
The scenario is very basic. I'll suggest a few:
1. You're on your laptop viewing the map and would like to scroll and zoom to a certain location. With a trackpad, it can get a little annoying. Much easier to get somewhere by zooming out (pressing -) panning with the arrows and zooming back in (+).

2. You're creating a route. You use the mouse to create the route and the keyboard to move the map.

In the end it's a matter of preference. I guess enough people use the keyboard to have it been supported by default in all map rendering platforms. (That I'm aware of)

**Comment by HarelM** [comment]
I'll see if removing all the "keyboard: false" from the code and upgrading to 1.10 helps with this issue. If you wish to contribute to fixing it I'll be delighted though (I think this is a pretty easy bug...) :-).

**Comment by hesher** [comment]
So basically remove keyboard: false and upgrade leaflet? 
		

		
	





On Wed, Jun 28, 2017 at 2:28 PM +0300, "Harel M" <notifications@github.com> wrote:












I'll see if removing all the "keyboard: false" from the code and upgrading to 1.10 helps with this issue. If you wish to contribute to fixing it I'll be delighted though (I think this is a pretty easy bug...) :-).

**Comment by HarelM** [comment]
Yes, and making sure everything is working as expected.

**Comment by HarelM** [comment]
@hesher do you want to try and create a pull request for this? The more contributors the happier I get :-)

**Comment by hesher** [comment]
wait a sec. ASP.net??! I'm on a mac :)

**Comment by HarelM** [comment]
The client side is angular-cli, you don't need the server side for this, I think.

**Comment by hesher** [comment]
Contacted you on facebook chat. Trying to bring up a running environment

**Comment by HarelM** [comment]
Answered there, but in general, here would be a far better place to contact me as my facebook is not so active...

**Comment by HarelM** [comment]
Let me know if you need any help.

**Comment by HarelM** [comment]
@hesher any updates on this?

**Comment by hesher** [comment]
Tried several times to run the project on a mac. (today again)
don't have enough time to fully research this

**Comment by HarelM** [comment]
No worries, there will be plenty opportunities in the future I believe. But you should try following angular-cli getting started guide and see if you can manage to create their example, if so, this project is just an elaborate example of the same thing...

**Comment by zstadler** [comment]
The "+" and "-" keys change the zoom level in steps of 3 rather than 1.

**Comment by HarelM** [comment]
This is the default behavior, I didn't touch it.

**Comment by zstadler** [comment]
Correction:
"-" and "=" change the zoom in steps of 1.
"_" and "+", being the shift- version of the above keys, change the zoom in steps of 3.

Seems OK to me.

**Comment by hesher** [comment]
Sounds like a feature to me :)
