### ISSUE TITLE
Check Graphhopper memory usage

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#382]
The Graphhopper takes more than 6Gb of memory. It is twice as much as it was a few months ago.

**Comment by HarelM** [comment]
The main reason for that is that now GH is never restarted as opposed to previous version. Seems like a memory leak. For now you can restart the service to reduce the memory.
This might due to the changes I made in the code but it also might not.
Is there a chance you can try and solve this?

**Comment by zstadler** [comment]
It sure looks like a memory leak. After restart it takes less than 800Kb, and the working set is less than 300Kb.
It will be interesting to see if the leak is a result of the DB update or the searches.

**Comment by zstadler** [comment]
Any update?

Between Graphhopper, Elastic search, and the dotnet web service, more than 10Gb are taken at any given time.

When MOBAC is creating the offline maps, the server has a high page fault rate which slows the server down.

<img width="392" alt="2017-08-11 15_53_28-clipboard" src="https://user-images.githubusercontent.com/1304610/29213881-d8c457c8-7ead-11e7-98a0-abcecfda0ccc.png">

**Comment by HarelM** [comment]
I was under the impression you are looking into it. Might be an issue with the GH code I added, but can also be in their code.
I'm not very familiar with java performance tools and would geatly appreciate if you could take a shot at it.

**Comment by zstadler** [comment]
This issue is a result of the change in the service update approach which you designed. I'll let you handle this.

**Comment by HarelM** [comment]
Ok.
I have restarted the service (It was on 4Gb memory, now on 300Mb) and commented out the updates (in `UpdateDb.bat`).
I want to leave it for a week or so and see if the cause is the updates or the routing requests.
I hope this is fine by you - I think the users can suffer a week without updates.
Is there a tool you are familiar with to keep track of the memory of this process while it's working?

**Comment by zstadler** [comment]
One option is to run `wmic`, for example every 1800 seconds (30 minutes):

```batch
wmic process where 'processid=11044' get VirtualSize,WorkingSetSize /every:1800 > c:\temp\wmic.log
```

Note that the old update approach indirectly handled memory leaks of any source because the service was restarted at least once a day.

**Comment by zstadler** [comment]
It seems like the process memory usage is stable at around 3.3 Gb

**Comment by HarelM** [comment]
Sounds too much IMO, Might have to do with the JVM configurations, I'm no expert in Java though.
I'll open an issue in their repository and see what they answer.

**Comment by zstadler** [comment]
Note that the issue is about twice that much

**Comment by HarelM** [comment]
See discussion here:
https://github.com/graphhopper/graphhopper/issues/1143
How much do you think will be enough but not too much? ~1Gb?
Let's try and use the `-xmx` flag and see what happens...

**Comment by zstadler** [comment]
IMO, it's reducing the memory size as much as possible without spending too much time on GCs. 

One GC every thousand routing requests seems reasonable to me.

**Comment by HarelM** [comment]
That's a bit vague... I can't translate from GC calls to total memory consumption :-/
I'll use 1 Gb and see what happens...

**Comment by zstadler** [comment]
It looks like this did not change the memory consumption much
![image](https://user-images.githubusercontent.com/1304610/30558442-14536d86-9cba-11e7-99f2-bf9ec6e70d5d.png)

**Comment by HarelM** [comment]
Probably other flags are needed (I hope this can be fixed with flags).
Here's an article about it which is worth exploring:
https://plumbr.eu/blog/memory-leaks/why-does-my-java-process-consume-more-memory-than-xmx

**Comment by zstadler** [comment]
Will also be using [GCViewer](https://github.com/chewiebug/GCViewer) - a GC analysis tool for Java.

**Comment by HarelM** [comment]
Thanks for taking care of this!
