### ISSUE TITLE
Search results list doesn't disapear

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#383]
How to reproduce - perform a search and decide not to use it:
- Search for something like "מגידו"
- DO NOT to click any of the search results
- Click on the search button

What happens
- The search text box disappears, but search results list remain on the screen
<img width="227" alt="2017-06-29 13_07_31-israel hiking map" src="https://user-images.githubusercontent.com/1304610/27686511-bca923fa-5cdb-11e7-8f9a-983e89408de8.png">

What I expect to happen:
- Both the search text box and search results list should disappear

**Comment by HarelM** [comment]
Yes, I saw it to but was unable to fix it unfortunately...
