### ISSUE TITLE
Update file names to match Angular style-guide

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#385]
The following is the Angular style guide which should be followed, mainly files names should be changed.
https://angular.io/guide/styleguide
Since this also requires to move the tests to be beside the production code I'll use this issue to bring back the tests as well.

**Comment by HarelM** [comment]
@moshfeu I think most files were updated to match the file names in angular style guide and I believe you can re-fork.
Let me know if you encounter anything out of the ordinary, otherwise I'll close this issue.

**Comment by moshfeu** [comment]
WOW, Great job! 
To be honest, I'm not familiar with angular style, but I looked on some commits and its look great!
I re-forked yesterday, but I fetched again now, so I think I'm good.
Slowly and safely I'm learning to use git and github, better.

**Comment by HarelM** [comment]
There's a link at the beginning of this thread if you want to read, here it is again:
https://angular.io/guide/styleguide
It's a bit long, but describes coding conventions related to angular development.

**Comment by moshfeu** [comment]
Yes, I started to read this but I will need a week vacation to read all ;)

**Comment by HarelM** [comment]
I think this covers most of what I wanted to do here. Closing for now, other small efforts will be done as we go.
