### ISSUE TITLE
Add Nakeb layer

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#386]
Either as is - meaning another layer or allow expanding the overlays (if there will be a lot, not sure yet).
API is the following:
All routes
https://www.nakeb.co.il/api/hikes/All
More data by id:
https://www.nakeb.co.il/api/hikes/1
Hopefully will be able to do it soon.

**Comment by HarelM** [comment]
Planing on allowing this layer to be seen only from zoom 11 and above.
I still need to improve the POI marker popup design, but other than that the code is pretty much complete.
Here's a preliminary screen shot:
![image](https://user-images.githubusercontent.com/3269297/27959853-c6874184-6331-11e7-9122-f5549fc3f437.png)

**Comment by HarelM** [comment]
Well, I was ready to upload the changes to the site but I noticed it takes too long to fetch the data:
In the image below you can see that it took 20 seconds to fetch the data.
Should I be caching the responses on my server? I rather not if I don't have too...
![image](https://user-images.githubusercontent.com/3269297/27989437-74ef4216-6441-11e7-8f94-d869ee58051f.png)
Is this a maintenance task that is running that can cause this?

**Comment by MatanBenMoshe** [comment]
It seems there was some maintenance there, but I also added cache improvements.
Please recheck now:
![image](https://user-images.githubusercontent.com/17752588/27989651-08d7cd50-6446-11e7-9fe6-441407e5aa32.png)

**Comment by HarelM** [comment]
Sorry, forgot to mention I already saw that it returned to acceptable delay. 
I'll post on Facebook soon, but you can start admiring how it look and feels in the site, I have just published it...

**Comment by HarelM** [comment]
@MatanBenMoshe Just posted on facebook, let me know if there's anything else you want me to add.
Regardless, Are you duplicating the routes that are shared when creating a new content in your site?
I hope you do since OSM users can now delete their shares so you can't relay on it (you probably thought about it too, but I just wanted to make sure you are aware of this issue).
