### ISSUE TITLE
Migrate to Proj4Net instead of ITM

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#387]
The following issue is the relevant one to facilitate the translation:
https://github.com/NetTopologySuite/ProjNet4GeoAPI/issues/16
Unfortunately, Proj4Net is not written in .net core so this requires another effort to migrate it which is somewhat covered here:
https://github.com/NetTopologySuite/ProjNet4GeoAPI/issues/11
Unfortunately the code exists but there's no NuGet package...

**Comment by zstadler** [comment]
What is the difference, in meters, between the results of the old code and the results of the new code?

**Comment by HarelM** [comment]
According to linked issue about 0.5 cm.
