### ISSUE TITLE
Upload a trace doesn't work

### ISSUE THREAD

**Issue by moshfeu** [IsraelHikingMap/Site#389]
**Steps:**

1. Click the button.
2. Choose a file

**Expected result:**

The file will appear in the traces list.

**Actual result:**

Nothing happen. No loader, no errors in the console, no xhr call in the network panel.

**Comment by HarelM** [comment]
The following is the generated code from `ng build --prod`:
For some reason `e` is undefined and file service method is not called.
I'll try and understand why this happens, probably related to AoT or production minification process...
```
l.prototype.uploadToOsm = function(e) {
                var l = this;
                e && this.fileService.upload(M.Urls.osmUploadTrace, e).then(function() {
                    l.toastService.success(l.resources.fileUploadedSuccefullyItWillTakeTime),
                    l.userService.refreshDetails().then(function() {
                        l.updateFilteredLists(l.searchTerm.value)
                    })
                }, function() {
                    l.toastService.error(l.resources.unableToUploadFile)
                })
            }
```

**Comment by HarelM** [comment]
Maybe I need to use the same method done in `FileComponent` and `file.html`:
`<input type="file" name="file" id="openFile" (change)="open($event)" [style.display]="'none'" />`
```js
public open(e: any) {
  let file = e.dataTransfer ? e.dataTransfer.files[0] : e.target.files[0];
```
I'll try and fix it tonight, thanks for reporting!

**Comment by HarelM** [comment]
I'm sure I fixed it in this commit and also tested it: f4cf75400e725a2ef3a5c6e5e35a3e55b1a7d4fb
Apparently this wasn't enough... :-/

**Comment by HarelM** [comment]
Tested and published. Apparently I didn't really tested it up until now as the code wasn't referring to the right server address...

**Comment by moshfeu** [comment]
Works for me too. Thanks 👍
