### ISSUE TITLE
Text breaks in some screens on the main leaflet buttons.

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#394]
The following image describe the issue well - the text is breaking:
In other screen there is a gap missing after the profile image.
![image](https://user-images.githubusercontent.com/3269297/28006068-5e746366-6556-11e7-9950-040e8439366f.png)

**Comment by moshfeu** [comment]
I see it's happening in the statistics parts too. Which browser / resolution / OS it's happening?

**Comment by HarelM** [comment]
I see it at work, win 7, chrome, regular resolution.

**Comment by moshfeu** [comment]
That's wired. I just tested it on win7 and chrome using browserstack.com and it looks fine. Which exactly Chrome version are you using?

**Comment by HarelM** [comment]
Probably related to screen resolution, in any case my PC was not the only place I saw it.

**Comment by moshfeu** [comment]
I will check in the evening at home. What is your resolution?

**Comment by HarelM** [comment]
1920x1080 24" screen.

**Comment by moshfeu** [comment]
Not reproduced on windows 7, Chrome 1920x1080 22".
Try to add `white-space: nowrap` to the `.control-container-item.gutters` elements see if it solved it.

**Comment by HarelM** [comment]
This partially fixes the problem:
![image](https://user-images.githubusercontent.com/3269297/28084449-552370d2-6681-11e7-8a5d-be0152d6f032.png)
I've tried `display:block` but it moves the text to the top of the span which is not great either, can be probably be fixed with `margin-top` but it feels too dirty already:
![image](https://user-images.githubusercontent.com/3269297/28084549-9b1cf144-6681-11e7-9baf-234ec68cfcab.png)

**Comment by moshfeu** [comment]
Why did you added `display: block`? Now it `display: table-cell` that's why `vertical-align: middle` works.

**Comment by HarelM** [comment]
Before display block the text breaks as can be seen in the first image.

**Comment by moshfeu** [comment]
And doesn't `white-space` solved it?

**Comment by HarelM** [comment]
Nope, take a look at the first image...

**Comment by moshfeu** [comment]
Yes, you are right. The strange thing is that even if I add many letters to the name it won't break on my computer. Are you sure that you are in the default zoom: 100%? If I do zoom-in (110%) the issue reproduce.

**Comment by HarelM** [comment]
100% sure I'm in zoom 100% :-) I have no clue as to why this behaves this way... probably needs some css massaging... I'll try to get to it in a few days...

**Comment by HarelM** [comment]
The following should do the trick - tested using the browser - should be changed according to coding standards
```html
<div class="control-container-item gutters">
    <div style="display:  table-cell;vertical-align: middle; height: 30px;">
		<img alt="" class="" height="16" width="16" src="imgeurl" style="float:  right; margin-left: 5px;">
			<span class="pull-right" hidden=""><i class="fa icon-user fa-lg"></i></span>
			<span class="hidden-xs" style=""> Harel M</span>
    </div>
</div>
```
