### ISSUE TITLE
Add the OSM labels to the items in the legend 

### ISSUE THREAD

**Issue by moshfeu** [IsraelHikingMap/Site#396]
So it will easy people to add the right labels and they will not have to search for them in the (long) documents in the wiki.

Image for demonstration:

![screen shot 2017-07-11 at 1 04 34 pm](https://user-images.githubusercontent.com/3723951/28063414-b8bc8b9e-6639-11e7-8671-7b6f313d5ea1.png)

It can be in tooltip or something.

In that matter, I just throw and idea to allow to user to add points to OSM via the website, similar to the option to add roads. Not via "my tracks" but only by adding a point to the map.
It will help to the users to do so online during their trip. I needed it myself once.

**Comment by HarelM** [comment]
The first suggestion can truly be helpful, although might be hard to maintain.
About editing in OSM, there are apps that can do it, @zstadler probably knows a few.
I don't want to create an OSM editor out of the site, their editor is very good and there's a button to take you to the relevant location in our site. Their website is not very mobile friendly, but I believe you should open a suggestion there and see if they are willing to improve the mobile experience instead of rewriting it here.

**Comment by zstadler** [comment]
Perhaps the URL for the appropriate wiki page can be embedded in the translated text on translate.zanata.org?

For example 
`<a href="http://wiki.openstreetmap.org/wiki/Tag:historic%3Darchaeological_site">אתר ארכאולוגי</a>`
instead of 
`אתר ארכאולוגי`

**Comment by zstadler** [comment]
The [maps.me](https://maps.me) application offers a simple interface for adding many types of POIs.

**Comment by moshfeu** [comment]
@zstadler 
1. Good idea.
2. Thanks for introduce the app. It's quite good. It's not fully updated (many new places and roads are missing) and it's not including Israel Hiking maps. I, personally, preferred to do this with the interface of Israel hiking website, but understand what @HarelM say. Although, the idea come from the option to add roads from the website to OSM..

**Comment by HarelM** [comment]
I have Added the following to the legend capabilities:
1. link
2. osmTags
Here is how it looks for a sample I made - the mouse is missing which turn into a hand when hover and you can see the tooltip.
![image](https://user-images.githubusercontent.com/3269297/31395284-17f9f83e-ade9-11e7-8abc-7ac752f8c5f0.png)
The main issue that still needs to be addressed is adding the relevant info to the following file:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.Web/sources/application/components/sidebar/info-sidebar.component.ts

**Comment by zstadler** [comment]
Notes:
- Providing accurate osm tags for some legend entries could be a problem. For example, [barriers classification in the hiking map](/IsraelHikingMap/Map/blob/master/Rules/IsraelHiking.mrules#L393-L416). The text may end up simplifying the actual rules used. 
- There are also slight differences between the Hiking and the Biking maps.

**Comment by HarelM** [comment]
True, but I believe it is better than nothing, and should provide a fair starting point...

**Comment by zstadler** [comment]
Agreed

**Comment by zstadler** [comment]
Is it possible that the tooltip will show when the mouse hoovers any part of the legend entry, including the map, not just the text? It is especially important for "way" entries.

Compare:    
<image height="161px" src="https://user-images.githubusercontent.com/1304610/32648532-dd1b38da-c5fe-11e7-8488-d34971a3c4c4.png"> &nbsp;&nbsp; vs. &nbsp;&nbsp; <image height="161px" src="https://user-images.githubusercontent.com/1304610/32648654-886bdb18-c5ff-11e7-8abc-cd5787605cca.png">

Also:
1. Please increase the text size in the tooltip.
2. The tooltip appears over the next legend entry, which is hard to see and confusing.
3. When the tooltip is shown, clicking on the legend    
    <image height="103px" src="https://user-images.githubusercontent.com/1304610/32648860-6a9b1634-c600-11e7-8cf7-b6b3cff59bb2.png">    
    opens a new window in the same map position. IMO, either the map would open in the location shown by the legend, which will provide a larger context for the legend item, or a click should not be active there.

**Comment by HarelM** [comment]
I probably made some errors, so feel free to review it and pull request the relevant fix.
I didn't add links to OSM wiki, if any one is up for it feel free to pull request it too.
