### ISSUE TITLE
After adding a new track. Editing mode should be on.

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#397]
A confusing extra click.

**Comment by valleyofdawn** [comment]
Also when choosing a track from a list of available tracks. When I turn on the pencil icon on the left panel my expectation is that this track would become editable without an extra step.

**Comment by HarelM** [comment]
Edit can be done for route and poi separately so the application asks for you too choose instead of choosing for you, but I can agree it makes sense to do it automatically.
