### ISSUE TITLE
Add Nakeb route

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#399]
When Nakeb marker pops-up the route should be presented to the user.
There is a question here what to do in case the popup hides the route itself.
A possible solution would be to allow the user to toggle the route from the popup, it should be hard but might not be intuitive (every marker you open leaves a route behind).
I'll strat with a simple and naive implementation and see how it feels.

**Comment by HarelM** [comment]
@MatanBenMoshe initial implementation has been uploaded to test site:
https://israelhiking.osm.org.il/test/
The popup hides parts of the route, I'll see how I can solve this. 
I also want to add "convert to route" feature that will allow you to take this route and add it to your routes and edit it.
Let me know if you see any issues with current implementation.

**Comment by MatanBenMoshe** [comment]
Hi,
Thank you for your implementation. It's very convenient now!
- Not sure I understand your feature suggestion- do you mean a way for adding new route into Nakeb routes?
- I found one issue that when you zoom out and points are clustered (merged) the route disappeared. It can be unfriendly when two routes have the same start point.
- why the layer is limited to zoom 11 and above? I think it's better to have it also in lower zoom levels.

**Comment by HarelM** [comment]
No, what I meant was the second issue.
Zoom 11 was selected in order not to clutter the map at low zoom levels but still give a wide enough view.

**Comment by MatanBenMoshe** [comment]
OK.
I think it will be nice to reconsider the zoom threshold. Does it looks so bad?
I heard from a few people that selected the layer but didn't see any change on map and thought they do something wrongly.
The point is the user have no way to know that he needs to zoom in for seeing the points.

**Comment by HarelM** [comment]
I see, I thought about this issue too now, I'll experiment with it and see if it's ok or not...

**Comment by HarelM** [comment]
@MatanBenMoshe Can you add `alt` for the route points? I see that when converting to route in the site a request with all point is sent to the server to get the altitude of each point, if you have this data already it would help as the url of the altitude request gets very long...
I already implemented the code that uses what you send or sets it to 0 if it was not sent so no further code changes are required on my part.

**Comment by MatanBenMoshe** [comment]
I already have it in the route points, no?
What do I miss?
"latlngs": [{"lat": 33.251505651033376, "lng": 35.72939254142142, "**alt**": 796.0}, {"lat": 33.251505651033376, "lng": 35.72939254142142, "alt": 796.0}, ...

**Comment by HarelM** [comment]
Never mind, my bad, for some reason I was sure it wasn't being sent. This explains why I didn't see a request to my server for elevation yesterday after I added this fix... I guess I should be developing in more reasonable hours ;-).

**Comment by MatanBenMoshe** [comment]
:)
