### ISSUE TITLE
Whatsapp route sharing in IOS is not working

### ISSUE THREAD

**Issue by MatanBenMoshe** [IsraelHikingMap/Site#400]
See the error in the attached picture.

![image](https://user-images.githubusercontent.com/17752588/28210897-7fea6604-68a2-11e7-9707-8f61d390096b.png)

The right way to share in whatsapp should be something like:

`<a href="whatsapp://send?text=my_text_and_link_to_share" data-action="share/whatsapp/share">Share it!</a>`

If you want to go to new line in the text message use '%0A' instead of '\n'

**Comment by HarelM** [comment]
Can you share a site that you know allows whatsapp sharing using iPhone - meaning when you click on a button whatapp application opens and allows you to send a message? This is the current experience in android.

**Comment by MatanBenMoshe** [comment]
https://www.nakeb.co.il
Only in cellphone the share button appears.

**Comment by HarelM** [comment]
The following is the code I use for whatsapp share:
```
this.shareAddress = this.osmUserService.getUrlFromSiteUrlId(data); // full address of url
let escaped = encodeURIComponent(this.shareAddress); // escape
 this.whatappShareAddress = `whatsapp://send?text=${escaped}`;
```
Can be found here:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.Web/sources/application/components/dialogs/share-dialog.component.ts

I don't see any new lines, How should I change the code in order to make it work?
The problem is that I'm missing the `data-action`?

**Comment by MatanBenMoshe** [comment]
I tried and in Nakeb it works for me also without data-action.
Can it be related to unsafe prefix? Or maybe the encodeURIComponent?
I get in IOS the following link:
`unsafe:whatsapp://send?text=http%3A%2F%2Fisraelhiking.osm.org.il%2F%23!%2F%3Fs%3DsSGpnvfEb0`

**Comment by HarelM** [comment]
The unsafe might be it, it was automatically added lately by angular framework.
Did it used to work and stopped recently or never worked for you?

**Comment by MatanBenMoshe** [comment]
It never worked for me.
I noticed this issue first time on 19/04/2017.

**Comment by HarelM** [comment]
I have uploaded a version with safety override to the test site, can you check if it works? Sorry for nagging, I don't have an iPhone for testing...
https://israelhiking.osm.org.il/test/

**Comment by MatanBenMoshe** [comment]
Sorry but I still see the same problem :(

**Comment by HarelM** [comment]
I have created a small plunker [here](https://plnkr.co/edit/hEUYzG74IGd9sT7IkllY?p=preview).
Let me know if any of the two buttons are working, If both don't work, I'll be glad if you could change the code somehow to make them work.
I'll be happy to do it myself but the fact that I can't test and debug it makes it harder for me to find the solution...

**Comment by MatanBenMoshe** [comment]
I think the second one is fine. Can you put it in your site/test so I'll be able to verify it?

**Comment by HarelM** [comment]
I've just published the site to production, this is included, please close this issue if it is solved, let me know if it's not.

**Comment by MatanBenMoshe** [comment]
Fixed with the new version
