### ISSUE TITLE
Website get stuck in load page in Safari in incognito mode

### ISSUE THREAD

**Issue by MatanBenMoshe** [IsraelHikingMap/Site#401]
![img_4020](https://user-images.githubusercontent.com/17752588/28211437-56d60b8a-68a5-11e7-9ed6-1724a4229c05.PNG)

**Comment by HarelM** [comment]
Do you have any pointer how to debug with Safari? This happens also on desktop safari...

**Comment by MatanBenMoshe** [comment]
I have never done it.
Sorry :(

**Comment by HarelM** [comment]
I'm sorry, but it seems there are too many issues involving Safari browser regarding up-to-date frameworks and javascript standards that Safari does not support.
Feel free to pull request changes that are relevant as Safari for Windows desktop is not longer maintained and I don't have a Mac to debug these issues...
Closing for lack of interest to the public, sorry.
