### ISSUE TITLE
The X button

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#405]
1) Using it does not delete the active track from the track list. It remains there but is empty.
2) I see no reason why is shouldn't be present when the track is active but not in edit mode.

**Comment by HarelM** [comment]
Route manipulation is done only in the layers controller, the X is used to clear points, not delete.
The idea behind it is that the simplest user does not need to know about the layers controller.
It makes sense too facilitate

**Comment by valleyofdawn** [comment]
What am I supposed to do?

**Comment by HarelM** [comment]
Either close the issue if you can relate to what I said or try and convince me I should change current behavior, either way there's not much for me to do besides wait for your comment, so I assigned it to you :-).
