### ISSUE TITLE
Subtle map "jumps" as the tiles load

### ISSUE THREAD

**Issue by SwiftFast** [IsraelHikingMap/Site#410]
Immediately after panning or zooming the map, the tiles will often jump down a couple of times. Each jump seems to be 1 pixel down. Typically it's a burst of multiple jumps spanning ~0.5 second or so after zooming or panning. The jumps seem to happen in sync with the loading of new tiles. 

The issue is very subtle and can be missed, but it's pretty hard to ignore once it's noticed once. It's a bit annoying. I am not sure if it was introduced in the Angular update, or if it's old and I'm noticing it now.

I'd guess that the tiles that load push the already loaded tiles and change their position slightly.

Tested on multiple browsers.

**Comment by SwiftFast** [comment]
Here is a video. It is zoomed in to make the effect clearer. Watch in full screen.

https://streamable.com/s/jk9xf/jtazmn

**Comment by HarelM** [comment]
Can you check if this behavior exists when the wiki and Nakeb layers are off?

**Comment by HarelM** [comment]
I can't reproduce on my mobile or my PC... :-/ 
I'm using chrome in both cases, can you check if this happens in all your browsers.
Which OS are you using?

**Comment by SwiftFast** [comment]
The left side of the coordinates in the URL also jumps in perfect syncs with the visual jumps.

>Can you check if this behavior exists when the wiki and Nakeb layers are off?

The behavior did not stop after turning off all layers.

>Which OS are you using?

Reproduced on:
Firefox 54, Windows 7 (64 bit) 1920 x 1080
Firefox 52 LTS, Debian (64 bit)  1366 x 768
Chromium 57, Debian (64 bit) 1920 x 1080

Failed to reproduce on:
Chrome 59, Windows 7 (64 bit) 1920 x 1080

**Comment by HarelM** [comment]
I'll try and reproduce it but in getting the feeling it's a bug in leaflet.
Can you check if you see it happen in a leaflet demo?
https://leaflet-extras.github.io/leaflet-providers/preview/

**Comment by SwiftFast** [comment]
It is not happening in the link you provided.

Note that clearing the cache *may* make reproducibility easier. Or maybe this was anecdotal.

**Comment by HarelM** [comment]
I see the problem on FireFox on my machine as well. I can't seem to be able to reproduce it on any leaflet example so it might be an issue with my code but I have no clue how to start debugging it... :-/
Thoughts are welcome...

**Comment by SwiftFast** [comment]
Just a longshot: Are there any `setInterval`s in the code or functions that repeat about once every 0.5 seconds or so? To my eye, it seems the interval between the jumps is constant. (This might be subjective or load time dependent)

**Comment by HarelM** [comment]
@SwiftFast, I managed to reproduce something similar with Chrome using only leaflet. 
linked above, let's see what they answer....

**Comment by SwiftFast** [comment]
Thanks!

**Comment by HarelM** [comment]
Since there's not much I can do until a new release will be publish I don't see a good reason to keep this issue open. Hopefully a new release will be available soon.
