### ISSUE TITLE
Update MTB legend

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#413]
**Additions:**
Stairs,
Low-speed streets
Dry riverbed
Residential road
Playground

**Corrections (should point elsewhere)**
Easy path (should be green)
Area B
International border
supermarket
Toilet
Construction site
Peak would be nicer with ele, cave without

**Corrections (should have different title)**
מרכז מבקרים -> מידע

**Categories**
Move all paths (foot and bike) to one category, and all tracks to another. סינגלים/דאבלים

**Comment by valleyofdawn** [comment]
Zstedller wrote:

This should be opened as a Site issue

In the new issue,

Please differentiate between new MTB legend entries that already exist in the IHM, like stairs, and completely new entries, such as low-speed streets.
For new entries, please define their group name, Hebrew title, English title, location (lat/lon), and zoom.
For location changes please define their new location (lat/lon), and zoom.
For title changes, please modify the Hebrew and/or English translation. (See https://github.com/IsraelHikingMap/Site/wiki/Adding-New-Text-and-Updating-the-Translations.)
For new categories please define their Hebrew title and English title.

**Comment by HarelM** [comment]
Seems like either you didn't understand what Zeev wrote or completely ignored it.
>For new entries, please define their group name, Hebrew title, English title, location (lat/lon), and zoom.
>For location changes please define their new location (lat/lon), and zoom.

I can't add it to the legend without the above information and I don't have this information so please provide it.

**Comment by valleyofdawn** [comment]
I just moved it from /map to /site. I understand what I have to do when I have the time for it.

**Comment by valleyofdawn** [comment]
[MTB legend.docx](https://github.com/IsraelHikingMap/Site/files/1203106/MTB.legend.docx)

A table with the requested data

**Comment by HarelM** [comment]
Thanks! If something doesn't add up I'll let you know.

**Comment by valleyofdawn** [comment]
Please first check if the location is accurate enough on one or two features.

**Comment by HarelM** [comment]
Is all the information in the docx file or some of it is here because I got lost...

**Comment by HarelM** [comment]
@valleyofdawn please review my commit (mainly `info-sidebar.component.ts` file).

**Comment by valleyofdawn** [comment]
It looks good to me. My main concern is with the locations, which I can't review. Let me know when it's merged or run it on the test site please.

**Comment by HarelM** [comment]
@valleyofdawn Please check it on the beta site and close it if all requests are met.

**Comment by HarelM** [comment]
@valleyofdawn I'm hoping this is fixed.
In case it isn't please reopen.

**Comment by valleyofdawn** [comment]
One last edit:

Synagogue/בית כנסת
 zoom 16  31.7766/35.2343

**Comment by HarelM** [comment]
Reopen for Synagogue.
