### ISSUE TITLE
Min-zoom of custom map is ignored

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#414]
[OSM Mapnik as a custom map](https://israelhiking.osm.org.il/#!/?s=DAzxEv147c) is defined with min-zoom == 0. Nevertheless, there is no zoom-out beyond zoom level 7.

This does not happen if min-zoom is more than 0...

Tested on Firefox and Chrome running on Win-10.

**Comment by HarelM** [comment]
This is probably a leaflet bug.
What would you like the solution to be? do not allow the user to set min zoom to 0?

**Comment by zstadler** [comment]
Choosing zoom level 7 as the fallback minZoom is not likely a choice made in Leaflet.

I think the problem is in [this line](https://github.com/IsraelHikingMap/Site/blob/2160fae531ad70a152e8c8d011a38dcecfcfba95/IsraelHiking.Web/sources/application/services/layers/layers.service.ts#L334):
```Javascript
minZoom: layerData.minZoom || LayersService.MIN_ZOOM,
```
rather that checking if layerData.minZoom is undefined.

**Comment by HarelM** [comment]
You're probably right, didn't notice it chooses zoom 7 by default.
In any case, feel free to fix it :-)

**Comment by HarelM** [comment]
Worth mentioning the difference between `==` and `===` and `== null` vs `=== undefined`...
I prefer `== null` to avoid the unnecessary difference between `null` and `undefined`.

**Comment by zstadler** [comment]
There is no difference between `== null` and `== undefined` since `null == undefined`.
I respect your preference for `null`, which also saves a few keystrokes.
