### ISSUE TITLE
Add WikiVoyage overlay

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#416]
Similar to Wikipadia overlay.

See [the discussion in the Wikivoyage:Travellers' pub](https://en.wikivoyage.org/wiki/Wikivoyage:Travellers%27_pub#Technical_question) about ways to access geo-locations.

Notes:
- WikiVoyage page may include several categories of places with geo-locations. We should probably use the "see" and "do" categories.
- The links to the WikiVoyage pages can only use the anchors for the categories, as individual places do not have anchors.

**Comment by HarelM** [comment]
I'm not sure I understand how all of this works.
Do you have an API call example I can start with?
Also the conversation platform there is horrifying, I'll let you do all the talking as I'm having a really hard time understanding who is replaying to who in which comment...
Is there an API for English and Hebrew like Wikipedia so I can show relevant POIs according to the selected language of the site?
Do you think it deserves a layer of its own? I tend to think it should be a part of the Wikipedia layer

**Comment by zstadler** [comment]
You probably didn't notice that I've assigned myself to this task...

It looks like WikiVoyage has many more POIs than Wikipadia. It is also a different source with a different approach. IMO merging the two will be worse than not having WikiVoyage.

**Comment by HarelM** [comment]
I haven't notice the assignment, sorry.
Why do think merging the two is that bad?
I don't want to add too many layers to the layers sidebar in order not to confuse the user, the less the better. Maybe we can use the filters mechanism I'm building for the POI layer for Wikipedia content as well...?

**Comment by zstadler** [comment]
For the basic user the UI has 3 overlays. 99% of the time, the layers sidebar is closed. Adding WikiVoyage is not confusing.

<img width="264" alt="with WikiVoyage" src="https://user-images.githubusercontent.com/1304610/29304658-dc90719c-819c-11e7-8899-1d0613bb238b.png">  vs.  <img width="264" alt="without WikiVoyage" src="https://user-images.githubusercontent.com/1304610/29304668-ec57aab4-819c-11e7-8088-fc9068828740.png">


Mixing separate sites, just because their names share a prefix, would create a greater confusion.
It is as reasonable as merging Wikipedia and Nakeb. 

If the filtering mechanism will include filtering by source, then it could be used instead of separate layers. It will continue to present the user with the option to choose a subset of the sources. The change will just make that choice less accessible.

In any case, an "adapter" for retrieving the data from each source is needed.

**Comment by HarelM** [comment]
Issue #442 will make the trails the only default layer for overlay, wiki layer will be under POI as a separate category since I don't think I have a way to filter wiki values by categories.
How do you see the implementation of this feature fit in this concept?
