### ISSUE TITLE
Map scale interferes with managing the last track

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#417]
![image](https://user-images.githubusercontent.com/1304610/29498007-104f97d4-85fc-11e7-8b28-4b9b638a8b55.png)

It is hard to hit the top of the wrench icon in order to mange the last private track.

**Comment by HarelM** [comment]
I'm aware of this issue.
It's already fixed but not yet published.
I moved the scale to the other side, also fits with the rest of the info.
![image](https://user-images.githubusercontent.com/3269297/29498021-597ff070-85fc-11e7-980b-b2dcbca2dfaa.png)
