### ISSUE TITLE
Simplify language switch

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#419]
Now requires 3 clicks and looking at an ugly dialog box.
Can be one click on English/Hebrew flags of A/א icons.

**Comment by HarelM** [comment]
One click too minimalistic - if a user accidently clicks this button his entire interface changes.
I don't think we should avoid the dialog, as ugly as it is.
Maybe this issue should be to improve the dialog appearance.

**Comment by valleyofdawn** [comment]
The interface changes, but that's totally reversible. You don't need to read English to identify the Israeli flag (and I suspect > 95% of our users read some English)

**Comment by HarelM** [comment]
I prefer the need for an extra click to make sure the user knows what he is doing.
As I said in our meeting, reducing the number of clicks is not what defines a good or bad UX (although it's always a "hot" argument)...
I believe 95% of the users do not want to change the user interface by mistake (or at all most of the time) - hence the extra click...

**Comment by valleyofdawn** [comment]
In all the multilingual interfaces I can recall it is one click. Sometimes it's hidden under settings and you can also change metric/imperial units etc.  In any case it's not a big deal either way.  Your opinion Zeev?

**Comment by zstadler** [comment]
I like the idea of one click without opening a dialog

**Comment by HarelM** [comment]
I like the confirmation better.
About 1% of the users change the language and I'm sure I'm one of them when debugging.
I don't see a good reason to change the behavior.
