### ISSUE TITLE
Gates & Barriers

### ISSUE THREAD

**Issue by YGMZ** [IsraelHikingMap/Site#420]
Presently thereare 2 types of gates (closed / open).
3 types of gates required:
1 - open for motor vehicle (practically open for all...) 
     defined by: acsess all = yes or acsess motor vehicle = yes
2 - open for biking or foot
     on IHM defined by: acsess foot = yes and acsess motor vehicle = no
     on IMTBM defined by: acsess bicycle = yes and acsess motor vehicle = no
3 - closed

Presently 1 type of barrier.
2 types required:
1 - open for biking or foot
     on IHM defined by: acsess foot = yes and acsess motor vehicle = no
     on IMTBM defined by: acsess bicycle = yes and acsess motor vehicle = no
2 - closed
Note: open for all not required because in this case it is not prectically a barrier...

**Comment by HarelM** [comment]
Thanks for reporting this issue, but as far as I understand it is related to the map.
Can you please open it in the map repository?
https://github.com/IsraelHikingMap/Map/issues
