### ISSUE TITLE
Sharing a map with POI loses the POI designation/icon

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#423]
Always appears as a star.

**Comment by HarelM** [comment]
Interesting, I'll take a look at it later this week.

**Comment by HarelM** [comment]
Can you please specify how to reproduce? See this share - it has a fire on it:
http://israelhiking.osm.org.il/#!/?s=fkREJLVnVN

**Comment by valleyofdawn** [comment]
I see a fire and I can't reproduce. I think the problem may be that I switched the icon and it reverted back to the default star because I didn't hit the V icon. Maybe that behavior should change and just closing the window after choosing a new icon would suffice to change it.

**Comment by HarelM** [comment]
This will remove the ability to undo latest changes.
I think the current behavior, along issue #468 should be sufficient.
Closing...
