### ISSUE TITLE
Linking back from an iFrame to the site

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#424]
I suggest making the link more prominent. Right now it just the second among 6 different links,
This is important as sites like Groopy incorporate the map and we want to generate traffic back to the site.
Do we still need the Norwegian attribution for the MTB map? The map has changes a lot since we used it, maybe we can acknowledge this somewhere less prominent after consulting the Norwegian guy?

**Comment by HarelM** [comment]
I think embedded offroad has a clear way to show what is the source of the embedded map, not sure we want to go that far though...

**Comment by valleyofdawn** [comment]
Yes. That is too much. I'd go with something intermediate. But a logo is a good idea.

**Comment by HarelM** [comment]
Here's my suggestion - Icon + small text - bottom left corner
This might be two subtle, not sure...
![image](https://user-images.githubusercontent.com/3269297/31392101-0d7e43e0-ade1-11e7-9686-30d2f3fd72ad.png)

**Comment by HarelM** [comment]
@valleyofdawn @zstadler if you have a better suggestion let me know - or if you think this one is bad also let me know.
Note that this will appear also in the regular site and not just in the embedded ones.

**Comment by zstadler** [comment]
- Will this icon show also when the layers pane is closed?
- I suggest using "Israel Hiking" as the text rather than "IHM".

**Comment by valleyofdawn** [comment]
Is it only going to be on Iframes or always there?

**Comment by valleyofdawn** [comment]
Oh I see. To be frank, it's not very appealing, the way it partially covers the text, but most users won't have all these layers. I'd go with that and improve it once we employ a designer.

**Comment by HarelM** [comment]
I tried Israel Hiking, It turned out to be too long to fit on the icon.
I'll start with that and hopefully improve in the future (but probably it won't:-))...

**Comment by zstadler** [comment]
I see nothing wrong with text below the icon:
![embedded](https://user-images.githubusercontent.com/1304610/31401891-f209c028-adfc-11e7-89b4-6dfb1e61be1f.jpg)
(Text color needs improvement)

Other embedded maps take much more "screen space" for their self-promotion.
For example:

<img src="https://user-images.githubusercontent.com/1304610/31401982-38244998-adfd-11e7-84b6-af8dde0e6f1b.png" width="50%">

**Comment by HarelM** [comment]
Thanks for the tip!
Decided to go with blue (Israel etc...) feel free to change it:
<img src="https://user-images.githubusercontent.com/3269297/31406320-a2f038d4-ae09-11e7-8657-83a77b96dc01.png" height="300px" />

**Comment by zstadler** [comment]
I suggest to create some space between the icon and the bottom of the screen in order to address some overlaps:

- The attribution is covered in mobile view:

![image](https://user-images.githubusercontent.com/1304610/31736578-d68654fe-b44d-11e7-945f-00bb8ca6c8b8.png)

- The blue "Israel Hiking" text is covered on mouse hover any link, and this icon in particular:

![image](https://user-images.githubusercontent.com/1304610/31736653-07deca2c-b44e-11e7-9ae1-4f6ec6e96e9a.png)

**Comment by HarelM** [comment]
Relvant css nad html:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.Web/sources/application/components/ihm-link.component.css
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.Web/sources/application/components/ihm-link.component.html
