### ISSUE TITLE
Tile edges visible

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#425]
A fine 1 px line is visible at the seams of the tiles in chrome on windows, regardless of source.

**Comment by HarelM** [comment]
can you provide a screen shot?
probably a bug in leaflet, not sure there's anything I can do about it, please see if you can reproduce it on their sample maps:
http://leafletjs.com/examples/quick-start/

**Comment by valleyofdawn** [comment]
![image](https://user-images.githubusercontent.com/689201/30003435-854e41a6-90c5-11e7-8b24-81b8a0f5970d.png)

**Comment by valleyofdawn** [comment]
Their sample maps look fine.

**Comment by HarelM** [comment]
Can you share a link? I don't see it on my chrome + windows machine.
Are you sure this doesn't have to do with some browser settings?
When did it start?

**Comment by valleyofdawn** [comment]
It's subtle, but you wouldn't have missed it. It's everywhere.
It began a few weeks back.
I guess it's just me? I'll check PCs.

**Comment by HarelM** [comment]
Can't reproduce.
