### ISSUE TITLE
Short url is not opening correctly.

### ISSUE THREAD

**Issue by ATGardner** [IsraelHikingMap/Site#427]
While trying to open a specific short url (https://israelhiking.osm.org.il/#!/?s=2QKnKT5g1N), my browser opens the map on the last location of the map (or around 13/31.7730/35.1200 if my browser has no last location).
I am currently running Windows 10 Version 10.0.16257.1 (fast track build), and I reproduced the problem in 

* Chrome Canary Version 63.0.3204.0 (Official Build) canary (64-bit)
* Chrome Dev Version 62.0.3198.0 (Official Build) dev (64-bit)
* Microsoft Edge 41.16257.1.0

**Comment by HarelM** [comment]
Can you elaborate on what is the expected behavior and what is the actual behavior.
The map will automatically open in the last location it was left, but then it checks if there's a url it will move to it.
I'm able to see the pin of Weizmann Institute in the link above.

**Comment by sannius** [comment]
I use Firefox Nightly on Win8.1 - the map opened at the last location, not centered to the pin coordinates. Pin is visible if manually dragging the map to point to Rehovot.

**Comment by HarelM** [comment]
Doesn't reproduce on Windows 7 + chrome for me
Does reproduce for me on Windows 7 + firefox.
I'll take a look at it in a few days, I'm currently preparing version 5.0 for the OSM meetup.

**Comment by HarelM** [comment]
Can you check if the following does a better job?
http://israelhiking.osm.org.il/#!/?s=2QKnKT5g1N
It's the same address only in http and not https...

**Comment by ATGardner** [comment]
Sorry for not putting the "expected" behavior in the issue report. It was expected to be centered around the pin in Weizmann Institute.
About the 2nd address - it opened at the default center location (13/31.7730/35.1200). I then moved the map a bit (and zoomed in), and am now always showing my zoomed up location with the 2nd address, and a different location with the 1st address. It seems as though the "last location" depends on which link I used to navigate to the site.

**Comment by sannius** [comment]
This is from Firefox Browser Console:

Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. v@http://israelhiking.osm.org.il/vendor.a1f1bd8032a4e805f134.bundle.js:1:1123455
cqO5/</_.extend@http://israelhiking.osm.org.il/vendor.a1f1bd8032a4e805f134.bundle.js:1:1136446
uhSc@http://israelhiking.osm.org.il/vendor.a1f1bd8032a4e805f134.bundle.js:1:1530092
r@http://israelhiking.osm.org.il/inline.3c1dc6112a482d6948fc.bundle.js:1:96
Vxuo@http://israelhiking.osm.org.il/main.fb9229f25f2434e7bc29.bundle.js:1:417428
r@http://israelhiking.osm.org.il/inline.3c1dc6112a482d6948fc.bundle.js:1:96
ujNZ@http://israelhiking.osm.org.il/main.fb9229f25f2434e7bc29.bundle.js:1:771049
r@http://israelhiking.osm.org.il/inline.3c1dc6112a482d6948fc.bundle.js:1:96
26pj@http://israelhiking.osm.org.il/main.fb9229f25f2434e7bc29.bundle.js:1:47758
r@http://israelhiking.osm.org.il/inline.3c1dc6112a482d6948fc.bundle.js:1:96
/8cv@http://israelhiking.osm.org.il/main.fb9229f25f2434e7bc29.bundle.js:1:326
r@http://israelhiking.osm.org.il/inline.3c1dc6112a482d6948fc.bundle.js:1:96
ko8m@http://israelhiking.osm.org.il/main.fb9229f25f2434e7bc29.bundle.js:1:569439
r@http://israelhiking.osm.org.il/inline.3c1dc6112a482d6948fc.bundle.js:1:96
[1]@http://israelhiking.osm.org.il/main.fb9229f25f2434e7bc29.bundle.js:1:36687
r@http://israelhiking.osm.org.il/inline.3c1dc6112a482d6948fc.bundle.js:1:96
window.webpackJsonp@http://israelhiking.osm.org.il/inline.3c1dc6112a482d6948fc.bundle.js:1:418
@http://israelhiking.osm.org.il/main.fb9229f25f2434e7bc29.bundle.js:1:1
  vendor.a1f1bd8032a4e805f134.bundle.js:1:1123312
GET 
http://israelhiking.osm.org.il/null [HTTP/1.1 404 Not Found 20ms]
ERROR Error: Uncaught (in promise): TypeError: can't convert null to object
IbXO/o</t.prototype.getProxy/</i[t]@http://israelhiking.osm.org.il/vendor.a1f1bd8032a4e805f134.bundle.js:1:318034
e/this.toggleOverlay@http://israelhiking.osm.org.il/main.fb9229f25f2434e7bc29.bundle.js:1:420393
e/this.addExternalOverlays@http://israelhiking.osm.org.il/main.fb9229f25f2434e7bc29.bundle.js:1:422657
ujNZ/p</e.prototype.setData@http://israelhiking.osm.org.il/main.fb9229f25f2434e7bc29.bundle.js:1:772537
ujNZ/p</e.prototype.setInitialData@http://israelhiking.osm.org.il/main.fb9229f25f2434e7bc29.bundle.js:1:773068
e/this.addDataFromHash/<@http://israelhiking.osm.org.il/main.fb9229f25f2434e7bc29.bundle.js:1:771794
eFQL/</</</l</e.prototype.invoke@http://israelhiking.osm.org.il/polyfills.e43a16ff55e32b58c2c4.bundle.js:1:40020
onInvoke@http://israelhiking.osm.org.il/vendor.a1f1bd8032a4e805f134.bundle.js:1:11741
eFQL/</</</l</e.prototype.invoke@http://israelhiking.osm.org.il/polyfills.e43a16ff55e32b58c2c4.bundle.js:1:39947
eFQL/</</</u</r.prototype.run@http://israelhiking.osm.org.il/polyfills.e43a16ff55e32b58c2c4.bundle.js:1:35172
l/<@http://israelhiking.osm.org.il/polyfills.e43a16ff55e32b58c2c4.bundle.js:1:44944
eFQL/</</</l</e.prototype.invokeTask@http://israelhiking.osm.org.il/polyfills.e43a16ff55e32b58c2c4.bundle.js:1:40695
onInvokeTask@http://israelhiking.osm.org.il/vendor.a1f1bd8032a4e805f134.bundle.js:1:11653
eFQL/</</</l</e.prototype.invokeTask@http://israelhiking.osm.org.il/polyfills.e43a16ff55e32b58c2c4.bundle.js:1:40608
eFQL/</</</u</r.prototype.runTask@http://israelhiking.osm.org.il/polyfills.e43a16ff55e32b58c2c4.bundle.js:1:35863
o@http://israelhiking.osm.org.il/polyfills.e43a16ff55e32b58c2c4.bundle.js:1:32935
eFQL/</</</f</t.invokeTask@http://israelhiking.osm.org.il/polyfills.e43a16ff55e32b58c2c4.bundle.js:1:41869
h@http://israelhiking.osm.org.il/polyfills.e43a16ff55e32b58c2c4.bundle.js:1:21531
d@http://israelhiking.osm.org.il/polyfills.e43a16ff55e32b58c2c4.bundle.js:1:21807

Stack trace:
u@http://israelhiking.osm.org.il/polyfills.e43a16ff55e32b58c2c4.bundle.js:1:44405
l/<@http://israelhiking.osm.org.il/polyfills.e43a16ff55e32b58c2c4.bundle.js:1:44977
eFQL/</</</l</e.prototype.invokeTask@http://israelhiking.osm.org.il/polyfills.e43a16ff55e32b58c2c4.bundle.js:1:40695
onInvokeTask@http://israelhiking.osm.org.il/vendor.a1f1bd8032a4e805f134.bundle.js:1:11653
eFQL/</</</l</e.prototype.invokeTask@http://israelhiking.osm.org.il/polyfills.e43a16ff55e32b58c2c4.bundle.js:1:40608
eFQL/</</</u</r.prototype.runTask@http://israelhiking.osm.org.il/polyfills.e43a16ff55e32b58c2c4.bundle.js:1:35863
o@http://israelhiking.osm.org.il/polyfills.e43a16ff55e32b58c2c4.bundle.js:1:32935
eFQL/</</</f</t.invokeTask@http://israelhiking.osm.org.il/polyfills.e43a16ff55e32b58c2c4.bundle.js:1:41869
h@http://israelhiking.osm.org.il/polyfills.e43a16ff55e32b58c2c4.bundle.js:1:21531
d@http://israelhiking.osm.org.il/polyfills.e43a16ff55e32b58c2c4.bundle.js:1:21807
  vendor.a1f1bd8032a4e805f134.bundle.js:1:6969
"Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys"  util.js:222:12

**Comment by HarelM** [comment]
Apparently the problem is with the stored state of the overlay layers, I have no idea why specifically this but it appears that this is what is causing the issue.
A workaround for this issue temporary is to remove any custom overlay and create another share.
I'll try to contact the developer of the local storage layer (which I'm using and causing this issue) and see if he has anything smart to say about this issue.
Thanks for reporting the bug!

**Comment by HarelM** [comment]
Waiting for maintainer to respond:
https://github.com/zoomsphere/ngx-store/issues/19

**Comment by HarelM** [comment]
Will be published next week.
