### ISSUE TITLE
Site not loading on IE

### ISSUE THREAD

**Issue by ATGardner** [IsraelHikingMap/Site#428]
Trying to navigate to https://israelhiking.osm.org.il/ results in an IE error message
```
Line: 1
Error: Object doesn't support property or method 'assign'
```

I am running Internet Explorer 11.1.16257.0, Update Version 11.0.41 on Windows 10 Version 10.0.16257.1 (Fast Track) 64-bit.

**Comment by HarelM** [comment]
Yes, unfortunately IE is no longer being maintained by Microsoft.
Please see if this doesn't work on edge browser.
Also, I don't want to include a bunch of `polyfills` that will make the site load faster for this badly written browser...

**Comment by ATGardner** [comment]
If it's not supported, it's not supported.
Though you can use babel transpiling to support the latest browsers (including IE). But maybe their market share with your audience does not make sense putting such effort into it.

**Comment by HarelM** [comment]
Sorry, not planning on supporting it in the near future.
