### ISSUE TITLE
Enlarge POI images upon clicking them

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#431]
Very important to assess if the POI is worth a visit and greatly enhances the user immersive experience.
I can't understate how important that is to me.

**Comment by valleyofdawn** [comment]
עיון עוזי.
http://fdc2a36a.ngrok.io/#!/20/31.7582/35.1381

**Comment by valleyofdawn** [comment]
That's much better. 
Improvements:
Add a magnifying glass of plus icon to indicate the thumbnail can be expanded.
Make the big photo a full screen one.
Use the same style for the small and large window (either round or square corners. x icon on same side and place)

**Comment by HarelM** [comment]
Photos are almost full screen, this is the best I could do.
Added magnifying glass.
Dialog style is out of this issue's scope.
