### ISSUE TITLE
Allow weighted voting for POIs

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#433]
Based on how many edits a person contributed to OSM allow their vote to carry more weight

**Comment by HarelM** [comment]
I have created the voting system to facilitate for it but I wasn't sure what formula to use.
Currently a vote can be either +1 or -1.
A user can't change his mind right now, probably needs fixing too.
In nay case, please define the voting weight scale - or a formula to calculate the weight.

The OSM ranking I used for the UI is based on magnitude - 1-10, 10-100, 100-1000 and above 1000.

**Comment by zstadler** [comment]
I suggest we put this issue on hold for now as we can say much about the voting system until we see it in action.

I think most social sites, from facebook to stackoverflow, allow a person to change their vote.

**Comment by valleyofdawn** [comment]
I would go with int(1+log10(rank))

**Comment by HarelM** [comment]
Voting is very limited right now and doesn't seem to be significant. In any case, let's keep it simple...
