### ISSUE TITLE
Historical site - lose monument

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#434]
Monument and memorial are overlapping. In the MTB maps they are rendered the same. 
How about a historical holy place instead (for synagogue/mosque/Sheikh-tomb).

**Comment by HarelM** [comment]
Too specific in my point of view.
Also this should be defined in the map rules, not here, this is just a rejection of the definitions there...

**Comment by valleyofdawn** [comment]
I think that the distinction between memorial and monument is a waste of energy and we should include just a memorial. A monument, based on OSM wiki, is a big complex site e.g. Yad VaShem, and I'm pretty sure they are all mapped. In Israel small memorials are often tagged an monuments, and we should not encourage that habit. 

There are hundreds of holy tombs in Israel, many un-mapped, and we need a convenient way to add them.

**Comment by HarelM** [comment]
Not for this release. I agree monument and memorial are too confusing, I prefer to just remove one of them without adding anything else.

**Comment by zstadler** [comment]
I agree. Monuments are extremely few.
Also agree with @HarelM that holy sites & graves are not a priority.

**Comment by zstadler** [comment]
I support removing of monuments from the list of poi types. Nevertheless, I suggest we do not add any new poi types for now.
