### ISSUE TITLE
Finding a direct way to add a new public POI

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#435]
Requires converting a private one.
This is not self-explanatory. Maybe there can be a direct way?

**Comment by HarelM** [comment]
I don't have a good idea, as much as I thought about it, creating a POI and converting it to OSM point is the simplest way I found using things the user already know how to do with the site.
Feel free to suggest anything else...

**Comment by valleyofdawn** [comment]
Right clicking.
See #437

**Comment by HarelM** [comment]
See my comments there.
Using right click only saves 1 click and 2 mouse drags and the use case is not recommended as you are inventing a point without backing data.
Closing, sorry.
