### ISSUE TITLE
Simplify the Public POI dialog

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#436]
There is redudncy between the pencil tool and "הקלידו על מנת לערוך".
Leave only the pencil, but enlarge it. 
The camera image is unnecessary.
the text can be:
!לחצו כדי להוסיף תיאור או תמונה
instead of 
כדאי שתוסיפו תיאור כאן! לחצו על כפתור העריכה למטה

**Comment by valleyofdawn** [comment]
כדי לערוך צריך להתחבר לחשבון ה-OSM.
לחצו על הכפתור בפינה הימנית העליונה.

**Comment by valleyofdawn** [comment]
It would be much nicer if the expended dialog would not open an extra window on top of the basic one, but instead enlarged the existing window. Like we do for the private POI.
העלו נקודה
Is anyway not the right title for a dialog that edits an existing POI.

**Comment by HarelM** [comment]
I agree that it can improve, but this dialog, when there's no data in it, should shout "EDIT ME" - this was my main goal - almost every text there should encourage you to edit it, I don't think redundancy is an issue here.
I agree "add point" and "update point" should have different text, I was lazy :-)

>כדי לערוך צריך להתחבר לחשבון ה-OSM.
לחצו על הכפתור בפינה הימנית העליונה.

Not sure what to do with this sentence you wrote...

Can you please prepare a screen shot of how you would like it to look so we can discuss the differences?
Power Point can do wonders :-)

**Comment by HarelM** [comment]
Please open an account in zanata so I can grant you edit permission for the translations.

**Comment by HarelM** [comment]
@valleyofdawn waiting for your replay...

**Comment by HarelM** [comment]
You can use the IHM account to translate on zanata.org.

**Comment by HarelM** [comment]
Not sure there's much to do here.
The dialog work for me. and is also consistent with private POI editing when turning them to public.
If you would like to change the translation feel free to do so.
If you want to reopen this please supply screen shot of all the relevant scenarios:
1. Private poi => public POI.
2. Public poi => edit => advance editing.
