### ISSUE TITLE
Upload website link to OSM functional?

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#443]
Upon adding a link, and closing the "edit more" dialog box, there is no clear indication that the info was uploaded.
Upon reopening the dialog box the text is gone.

**Comment by HarelM** [comment]
You should be getting a text box that the operation was successful.
The beta site hit a breakpoint on my PC and the operation was not completed, I think.
Please try again.

**Comment by HarelM** [comment]
Please reopen if the bug can be reproduced.
