### ISSUE TITLE
Standardize windows design in the site

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#444]
Trying to standardize window design would give the site a more professional feel and minimize un-necessary movement when activating different element.
The layers, info and legend windows have different width.
The layers window has an X to close it, but the info and legend do not. (they can be closed with the i button)
The X on the layers window is bold and bigger than on the height profile.
The height profile is semi-transparent grey, whereas the side windows are light grey, and the POI and WPS and the future public POI windows are white.
The X is not always located on the extreme top right, as expected.
The resizing handles are unique, have not seen them in other windows, and the users may not immediately recognize them as such.
The POI windows have rounded edges, and other windows don't.
Of all these, I like the POI windows most. Simple and clean.

**Comment by HarelM** [comment]
Feel free ro find someone that knows his way around css and have time for this, this is way down my priorities, I don't see myself getting to it in the next year...

**Comment by valleyofdawn** [comment]
I think I'll learn CSS, then.

**Comment by HarelM** [comment]
Also the design of all dialogs are the same and all marker popups are the same, they are just different between themselves due to different frameworks - leaflet and angular material.

Good luck with CSS.
Also I think both you and I are not designers, only learning CSS will not be enough, IMHO...

**Comment by HarelM** [comment]
Again, a designer can improve most of the site, I don't see a good reason to keep this issue open and wait for someone to help...
