### ISSUE TITLE
Improve design of track definitions dialog box

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#445]
The suggested design uses the same features and feel of other interface elements (on the right), and is cleaner. Currently we don't have width and transparency, did we lose them on purpose?
![ttrack settings](https://user-images.githubusercontent.com/689201/30232655-e2070044-94f9-11e7-9f56-d256db71acd1.jpg)

**Comment by HarelM** [comment]
Opacity and weight are part of the advanced setting and is visible only when using advanced mode.
![image](https://user-images.githubusercontent.com/3269297/30232820-af643f3e-94fa-11e7-84fc-1309f72c31de.png)

**Comment by HarelM** [comment]
New dialog:
![image](https://user-images.githubusercontent.com/3269297/30241136-280c8a0a-9586-11e7-8b0b-db43473bb001.png)

**Comment by HarelM** [comment]
Too much work for too little benefit... :-/
Although I do like the new look :-)

**Comment by valleyofdawn** [comment]
Very nice!
Is this a mock-up or a snapshot?
The golden frame around the selected color is partly obscured. you may need to space the colors blocks out.
Maybe we should replace the orange color block, since the highlight won't show. I'd go with white, or light grey which works well with dark sat images.

**Comment by HarelM** [comment]
Nope, snapshot, exists on the beta site now.
orange frame is the same throughout the site for selected stuff - it has the obstruction issue all over, not planing on changing this as part of this issue.

**Comment by valleyofdawn** [comment]
I don't see it get obstructed in other places.
![image](https://user-images.githubusercontent.com/689201/30242492-1b4f74ca-95a0-11e7-8c62-57937ff88366.png)
In any case, it's a small detail.
