### ISSUE TITLE
Open terms of service dialog upon initial login

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#448]
When user logs in for the first time - a dialog should be presented in order for him to agree to the terms of service.
Something like the following:
![image](https://user-images.githubusercontent.com/3269297/30251326-13d62b50-9666-11e7-8750-053b4bc999d3.png)

@valleyofdawn will you be able to write something up?

**Comment by valleyofdawn** [comment]
Yes I would
