### ISSUE TITLE
Height graph: Resizeable

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#45]
1) Spread the height profile horizontally to the maximum possible. Once the route is long details are lost.
2) Place it a bottom of page, where it is least likely to block the view.
3) Better yet, use a draggable and stretchable box.
4) Use much higher transparency, for the same reason

**Comment by valleyofdawn** [comment]
Also. No need for meter fractions in hight. Instead of (33.6,897.25) use 33.6km 897m.
The circles on the top of the hight graph are distracting. Show only the active one.

**Comment by HarelM** [comment]
I'll see what I can do about the resizable/draggable dialog since it is not part of the angularstrap framework.
You should also remember that this site should be compatible with mobile devices and so I don't want the sizes to be hardcoded, instead they should be responsive to device's size.

**Comment by valleyofdawn** [comment]
I see your point. 
In that case, bottom of page, full width and transparent would do.

**Comment by HarelM** [comment]
You'll probably say that the windows should remember its last location and size.
Reopen if you think it's really needed.
