### ISSUE TITLE
Search to show POI data

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#450]
When the search hits a POI, the results do not show the POI information. It takes some inside understanding and a few clicks to see the info.

For example, after searching for "עין מחוללים" the user sees

![image](https://user-images.githubusercontent.com/1304610/30365669-224d1704-9871-11e7-973a-0416b43830e0.png)

rather than seeing the detailed info we carry for this place:

![image](https://user-images.githubusercontent.com/1304610/30365705-3a815538-9871-11e7-9e44-2c795b31f868.png)

IMO, it makes also sense to add the "+" and coordinates buttons to the POI dialog, regardless of how the user opened it.

**Comment by zstadler** [comment]
By the way, in order to see the POI info, the user needs to:

- Press the "trash can" button, which may feel dangerous. (Pressing the "x" will not be useful)
- Ensure that the POI layer is visible
- Click the POI icon

**Comment by HarelM** [comment]
I have it in my to-do list. This is an annoying issue I need to solve, there is a problem in case the point is filtered out, I need to brain storm on it...
