### ISSUE TITLE
Change '+' hovering text for search result of a point

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#451]
Currently it reads "turn into a track", which makes no sense for a point:

![image](https://user-images.githubusercontent.com/1304610/30365923-06045e12-9872-11e7-94ac-59f3757785a2.png)

**Comment by HarelM** [comment]
Please specify actual results and expected results, I don't know what would make more sense to you, this makes sense to me as this will only add the point to the currently edited route.

**Comment by zstadler** [comment]
I'd expect to see "Add a point" for a point and "Add a track" for a track.

**Comment by HarelM** [comment]
Will be dealt as part of #450
