### ISSUE TITLE
The legend is inaccessible

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#452]
![image](https://user-images.githubusercontent.com/1304610/30369185-41c5d688-987c-11e7-97db-5ad463796ac2.png)

**Comment by HarelM** [comment]
Just surfed from the mobile and it seems available, can you check from another device?
Is this a ui issue or pressing the button doesn't do anything?

**Comment by zstadler** [comment]
It's probably a browser issue, which I didn't figure out and cannot reproduce after I did several refreshes and re-logins.
