### ISSUE TITLE
New OSM POI interface snags, bugs and suggestions

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#453]
1.	Opening the layers window I expected to see the headers: Base maps, POIs & Overlays  or מפות בסיס  נקודות עניין, שכבות, instead these categories were separated by lines only
2.	I expected ESRI Ito be called ESRI תצלום לווין
3.	I expected Wikipedia to be under POIs, not overlays
4.	I expected סיווג שבילי אופנים to be called שבילי אופניים
5.	I expected the public POIs to include also gates, drinking water, and peaks.
6.	When adding a new public POI, I expected the categories to be clearly listed. Instead I saw only water and it wasn't clear to me I can replace it with Historic etc.
7.	When I searched for a POI , the result came up only with its name and location. I expected it to show me also the image and description and allow me to edit it.

**Comment by zstadler** [comment]
1. I disagree. This is needed only by super-users like us who have tons of layers. I think it looks just fine for the basic user, and avoids the need for "click to expand"
  ![image](https://user-images.githubusercontent.com/1304610/30377095-41a9f786-9897-11e7-85e4-83a0f9324908.png)  

2. You can probably change any text through the translation site
3. I agree
4. Your translation data is outdated. Please refresh the site. 
5. These items are not full-fledged POIs. For example, a description or a picture is rarely useful or existent for a gate or drinking water. It also seems more likely to be useful for reporting on the scene, using an app we don't have.
6. It seems like one of the issues for the style improvement requested in #444
7. That's issue #450

**Comment by valleyofdawn** [comment]
a Link to the translation site again? I never used it.

**Comment by zstadler** [comment]
Have a look at the Site wiki, accessible above

![image](https://user-images.githubusercontent.com/1304610/30378161-eeebe276-989a-11e7-8f37-9cc798b54b10.png)

**Comment by valleyofdawn** [comment]
For 1. So maybe add it in advanced mode?

**Comment by zstadler** [comment]
1. I suggest you click on the scroll bar instead of adding a collapse button...

**Comment by HarelM** [comment]
1. I agree with Zeev, no need to add more headers there - it is has too many words already.
2. I'll add the word to the translation.
3. #442
4. not an issue.
5. I agree with Zeev, I don't see what need to be developed.
6, 7 have a separate issues.

Bottom line this feature is only for text, I'll close it since you can change the translation, note that I opened an account for IHM user in Zanata for the translations.
No need to keep it open.
