### ISSUE TITLE
Picture uploaded sideways

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#455]
Even though it appears straight on my desktop.
search גיא אבוד

**Comment by HarelM** [comment]
I think it should be solved by wikimedia, I just don't know how...
Desktop application may or may not auto rotate the image according its orientation properties saved inside the picture, I just pass the file straight to wikimedia, I rather not start manipulating it before uploading.

**Comment by HarelM** [comment]
Will be covered as part of #496.
Closing...
