### ISSUE TITLE
Advances OSM POI edit interferes with basic edit.

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#456]
I edited the description of a POI. Then when to advanced edit. Changed something, saved. 
went back to the local editing, and uploaded.
The last upload did not work.

**Comment by HarelM** [comment]
Please define "did not work":
Did you see a toast saying something went wrong?
Can you press F12 in cases when things don't work and check if you see errors in the browser's console text window?
here's an example of how it looks in chrome:
![image](https://user-images.githubusercontent.com/3269297/30385035-93ce6828-98ae-11e7-9394-69189c26a2d0.png)

**Comment by valleyofdawn** [comment]
No error message. It simply didn't update.
