### ISSUE TITLE
Bad representation in upload point page in iphone

### ISSUE THREAD

**Issue by MatanBenMoshe** [IsraelHikingMap/Site#458]
![unnamed](https://user-images.githubusercontent.com/17752588/30399752-6888a8a2-98dd-11e7-8a56-8c5e7c2fb8cf.jpg)

**Comment by HarelM** [comment]
It seems that safari on desktop is even worse, I don't know how to debug this as I don't have a mac and I don't have an iphone and I'm not sure how to get the relevant error message :-/
Do you have any experience debugging iPhone from a PC?

**Comment by MatanBenMoshe** [comment]
No. Sorry but I have never done it. :(

**Comment by HarelM** [comment]
Please try it now, I hope I managed to fix it.

**Comment by MatanBenMoshe** [comment]
It seems much better but the camera icon is still in the middle of the page.
BTW- do you have an open issue for the disappearance of the vote in iPhone?

**Comment by HarelM** [comment]
I've tested it on my iPad and it looked OK.
Please share another screenshot of the latest state.
Please open a separate issue for the missing vote controls.

**Comment by MatanBenMoshe** [comment]
![img_4150](https://user-images.githubusercontent.com/17752588/30490178-e2a2c356-9a41-11e7-8848-d375cdcd3b66.PNG)

**Comment by HarelM** [comment]
Please check now, I hope this time it's fixed. If so, please close the issue.
