### ISSUE TITLE
Update Server's POI DB after a client upload to OSM/Wikimedia

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#459]
_**What I've done:**_ I've successfully added a description to a POI and then re-opened the POI.
_**What happened:**_ The description was the same as before the update.
_**What I expected:**_ The updated POI description to be shown.

Technically, I suggest that after the client updates a POI, including picture uploads to Wikimedia, it will send a POI update notice to the server. 
The server will then fetch the updated data for the specific OSM element and update its POI DB. 
If needed, the server may send the updated data back to the client.

**Comment by HarelM** [comment]
This is what's coded. I saw it happen yesterday morning but I couldn't reproduce on my local environment.
I'll try to republish the code and see if it solves the issue...

**Comment by HarelM** [comment]
Can't reproduce by the above instructions, please reopen if this happens again with more details such as OS, browser and exact scenario to reproduce.

**Comment by HarelM** [comment]
Probably some sort of duplicate of #456
