### ISSUE TITLE
Disappearance of the vote for points in iPhone

### ISSUE THREAD

**Issue by MatanBenMoshe** [IsraelHikingMap/Site#461]
![img_4151](https://user-images.githubusercontent.com/17752588/30490263-1e18398e-9a42-11e7-9011-3712c6856cc2.PNG)

**Comment by HarelM** [comment]
Probably the same issue as #458 - seems like `column` layout has issues on iPhone, I'll try and open a bug for flexbox.

**Comment by HarelM** [comment]
As I said in #458, please verify the last update has fixed the issue. If so, please close it.
