### ISSUE TITLE
Save-as text NOT in the middle, missing search '+' button

### ISSUE THREAD

**Issue by nadavheimann** [IsraelHikingMap/Site#466]
Save as TextBox Text is not in the middle 

![image](https://user-images.githubusercontent.com/4962438/30519892-385d19d6-9baa-11e7-8de8-c038fac491aa.png)

**Comment by HarelM** [comment]
Also applies to issues in search - missing the '+' button, there's a pixel at the top that is not aligned.
![image](https://user-images.githubusercontent.com/3269297/30555534-74fc634a-9cb0-11e7-95ea-052f2344f347.png)

**Comment by nadavheimann** [comment]
Thanks, its look like ok now .
