### ISSUE TITLE
POI update should not modify relation classification

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#467]
For example, [relation 2165457](https://www.openstreetmap.org/relation/2165457) was changed in [changeset 52101165](https://www.openstreetmap.org/changeset/52101165)

**Comment by zstadler** [comment]
The changeset deleted `route=hiking` and replaced it with `natural=spring`

**Comment by HarelM** [comment]
I'll use this bug to fix the issues with routes, this is not the only issue...
You should be able to change the type of the route to hiking bike etc, but currently you can't...
Thanks for reporting!

**Comment by zstadler** [comment]
Changing the route type is an issue. 
I've already seen several OSM edits where the highway tag was changed from track to cycleway because it is used by bicycles. It will likely get worse if we allow it to be changed easily.

The enhancement is not urgent. IMO, fixing the bug is.

**Comment by zstadler** [comment]
Another non-critical issue:
[Changeset 52090464](http://osmhv.openstreetmap.de/changeset.jsp?id=52090464) was uploaded but changed nothing.

**Comment by HarelM** [comment]
I have removed the ability to open advance editing. I think it'll be OK for now, if we want to add something else we'll be able to do it later.
