### ISSUE TITLE
keyboard functionality on "new POI" window

### ISSUE THREAD

**Issue by arielki** [IsraelHikingMap/Site#468]
1. When opening a new POI window, cursor focus should be on the subject field.
2. "shift+enter" shall add a new row 
3. "enter" shall save the POI and close the dialog window.
![image](https://user-images.githubusercontent.com/32037355/30522088-25c8902e-9bd3-11e7-8c78-30f77ae91565.png)

**Comment by HarelM** [comment]
Will be available next site publish, hopefully within a few days.

**Comment by arielki** [comment]
Thxs!!

**Comment by HarelM** [comment]
Thank you for taking the time and suggesting features to implement.

**Comment by HarelM** [comment]
Published.

**Comment by arielki** [comment]
Cursor focus on the "subject" field whn opening the "new POI" window, was not implemented..

The rest works as requested.

Thank you!

**Comment by HarelM** [comment]
Sorry... You are right...
