### ISSUE TITLE
Automatic route planning based on different criteria

### ISSUE THREAD

**Issue by arielki** [IsraelHikingMap/Site#469]
Currently selection of "start" and "end" point , creates a single route between them.
The request is to present the user different routes based on specific requirements such as:  

- Minimum distance
- Minimum altitude
- Road/off-road
- When off-road, then roads "allowed", "not allowed", "minimize roads"
- Avoid ascents with slopes above x
- avoid descents with slopes above Y
- other

**Comment by HarelM** [comment]
We are using graphhopper as our routing engine.
These inputs are not supported as far as I know.
You can open a request there with the following requirements or implement something there.
I personally think this requirement is not relevant to about 95% of the users and has minimal value as opposed to a lot of time invested in implementation.
