### ISSUE TITLE
Add option to clear all tracks POI at once

### ISSUE THREAD

**Issue by arielki** [IsraelHikingMap/Site#470]

**Comment by HarelM** [comment]
Please elaborate.
Are you talking about personal POIs/Routes or public POIs/Routes?
Public POIs/Routes have an eye you can click on in the layers control on the left.

**Comment by arielki** [comment]
Personal POIs

**Comment by arielki** [comment]
Clearing all personal POIs (e.g using personal POIs as direction
instructions)

**Comment by HarelM** [comment]
You can clear the entire route data, I don't think there should be an extra button just for clearing private POIs...

**Comment by arielki** [comment]
Usually, after creating a route, need to share/distribute the gpx file with other riders.

Need to clear all private POIs in order to share the "clean" route only, not including private POIs.

Deleting POI by POI is quite "annoying"..

**Comment by HarelM** [comment]
Not sure why you would want to remove all the POI, why not share them?
In any case, I think this is too specific for your needs and I don't see this feature used by many users.
If you wish to implement it and send a pull request you are welcome, otherwise I'll close the issue.

**Comment by arielki** [comment]
I use personal POIs, mainly for setting directions (and hearing them during the ride, using waypoint alarms on Orux).

Not everybody want to get personal POI on files they receive, just the route itself.

It is not a critical request, but it would help.

As I see it can be implemented in 2 ways:

1.      Clearing all personal POIs (through the "Edit POI" button, through the "Clear route" button, or a dedicated button on the right side)

2.      Saving only the route or route + personal POIs after clicking on the "save" button.

**Comment by HarelM** [comment]
As I said, you are free to send a pull request.
Saving only the route can only be done in "save as" option, which I don't think is a good place to look for it.
Another option is when clicking the clear button - open a button bar with 3 buttons - clear all, clear route, clear POI but all of them need an icon which should be intuitive, this is not so easy.
The last option I can think of is to allow removing all points on the POI popup menu of a single private POI, this is also not so intuitive.
In any case, as I said, I don't think this is relevant to most users.

**Comment by HarelM** [comment]
Also in this specific case you can download the GPX file, remove all wpt tags which are written at the top of the file, open the file and share it. It is annoying, but again I don't see a use case that is relevant for most users...
