### ISSUE TITLE
Links to external tracks load only after map is panned

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#471]
**_I have_**: clicked on the link https://israelhiking.osm.org.il/#!/?url=http://www.jeepolog.com/UserFiles/TWL/dolev-zanoach.twl
**_I expected_**: the site to show the track on the map
**_What happened_**: the site loaded, but the track did not show

**_Then I_**: panned the map with the mouse
**_What happened_**: the track loaded sucessfully

**Comment by HarelM** [comment]
Are you sure this is not just a delay in the loading of the track?
I tried to reproduce locally and I can see the track without panning...

**Comment by zstadler** [comment]
Yes, you are right.
The problem is that the progress bar completes are disappears twice throughout the process. Sometimes, the disappearance takes a long time. 

Should I change the issue's title?

**Comment by HarelM** [comment]
not sure there's much I can do here, I'm leaning towards closing this issue...

**Comment by HarelM** [comment]
Please reopen if you think there's an issue here.
