### ISSUE TITLE
Link all MTB relations to relevant descriptions

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#473]
Mainly through the KKL E-yarok site. Use the weblink tag in OSM.
Please assign to me.

**Comment by HarelM** [comment]
Enjoy. Not sure how this is related to issues in the site as it is an OSM effort as far as I can tell...?

**Comment by HarelM** [comment]
I think this is no longer needed for the site as we are using off-road integration now.
In any case, it won't hurt to add this info to OSM.
Closing as this is no longer an issue related to the site.
