### ISSUE TITLE
Picture upload failure

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#481]
I've failed to upload a picture at "[באר פחר](https://israelhiking.osm.org.il/#!/16/31.3457/34.8164)" from the desktop

![image](https://user-images.githubusercontent.com/1304610/30759414-c2fee03c-9fde-11e7-9749-672e550ecfbe.png)

The upload failed multiple times. It seems like no response was sent received

The time of one of the attempts is in the screenshot below
![image](https://user-images.githubusercontent.com/1304610/30759271-48e77e26-9fde-11e7-8c9b-d932bfff5bfe.png)
![image](https://user-images.githubusercontent.com/1304610/30759303-6850aa1c-9fde-11e7-9f8c-41e38f1e9f2a.png)
![image](https://user-images.githubusercontent.com/1304610/30759326-79266d9a-9fde-11e7-8791-591ab3746b3e.png)
![image](https://user-images.githubusercontent.com/1304610/30759345-85c7751c-9fde-11e7-83b0-03e1cfca348f.png)

**Comment by HarelM** [comment]
Seems like the server is returning 500 - internal server error.
I tried to find the error in the logs at the relevant time (18:33) but I couldn't find anything out of the ordinary.
If this is something that is easy for you to reproduce I suggest to log to the server, clean the logs folder (either delete all logs or just place them aside) and try and upload and see if anything is written to the log file.
Another option is to upload the image here and I'll try and reproduce it.
I see that the image URL has two `/` which might be problematic in some cases, I'll try to fix this just in case...

**Comment by zstadler** [comment]
18:33:37 GMT is 21:33:37 local time. The log file has this line:

`2017-09-22 21:33:37.7688 | 13|ERROR| soft.AspNetCore.Server.Kestrel | Connection id "0HL81JJA3C9J5": An unhandled exception was thrown by the application. WikiClientLibrary.OperationFailedException: badtoken:Invalid CSRF token.`

**Comment by HarelM** [comment]
I don't have a clue what can cause this. This is related to the library I'm using to upload images to wikimedia, maybe we can open an issue there...?
https://github.com/CXuesong/WikiClientLibrary/issues
You can also try and reproduce this issue locally using the c# code and the `WikipediaGateway`.

**Comment by HarelM** [comment]
What is the size of the image? Maybe the image is large and it takes a long time to upload it and the clients gets a timeout? I set the timeout to 5 minutes which I thought is enough...

**Comment by zstadler** [comment]
It's not the 5 minute timeout. I had 3 failures in less than 5 minutes
```
2017-09-22 21:29:51.2233 |  0|INFO | IHM | Upload an image to wikimedia common: באר פחר, Location: 31.3445801, 34.8163586 
2017-09-22 21:30:59.6139 |  0|INFO | IHM | Upload an image to wikimedia common: באר פחר, Location: 31.3445801, 34.8163586 
2017-09-22 21:33:27.9563 |  0|INFO | IHM | Upload an image to wikimedia common: באר פחר, Location: 31.3445801, 34.8163586 
````
The difference between the timestamp in `site-2017-09-22.log` and the timestamp in `errors-2017-09-22.log` is about 10 seconds

**Comment by HarelM** [comment]
I tried searching for this error, but the word wiki in google only leads to wiki pages and not to the wikimedia documentation so it's extremely hard to find a similar issue/solution.
I suggest to try and ask in the repository I linked, the owner might know something.
The only thing that might be relevant that I found is the following:
https://phabricator.wikimedia.org/T89702
But I don't know what to do with the info provided there...

**Comment by zstadler** [comment]
According to https://github.com/CXuesong/WikiClientLibrary/issues/21#issuecomment-331722885, the above commit may be a redundant workaround.

**Comment by HarelM** [comment]
Great :-) you'll have a chance to play with NuGet a bit.
See if you can remove the redundant workaround and update the relevant package's version in the same commit.

**Comment by zstadler** [comment]
I'll what for publishing the workaround to see if it fixed this specific issue.
Then, you'll need to review the other changes in the release notes before upgrading, as @CXuesong wrote.

**Comment by HarelM** [comment]
@zstadler I published your fix. Let me know how you would like to proceed.

**Comment by zstadler** [comment]
I suggest that we chech for absence of token errors in a week.

In any case, I will let you handle the package upgrade, if you decide to take it.

**Comment by HarelM** [comment]
Sure, let's review this issue in a week. 
I'll update the package regardless along other packages I need to upgrade.

**Comment by HarelM** [comment]
Last error in the logs is from the 24-09.
Closing for now.
We'll need to revisit after 3rd party references update that I'm planning soon, but I don't expect this error to return even if removing the workaround.
