### ISSUE TITLE
Incorrect tagging when saving a Wikipedia site link

### ISSUE THREAD

**Issue by SafwatHalaby** [IsraelHikingMap/Site#484]
This node was created through IHM:  https://www.openstreetmap.org/node/5121718321

Initially, it had a `website=<he.wikipedia.org link>`. There's a community consensus to use the `wikipedia` tag instead, so I changed that to `wikipedia=he: <article name>`. Some time later, the user re-added the website link. 

I haven't checked the new UI, but I believe it's encouraging this. I think IHM should use the right tagging when the website link leads to Wikipedia.

**Comment by SafwatHalaby** [comment]
Perhaps the UI should have two seperate fields. "Wikipedia" and "website".

**Comment by HarelM** [comment]
I can't argue about the usage of correct tagging.
I'll see what I can do. 
I don't think the right solution is two fields for the same purpose.
I'm not very familiar with the wikipedia API and tagging, can you elaborate a bit how should I be tagging them?
The UI which we're offering is as simple as it can be and I'm not planning on changing it: a form field with and input to place an address of an external site.
My question is how do I extract the relevant data form this link in order to put it in the tags?
Also the above tagging seems insufficient: if I want to link to a Wikipedia page that is different between Hebrew and English how do I tag it?
I assumed the wikipedia tagging should've been `wikipedia:he=<article name for hebrew>` and `wkipedia:en=<article name for english`, am I wrong?

**Comment by SafwatHalaby** [comment]
>The UI which we're offering is as simple as it can be and I'm not planning on changing it: a form field with and input to place an address of an external site.

Fair enough. Then I propose internally detecting when the website is a Wiki and tagging accordingly as as described below.

>Also the above tagging seems insufficient: if I want to link to a Wikipedia page that is different between Hebrew and English how do I tag it?

A single Wikipedia tag, preferably in the local language, is sufficient. From the [OSM Wiki](https://wiki.openstreetmap.org/wiki/Key:wikipedia): "Data users can access articles in other languages where available using Wikipedia's interlanguage links."

>My question is how do I extract the relevant data form this link in order to put it in the tags?

You need the article **name** prefixed with the **language**. Luckily the Wiki url always has both the **name** and the **language**. So `website=https://en.wikipedia.org/wiki/Literary_Hall` becomes `en: Literary Hall`. Here's an untested regex:

`s/https?\:\/\/([a-z]).wikipedia.org/wiki/(.*)/$1: $2/g`

Note that the article name ($2) needs further treatment:
- Swap '_' with spaces.
- Non English languages sometimes (or always?) need url decoding. For instance:
 `https://he.wikipedia.org/wiki/%D7%AA%D7%9C_%D7%A9%D7%9C%D7%9D` needs to become `he:תל שלם`

**Comment by SafwatHalaby** [comment]
```

var uri = "https://he.wikipedia.org/wiki/%D7%AA%D7%9C_%D7%A9%D7%9C%D7%9D";
var matchWikipedia = /((https?\:\/\/)|^)([a-z]+).wikipedia.org\/wiki\/(.*)/
if (matchWikipedia.test(uri))
{
	uri = decodeURI(uri);
	uri = uri.replace(matchWikipedia, "$3: $4").replace("_", " ");
	console.log(uri); // prints
}
else
{
	console.log("Not a wiki tag");
}
```

**Comment by SafwatHalaby** [comment]
```
/** Receives a URL. If it leads to a Wikipedia article, returns the proper corresponding
OSM value. Otherwise return null. */
function getWikiTagValue(url)
{
	var matchWikipedia = /((https?\:\/\/)|^)([a-z]+).wikipedia.org\/wiki\/(.*)/
	if (matchWikipedia.test(url))
	{
		// This is a Wikipedia URL
		url = decodeURI(url);
		return url.replace(matchWikipedia, "$3: $4").replace("_", " ");
	}
	else
	{
		// this is a generic URL
		return null;
	}
}

var a = "https://he.wikipedia.org/wiki/%D7%AA%D7%9C_%D7%A9%D7%9C%D7%9D";
var wikiValue = getWikiTagValue(a);
if (wikiValue == null)
{
	console.log("Not a wiki URL");
}
else
{
	console.log(wikiValue); // prints "he: תל שלם"
}
```

**Comment by SafwatHalaby** [comment]
More compact version:

```
/** Receives a URL as a string.
Returns a key-value pair as an object: {key: <str>, value: <str>}

If the URL leads to a Wikipedia article, the key will be "wikipedia"
and the value will be the proper value as documented in:
https://wiki.openstreetmap.org/wiki/Key:wikipedia

If the URL leads to any other website, the key will be "website",
and the value will be the original URL. */
function getWebsiteOrWikiTag(url)
{
	var matchWikipedia = /((https?\:\/\/)|^)([a-z]+).wikipedia.org\/wiki\/(.*)/
	if (matchWikipedia.test(url))
	{
		// This is a Wikipedia URL
		url = decodeURI(url).replace(matchWikipedia, "$3: $4").replace(/\_/g, " ");
		return {key: "wikipedia", value: url};		
	}
	else
	{
		// this is a generic URL
		return {key: "website", value: url};
	}
}

var originalValue = "https://he.wikipedia.org/wiki/%D7%9E%D7%A9%D7%99%D7%9E%D7%94_%D7%91%D7%9C%D7%AA%D7%99_%D7%90%D7%A4%D7%A9%D7%A8%D7%99%D7%AA_(%D7%A1%D7%93%D7%A8%D7%AA_%D7%A1%D7%A8%D7%98%D7%99%D7%9D)";

var tag = getWebsiteOrWikiTag(originalValue);

console.log(tag.key + "=" + tag.value);
```

**Comment by HarelM** [comment]
Would be better if you could send a pull request for the following file which deals with updating OSM POI:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.API/Services/Poi/OsmPointsOfInterestAdapter.cs
Checkout the add and update methods.

**Comment by SafwatHalaby** [comment]
Will do.

**Comment by SafwatHalaby** [comment]
This would also require reversing the process when the users are viewing the POI, wouldn't it? An underlying `wikipedia` tag should be converted to a website URL for the user to see.

**Comment by HarelM** [comment]
Yes, the above class does exactly that - convert from OSM data to `PointOfInterestExtended` class and back.
All the logic is in the server side, so the UI doesn't need to change.

**Comment by SafwatHalaby** [comment]
What if the OSM element has both a `website` tag and a `wikidata` tag?

**Comment by SafwatHalaby** [comment]
I think you need to bump up the priority of this issue. The edits are adding up, causing issues:
  
* Improper tagging
* IHM users do not see the existing "wikipedia" tags for POIs and add a redundant "website" tag
* IHM users add "website" tags with wikipedia urls, Some Wiki bots auto fix it and move it to "wikipedia", making the "website" disappear from IHM interface, bad UX.
* Some IHM users add back their "website" tag, and now we have a redundant tag.

**Comment by SafwatHalaby** [comment]
>What if the OSM element has both a `website` tag and a `wikipedia` tag?

You'd probably have to modify the user interface to deal with this.

Perhaps have a single unified "website" field  in the interface as discussed earlier (which saves to either `wikipedia` or `website` behind the scenes), but if both `wiki` and `website` are detected for an element, add an extra field.

**Comment by HarelM** [comment]
Priority is up to you as I'm waiting for a pull request made by you...
Either way, I'm not planning on complicating the user interface in order to facilitate for this.

**Comment by SafwatHalaby** [comment]
Before making a PR, I need to know what to do, because the solution we've talked about earlier would not work if an osm element has both a `wikipedia` tag and a `website` tag. Which one would be displayed in the user interface?

**Comment by SafwatHalaby** [comment]
I've looked at the map a bit. I think a possible solution that requires no interface change would be prioritizing the `website` tag when both tags are present. This seems to be a rare occurrence for hiking POIs anyways so it doesn't seem like a big deal.

**Comment by HarelM** [comment]
I agree. `website` should have higher priority.
The server have an object prior to update and the new object in the update method - this is how currently I know how to change the tagging of a type of POI according to the icon (which tags to remove and which to add).
The same logic can be used for wikipedia tags - you'd have the new website tag and the old website tag and decide what to do according to server logic.
Was this clear enough?

**Comment by SafwatHalaby** [comment]
Yes. Updating is clear (hike map => osm).  But are you sure this is the only file? What about displaying data (osm => hike map), wouldn't I need to modify the url-setting logic here?:

https://github.com/IsraelHikingMap/Site/blob/6315ff397db54e21c67298b983b0050796e93d50/IsraelHiking.API/Services/Poi/BasePointsOfInterestAdapter.cs#L96

If I'm understanding this correctly, when a client clicks a POI, `OsmPointsOfInterestAdapter.GetPointOfInterestById` is called, which calls `BasePointsOfInterestAdapter.FeatureToExtendedPoi`, which is in charge of creating the `url` field. And that field is [sent](https://israelhiking.osm.org.il/api/poi/OSM/2319643913?language=he&type=node) to the client and is displayed in the client's website textbox. So, I'd need to change the url-creating logic. (fetch from Wiki tag or website tag, prioritize website if both present, convert wiki tag to full url if it's the only opne present)

**Comment by HarelM** [comment]
Yup, conversion is always symmetric.
Please note that I have updated the setup instructions since I upgraded to .net core 2.0.
Make sure to update the url in the osm adapter and not in the base class.

**Comment by SafwatHalaby** [comment]
The hassle of setting this up on Linux discouraged me from doing this. Please un-assign me.

This problem is still occurring regularly (IHM is adding website=wikipedia, and editors fixing this at OSM, making the link disappear from IHM). e.g. https://www.openstreetmap.org/changeset/54134647

**Comment by HarelM** [comment]
Please define exactly how should one convert the website url to OSM wiki tags and back and I'll make an effort to include this in the next release.

**Comment by SafwatHalaby** [comment]
Please see https://github.com/IsraelHikingMap/Site/issues/484#issuecomment-331631101. Note that I couldn't find official guidelines. These are my own observations and I may have missed some edge cases.

In summary:

### URL to OSM Tag

`http://lang.wikipedia.org/wiki/articleName` needs to become `lang: foo(articleName)`, where `foo` is a function which url-decodes articleName and then replaces _ with a space. urls may also start with `https`.

### OSM Tag to URL

`lang: articleName` needs to become `https://lang.wikipedia.org/wiki/foo2(articleName)`, where foo2 replaces spaces with `_` and then url-encodes.

### Additional info

* Lang should be two English letters, typically `he`, `en`, or `ar`, but technically any [ISO 639](https://en.wikipedia.org/wiki/ISO_639) code is allowed.
* Article name uri encoding and decoding should be equavilant to Javascript's [encodeURIComponent()](https://www.w3schools.com/jsref/jsref_encodeURIComponent.asp) and [decodeURIComponent()](https://www.w3schools.com/jsref/jsref_decodeuricomponent.asp) functions.

**Comment by HarelM** [comment]
Sorry, I don't understand what you wrote.
No need to get into implementation details, all I need is an example of relevant OSM tagging and wikipedia URL.
The above is cryptic to me: `<lang>` is not a valid OSM tag - did you mean `wikipedia:lang=value`? which value?
The regexp is even more cryptic so I can't use this comment as well (maybe I would be able to use it when implementing but I need to understand the concept first).
Please see if you can describe it in a user language.
Try forming a sentence like: "As an OSM user I would like to..." or "As a IHM user I would like to... so that I would be able to..."

**Comment by SafwatHalaby** [comment]
`<lang>` is my own place holder and it indicates where a 2 letter language string should be. e.g. `en`, `ar`, `he`.  `<articleName>` is my placeholder for any article name (a string).

I have provided two examples:
*  `website=https://he.wikipedia.org/wiki/%D7%AA%D7%9C_%D7%A9%D7%9C%D7%9D` <=> `wikipedia=he:תל שלם`
* `website=https://en.wikipedia.org/wiki/Literary_Hall` <=> `wikipedia=en: Literary Hall`.

Is this clear enough? I will formulate it differently if this is still vague.

**Comment by HarelM** [comment]
This is perfect.
but if I understand correctly it means that every OSM element can have multiple values for the wikipedia tag?
I know OSM supports multiple tags with the same key, but this creates an issue when converting to geojson etc since in most cases the conversion is made to a key value dictionary.
Wouldn't it be better to use the following conversion:
*  `website=https://he.wikipedia.org/wiki/%D7%AA%D7%9C_%D7%A9%D7%9C%D7%9D` <=> `wikipedia:he=תל שלם`
* `website=https://en.wikipedia.org/wiki/Literary_Hall` <=> `wikipedia:en=Literary Hall`.

Also, is this the only interesting tag that is related to wikipedia?

**Comment by SafwatHalaby** [comment]
According to taginfo, there are about 9000 `wikipedia:en` and about a million `wikipedia` keys.

The form you're mentioning, `wikipedia:lang`, is discouraged, because it adds redundant tags. Wikipedia has its own language interlinking system. A **single link** to one language, preferably the local language, is enough.

>only provide, in normal circumstances, a link to a single Wikipedia article, which should be to the article in the primary language for the subject. -- https://wiki.openstreetmap.org/wiki/Key:wikipedia



>Also, is this the only interesting tag that is related to wikipedia?

There is the related [wikidata](https://wiki.openstreetmap.org/wiki/Wikidata) tag. In essence, it makes the `wikipedia` tag redundant in many cases, and it might one day replace it. But many prefer having both tags and it's a debated subject. I don't think it should be added to the interface if you're striving to keep the interface super simple, and I think it should be ignored. (At least for now, where the two tags coexist and `wikipedia` is used heavily)

**Comment by SafwatHalaby** [comment]
>but if I understand correctly it means that every OSM element can have multiple values for the wikipedia tag?

Only one WIkipedia tag should be present. `wikipedia=lang:articleName`, `wikipedia:lang` is not widely used.

**Comment by HarelM** [comment]
OK, I think I understand now. Thank you for you patience.

**Comment by HarelM** [comment]
@SafwatHalaby feel free to review the code.
Haven't fully tested it, if you have a place I can check let me know.

**Comment by HarelM** [comment]
@SafwatHalaby please let me know if this does the trick, I have updated the production site with this feature/fix.
