### ISSUE TITLE
Create new route in Nakb from sharing page

### ISSUE THREAD

**Issue by MatanBenMoshe** [IsraelHikingMap/Site#485]
Add an option to continue and add a new hike to Nakeb database from the share page in Israel Hiking Map.
The link to Nakeb will seems something like https://www.nakeb.co.il/add_new_hike?ihm_link=G2ckwpPj65
In Nakeb add_new_hike page the title, description and the link to IHM will be loaded from the link and will be shown there.

**Comment by MatanBenMoshe** [comment]
I have implemented my side. Please check it's OK.
For example: https://www.nakeb.co.il/add_new_hike?ihm_link=1A6MiV4zGY
Currently it loads 3 values into the form:
1. title
2. descreption
3. IHM link

Maybe we should consider adding more fields? What do you think?

**Comment by MatanBenMoshe** [comment]
The only thing i can think about is email. Not sure it's so important.
What do you think? Does it seems OK?

**Comment by HarelM** [comment]
Unfortunately I don't have the e-mail address of the user (I know it's bad...).
Here are a few things I thought about:
1. The length can be calculated.
2. The difficulty might be also calculated using an algorithm that takes into account the length and the height shift - at least it can bu suggested.
3. Same thing for the time the trip might take.
4. Region can also be calculated from the route data.
5. If it's a round trip can probably also be calculated.

**Comment by MatanBenMoshe** [comment]
These are good points. I'm planning to remove all those fields from the add_new_hike page for make it more easy and simple to add new hike.

**Comment by HarelM** [comment]
I would advise against removing them totally but rather allow advanced options to anyone who desires to add those properties manually. In any case, the next release will have this button in the sharing window.

**Comment by MatanBenMoshe** [comment]
I didn’t mean to remove them totally from the hike, but just from adding new hike process.
I want the user to face less fields to fill when he wants to add a hike. Anyway, we’re verifying manually the hike is good enough so we can add it manually.

BTW- when are you planning your next release?

**Comment by HarelM** [comment]
Probably to the beta site tonight, and a few days later in case no major issue will be found I'll publish to production.
I can totally relate to less input fields when adding a new hike, if you add those fields manually when auditing the hike then there's no problem, except you have more work which in some cases of advanced users can be reduced.
In any case, less input for most users is the right way to go...

**Comment by HarelM** [comment]
Published to beta site: https://israelhiking.osm.org.il/test/
Let me know if you encounter any errors, I have updated all the UI 3rd party packages so things might not work as expected (although I did run some tests).
![image](https://user-images.githubusercontent.com/3269297/31049496-0f952a96-a63d-11e7-8255-bba3a2ea986f.png)

**Comment by MatanBenMoshe** [comment]
Looking good!

**Comment by HarelM** [comment]
Published to production. Please let me know if any changes are needed.
