### ISSUE TITLE
Allow to send public tracks to off-road

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#486]
Add a check box "suggest as public track" to the share to off-road.
Send it as a share code 3 when check box is marked.
Base on https://github.com/IsraelHikingMap/Map/issues/171

**Comment by HarelM** [comment]
@ilanza Seems that every route is currently sent with sharing code 3:
https://github.com/IsraelHikingMap/Site/blob/012304cf2c5ef093c93d410ac3bbffbd8ff03d25/IsraelHiking.Web/sources/application/components/dialogs/share-dialog.component.ts#L183
```
this.offroadRequest.sharingCode = 3; //fixed
this.offroadRequest.path = [];
this.offroadRequest.mapItems = [];
```

You told me in the mail I should replace 5 with 3 so I'm not sure which is private and which is public now...
Please advise.

**Comment by HarelM** [comment]
@ilanza I have updated the site with the relevant changes, please test that you get the right request (mainly the `sharingCode`).

**Comment by ilanza** [comment]
My mistake. It should be sent as 
this.offroadRequest.sharingCode = 1;
1 is pending approval.

**Comment by HarelM** [comment]
I have published the fix to the beta site:
https://israelhiking.osm.org.il/test/
Please make sure it works as expected.

**Comment by HarelM** [comment]
@ilanza published to production.
Please let me know if any changes are needed.
