### ISSUE TITLE
Picture name for POIs with special characters

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#487]
An error occurred when upload a picture for ["אתר "ערים בלילה](https://israelhiking.osm.org.il/#!/?q=ערים%20בלילה).

The intended name of the uploaded picture includes the double quotes of the name:
`2017-09-26 07:40:38.1696 | 13|ERROR| soft.AspNetCore.Server.Kestrel | Connection id "0HL84C982VGTI": An unhandled exception was thrown by the application. System.ArgumentException: The format of value 'File:Israel_Hiking_Map_אתר"עריםבלילה"' is invalid.`

Double quotes are not listed by Wikimedia as a [technical restriction for filenames](https://en.wikipedia.org/wiki/Wikipedia:File_names#Technical_restrictions), only # < > [ ] | : { } / and sequences of tilde characters (~~~). Therefore, this could be an issue in the Site code.

**Comment by HarelM** [comment]
The proposed solution is to replace '"' with "_".

**Comment by HarelM** [comment]
Missing other characters: `# < > [ ] | : { } / ~`
A regular expression will probably fix here.

**Comment by HarelM** [comment]
Published, feel free to test it, I have done very little tests on this...
