### ISSUE TITLE
Search URL to open the top search result

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#488]
This is a proposal for changing the behavior of the search url. If my memory serves me right, this used to be the behavior at some point in the past.

When using a search URL such as [https://israelhiking.osm.org.il/#!/?q=עין שריג](https://israelhiking.osm.org.il/#!/?q=%D7%A2%D7%99%D7%9F%20%D7%A9%D7%A8%D7%99%D7%92), the site shows a list of results

![image](https://user-images.githubusercontent.com/1304610/30843999-546d61d4-a295-11e7-8c12-6369eb6e800c.png)

Instead, I suggest the top search result will be selected and the map will focus on it.

![image](https://user-images.githubusercontent.com/1304610/30844085-d28f4da2-a295-11e7-82cc-70eb5594d8ef.png)

**Comment by HarelM** [comment]
Philosophical aspect is present here, moving part of the conversation to private.

**Comment by zstadler** [comment]
Summary of our brainstorm:
- The plan for the new behavior is that using the search through the URL will be equivalent to the current behavior of typing the text in the search bar and clicking the top search result. [See note below]
- The same behavior will take place when `Enter` is used from the keyboard.
- The same behavior will take place in mobile and desktop experiences.

Note:    
The details of the current behavior are: The map pans and zooms to the result's location, the result is selected and its pop-up visible, as seen in the above screenshot, and the search bar with the search results list is removed.

**Comment by HarelM** [comment]
Unfortunately this proves to be harder than I thought.
The following is where this fails:
When clicking the `ENTER` I currently don't know if this currently highlighted selection is an item in the list or not, so when hitting enter I do not know if I should do something or just use the default currently implemented behavior.
The following is the relevant API for autocomplete component:
https://material.angular.io/components/autocomplete/api
Having said that I can tell if the call was done from the URL or not.
My new proposal:
Only go to search results when URL query is involved (which is the original issue that was opened).
@zstadler please approve.

**Comment by zstadler** [comment]
Regarding
> When clicking the `ENTER` I currently don't know if this currently highlighted selection is an item in the list or not, so when hitting enter I do not know if I should do something or just use the default currently implemented behavior.

Currently, there is only one option in which the `Enter` does not do anything after typing text in terh search box. It is only if the down/up arrows have not been used to select a specific result line. I suggest that only in this case, the `ENTER` will be equivalent to `Down and Enter`.

**Comment by HarelM** [comment]
This logic is too complex and I need to manage the state of the drop down which is managed elsewhere in a code I don't have access to (angular material).
It might be possible to make it work, but I currently don't know how and I have a feeling it will make things very complex which I think is not worth it in term of code complexity and effort vs added value for the user.
So in order to mitigate, I propose to improve only the URL UX and keep the current search UX the same.
I know the URL benefit is limited to very few people who uses this feature but the code involved in adding it is also very small and contained.

**Comment by HarelM** [comment]
In light of recent changes and better understanding of the material framework on my part, I was able to fully support all required functionality.
@moshfeu Please note that you can now (right after I publish this feature) share a POI if it is the first search result using the method @zstadler mentioned in his post [above](https://github.com/IsraelHikingMap/Site/issues/488#issue-260496687)

**Comment by moshfeu** [comment]
Great! If you could also, generate the [social tags](https://moz.com/blog/meta-data-templates-123) so when someone will post this URL on facebook, for ex, the post will include the right content.
[AngularJS plugin](https://github.com/vinaygopinath/ngMeta) need to find for Angular 2+.

**Comment by HarelM** [comment]
There's a code to do it in the server called `OpenGraphController` - which handles facebook escape fragment portocol.
If you want to invest time in generating a share for POI that will also be supported in facebook feel free, I don't see much use to it...

**Comment by moshfeu** [comment]
I think that, this way, the posts on the social medias will look much attractive. 

Something like this:

![screen shot 2017-12-25 at 1 50 38 pm](https://user-images.githubusercontent.com/3723951/34339277-bed210e8-e97a-11e7-87d1-aadbc87ccf50.png)

instead of:

![screen shot 2017-12-25 at 1 46 08 pm](https://user-images.githubusercontent.com/3723951/34339290-e323bc44-e97a-11e7-9fcd-a965bad76a99.png).

Sadly, I can't do it in the near future..

**Comment by HarelM** [comment]
Yes, I can see what you mean.
Can you please open another issue about sharing of POIs?
I don't think it should use the search mechanism as search results may change and it should not affect the share - meaning it should use the ID of the POI for sharing.
Please try and define a UX for this (for example a share button inside a POI that will open a menu of possible social media options), preferably with screenshots.
Also include this Facebook requirement.
