### ISSUE TITLE
"Find unmapped routes" doesn't work

### ISSUE THREAD

**Issue by moshfeu** [IsraelHikingMap/Site#492]
When click on the button it seems that the map trying to go to wrong coords.

For example:

https://israelhiking.osm.org.il/#!/7/0.0000/4.2562

Instead of: 

https://israelhiking.osm.org.il/#!/16/32.0532/35.3181

So user can't use this functionality.

Example route: https://israelhiking.osm.org.il/#!/?s=FPloZ8ift0

**Comment by HarelM** [comment]
Thanks for reporting this!
Seems there are a few bugs there besides what you see about moving to invalid coordinates.
Please keep this unmapped so I can use this for debug.

**Comment by HarelM** [comment]
Related to a bug in a framework I'm using:
https://github.com/NetTopologySuite/ProjNet4GeoAPI/issues/20
I can probably use the workaround until it is fixed...

**Comment by moshfeu** [comment]
Thanks! I has another route if you will need.

**Comment by HarelM** [comment]
Will be published to production today or tomorrow.

**Comment by HarelM** [comment]
Published. Please let me know if you encounter any other issues.
Thanks again for reporting!

**Comment by moshfeu** [comment]
It seems that its working now. Thanks!
