### ISSUE TITLE
Advanced mode is no longer persistent

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#493]
## Context - ההקשר

The layers pane has an advanced mode
![image](https://user-images.githubusercontent.com/1304610/31064722-bc769d2a-a747-11e7-9844-694bae6aae98.png)

## Expected Behavior - ההתנהגות הצפויה

I'd like to remain in "advanced mode" every time I open the layers pane

## Actual Behavior - ההתנהגות בפועל

After closing and re-opening the layers pane, the advanced mode is turned off

## Steps to Reproduce - הוראות לשיחזור הבעיה

1. Open the layers pane
2. Turn on the advanced mode
3. Close the layers pane
4. Open the layers pane
5. The advanced mode is no longer active

## Impact - השפעה

The user is forced to repeatedly turn on the advanced mode.

## Your Environment - סביבת העבודה שלך

* Operating System and version - מערכת ההפעלה וגרסתה:    
Windows 10 Home

* Web Browser and version - דפדפן וגרסתו:    
  * Firefox 55.0.3 (64-bit)
  * Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by HarelM** [comment]
I wasn't able to reproduce on Win 10 chrome, are you sure this is not related to http/https change?

**Comment by HarelM** [comment]
Sorry, my mistake, didn't fully reads the steps to reproduce - it happens on second open when no refresh was made between opens.

**Comment by HarelM** [comment]
Seems like this issue is caused by the AoT compilation for production, not sure how to address this as I can't debug the minified code well and the bug doesn't reproduce in debug environment... :-/
I'll try and see if the maintainer of the local storage can help with that...

**Comment by HarelM** [comment]
Unfortunately the fix is more of a workaround so there might be other places where this issue can occur...
