### ISSUE TITLE
הוספת נ.צ מנתוני תמונה

### ISSUE THREAD

**Issue by Amirstad** [IsraelHikingMap/Site#494]
## <p align="right">ההקשר</p>

<p align="right" dir="rtl">
כיום ניתן להוסיף תמונות לנקודות עניין שכבר "נדקרו" וסומנו במפה, או לחלופין לסמן ידנית על המפה נקודה חדשה וליצור בה  נקודת עניין. על מנת להקל במצב בו משתמש צילם נקודת עניין ומעוניין להוסיפה למפה, במכשירי סלולר ובמצלמות רבות התמונה מכילה את נתוני המיקום בקובץ ויעזור מאוד אם תהיה אופציה להעלות את התמונה ומיקום עבורה יווצר אוטומטית.

## <p align="right" dir="rtl">מצב רצוי בראייתי
<p align="right" dir="rtl">
משתמש בוחר נקודת עניין/ יוצר נקודת עניין חדשה.  
המשתמש מעלה תמונה לנקודת העניין.  
במידה ומצויים נתוני מיקום, הללו נלקחים מן הקובץ ונבדקים מול מיקום נקודת העניין כרגע.  
במידה וישנה אי התאמה הגדולה מגודל מסוים (לדוגמא 20 מטרים) יישאל המשתמש האם ברצונו לעדכן את מיקום נקודת העניין על פי נתוני המיקום של התמונה.  
ניתן להוסיף לשלב זה תצוגה ויזואלית של מיקום הנקודה לעומת מיקום התמונה או לחלופין ציון המרחק ביניהן.

**Comment by HarelM** [comment]
בהינתן שבעתיד המאוד קרוב אנחנו הולכים להוסיף יכולת של הוספת מספר תמונות לנקודת עניין איך התוספת הזאת משתלבת בה? האם כל התמונות יזוזו?
בנוסף אנחנו מעוניינים כמה פשחות לשאול שאלות את המשתמש - שאלה כמו "האם אתה בטוח שהתמונה מתאימה לנקודת העניין?" היא שאלה שרק תגרור אי נוחות למשתמש שלא יהיה בטוח מה לעשות באותו הרגע ואחת האפשרויות היא שהוא יחליט לא להעלות את התמונה בכלל.

מה שאולי יותר נכון באופן כללי הוא מצב עריכה של הוספת נקודות עניין - כלומר מצב ספציפי בו אפשר לעשות פעולות מעין אלו - כלומר כפתור שמפעילים על מנת להוסיף נקודות עניין שאחת מהאפשרויות שלו היא הוספת נקודות עניין מתוך מיקום בתמונה.
בכל מקרה, כרגע אנחנו רוצים לתת לעוד משתמשים להתנסות בממשק לפני שאנחנו משנים אותו.
זו הצעה יפה שנצטרך לחשוב איך לשלב אותה.
תודה על הרעיון!

**Comment by HarelM** [comment]
Not sure this resolves the issue, but I'll add the option to open a picture or drag it onto the map to create a route with a single POI using GPSBabel functionality.
Problem with this is that I don't have the image name when converting with GPSBabel so the POI name is a temp filename... :-/
Since I'm guessing very few people are planning on using this drag-n-drop feature I don't see it as a big issue.

**Comment by HarelM** [comment]
It's a little complex now but it's possible with some clicks...
