### ISSUE TITLE
POI image thumbnails are downloaded in full resolution

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#497]
## Bug
When showing a thumbnail of a POI, the full resolution image is downloaded.

## What I expect to happen
Only a thumbnail of the image is downloaded, using the same URL syntax as used for the Wikipadia layer

## What really happened
The full-resolution image is downloaded slowly.

## What I did that caused the issue - step by step

- Search for "המפל הנסתר"
- Click on the first result - "המפל הנסתר, מועצה אזורית תמר"
- Wait for the thumbnail image to download
- View the thumbnail image properties
- See the size is `4,032px × 3,024px (scaled to 133px × 100px)`

## My environment
* Operating System and version: Windows 10 home
* Web Browser and version: Firefox 55.0.3 (64-bit)

## Thing I think the developers should know, images, links etc.
Rather than downloading the full-resolution image from 
https://upload.wikimedia.org/wikipedia/commons/6/61/Israel_Hiking_Map_%D7%94%D7%9E%D7%A4%D7%9C_%D7%94%D7%A0%D7%A1%D7%AA%D7%A8.jpeg
I suggest downloading a 180px thumbnail from
https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Israel_Hiking_Map_%D7%94%D7%9E%D7%A4%D7%9C_%D7%94%D7%A0%D7%A1%D7%AA%D7%A8.jpeg/180px-Israel_Hiking_Map_%D7%94%D7%9E%D7%A4%D7%9C_%D7%94%D7%A0%D7%A1%D7%AA%D7%A8.jpeg

**Comment by HarelM** [comment]
Bare in mind that images can be added from places other than wikipedia and in that case it will not work.
I can probably create a function that can check if the image is from wikipedia and manipulate the URL.
How did you know how to compose the 180px URL? I couldn't find the documentation about how to scale images to create the URL you provided...?

**Comment by zstadler** [comment]
> I couldn't find the documentation about how to scale images to create the URL you provided...?

https://meta.wikimedia.org/wiki/Thumbnails#Dynamic_image_resizing_via_URL

For NNN pixels wide image, substitute `(http.*)(/./../)(.*)` with `\1/thumbs/\2\3/NNNpx-\3`

**Comment by HarelM** [comment]
I think this can also solve #496.
The above is very helpful, I'll add the check for images that are not from wikimedia common in case someone edits OSM without upload an image to wikimedia.

**Comment by HarelM** [comment]
Published. Images are now also presented with lower resolution according to context in order to make image loading faster and reduce network traffic.
Thanks for the suggestion!
