### ISSUE TITLE
Additional formats for Lat/Lon search

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#499]
## Enhancement
Several lat/lon formats, as seen in the GEOnames database, are currently not supported by the search.

## What I expect to happen
The search to support
1. A `<Tab>` character as a possible separator between lat and lon. For example: `33.089748	35.319408`
2. A `:` character as a possible degrees/minutes/seconds separator. for example: `33:05:23N 35:19:10E`

## What really happened
The search does not recognize these formats

## My environment
* Operating System and version: Windows 10 Home
* Web Browser and version: Firefox 55.0.3 (64-bit)

## Thing I think the developers should know, images, links etc.
It is not clear how the `<Tab>` character is sent to the server

**Comment by HarelM** [comment]
This is not a bug IOM.
would you like to impotent it?

**Comment by HarelM** [comment]
`Tab` character was causing issues getting to the right controller method.
I have fixed it in the client side much like `/` character.

@zstadler can you please take a look at the following method:
https://github.com/IsraelHikingMap/Site/blob/2c9f9e5e1f06d9e2bc57212ae9ded4adafdcec86/IsraelHiking.API/Converters/CoordinatesParsers/UtmParser.cs#L27
The parameter `northing` is not in use besides the initial check but is being updated along the function.
Not sure what should be the right behavior. I checked to see if this was a mistake I made when I moved the code to a separate class, but it doesn't seems that way...

**Comment by HarelM** [comment]
@zstadler 
I send the `northing` value to the itm wgs84 converter now as I saw the it gave bad results for ICS
163226 1236767 coordinate, which is around טבעון.
Please review my code changes and make sure all the "ifs" are in the right place and doing what they should as I have little knowledge in that area.
