### ISSUE TITLE
Check for null responses from the router engine

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#5]
Sometimes, the routing leaves empty segments. I suspect it is because the routing engine did not provide a valid response/in time. This is usually fixed by going out and back into routing mode.

 I suggest the request will be re-sent once more to routing engine if the response is empty/invalid.

**Comment by HarelM** [comment]
Timeout of 1 second was added, no retries for now, we'll reopen if this is not enough.
