### ISSUE TITLE
Select multiple nodes

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#50]
With shift-clicking or shift-dragging an enclosing area.
It would simplify deleting multiple nodes from a route.

**Comment by HarelM** [comment]
See my comment at #38.
I currently do not have a way to select nodes multiple nodes. I'll try and think of an elegant way to allow the user to select multiple nodes - this will require to show the user that a certain node is selected.

**Comment by HarelM** [comment]
Routes usually do not have many points, Since click-drag is saved to map movement the only thing that would make sense is shift-drag, which I doubt someone will use.
Closing this for lack of public interest.
