### ISSUE TITLE
Certain tracks types are not showing on Groopy's embedded map

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#500]
## Feature-Bug
Note: This is a cross-site integration bug that requires a new feature from the IHM site.

[groopy.co.il](groopy.co.il) is using Israel Hiking embedded maps to show all its tracks. 
Unfortunately, the map does not support the following formats that are used extensively in Groopy:
- OziExplorer's `.plt` files
- CompeGPS `.trk` files
- Tab-separated `.txt` files

## What I expect to happen
The track to show on the embedded map.

## What really happened
The embedded map does not show the track.

## What I did that caused the issue - step by step
- Open Groopy's [מיער חולדה ליער המגינים דרך יער לחי](http://www.groopy.co.il/trackinfo.aspx?pid=817) page which uses the `.plt` track format.
  - Scroll down to the embedded Israel Hiking map and see there is no track on the map.
- Similarly, with the [מערד סינגל עין בוקק ים המלח](http://www.groopy.co.il/trackinfo.aspx?pid=1972) page which uses the `.trk` track format.
-  Similarly, with the [קרית טבעון, ציפורי ושמורת אלוני אבא](http://www.groopy.co.il/trackinfo.aspx?pid=580) page which uses the `.txt` track format.

## Things I think the developers should know, images, links etc.
GpsBabel, which is already used to translate other track formats, supports both formats:
- OziExplorer input using the `-i ozi` flag
- CompeGPS input using the `-i compegps` flag
- Support for Tab-separated input will probably require the use of the [Character Separated Values](https://www.gpsbabel.org/htmldoc-development/fmt_xcsv.html) input format, an associated style definition, and transforming waypoints into a track with the `-x transform,trk=wpt,del` flag

_Edited: rephrased, reformatted, and added the `.txt` file format_

**Comment by zstadler** [comment]
While adding support for CompeGPS `.trk` track files, the same flag can also support CompeGPS `.rte` route files which are also in use.

**Comment by HarelM** [comment]
This explains all the errors I saw in the logs and thought that it were mistakenly dragged onto the map.
This should be an easy fix...

**Comment by HarelM** [comment]
The linked txt file:
http://www.groopy.co.il/files/maslul/580gps.txt
contains a text file with UTM (I think) coordinates, Not sure using GPSBabel's csv format with different delimiter will do the trick without other flags (besides the transform).
Not sure from which device this file came from, but I think it will be better for Groopy to replace those files with known formats...

**Comment by HarelM** [comment]
Further investigation shows that the coordinates are not UTM coordinates but rather ICS coordinates.
God knows what is the source of these files but I don't think we should support them.
Closing this issue for now.
Please open a separate issue for the support of txt ICS files if you see fit, but I think Groopy should fix this on their side, I don't mind helping out with the conversion itself as a one time effort but I rather not add it to the production code.
