### ISSUE TITLE
Filter all KKL mtb routes and use them from off-road

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#501]
## What I expect to happen
No duplicates routes will be visible on the map.
KKL MTB routes would be updated using the off-road interface

## What really happened
KKL MTB routes are generated from OSM data and not through off-road interface

## Thing I think the developers should know, images, links etc.
in order to filter out KKL routes from OSM data the following are the relevant tags on a `relation`:
`operator=kkl` 
`role=mtb`

**Comment by HarelM** [comment]
@valleyofdawn Please approve that the following tags are the correct way to find KKL mtb routes:
`operator=kkl`  and `route=mtb`

**Comment by valleyofdawn** [comment]
Approving
