### ISSUE TITLE
Namesless POI have not info tooltip

### ISSUE THREAD

**Issue by moshfeu** [IsraelHikingMap/Site#503]
For example, the cave at:

https://israelhiking.osm.org.il/#!/15/32.0439/35.3224

And can't be edited (obviously). I think that not all of the caves have name but image and description will be useful.

**Comment by zstadler** [comment]
You can definitely edit it
1. Click on the POI edit icon
2. Click on the cave location
![image](https://user-images.githubusercontent.com/1304610/31311698-8c366b46-abba-11e7-9dd4-fa48a2cde956.png)

3. Click n the Upload button
4. Check that the POI type is a cave
![image](https://user-images.githubusercontent.com/1304610/31311705-9d28cbc4-abba-11e7-8295-812c0919570d.png)

**Comment by HarelM** [comment]
@moshfeu Please let us know if this is what you asked for, if so, please close the issue.
Thanks!

**Comment by moshfeu** [comment]
Yes! Thanks!
