### ISSUE TITLE
User dialog looks not good on mobile

### ISSUE THREAD

**Issue by moshfeu** [IsraelHikingMap/Site#507]
## What I expect to happen
User dialog should looks better on mobile devices. At least could be closed.

## What really happened
The dialog cutted and can't be closed

## What I did that caused the issue - step by step

Open the user dialog on mobile

## My environment
Android Chrome but I believe that it's happening on all mobile devices

## Thing I think the developers should know, images, links etc.

![capture _2017-10-10-23-31-04](https://user-images.githubusercontent.com/3723951/31409373-55ce2ab0-ae14-11e7-9994-2560d02c1bd6.png)

**Comment by HarelM** [comment]
I opened a bug for the angular material team a while ago but nothing happened.
Try and see if you nag them about it too if they decide to fix it:
https://github.com/angular/material2/issues/4574
