### ISSUE TITLE
Better POI Styling

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#508]
## Bug
Wikipedia images are presented in incorrect aspect ratio.

## What I expect to happen
Images to show in their original aspect ratio. For example:
![image](https://user-images.githubusercontent.com/1304610/31468849-49a2f228-aee8-11e7-96a2-09bfe33bbd66.png)

## What really happened
![image](https://user-images.githubusercontent.com/1304610/31468164-4cc1c6bc-aee5-11e7-879e-543bbff98724.png)

## What I did that caused the issue - step by step
1. Open https://israelhiking.osm.org.il/#!/18/32.9288/35.8548
2. Turn on the Wikipedia layer
3. Click on the Wikipedia item in the center of the screen

## My environment
* Operating System and version: Windows 10 Home
* Web Browser and version: Firefox and Chrome

## Thing I think the developers should know, images, links etc.
It may be fixed by replacing `max-width: 33%;` in the style of the div containing the image with `margin-right: 10px;` and removing `height: 100%; ` and `min-height: 100%;` from the style of the image itself.

```html
<div fxflex="33" style="flex: 1 1 100%; box-sizing: border-box; 
      /*! max-width: 33%; */
      margin-right: 10px;">
  <img fxfill="" style="margin: 0px; width: 100%;
      /*! height: 100%; */ 
      min-width: 100%; 
      /*! min-height: 100%; */"
      src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Juhader-02.JPG/128px-Juhader-02.JPG">
</div>
```
It seems like the existing style relies on the fact that Wikipedia images are requested at 128 pixel width. For general purpose images, `width: 180px; min-width: 180px;` can be used.

**Comment by zstadler** [comment]
Also, the top of the text should be aligned with the top of the image:

![image](https://user-images.githubusercontent.com/1304610/31469615-f99ddeac-aeea-11e7-830e-437cb73ccf66.png)

This can be done by using
```html
<div class="text-right" style="flex: 1 1 100%; box-sizing: border-box; margin-right: 10px; max-width: 66%;">
בריכת אורחה או בריכת ג'וּחַדֶר היא בריכה מרובעת עשויה בטון ובזלת אשר אוגרת את מי המעיינות של עין אום א-שרשיח הנובעים למרגלות גבעת אורחה.
</div>
```
which adds `class="text-right"`  to the `div` and removes the inner `p`:
```html
<div style="flex: 1 1 100%; box-sizing: border-box; margin-right: 10px; max-width: 66%;">
  <p class="text-right">
בריכת אורחה או בריכת ג'וּחַדֶר היא בריכה מרובעת עשויה בטון ובזלת אשר אוגרת את מי המעיינות של עין אום א-שרשיח הנובעים למרגלות גבעת אורחה.
  </p>
</div>
```

**Comment by HarelM** [comment]
This layer is planned to be removed. I don't see a reason to put any effort in fixing this right now...

**Comment by zstadler** [comment]
Frankly, I find the style of the Wikipedia pop-ups much more appealing and compact than the existing style of the POIs, especially with the above proposal.

For example:

![poi mockup](https://user-images.githubusercontent.com/1304610/31707683-b08828ca-b3f5-11e7-9ce7-e3c8207c4617.png)

**Comment by HarelM** [comment]
I agree this looks good.
Unfortunately this does not take into consideration the "source" image.
Take a look at nakeb or geepolog popups.

**Comment by zstadler** [comment]
I hope I understood what you mean by "the source image."

![trail mockup](https://user-images.githubusercontent.com/1304610/31718180-93821688-b417-11e7-9031-6f7df636bd5e.png)

**Comment by HarelM** [comment]
Nice!
What about when the text it long?
What about when the image is vertically oriented?
Also can you send me the height and width of the relevant part of the popup?
Can you also send how it should look where there's no image and how would the editing mode look?

**Comment by zstadler** [comment]
- According to the css, only the width of the text and the image is fixed.
- Their height and the height of the popup should be undefined.
- I've used 55px as the height if the source image, and it should scale proportionally.
- The current camera icon is fine for POI's. I don't know remember what we've agreed, if at all, with the trails providers.
- I suggest the basic editing mode will use the same dimensions.

**Comment by zstadler** [comment]
There is also a small correction to the description text definition in order to align it with the title.

This can be done by using
```html
<div class="text-right" style="flex: 1 1 100%; box-sizing: border-box; max-width: 66%;">
בריכת אורחה או בריכת ג'וּחַדֶר היא בריכה מרובעת עשויה בטון ובזלת אשר אוגרת את מי המעיינות של עין אום א-שרשיח הנובעים למרגלות גבעת אורחה.
</div>
```
removing `margin-right: 10px; `.

**Comment by HarelM** [comment]
@moshfeu if you are up to it, it would be great if you could take care of this issue.
In general both wiki-marker-popup and poi-marker-popup should look the same, much like what @zstadler illustrated:
regular:
![image](https://user-images.githubusercontent.com/3269297/32064892-d4cc95b0-ba83-11e7-9144-1a33a4b9ff05.png)
edit mode:
![image](https://user-images.githubusercontent.com/3269297/32065157-96610c24-ba84-11e7-9668-cf3a989dda69.png)
No image:
![image](https://user-images.githubusercontent.com/3269297/32065241-cef17e48-ba84-11e7-8573-3bee117f2263.png)

Few notes:
1. text overflow should surround the picture.
2. wiki markers should not have vote options.
3. wiki markers should not have edit options (or for that matter any point defined as non-editable).
4. source image should be inline with the title of the POI.
5. This popup has fixed width so I don't see a good reason to use material framework here as all sizes should be fixes as well.

As a side note - it is more important to change the POI look than wiki POI because I'm planning in the near future to add wiki markers inside POI mechanism - see #442.

**Comment by moshfeu** [comment]
I will take a look. I hope I could get all the options due I couldn't update the local DB.

**Comment by HarelM** [comment]
Had some time to work on it.
@zstadler please let me know if this suits your needs.
This is how it looks:
![image](https://user-images.githubusercontent.com/3269297/32198353-753c8240-bdd0-11e7-938d-b11bace31d0a.png)
Empty POI:
![image](https://user-images.githubusercontent.com/3269297/32198888-d47138f8-bdd2-11e7-90f3-4d45d5401651.png)
Edit Empty POI:
![image](https://user-images.githubusercontent.com/3269297/32199119-e8927a62-bdd3-11e7-85a5-e69e984c3056.png)
With image while editing:
![image](https://user-images.githubusercontent.com/3269297/32200008-0f7a0150-bdd8-11e7-9370-3513ceb494af.png)
