### ISSUE TITLE
Add to share link metadata its name and description 

### ISSUE THREAD

**Issue by MatanBenMoshe** [IsraelHikingMap/Site#510]
## What I expect to happen
See the link name and description in its metadata when sharing in WhatsApp and others

## What really happened
It looks like regular link to the website 

## What I did that caused the issue - step by step
Share link in WhatsApp 

## My environment
* Operating System and version:
* Web Browser and version:

**Comment by MatanBenMoshe** [comment]
![76b8fc8a-9657-48bd-b39a-0f91c9c31b93](https://user-images.githubusercontent.com/17752588/31509122-09b95494-af89-11e7-9b41-1320c50a41c4.jpeg)

**Comment by HarelM** [comment]
Facebook supports `escape_fragment` protocol which allows to get more data for single page application (SPA), whatsapp doesn't so the link is always to the default link.
Might have changed since the last time I studied the matter though...

**Comment by MatanBenMoshe** [comment]
I'll try to rewrite the suggestion- not the metadata but the **text** itself can be with more details.
For example, instead of just:

> israelhiking.osm.org.il/#!/?s=7PzFFQSpiP

Something like:

> קישור למסלול - נחל עמוד תחתון
> israelhiking.osm.org.il/#!/?s=7PzFFQSpiP

where נחל עמוד תחתון is the link title.

**Comment by HarelM** [comment]
I see, Thanks for the suggestion!
Since I can't test it on my dev env I'll upload something and see if it works.
