### ISSUE TITLE
Display indicator if POI has extra data

### ISSUE THREAD

**Issue by moshfeu** [IsraelHikingMap/Site#512]
## Feature
Display an indicator on the POI's tooltip so the user could know if there a reason to click on it.

## Thing I think the developers should know, images, links etc.

Something like this:

![indicator](https://user-images.githubusercontent.com/3723951/31538708-17ce3b0e-b00f-11e7-98f0-68a6e73deb4b.png)

**html** (under `fa-stack fa-lg`)

```
<span class="indicator" style="
    background: poi-color;
"></span>
```

**css**
```
span.indicator {
    width: 5px;
    height: 5px;
   display: block;
    position: absolute;
    top: 5px;
    right: 5px;
    border-radius: 50%;
}
```

**Comment by HarelM** [comment]
I don't see a good reason to introduce such a feature - I want people to see that there is missing data and add it. Instead this feature will facilitate for the option to know there is missing data and not add anything...
Not sure I managed to convey my message.
I want people to be irritated by the fact there's no data and contribute...

**Comment by moshfeu** [comment]
Sure! But if the user looking for POI in their trip they have no data yet. Currently, that the site has no many data yet, it's a little annoying to open tooltip which has no data. Also, in this days, indicators cause the user to do more interactions by the power of the habit. This is my opinion of course :)

**Comment by HarelM** [comment]
Unfortunately, the description and image of a POI is fetched when the POI is opened so this data is not present at the time the POI marker is created.
I can add a flag probably to `PointOfInterest` and update it when fetching the data from the database but it seems very complex for the small benefit we'll get.
Pull request is welcome.

**Comment by zstadler** [comment]
Alternatively, we can consider avoiding in the future including in the POI layer places that have no description and no image.

In such a case, a click on any POI in the layer will be valuable as it will show additional information.

On the other hand, contributors will be able to add descriptions and images to any place on the map just like they are able to do now for places that have no name.

**Comment by HarelM** [comment]
I think the current way of adding data to POI that do not exists is for advanced users and not for regular users.
I think the current UX for regular users that they can edit an existing POI that only has a name is the preferred method.
We might consider rethinking this in the future when there's more data in the POI layer, but I think that for now this is the right approach in order to engage the users in updating the POIs.
Also note that POI layer can be seen over satellite imagery (but this is probably a edge case).

**Comment by HarelM** [comment]
Wasn't as complex as I thought it will be. Now that some POIs have data due to the merge algorithm it is useful to see which points have data and which don't.
