### ISSUE TITLE
POI edit dialog is closed after map pan

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#514]
## What I expect to happen
The dialog to stay open.

## What really happened
The dialog was closed. If an image is uploaded before the pan, it is lost.

## What I did that caused the issue - step by step
1. Search for "מערת הקולומבריום"
2. Select the first result
3. Click the "edit" button and see this dialog:
  ![image](https://user-images.githubusercontent.com/1304610/31565897-21e73ad4-b071-11e7-9cdd-68bcaeb977c3.png)
4. Pan the map in order to see the full dialog and the dialog is closed:
  ![image](https://user-images.githubusercontent.com/1304610/31565731-a137d9b6-b070-11e7-8454-8c7f54d90302.png)

## My environment
* Operating System and version: Windows 10 home
* Web Browser and version: Firefox

**Comment by HarelM** [comment]
The dialog closes only when the POI point is more than 20% outside the view-able area.
Are you sure these are the correct steps to reproduce?
The images shows a different zoom level - not panning (I define panning only as moving the map to the sides, not sure this is the definition though - but this is the leaflet's code definition of panning).
