### ISSUE TITLE
Add legend item for unmarked trail

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#517]
## Feature
Following https://github.com/IsraelHikingMap/Map/issues/163, there is a need to show the difference between marked trails and unmarked trails.

**Comment by HarelM** [comment]
53eb6c9165cb44cdc634661efd35f7dcfd3b3ab4
0ac29167a542d6b24a1598c4a50c217094fe20f5
184ccb699894928c5a41ada17f3659ff4a7709f6
