### ISSUE TITLE
Potential "blank touching" bug

### ISSUE THREAD

**Issue by SafwatHalaby** [IsraelHikingMap/Site#518]
## What I expect to happen

IHM should either modify an OSM element or not touch it at all.

## What really happened

A node appeared in 3 hiking map-created changesets, but only the first one modified the node. The other 2 changesets seem to have made no modifications to the node tags nor to its coordinates. Effectively a "blank edit".

- https://www.openstreetmap.org/node/4119166214
- https://osmlab.github.io/osm-deep-history/#/node/4119166214

Node coordinates remained the same across all 3 changesets: 33.0094109, 35.2060013

## What I did that caused the issue - step by step

I don't know. Issue detected via QA tools.

It may be useful to contact the [uploader](https://www.openstreetmap.org/user/Nir%20Rabino) and ask them what they did to cause this.

## My environment

Irrelevant.

## Thing I think the developers should know, images, links etc.

I think this "blank touching" was described in the OSM Wiki but I cannot find it now. It probably has a better term.

**Comment by HarelM** [comment]
I think it should be easy to reproduce, just click edit on a POI and save it. Currently the server does not check if any changes were made, it just updates OSM. I was hoping OSM takes care of it...
Might be worth trying and opening a bug on their side as well...
