### ISSUE TITLE
UX - Confusing message when POI has no description

### ISSUE THREAD

**Issue by SafwatHalaby** [IsraelHikingMap/Site#519]
## What I expect to happen

When a non logged in user clicks a POI that has no description, the message should be clear: "This POI has no description. You can log in to add one!"

## What really happened

When a non logged in user clicks a POI that has no description, the message says "Please login", giving the impression that the description exists but is hidden for guests. A guest who registers and then logs in based on that, will be disappointed.

Current wording: 

```
You need to login to OSM first, please use the button in the upper right corner to login

יש צורך להתחבר לחשבון ה- 
OSM,
 אנא לחצו על הכפתור בפינה הימנית עליונה על מנת להתחבר. 
```

**Comment by HarelM** [comment]
While he might get disappointed, it did make him login to OSM. 
Not that I planned it this way but I'm not sure this is a bad side effect...

**Comment by SafwatHalaby** [comment]
Well, that was just one kind of user. I should have picked a less optimistic outcome example.

"register-to-see-content" is annoying for many . The kind of user at the other end of the spectrum goes like: "They're trying to force account registration down my throat just to show me some walled content! I ain't never coming back. I bet they'd probably spam my E-mail anyways. AmudAnan ftw!".

It's well known that every extra click will shed away visitors. In fact, many "walled content" websites try to trick you by withholding the fact that registration is required until you take a few steps in because they know "register-to-see-this" is likely to make you leave the site.

**Comment by HarelM** [comment]
I don't really mind changing the text.
Please suggest a text in Hebrew and in English for the dialog when user is not logged in.
