### ISSUE TITLE
Add route/s sharing control

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#52]
In combination with plotting external routes this would allow sharing your routes on the map.

**Comment by HarelM** [comment]
No sure I understand this one.
There's no problem using iframe with IHM. I just tested it locally, here is the code:
```html
<!DOCTYPE>
<html>
<head>
</head>
<body>
	<iframe src="http://osm.org.il/IsraelHiking/" height="500" width="500" />
</body>
</html>
```

**Comment by valleyofdawn** [comment]
Great. 
Why not put a link with the code so anyone can share their route visually?

**Comment by HarelM** [comment]
Again, not sure what you mean. You can copy the address bar and share the route using a link. Please elaborate or close.

**Comment by valleyofdawn** [comment]
![sharing example] (https://drive.google.com/file/d/0B9wqXNeLjm_YenFVb0I0WC1md1E/view?usp=sharing)

**Comment by HarelM** [comment]
Please please use more words...

**Comment by valleyofdawn** [comment]
You can't see the image?

**Comment by HarelM** [comment]
Nope...

**Comment by valleyofdawn** [comment]
![share](https://cloud.githubusercontent.com/assets/689201/9248913/c68ae924-41c8-11e5-8b6c-a3ef1c1d6851.jpg)

**Comment by HarelM** [comment]
I thought this pop up was preventing me from see the relevant image :-)
This is easy except the for the social networks.
I think we can start with a simple share without the social networks and maybe add them later...

**Comment by valleyofdawn** [comment]
Excellent.
On the longer run, social networks are important as many people use them to share their rides.

**Comment by HarelM** [comment]
Very basic and probably not pretty enough. but I think it'll do for now...
