### ISSUE TITLE
Flagging bad point

### ISSUE THREAD

**Issue by SafwatHalaby** [IsraelHikingMap/Site#522]
## What I expect to happen

A user totally unexperienced with mapping should have an easy way to report issues. I propose a "דווח על תקלה" button or something similar.

## What really happened

A user wrote his complaint in a description. Although it's illegal, it got my attention while doing QA, and there's no other way to flag things from IHM itself. 

That's the point: https://israelhiking.osm.org.il/#!/20/32.7913/34.9958

Changeset: https://www.openstreetmap.org/changeset/53013175

**Comment by HarelM** [comment]
I think this is a valid description, I thought about adding the same for "עין ערפד" "עין שבתי" and "עין אוד" where I did a hike and there wasn't a drop of water.

**Comment by HarelM** [comment]
Also who will you report this to? I'm not planning on spending my time fixing places people reported a problem...

**Comment by SafwatHalaby** [comment]
>Also who will you report this to? I'm not planning on spending my time fixing places people reported a problem...

...to me. I'm monitoring that stuff anyways. Perhaps pushing [OSM Notes](http://resultmaps.neis-one.org/osm-notes-country-feed?c=Israel&a=opened) should be enough, I'd catch them. You don't have to invent a report system.

>I think this is a valid description, I thought about adding the same for "עין ערפד" "עין שבתי" and "עין אוד" where I did a hike and there wasn't a drop of water.

Adding the water quantity of a point, or the fact that a node called "ein" has no water, is a valid description. Adding a "this POI is not there and should be removed from OSM" is not a valid description.

And in general, many map viewers who don't know how to map would wanna report other generic problems (e.g. this street is a dirt street, this shop changed a while ago)

**Comment by SafwatHalaby** [comment]
Well, maybe I was sloppy when reading the description. If the description is implying the POI is there but is dull and uninteresting, then that particular instance is a bad example for a POI that should be deleted. But the proposal could be valid anyways.

**Comment by HarelM** [comment]
There are a lot of OSM notes is Israel right now. I don't suppose you are planning on fixing those, right?
The concept of "some one else will fix it for me" is just not the right message we would like to send to the community - our message is: "if it's not right for you, you should fix it and not someone else".
We (IHM team) had this discussion about OSM notes and we believe it is the wrong approach.
We believe people should take the time to learn the system and improve it by contributing.
I'm coming off as someone who doesn't want to implement anything, but honestly that's not it...

**Comment by SafwatHalaby** [comment]
That's a good argument. Fair enough.

>I don't suppose you are planning on fixing those, right?

It's realistically impossible for me to fix all of them time-wise and knowledge-wise.  I want to monitor all new notes (which aren't very frequent as of now) and fix what I can. I also check out some older notes from time to time.
