### ISSUE TITLE
Explanation for repetitive bad descriptions. "תחילת מסלול"

### ISSUE THREAD

**Issue by SafwatHalaby** [IsraelHikingMap/Site#523]
I'm often seeing and reverting `description=תחילת מסלול`. Is this a coincidence or is IHM encouraging this somehow?

**Comment by HarelM** [comment]
I don't see how IHM can encourage this. can you?

**Comment by HarelM** [comment]
I also don't think this is the right forum to discuss this. OSM forum is the right place to talk about bad tagging and description.

**Comment by SafwatHalaby** [comment]
Sorry HarelM. If there's a technical UI reason encouraging this, then this could be the right place to discuss this.

>I don't see how IHM can encourage this. can you?

I have no explanation, but I think all such edits are coming from IHM.

**Comment by HarelM** [comment]
Nothing to be sorry about :-)
IHM makes it easier to edit and I believe has more people willing to edit as it doesn't require a steep learning curve as opposed to OSM, I think...

**Comment by zstadler** [comment]
> I'm often seeing and reverting description=תחילת מסלול. Is this a coincidence or is IHM encouraging this somehow?

@SafwatHalaby,
Can you send links to few of these changesets? I'd like to check if the descriptions were added using IHM.

**Comment by SafwatHalaby** [comment]
>IHM makes it easier to edit and I believe has more people willing to edit as it doesn't require a steep learning curve as opposed to OSM, I think...

Could be.

I suspected it might be a strange use case where people use this to tag the edges of their trip or something.

@zstadler, I wish I had them. I've been seeing them across an extended time period of Osmcha mapping and didn't collect them. It's usually "תחילת מסלול" or "סיום מסלול" or some other variation. Since the expression registered in my brain it must have been at least a couple of times. 

I found the following by randomly specifying Overpass Attic dates. Is there a simple way to extract all of them? That'd give a picture of how many are IHM.  

ihm:
https://www.openstreetmap.org/node/4889863123/history

not ihm:
https://www.openstreetmap.org/node/4781190218/history

**Comment by HarelM** [comment]
You can send a personal message to the relevant user too and ask him...

**Comment by zstadler** [comment]
I wrote them:
* https://www.openstreetmap.org/changeset/53036278
* https://www.openstreetmap.org/changeset/47539487

This phenomenon does not seem to me as any different than other spamming and trolling in Israel.

With [this Overpass query](http://overpass-turbo.eu/s/sAA), I could only find one additional node, from the same user:
* http://www.openstreetmap.org/node/4889863122

Overall, it seems like two users since January 2015.

**Comment by SafwatHalaby** [comment]
That query does not take into account the tags that I removed.
Example: User adds tag in 2016, tag removed some days after in 2016. It wouldn't appear in a 2015-2017 diff. 

>Note that the output does not include any intermediate versions, which might exist between the first and the last timestamp, i.e. if there are several changes on an object, only the last version in the given timeframe is returned. 

source: https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Difference

**Comment by SafwatHalaby** [comment]
... with that said, I'm not 100% confident it's an IHM/special issue and you could be right. I simply recall spotting this multiple times, probably more frequent than generic vandalism. I don't have numbers to prove my memory right, and thought there could be a simple explanation that I'm missing.
