### ISSUE TITLE
Display map OSM update time 

### ISSUE THREAD

**Issue by ylivny** [IsraelHikingMap/Site#526]
## Feature
Display map OSM update time for the currently displayed zoom level
A suitable place can be the status bar at the bottom of the map (the one that contains the copyrights, similarly to the way Google Maps are displaying date of street view pictures) -or- in the About menu (might be tricky since the zoom level can change while the menu is open)

**Comment by HarelM** [comment]
I think that update date by zoom level is a bit too complicated.
This should also be applied to offline files as well.
I'll see what can be done.
Thanks for taking the time to open a request!

**Comment by zstadler** [comment]
Different times are applicable to Hebrew and English, to the hiking map and the MTB map.

I also believe that the separation by zoom level is too complex.

**Comment by HarelM** [comment]
I hope we'll be able to solve this by improving the tile generation process to be as up-to-date as possible.
Since I think our time is better spent finding a solution to this problem I'm closing this issue.
If we won't be able to make the tiles up-to-date, I'll reopen this issue.
