### ISSUE TITLE
Allow hiding of search result icon from the map

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#529]
## Feature
I've used the search to pan and zoom the map to an area.
In order to take a screenshot, I would like to remove the icon of the selected search result, but I could not find how.

Here is a sample screen shot with the search result icon:

![image](https://user-images.githubusercontent.com/1304610/32224877-cdfe6c9c-be4b-11e7-86fd-41dd5cb3446b.png)

Here is a screenshot with all available dialogs and buttons. As far as I can see, none of them allow the removal of the icon from the map. 

![image](https://user-images.githubusercontent.com/1304610/32224985-2544b20e-be4c-11e7-9dba-d51b78540672.png)

I suggest adding a <image height="16px" src="https://user-images.githubusercontent.com/1304610/32225045-69d9fc8a-be4c-11e7-846d-70ce434d4f8d.png"/> button to the POI dialog.

**Comment by HarelM** [comment]
The only issue here, I think, is that you shouldn't be able to do it for actual POIs (those that are not part of the search results but part of the POI layer) and this makes things complicated.
I did see this issue but didn't have a good solution, I'll see if I can think of one...

**Comment by HarelM** [comment]
What about routes search results? 
This icon is used only to clear the route from the map but not to hide the marker itself.
Do you want to change the current behavior for routes? Do you want this icon to have different behavior depending on if this is marker from search results or from POI routes layer?

**Comment by zstadler** [comment]
For the same reason as for POIs, and for consistency, I think that the icon for a route search result should be removed from the map together with the route. 

The icon should also be removed after the "+" button is clicked and the route is added as a new layer. From this point on, the origin of the new layer is no longer relevant.

**Comment by HarelM** [comment]
But selecting search results can open an existing route from the route POI layer - what should happen in this case? The hide button should be acting differently? This might create a confusing UX...
