### ISSUE TITLE
No preview for share

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#530]
## What I expect to happen
I expect there will be a preview for https://israelhiking.osm.org.il/#!/?s=aoveiXpMoW such as:

<image width="25%" src="https://user-images.githubusercontent.com/1304610/32238733-4e0af08e-be71-11e7-887d-77d91e1663c6.png">

## What really happened
The preview is blank.

<image width="75%" src="https://user-images.githubusercontent.com/1304610/32238254-fdc1a920-be6f-11e7-9fa9-0c21101898f1.png">

## Thing I think the developers should know, images, links etc.
The URL for the white base map is a white pixel taken from
https://upload.wikimedia.org/wikipedia/commons/6/60/1pixel-wit.png

<image width="50%" src="https://user-images.githubusercontent.com/1304610/32238411-5cbbd734-be70-11e7-9f3c-2c63baf51ffe.png">

**Comment by HarelM** [comment]
Well, I'm not sure this is a valid example as the base layer is not a tile layer.
The server code assumes the tiles are 256x256 px.
Seems like an edge case I'm not sure worth fixing...

**Comment by zstadler** [comment]
https://israelhiking.osm.org.il/#!/?s=hYszeLdzT4 is a share that uses a fixed 256x256px white tile as a layer definition, and it too does not have a working preview.

**Comment by zstadler** [comment]
The share still has no preview in "My Shares" list

![image](https://user-images.githubusercontent.com/1304610/32936187-eefba5c6-cb7b-11e7-9d79-93ca7ba83312.png)

**Comment by HarelM** [comment]
Please check the images api to see if the image is generated or not.
It might be a browser timeout issue or cache issue.

**Comment by HarelM** [comment]
Need to support overlays for image preview.

**Comment by HarelM** [comment]
Fixed by 0eb9118
