### ISSUE TITLE
After sharing allow editing without changing the original shared link

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#531]
## What I expect to happen
Currently, after sharing a track any update requires a new share with a new url. It would be nice to have an option to update a shared track so that the original shared url links to the updated track. 

## What I did that caused the issue - step by step
Feature request

**Comment by HarelM** [comment]
The problem here is mainly the concern of how the user decides to edit a share, how to save it (save button is already used for files) and how to cancel editing.
Please propose a solution for all the above without introducing new buttons on the main screen and without complicating current usage of the site for regular shares, edit and save.

**Comment by oriori** [comment]
In the my shares window, add a button "edit route" (or replace the edit route details button) next to each route. Once clicked the user will be taken to (maybe a new instance of the) main map screen to edit the route. When clicked, the share link button will now invoke the share link dialog box but instead of the share now with friends button, there will be two buttons. One for sharing under the original link and one for sharing with a new link.
Another option is that instead of adding a button to the my shares window, simply clicking on the link to view the route will take the user to the main map window with the share link modification specified above. A different color for the share link button can serve as a visual indication to the user that he is in this edit mode.

**Comment by HarelM** [comment]
I was thought about it too and came up with the first suggestion as well, but instead of two buttons I thought about using a check-box saying something like "Update current share" or something similar which is basically the same.

**Comment by zstadler** [comment]
I like it!
Perhaps a "Save current map" title for the checkbox.

**Comment by HarelM** [comment]
The following is what is planned for this release:
1. When a user creates a share the next time he'll try and share a check-box will appear letting him choose if he wants to update current share.
2. When a user opens his own share and opens the share dialog the same check-box will appear.

If you think there are other valid scenarios let me know.
I think it's fairly intuitive and covers the basic needs without complicating it.

**Comment by oriori** [comment]
Regarding 1, when does this behavior resets to the normal one? (when does
the website forgets the user shared a route and doesn't offer the checkbox
to update the old share?). If it persists, is it clear to the user which
share he is about to update?
Also, if it's not already the case, I would make the checkbox unchecked by
default.
And lastly, if a share was updated, the website should say so in the msg
displayed to the user, instead of saying a share was created.

**Comment by HarelM** [comment]
The website will forget after a refresh.
The check-box is off by default, and is not persistent.
The user will be presented with the regular share dialog - there's no message, the button text does change to better indicate this is a different action.
I'll update the site in the next few days, give it a try and then let us know if this is fits your needs or not...

**Comment by oriori** [comment]
Sounds good.
And by msg I meant the text in the window appearing after creating the
share. But nevermind.
