### ISSUE TITLE
search what is near here

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#532]
## What I expect to happen
Let the user search for objects drawn on the map by clicking on them or near them. Ideally, while in this mode, a user would click on a single track or a highlighted road (like the IBT), for example and the same dialog box that pops up after a finding the object with a textual search will appear. For simplicity the "near here" results can be limited to specific object types (roadways etc). A more advanced feature will give the user the option to limit the types of objects searched for.

**Comment by HarelM** [comment]
I don't understand the proposal, can you elaborate a bit? maybe add some screenshots/power point presentation of the required feature?

**Comment by zstadler** [comment]
@oriori,

Is it related to the "Use visibility within current map extent to prioritization of search results" issue #249?

**Comment by oriori** [comment]
@zstadler That might be one way to implement it. I was thinking more along the lines of google maps What's here? (right click anywhere on google maps). But instead of simply giving an address or a region name, the result will be the option to select a track or whatever the user is interested in. Think for example about a user who wishes to convert the TA-Jerusalem bike route (ים לי-ם) into an IHM route. He sees it marked in red on the map but he doesn't know the route name. With this functionality he would be able to convert it into an IHM route easily, and also learn the route name.

**Comment by HarelM** [comment]
In my opinion, the interaction with the map, or any user interface for that matter should be done with visual cues, and those visual cues should be big enough so that you'll be able to easily click them - this is the mobile first approach.
Clicking on a place in the map and assuming it will interact is not intuitive for most users.
Therefore, we decided to place marker where there are routes and places that we think are interesting.
You can show and hide these routes and points in the layer menu.
If I understand correctly, there's nothing to implement in this feature request.

**Comment by oriori** [comment]
Yes, the public routes answers most of what I requested. I wasn't familiar with that. Is there a design discussion/document for public routes? The UX of public routes isn't on par with the rest of the website, IMO.

**Comment by HarelM** [comment]
>The UX of public routes isn't on par with the rest of the website, IMO.

This is a bit too vague for me to be able to do anything with this. I believe the POIs and Route POI are using the same UX, the wikipedia marker will be converter to the same UX with issue #442 and the rest of the editing UX is now covered in issue #537 which is still not implemented but is something we'll be getting to soon and should facilitate for a consistent UX throughout the site.

**Comment by oriori** [comment]
What's the source for public routes? There are many duplicates, some errors (the 4 bicycle routes [here](https://israelhiking.osm.org.il/#!/16/31.9404/34.9459) are shifted from the actual roads), incomplete routes (סובב ירושלים) and some [junk](https://israelhiking.osm.org.il/#!/17/31.8539/34.9739) (אדמה , רוח וארז)

**Comment by HarelM** [comment]
OSM, Off-road and Nakeb.
Those with the following button are from off-road, if you have any issues with it please contact them.
![image](https://user-images.githubusercontent.com/3269297/32299459-5792731e-bf5e-11e7-9f1d-ce1356b1679d.png)
Nakeb have this icon on top left corner:
![image](https://user-images.githubusercontent.com/3269297/32299526-a02e4d82-bf5e-11e7-9f1e-25545b205233.png)
Others without the button or the icon are from OSM and are also editable.
