### ISSUE TITLE
User defined shortest path

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#534]
## Feature
It would be nice to have an option to edit routes in a mode that minimizes other quantities and not necessarily the length of the route between the user placed waypoints. Alternative metrics can be elevation gain, max elevation difference, number of intersections, length of single tracks (first minimize single tracks length then minimize total length), length of 4x4 roads (same), and maybe steepness (needs a better way to measure it than the naive one). Ideally the user will be able to define any combination of these with given weights. A more realistic approach would be to give the user some predefined options.

**Comment by HarelM** [comment]
This is a duplicate/enhancement of issue #469.
See my answer there.
