### ISSUE TITLE
Save should download all non empty routes not just one

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#536]
## Bug/Feature
Not sure

## What I expect to happen
All routes in current IHM window should start downloading once save button is clicked on

## What really happened
Only one route is downloaded (the active one if there is one)

## What I did that caused the issue - step by step
Create more than one route
Save

## My environment
* Operating System and version:
Windows 10

* Web Browser and version:
Chrome 62.0.3202.75

**Comment by HarelM** [comment]
You have the save-as button which supports advanced options for saving multiple routes.
Our main use-case is that a user is working on a route and would like to save it and not the other routes.
![image](https://user-images.githubusercontent.com/3269297/32272694-db461da2-bf07-11e7-8e24-11b79e1ec7f4.png)

**Comment by oriori** [comment]
The first three gpx options in the save as menu download only the active route. The last gpx saves all routes to a single gpx file. None of the options saves each route to its own file. IIRC, That was the default save behavior in the past and is what I am asking for.

**Comment by HarelM** [comment]
Nope, sorry, this was never the default behavior. You couldn't save multiple routes to multiple files.
In any case this can be achieved by manually downloading each route. So I'm not sure I understand what you are asking.
Can you please describe a user scenario which you wish to improve/solve?

**Comment by oriori** [comment]
I wish to simplify the process of saving multiple routes to multiple files.
It can be a bit of a pain to do that manually. It is especially important
when sharing multiple routes using a single URL with users who are less
proficient with the site UI.
I will go further and say that IMHO it is far more useful to save all
routes at once to multiple files rather than each one separately. So I
would make the default behavior of the save button to be to save all
routes. If a user wishes to, it will still be possible to save only the
active route through the save as button.

**Comment by HarelM** [comment]
You can't download multiple files, just a zip file that contains multiple files, which, IMHO, is even more complicated than doing it manually.
Having said that, you still didn't provide a user scenario which makes sense.
Why would you send multiple routes? Why would someone received a share with multiple routes and decided to download all of them? If you want to share multiple routes why not send a zip file with all of them to your friend.
I truly don't understand why would some use this feature...

**Comment by HarelM** [comment]
Also I do not agree about the default behaviour - a user is editing a single route and it makes much more sense to save that route and not all of the routes, IMHO.

**Comment by oriori** [comment]
I didn't know you can't send multiple files. That makes this discussion
useless.
