### ISSUE TITLE
Add height gain statistics

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#54]
An important Stat for road cyclists is the accumulated climbing. It can be gleaned from the hight data and presented alongside the length Stat in the height profile. See groopy for discussion.

**Comment by HarelM** [comment]
How would you define gain?
```(Height start - Height end)``` Or ```Sum(Abs(Height between two sequential points))``` ?

**Comment by valleyofdawn** [comment]
Neither. Only positive gain counts.
[Cumulative elevation gain] (https://en.wikipedia.org/wiki/Cumulative_elevation_gain)

**Comment by HarelM** [comment]
OK, no problem, I'll add it no next release.

**Comment by valleyofdawn** [comment]
In excel, for an array of numbers at (a1:a7) this would work:
{=SUM(((A2:A7-A1:A6)+ABS(A2:A7-A1:A6))/2)}

**Comment by valleyofdawn** [comment]
Although total elevation gain (your first option) would also be useful.

**Comment by HarelM** [comment]
Just let me know what would make you guys happy, I can put both (total gain as linked in the wiki page and heights' delta - although the other way around: end - start).

**Comment by valleyofdawn** [comment]
Both please
