### ISSUE TITLE
Confirm before delete route from my shares

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#540]
## What I expect to happen
If a route is deleted from my shares there is currently no way to undo it. A confirmation dialog box would degrade the user experience, I think. Perhaps after taking an action in the my user window, like deleting a route, add a short small line of text at near the top of the window describing what happened and giving an option to undo it (a la gmail).

**Comment by HarelM** [comment]
The implementation of this feature is very complex and the benefit is very small.
Feel free to implement it and send a pull request, otherwise close it...

**Comment by oriori** [comment]
I will not implement it myself but before closing the issue maybe consider a simple alternative solution. Perhaps deleting should require two clicks. The first "unlocks" the delete button (with some visual change to the button) and the second actually deletes the route. Or Just add a confirmation dialog box after all if that's the simplest solution.

I think a quick fix is needed here. Sometimes a route url is shared with many people and in many places. Even if the original route can be recovered from a local file, the original url is lost and all references to the url must be updated.
A second issue is as the site advances and matures, users become more comfortable with using IHM as their main repository of route files. I for example, have several routes that I'm working on, saved only on the website through the share button without having a local backup copy.
Also, please note that right now the delete button is right next to the copy url button and can be pressed accidentally. Especially on a touch screen.

**Comment by HarelM** [comment]
Fair enough, I understand your point. I'll see what can be done.

**Comment by HarelM** [comment]
Didn't want to place a dialog over a dialog, this is the best solution I could think of:
![image](https://user-images.githubusercontent.com/3269297/33509550-50419a4e-d70b-11e7-95a5-7e3870481cf8.png)
