### ISSUE TITLE
Add preview to the share dialog

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#541]
## What I expect to happen
Show the thumbnail of a new share as part of the share dialog, before creating it.

## What really happened
You can only see the thumbnail after the share is created. In most cases, you would see it after the share was published.
For example, only after creating and publishing https://israelhiking.osm.org.il/#!/?s=ms5joClFaz I realized that the route is not in the center, and that the preview should zoom-in.

**Comment by HarelM** [comment]
Thumbnail is just for getting a feeling of what you shared it's not a "print-screen". 
Right now, not everything is rendered (for example markers) and changing the code would mean we'll need to write a small rendering engine which I think is too much effort for too little benefit.

**Comment by zstadler** [comment]
Of course it is not a print-screen. I can do print-screen of the map...

I'd like to see how the thumbnail would look on social media before posting it.
Once the share is created and posted, it is much more difficult to change its center or zoom level.

It would also be nice if the preview area will be the same as in Facebook. 
For example, this is a thumbnail as seen on "My Shares"

<image height="200px" src="https://user-images.githubusercontent.com/1304610/32349693-9ae81c14-c020-11e7-86c2-d4cc22a6ea7e.png">

This is the thumbnail of the same share as seen on Facebook:

<image height="135px" src="https://user-images.githubusercontent.com/1304610/32349918-5870d956-c021-11e7-93c3-683bc115ae0b.png">

(it is a 90x90px image stretched to 133x133px)

**Comment by HarelM** [comment]
Will add only a preview much like the image after sharing.
I'm not planning on supporting both images aspects as I don't have a clue how facebook decides to crop image nor I'm willing to try and guess, it can also change in the future which makes it breakable.
