### ISSUE TITLE
public routes POI converted to routes don't have altitude data in their route stats

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#543]
## What I expect to happen
See altitude profile in route stats

## What really happened
No altitude info for route

## What I did that caused the issue - step by step
Search for סינגל יחיעם
Click on סינגל יחיעם in the search results
Click on the + button in the public POI route window

## My environment
* Operating System and version:
Win 10

* Web Browser and version:
Chrome 62.0.3202.75

**Comment by HarelM** [comment]
Thanks for reporting! We'll take care of it in the next few days.
