### ISSUE TITLE
Close the layers window by clicking on the map

### ISSUE THREAD

**Issue by MatanBenMoshe** [IsraelHikingMap/Site#545]
## What I expect to happen
The layers window will be close by clicking on the map, not only by clicking on X

## What really happened
The window is closed just by clicking on X

![image](https://user-images.githubusercontent.com/17752588/32366989-2d998ff8-c089-11e7-8435-6323e8c41342.png)

**Comment by HarelM** [comment]
This is actually a non desired feature by people who want to keep this sidebar open while using the map.

**Comment by MatanBenMoshe** [comment]
OK. I didn't think of this point :)
