### ISSUE TITLE
Iframe icon doesn't link to the site

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#547]
Bug
What I expect to happen:
Pressing the icon would open a tab with the IHM site

What really happened:
It reloaded the map inside the iframe

What I did that caused the issue - step by step
Looked at the iframes in both groopy and Kfar Hanokdim

My environment:
Windows 10
Chrome

**Comment by zstadler** [comment]
I believe a `target="_top"` is missing from the link.
