### ISSUE TITLE
Iframe shows wrong area

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#548]
Bug
What I expect to happen:
The iFrame should have shown the relevant area using the bike map

What really happened:
It showed the last place I visited with the overlay I was using

What I did that caused the issue - step by step
Looked at the iframes in both groopy and Kfar Hanokdim
e.g. 
[http://groopy.co.il/trackinfo.aspx?pid=2117](http://groopy.co.il/trackinfo.aspx?pid=2117)
My environment:
Windows 10
Chrome

**Comment by zstadler** [comment]
Looks OK on firefox

**Comment by HarelM** [comment]
Looks good from my mobile device...

בתאריך 7 בנוב׳ 2017 11:27,‏ "zstadler" <notifications@github.com> כתב:

**Comment by HarelM** [comment]
I can't reproduce, please reopen if this happens again. 
Make sure this is not due to slow connection and site loading time.
