### ISSUE TITLE
No need for the default empty route

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#551]
Feature
Since clicking on edit route now automatically creates a new route when no route exists #539, there's no need for the default empty one. It only creates confusion when loading a route from file and having it listed as the second route.

**Comment by HarelM** [comment]
This is an interesting idea, thanks for your thoughts!
The question here is what will happen when there's no empty route in term of what is expecting a route to be created, But that can be easily verified when the app starts.
Another question is if this will be intuitive to a user - when there's no route, but I tend to think that pressing the pencil is as intuitive as it can get...

**Comment by zstadler** [comment]
Did you check that adding a POI, say from a search result, works when there is no route?
Currently, if there is no route, it does not work.

**Comment by HarelM** [comment]
I didn't. I'll make sure it works.
If you think of other scenarios that might be problematic let me know and I'll make sure this feature does not break them.
