### ISSUE TITLE
Complex relations from search are not presented correctly

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#554]
## What I expect to happen
Relations should be presented with all related ways

## What really happened
Only the first way is presented

## What I did that caused the issue - step by step
Searched for סובב מכתש רמון
opened the popup.

**Comment by zstadler** [comment]
This may be a different issue, but [סינגל בירה](http://www.openstreetmap.org/relation/2706443) is not fully presented as a search result.

OSM:
![image](https://user-images.githubusercontent.com/1304610/33034016-2dbb0a12-ce2f-11e7-8942-989650624cbc.png)

IHM:
![image](https://user-images.githubusercontent.com/1304610/33034061-52b9df96-ce2f-11e7-8f02-4e2d691e7e21.png)

The relation seems to be well-constructed single loop according to [OSM Relation Analyzer](http://ra.osmsurround.org/analyzeRelation?relationId=2706443&_noCache=on)

**Comment by HarelM** [comment]
As far as I can see from the investigation I made this is due to bad mapping of names in the ways.
The search preprocessor is removing the relation since it has a kkl operator tag but the ways are kept and joined. this is why it has the "street" icon which is a default icon for highways.
I prefer to fix the mapping and not the code when possible, I think it will be a better fix to the issue at hand.

**Comment by zstadler** [comment]
Duplicating the relation tags on relation members is bad mapping.
I suggest we do not relay or encourage this.
