### ISSUE TITLE
Improve databases update procedure

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#557]
## What I expect to happen
pbf file should be updated before every run and runs should be scheduled to once an hour without being related to map updates.

## What really happened
Current state is the the databases are updated using a pbf file that is downloaded from geobarik and changes once a day.

## Thing I think the developers should know, images, links etc.
Related to:
https://github.com/IsraelHikingMap/Map/issues/179

Also it might prove useful to pack all related software in a NuGet package to make it available to developers so the procedure can be tested locally.
In this case a detailed description of the relevant software is needed, where to get them and how to use them.

**Comment by zstadler** [comment]
The following programs need to be installed and included in the PATH:
- wget.exe - http://gnuwin32.sourceforge.net/packages/wget.htm
- osmup.exe - https://wiki.openstreetmap.org/wiki/Osmupdate#Download
- osmconvert.exe - https://wiki.openstreetmap.org/wiki/Osmconvert#Binaries
