### ISSUE TITLE
Route color isn't updated in route stats window

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#559]
## What I expect to happen
Route color in route stats window should route color in main window

## What really happened
Route color in route stats window isn't updated when updating route color in route properties window.

## What I did that caused the issue - step by step
Change a route color 
Open route stats window

## My environment
Win 10 
Chrome

## Thing I think the developers should know, images, links etc.
Currently the user can workaround this by setting another route to be the active one in the editor and then switching back to the original route.

**Comment by HarelM** [comment]
Thanks for reporting! will be taken care of in the next few days.
