### ISSUE TITLE
Keep centering the map after activating GPS

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#56]
Experienced on Mobile, perhaps also on Desktop. 

The position is centered only upon activation, but the position can easily move out of the visible area.

**Comment by HarelM** [comment]
I'll look into the locate control options and see what can be done with it...

**Comment by zstadler** [comment]
http://www.w3schools.com/jsref/met_win_setinterval.asp

**Comment by zstadler** [comment]
L.control.locate({ 
//... 
follow: false, // follow the user's location
//... 
})

**Comment by HarelM** [comment]
You are welcome to try it out and see if it works, my guess is that you wont be able to move the map around while this is on...

**Comment by zstadler** [comment]
This is probably controlled by
```javascript
    stopFollowingOnDrag: false, // stop following when the map is dragged if `follow` is true (deprecated, see below)
    remainActive: false, // if true locate control remains active on click even if the user's location is in view.
```
Full option list is available at
https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/README.md

**Comment by zstadler** [comment]
On second thought, I prefer keep re-centering the map while "locate" is active.
The user can inactivate the following and regain panning control.
Zooming in and out is possible even when "following"
