### ISSUE TITLE
Better management of user's private routes and POIs

### ISSUE THREAD

**Issue by ylivny** [IsraelHikingMap/Site#563]
## Feature

I believe that users that use the site over time will create multiple routes and POIs and would like the ability to store the items and load them in the future for editing/viewing. 
Supplying this ability will make the site a personal travel portal for some users.

Currently users can save their private routes and POIs by sharing them and then accessing the shared items under the "my shares" tab in the settings dialog. Each shared item may contain several routes and POIs.

While this option might be somewhat not intuitive, it provides a way to store your routes and POIs under ones account. However, it lacks several abilities that, IMHO, will improve the user experience of the site users.

My suggestions are:

1) **enable loading of the shared item into current map** 
currently shared items are opened in a new window which means that one cannot see multiple routes that belong to different shared items in the same map.

I suggest to add a View option to a shared item that will load all POIs and routes to the current window. Under the layers menu I expect all the POIs and routes of the shared item to be grouped (to distinct them from other routes with same name)

2) **replace "my shares" with "my places"**
Instead or in addition to the "my shares" tab, I would add a "my places" tab that will store private routes and POIs. The Save menu item will have an option to store the route/POI in "my places" instead of exporting it to a file.

**Comment by HarelM** [comment]
The ability to see a share on the map without opening a new tab is understandable.
I think grouping is an overkill and unwanted complexity.
I don't understand the definition of my places - how is it different than my shares? Save to file IMHO is more intuitive and wanted as the default save button action.

**Comment by ylivny** [comment]
I understand why grouping seems an overkill. Accepted.

Regarding the 'My Places' vs. 'My Shares' - I will try to explain.
As far as I saw, currently there are 4 ways to save a routes/POIs in the site:
1. Share - this will create a share-able link to the active routes/POIs and store it in the 'My Shares' list.
2. Save - will save a GPX file containing the selected route
3. Save from the route definition menu - save as Save
4. Save As - save single/all routes in several formats

I feel that the ability to store routes is 'hidden' behind the Share feature (and it is actually a side-effect of the share feature).

When a user just wants to store a route in its private routes list it is not natural to look for this ability under the Share option.
On the other hand, I understand why you do not want to add this ability to the Save options (which all result in file creation).

I would consider adding a new Store option (maybe only in the route definition dialog, to prevent overloading the main map).

Regarding how to access these stored routes - I suggest that routes stored by this new option will appear in a new 'My Places' or 'My Routes' tab.
Optionally, this tab can replace the 'My Shares' tab and contain all shared routes too (a route that was shared will have a link icon next to it. pressing it will open the route in a new tab).

**Comment by HarelM** [comment]
I understand the software requirements, but what I fail to understand in this case is the relevant user scenario this feature is designed to solve.
Most users as far as I can tell would like to do the following:
1. Plan a route and share it with their friends - hence the share button.
2. Plan a route and send it to some application - hence all the file saving options.

Just storing routes online is not something most users need, IMHO, and so a workaround to share a route suffices that need. 

I don't see another relevant user scenario that applies to **most** users - I don't understand why a user would like to just store a planned route online, without sharing or exporting to file.

Also another tab is not needed as far as I can see as it stores the same exact data.

**Comment by ylivny** [comment]
I see you point.

The user scenario I was thinking about relies on the assumption that some hikers need a platform to plan their hikes and store them for future reference. In a way it is a way to create a library of all past and planned hikes.

I know that I would have used this ability if I knew it exists (and if the IHM was available 10 years ago :-)).
I know of other people that look for such a platform.

I accept that the relevant user scenario does not apply to **most** users but I still think it worth considering, I understand that the priority of such changes is low.

**Comment by oriori** [comment]
Have a look at what goes on on gpsies.com. There are quite a few users that have libraries of routes. And it's better to manage them on the cloud than locally, I think. 
Also, Just like @ylivny said, I started managing my routes on IHM after realizing I can save them by sharing them. More users would do that if it wasn't a workaround hidden behind a different functionality.

**Comment by HarelM** [comment]
The following is the gpsies equivalent of IHM in terms of route planning.
I don't want to start criticizing it as the UX is just horrible, so let's not go there.
![image](https://user-images.githubusercontent.com/3269297/33529605-c281d404-d87b-11e7-82b0-e94e3bcdee6e.png)

Bottom line: I don't mind this being a hidden feature for now.
If, in the future, the default concept will be to store routes in the cloud and not download the route to file (for example if there was a supporting app so storing will automatically add the route to the app)  I'll consider changing it.

**Comment by ylivny** [comment]
Sounds reasonable.
I hope that the 1st item (loading of the shared item into current map) will get higher priority
