### ISSUE TITLE
Click on 'Edit route detail' for a specific route in 'My Shares' tab moves all routes to edit mode

### ISSUE THREAD

**Issue by ylivny** [IsraelHikingMap/Site#564]
## What I expect to happen
When clicking on 'Edit route detail' for a specific route in 'My Shares' tab I expect only this route details to be editable.

## What really happened
When clicking on 'Edit route detail' for a specific route in 'My Shares' tab all routes details become editable.

## What I did that caused the issue - step by step

1. share two route or more
2. open 'Me Shares' under the settings menu
3. click on 'Edit route detail' for a specific route

## My environment
* Operating System and version: Windows 7
* Web Browser and version: Chrome 62.0.3202.94

**Comment by HarelM** [comment]
Thanks for reporting! We'll try to solve this in the next few days.
