### ISSUE TITLE
Update to angular 5

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#565]
## Infra

Material and angular should be updated to 5, also other client side packages, angular-cli etc.

**Comment by HarelM** [comment]
Reopening due to issues with CI runs.

**Comment by IsraelHikingHost** [comment]
Not much else to do here - I've opened a bug for appveyor, I hope they'll have some ideas how to solve this out-of-memory issue.
https://help.appveyor.com/discussions/problems/10192-out-of-memory-when-using-angular-cli-15-angular-5

**Comment by HarelM** [comment]
Not much else to do here - I've opened a bug for appveyor, I hope they'll have some ideas how to solve this out-of-memory issue.
https://help.appveyor.com/discussions/problems/10192-out-of-memory-when-using-angular-cli-15-angular-5

**Comment by HarelM** [comment]
Resolved by #567.
Thank you very much @IlyaFinkelshteyn 
You just made me love open source a bit more :-)
