### ISSUE TITLE
zooming in/out in new beta version is visually unpleasant 

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#568]
## Bug/Feature 
I'm not sure

## What really happened
Switching between zoom levels in the map is now done a bit differently. Previously, the tiles of the current zoom level were resized and only after that the tiles of the new zoom level replaced them. In the new version, the tiles are cross-faded into the new tiles while the old ones are being resized. Personally, I find this effect disorienting and would much prefer the old transition between zoom levels. 

## What I did that caused the issue - step by step
https://israelhiking.osm.org.il/beta
Zoom in or out

## My environment
Win 10
Latest Chrome

**Comment by HarelM** [comment]
This functionality was not touched.
In any case, this is the behavior provided by leaflet and I'm not planning on changing it.
Thanks for reporting!
