### ISSUE TITLE
"null" is added to the name of every route in my shares

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#569]
## What I did that caused the issue - step by step
https://israelhiking.osm.org.il/beta
My shares

## My environment
Win 10
Chrome

**Comment by HarelM** [comment]
Can you please provide a screenshot?

**Comment by oriori** [comment]
![image](https://user-images.githubusercontent.com/8708384/33530497-35b9f64c-d889-11e7-8c39-baf4c205a106.png)

**Comment by HarelM** [comment]
Fixed in beta site.
