### ISSUE TITLE
Image is no longer available

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#572]
## Bug
An image uploaded to a POI is no longer available.

## What I expect to happen
When searching and selecting "מערת הקולומבריום, שמורת טבע חורש עדולם", I expect to see the uploaded image.

## What really happened
The image is broken:
![image](https://user-images.githubusercontent.com/1304610/33763898-e4e74b12-dc1a-11e7-85d3-98f8206a8b51.png)

## Thing I think the developers should know, images, links etc.
First reported in [changeset 52910710 discussion](http://www.openstreetmap.org/changeset/52910710)

**Comment by zstadler** [comment]
[The image is still available on Wikimedia](https://commons.wikimedia.org/wiki/File:Israel_Hiking_Map_%D7%9E%D7%A2%D7%A8%D7%AA_%D7%94%D7%A7%D7%95%D7%9C%D7%95%D7%9E%D7%91%D7%A8%D7%99%D7%95%D7%9D.JPG)

**Comment by HarelM** [comment]
Checkout the [image link in OSM](https://www.openstreetmap.org/node/3577493787) - it has a "_1" at the end.
This means that the original image was named מערת_הקולומבריום_1
When surfing to the following address the page gets redirected (it looses the "_1"):
https://commons.wikimedia.org/wiki/File:Israel_Hiking_Map_מערת_הקולומבריום_1.JPG
Might be the cause of this issue, I'm not sure...
I think that in this case it might be better to just update the OSM link...
My best guess is that this is some wikipedia code, not sure what I can do, any thoughts are welcome...

**Comment by zstadler** [comment]
The issue is about the site code, not the OSM data. In other words, what could be done by the site to prevent future links from breaking as all changes to OSM and WikiMedia data were done through the site.

It looks like the "_1" image was removed as duplicate: 

>  [10:00, 21 November 2017 JuTa (talk | contribs) deleted page File:Israel Hiking Map מערת הקולומבריום 1.JPG (Exact or scaled-down duplicate: File:Israel Hiking Map מערת הקולומבריום.JPG) (global usage; delinker log)](https://github.com/IsraelHikingMap/Site/issues/552)

Perhaps this was caused by an upload that did not result in a successful POI creation, followed by a successful attempt to add the same image to the POI.

To what extent is this scenario handled by https://github.com/IsraelHikingMap/Site/issues/552?

**Comment by HarelM** [comment]
Hopefully this should be prevented by #552 as the upload is now done at once.
