### ISSUE TITLE
Wrong names for routes with same name added to the map through the new 'My shares' > 'Turn to a Route' button

### ISSUE THREAD

**Issue by ylivny** [IsraelHikingMap/Site#574]
## What I expect to happen
If several shared routes with the same name exist in the My shares list and are added to the current map using the 'My shares' > 'Turn to a Route' button they should all have the name of the shared route (optionally with a counter)

## What really happened
The first route will get a correct name. Other will get 'Route N'

## What I did that caused the issue - step by step

1. create a route and name it as 'ABCD'
2. share the route (the generated share name will also be ABCD)
3. remove the route from the map
4. repeat steps 1-3 (with a different route)
5. open 'My Shares' and add one of the shared routes named ABCD to the current map (Turn to a Route)
6. do step 5 again
Result: the 2nd route that was added to the map got a generic name

## My environment
* Operating System and version: Windows 7
* Web Browser and version: Chrome 62.0.3202.94

**Comment by HarelM** [comment]
I think it's more of a feature than a bug, never-the-less this is a good input, thanks!
