### ISSUE TITLE
Bad behavior when description is too long

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#578]
## Bug
When the description field is over 255 characters 

## What I expect to happen
Success or UI should prevent me from doing mistakes

## What really happened
In my case - the image is uploaded but the OSM value does not get updated - error can be seen in the logs.

## What I did that caused the issue - step by step
1. Open POI
2. Edit POI
3. Added an image and a description that is more than 255 characters.
4. Click submit.

## Thing I think the developers should know, images, links etc.
Limiting the input is probably the best approach right now.
Bug was opened in OSM repository:
https://github.com/openstreetmap/openstreetmap-website/issues/1702

**Comment by zstadler** [comment]
@HarelM added [a comment](https://github.com/openstreetmap/openstreetmap-website/issues/1593#issuecomment-352124370) in issue https://github.com/openstreetmap/openstreetmap-website/issues/1593 about potential change of the 255 character limit.
