### ISSUE TITLE
Merging routes deletes POI

### ISSUE THREAD

**Issue by hagai-lvi** [IsraelHikingMap/Site#579]
## What I expect to happen
When I merge 2 routes, I expect all the POI I've added to both routes will exist after the merge

## What really happened
After merging 2 routes, the POIs were removed, and only the route was left

## What I did that caused the issue - step by step
1. Create a route with 3 "points" - start, middle, end
2. Create a POI in the route
3. Click the middle point of the route, and split the route in this point (the scissors icon)
> NOTE that after the split, the POI is still there
4. Click the same point again (Make sure you are in edit route mode) and select merge (the `+` icon)
5. The POI will be gone
## My environment
* Operating System and version: macOS Sierra 10.12.16
* Web Browser and version: chrome Version 62.0.3202.94 (Official Build) (64-bit)

## Thing I think the developers should know, images, links etc.
I was able to easily reproduce this multiple times, so I don't expect any problem reproducing it. I'd be glad to help.

**Comment by HarelM** [comment]
Thanks for reporting!
The fix will be published within the next few days.
