### ISSUE TITLE
Linking back from an iframe with a track should open it in IHM

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#580]
Feature

What I expect to happen:
[http://www.kfarhanokdim.co.il/attraction/%D7%A1%D7%99%D7%A0%D7%92%D7%9C-%D7%A0%D7%95%D7%A7%D7%93%D7%99%D7%9D-%D7%9E%D7%A1%D7%9C%D7%95%D7%9C-%D7%90%D7%95%D7%A4%D7%A0%D7%99%D7%99%D7%9D/]

When I clicked the IHM icon I expected it to show the featured track on the IHM site.

Instead it just jumped back to the site.

I suggest that using the icon would let me see and edit the track in the IHM site.

**Comment by HarelM** [comment]
Not sure I understand the last part.
In any case what I plan to do is use the link that was provided to the iframe and open it in a new ta, that's all - which means that if the user did anything inside the iframe, e.g. panning the map etc., these operations will be ignored and the new tab will open like the original iframe.

**Comment by valleyofdawn** [comment]
That would be good.

**Comment by valleyofdawn** [comment]
This feature stopped working in iFrames. Clicking the logo does nothing.
e.g. 
https://inature.info/wiki/%D7%A6%D7%95%D7%A7%D7%99_%D7%92%D7%93%D7%95%D7%A8_%D7%95%D7%97%D7%95%D7%A3_%D7%92%D7%93%D7%95%D7%A8

http://www.groopy.co.il/trackinfo.aspx?pid=2367

**Comment by HarelM** [comment]
Thanks for reporting. It appears to have stopped working after the mapbox migration.
