### ISSUE TITLE
Fail to upload a gpx file

### ISSUE THREAD

**Issue by BZST** [IsraelHikingMap/Site#581]
## Bug
(Delete the non-relevant)
When I click the "open file" option on the left, the file explorer opens as expected. When I choose a gpx file to open, the red line on top of the map page seems "as usual": running from left to right, but nothing is shown on the page (I expect to see the gpx track).

The gpx file is attached. Pls be aware that in the past it worked OK with this file.
[2017-10-11_07-11_Wed.zip](https://github.com/IsraelHikingMap/Site/files/1585045/2017-10-11_07-11_Wed.zip)

## My environment
* Operating System and version:
* Web Browser and version:

**Comment by HarelM** [comment]
Thanks for taking the time and reporting!
This issue happens because the route has no name.
It will be fixed in next release.

**Comment by BZST** [comment]
Thanks for your reply. Obviously the gpx file itself has a name. So I assume you mean that yet another name - independent of the file name itself - must be assigned somehow. Pls explain how I can assign such a name.

Thanks

**Comment by HarelM** [comment]
Is it urgent? If you can wait for a day or two I'll just upload a fix to solve this, if not let me know and I'll send you a file that will work...

**Comment by BZST** [comment]
Oh no, absolutely not. I was just curious what it practically means that "the route has no name". Its not urgent. I will wait.
Anycase, MANY thanks for the great job you and your friends are doing!!!

**Comment by HarelM** [comment]
When looking at the gpx file with a file editor (I like Notepad++) the following `trk` element does not have a child `name` tag but only a child `trkseg` tag, so when the site tries to manipulate this name it fails - the issue was introduced as part of #574 feature.
![image](https://user-images.githubusercontent.com/3269297/34450684-cc4e4af6-ed18-11e7-9653-4ecfef556a6d.png)
