### ISSUE TITLE
A specific MTB trail isn't recognized as such

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#584]
## Bug

https://israelhiking.osm.org.il/#!/?s=cNC2BWOkZ6

Trying to build a route that passes through Gaada single, the website treats it as an off-trail area. There's no problem with hiking routes passing through there (In the link, change the endpoint to hiking mode). Looking at the OSM data for the trail and comparing to other nearby singles, there are no differences in labels and tags that should cause this one trail to behave differently. The only tags I haven't seen on other MTB trails is the hiking difficulty and the sac_scale.

**Comment by HarelM** [comment]
Thanks for reporting!
This seems to be an issue with GraphHopper:
Here's a test I made on the OSM regular site to see the results there which shows a similar issue.
I'll contact GH to see what they have to say.
![image](https://user-images.githubusercontent.com/3269297/34435595-8570c568-ec97-11e7-9015-510daeca70e5.png)

As a workaround for now, you can switch to hike-navigation for this section and continue bike-navigation on the next section.

**Comment by HarelM** [comment]
We might need to switch to "mtb" profile instead of using bike2 profile.
In any case you are correct as this is a result of the `sac_scale` tag.

**Comment by HarelM** [comment]
@valleyofdawn @zstadler What do you say about changing the routing from bike2 to mtb as the default routing for bikes?
bike2 is bike routing with elevation consideration while mtb is for mountain bike (which I think is without elevation consideration).
Changing to mtb will solve this issue.

**Comment by valleyofdawn** [comment]
For some reason the mtb mode prefers tracks over designated bicycle paths. that's no good. see here:

[https://graphhopper.com/maps/?point=31.659577%2C34.972092&point=31.653228%2C34.991498&locale=en-US&vehicle=bike&weighting=fastest&elevation=true&use_miles=false&layer=OpenStreetMap](url)

**Comment by HarelM** [comment]
I see. I don't have a good way of solving both issues. @valleyofdawn can you open an issue for GraphHopper describing this issue, let's see what they say...

**Comment by zstadler** [comment]
I believe this issue can be solved with a new Graphhopper profile. This is similar to the discussion we had with @citizen-dror at https://github.com/IsraelHikingMap/Map/issues/136

@valleyofdawn wrote:

> For some reason the mtb mode prefers tracks over designated bicycle paths. that's no good. see [here](https://graphhopper.com/maps/?point=31.659577%2C34.972092&point=31.653228%2C34.991498&locale=en-US&vehicle=bike&weighting=fastest&elevation=true&use_miles=false&layer=OpenStreetMap)

Here is what I found about the the profiles. It seems like each of the existing profiles has some drawbacks.

* The bike and mtb profiles are based on an abstract "BikeCommon" profile.
* The bike2 is based on the bike profile and [reduces the speed on inclines and declines](https://github.com/graphhopper/graphhopper/blob/196aac2dc8b113071be627adcd3572ed0b5b0140/core/src/main/java/com/graphhopper/routing/util/Bike2WeightFlagEncoder.java#L148-L150). They are equivalent in any other way. 
* The mtb profile does not have elevation-based speed adjustments
* The bike and bike2 profiles allow only "hiking" sac_scale while the mtb profile allows "hiking", "mountain_hiking", "demanding_mountain_hiking", and "alpine_hiking" sac scales.
* The mtb profile has different handling of some road types as well as differences in speed definitions.

| highway tag | bike, bike2 profiles | mtb profile |
|---|---|---|
| service, tertiary, tertiary_link, residential, unclassified | prefer | prefer|
| road, track | - | prefer |
| path | pushing | prefer |
| footway, pedestrian, steps, tracks with grade2-grade5 | pushing | - |
| trunk, trunk_link | avoid | - |
| primary, primary_link, secondary, secondary_link | avoid | avoid |

Note:
* The different handling of "path" 
* All profiles have a preference for "service", "tertiary", "tertiary_link", "residential", and "unclassified" roads.

**Comment by valleyofdawn** [comment]
It seems like the MTB profile could do much better.
Speed doesn't mater that much - you want to maximize the fun, not minimize your time out
Elevation doesn't matter.
Path should be pushed over track (though it depends on what MTBiker you are)
Footway should be avoided
bicycle=designated should be preferred over bicycle=yes which should be preferred over bicycle=? 
Belonging to a route=mtb relation should be pushed (I don't know if the algorithm can handle relations)

**Comment by zstadler** [comment]
@valleyofdawn,

Speed is essential for Graphopper routing. This is how the different roads are compared. To maximize the fun, you can use the "prefer", "pushing", "avoid" and normal categories.

By the way, "pushing" is a term used to by Graphhopper describe walking with the bike, similar to bicycle=dismount. It is not about increasing the priority.

**Comment by HarelM** [comment]
@zstadler I'm assigning this issue to you as well to be taken care of along side #621.
Feel free to keep only one issue open with all the requirements or keep it as is, whichever suites your needs.

**Comment by HarelM** [comment]
Closing in favor of #640
