### ISSUE TITLE
Info isn't displayed when hovering over route

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#585]
## What I expect to happen
Tooltip like window to appear in the route stats window showing the distance, altitude and grade at current position. 

## What really happened
Tooltip doesn't appear or appears only once.
The tooltip only appears when hovering over the elevation profile, not when hovering over the route.

## What I did that caused the issue - step by step
Create a route.
Open route stats
Hover over route

## My environment
Win 10
Chrome

## Thing I think the developers should know, images, links etc.
Only in latest version, I think.

**Comment by HarelM** [comment]
Thanks for reporting! I'll try and see why it stopped working.
