### ISSUE TITLE
 Galileo Offline maps

### ISSUE THREAD

**Issue by gillss** [IsraelHikingMap/Site#586]
## Feature
SqliteDB for Galileo Offline maps

## What I expect to happen
Your site has great support for Android users, but we IOS people feel neglected.
Can you please add  SQLiteDB file for GALILEO in the download area?
MOBAC and SASPLANET get a lot of errors trying to download tiles (especially on zoom 16)  

It would be especially nice, if we could be able to download a file you built for us
I believe preparing such a file will reduce the need for massive downloads from the site.

Thank you in advance (for making the IOS people more happy)
Gill

**Comment by HarelM** [comment]
Needs to be done in the map repository first.
https://github.com/IsraelHikingMap/Map/issues/189
Regardless - how does one make the application download the map? Do we need to contact Galileo in order to add a map there?
Also we don't have an iPhone so we can't test it - if you can't help us with the tests we won't proceed.

**Comment by gillss** [comment]
Galileo app have wonderful Feature to transfer data file via itunes to Iphone folder.
all we have to do is to get the sqlitedb file (downloaded to PC) and transfer it to the phone via itunes.
MOBAC has the ability to create a sqlitedb from your tiles (it is The wonderful ability you gave us) The problem so far is downloading from your site.
There are a lot of errors in the download process.
If you make such a file with MOBAC localy for us, and place it in the download area, 
every IOS user will thank you. 
I would be very happy to be a beta tester for you.

thank's again
Gill

**Comment by gillss** [comment]
Another small matter.
Galileo App has an Android application that works exactly like the iPhone.
So Android users can also choose whether to use ORUXMAPS or GALILEO APP.
If you agree to produce such a file for us.

**Comment by HarelM** [comment]
Thanks for the info.
Let's continue the discussion on the Map repository.

**Comment by HarelM** [comment]
Closing this as well after the discussion in the map repository.
