### ISSUE TITLE
Cannot add point by coordinates to route

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#587]
## What I expect to happen
After finding a point by coordinates I expect the "+" button to add it to the current route

## What really happened
A new point is not added.

## What I did that caused the issue - step by step
1. Search for "32 32"
2. Click on the search result
3. Click on the "+" button

## My environment
* Operating System and version: Win 10 home
* Web Browser and version: Firefox 56.0.2 (64-bit)

## Thing I think the developers should know, images, links etc.

![image](https://user-images.githubusercontent.com/1304610/34468957-b22a4232-ef1c-11e7-94a7-c3c131bfcc10.png)

**Comment by HarelM** [comment]
Problem with empty poi extended object:
```js
 public addPointToRoute() {
...
this.routesService.selectedRoute.route.markers.push({
            latlng: this.latLng,
            title: this.title || this.description,
            type: icon.replace("icon-", ""),
            id: this.poiExtended.id,
            marker: null
        } as IMarkerWithData);
```
