### ISSUE TITLE
Bugs in height profile box

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#59]
Max diff should be negative when it’s a decent
Height profile is missing the X coordinates
Height profile stops at 10 Km

**Comment by HarelM** [comment]
See issue #61.

**Comment by HarelM** [comment]
Please send an example route.

**Comment by valleyofdawn** [comment]
I couldn't recreate the 10 km problem.
the missing x axis is always there for me. only ''1'' appears on the axis.

**Comment by HarelM** [comment]
Can you share a route for example? The x axis is in round km, if the route is less than 1 km the only thing you would see is 1. Might this be the problem?

**Comment by valleyofdawn** [comment]
No, it happens in all of them. long ones too.

**Comment by valleyofdawn** [comment]
2 more problems.
the height profile doesn't work for polygons.
If you switch to a different route and the go back, the profile would freeze even if you add dots.

**Comment by HarelM** [comment]
@valleyofdawn please send a route.
I'll open another issue on elevation - I currently set elevation for manual points as 0.

**Comment by valleyofdawn** [comment]
[route] (http://osm.org.il/IsraelHiking/PreProduction/#/14/30.2801/34.7361?markers=&Route_1=h,30.2879,34.7442;h,30.2604,34.6881)
![screenshot 2015-08-18 14 12 28](https://cloud.githubusercontent.com/assets/689201/9328656/385ba62c-45b3-11e5-91f3-208a2e4f36f0.png)

**Comment by HarelM** [comment]
Oh, I see now, I'll fix it tonight. This is happening because I changed the route length to be text instead of a number. Thanks for spotting this!

**Comment by HarelM** [comment]
I saw the 10 km issue just now after the fix.
