### ISSUE TITLE
Allow images on private POIs

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#590]
## Feature
 * I would like to be able to copy a public POI and that the relevant image will be copied as well.
 * I would like to be able to upload an image to a private POI.
 * I would like to be able to share it so that other will be able to see it.
 * I would like to be able to save the file and open it and that the image will be kept as well.

## Thing I think the developers should know, images, links etc.
There are two options to save the image in gpx file:
1. as a link
~2. as base64~
Since I don't think it's a good idea to store all the images in our servers a possible solution for this would be to store the private images in imgur.
Also storing this as base64 will increase the GPX size dramatically.
This might facilitate somewhat for issue #404.

Still need to think how the read only mode of these POIs should look like.

**Comment by HarelM** [comment]
Initial preview for edit mode:
![image](https://user-images.githubusercontent.com/3269297/34695906-47f3fe62-f4d5-11e7-8f02-f6fcaf3b50c4.png)

I'm using exiting GPX elements to store the image and the description so the user can export and import this with ease.

I have yet to facilitate for image upload and I do not wish to use wikimedia common in this case as these are private POIs, but the user would need to upload the image somewhere - probably imgur.

Readonly mode is still needed.

**Comment by HarelM** [comment]
Closing this as main development was done.

**Comment by zstadler** [comment]
When importing a POI from the search results, and the POI layer is not visible, the search result marker is always visible behind the imported POI:
![image](https://user-images.githubusercontent.com/1304610/34944756-7bb6c642-fa09-11e7-8bc3-7ad18d342da8.png)

Needless to say that the search result marker is inaccessible. I suggest that the search result marker will be removed after the import.

**Comment by HarelM** [comment]
I agree, this will only affect search results thought.
Can you open a different issue for this? I'll have easier time to manage it that way...

**Comment by zstadler** [comment]
@HarelM I've created a new issue and deleted my comment above. Please feel free to delete this comment and your comment above

**Comment by HarelM** [comment]
Thanks! I'll take it from here.
