### ISSUE TITLE
Adding a "place" area adds a route around its perimiter

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#591]
## What I expect to happen
When selecting a "[place](https://wiki.openstreetmap.org/wiki/Key:place)" from the search results list and then adding it to the private layer, I expect the place to  be added as a POI regardless if this place is an OSM node, an area, or both of them. 

## What really happened
When a place is defined as an area, its perimeter is added as a closed route. IMHO, such a route is useless. In most cases, there is no path or road for this new route.

## What I did that caused the issue - step by step
1. Search for [יפתח, מועצה אזורית גליל עליון](https://israelhiking.osm.org.il/#!/?q=יפתח,%20מועצה%20אזורית%20גליל%20עליון)
2. Click on the "+" button

## My environment
* Operating System and version: Windows 10 Home
* Web Browser and version: Firefox 56.0.2 (64-bit)

## Thing I think the developers should know, images, links etc.

There is no path that allows you to walk this circular route:

![image](https://user-images.githubusercontent.com/1304610/34647134-d95e96d6-f382-11e7-8dc3-40eb6439a39e.png)

If יפתח was added as a POI, the POI can later be used to build the user's own route that visits the place.

**Comment by HarelM** [comment]
One can argue this is the definition of this place.
Other "less wanted" search results can be fetched when searching for "עמק זבולון" for example.
But, I don't want to start a philosophical argument, so let's talk about it next time we talk on the phone.

**Comment by zstadler** [comment]
Similarly, for [אנדרטת הר הטייסים](https://israelhiking.osm.org.il/#!/?q=אנדרטת%20הר%20הטייסים). The added route looks like a red point even in zoom 19:

![image](https://user-images.githubusercontent.com/1304610/35404403-853b3d7e-020b-11e8-926f-e752ebaabd10.png)

Moreover, it is hard to understand from the search result that this is a route, not a POI

![image](https://user-images.githubusercontent.com/1304610/35404551-0b1853f0-020c-11e8-9cb9-9ba911562e7f.png)

**Comment by HarelM** [comment]
To summarize the phone conversation:
IHM is not designed to facilitate for areas download and so everything that is considered a POI by tags or areas should be able to be converted to POI and not a route.
A possible enhancement would be to show the area on the map as a transparent polygon so that the user will know this is the relevant area.

**Comment by HarelM** [comment]
Another issue with the fact that POI are returned as area is the fact that they can't be "advanced edited" - only changing the description is possible.
The original limitation comes from the fact that a route doesn't have a proper icon and advance editing it will cause incorrect tagging to be added - this needs addressing too...

**Comment by HarelM** [comment]
Here's a screen shot of how it will look:
There's still some work to do in order to make it work well.
![image](https://user-images.githubusercontent.com/3269297/35744653-8fbc37be-0849-11e8-89c9-6b9589a94aa0.png)
