### ISSUE TITLE
Sort routes and maybe maps

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#594]
Feature request

When planning a multiple-section route, the order and names may end up not consecutive in the list.
(If you import, split, etc).
It would be useful if we could drag them around to tidy things up.
Similarly, I have many basemaps in my list, I'd like to order them alphabetically.

ArcGIS implements this nicely:
![image](https://user-images.githubusercontent.com/689201/34810767-03df8098-f6a6-11e7-9e4e-f674d047b50a.png)

**Comment by HarelM** [comment]
Base layers is a bit more tricky since the top 3 should always be the default ones so I'm guessing I won't be implementing it. Routes are easier I guess.
In any case this is a very low priority feature since it doesn't affect the majority of the users.

**Comment by HarelM** [comment]
Bare in mind that I did minimal testing on this, @valleyofdawn I suggest to better QA it after I publish.

**Comment by valleyofdawn** [comment]
Works perfectly.
Perhaps give the user a clue that this feature exists.
Change the cursor to a 4-way arrow when hovering? Add a handle you van drag on the side?

**Comment by HarelM** [comment]
Not sure I like it, let me know if it feels too much for you as well, it's super easy to change if needed.
