### ISSUE TITLE
Hebrew tooltip on 4wd auto-routing button is jumbled

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#595]
Instead of ניווט 4×4 it reads ניווט 4x4
Using the mathematical symbol × instead of a lower case X seems to do the trick

**Comment by HarelM** [comment]
Feel free to update the translating then, I'll pick it up next time I publish.

**Comment by valleyofdawn** [comment]
The Zanata IHM project is read-only to my user. Please send me the username and password privately

**Comment by HarelM** [comment]
I've added you as a maintainer, feel free to fix other translations as well...

**Comment by valleyofdawn** [comment]
closed
