### ISSUE TITLE
Tooltip on MTB Singles

### ISSUE THREAD

**Issue by YGMZ** [IsraelHikingMap/Site#596]
## Bug
expected: tooltip will show the definition required on OSM in order to display the path's color
observed: shows wrong or partial definition (example: blue single defined by mtb:scale = 1 or 3, but tooltip shows 2 or 3)
see photo in following link:
https://drive.google.com/file/d/0BwKVGChbqrLtYTB3NUtWbnFpOTFvYWN5VDVjazhwcURVU0FV/view?usp=sharing

**Comment by HarelM** [comment]
@valleyofdawn please supply with an updated legend locations for this issue.
Regardless, Legend will be kept partial as it was designed to highlight the relevant tagging needed and not all of them.

**Comment by valleyofdawn** [comment]
The legends and locations are good for both Hebrew and English. It's just the tooltips that don't match the definitions.
For Moderate it should read mtb:scale=1
For Advanced it should read mtb:scale=2/mtb:scale=3
For Challenging it should read mtb:scale=4/mtb:scale=5
