### ISSUE TITLE
Legend icons disappear on second use

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#598]
Bug

When I click a category in the legend, then close it, then open it again, the thumbnails remain blank. 
Affects both maps.
Latest chrome on win 10
Also chrome on Android

**Comment by HarelM** [comment]
Related to a previous check-in I made... :-/
@valleyofdawn it could help a lot if you could change the file I checked-in (or send a pull request) and add the relevant links to the relevant OSM wiki page.
There's an example with quarry that has the following link:
http://wiki.openstreetmap.org/wiki/Tag:landuse%3Dquarry
