### ISSUE TITLE
Allow creating private POI from image with location

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#599]
## What I expect to happen
When I open an image or drop it onto the map the image will create a private POI with the image already inside.

## What really happened
The POI is created but the name is a temp file name and the image is lost.

**Comment by zstadler** [comment]
How does this differ from #494?

**Comment by HarelM** [comment]
Up until now, the user was not able to add images to private POIs but only create POI from images.
You can check-out the current behavior, which is very limited: the user can open an image and a private POI is created, but this POI doesn't have any interesting data except the location the image was taken.
This issue should improve this experience by creation a private POI **with** an image at the relevant location.
Also I don't like the concept of updating a POI location due to an image upload is a required feature/behavior so I decided not to implement it in regards to #494.

**Comment by HarelM** [comment]
While working on this issue I see that the concept of opening an image is creating a new route every time.
I don't think this is a great UX - if I drag an image to the map I would like to add it to the current active route and not create a new route.
I think this concept can be extended to files that contain only POIs - meaning these POIs will be added to current route instead of creating a new route.
