### ISSUE TITLE
Cannot add multiple images to a new public POI

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#603]
## My environment
* Operating System and version: Android 8.0
* Web Browser and version: Firefox

This scenario was not tested on desktop

**Comment by HarelM** [comment]
Multiple images can only be added through the advanced upload dialog.
Please elaborate what steps you tried to do to advice this.

**Comment by zstadler** [comment]
1. In "POI edit" mode click on the desired place
![image](https://user-images.githubusercontent.com/1304610/35039314-27e1a360-fb86-11e7-94b2-892ef5e15932.png)

2. Click "Upload POI" (notice the missing "Add Picture" image)
![image](https://user-images.githubusercontent.com/1304610/35039361-4cd17bb4-fb86-11e7-8bce-a58ccae326bc.png)

3. Add a picture with the "+" button
![image](https://user-images.githubusercontent.com/1304610/35039489-b6ee0d46-fb86-11e7-9fda-5be9cdb0a05f.png)

4. Click the "+" button and add another picture
![image](https://user-images.githubusercontent.com/1304610/35039754-81b308d8-fb87-11e7-80b6-2c1f28202f9c.png)

5. Move to the right and left with the ">" and "<" buttons and notice that the previous picture is not available.
![image](https://user-images.githubusercontent.com/1304610/35039905-f1261cd2-fb87-11e7-8a20-35e6de7b1d70.png)

Note: The above was reproduced on the desktop. 

When uploading, only one picture is added to the public POI.
