### ISSUE TITLE
Arrow keys do not scroll the map in "POI Edit" mode

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#605]
After a POI is added, the arrow keys stop working.

**Comment by HarelM** [comment]
Make sure the map has the focus. closing a popup makes the map loose focus for example.
Clicking on the map when not in edit mode restores focus.

**Comment by HarelM** [comment]
Also sorry, not planning on fully supporting tmap movement keyboard feature, I did the minimal effort to allow this as part of another feature and am not planning to spend time maintaining it...
