### ISSUE TITLE
Elevation gain and loss

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#61]
Best would be to have 3 statistics:
Ascent, Descent, Total
Were Ascent-Descent=Total

**Comment by HarelM** [comment]
How would I calculate each?
Ascent = max height - start point?
Decent = absolute of (start point - min height)?
Total = (max height - min height) (+-sign according to who's first)?

**Comment by valleyofdawn** [comment]
No, ascent is what you have now as gain. total is what you have now as total dif, and descent should be your difference.
Thus if you climbed a 100 m and descended 40, your total should be 60.

**Comment by HarelM** [comment]
This doesn't make sense to me, total and ascent are working in different scales. Reducing one from the other had no mathematical meaning.
What might make sense is gain, descend which will be the opposite of gain (summing downhill) and total will be the difference, although I'm still not sure the total will tell you something...

**Comment by valleyofdawn** [comment]
it does make sense if descent is by definition a negative number.
in a circular route total should always be 0. Say 145 + (-145) = 0
Maybe total should be called something else, like absolute difference.

**Comment by valleyofdawn** [comment]
.. but if you want to get serious about it you can add lowest point, highest point, elevation difference between these two, and average grade (in %)

**Comment by HarelM** [comment]
Adding data is easy, I don't want to overwhelm the user with it. I'll add descend calculation like gain but only for downhill. I think this will be enough for now...

**Comment by valleyofdawn** [comment]
Good.
