### ISSUE TITLE
העיר העתיקה של ירושלים מופיעה תחת שם עיר בערבית

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#611]
![image](https://user-images.githubusercontent.com/1304610/35051313-9f9d3258-fbad-11e7-8de1-86ce4dc4f00b.png)

The Arabic name "الحي الإسلامي" translates to "Muslim Quarter" which probably comes from https://www.openstreetmap.org/relation/5862585.

![image](https://user-images.githubusercontent.com/1304610/35051882-e6486262-fbae-11e7-8c32-666c7414b4e4.png)

1. The "Muslim Quarter" relation is admin_level=10 - a neighborhood. I think we need to use admin_level=8 - Municipalites (cities), Local Councils, Regional Councils - or higher
2. Relation 5862585 has a name:he tag which was not used.

**Comment by HarelM** [comment]
Regarding 1:
Please take a look at the following function and let me know how you think it should be changed:
https://github.com/IsraelHikingMap/Site/blob/cad8f03b7c4b2fa2ac43c71f4053a9ddd6bd23a3/IsraelHiking.API/Executors/OsmGeoJsonPreprocessorExecutor.cs#L231
This function determine which features can be considered containers, later it orders them by area size and uses the smallest area that contains another feature to be used as the location (after the , in the results).

Regarding 2:
Search results prefer `name` and `address` (address is a generated tag using the above mechanism) tags in Hebrew and `name:en`, `address:en` in English.
Code can be seen here:
https://github.com/IsraelHikingMap/Site/blob/8ab7738c262cd289fed26f1635f0af5c1ce7f10e/IsraelHiking.Web/sources/application/services/search-results.provider.ts#L48
If you think this logic should be fixed let me know how and I'll gladly fix it.

**Comment by zstadler** [comment]
1. I suggest that https://github.com/IsraelHikingMap/Site/blob/cad8f03b7c4b2fa2ac43c71f4053a9ddd6bd23a3/IsraelHiking.API/Executors/OsmGeoJsonPreprocessorExecutor.cs#L252 is changed to
    ```
    (feature.Attributes.GetNames().Contains("boundary") && feature.Attributes["boundary"].ToString() == "administrative" &&
     feature.Attributes.GetNames().Contains("admin_level") && feature.Attributes["admin_level"].ToInt() <= 8) ||
    ```
    _Note:_ `ToInt()` above is probably incorrect

2. The code at https://github.com/IsraelHikingMap/Site/blob/8ab7738c262cd289fed26f1635f0af5c1ce7f10e/IsraelHiking.Web/sources/application/services/search-results.provider.ts#L47-L48 seems to indicate that `properties.address` was set to the Arabic `name` rather than the Hebrew `name:he`.

**Comment by HarelM** [comment]
Can you elaborate on 2?
`address` is copied from the`name` of the container area
`address:he` is copied from the`name:he` of the container area
`address:en` is copied from the`name:en` of the container area
assuming they exist.

**Comment by zstadler** [comment]
The code for `address` should be:
```
let address = isHebrew
 ? feature.properties["name:he"] || properties.name
 : feature.properties["name:en"] || properties.name;
```

BTW, similar code exists in `private getName()` at https://github.com/IsraelHikingMap/Site/blob/8ab7738c262cd289fed26f1635f0af5c1ce7f10e/IsraelHiking.Web/sources/application/services/search-results.provider.ts#L61-L63 However, the above code gives `name` precedence over `name:he`.  This could cause similar issues when `name:he` exists and `name` is not in Hebrew. Please consider correcting the precedence in  `private getName()` too.

**Comment by zstadler** [comment]
@HarelM,

BTW, since https://github.com/IsraelHikingMap/Site/blob/8ab7738c262cd289fed26f1635f0af5c1ce7f10e/IsraelHiking.Web/sources/application/services/search-results.provider.ts#L33 is it possible to rewrite the above code as
```
let address = isHebrew
 ? properties["address:he"] || properties.address 
 : properties["address:en"] || properties.address ;
```
?

**Comment by zstadler** [comment]
The [OSM wiki](https://wiki.openstreetmap.org/wiki/Relation:boundary#Relation_members) says that the "subarea" role is
> __Optional, disputed and redundant__

It is therefore safe and better to ignore all "subarea" members.

**Comment by HarelM** [comment]
If that is the case, it will be better to fix the mapping, IMHO.

**Comment by zstadler** [comment]
"deprecated" is not "forbidden". You are welcome to change the map. I hope this will not start an edit war.

**Comment by HarelM** [comment]
Added a post in OSM Israel forum, will change the relevant code according to your suggestions.
https://forum.openstreetmap.org/viewtopic.php?id=61082

**Comment by HarelM** [comment]
@zstadler is it correct to update the test for valid container for: 
places that has a place tag, are area and do not have a boundary tag?
for example this one:
https://www.openstreetmap.org/way/91312345

**Comment by zstadler** [comment]
I don't know. This may create duplications. For example, a place tag on the residential area and an administrative boundary.

**Comment by HarelM** [comment]
I don't think there's an issue of duplication here since this is just the list of containers that can be used to test if an element is inside them (the smallest container is used for the address field of the element). The questions here, according to the example above, is if `place` tag can be considered a valid container which won't create the bug in this issue.
In other words - I'm looking for a condition to define a settlement.
The above condition that we started from:
```
(feature.Attributes.GetNames().Contains("boundary") && feature.Attributes["boundary"].ToString() == "administrative" &&
 feature.Attributes.GetNames().Contains("admin_level") && feature.Attributes["admin_level"].ToInt() <= 8)
```
Does not capture small settlements such as this:
https://www.openstreetmap.org/way/91312345
So I though about adding a check for `place` tag as well.
Do you think it is a correct check in terms of OSM tagging to achieve what we want?

**Comment by zstadler** [comment]
The place tag can be used for areas. 
However, you need to select the applicable values. Similar to the admin levels, For example, I don't think we want to go have suburbs and neighborhoods as containers.

**Comment by HarelM** [comment]
@zstadler feel free to review my last commit, let me know if it needs any modifications.
