### ISSUE TITLE
Cannot find cause for self-intersecting MultiPolygon error

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#612]
The site DB update log has the following error:

```
2018-01-17 16:25:31.8773 |119 |ERROR| MultiPolygon with ID: 5862586 Self-intersection (35.2257013,31.7784121) 
```

This is the location of [node 29944345](https://www.openstreetmap.org/node/29944345), which is part of the [Old City relation 5862586](https://www.openstreetmap.org/relation/5862586) and I could not find any self-intersection there.

[OSM Inspector](http://tools.geofabrik.de/osmi/?view=geometry&lon=35.23134&lat=31.77759&zoom=15&opacity=0.67&overlays=self_intersection_ways,self_intersection_points) does not report any self-intersecting ways in this area.

Potentially, this the error is cause by some interaction with the "subarea" members of the "Old City" relation:

- Relation Armenian Quarter (5862581) as subarea
- Relation Jewish Quarter (5862583) as subarea
- Relation Muslim Quarter (5862585) as subarea
- Relation Temple Mount (5862584) as subarea
- Relation Christian Quarter (5862582) as subarea

IMO, unlike other members of relations, subarea members should not be considered part of the relation's geometry.

**Comment by zstadler** [comment]
Another unexplained self-intersecting relation error is:

```
2018-01-17 16:25:32.9242 |119 |ERROR| MultiPolygon with ID: 1638363 Self-intersection (34.915475,31.818752) 
```

This is the location of [node 1338676995](https://www.openstreetmap.org/node/1338676995), which is shared by two adjacent closed ways which are members of the multipolygon: [way 128007774](https://www.openstreetmap.org/way/128007774) and [way 126392094](https://www.openstreetmap.org/way/126392094).

**Comment by HarelM** [comment]
The OSM preprocessing is doing the following steps:
1. Group OSM elements by name, for all the lement with the same name:
2. Remove ways that are part of a relation that carries the name of the relation.
3. Take all the ways from a relation recursively (including sub-relations) and try to merge them into as little geometries as possible.
4. build from the merged ways geometries geojson shapes such as MultiPolygon etc. which creates the issues you mentioned above.

While ignoring subarea is probably simple enough to include in the algorithm I'm not sure what to do with the forest issue...
Looking at the relation I tend to think it is not a valid shape as I would expect an inner and outer shapes for the following area:
![image](https://user-images.githubusercontent.com/3269297/35072315-b5218108-fbec-11e7-82f7-2611d4f576e0.png)
In any case, any ideas on how to solve this (preferably without making this algorithm too specific) will be appreciated.

**Comment by zstadler** [comment]
The two small gaps between the above ways were a mapping error which I've removed. There is no longer a need for inner members. Let's see if this edit avoids the error.

BTW, [Way 128007774](https://www.openstreetmap.org/way/128007774) and [way 126392094](https://www.openstreetmap.org/way/126392094) are both outer members of the same relation. They have different tags and therefore one cannot merge them to a single outer member.

**Comment by HarelM** [comment]
Can I close this issue? I'm not sure what I need to do here...

**Comment by zstadler** [comment]
There are two corrections to be made in the The OSM pre-processing:
1. Build the multi-polygons' geometry using only "inner", "outer", and empty roles. No other role, including "admin_center", "subarea", or a role someone invented, should impact the geometry.  
This should solve the issues with relations [1703814](https://www.openstreetmap.org/relation/1703814), [4733518](https://www.openstreetmap.org/relation/4733518), and [5862586](https://www.openstreetmap.org/relation/5862586).
2. Accept sharing of nodes between the above multipolygon members where no real intersection exists. This should solve the issue with relation [1638363](https://www.openstreetmap.org/relation/1638363#map=18/31.81909/34.91619) _after the gaps were removed_, as seen below:
![image](https://user-images.githubusercontent.com/1304610/35139708-fbecfd5e-fcfc-11e7-8143-e93efcec4c89.png)

**Comment by HarelM** [comment]
Let's leave 1 aside for a moment.
I don't know how to convert 2 to a valid geojson shape. As far as I unerstand a multipolygon can't have ways that intersect which is the caee above.
I don't understand why the case above is a valid relation in terms of geometry, meaning why there are two section that can be marged but are kept apart.

**Comment by zstadler** [comment]
Adjacency is different than intersection. In item 2 above, there is no intersection since no node or vertex of one area is inside the area of another area.

Moreover, as far as I understand GeoJSON's MultiPolygons, the OSM restrictions on multipolygons [do not apply there](https://tools.ietf.org/html/rfc7946#section-3.1.7):
> __3.1.7.  MultiPolygon__
>
>    For type "MultiPolygon", the "coordinates" member is an array of Polygon coordinate arrays.

It means that GeoJSON accepts intersection and overlap between Polygons in the same MultiPolygon.

**Comment by HarelM** [comment]
The validation of the converted OSM to GeoJson is made by NTS framework. According to this implementation this is not a valid GeoJson shape.
Elasticsearch can only work with GeoJson object so I have to convert to GeoJson. I'm not sure how to solve this besides change the mapping so that the conversion will work according to NTS rules, which, I think, are decent rules.

**Comment by zstadler** [comment]
I have no motivation to debug issues in NTS

**Comment by HarelM** [comment]
I'm now trying to add the relations to the elastic search database and am getting an error on the same relations:
```
ES error:
2018-02-03 22:37:16.4194 |  9 |ERROR| Inserting relation_OSM_1637978 falied with error: failed to parse [geometry] caused by: Points of LinearRing do not form a closed linestring 
2018-02-03 22:37:16.4194 |  9 |ERROR| Inserting relation_OSM_1638667 falied with error: failed to parse [geometry] caused by: Points of LinearRing do not form a closed linestring 
2018-02-03 22:37:16.4194 |  9 |ERROR| Inserting relation_OSM_1649751 falied with error: failed to parse [geometry] caused by: Points of LinearRing do not form a closed linestring 
2018-02-03 22:37:16.4194 |  9 |ERROR| Inserting relation_OSM_3791784 falied with error: failed to parse [geometry] caused by: Points of LinearRing do not form a closed linestring 
```

```
NTS error:
2018-02-03 22:31:54.6126 |  4 |ERROR| MultiPolygon with ID: 1637978 Ring Self-intersection (35.249638,32.8651033) 
2018-02-03 22:31:54.7579 |  4 |ERROR| MultiPolygon with ID: 1638667 Self-intersection (34.9200588,31.7107475) 
2018-02-03 22:31:54.9695 |  4 |ERROR| MultiPolygon with ID: 1649751 Ring Self-intersection (34.7470509,31.4742719) 
2018-02-03 22:31:55.1801 |  4 |ERROR| MultiPolygon with ID: 3791784 Ring Self-intersection (35.1654217,31.8896851) 
```

Seems like this is not just one implementation (unless ES is using JTS). I would say that the above four geometries can't be converted to GeoJson - which I tend to think makes their mapping less "correct".

**Comment by zstadler** [comment]
Here are the 4 relations as converted to GeoJSON by [Overpass Turbo](http://overpass-turbo.eu/): [issue_612_GeoJSONs.zip](https://github.com/IsraelHikingMap/Site/files/1692258/issue_612_GeoJSONs.zip)

All 4 have been found to be valid GeoJSON by http://geojsonlint.com/ and https://www.mapbox.com/geojsonhint/

Perhaps the issue is with the component that converts the OSM data to GeoJSON? It would be interesting to
- Read the attached GeoJSONs to ES and NTS
- Compare the attached GeoJSONs to their equivalents in teh current flow.

To reproduce the GeoJSON files:
1. Use a relation of your choice in the following Overpass Turbo query:
    ```
    rel  (3791784); 
    out meta geom;
    ```
2. Run
3. Export -> Data -> download/copy as GeoJSON

**Comment by HarelM** [comment]
Thanks for the input, I'll see what can be done to test this.
Reopening until I have an answer.

**Comment by HarelM** [comment]
Ran the following:
1. Read feature collection: rel1637978.geojson provided in the zip.
2. Deserialize to `FeatureCollection` object 
3. Check for validity:
Results:
Not valid according to NTS: `Ring Self-intersection at or near point (35.249638, 32.8651033, NaN)`
Seems like the validators do not agree...
I'll open an issue with NTS and see what they have to say...

**Comment by HarelM** [comment]
I'm not sure the link to the mapbox lint actually checks the geometry validity:
I have altered the GeoJson a bit to make it invalid in terms of shaping cutting one another and I don't see an error, am I missing something?
![image](https://user-images.githubusercontent.com/3269297/35831664-3662fb12-0ad3-11e8-801e-e4591adb1dd8.png)

**Comment by zstadler** [comment]
I may have misinterpreted what you meant by "a valid geojson shape". NTS may have sticker conditions for validity.

Is there an NTS definition for its valid shapes?

**Comment by HarelM** [comment]
Not sure, some documentation can be found here:
https://locationtech.github.io/jts/javadoc/index.html
You can look for IsValidOp,
Also the comment says:
`Tests whether this Geometry is topologically valid, according to the OGC SFS specification.`
Which I think is the following document:
https://portal.opengeospatial.org/files/?artifact_id=829
Which have the following image in it which describes an invalid polygon as much as I can understand:
![image](https://user-images.githubusercontent.com/3269297/35873834-954bfa98-0b73-11e8-88d7-728b43f91fd6.png)
Feel free to double check everything I wrote here...

**Comment by zstadler** [comment]
Indeed, the spec fot MultiPolygons says:

> 2.  The Boundaries  of  any  2  Polygons  that  are elements  of  a  MultiPolygon  may  not  ‘cross’  and  may  touch at  only  a finite  number  of  points.

Perhaps using a GeometryCollection object will provide similar capabilities without the restrictions of the MultiPolygon object.

**Comment by HarelM** [comment]
There are numerous place in the code that relay on the fact that this type of geometry can't be created or relays on the assumptions that MultiPolygon is in use, changing it might be risky with very little benefit.
There are only 4 geometries in all Israel that suffer from this issue, why not just change those?

**Comment by HarelM** [comment]
I don't see any issues with the current code in terms of conversion. Most mapping issues were resolved. closing this...
