### ISSUE TITLE
Linking OSM user to Wikimedia images fails

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#619]
The Author field in the images uploaded to wikimedia can, at least sometimes, link non-existent OSM users.
e.g. here:
[https://commons.wikimedia.org/wiki/File:Israel_Hiking_Map_%D7%A2%D7%99%D7%9F_%D7%9E%D7%92%D7%93%D7%9C.jpeg](url)

**Comment by HarelM** [comment]
My bad - has to do with a wrong function I used and didn't fully checked...
