### ISSUE TITLE
Save button in route properties

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#62]
It's not clear if it saves the route or just it's properties.
Change the tooltip to read "save changes"

**Comment by HarelM** [comment]
Better yet, I'll add buttons to allow user to save only the selected route to file and add another button with "V" to save properties.

**Comment by valleyofdawn** [comment]
good idea!

**Comment by valleyofdawn** [comment]
Thank you. Please change the tooltip as well. "confirm changes" would work better with the check sign icon.
