### ISSUE TITLE
Add details to images uploaded to Wikimedia

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#620]
## Feature
Add the details field from OSM to the details field of images uploaded to Wikimedia.
Would help with search and add credibility to the importance of the image if someone wonders.

**Comment by HarelM** [comment]
Can you define "details"? the only thing that I think can currently be added is the description.

**Comment by valleyofdawn** [comment]
description and also keywords, Israel, type of poi ( spring / ruins etc.) and maybe coordinates or area in Israel.

**Comment by HarelM** [comment]
This is too vague. Can you define it in Wikipedia markdown?
Would be great if you can edit one of the Wikipedia pages and send it here so I can check which tags you added.

**Comment by HarelM** [comment]
I'll publish the description, title and user name tonight to reduce pressure. 
Let me know if you have thoughts on how to improve it in the future.
@safwathalaby let me know if you have any thoughts about this.

**Comment by HarelM** [comment]
Recently uploaded file can be found here - User is now valid and the POI's description was used.
https://commons.wikimedia.org/wiki/File:Israel_Hiking_Map_%D7%90%D7%AA%D7%A8_%D7%90%D7%91%D7%9F,_%D7%A8%D7%95%D7%97,_%D7%9E%D7%99%D7%9D.jpeg

**Comment by HarelM** [comment]
No comment was made in the last two weeks. Closing...
