### ISSUE TITLE
A problem with sharing my routes and layers

### ISSUE THREAD

**Issue by davidih** [IsraelHikingMap/Site#622]
## What I expect to happen
I'm trying to share my routes and layers

## What really happened
I get a message: "לא ניתן לפתוח את הקישור"
and not all my layers are displayed.

See example:
https://israelhiking.osm.org.il/#!/?s=C2ul3KFWTZ

## What I did that caused the issue - step by step
Add 2 layers, one of them is partly transparent.
Add 2 routes (happen also with one route)
Share them

## My environment
* Operating System and version:
Win-10
* Web Browser and version:
Chrome
## Thing I think the developers should know, images, links etc.
![kishur](https://user-images.githubusercontent.com/5500917/35195772-f6a8d75c-fed0-11e7-897d-1da099d2eb4a.jpg)

**Comment by zstadler** [comment]
I was able to open the share link.
![image](https://user-images.githubusercontent.com/1304610/35195909-4be5513a-fed3-11e7-95e8-3ebb5ea645ad.png)

Please try to reload the site with _Ctrl-F5_ and re-open the share link.

**Comment by HarelM** [comment]
I was too able to open it using my mobile android chrome browser. Try opening it from another machine.
Please close if it works.

**Comment by davidih** [comment]
I’m also able to open it on a logged-in site. When I try in IE or in Chrome – incognito mode or in a different machine where I’m not logged in – I get this problem

**Comment by HarelM** [comment]
I'm able to reproduce it in incognito mode, I'll try and check why later tonight.

**Comment by HarelM** [comment]
@davidih 
I have opened an issue in a library I'm using that seems to cause this issue in incognito mode.
https://github.com/zoomsphere/ngx-store/issues/33
I'm still unable to reproduce it in non-incognito mode - meaning the link shows there relevant info even if I log out (before surfing).
Can you try the following, please:
1. Open a browser (regular tag)
2. Press F12 to open debug tools
3. Click on console tab.
4. Surf to the following address with the PC that you see the problem with:
https://israelhiking.osm.org.il/debug/#!/?s=C2ul3KFWTZ
5. Copy the red text that is probably there.

**Comment by HarelM** [comment]
@davidih as a side note, the route and maps are shared but the map is not centered on the route, you can tell whoever you send the share to, to pan south and see the route...

**Comment by davidih** [comment]
I noticed that. However, I have 2 layers in the share and in that case one of them is missing

**Comment by davidih** [comment]
This is how I reproduce it in non-incognito mode:
F12
Go to the application tab and clear all the storage
paste the URL

**Comment by HarelM** [comment]
I see, as a work around for now, you can send the relevant address with instruction.
I'll need your help to further investigate this, see my comment above.
In order to reduce complexity, let's ignore the incognito mode for now, I'm working on it in a different channel.

**Comment by davidih** [comment]
![ihm console](https://user-images.githubusercontent.com/5500917/35210203-f5bb8536-ff59-11e7-8e67-6fac95c9936a.jpg)

**Comment by HarelM** [comment]
Just to make sure we are on the same page:
The above error message is received in regular mode (**not in** incognoito), in chrome on windows 10, right?
Can you also make a screen shot of the following screen:
Inside F12 -> Application -> Local storage (on the left) -> look for the value of ngx_activeOverlayKeys
![image](https://user-images.githubusercontent.com/3269297/35210460-f740b998-ff5a-11e7-91af-2ea81431a530.png)

**Comment by HarelM** [comment]
>Go to the application tab and clear all the storage

Sorry, missed that message, although I'm not sure this is a valid use case, I'll see if I can reproduce it too.

**Comment by davidih** [comment]
Well.. that's the case when my friends get it - they don't have yet local storge for IHM

**Comment by HarelM** [comment]
Ok, I think I found the root cause for this.
This has to do with the fact that the following local storage key is not created:
`ngx_activeOverlayKeys`
If you set it to `[]` the link will work.
I hope I'll get an answer soon here:
zoomsphere/ngx-store#33
As I think it is the same root cause.
Thanks for reporting and for helping debug!

**Comment by davidih** [comment]
Thanks for the quick response and for all the great work you do with IHM!!

**Comment by HarelM** [comment]
I have managed to find what I believe is the root cause of this issue.
I hope I'll get an update library containing this fix soon, otherwise I'll fix it locally and publish the fix until I get an update. Hopefully this will be closed within the next few days.
