### ISSUE TITLE
Incorrect language for POI added by clicking on the map

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#624]
## What I expect to happen
The language of the POI name to match the UI language

## What really happened
The POI name is in English while the UI is in Hebrew

## What I did that caused the issue - step by step
1. Open the map in [this position](https://israelhiking.osm.org.il/#!/17/29.6214/34.9417)
2. De-activate the POI layer, if visible
2. Enter POI edit mode
3. Click on the "חניון לילה שחורת" icon

The name of the new POI is "Shehoret Night Camp" rather than "חניון לילה שחורת"

## My environment
* Operating System and version: Win-10 Home
* Web Browser and version: Firefox 56.0.2 (64-bit)

## Thing I think the developers should know, images, links etc.

<img width="384" alt="2018-01-25 08_16_16-israel hiking map" src="https://user-images.githubusercontent.com/1304610/35373841-0a868f5a-01a9-11e8-80a2-1ba1061495c3.png">

**Comment by zstadler** [comment]
The issue now happens when the POI layer is active and a Wikipedia POI is clicked

1. Open the map in [this position](https://israelhiking.osm.org.il/#!/18/31.6481/34.6820)
2. Activate the Wikipedia POI layer
3. Change to Read-Only mode
4. Hover over the Wikipedia POI in the center of the screen and see the "משטרת עיראק סווידאן" title in Hebrew.
3. Activate POI Edit mode
4. Click on the "משטרת עיראק סווידאן" Wikipedia POI

The resulting private POI is in English
<img width="280" alt="2018-01-25 18_29_30-israel hiking map" src="https://user-images.githubusercontent.com/1304610/35399920-22352526-01fe-11e8-8bf4-172ce174d4a0.png">

**Comment by HarelM** [comment]
I knew this was a bad idea to change this code 😊

**Comment by zstadler** [comment]
Actually, I don't know if this is behavior has changed with the above fix, or it was already there when I created this issue.

**Comment by HarelM** [comment]
I'm guessing both issues are related to the previous fix with the feature attributes, related to the search.
No worries, they are easy to fix...

**Comment by HarelM** [comment]
Here is the explanation:
There are two markers at the same location, one in Hebrew and one in English.
When generating the POI layer the language is sent to the server and the marker is not presented (only markers with the required language are presented).
When generating snapping all languages are fair play (to increase the chance of snapping to something useful) and so you get the first one the snapping finds.
I think the best solution to this issue will be to fix this as part of #616 by adding OSM data on the building to link to both Hebrew and Enligh wiki pages using OSM tags.
I can probably order them by language, but it feels more of a patch than an actual fix...

**Comment by HarelM** [comment]
This is now possible due to the change made in #1115 - Clicking on a point now send to the server a request for "get closest point" - Adding a language parameter should be easy.
