### ISSUE TITLE
Avoid using Wikipedia's svg images

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#625]
# This issue was [re-stated below](/IsraelHikingMap/Site/issues/625#issuecomment-367595668)
This original description was kept as-is for clarity of the discussion that follows.

## What I expect to happen
When a Wikipedia POI is added as a private POI, look for non-svg image for the item.

## What really happened
When a Wikipedia entry has a geographic location, it is usually the first image on the page. This is probably in order to help the orientation for Wikipedia readers.
As a result, this is also the image used for the private POI.
The outcome is a POI with an image of two maps.

## What I did that caused the issue - step by step
1. Open the map in [this position](https://israelhiking.osm.org.il/#!/18/31.6481/34.6820)
2. Activate the Wikipedia POI layer
3. Change to Read-Only mode (to avoid [another issue](https://github.com/IsraelHikingMap/Site/issues/624#issuecomment-360522214))
4. Click on the "משטרת עיראק סווידאן" Wikipedia POI

The resulting private POI has [300px-HaShfela.svg](https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/HaShfela.svg/300px-HaShfela.svg) as its image:

![image](https://user-images.githubusercontent.com/1304610/35399624-594e50c4-01fd-11e8-9115-2f9b252f3d59.png)

## Thing I think the developers should know, images, links etc.
I suggest using the first non-svg image in the page:

[![375px-iraq-suidan](https://user-images.githubusercontent.com/1304610/35400275-f2e71f3a-01fe-11e8-9fec-02f1ca69501c.jpg)<br>https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Iraq-suidan.jpg/375px-Iraq-suidan.jpg](https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Iraq-suidan.jpg/375px-Iraq-suidan.jpg)

**Comment by HarelM** [comment]
This logic is very risky.
Also I don't see a way to do it using the library used in the site, and there's also a problem, I think, with the wiki API to get all images.
See here:
https://github.com/CXuesong/WikiClientLibrary/blob/194a876c64fcb13d322b9e2c559b0118781045f9/WikiClientLibrary/Pages/Queries/Properties/PageImagesPropertyProvider.cs
And here:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.DataAccess/WikipediaGateway.cs

I don't think it will be wise to implement it.

**Comment by HarelM** [comment]
The following is the response of images Wikimedia API for יער צרעה, I think,
Feel free to look at it and let me know how should one select the "correct" image.
I couldn't find anything good in the Wikimedia API documentation to fully solve this.
If you guys have any thought on how to properly solve this let me know, otherwise I'll close this issue.
https://he.wikipedia.org/w/api.php?action=query&titles=%D7%99%D7%A2%D7%A8%20%D7%A6%D7%A8%D7%A2%D7%94&prop=images&imlimit=100

**Comment by zstadler** [comment]
I've checked the English Wikipedia for the "page image" of different places. It seems like there is an effort in many Wikipedia pages to have a meaningful "Page Image". All the Hebrew Wikipedia templates with coordinates](https://he.wikipedia.org/wiki/%D7%A7%D7%98%D7%92%D7%95%D7%A8%D7%99%D7%94:%D7%AA%D7%91%D7%A0%D7%99%D7%95%D7%AA_%D7%9E%D7%99%D7%93%D7%A2_%D7%A2%D7%9D_%D7%A7%D7%95%D7%90%D7%95%D7%A8%D7%93%D7%99%D7%A0%D7%98%D7%95%D7%AA) that I checked, place an image before the map, causing it to become the "Page Image"

My conclusion is it is a bad editing practice to put a map as the "Page Image" of a Wikipedia entry when a picture is available.

I therefore suggest to avoid showing page images made of svg. IMO, it would be better to show the OSM image or no image at all.

**Comment by zstadler** [comment]
# Let me re-state the issue:

## Feature
## What I expect to happen
When a the image of a Wikipedia POI is in svg format, avoid showing it. 

## What really happened
When the image is an svg, it is usually a pair of background maps of the area which is inappropriate in the context of this site.

![image](https://user-images.githubusercontent.com/1304610/36526042-42859794-17b5-11e8-8092-1bfb2ea5c54c.png)

## What I did that caused the issue - step by step
1. Open the map in [this position](https://israelhiking.osm.org.il/#!/18/31.6481/34.6820)
2. Activate the Wikipedia POI layer
3. Change to Read-Only mode (to avoid [another issue](https://github.com/IsraelHikingMap/Site/issues/624#issuecomment-360522214))
4. Click on the "משטרת עיראק סווידאן" Wikipedia POI

The POI information pop-up has [300px-HaShfela.svg](https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/HaShfela.svg/300px-HaShfela.svg) as its image.
