### ISSUE TITLE
UX improvements to height profiles

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#629]
Feature:

1) The profiles are often poorly visible due to the semi transparency. Especially on dark background (e.g. sat images). Would work better on simple white.
2) MTB riders often ask "what percentage of the track in single track, double track & paved road?"
Some sited give you this feedback on the profile. e.g. here: http://osm.santolibre.net/route/details/1492739
3) In mobile mode I think this window should open by default to fill the bottom of the screen
4) in PC mode it could open initially on the lower left, and not fully stretched so that when the left panel opens it won't obstruct it as it does now. This is especially the case when you first open the left  panel and then the height profile which opens partly behind it.
5) When printing the map with the profile open, it gets deformed. Tested with printing to PDF.

**Comment by HarelM** [comment]
1. No argue here - my main concern is that it will make the map feel small, I'll play a bit with it and see how it feels.
2. Too complicated and too much info - not going to happen.
3. Making things work in one way for mobile is very hard to do and maintain, can't promise.
4. Same as above. 
5. I'll check, might be an issue with google charts...

Note, the fact that the height graph can be resized and moved is over complicating the entire window - if this is a required feature more than the above requirements then I'm afraid I won't be able to implement any of them, please let me know which is more important. 

Also I would like to make all the covering windows that are not dialogs (those that still let you interact with the map) be on the left side over/on the sidebar, this will also be relevant to POIs - see #614. Let me know if this is an acceptable solution.

BTW, this is how the linked site looks on mobile - way way too much information.
![image](https://user-images.githubusercontent.com/3269297/35463144-eb4d2496-02f7-11e8-85a6-629c2dced4e2.png)

**Comment by valleyofdawn** [comment]
If I had to choose I'd go with the fixed size rather than stretchable. Can it still be movable? It should be short and elongated so as to not take up too much space. If possible, half the width of a PC screen and the entire width of a mobile screen.
Many people are not initially aware of this feature. Maybe open it by default when you start or import a track. Allow the user to close it of course.

**Comment by zstadler** [comment]
If the height graph is no longer transparent, I see no reason to keep it on top of the map. 

I suggest it would take the bottom 10-15% of the screen, similar to the way the layers use the left side of the screen. There is also no need to make it moveable.

**Comment by HarelM** [comment]
I agree with Zeev, I don't see a reason to make it movable if it's not transparent, and also in general I see very little benefit of this being movable.
I think there should be a way to hide it since for mobile device you don't have a lot of space.
There's a lot of css and mobile/PC considerations here so the complexity is high and the benefit is low - so the priority of this issue just became extremely low...

**Comment by valleyofdawn** [comment]
Isn't it too wide on a big screen?
Also. can the small stats window be incorporated inside, so the bottom strip beyond the height profile is not wasted? Opening the height window would feel like expanding the small stats window.

**Comment by HarelM** [comment]
Replacing the button line with an entire section is a nice touch, much like leaflet is doing automatically for the default layers menu (not what we are using), with addition to scaling animation is can look good.
Having said that, and as I said, it is very complex with little to no benefit...

**Comment by valleyofdawn** [comment]
I'm sure you'll come round to it as you always do.

**Comment by HarelM** [comment]
Below is the new look (and new framework - d3), I can probably make it look better but I don't have a good idea how...
Printing seems to show a decent graph.
I made it somewhat mobile friendly (but it can be better I guess).
It opens from the side replacing the statistics line.
![image](https://user-images.githubusercontent.com/3269297/38772793-ade4af92-4047-11e8-90c4-de3ea7ed2f99.png)
I'll upload it to beta site shortly for you to play with it.

Still missing:
 * Show a message when no active route or no points are available - currently the window is just empty.

**Comment by valleyofdawn** [comment]
It looks very nice!
Maybe add the axis for the blank profile, to give users a hint what this is about.
Two-digit KM POIs could use a smaller font, as they are bigger than the drops.

**Comment by HarelM** [comment]
I'm using the following project as a code base reference:
https://giscience.github.io/Leaflet.Heightgraph/
The solution there to the tooltip issues is by drawing it as a part of the chart with svg and not with regular HTML as I did.
I'll implement this method as well since firefox just doesn't want to display the tooltip in the right place. :-/
>Maybe add the axis for the blank profile, to give users a hint what this is about.

This is what I wrote above: "Show a message when no active route or no points are available - currently the window is just empty."

**Comment by HarelM** [comment]
>resize would be possible without the overhead of resize handles or by overlapping the handles with the border.

I don't have a clue what you mean by this statement...

Please also describe a use case where the ability to resize the graph is useful enough to justify the complexity it brings.

**Comment by valleyofdawn** [comment]
I think the advantage of resizing is clear - when you plan a very long route, the profile gets condensed horizontally and hard to read.
It would be better if you could zoom in by pinching or scrolling on certain areas of the profile.
Right now I don't think it's in high priority unless you like the challenge.

**Comment by HarelM** [comment]
>I think the advantage of resizing is clear

Not to me - when the route is long it might not improve to open the graph in a large panel as the resolution is finite and the route distance isn't (kinda) so you can always end up with a chart that is not detailed enough.
D3 proves zoom controls by dragging a rectangle over the chart (requires implementation though) but then you need a "clear zoom" button and the entire experience becomes complex, which again, I'm not convinced is needed.

**Comment by zstadler** [comment]
The current elevation profile did not get any complaints on "lack of resolution". We can think of solving that issue if and when it is brought with a reasonable user flow.
in the meantime, it seems the majority of people on this thread believe enlarging the elevation profile is needed.

Would it be better to add a button that will maximize/restore the width of the graph rather than full width and height resizing control?

**Comment by valleyofdawn** [comment]
I think it's nice to have, not needed. Another nice option is for it to  auto-zoom-in when you traverse the course with the cursor.

**Comment by HarelM** [comment]
Still open:
* Ability to increase chart area and/or zoom options:
http://bl.ocks.org/bollwyvl/871b7c781b92fd0044f5
https://bl.ocks.org/mbostock/2b534b091d80a8de39219dd076b316cd
https://bl.ocks.org/mbostock/7ec977c95910dd026812
I couldn't find a drag-box-zoom in the examples above for d3 (the framework), let me know if you find one.
Possible zoom options: slider/buttons/pitch-scroll.
 * Hover point circle on the line itself - should improve how the hover looks a bit.

**Comment by HarelM** [comment]
I think the button is a good and simple idea.
The margin on the right is for when the drawing is open and the screen height is small - can be seen on mobile - the button s overlaps the chart.
Left side margin is small enough, IMHO.

**Comment by HarelM** [comment]
Publish to production and I'm not planning any more improvements.
