### ISSUE TITLE
Expand zoom levels for ESRI 

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#634]
## What I expect to happen
Allow all available zoom levels for ESRI satellite imagery base map

## What really happened
Zoom levels are defined according to the hiking and biking maps

## My environment
All OSes and browsers

**Comment by HarelM** [comment]
Originally, when I added this layer, The ESRI zoom levels were not available over zoom 16 and this is why it uses this zoom.
The following method just sets default values:
https://github.com/IsraelHikingMap/Site/blob/ffa98d60e89737ce7e025d722947563ad3e3a87f/IsraelHiking.Web/sources/application/services/layers/layers.service.ts#L400
Which can be overwritten here:
https://github.com/IsraelHikingMap/Site/blob/ffa98d60e89737ce7e025d722947563ad3e3a87f/IsraelHiking.Web/sources/application/services/layers/layers.service.ts#L98
