### ISSUE TITLE
No height profile for straight-line navigation

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#637]
## What I expect to happen
See DEM-based height profile when using straight-line navigation

## What really happened
The height profile is straight lines between the navigation points, regardless of the DEM.

## What I did that caused the issue - step by step
Open the height profile for [this example](https://israelhiking.osm.org.il/#!/?s=L6WDWe9teB)

## My environment
* Operating System and version: All
* Web Browser and version: All

## Thing I think the developers should know, images, links etc.

![image](https://user-images.githubusercontent.com/1304610/35998004-06c124bc-0d24-11e8-83de-ee4c90502bb9.png)

**Comment by HarelM** [comment]
Please elaborate:
What should be the sampling rate of this line?
What should happen when drawing long lines?
What is the use case this should solve? As in theory, there's no much use for the height profile when drawing straight lines as these lines should either be short to overcome mapping errors or used to measure distance as far as I understand.

**Comment by zstadler** [comment]
I'll try...

> What should be the sampling rate of this line?
> What should happen when drawing long lines?

Here is a thought: There are two factors to consider:
1. The native resolution of the DEM is 1 arc-second (1/3600 of a degree) which is about 30 meters. There isn't much value in any higher resolution.
2. The screen width is no more than 2000 pixels. We can assume there is no need for more that 1000 sample points for the entire graph. Moreover, the number of samples for the segment can be proportional its length WRT the length of the entire route.

Given a segment of length `l` meters, out of a route of length `L` meters, the number of equidistant samples would be `min(l/30, 1000*l/L)`

> What is the use case this should solve? As in theory, there's no much use for the height profile when drawing straight lines as these lines should either be short to overcome mapping errors or used to measure distance as far as I understand.

These assumption assume the routing is working and preferred by all users. Issues #584 and #621 are examples were routing is not working. 
Another assumption should be for consistency - the height profile should be along the path and not only in the route points for all routing modes. 

Note that the example above was only for illustrating the technical problem.

**Comment by HarelM** [comment]
This still doesn't answer the question of a valid use case - in the mtb example the user should use the hiking profile, and the second example is irrelevant to this case.  My assumption is that a user should not use the straight lines unless there's a mapping issue and highways do not exist where he plans his route. In these rare cases the lines are probably short and the current implementation is enough. Therefore I still don't see a valid use case. I agree there's an issue here with the height graph, and I also don't think it will be hard to fix, but if there isn't a valid use case, why invest time in fixing it?

**Comment by HarelM** [comment]
Files are not manipulated to have more points - so I'm not sure I have a fix to this issue.
Having said that the following use case is problematic:
1. Plan straight lines on IHM
2. Export and send to someone
3. Open in IHM - the issue above will happen.

I don't think I should be manipulating files, but I can make sure I don't create files that will can present incorrect heights.

Please note that this will not solve the issue of drawing a long straight line (say 10 KM in one segment), but I hope no one is expecting to draw a long straight line and have the right height data.

**Comment by HarelM** [comment]
The total length of the route is not available since routing is always between two points...
Having said that I tend to think that 30 point should be enough, and there's no need to sample in a distance that is less than 30 meters:
Here are the results:
![image](https://user-images.githubusercontent.com/3269297/38644566-a5c04692-3de9-11e8-900c-56e6efefedaf.png)

**Comment by zstadler** [comment]
I agree that the user's route should not be modified.

Instead of building the height graph, one point at a time, on the client side, I suggest the server will receive the user's route and respond with an elevation graph. This will enable the server to provide finer-granularity graph for any given route. 

I believe this is how Strava calculated the elevation graph for the _original_ route:

![image](https://user-images.githubusercontent.com/1304610/38692645-0b850172-3e8d-11e8-92bb-46d4970d190f.png)


BTW, with this approach, I do not see an issue with a 10Km line, although this is not an important capability.

**Comment by HarelM** [comment]
I don't think this is a good idea since it will make the elevation graph "sluggish".
I believe the current solution is good enough.

**Comment by zstadler** [comment]
The full user route of the above example has 137 segments. Only 4 of them were presented above. Ensuring that the route has at least 30 points would not change anything with regard to the elevation profile issue it demonstrates.

Strava does not seem to be sluggish. I believe there may be a sluggishness issue, if at all, only if the code continues to run on the client side and for weak clients such as mobile phones.

**Comment by HarelM** [comment]
You are welcome to implement it. as I said, I believe the current solution is good enough.
