### ISSUE TITLE
No icon for the Share button

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#64]

**Comment by HarelM** [comment]
Icon is there (PreProduction site)... try refresh the browser...

**Comment by zstadler** [comment]
It was blocked based on the [Fanboy's Social Blocking List](https://easylist.adblockplus.org/en/)

See "##.fa-share-alt" at https://easylist-downloads.adblockplus.org/fanboy-social.txt

**Comment by HarelM** [comment]
Not sure what I can do about it...

**Comment by zstadler** [comment]
No intent for you to do anything. I get what I've asked for - no social
media on my browser...
I just wanted to share the actual reason
