### ISSUE TITLE
Custom layers vanished

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#643]
## What I expect to happen
Custom layers should not vanish

## What really happened
There's a scenario which deletes the custom layers.
The scenario is still unknown but the fact that it can happen it alarming.

## What I did that caused the issue - step by step
Not sure...

## Thing I think the developers should know, images, links etc.
Current way of editing custom layers will update the server with the entire custom layer each update - this is not a safe way to update such user data and should be split into regular CRUD operations for each custom layer on its own.

Also this feature will require to take a ES database backup in order to merge missing layers.

**Comment by zstadler** [comment]
I have created a separate Elastic Search server for a copy of the data captured  by the site backup dated 13.1.2018. The server is accessible only from within the site host at port 9213.

The separate server was configured using the following lines in  
`"C:\Temp\IsraelHiking.osm.org.il_backup_2018-01-13\ElasticSearch\config\elasticsearch.yml"`:
```YAML
# Set a custom port for HTTP:
http.port: 9213
#
# Disable discovery
transport.type: local
```

The backup data contains layers that are no longer available in the current data, such as my own layers.

The backup data also contains what seems to be invalid layer definitions.  This may aor may not be related to this issue. For example, [`http://localhost:9213/user_layers/usermaplayers/5339643?pretty`](http://localhost:9213/user_layers/usermaplayers/5339643?pretty)
```json
{
  "_index" : "user_layers",
  "_type" : "usermaplayers",
  "_id" : "5339643",
  "_version" : 4,
  "found" : true,
  "_source" : {
    "layers" : [
      {
        "isOverlay" : true,
        "key" : "",
        "address" : "",
        "minZoom" : 7,
        "maxZoom" : 16,
        "opacity" : 0.1
      }
    ]
  }
}
```

and [`http://localhost:9213/user_layers/usermaplayers/5258293?pretty`](http://localhost:9213/user_layers/usermaplayers/5258293?pretty)
```json
{
  "_index" : "user_layers",
  "_type" : "usermaplayers",
  "_id" : "5258293",
  "_version" : 37,
  "found" : true,
  "_source" : {
    "layers" : [
      {
        "isOverlay" : true,
        "key" : "Wiki",
        "address" : "",
        "opacity" : 1.0
      }
    ]
  }
}
```

There are also cases where a user has both valid and invalid layers.

**Comment by HarelM** [comment]
Great! Thanks!
What do you mean by invalid layers?

**Comment by zstadler** [comment]
> What do you mean by invalid layers?

Layers with empty `address` or `key`

**Comment by HarelM** [comment]
The following is the code I used for the migration, adding it here in case of future reference as I'm not planning on checking-in this code...
[MigrateElasticsearchLayer.cs.txt](https://github.com/IsraelHikingMap/Site/files/1755211/MigrateElasticsearchLayer.cs.txt)

**Comment by zstadler** [comment]
> The following is the code I **_used_** for the migration

@HarelM, Did you restore the layers from the backup?
I still don't see my old layers.

**Comment by HarelM** [comment]
Not yet, probably tonight. **used** as in for testing on my development machine.
Note that this feature is still in progress, once it will be released (removed from the board) I'll ask you to check if you can see your old layers.

**Comment by zstadler** [comment]
Does this code remove the illegal/invalid layers?

**Comment by HarelM** [comment]
>Does this code remove the illegal/invalid layers?

Yes

**Comment by HarelM** [comment]
Update published.
