### ISSUE TITLE
Keep share URL in address bar 

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#646]
## What I expect to happen
Share url should be visible after the site finishes loading

## What really happened
The share url is cleared

## What I did that caused the issue - step by step
1. Open a share

## My environment
Any 

## Thing I think the developers should know, images, links etc.
When the share is not cleared there needs to be a button somewhere to allow the user to clear it...

**Comment by HarelM** [comment]
@valleyofdawn @zstadler I have published this feature but it turned out to be risky, would appreciate any test that you make to make sure this works as expected, and any other tests related to address and links...

**Comment by zstadler** [comment]
I find it a bit strange that the map position and zoom are updated and shown in the address bar. I would prefer that regardless of the map position, the address bar would show just
```
https://israelhiking.osm.org.il/#!/?s=uxAuWbKzeD
```
rather than
```
https://israelhiking.osm.org.il/#!/14/32.7047/35.1306/?s=uxAuWbKzeD
```
In any case the map position and zoom are ignored upon reload or any other use of the URL containing them.

**Comment by HarelM** [comment]
The change wasn't easy and I feel that everytime I touch this code I introduce new bugs so I prefer to change it as little as possible.
Having said that, I understand the concern about how the site ignores the position when refreshing with a URL, but changing this requires to think about all the use cases and see that they are well taken care of, which again, is not easy.
