### ISSUE TITLE
Improve user button

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#648]
## Feature
The button on the upper right that is related to the user should be simplified and more user friendly:
1. Add tooltips
2. Remove button of the left end - they don't give any thing beside complexity.

**Comment by HarelM** [comment]
New look:
![image](https://user-images.githubusercontent.com/3269297/36812199-fc98cb10-1cd8-11e8-938f-d1f018ce1d88.png)

**Comment by zstadler** [comment]
The "logout" button can also be moved to the "My Profile" window.
