### ISSUE TITLE
Open the shares list first in the user profile

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#649]
## What I expect to happen
Show the shares list as the initially-open tab of the user profile

## What really happened
The the GPX recordings is shown when the user profile is open

## What I did that caused the issue - step by step
Open the user profile

## My environment
* Operating System and version: any
* Web Browser and version: any

## Thing I think the developers should know, images, links etc.
I believe the shares list is more useful to the user and it is a unique feature of the site deserving a more prominent view.

**Comment by HarelM** [comment]
I agree, judging from my last experience when constantly switching to share every time I refresh and open the user profile.

**Comment by zstadler** [comment]
Agreed
