### ISSUE TITLE
When selecting search text with mouse, the map moves

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#65]
When I do:
* Open the search window
* Type some text
* Use the mouse to select the test using shift-drag

What happens:
* The map moves

I expect to happen:
* No impact on map position

**Comment by HarelM** [comment]
I have an issue with it in all the controls, this is the first control that uses drag... I'll fix it, good spotting.

**Comment by HarelM** [comment]
http://gis.stackexchange.com/questions/104507/disable-panning-dragging-on-leaflet-map-for-div-within-map
```
// Disable dragging when user's cursor enters the element
    info.getContainer().addEventListener('mouseover', function () {
        map.dragging.disable();
    });

    // Re-enable dragging when user's cursor leaves the element
    info.getContainer().addEventListener('mouseout', function () {
        map.dragging.enable();
    });
```

**Comment by HarelM** [comment]
Applied to layers control as well.
