### ISSUE TITLE
Share is not shown after opening from its iframe

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#650]
## What I expect to happen
Clicking on the Israel Hiking logo from a shared map contained in an iframe should open the share in a new tab.

## What really happened
A new tab is opened, but the share is not shown.

## What I did that caused the issue - step by step
1. Open http://www.masa70.co.il/post-20/
2. Scroll down to the embedded map
3. Click on the "Israel Hiking" logo

The site will be opened in a new tab, but the route is not shown

## My environment
* Operating System and version: any
* Web Browser and version: any

**Comment by HarelM** [comment]
Seems like the following line is not doing its job.
https://github.com/IsraelHikingMap/Site/blob/a87b8f8c79767430bbb66825cb41a2e4b4fbba05/IsraelHiking.Web/sources/application/services/hash.service.ts#L129

The following need to be checked as a replacement:
`window.self === window.top`

**Comment by zstadler** [comment]
I suggest the following logic for clicking the Israel Hiking logo:

1. In an iframe, the map will be re-opened as the top element of a new tab. The `!#/?s=` and `!#/?url=` suffixes will be preserved in the new tab in order to present the contents embedded by the site that uses the iframe.
2. As the top window, the page will be reloaded while removing any contents: shares, external urls, and private routes. The reload will be done in the same tab in order to avoid unnecessary creation of tabs, especially since the UX for multiple tabs has not been defined or reviewed yet.

Currently, the right contents are presented in both scenarios, but a new tab is opened in the scenario 2.
