### ISSUE TITLE
No enlargement of private images in POIs

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#655]
Bug

## What I expect to happen:
I expected the image to be enlarged

## What really happened:
nothing

## What I did that caused the issue - step by step
Dragged an image into the site.
Added a short description.
Doubble clicked the image.
It remained a thumbnail.

## My environment
Windows
Chrome

The private images are useless without actually seeing them.
Copying the behavior of public POIs and Wikipedia points would be nice.

**Comment by HarelM** [comment]
Will be fixed as part of #614 - which should improve all aspects of similarity between all the different POI popups.
I'll close it once I'll commit this change.

P.S. Can you send me the share? I'm pretty sure there is a way to see a large image for private POI, maybe while in edit mode...?

**Comment by valleyofdawn** [comment]
Here's an example.
https://israelhiking.osm.org.il/#!/?s=3He7TXaE2q

I think we should consider supporting **larger** photos.
Some potential users focus on nature photography and would like to show off their photos along a course.
The size supported now may be informative but won't allow full artistic appreciation of photos.

**Comment by HarelM** [comment]
See #614.
