### ISSUE TITLE
Elevation for non routed points.

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#66]
As a user I expect to see elevation for manually added non routing points.
possible solutions:
http://dev.virtualearth.net/REST/v1/Elevation/List?points=lat1,long1,lat2,long2,latn,longn&heights=heights&key=ArUJIOvdEI-4sFS5-3PqMlDJP-00FMLrOeLIGkLRpfWIjfpOcESgnE-Zmk-ZimU2
using bing key: https://msdn.microsoft.com/en-us/library/ff428642?f=255&MSPPError=-2147217396
or Google (although the limitation on usage is a bit low...):
https://developers.google.com/maps/documentation/elevation/intro
or maybe we need to add it to the server...

**Comment by valleyofdawn** [comment]
This is screwing up the gain measurement even if you have a short non routed section.
If it's easy, please implement a linear drop between nodes as an interim solution.

**Comment by HarelM** [comment]
@valleyofdawn, @zstadler,
I have added elevation awareness to non-routed/missing elevation points (pre production).
It appears that bing is using a different elevation data than brouter.
I think it's good enough now, we'll need to setup a routing server which also able to returns heights.
