### ISSUE TITLE
Merge POI algorithm

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#660]
## Feature
There are currently (after adding Wikipedia and iNature to POIs) places where more than one POI represent the same thing.
In order to simplify this the following should be implemented:
1. An algorithm to find and merge "duplicate" points.
2. The ability to link a single POI to multiple sites.
3. The ability to let the algorithm know two or more POIs are the same.

To do it @zstadler and I have decided the following is the best approach:
The algorithm will find places that are close to each other (up to 100 meters).
and have the same name.
OSM elements can have multiple names and so I suggest that in order to notify the algorithm there are duplicate POIs one could edit OSM and add a new name that is equal to the provider's POI site name.

for example:
OSM point with `name:he=my_poi`.
Wikipedia point at the same location with the title `mi_poi`.
Since both do not have the same name they will not be joint to a single point.
To fix this, one needs to go to OSM and add `name:he1=mi_poi` to let the algorithm know it is actually the same POI.

**Comment by HarelM** [comment]
As part of the results analysis of the merge algorithm I see a case that is relevant to places where the municipal boundary is different (usually larger) than the residential boundary (usually aother relation)
here's an example (I do think the mapping is correct in this case):
https://www.openstreetmap.org/node/280115936
https://www.openstreetmap.org/way/25692063
https://www.openstreetmap.org/relation/1379225 
Currently the places node handling removes the smaller boundary and leaves the larges as a separate entity. 
I tend to say that in this case the larger boundary should be removed from our database if it has the same name as the place node and the smaller boundary - as it has no significant interesting information to add and will cluster the search results.

**Comment by zstadler** [comment]
I suggest we use the smallest available container. I believe this is also how Nominatim works. In this case, it is the residential area.

I also believe we should ignore place=suburb, place=neighborhood and the corresponding admin_levels 9 and 10.

**Comment by HarelM** [comment]
The algorithm currently using the smallest container and ignores 9,10 etc as containers candidates.
What I wanted to do is to "throw" the larger containers as POI search results to reduce search results clutter, meaning:
The following search results are a merge between 4 entities - label node, residential boundary, municipal boundary and a Wikipedia point. 
I want to present only one search results for the case above: merge the node with the residential (smaller) boundary and with the Wikipedia point and "throw" the municipal (larger) so that it won't show in the results.
![image](https://user-images.githubusercontent.com/3269297/38307798-9f4d1334-381d-11e8-85bb-993538d9b41b.png)

**Comment by HarelM** [comment]
Attached are initial results of the algorithm:
First part is the removal of places in favor of their label nodes
The second part is the merging of element - it's a bit cryptic but it shows the id in every system and which items were merged to which:
```
<he|en>_<number> = <he|en>.wikipedia.org/wiki/?curid=<number>
<node|way|relation>_<number> = www.openstreetmap.org/<node|way|relation>/number
<long number> = https://off-road.io/track/<long number>
<short number> = https://inature.info/wiki/?curid=<short number>
```
[merge.txt](https://github.com/IsraelHikingMap/Site/files/1876721/merge.txt)
The results are fair, I think.

**Comment by HarelM** [comment]
You can probably write a small script to do the translation, but I'll see what I can do.
The above means that an iNature point with id 4758 was merged to OSM way with the above ID.

**Comment by HarelM** [comment]
Results can be seen in attached file (download and change from txt to html).
[merge.txt](https://github.com/IsraelHikingMap/Site/files/1877805/merge.txt)
There are some mapping issues that we should consider fixing regardless of the fact that the algorithm may fix it such as node duplication.

**Comment by HarelM** [comment]
All the above are tested and fixed. so they seem to be working properly.
Still need to test client update.
