### ISSUE TITLE
Logic for clicking the Israel Hiking logo

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#662]
I suggest the following logic for clicking the Israel Hiking logo:

1. In an iframe, the map will be re-opened as the top element of a new tab. The `!#/?s=` and `!#/?url=` suffixes will be preserved in the new tab in order to present the contents embedded by the site that uses the iframe.
2. As the top window, the page will be reloaded while removing any contents: shares, external urls, and private routes. The reload will be done in the same tab in order to avoid unnecessary creation of tabs, especially since the UX for multiple tabs has not been defined or reviewed yet.

Currently, the right contents are presented in both scenarios, but a new tab is opened in the scenario 2.

**Comment by zstadler** [comment]
The logo's tooltip should be dynamic, accordingly.

**Comment by zstadler** [comment]
Using the text "Open in Israel Hiking" below the logo, in embedded mode, instead of just "Israel Hiking" would be even better.

**Comment by HarelM** [comment]
I prefer not to change the logo - the symbol and text should stay the same - for that reason it also doesn't change when the language is Hebrew.
