### ISSUE TITLE
Simplifying the UI/UX of embedded maps

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#663]
## What I expect to happen
The UI/UX of embedded maps could be improved by simplifying it for this context. If a user need an advanced capability, it would make sense to click on the Israel Hiking logo and get access to the full capabilities of the site in a new tab.

## What really happened
Many of the site capabilities are irrelevant or low priority in this context, yet they occupy valuable screen "real estate" and reduce the clarity of the presented share/route.

## Thing I think the developers should know, images, links etc.
I suggest the UI will include the following items, in descending order of priority:

- Israel Hiking logo
- Save
- Share
- About/Legend

Optional - if frame height allows:
- Zoom-in/Zoom-out
- Save as
- Language
- Print

![image](https://user-images.githubusercontent.com/1304610/37596380-a1d354e2-2b84-11e8-9a09-d3811fdf9bd0.png)

It seems like the right side has very few buttons. This is an opportunity to consider either (a) move all buttons to one side, or (b) move some buttons from the left side to the right side.

**Comment by HarelM** [comment]
Isn't this request aleady covered by #361?
I think that places that uses an embedded map should have the possibility to control what is presented in their site and it is not for us to decide, we can suggest a default settings. In any case, I think the linked issues cover this.

**Comment by zstadler** [comment]
As we've seen in several interactions with site owners, they are not familiar with web programming, to say the least. It is therefore important to set good defaults that will be used by +90% of them.

At the end of the day, an embedded map does not look good, or it isn't useful, will reflect on the reputation of the Israel Hiking site. It also affects third-party site owners' decisions between Google maps and Israel Hiking.

For example, see the minimal map decoration when Google Maps are used to show a [Nakeb trail](https://www.nakeb.co.il/hike/19) over the Israel Hiking map:

![image](https://user-images.githubusercontent.com/1304610/37640603-15bb9834-2c1f-11e8-9eff-ab238371415b.png)

versus the same bounding box in Israel Hiking:

![image](https://user-images.githubusercontent.com/1304610/37640823-f38208e2-2c1f-11e8-821c-601178cf0866.png)

Similar visual simplicity can be seen in the [Off-road site](http://off-road.io).

Setting good defaults is significantly simpler than a full-fledged iframe control. These defaults should be preserved if and when #361 is implemented.

**Comment by HarelM** [comment]
I agree iframe users are not developer and therefore there should be a section in the site or an entierly different page to allow the creation of the needed iframe with the relevant controls. The above requirements is a subset of #361 and implementing this issue will result in wasted development time.
I don't see a reason to keep this issue open...

**Comment by zstadler** [comment]
Let's keep this issue open until #361 is either implemented or abandoned.

**Comment by HarelM** [comment]
I think print and save-as are not needed but layers is, so:
* Zoom (not on mobile)
* Location (Only on mobile)
* Layers
* Save
* Info
* Share
* Language

**Comment by zstadler** [comment]
I think save-as is needed since several applications and devices do not accept the default gpx save format.
I think print is also needed for people who want to take the map with them to the trip, especially hikers, but also less-technical people.

**Comment by HarelM** [comment]
I think printing should only be available from our site when the user wants to see a full screen of the map, otherwise he should be printing the entire embedding page and not just the map, IMO.
I don't mind adding save-as back but I think the embedding page should also make a file available for download - most sites do not offer more than one file...
