### ISSUE TITLE
Recognize Degrees-Minutes-Seconds location search without North/South, East/West

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#665]
## Bug

The search string `31 42 28.56940 34 36 23.92196` is not recognized as a valid location.
It should be equivalent to `31 42 28.56940 N 34 36 23.92196 E`, which is recognized.

Similarly, `-31 42 28.56940 -54 36 23.92196` should be equivalent to `31 42 28.56940 S 54 36 23.92196 W`.

**Comment by HarelM** [comment]
@zstadler any progress on this? I'm currently not taking care of this since you are assign to it.
If you'd like me to fix this please assign me.

**Comment by HarelM** [comment]
`NS EW` characters are used as separators for the regular expression to know where the first number end and the second number starts.
Allowing not to place them can result in unwanted behavior, consider the next two cases:
`32 33 34 35` - is it `32 33 N 34 35 E` or `32 N 33 34 35 E` or `32 33 34 N 35 E`?
`32 33 34 35 36` - is it `32 33 34 N 35 36 E` or `32 33 N 34 35 36 E`?
The only valid case I can think of is when you have a total of 6 numbers - this probably requires a new class to take care of this scenario.

**Comment by zstadler** [comment]
> `NS EW` characters are used as separators for the regular expression to know where the first number end and the second number starts.
Allowing not to place them can result in unwanted behavior, consider the next two cases:
`32 33 34 35` - is it `32 33 N 34 35 E` or `32 N 33 34 35 E` or `32 33 34 N 35 E`?
`32 33 34 35 36` - is it `32 33 34 N 35 36 E` or `32 33 N 34 35 36 E`?
The only valid case I can think of is when you have a total of 6 numbers - this probably requires a new class to take care of this scenario.

IMO 2 and 4 numbers can also be parsed, not only 6 numbers:
`32 33 34 35` is `32 33 N 34 35 E`
`32 34` is `32 N 34 E` 

In addition, other optional components can be used to resolve the ambiguity:
- The use of  `°` (degree), `'` (minute), or `"` (seconds) annotations
- A decimal number denotes the end of a coordinate:
  `32 34.75 35` is `32 34.75 N 35 E` 
- A negative number denotes a start of a coordinate:
  `32 -33 35` is `32 N 33 35 W`

**Comment by zstadler** [comment]
For our future reference, it may be worthwhile to see the approach used by [coordinate-parser](https://github.com/servant-of-god/coordinate-parser)

**Comment by HarelM** [comment]
If the referenced library covers all these cases I don't see a reason not to translate it to c#, it shouldn't be hard...
