### ISSUE TITLE
Search results are open after choosing

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#67]
Reproduction:
* Search for Haifa
* Choose one of the options
What happens:
* List of search results is visible and clickable
What I expect to happen:
* Search is reduced to its original button once a search result is clicked
Optional behavior:
* The map temporarily pans (no zoom change) to each search result when the mouse hoovers on it. Original location is restored if mouse is away or search is abandoned

**Comment by HarelM** [comment]
Optional option might make the user "dizzy". search will collapse.
