### ISSUE TITLE
KM POIs to be places at incorrect distances from the start point

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#670]
## What I expect to happen
KM POIs to be places at correct distances from the start point.

## What really happened
In some routes, the Km POIs are shown at incorrect locations, probably using the route's turning points.

For example, There is no "1 Km" POI and the "2 Km" POI is placed at 2.53 Km.

![image](https://user-images.githubusercontent.com/1304610/38292376-336a29e4-37ec-11e8-88d8-3f638d883023.png)

## What I did that caused the issue - step by step
1. Open https://israelhiking.osm.org.il/#!/?url=http://www.jeepolog.com/UserFiles/TWL/dolev-zanoach.twl
2. Statistic graph -> Km POIs

**Comment by zstadler** [comment]
This issue was opened after a question in [this thread](http://www.jeepolog.com/forums/showthread.php/107655-%D7%A9%D7%90%D7%9C%D7%94-%D7%A9%D7%99%D7%A0%D7%95%D7%99-%D7%A6%D7%91%D7%A2-%D7%A7%D7%95-%D7%A1%D7%99%D7%9E%D7%95%D7%9F-%D7%9E%D7%A1%D7%9C%D7%95%D7%9C-%D7%91-ORUXMAPS?p=786958&viewfull=1#post786958)

**Comment by HarelM** [comment]
Except maybe the above person in that thread I really don't think this feature is in use.
In any case, I couldn't leave it incorrect.
We can always decide to remove it later...
