### ISSUE TITLE
Description of bus stop in elyakim

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#672]
## What I expect to happen
Not sure

## What really happened
The following is the description of Elyakim juction which was merged with a wikipedia point:
רחוב:יציאה לכביש 70 עיר: מגידו רציף: קומה:
Which is the description of the bus stop.

## What I did that caused the issue - step by step
Open POI at:
http://israelhiking.osm.org.il/#!/19/32.6359/35.0639

## Thing I think the developers should know, images, links etc.
https://www.openstreetmap.org/node/1803052858
This description is given by the osm bot.
@SafwatHalaby can we improve the description somehow (maybe remove empty entries)? do we have to use the description field?

**Comment by HarelM** [comment]
@SafwatHalaby any updates on this? can you update your script a bit?

**Comment by SafwatHalaby** [comment]
I will look into this.

**Comment by SafwatHalaby** [comment]
The issue will be fixed prior to the next update.

**Comment by HarelM** [comment]
I should probably remove the option to merge bus stops to other POI sources since the description from OSM has the highest priority and it looks weird...

**Comment by SafwatHalaby** [comment]
The description field appears to be useful. It sometimes contains info about a previously unmapped street name. The next update will remove empty entries.

**Comment by SafwatHalaby** [comment]
The update fixed this thoroughly. 

More info: https://wiki.openstreetmap.org/wiki/User:SafwatHalaby/scripts/gtfs

**Comment by HarelM** [comment]
Thanks for the update!
