### ISSUE TITLE
Incomplete merge of POIs

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#675]
### Follow-up for #660 

**Incomplete merge**
  The merge is incomplete when multiple objects exist close to one another. For example, there are [8 nearby nodes named "צומת פלוגות"](http://overpass-turbo.eu/s/xNQ). They are merged into at [5 POIs](https://israelhiking.osm.org.il/#!/?s=fIS4CD2Rpx) instead of just one.

  ![image](https://user-images.githubusercontent.com/1304610/38621160-f068e10e-3da8-11e8-9562-2c7b12336200.png)

  This is probably because the algorithm is order-dependent. Consider the following POIs, having 80 meter gaps:   

  ![image](https://user-images.githubusercontent.com/1304610/38624651-4f96a406-3db1-11e8-88d2-4b5c86beb82a.png)   
  If processed in the order of their IDs, the 2nd POI is 160 meters form the 1st POI and will not be merged with it. However, when the 3rd POI is processed, the opportunity to merge all 3 of them can be detected.

**Comment by zstadler** [comment]
### Item 3 above was moved to #676

**Comment by HarelM** [comment]
I'm looking into צומת פלוגות and it seems that even if I solve the issue above with the order the merge will not take place as the distance between the nodes is more than 100 meters...
I don't fancy the idea of defining threshold per type of point, it will create a complex code that I'll have a hard time debugging and explaining the results, I think...

**Comment by HarelM** [comment]
### Item 1 above [was moved](https://github.com/IsraelHikingMap/Site/issues/677) to #677

**Comment by HarelM** [comment]
I've basically added what we talked about - when merging points the geometry is accumulated into `GeometryCollection` and when the algorithm finishes merging it picks the "interesting geometry".
This solves the above case with the 3 points. I've also added test to cover all the available scenarios.
See here:
https://github.com/IsraelHikingMap/Site/blob/2c781afeb9dd12efd15e2511436f36a7e4c64dff/IsraelHiking.API/Executors/FeaturesMergeExecutor.cs#L96

I'll re-run the merge tonight after I finish all the tweaking and send an updated report.

**Comment by zstadler** [comment]
According to my measurement, the maximal distance between adjacent nodes in צומת פלוגות is 80 meters

![image](https://user-images.githubusercontent.com/1304610/38723496-f2242bea-3f09-11e8-8e49-b101b64b4fc7.png)

**Comment by zstadler** [comment]
> I'm looking into צומת פלוגות and it seems that even if I solve the issue above with the order the merge will not take place as the distance between the nodes is more than 100 meters...
I don't fancy the idea of defining threshold per type of point, it will create a complex code that I'll have a hard time debugging and explaining the results, I think...

The highway junctions are within 80 meters of one another. The bus stations are within 125 meters of one another.

It will be perfectly fine to change the merging distance to 150 meters for all POI types.

As a side note, the bus station names are only used to locate places and junction where there are no street names. IMO, they are not different than junction names and the two categories can be safely merged.

**Comment by HarelM** [comment]
I do not agree with your statement regarding the usage of bus stations, sorry.
A bus station is a bus station and a juction is a juction, for me they are separate entities and I want to see different search results.
In any case, I'm not comparing in meters but in degrees. Current threshold is 0.001, Can you check what number it should be to correspond to 150 meter?

**Comment by zstadler** [comment]
0.0015 or 0,.002 degrees would be fine.

**Comment by HarelM** [comment]
Updated to 0.0015 and allowed it to be changed from configuration file.
The final results can be seen in the image below.
Main issues are resolved IMHO. 
Special cases such as the above will be decided offline and open as a separate issue.
Closing...
![image](https://user-images.githubusercontent.com/3269297/38746948-dc06cffa-3f51-11e8-8856-ef0f57e20a87.png)

**Comment by HarelM** [comment]
The problem with Eilot RC is the following:
The wikipedia tag that is merged to this relation creates a geometry collection of two polygons and a point. The above line selects the first polygon.
I'll see if I can think of a clever way to fix this...
