### ISSUE TITLE
Can't open GPX files generated by the site in Galileo (iOS)

### ISSUE THREAD

**Issue by hagai-lvi** [IsraelHikingMap/Site#681]
## What I expect to happen
I expect the site to generate GPX files that will be opened in an app called galileo.  
In the past (a few weeks ago) I've managed to open files generated by the site in this app, but something has changed in the way the site handles files and now I can't.  
It seems as if there was a change in the [BOM](https://en.wikipedia.org/wiki/Byte_order_mark), encoding or something similar.

## What really happened
I can't open new files generated by the website in my app.

## What I did that caused the issue - step by step
1. Create a route
2. Click Save (Tried all of the possible variations of GPX available in the website)
3. Open the file in the app on my iPhone

## My environment
* Operating System and version:
macOS 10.13.1 / iOS 11.3
* Web Browser and version:
Chrome Version 65.0.3325.181 (Official Build) (64-bit)

## Thing I think the developers should know, images, links etc.
I've attached a zip with 2 files:
1. `will_open.gpx` - a file generated by the site a few months ago, and that I am able to open in my app
2. `wont_open.gpx` - a file generated by the site today (April 14, 2018) that I can't open in my app

Notice the following:
```
$ hexdump wont_open.gpx | head
0000000 3c 3f 78 6d 6c 20 76 65 72 73 69 6f 6e 3d 22 31
0000010 2e 30 22 3f 3e 0d 0a 3c 67 70 78 20 78 6d 6c 6e
0000020 73 3a 78 73 69 3d 22 68 74 74 70 3a 2f 2f 77 77
0000030 77 2e 77 33 2e 6f 72 67 2f 32 30 30 31 2f 58 4d
0000040 4c 53 63 68 65 6d 61 2d 69 6e 73 74 61 6e 63 65
0000050 22 20 78 6d 6c 6e 73 3a 78 73 64 3d 22 68 74 74
0000060 70 3a 2f 2f 77 77 77 2e 77 33 2e 6f 72 67 2f 32
0000070 30 30 31 2f 58 4d 4c 53 63 68 65 6d 61 22 20 76
0000080 65 72 73 69 6f 6e 3d 22 31 2e 31 22 20 78 6d 6c
0000090 6e 73 3d 22 68 74 74 70 3a 2f 2f 77 77 77 2e 74
                                                                                
$ hexdump will_open.gpx| head 
0000000 ef bb bf 3c 3f 78 6d 6c 20 76 65 72 73 69 6f 6e
0000010 3d 22 31 2e 30 22 20 65 6e 63 6f 64 69 6e 67 3d
0000020 22 75 74 66 2d 38 22 3f 3e 0d 0a 3c 67 70 78 20
0000030 78 6d 6c 6e 73 3a 78 73 69 3d 22 68 74 74 70 3a
0000040 2f 2f 77 77 77 2e 77 33 2e 6f 72 67 2f 32 30 30
0000050 31 2f 58 4d 4c 53 63 68 65 6d 61 2d 69 6e 73 74
0000060 61 6e 63 65 22 20 78 6d 6c 6e 73 3a 78 73 64 3d
0000070 22 68 74 74 70 3a 2f 2f 77 77 77 2e 77 33 2e 6f
0000080 72 67 2f 32 30 30 31 2f 58 4d 4c 53 63 68 65 6d
0000090 61 22 20 76 65 72 73 69 6f 6e 3d 22 31 2e 31 22
```

`will_open.gpx` has a bom (3 bytes in the beginning of the file, `ef bb bf`), and `won't_open.gpx` doesn't have. I think that this is the whole difference, because after that both of the files are similar.  
Attached files: [Archive.zip](https://github.com/IsraelHikingMap/Site/files/1910077/Archive.zip)

**Comment by HarelM** [comment]
Thanks for your report, I'll see if I can understand what had changed.

**Comment by HarelM** [comment]
@hagai-lvi I'll need your help here.
I've opened the files in notepad++ and I see a difference in the xml header.
wont_open.gpx:
`<?xml version="1.0"?>`
will_open.gpx
`<?xml version="1.0" encoding="utf-8"?>`

Can you check that if you manually edit the won't open to have the `encoding="utf-8"` attribute it will open on your device?
Regardless, this is probably a needed fix and I'll try to include it in my next release.

**Comment by zstadler** [comment]
It seems like will_open is using utf-8 encoding, which implies (a) a bom sequence and (b) encoding in the xml header.

Since the GPX file can include non-latin characters, I suggest we find a way to continue and produce utf-8 encoded files.

**Comment by HarelM** [comment]
I've created a file after a small fix I made to add the utf8 header.
@hagai-lvi can you please check that this file works before I publish the fix?
[should_open.gpx.txt](https://github.com/IsraelHikingMap/Site/files/1910195/should_open.gpx.txt)

**Comment by HarelM** [comment]
I'll deploy the fix in the next few days. If you can do the check above just to make sure this is the root cause of this issue it would be great since I don't have a good way of testing it...

Thanks again for reporting! Our ability to test our application is limited and I can't stress enough how valuable the fact that you took the time and opened an issue here :-)

**Comment by hagai-lvi** [comment]
@HarelM Tried what you've asked:
Replaced `<?xml version="1.0"?>` in will_open.gpx with `<?xml version="1.0" encoding="utf-8"?>`
**It still won't open**, so this doesn't solve it. Only adding the bom...

**Comment by HarelM** [comment]
@hagai-lvi I have uploaded the fix. It seems like there's still an issue with writing the encoding header which I can't seem to be able to reproduce when running locally.
Can you check though if it help in some way?

**Comment by HarelM** [comment]
FYI: I've edited my last message.

**Comment by hagai-lvi** [comment]
Interesting, it does work, but the route is dated 1/1/1970, which isn't the case for routes I've planned with the site in the past. I'll investigate it further in the evening and I'll write my observations here.

**Comment by hagai-lvi** [comment]
OK @HarelM , my bad, Everything works flawlessly.
Thanks a lot for being so responsive and solving this so fast!

You can close the issue as far as I'm concerned.

**Comment by HarelM** [comment]
Thanks for reporting!
