### ISSUE TITLE
add to osm dont work when try to update

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#685]
## Bug

Copy from https://github.com/IsraelHikingMap/Map/issues/206 @Orrgvili :

i upload new recording of updates made to single 
cant update the new parts 
i received the following massage 
לא ניתן לשלוח את המסלול

[SinglMitar_new.gpx.txt](https://github.com/IsraelHikingMap/Map/files/1931292/SinglMitar_new.gpx.txt)

**Comment by HarelM** [comment]
@Orrgvili I'm able was able to upload the file and look for missing routes:
![image](https://user-images.githubusercontent.com/3269297/39043513-4fee0ce6-4496-11e8-8378-688b0fc6825f.png)
![image](https://user-images.githubusercontent.com/3269297/39043573-736da618-4496-11e8-8308-305bbd5cacef.png)

**Comment by Orrgvili** [comment]
the add to OSM dont work 
if we are on it why there is difference between the  read and blue line ?  

![image](https://user-images.githubusercontent.com/10514419/39082021-be78bdf0-4554-11e8-9bd4-91e4e2f0d87a.png)

**Comment by HarelM** [comment]
Thanks for the clarification, I'll see why it's not working.
The difference between the red and blue line are that the blue is the original recording and the red is a simplified version to upload to OSM (Which should be simple and with less points much like hand tracing).

**Comment by zstadler** [comment]
> The difference between the red and blue line are that the blue is the original recording and the red is a simplified version to upload to OSM (Which should be simple and with less points much like hand tracing).

We had an internal discussion about this simplification. Unfortunately, I failed to convince @HarelM that the current settings are over-simplifying the trace. Personally, I trace streams at higher accuracy...

**Comment by HarelM** [comment]
I think I can reproduce the issue.
@Orrgvili Can you please check your history to see what the algorithm did do? I tend to think it added some unwanted point - worth deleting them since I think it failed mid way...

**Comment by HarelM** [comment]
It will probably show up as the following white drops:
![image](https://user-images.githubusercontent.com/3269297/39082383-15b031b0-455b-11e8-8170-c1b8b1dff27e.png)

**Comment by zstadler** [comment]
It's https://www.openstreetmap.org/node/5566049721

**Comment by zstadler** [comment]
It also looks like https://www.openstreetmap.org/node/5568510452 and https://www.openstreetmap.org/node/5568510452, both created by IHM, are separate nodes at the same position.

**Comment by HarelM** [comment]
Seems like this issue had discovered a bug in OsmSharp.Core here:
https://github.com/OsmSharp/core/issues/54
I have written a workaround until this issue will be fixed.

**Comment by HarelM** [comment]
Published, Please note that I have made very little test to make sure this works.
I have also uploaded some of the part of the trace to test my code so they won't show up as missing now...

**Comment by Orrgvili** [comment]
encounter problem with this upload method   
look at the link https://israelhiking.osm.org.il/#!/?s=1aghqqeGoZ
an look at the screen capture 
![image](https://user-images.githubusercontent.com/10514419/39091808-97e1de1c-4606-11e8-9c55-e678858540e8.png)
it was uploaded wrong  the generalization removed too many vertexes

**Comment by HarelM** [comment]
True, but this was evident from the algorithm suggestions. It was up to you to decide if the results are satisfying or not.
While the suggestions can probably improve the fact is that very few people are actually using this feature and it takes a lot of effort to improve it.
I'll open another issue for it nevertheless.
