### ISSUE TITLE
Improve missing lines prolong mothod

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#687]
## What I expect to happen
Prolonging a line should be less simplified

## What really happened
Simplification takes the first and last point only so the line is over simplified.

## What I did that caused the issue - step by step
See issue #685 

## Thing I think the developers should know, images, links etc.
The original reason for this was to remove going back and forth on the same line - this has a higher priority than simplification.

Here are the relevant examples:
Too simplified:
![image](https://user-images.githubusercontent.com/3269297/39092188-bc429800-4610-11e8-8364-5edb3e216bd7.png)
Missing part:
![image](https://user-images.githubusercontent.com/3269297/39092190-c6e328ec-4610-11e8-9207-b567bcaf81e1.png)

**Comment by zstadler** [comment]
Another example with a potential issues:

![image](https://user-images.githubusercontent.com/1304610/39915406-8e019432-5510-11e8-9211-45f874d41924.png)

1. Track over-simplification
2. After simplification the proposed new way is farther from the GPS recording than the existing road
3. Proposed short segments, seemingly below the threshold
4. Two overlapping proposed ways

The GPX source is [Keshet_Cave.zip](https://github.com/IsraelHikingMap/Site/files/1994569/Keshet_Cave.zip)

**Comment by zstadler** [comment]
A newly-created way, in yellow below, overlaps with an existing road, in green.

https://overpass-api.de/achavi/?changeset=58950920

![image](https://user-images.githubusercontent.com/1304610/40014814-36d44860-57ba-11e8-8b9f-f27e40bc334a.png)

**Comment by zstadler** [comment]
Here is the relevant snippet: [Gvaot Gad.zip](https://github.com/IsraelHikingMap/Site/files/2008249/Gvaot.Gad.zip)

**Comment by moshfeu** [comment]
Following to #711, the algorithm is better but still missing new route, here:

https://israelhiking.osm.org.il/map/17/32.0232/34.8447

with the track:

https://www.openstreetmap.org/user/Mosh%20Feu/traces/2721478

![screen shot 2018-06-05 at 2 44 40 pm](https://user-images.githubusercontent.com/3723951/40974156-622b28a0-68cf-11e8-8485-9a56dbb5d47d.png)

**Comment by HarelM** [comment]
I think that in this case the lines that need to be added is too short - minimum missing line length is 250 meter, I think... I'll check it never the less when I'll work on this issue.

**Comment by moshfeu** [comment]
I have more examples on this track:

https://israelhiking.osm.org.il/map/16/32.0235/34.8734

![screen shot 2018-06-05 at 3 40 08 pm](https://user-images.githubusercontent.com/3723951/40976404-c1cfe294-68d6-11e8-8922-374218ded15c.png)

<hr />

https://israelhiking.osm.org.il/map/18/32.0151/34.8496

![screen shot 2018-06-05 at 3 41 02 pm](https://user-images.githubusercontent.com/3723951/40976446-e093409a-68d6-11e8-970f-73e3d578e52b.png)

**Comment by HarelM** [comment]
I have looked at all the above examples. I think they make sense in terms of what the algorithm should do.
This is how keshet cave results look:
![image](https://user-images.githubusercontent.com/3269297/42716808-177913a8-8706-11e8-8760-d735c6c94f48.png)
This is how single Meitar looks - the missing part in the end is due to a recording that was cut before reaching a road, so it probably can be improved but I prefer not to add a special case for recrding start and end segments.
![image](https://user-images.githubusercontent.com/3269297/42716909-852c1648-8706-11e8-8d7d-cfa1312cbf20.png)
I'll open a different issue for the givat gad wrong artifact since it's in a different part of the code.

**Comment by HarelM** [comment]
Closing this for now as I currently don't have any improvements I would like to do in the algorithm. In case there will be new cases that require improvements in the future a new issue will be open or this issue will be open.
