### ISSUE TITLE
iFrame share is zoomed out

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#690]
## What I expect to happen
iframe for the following share should present it as expected:
https://israelhiking.osm.org.il/#!/?s=CRKxpnRNAs

## What really happened
![image](https://user-images.githubusercontent.com/3269297/39419642-7481d1fc-4c69-11e8-848d-19f86e65c7a5.png)

Based on user input.

**Comment by HarelM** [comment]
The following code generate the below image:
`<iframe src="https://israelhiking.osm.org.il/#!/?s=CRKxpnRNAs" width="600" height="600" frameborder="1" scrolling="no"></iframe>`
which looks correct to me.
![image](https://user-images.githubusercontent.com/3269297/39419980-105e8394-4c6b-11e8-8cf4-8063e71abe3c.png)

**Comment by avrahamg** [comment]
<iframe id="MapIHM" src="" width=100% height=50% frameborder="0" style="border:0; display: none;"></iframe>
That's the iframe i used, js use php to add the src, as a http link.

**Comment by avrahamg** [comment]
http://achataim.000webhostapp.com/www/trip.php?foreignName=kiryatata
Here is an example of a web page, that its iframe loaded zoomed out.

**Comment by HarelM** [comment]
Thanks for the input, I'm not sure what's causing this bug.
Can you try removing the animation and see if it helps?
The iframe in the site looks fine after updated with the link so I don't have a good idea what can cause this.
your guess is as good as mine...

**Comment by HarelM** [comment]
I see. 
The location is embedded in the share, so there's no need to specify it.
Your share is fine and shows the right location when not used in your site (see my example above).
Is there a way for you to try and create a simpler reproduction of this issue? Maybe using plunkr or fiddler?
Can you just test and see if removing the animation helps - I understand this is a site requirement but I want to understand if this is the root cause or not...

**Comment by avrahamg** [comment]
Ok.
I'll try it later today, after working hours.
Thanks.

**Comment by avrahamg** [comment]
I tried to remove the animation, and it works fine.
:-(

**Comment by HarelM** [comment]
I think it has to do with the fact that the iframe size changes - maybe you can do the animation on a white rectangle and just hide and show the iframe when the animation is complete? I don't know...
If you find out something that I'll be able to use to fix this let me know...

**Comment by avrahamg** [comment]
Finally i found a time to check it out.
Now it works fine, i changed the jquery effect to "blind".
Thanks a lot! :-)

**Comment by HarelM** [comment]
Thanks, can I close this issue then?

**Comment by avrahamg** [comment]
Yes.
Thanks again.
