### ISSUE TITLE
Map height graph width 

### ISSUE THREAD

**Issue by olevi70** [IsraelHikingMap/Site#691]
## What I expect to happen
suggested to expend height graph width on full screen width (or allow two expend levels, half width and full width). 

## What really happened
currently fully expended occupies only half screen width.

## My environment
firefox 59.0.3 (64-bit)
chrome   66.0.3359.139 (Official Build) (64-bit)

**Comment by HarelM** [comment]
This requires migrating to scss - which I'm currently investigating.

**Comment by HarelM** [comment]
Full:
![image](https://user-images.githubusercontent.com/3269297/43009913-abce9438-8c47-11e8-9d31-8bda5d95d1ce.png)
With Sidebar:
![image](https://user-images.githubusercontent.com/3269297/43009926-b6e84aee-8c47-11e8-97a8-7d591b07668f.png)
Normal:
![image](https://user-images.githubusercontent.com/3269297/43009944-c03f02ea-8c47-11e8-96b9-84c19dc74ee9.png)
Mobile:
![image](https://user-images.githubusercontent.com/3269297/43009967-ced6e728-8c47-11e8-93f1-056b58de1eec.png)
