### ISSUE TITLE
No auto-close for messages resulting from long operations

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#695]
### What I expect to happen
When a message appears after a long operation, the message will close only after a user click. 

### What really happened
Messages from long operations may show and disappear without the user noticing them. This applies to both confirmation and error messages. AFAIK, such long delays exist only for server operations. The long operations that come to mind are: POI updates, image uploads, and GPS recording analysis for missing ways.

### Things I think the developers should know, images, links etc.
IMO, it would be best if the dismissal of any server-driven message will be automatic, only if the operation took less than a given time (3-5 seconds).
Alternatively, require manual dismissal only for messages of specific server operations, regardless of their delay.

**Comment by HarelM** [comment]
I agree this is needed, but can we do it only if the operation fails? I think that if the operation succeeds then this will be annoying. When the operation is still running a progress bar should appear somewhere on the screen...

**Comment by HarelM** [comment]
This commit only handled unmapped routes and upload public POI.
In case there are more places please let me know and I'll add, I have created the required infrastructure for this.
