### ISSUE TITLE
Immediately show the formats list for Save-As

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#698]
### What I expect to happen
The list of formats to be visible immediately after the  "Save-As" button is clicked:
![image](https://user-images.githubusercontent.com/1304610/39996945-dbcc2896-5789-11e8-88b1-aa1ecfb97e84.png)

### What really happened
![image](https://user-images.githubusercontent.com/1304610/39997001-fc4be232-5789-11e8-8902-afebfe2e2e22.png)
This step is not useful because the only thing the user can, and should do, is expand the list. 
On the other hand, it may not be very clear to the user that there is a collapsed list there.

**Comment by zstadler** [comment]
Thanks!

**Comment by HarelM** [comment]
You are welcome :-) this is also available on the beta site in case you want to get the feeling of it.
