### ISSUE TITLE
indicate start and end of route

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#70]
Maybe green and red dots inside the drop icons?
Otherwise you reverse the route and nothing visible happens.

**Comment by HarelM** [comment]
True. I'll see if I can put arrows on the route it self if it is easier...

**Comment by zstadler** [comment]
I prefer different Start and End icons than barely visible arrowas a-la
Waze.
IMO, OruxMaps' animated " > > > > > >" style is a second-best option.

**Comment by valleyofdawn** [comment]
Here's an option
![route1](https://cloud.githubusercontent.com/assets/689201/9382986/0e7246d0-474e-11e5-8ae0-7b8e9ef6d102.jpg)
