### ISSUE TITLE
add option to upload to Wikimedia Commons with my user

### ISSUE THREAD

**Issue by amiad** [IsraelHikingMap/Site#700]
<div dir="rtl">
אני מעדיף לעלות את התמונות ל־IHM תחת המשתמש שלי בוויקישיתוף.

כרגע אם אני מעלה אותן דרך הממשק של האתר הן עולות תחת המשתמש של IHM.

יש את האפשרות לעלות עצמאית את התמונה לוויקישיתוף ואז להכניס את הקישור לתגית image אבל זה הרבה יותר מסורבל.

אשמח אם תוסיפו את האפשרות לעלות תמונות למשתמש שלי ולא רק למשתמש הכללי.
<div>

**Comment by HarelM** [comment]
בגדול, זה מאוד מסובך ודורש כניסה לחיסכון ויקישיתוף דרך האתר.
התמונות שמועלות מצביעות לחשבון או אס אם של המשתמש שהעלה אותן.
מעבר לסדר הטוב, תוכל לפרט למה אתה מעדיף שהתמונות יעלו דרך החשבון שלך?

**Comment by amiad** [comment]
<div dir="rtl">
כן, ברור לי שזה ידרוש התחברות לחשבון הוויקישיתוף האישי.

אני רוצה שאוכל בעתיד לראות את התמונות שהעליתי כולל למשל שימוש בהן בוויקיפדיה ולא לחפש אותן בין שאר התמונות של המשתמש הכללי. 


אני בטוח שאתה זוכר שאם מעלים תמונה לוויקישיתוף היא יכולה לשמש במקומות אחרים וזה לא רק מקום שמירה לתמונות עבור IHM.

תודה
</div>

**Comment by HarelM** [comment]
Switching to English, sorry...
Double login is a huge hassle. Nevertheless, Pull request is welcome. A UX definition is welcome too.
Images that were uploaded can be used, regardless of the user who added them, I agree it might be annoying to find the image you uploaded.
Also wikipedia pages are used in IHM so if you prefer to edit wikipedia and not OSM you are more than welcome to. IHM will merge points when possible.
As you said, there's a workaround. You can always write a tool to upload an image to your wikimedia account. This site's major focus is OSM though.

**Comment by HarelM** [comment]
Looking back at this issue, an advanced user can upload a file to wikimedia and link it from OSM. Both editors are outside the scope of this site, adding a secondary login management is too complex at this point.
