### ISSUE TITLE
Improve site performance when opening a POI

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#702]
## What I expect to happen
When opening a POI that was opened by another user and nothing changed since then I would like the loading time to improve.

## What really happened
I'm waiting for points that were fetched by the server multiple times.

## What I did that caused the issue - step by step
Open a POI from wikipedia for example.

## Thing I think the developers should know, images, links etc.
iNature items are cleaned and cached every database rebuild - this can improve rebuild time too.
I have sent a mail to Nakeb and asked them to add this info to the API contract we are using.
I think wikipedia and therefore iNature has this info built-in in the data, still need to look at off-road info.

**Comment by MatanBenMoshe** [comment]
I have added the "last_modified" field to Nakeb API.
Let me know if it's fine for your needs.

**Comment by HarelM** [comment]
Thanks! I'm guessing that all time stamps are the same since the this field didn't exist in the database before but it will be maintained in the future, right?

**Comment by HarelM** [comment]
iNature and Wikipedia both support the following API call:
https://www.mediawiki.org/wiki/API:RecentChanges
Which should help.

**Comment by HarelM** [comment]
Current implementation is naive - it stores a POI that was opened in elastic search index - kind of database cache that is valid for 30 days (configurable).
The implementation of recent changes is more complex and I don't have a good idea currently how to solve it for all POI providers.
