### ISSUE TITLE
Cant upload GPX file 

### ISSUE THREAD

**Issue by Orrgvili** [IsraelHikingMap/Site#709]
try to upload GPX file to view
and got  the massage  "לא ניתן להעלות את הקובץ"
tried it again with file i loaded in the past and same result

**Comment by HarelM** [comment]
Please elaborate on what you define as upload.
Please attach the relevant file.

**Comment by HarelM** [comment]
Seems like an issue with upload to OSM.
I'll check it tonight.
Thanks for reporting!

**Comment by HarelM** [comment]
I don't fully understand why this stopped working. I'm getting a 404 from OSM API.
See issue here:
https://github.com/openstreetmap/openstreetmap-website/issues/1889
@Orrgvili if there's a way for you to check that the OSM API is working without using my code I'll be able to confirm or deny this is an issue with my code, if you can't we'll need to wait for a response from OSM team.

**Comment by Orrgvili** [comment]
you fixed it before i test what you asked
