### ISSUE TITLE
Implement four routing modes

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#71]
On the longer run, if a suitable service is found, would be nice to match routes for hikers, MTBikers, 4W drivers and commuters.

**Comment by HarelM** [comment]
Agree, I wonder how this was left out...

**Comment by HarelM** [comment]
Related links:
http://www.liedman.net/2015/04/13/add-elevation-data-to-osrm/
http://brouter.de/brouter/
http://osm2po.de/
https://github.com/graphhopper/graphhopper/

**Comment by HarelM** [comment]
Manged to create a local graphhopper web service on my PC using the following instructions:
https://github.com/graphhopper/graphhopper/blob/master/docs/web/quickstart.md
changed the configuration as follow:
```
graph.flagEncoders=car,foot,mtb
osmreader.instructions=false
```
Elevation is not tested yet.
this is an example for a request that yielded results:
```
http://localhost:8989/route?point=31.8239,35.0375&point=31.8213,35.0965&instructions=false&points_encoded=false&vehicle=foot
```
Next step: combine this with .Net Web API for both height and routing.
