### ISSUE TITLE
Find unmapped routes mark the whole track as unmapped

### ISSUE THREAD

**Issue by moshfeu** [IsraelHikingMap/Site#711]
## What I expect to happen

Only unmapped routes will mark as unmapped. (The track's color will be blue). 

## What really happened

The whole track seems to be unmapped (The track's color is red) including mapped routes, of course.

## What I did that caused the issue - step by step

I uploaded a GPX file and try to add untracked tracks via the UI.

## My environment 
* Operating System and version: irrelevant
* Web Browser and version: irrelevant

## Thing I think the developers should know, images, links etc.

![screen shot 2018-06-04 at 8 30 33 am](https://user-images.githubusercontent.com/3723951/40899847-a32ac332-67d1-11e8-9186-856053600fc8.png)

The track: https://www.openstreetmap.org/user/Mosh%20Feu/traces/2721478

**Comment by HarelM** [comment]
Can you make sure the route is public? I can't see it...
Seems like the issue is with the highways database on the server and not the missing routes algorithm.
You can see that snapping is also not working which is a good indication for that.
I'll check it tonight, Thanks for reporting!

**Comment by moshfeu** [comment]
Sorry, I public'ed it now.
Thanks.

**Comment by HarelM** [comment]
Probably related to the same root cause as #712 - issue with database rebuild after upgrading a library I'm using.
Please try it tomorrow after I'll publish a version and have the databases rebuild.

**Comment by moshfeu** [comment]
Sure. Thanks!

**Comment by moshfeu** [comment]
Still not done. I replied in #687  and closing this.
