### ISSUE TITLE
Simplify adding image to existing OSM POI

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#716]
Feature

In preparation for the upcoming mapping party I'd like to simplify adding images to existing OSM POI.

I suggest making go-tagged image POIs draggable.
Dragging and snapping it to a nearby existing OSM POI, followed by "upload to OSM" would update the OSM node with the image.

**Comment by HarelM** [comment]
It can work, but I think it's complicated and not intuitive.
Another option is to ask the user when he opens/drags an image to add it to an existing api, but that can be annoying if that not what you want to do.
Another option can be done with shares - once a user creates a share of a route containing images there will be a button to check if any of the images can be added to exiting pois.
And there's also the option to create a dedicated page/site for it.
My main concern here is not the feasibility but the UX.
If you have other ideas I'll be happy to know.

**Comment by HarelM** [comment]
Another option is to make everything faster by either keeping the image in the client side browser or reduce the file size.
An interesting piece on resolution and compression can be seen here:
http://users.wfu.edu/matthews/misc/graphics/ResVsComp/JpgResVsComp.html
I'm still struggling to define the right file size / resolution to keep assuming I resize and then upload the image to the server.

**Comment by valleyofdawn** [comment]
We can safely assume that most images will be uploaded for personal use and not to OSM POIs.
Therefore we shouldn't bother the user with extra dialogues at the initial upload stage.
Maybe once the user presses the "upload" button, we can check if there's a POI within 50m. If there is, we can ask them if they should be merged.
As for resolution and compression. I would go with a 1920 width and medium JPG quality.
Can a thumbnail be uploaded first with the actual transfer of the larger file happening in the background afterwards?

**Comment by HarelM** [comment]
I tend to agree with the idea to ask the user when he wants to upload a private POI and make it public to reduce the creation of duplicate points.
There is an option to show and image with the location fast but uploading in the background is a risk of not knowing to which POI the image belongs to - also if the user delete the POI its creating an even higher risk of things breaking down.
I'm exploring the possibility to keep the data in the client side only without uploading it to the server at all for private POIs only.
The problem with this approach is that it will create heavier GPX files and heavier shares.
Which might require us to go over the database and convert binary images data to URL every night or so to reduce database size.
I'm not sure I'll be able to finish a stable version until 3.7, maybe a beta with this approach...

**Comment by HarelM** [comment]
The following should be the expected behavior when trying to upload a point that is close enough to another point, there's currently and issue that opening an image will move the map to zoom 20 so the points are not close enough, it will be fixed but not for Tuesday.

![image](https://user-images.githubusercontent.com/3269297/42129014-4e3f05cc-7cc1-11e8-9341-9f1c79d804dd.png)

Also it might take a few seconds for the pop-up to appear as it send a request to the server, wait time UX can be improved but I think it will be enough for Tuesday, assuming everything will work as expected.

**Comment by valleyofdawn** [comment]
POI upload interface issues:
Multiple bugs and improvements sorted from critical to less so
1.	Portrait photos are uploaded horizontally like so:
 ![image](https://user-images.githubusercontent.com/689201/42135676-c8c53330-7d56-11e8-9a82-31957fdb7c4f.png)

2.	After uploading a photo, clicking on the POI icon shows it. Clicking on the tooltip with its name just below it shows a different dialog box, without the photo.
3.	The POI it asks to update is the closet one. When dragging a tourist attraction to “yad Avshalom” it asked wheather to update the nearest restaurant.
Users are unlikely to update restaurant photos through our site. Select only POIs of certain types or categories.
4.	When a non-geotagged image is dragged into the map, a vague error message appears. Please change it to: the location this image was taken is unknown, Can’t open. For future 
5.	When an existing POI has no title and the interface wants to merge a photo POI with it, the confusing message “Would you like to update: undefined?” appears. Instead lets use  use the category and type. Like so: Would you like to update the nearby memorial?. Bear in mind that many trees, viewpoints waterfalls etc. do not have names.
6.	No need for “הוסף קישור” – one website is enough for a rudimentary OSM editor. Multiple ones can be handled through iD. If anything, **elevation** would make more sense.  
7.	Tap water / מי שתייה should be added to the water category. This is an essential resource for planning longer trips – both on foot and on MTB. If you feel space is limited, unite the well and cistern to make space.
8.	The nature category is impoverished. I would add “geological attraction” to the list. I designed an icon previously.
9.	Shouldn’t lone tree be changed to tree – very impressive trees can be found in a forest for instance?
10.	The POI upload dialog requires  scrolling in mobile devices and small laptops. We can avoid it be eliminating extra gray space. 
11.	The OK button may be better placed at the bottom of the POI OSM upload dialog

**Comment by valleyofdawn** [comment]
I think the first issue is a show stopper. Many users would stop in their tracks if they see their image uploaded sideways.  The rest can wait.

**Comment by HarelM** [comment]
Fair enough. I'll do my best to fix it tonight.

**Comment by valleyofdawn** [comment]
The image orientation now works fine as well as the double dialog issue.
We should discuss again the types of POIs, but this can wait. (I'm also missing peaks which are not viewpoints).

**Comment by HarelM** [comment]
I'm closing this issue as I don't think there's anything left to implement as part of this feature.
If you think there are things to improve please open a separate issue or use an existing one such as #454.
