### ISSUE TITLE
בעיה בכניסה למערכת

### ISSUE THREAD

**Issue by shimontropper** [IsraelHikingMap/Site#717]
## Bug/Feature
לא מצליח להכנס למערכת עם שם משתמש וסיסמא שלי
## What I expect to happen
להכנס למערכת ולראות את כל המסלולים שלי

## What really happened
נפתח חלון קטן עם מפה בתוכו

## What I did that caused the issue - step by step
לחצתי על כניסה למערכת
נתתי הרשאות
הופיעה החלון הקטן

## My environment
* Operating System and version:
Windows 10
* Web Browser and version:
Chrome 67.0.3396.87
## Thing I think the developers should know, images, links etc.
![image](https://user-images.githubusercontent.com/29043979/41410710-04420342-6fe3-11e8-8a3d-77230be75441.png)

**Comment by HarelM** [comment]
Thanks for reporting!
I can reproduce the issue.
Will be fixed hopefully tonight.
Sorry for the inconvenience.

**Comment by valleyofdawn** [comment]
I also suffered from this issue when reported and now it's okay.
