### ISSUE TITLE
REQUEST: add Arcgis online servers as base maps

### ISSUE THREAD

**Issue by krooven** [IsraelHikingMap/Site#718]
## Feature
It Would be very useful if one could add an Arcgis online map server like the xyz servers.
ARCGIS ONLINE is a gateway to alot of map servers, like old maps (similar to the British mandate map uploaded to the project recently), aerial photos, government data and more.

It should be possible using this leaflet tool kit here:
https://github.com/Esri/esri-leaflet
or similar tools.

Thank You
Reuven

**Comment by HarelM** [comment]
@krooven any new about this issue?
Can I close it?

**Comment by krooven** [comment]
Unfortunately aadding maps in IHM only support TMS (and WMS?).
ArcgisOnline is a different web service.

Please refer for these server as example, It can't be added as basemap nor as layer in IHM:
https://ags.moin.gov.il/arcgis/rest/services/PlanningPublic/allplans/MapServer/0
https://ags.moin.gov.il/arcgis/rest/services/PlanningPublic/road_compilation/MapServer/0
https://maps.gsi.gov.il/arcgis/rest/services/Geo50K/Geo50K_Ashdod_2004/MapServer

but leaflet is indeed support ArcgisOnline server as mention above.

I think it can be a great feature.

**Comment by HarelM** [comment]
Can you check if the following documentation is the right layer?
https://esri.github.io/esri-leaflet/api-reference/layers/feature-layer.html
In theory, assuming the above is the right implementation, I don't see a reason why it shouldn't work.
I'll test it soon and update if this is simple or not.

**Comment by krooven** [comment]
It should be fine, at least for vector data (adding as layer) not sure it helps to add the server as basemap.
Anyway maybe the plugins here can help it http://esri.github.io/esri-leaflet/plugins/

Thanks

**Comment by HarelM** [comment]
@krooven I've tried to implement both MapServer and FeatureLayer. I'm not sure how well I managed to do it.
I would very much appreciate if you can do some tests to see that it works as expected and report here.
Thanks ahead.
