### ISSUE TITLE
Tick marks on height profiles

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#72]
Would help legibility

**Comment by HarelM** [comment]
Can elaborate? this issue is not clear.

**Comment by valleyofdawn** [comment]
To the left of the numbers on the Y scale and above the ones on the X scale should be tick marks - short lines showing where exactly the numbers fall.
![xamgauge_add_tick_marks_to_gauge_01](https://cloud.githubusercontent.com/assets/689201/9382948/a85341b0-474d-11e5-8b8a-37274f467c8a.png)

**Comment by HarelM** [comment]
The following is the library I'm using.
https://github.com/n3-charts/line-chart
You are welcome to open an issue there and ask them, I didn't find it in their documentation.

**Comment by valleyofdawn** [comment]
They just added inner ticks at my request.

**Comment by HarelM** [comment]
This way probably already implemented. updated reference and relevant code. Thanks!
