### ISSUE TITLE
Support shapefile

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#720]
## Feature
I would like to be able to open a shapefile as a route in the site.

**Comment by noamrozenfeld** [comment]
[Turkish_trenches_beersheva.zip](https://github.com/IsraelHikingMap/Site/files/2108419/Turkish_trenches_beersheva.zip)

Example of a shapefile. From Deshe data of Beer Sheva survey

**Comment by HarelM** [comment]
Can you attach a screenshot of what supposed to be the right outcome?
The server uses GPSBabel in order to convert file formats.
I tend to think it won't be able to handle these files.
This is the regular output of this format? a zip file?
I got something very strange when converting the files you gave me:
![image](https://user-images.githubusercontent.com/3269297/41502695-d0702840-71c8-11e8-91e8-08cfa872cc51.png)
This is the converted file, probably the issue is with the fact that it uses ITM coordinates?
[gpx.gpx.txt](https://github.com/IsraelHikingMap/Site/files/2108533/gpx.gpx.txt)
I'm a bit lost here... any help will be appreciated...

I'm also not entirely sure there's a valid use case here, this is not intended as a GIS software, it is intended for outdoor activity planning.
So a valid use case would help too :-)

**Comment by HarelM** [comment]
Closing this for lack of response and lack of definition how this would help outdoor activities.
