### ISSUE TITLE
Update icons according to map

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#721]
## Feature
see here: https://github.com/IsraelHikingMap/Map/issues/160

This issue will be used for the relevant commits in this repository.

**Comment by HarelM** [comment]
According to @valleyofdawn:
"Also you have not changed the monument icon to what was agreed upon and the campsite should be brown".
Shouldn't viewpoint be brown too?

**Comment by valleyofdawn** [comment]
Yes, I believe everything related to tourism should be brown.
