### ISSUE TITLE
Printing doesn't work as expected

### ISSUE THREAD

**Issue by amirlevko** [IsraelHikingMap/Site#722]
## What I expect to happen
the print area would open around the centered area of the map
or even show the printing area rectangle before moving on to opening the browser's printing page (feature?)

## What really happened
the browser's printing window opened around a different area than the one centered on the map. usually to the left and down

## What I did that caused the issue - step by step
centering the map
clicking the printing icon

attached below are pics from before and after clicking the printing icon

## My environment
* Operating System and version: win 10
* Web Browser and version:  chrome Version 67.0.3396.87 (Official Build

## Thing I think the developers should know, images, links etc.

![image](https://user-images.githubusercontent.com/40337026/41508373-7169aba8-724c-11e8-8efb-b2c2e9c91b55.png)

![image](https://user-images.githubusercontent.com/40337026/41508379-85ee3eea-724c-11e8-8129-7443fff39bef.png)

**Comment by HarelM** [comment]
Not sure I have a lot to do with this issue. this is how the browser decides what to print...
You can always use <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>s</kbd> and select the relevant part you want to print...

**Comment by amirlevko** [comment]
Thanks for the quick response.
are you sure about  ctrl+shift+s ? seems to not work for me.

i've attached a link to a third party app on my post (https://inkatlas.com/create/) you can check it out as a future feature

**Comment by valleyofdawn** [comment]
Doesn't it work better using landscape mode?

**Comment by amirlevko** [comment]
not really... try it. 
you get more width, but it still centers to the left

**Comment by amirlevko** [comment]
i fully agree that it has low priority. but just to clarify... :)
what your'e suggesting makes an ok map, snapping a screenshot is not really a good practice when printing  a map for several reasons (quality, details, page organisation etc)

compare these two 

[atlas-121293.pdf](https://github.com/IsraelHikingMap/Site/files/2111282/atlas-121293.pdf)
[a.pdf](https://github.com/IsraelHikingMap/Site/files/2111284/a.pdf)

**Comment by valleyofdawn** [comment]
The page looks similar to the screen when in the printing dialogue you use landscape + scale down to ~52% (might be resolution specific).
It's an ugly workaround but it works.

**Comment by valleyofdawn** [comment]
## Bug - specific to the beta version of December 2018
[Israel.Hiking.Map.pdf](https://github.com/IsraelHikingMap/Site/files/2648931/Israel.Hiking.Map.pdf)

## What I expect to happen
Printing the map would preserve the x-y ratio

## What really happened
The map was distorted to fit the printed page 

## What I did that caused the issue - step by step
Clicked the print button from the web page
Selected a printer (e.g. PDF)
Set the layout to portrait (it also happens in landscape but is less noticeable)
## My environment
* Operating System and version: win 10
* Web Browser and version: Latest Chrome 

## Thing I think the developers should know, images, links etc.
[Israel Hiking Map.pdf](https://github.com/IsraelHikingMap/Site/files/2648901/Israel.Hiking.Map.pdf)
