### ISSUE TITLE
The route not pass through highway=steps

### ISSUE THREAD

**Issue by amiad** [IsraelHikingMap/Site#724]
## What I expect to happen
If have steps in route theroute not pass through them.

## What really happened
The route will pass them.

## Thing I think the developers should know, images, links etc.
See: https://israelhiking.osm.org.il/share/HRqiAIrPtD

**Comment by HarelM** [comment]
I agree. Bike routing should not go through stairs, IMHO.

**Comment by amiad** [comment]
OK, but we need to fix it for hiker.

**Comment by HarelM** [comment]
It does route though steps in hiker mode, I don't understand why, but this particular case fails.
I've also tested this place in openstreetmap site using graphhopper and hike profile to see that this is not locally to our site.
Probably mapping issue, but I can't find out what (sac_scale?).
![image](https://user-images.githubusercontent.com/3269297/41605049-48eaa5e4-73e9-11e8-9b85-a73b92e84945.png)
Steps in another location that performs as expected:
![image](https://user-images.githubusercontent.com/3269297/41605152-851c4d88-73e9-11e8-9ae8-c5e594f38ad8.png)

**Comment by HarelM** [comment]
Incorrect tagging of sac_scale: `3` is not a valid sac_scale value. 
https://www.openstreetmap.org/way/489130473
See here how it should be mapped:
https://wiki.openstreetmap.org/wiki/Key:sac_scale

**Comment by amiad** [comment]
Thanks.
I remove `sac_scale` from the way.

I don't sure Dargiot should be marked as steps.
