### ISSUE TITLE
BaseLayer doesn't work for URL in new address sceme

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#726]
## What I expect to happen
The following address should put set the base layer to be IMTBM:
https://israelhiking.osm.org.il/url/http:%2F%2Fwww.groopy.co.il%2Ffiles%2Fmaslul%2F2213gps.gpx?baselayer=Israel_MTB_Map

## What really happened
The file loads, the base layer doesn't change.

## What I did that caused the issue - step by step
surf to the above address

## My environment
* Operating System and version: Win 7
* Web Browser and version: Chrome

## Thing I think the developers should know, images, links etc.
It used to work with the following address:
https://israelhiking.osm.org.il/#!/?baselayer=Israel_MTB_Map&url=http://www.groopy.co.il/files/maslul/2213gps.gpx

**Comment by zstadler** [comment]
It seems like it still does not work universally.

For example, open https://israelhiking.osm.org.il/poi/OSM/way_149521661?baselayer=Israel_MTB_Map in a private/incognito window.

**Comment by HarelM** [comment]
The only valid use case for Base layer I'm aware of right now is presenting a file on top of our site with a specific base layer. This is the use case that we support for groopy for example.
I can't think of a valid use case for public POI - since you can't generate this url in our site and there's no site that requested this feature. While this can be implemented I don't see a reason to, right now. If we'll have a valid use case in the future let's open a different issue.
