### ISSUE TITLE
save\load gpx file

### ISSUE THREAD

**Issue by zoharkolberg** [IsraelHikingMap/Site#728]
## Feature
(Delete the non-relevant)

## What I expect to happen
to be able saving and loading gpx files to\from  google drive\ other cloud services

## What really happened
saving\loading from local computer

## My environment
* Operating System and version: 
* Web Browser and version:

**Comment by HarelM** [comment]
The problem with using a cloud service is that it requires additional credentials, which is problematic to manage.
In theory I would like the user to be able to upload images from google photos straight to the site, but the credentials are problematic here too.
As a workaround, you can make sure you save and load file from your local google drive folder to achieve this functionality. I sincerely don't think it's a bad workaround...

**Comment by zoharkolberg** [comment]
can not have local google drive folder at work, so what i do at work computer does not appear in my smartphone..
by the way, i sign in to israelhikingmap with my google credentials...
actually, what i was looking for in an option to save gpx files into my account in israelhikingmap so when i log in from other device my routs appear on the map.
another feature - sharing routs to other users?

by the way its a great tool for planning... very usefull. thanks.

**Comment by HarelM** [comment]
A few corrections:
1. The fact that you use the same user name and password doesn't make it the same account :-) OSM and google accounts are different and don't share any data.
2. Sharing is already implemented - right side share button. ![image](https://user-images.githubusercontent.com/3269297/41816780-2597b72a-7796-11e8-8764-3723d6fed5f1.png)
3. When you open a GPX file and share it - the share is saved to you shares list if you are logged in - so you can open/see a route you have used at home when you are at work.

As far as I can tell, there's nothing to implement in this feature. Can I close it?

**Comment by zoharkolberg** [comment]
Can I close it? Yes :)
thanks again

**Comment by HarelM** [comment]
Although I now see that the answer to this question in not in the FAQ, it a good idea to go to our Facebook group and read the FAQ there:
https://www.facebook.com/groups/994960670559126/
