### ISSUE TITLE
GPX form IHM  problem uploading to garmin ETREX 

### ISSUE THREAD

**Issue by Orrgvili** [IsraelHikingMap/Site#731]
tried to upload the file from here 
https://israelhiking.osm.org.il/share/y8uYMgk608
to my etrex and i revived error 
only after i saved it in  gps track editor it worked 
i think the difference is the is the  time tag in the  converted one 

[GPX.zip](https://github.com/IsraelHikingMap/Site/files/2145625/GPX.zip)

**Comment by HarelM** [comment]
The GPX file the site produces is a valid one.
You have save-as options to facilitate for other format which might be supported in some devices.
If etrex does not know how to read a valid GPX file please open a bug to them - you are a paying customer.
If their devices do not work properly it is not my responsibility to make them work. I honestly don't understand why people buy this inferior product.
