### ISSUE TITLE
Error while adding an ESRI layer

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#733]
## What I expect to happen
See the "שטח בטחוני, שטחי אש ושטחים סגורים" layer of תמ"א 35 as published at
`https://ags.moin.gov.il/arcgis/rest/services/PlanningPublic/tama35_hanchayot_svivatiot/MapServer/14`

## What really happened
The layer would not show.
The console (F12) has this message:   
`ERROR TypeError: this._url is undefined`

## What I did that caused the issue - step by step
Add a new layer with the above URL

## My environment
* Operating System and version: Windows 10 Home
* Web Browser and version: Firefox

## Thing I think the developers should know, images, links etc.
Origin: [A comment by Hoopak Ashir](https://www.facebook.com/groups/994960670559126/permalink/1746850908703428/?comment_id=1751189524936233&reply_comment_id=1751621251559727&comment_tracking=%7B%22tn%22%3A%22R4%22%7D) on Facebook

**Comment by HarelM** [comment]
Not sure what to do here, seems like an issue with esri-leaflet or my layers factory code:
https://github.com/Esri/esri-leaflet/issues/1104
Waiting for their input.

**Comment by zstadler** [comment]
The same error still happens when adding the following ESRI layer as a base layer

https://gisn.tel-aviv.gov.il/arcgis/rest/services/IView2Ortho2017/MapServer

**Comment by HarelM** [comment]
This is not the same issue.
From the browser console:
`
Mixed Content: The page at 'https://israelhiking.osm.org.il/map/17/31.8574/34.9222' was loaded over HTTPS, but requested an insecure image 'http://gisn.tel-aviv.gov.il/arcgis/rest/directories/arcgisoutput/IView2Ortho2017_MapServer/_ags_mape0dcfef62d194cd5858e9b10416e7de3.png'. This content should also be served over HTTPS.
`
It seems this is a browser restriction and not an issue with the code.
https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content

If you find a way to override this please report here, I couldn't find anything from a short google search.
If you can't find, please close the issue.

**Comment by HarelM** [comment]
Try using this layer as an overlay and see if this error still happens.
I deeply regret adding this library to the site...
I have neither the motivation nor the time to debug their library.
I would like to revert it, add it in a branch, fully debug with all sorts of layers and only then add it back when we can't find any issue with it.
If you insist on keeping it, please take the time to debug it and open issues at esri-leaflet GitHub repository.

**Comment by zstadler** [comment]
I'm getting an "undefined" error on a different variable
```
ERROR TypeError: e is undefined
Stack trace:
At@https://israelhiking.osm.org.il/main.1e3f87036ef18695a956.js:1:1956053
_animateZoom@https://israelhiking.osm.org.il/main.1e3f87036ef18695a956.js:1:2018799
fire@https://israelhiking.osm.org.il/main.1e3f87036ef18695a956.js:1:1937584
_animateZoom@https://israelhiking.osm.org.il/main.1e3f87036ef18695a956.js:1:1977479
_tryAnimatedZoom/<@https://israelhiking.osm.org.il/main.1e3f87036ef18695a956.js:1:1977264
0TWp/</</u</t.prototype.invokeTask@https://israelhiking.osm.org.il/polyfills.2d27f04af9221a930cea.js:1:8734
onInvokeTask@https://israelhiking.osm.org.il/main.1e3f87036ef18695a956.js:1:2198814
0TWp/</</u</t.prototype.invokeTask@https://israelhiking.osm.org.il/polyfills.2d27f04af9221a930cea.js:1:8647
0TWp/</</i</e.prototype.runTask@https://israelhiking.osm.org.il/polyfills.2d27f04af9221a930cea.js:1:3910
0TWp/</</c</e.invokeTask@https://israelhiking.osm.org.il/polyfills.2d27f04af9221a930cea.js:1:9828
e/this.invoke<@https://israelhiking.osm.org.il/polyfills.2d27f04af9221a930cea.js:1:9713
u/n.args[0]@https://israelhiking.osm.org.il/polyfills.2d27f04af9221a930cea.js:1:25018
  main
```

**Comment by HarelM** [comment]
Opened an issue with ESRI:
https://github.com/Esri/esri-leaflet/issues/1107

**Comment by HarelM** [comment]
@zstadler see Esri/esri-leaflet#1107
It seems that there is a problem with the servers according to @jgravois
Are you familiar with the people operating these ArcGIS servers in order to contact them and inform them about their issues?
According to your comments there are two different servers with the same issue, right?
`https://ags.moin.gov.il/arcgis/rest/services/PlanningPublic/tama35_hanchayot_svivatiot/MapServer/14`
`https://gisn.tel-aviv.gov.il/arcgis/rest/services/IView2Ortho2017/MapServer`

**Comment by zstadler** [comment]
@HarelM wrote:

> @zstadler see Esri/esri-leaflet#1107
It seems that there is a problem with the servers according to @jgravois

I'd like to clarify that I respectfully disagree with @jgravois

The ArcGIS Online map viewer is capable of showing both sources when given the above URLs
- [`http://www.arcgis.com/home/webmap/viewer.html?url=https%3A%2F%2Fags.moin.gov.il%2Farcgis%2Frest%2Fservices%2FPlanningPublic%2Ftama35_hanchayot_svivatiot%2FMapServer%2F14&source=sd`](http://www.arcgis.com/home/webmap/viewer.html?url=https%3A%2F%2Fags.moin.gov.il%2Farcgis%2Frest%2Fservices%2FPlanningPublic%2Ftama35_hanchayot_svivatiot%2FMapServer%2F14&source=sd) - as an overlay
- [`http://www.arcgis.com/home/webmap/viewer.html?basemapUrl=http%3A%2F%2Fgisn.tel-aviv.gov.il%2Farcgis%2Frest%2Fservices%2FIView2Ortho2017%2FMapServer&source=sd`](http://www.arcgis.com/home/webmap/viewer.html?basemapUrl=http%3A%2F%2Fgisn.tel-aviv.gov.il%2Farcgis%2Frest%2Fservices%2FIView2Ortho2017%2FMapServer&source=sd) - as a base map

I see no reason for the [Esri/esri-leaflet](/Esri/esri-leaflet) add-on to fail when it is provided with the same source URLs.

Indeed, now that this issue is closed, the Israel Hiking site is capable of showing both maps.

Thanks for the fix!

**Comment by HarelM** [comment]
The fact that a URL can be seen in the relevant platforms doesn't mean there isn't a problem with the server as well, it just means that the code before the fix was not able to handle the errors - which is what was done in the fix...

**Comment by jgravois** [comment]
@HarelM well said.

> @zstadler I respectfully disagree with @jgravois

i provided a reproducible test case and wrote fairly extensively about the intermittent, inappropriate behavior of the [`/export`](https://developers.arcgis.com/rest/services-reference/export-map.htm) operation of a few specific map services in https://github.com/Esri/esri-leaflet/issues/1107#issuecomment-403543601. your ArcGIS Online examples leverage [`/query`](https://developers.arcgis.com/rest/services-reference/query-feature-service-layer-.htm) and [`/tile`](https://developers.arcgis.com/rest/services-reference/map-tile.htm) respectively. 

that said, i just spent a few more minutes testing in my dummy app (without the patch) and I am no longer seeing those ArcGIS Server machines producing invalid responses. so all's well that ends well!
