### ISSUE TITLE
OSM POI upload bug from June 30 beta - tags lost, reverts to tourist attraction

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#734]
## What I expect to happen
POIs should be uploaded to OSM properly tagged

## What really happened
All POIs are uploaded as tourist attraction. Tried nature tree and historic ruins with same results.

## What I did that caused the issue - step by step
Added provate POI and named it.
Pressed the upload icon
changed category and type
pressed the v OK button
The POI was uploaded as a tourist attraction, with the golden star icon.
This was confirmed in the OSM editor.

## My environment
Chrome on win10

**Comment by HarelM** [comment]
Fixed by 83941facc4a5d11272ef20b7cddbebfd70386755
