### ISSUE TITLE
Add narrated movie help

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#735]
Feature
 I suggest adding a list of narrated explanatory movies to the website help feature.

Covered issues:
How to plan a route
How to import and export routes
How to add a custom map
How to load the Strava HeatMap
How to add a POI
How to split and unite routes
How to upload a POI to OSM
How to deal with photos

Your thoughts?

**Comment by HarelM** [comment]
I have no objections in theory, 
One point to consider is that the movies should be good also for people who can't hear.
Having said that, I usually don't find the right movie when trying to understand how a software works, usually because I don't know which movie would help and I don't have the time to watch them all.
I think that a on screen help wizard that briefly goes over the capabilities and the buttons on the screen would do much better.
Check out the latest version of off-road and how the initial screen helps out.
Also check the OSM editing tutorial in iD.
Movies are nice but they require some work, also they might get outdated due to UI changes.
If you don't mind maintaining them, it can work.

**Comment by valleyofdawn** [comment]
An online interacrive tutorial would be even better, but I can't program it. Movies I can do and I can update them as needed.

**Comment by HarelM** [comment]
@valleyofdawn might be better if you put this on your task list as in any case it won't be part of the code here before the videos are created, when they are, please open an issue and link them.
Closing for now...

**Comment by HarelM** [comment]
Due to Facebook interest I'll open this issue in order to allow collaboration here.

**Comment by HarelM** [comment]
<div dir="rtl">
הנה מה שדימיינתי כשחשבתי על הבקשה הזו:

1. לעשות רשימה של כמה מה שרוצים להקליט
1. להקליט על הנייד ועל מחשב שולחני, למרות שזה לא בהכרח קריטי להקליט על שניהם, כולל קריינות של על מה לוחצים ומה זה מאפשר, קריינות בסיסית וסרטון בסיסי של לכידת מסך ועכבר או "אצבע".
1. לרשום בתיאור הוידאו את השלבים ואת הכפתורים שלוחצים עליהם על מנת שמי שרוצה לקרוא ולא לראות את הסרטון יוכל
1. לפרסם את הוידאו בערוץ יוטיוב של האפליקציה
1. לקשר לסרטוני הוידאו מתוך מסמך השאלות הנפוצות

**Comment by HarelM** [comment]
<div dir="rtl">
רשימת נושאים לסרטונים:

1. הזזת המפה -> זום פנימה והחוצה -> סיבוב המפה -> שינוי נקודת הראות
1. כניסה למשתמש -> פתיחת תפריט המשתמש -> צפיה בשמירות ובהקלטות 
1. הפעלת עקיבת גפס -> שינוי צפון למעלה -> הפעלת וכיבוי הקלטה -> כיבוי עקיבת גפס
1. תפריט -> מסלולים - מפות - שכבות -> מעבר על שכבות הבסיס, השכבות השקופות, נקודות עניין והמסלולים הפרטיים
1. מפות לשימוש לא מקוון - הורדה, הפעלה "כפוייה" 
1. חיפוש -> צפיה בנקודת עניין -> שיתוף
1. תכנון מסלול בסיסי - קליקים על המפה ונק' עניין פרטיות
1. צפייה בגרף הגבהים -> נק' ק"מ -> גרף שיפועים -> שיפוע לפי צבע על המפה
1. צפיה באשכול נקודות עניין -> בחירת מסלול -> הפיכת מסלול למסלול פרטי
1. שמירה שיתוף קבצים - יצירת שמירה בענן, שמירה לקובץ ושיתוף, שמירה כ..., פתיחת קובץ (גם ע"י גרירה)
1. נושאים אחרים בתפריט הראשי: אודות - מקרא, דיווח על בעיה, שפה 
1. עריכת מסלול מתקדמת: פיצול, חיבור, מסלול שעולה על עצמו, מסלול בעזרת קווים ישרים, שינוי צבע רוחב ושקיפות, היפוך מסלול
1. עריכת נק' עניין ציבורית
1. הוספת נקודת עניין ציבורית פשוטה ומורכבת
1. הוספת מסלול למפה אחרי הקלטה - עד היציאה לאואסאם

**Comment by HarelM** [comment]
I've started playing with Zoom to allow easy recording and screen sharing. I have recorded item 5 on the list.

**Comment by HarelM** [comment]
Most of the movies have been recorded.
The next effort should be updating the FAQ with both the movies and updated screen shots...

**Comment by HarelM** [comment]
FAQ was update, there's still a last video I would like to record about adding a simple line to the map after a recording now that the fix of the background tiles was published.

**Comment by HarelM** [comment]
Move was recorded and added to FAQ page.
This basically sums up all the videos I wanted to record.
If any of you would like to record other movies and have them uploaded to the IHM channel please let me know.
I'm closing this issue now.
