### ISSUE TITLE
undo concatenate routes restores one route and deletes the other

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#739]
## What I expect to happen
return to previous state: have the two original routes on the map

## What really happened
One of the two original routes is restored on the map and the other is erased

## What I did that caused the issue - step by step
1. In edit mode, link two routes by pressing the + on the endpoint of one of two routes
2. Undo

## My environment
Win 10
Chrome

**Comment by HarelM** [comment]
Unfortunately I'm aware of this issue.
See here #402.
The solution to this problem is to do a global undo and not undo per route, which is complex and with little benefit.
Closing this as duplicate, sorry...

**Comment by oriori** [comment]
Please consider disabling the undo function when the next operation to undo is not really undo-able. As of now, undoing concatenate route causes a data loss that can not be easily recovered from.
