### ISSUE TITLE
Support multi-section GPX route import

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#74]
[This one] (http://www.gpsies.com/map.do?fileId=erpumdvynhcqxnoe) for instance doesn't work.

**Comment by valleyofdawn** [comment]
Would be nice if each section is imported as a separate route.

**Comment by HarelM** [comment]
I'll see what I can do since they all have the same name...

**Comment by valleyofdawn** [comment]
Great ride part 1.gpx
Great ride part 2.gpx
