### ISSUE TITLE
Use ESRI layer name as the default name for a new layer

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#741]
## What I expect to happen
When a new ESRI layer is added, use the published layer name as the default name for the new layer

## What really happened
The user need to type a layer name, regardless of the name given to the ESRI layer

## What I did that caused the issue - step by step
1. Add a new layer
2. type https://ags.moin.gov.il/arcgis/rest/services/mehoziot_app/MapServer/1 in the address field
3. The required name field is blank

## My environment
* Operating System and version: Any
* Web Browser and version: Any

## Thing I think the developers should know, images, links etc.

The proposal is to copy name field from the JSON of the ESRI layer definition. However, the user would be able to modify it.

For example, use ` "name": "יעודי קרקע"` from 
https://ags.moin.gov.il/arcgis/rest/services/mehoziot_app/MapServer/1?f=pjson
as the default name

```
{
 "currentVersion": 10.5,
 "id": 1,
 "name": "יעודי קרקע",

 ...
```

**Comment by HarelM** [comment]
Seems that ArcGIS online doesn't support [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) (tested on two different servers) so the above won't work when calling from within a website and not as a standalone browser request.
```
Failed to load https://ags.moin.gov.il/arcgis/rest/services/mehoziot_app/MapServer/1?f=pjson: Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response.
```
You are welcome to try and tackle this, but I think it's not worth the effort.
