### ISSUE TITLE
Support WMS format

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#748]
## Feature
It will help if IHM will support the WMS format, not sure if I know how to identify it though.
Need to investigate this.

**Comment by zstadler** [comment]
As a rough identifier for a WMS URL, it would have a `REQUEST=GetMap` parameter. 

Also note that some Israeli WMS sources use the ITM projection, which is not natively supported by Leaflet.

**Comment by HarelM** [comment]
This will require the user to input a lot of parameters that are probably hard to get and will make the add layer window complicated.
I don't think this feature should be implemented due to high UX complexity and low benefit.
