### ISSUE TITLE
typing a modified URL in the address bar does not change the map

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#75]
Scenario:
* Open http://osm.org.il/IsraelHiking/PreProduction/#/11/31.0012/34.7896?markers=&Route_1=
* In the address bar Change the "11" of the URL to "14" and press enter.

I was expecting the map to change its zoom to 14.
Seen on both Firefox and IE

**Comment by HarelM** [comment]
It's one way binding, you'll need to click refresh, I'll try and read about it, I think it will require major changes in order to support it.

**Comment by zstadler** [comment]
I assume that there an ignored event as a result of the "enter"...

**Comment by HarelM** [comment]
This requires both better server side support and other implementation to remove the "#" (hash band mode).
I think the users can hit the refresh button...
