### ISSUE TITLE
Issues when uploading a picture to Wikimedia

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#751]
## What I expect to happen
1. Upload to Wikimedia to preserve the aspect ratio
2. Upload to Wikimedia to maintain resolutions of pictures with 2M pixels or less.

## What really happened
Instead of a 450x600 pixel image (0.27 M pixels)
![](https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Israel_Hiking_Map_%D7%A2%D7%99%D7%9F_%D7%97%D7%A0%D7%93%D7%A7.jpeg/90px-Israel_Hiking_Map_%D7%A2%D7%99%D7%9F_%D7%97%D7%A0%D7%93%D7%A7.jpeg)
the result was 300x150 pixels - 1/6 of the original resolution and distorted:
![](https://upload.wikimedia.org/wikipedia/commons/thumb/archive/9/97/20180705091958%21Israel_Hiking_Map_%D7%A2%D7%99%D7%9F_%D7%97%D7%A0%D7%93%D7%A7.jpeg/120px-Israel_Hiking_Map_%D7%A2%D7%99%D7%9F_%D7%97%D7%A0%D7%93%D7%A7.jpeg)

## What I did that caused the issue - step by step
The picture in [2008_0712-עין-חנדק (Medium).zip](https://github.com/IsraelHikingMap/Site/files/2165926/2008_0712-.-.Medium.zip) was added to [עין חנדק](https://israelhiking.osm.org.il/poi/OSM/node_4319817216?language=he)

## My environment
* Operating System and version: Win 10 home
* Web Browser and version: Firefox 56.0.2

## Thing I think the developers should know, images, links etc.
There was no issue when the image was later uploaded directly to Wikimadia Commons. See [the image history](https://commons.wikimedia.org/wiki/File:Israel_Hiking_Map_%D7%A2%D7%99%D7%9F_%D7%97%D7%A0%D7%93%D7%A7.jpeg#filehistory) on Wikimedia.

**Comment by HarelM** [comment]
Yes, it seems like this is a client side resize issue, probably related to the code I have written.
Thanks for catching it!

**Comment by HarelM** [comment]
Please see if you have any other issues with the image.
Note that the image that you see is the image that will get uploaded - so in theory you can identify the bug without uploading it to wikimedia.
