### ISSUE TITLE
Slope of a section in the height profile is local rather than average

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#755]
## What I expect to happen
I expected the slope to show the average slope of the highlighted section. and the height to show the cumulative climb.
This is equivalent to the total distance of the section shown. Average slope and cumulative climb are useful pieces of information to cyclists and MTB riders.

## What really happened
It showed the local slope and height - in the rightmost edge of the section

## What I did that caused the issue - step by step
Opened the height profile, drag-pressed the mouse on it to highlight a section, looked at the stats.
In this image for example the average slope in ~7% but is shows the -13% in the last bit:
![image](https://user-images.githubusercontent.com/689201/42408200-7981b170-81d1-11e8-87d7-e9b0e691067d.png)

**Comment by HarelM** [comment]
The stats are below the graph and not inside it. I don't have any plans to change the tooltip since you can hover the graph after selection.
I don't think the current behavior should change.

**Comment by HarelM** [comment]
I can add an average slope to the statistic below the chart when there is a selection in theory, not sure it has a lot of benefit though...

**Comment by valleyofdawn** [comment]
It does add benefit to riders wanting to know how steep a section would be. That would also be a good chance to move the "km mark" button to a more discoverable place.
