### ISSUE TITLE
feature request: In edit mode, add point to route without altering route

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#756]
Feature
When uploading a gpx file that was not originally edited on IHM, it is quite a hassle to edit a small section in the middle of the route. A slight drag and drop of any point along the route can cause the site to completely alter the route between the previous and next key points along the route. This is understandable but it would be nice to have some way around it.
The easiest way I can imagine is to add two key points to the route delimiting the section the user wants to change. That is, to have an option to add key points to the route without altering the route. However, currently an added key point must be classified as one of hike/bike/car/straight line. But as described above, adding a key point with one of these navigation modes causes the site to recalculate the navigation and alter the route.
I am not sure that this option is worth the screen real estate that another button will require. A better way to implement it might be by having no navigation mode selected (by pressing again on the selected navigation mode). Another option is to suppress re-navigation if a specific key is pressed when a point is added to the route.

**Comment by HarelM** [comment]
I'm not sure I understand the problem.
Can you define it using the following temple:
As a user I would like to ... so that I'll be able to...

**Comment by oriori** [comment]
While constructing an example I accidentally discovered the functionality I asked for is already implemented: Just add a key point to the route by clicking on the route without dragging it.
