### ISSUE TITLE
Cannot edit a POI after saving a previous edit

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#761]
## What I expect to happen
Be able to edit a POI after saving a previous edit

## What really happened
The edit button does not work after saving an edit to a POI

## What I did that caused the issue - step by step
1. Edit a POI
2. Save the edit
3. Press the edit button

## My environment
* Operating System and version: Win 10 Home
* Web Browser and version: Firefox 64.0.2

## Thing I think the developers should know, images, links etc.
Workaround: closed the POI panel and then click on the POI icon on the map to open it again.

**Comment by HarelM** [comment]
Thanks for reporting. I'm aware of this, didn't get to fixing it yet, this is due to a fix I made regarding #757. Should be fixed soon.
