### ISSUE TITLE
Improve loading time of shares with images

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#765]
## What I expect to happen
Shares should load fast

## What really happened
It takes a few seconds to load a share that is heavy due to images

## What I did that caused the issue - step by step
Surf to:
https://israelhiking.osm.org.il/share/xkl0jAAcpW

## My environment
* Operating System and version: any - especially on mobile
* Web Browser and version: any  - especially on mobile

## Thing I think the developers should know, images, links etc.
Images are now stored in the database as blods and not uploaded to imgur as before.
A possible solution to this issue is so periodically upload images to imgur and update the share accordingly.
Another option is to upload the images to imgur when the share is created.

@valleyofdawn, can you supply the original images used for this share so I'll be able to test my implementation?

**Comment by valleyofdawn** [comment]
https://photos.app.goo.gl/D7b8uoD8HCwNn6c49

**Comment by valleyofdawn** [comment]
When sharing a track with several HD images over mobile data this typically takes many minutes.
Meanwhile the user is left baffled with what looks like a frozen app.
I suggest, at a minimum to add a message "Please wait, uploading images" after a few seconds.
Better yet,  suggest sharing the track only and updating it with images when Wi-Fi is connected (much like Google Images does).

**Comment by HarelM** [comment]
Please add a new share that presents the issue.
HD images are rescaled to lower resolution long before shading, so I don't believe this is the root cause.
Also please measure the time it takes to load.

**Comment by valleyofdawn** [comment]
This share, with 4 images, took 60 seconds to upload on mobile data inside a city apartment.
I had the same issue with a previous phone. Both considered high-end phones.
https://israelhiking.osm.org.il/share/2lQ8B05RxD

**Comment by HarelM** [comment]
This issue is about loading time, not uploading time.
It took me 14 seconds to see the share, 7 of them after the app started. This is reasonable time from my point of view.
If the problem is with upload time please open a different issue, this is confusing.

**Comment by HarelM** [comment]
#1019 was created. closing this one.
