### ISSUE TITLE
Remove console error of missing files

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#776]
## Infra
When surfing to the site there is an error in the console due to a bug in leaflet.
https://github.com/Leaflet/Leaflet/issues/4968
https://github.com/Leaflet/Leaflet/issues/6247

In order to solve this console error, one need to add the following plug-in:
`leaflet-defaulticon-compatibility`.

**Comment by Le-Stagiaire** [comment]
https://github.com/Leaflet/Leaflet/issues/4968#issuecomment-407196479

Here you say you'd prefer see the problem soldved with a fix rather than using a plug-in, it seems a good idea, why changing side now ?

**Comment by HarelM** [comment]
I would love nothing better than this fixed inside leaflet. However, I'm not among the core contributors. So, while this is not fixed I'll be using the exiting solution which is not ideal... One has to pick his fights... :-/

**Comment by Le-Stagiaire** [comment]
Oh my bad I thought you add the issue on leaflet project ...
