### ISSUE TITLE
Improve share library prominence/usability/design

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#777]
##  Feature
Rethinking the Share library.
The share library began as an afterthought and evolved to become the main place many users store their routes.
Problems I see with it.
1)	To reach it, users have to press on “my profile”. They have no reason to suspect it’s there. It’s a very useful button and should be on the top page. 
2)	It is mixed up with elements of the OSM activity such as your OSM status, number of changes, and upload recording to OSM, while there is no connection between them. All in all, there are too many elements to interact with on this page.
3)	You can only see 2 routes at a time, on a laptop, and one on a smartphone, requiring lots of scrolling.
4)	To scroll you use both the left scroll bar and the bottom page selector. Infinite scrolling, such as exists in FaceBook and WhatsApp is simpler, and what users have come to expect of such an interface. It should only load the data and thumbnail as you scroll down.
I'm adding a mock-up for your consideration.

![image](https://user-images.githubusercontent.com/689201/43358745-20cc62e4-929f-11e8-94ed-e392c2cc36df.png)
![image](https://user-images.githubusercontent.com/689201/43358748-291e6abe-929f-11e8-8b34-61b888d55e61.png)

**Comment by valleyofdawn** [comment]
1. To clarify. OSM-related stuff should stay under the OSM login button. They could keep using the current interface only without "my shares". The interface I suggested should be devoted to shares and accessible from the top page with an icon next to "share". Could look like this.

**Comment by zstadler** [comment]
The personal icon is a natural button for your personal information on our site. I do not support the request to create another button/icon or replace the existing one.

**Comment by valleyofdawn** [comment]
So I gather you like the simpler library interface but not how it is accessed.
What about this solution then.
it removes 2 buttons from the top page. It won't give the share library more prominence, but would take care of the other stuff.

![image](https://user-images.githubusercontent.com/689201/43360691-5db34e2e-92c3-11e8-907a-8cd222101431.png)

**Comment by HarelM** [comment]
I'm not sure what the this suggestion solves...
I still think changing language should be at the main screen.
Logout and profile button is a standard in all sites, I don't see a reason to remove the logout button.
Share is also one of the most important features, I don't see a reason to remove it from the main screen.
I don't mind adding the icons to the tabs inside the user profile, but that's probably not going to improve things much... :-)
What is the suggested UX regarding this dialog? does it expand when clicking on one of the lines? does it appear after you click the user profile button on the right side? I'm a bit confused...

**Comment by valleyofdawn** [comment]
1. The suggestion solves the problem seen in the mobile screen capture below. A list showing just one item does not function as a list. To show say 5 items we need to make space in that dialogue box, which means removing unnecessary items. These items belong under the profile/OSM so we need to separate them.
2. My initial suggestion was to add the share library as a top-page icon. Since we all think the top page is beginning to become overwhelming I suggested instead to take the profile button and show all related items.
3. In another issue you said that the language button is to be pressed once in the lifetime of a user. No point crowding the top page with it. It also a personal preference. This way it would open in English wherever the user logs in. The new way it also shows you which language is currently active.
4. Logout on the top page is **not** a standard in **all** sites.  In fact, every site I checked had it one layer deeper, in the pull down menu. I'm attaching some examples of profile dialogues from sites similar to ours. The exit button is rarely used but clearly belongs in the profile.
6. The share button should definitely stay on the top page. Under the profile should be only the shares library. We should use a different icon. 
7. The behavior is simple. Press on the profile button. Get the dialogue box (I like how the height profile expands). Choose whether to see the share list, browse the recording list, change language or log out. Close dialogue. 

The share list on our mobile site:
![image](https://user-images.githubusercontent.com/689201/43363781-19e5d55c-9315-11e8-9725-427eaacb6cfe.png)

The profile dialogue box on komoot.com:
![image](https://user-images.githubusercontent.com/689201/43363891-a2d5381a-9317-11e8-8333-0be45fe18713.png)

In strava:
![image](https://user-images.githubusercontent.com/689201/43363903-f64ecb3c-9317-11e8-90bd-1c633a4f37ef.png)

In Wikiloc:
![image](https://user-images.githubusercontent.com/689201/43363927-998d17e0-9318-11e8-9a4e-f302c5f4def7.png)

**Comment by valleyofdawn** [comment]
Your thoughts on the last suggestion?
We must agree that a list the fits one item at a time is useless.

**Comment by HarelM** [comment]
I agree that a list of one item is useless.

>In another issue you said that the language button is to be pressed once in the lifetime of a user. No point crowding the top page with it. It also a personal preference. This way it would open in English wherever the user logs in. The new way it also shows you which language is currently active.

You should find my full comment if you cite me - the fact that you press it once in a lifetime doesn't mean it's not extremely important to new users - therefore should be in the main screen.

> Logout on the top page is not a standard in all sites. In fact, every site I checked had it one layer deeper, in the pull down menu. I'm attaching some examples of profile dialogues from sites similar to ours. The exit button is rarely used but clearly belongs in the profile.

This doesn't change the screen much, I don't see a reason to nitpick it.

>The behavior is simple. Press on the profile button. Get the dialogue box (I like how the height profile expands). Choose whether to see the share list, browse the recording list, change language or log out. Close dialogue.

The desktop UX is fine, IMO, so I wouldn't want to change it - I don't agree with most of your comments above about what is redundant and what is important, sorry.
So changing this only for mobile is a lot of work and very error prone.
When we'll have an app we should consider solving it - up until then, I don't see a reason to change this.

**Comment by valleyofdawn** [comment]
I think it should be changed identically to both mobile and desktop. My laptop shows 2 items in the list, which is also not great. Another problem is that there are a lot of irrelevant items and the important one - search, is not prominent.

**Comment by HarelM** [comment]
I disagree about the importance of search, search is for advance users, IMO.
Regardless, I can't fully grasp the concept you are suggesting.
Please prepare a powerpoint mock-up of how it should look in mobile and how it should look in desktop and I'll be able to comment on it - it should indicate what happens when clicking and how the screen flows (you can use powerpoint's transparent link to illustrate click to move from one slide to the other).

**Comment by valleyofdawn** [comment]
An interactive PPT mock-up of the behavior.
[behavior.pptx](https://github.com/IsraelHikingMap/Site/files/2267305/behavior.pptx)

**Comment by HarelM** [comment]
Great! Can you also make a similar one for mobile as there is a lot less space for mobile and the images take a lot of room.
Please note that I don't see where you can upload a file to OSM in the attached presentation.
To locally illustrate how a mobile browser will look you can do one of the following:
1. Minimize the browser to the dimensions of a mobile device (the browser window itself)
2. Or - Press F12 and switch to mobile view, in chrome its the following blue button:
![image](https://user-images.githubusercontent.com/3269297/43879826-736c6d92-9bae-11e8-8184-e9b1a9c36049.png)

**Comment by HarelM** [comment]
@valleyofdawn any updates on this? a mobile UX version can help #782 a lot, I think.

**Comment by valleyofdawn** [comment]
[mobile recordings.pptx](https://github.com/IsraelHikingMap/Site/files/2354178/mobile.recordings.pptx)
Here's a draft. No behavior yet.
Notice the sort by date and alphabetically buttons.

**Comment by zstadler** [comment]
Would it also be possible to move the "save as" button away from the main screen?

**Comment by HarelM** [comment]
Thanks for the presentation!
Here are my comments:
If there's a search bar I don't see a need for sorting - it is by default sorted by date so you have the last recordings first.
The small pictures were like that in the original design and were not effective in that size, thus I enlarged them.
The action buttons are missing?
Also the same is needed for the shares I guess...

**Comment by HarelM** [comment]
>Would it also be possible to move the "save as" button away from the main screen?

I don't see how this is related to this feature...?

Also the upload trace is missing in the suggested UX...

**Comment by valleyofdawn** [comment]
Yes, "save as" belongs to #797.
The sort by is useful if you want to look at oldest first or have multiple entries starting with say "Rehovot to...".
The images seem merely ornamental. Especially in the recordings, the shape of the route doesn't help you recognize anything. I would much rather lose the thumbnails altogether that have fewer items in the list.
The upload recording may be misplaced here as it does not refer to the existing library. How about putting it next to "save" in the route dialogue?
Can you generalize from this to the route (formerly share) library, or should I create another mock-up?
I lost the action buttons in the presentation somehow - here is how it should look:
![image](https://user-images.githubusercontent.com/689201/45141487-a9794600-b1be-11e8-82e0-8a08a73dc24f.png)

**Comment by valleyofdawn** [comment]
Also notice the area feature. It would help a lot in identifying the recordings.

**Comment by valleyofdawn** [comment]
I think the OruxMaps dialogue is a good reference, although too cluttered for my taste.
![image](https://user-images.githubusercontent.com/689201/45142100-53a59d80-b1c0-11e8-9957-8a69ad477eb5.png)

**Comment by HarelM** [comment]
I can probably generalize to shares as well.
If the recording will hold both local and OSM recordings then an upload button should be available in this dialog.
Not sure I understand where the link is pointing to (blue header + underline)? Since you need to select a row now it doesn't make sense, IMO, to have part of the row behave in another way besides doing the "select row" operation.

> The sort by is useful if you want to look at oldest first or have multiple entries starting with say "Rehovot to...".

I don't see how this is an interesting use case...
I don't want to clutter this dialog with too many buttons in too many places - planning not to add sort at first.

> Also notice the area feature. It would help a lot in identifying the recordings.

True, but this info does not exits when recording or uploading to OSM so it needs to be fetched from the server. Not planning on implementing it as part of this feature as it's too complicated right now. If we'll store the recording locally in the future this can be implemented.

Also missing in this mockup how this looks when editing - right now you can edit name, tags and visibility. tags and visibility are missing in your mock-up.

**Comment by HarelM** [comment]
@valleyofdawn I'll also need an svg icon for the recordings.
Or I can use one of the following:
![image](https://user-images.githubusercontent.com/3269297/45180459-21c62280-b224-11e8-8570-bbc5932214f0.png)

**Comment by HarelM** [comment]
Using the elements I have in order to not build too many custom controls this is how the initial "menu" will look like:
![image](https://user-images.githubusercontent.com/3269297/45181077-05c38080-b226-11e8-89eb-d865e49f4d50.png)

**Comment by valleyofdawn** [comment]
So you don't want the OSM bling and the language selector?
Also no changing of "shares" to "tracks"?

**Comment by valleyofdawn** [comment]
There is also a duplication of the exit button.

**Comment by HarelM** [comment]
You're right, I forgot the OSM progress bar, I'll add it - I explained the language above a few times.
In order to keep the menu to the left I needed to keep a button on the side. I kept the logout, you kept the image, I don't think it matters much, and keeping it as it was before is easier.

**Comment by valleyofdawn** [comment]
Not really - the image conveys that these are personal settings, the exit button does not.

**Comment by HarelM** [comment]
When the dialog is open (not the menu) this has very limited visibility. keeping this as is for the sake of not waiting time on it.
Menu:
![image](https://user-images.githubusercontent.com/3269297/45186208-57bfd280-b235-11e8-91a8-3d62d9858d1c.png)

**Comment by valleyofdawn** [comment]
![recording](https://user-images.githubusercontent.com/689201/45215298-b886f380-b2a5-11e8-9097-87e5ecfdc236.png)
[Recording.svg.txt](https://github.com/IsraelHikingMap/Site/files/2360723/Recording.svg.txt)

**Comment by valleyofdawn** [comment]
Regarding the edit I think we can live with the current solution for the time being. Frankly, private tracks should have other edit fields.

**Comment by valleyofdawn** [comment]
![routes](https://user-images.githubusercontent.com/689201/45217160-b758c500-b2ab-11e8-8ee3-a1cd92304485.png)
[routes.svg.txt](https://github.com/IsraelHikingMap/Site/files/2360882/routes.svg.txt)

**Comment by HarelM** [comment]
Recordings icon is too complex:
![image](https://user-images.githubusercontent.com/3269297/45259406-aeafde00-b3d4-11e8-9607-4bdc9958057e.png)
Make sure to place them in the canvas at the right location and size - it seems that they are too small even before I made them bigger by changing the canvas...

**Comment by HarelM** [comment]
Recorings UX after modification:
![image](https://user-images.githubusercontent.com/3269297/45259470-79a48b00-b3d6-11e8-8a98-3b6e57e349d5.png)

**Comment by HarelM** [comment]
@valleyofdawn any comments on current implementation? I think the icon is too small, I'm leaning towards using the icon I suggested (two crossing arrows).
Other than that I think this can be published to production.

**Comment by valleyofdawn** [comment]
Try this:
![recording](https://user-images.githubusercontent.com/689201/45472655-8a8a2f00-b73d-11e8-91e7-954e9fb0821f.png)
[Recording 2.svg.txt](https://github.com/IsraelHikingMap/Site/files/2378096/Recording.2.svg.txt)

**Comment by HarelM** [comment]
Still to be done - remove blue links, maybe add them as a button?
