### ISSUE TITLE
Multipoligon relation shown wrong when selected on map

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#780]
## What I expect to happen
When selecting a multipolugon, through search for instance, I expect the are to show the inner polygons correctly.

## What really happened
They are connected through lines

## Thing I think the developers should know, images, links etc.
Example: Yatir forest
https://israelhiking.osm.org.il/poi/OSM/relation_1649842?language=he

**Comment by valleyofdawn** [comment]
Could you recreate this?

**Comment by HarelM** [comment]
I have no problem seeing the issue. This specific case also shows an issue with the wikipedia user (special contribute).
Need to check if this is a client side or server side issue.
