### ISSUE TITLE
Support offline maps and POIs

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#783]
## Feature
The following might be a good solution to offline tiles without requiring the user to download a huge file - which sometimes fail.
https://github.com/allartk/leaflet.offline
Or this:
https://github.com/robertomlsoares/leaflet-offline

**Comment by zstadler** [comment]
If we want to support Oruxmaps's offline maps, with the known download issues, the following are starting points:
* The [MBTiles leaflet plugin](https://gitlab.com/IvanSanchez/Leaflet.TileLayer.MBTiles) has implemented fetching tiles from an SQLite DB. Clearly, the DB scheme are different than Oruxmaps offline maps scheme.
* [This comment](https://github.com/Leaflet/Leaflet/issues/6187#issuecomment-397260519)  describes how to use 512x512 pixel tiles, as is the case in Oruxmaps offline maps. However, this approach is not directly applicable to Oruxmaps, as its offline tiles are not necessarily aligned with the tile boundaries the the lower-level zoom.

**Comment by HarelM** [comment]
Another thing to consider here is that if we implement rotate we'll need to switch to OpenLayers according to #669 - which has a cache layer built in.
http://workshops.boundlessgeo.com/openlayers3/layers/cached.html

**Comment by HarelM** [comment]
This feature will facilitate the entry point to looking into what's needed in order to work offline properly - it should work both with the regular browser and with the mobile app the same way.
In order to facilitate offline work the first thing that we need it to better hold the current state of the app so that we initially fetch it from local storage and then hydrate it from the server.
To do that we need a good framework.
[Redux](https://redux.js.org/) seems like it is battle proof and is used with react so it seems like a good idea to use it.
It also supports undo and redo almost out of the box which is needed for #402

**Comment by HarelM** [comment]
This is the angular implementation of it:
https://github.com/angular-redux/platform/tree/master/packages/store

**Comment by HarelM** [comment]
This is an interesting answer related to vector tiles, openlayers and ionic (which is a superset of cordova)
https://gis.stackexchange.com/questions/237407/openlayers-support-for-vector-tiles-pbf-split-and-crop

**Comment by HarelM** [comment]
Looking into database solution for offline usage the following is what I came across:
http://www.diva-portal.org/smash/get/diva2:1215529/FULLTEXT01.pdf
Need to investigate `IndexDB` with spatial capabilities.

**Comment by HarelM** [comment]
Need to investigate this further due to performance issues with PouchDB and chrome.
https://malcoded.com/posts/angular-service-worker
https://angular.io/guide/service-worker-intro
https://angular.io/guide/service-worker-getting-started

**Comment by HarelM** [comment]
Performance issues were fixed using worker-pouch repository.

Here's what I think is needed in order to make OruxMaps work with IHM app:
1. Be able to query a sqlite file that is one the device, probably using [this plug-in](https://github.com/litehelpers/Cordova-sqlite-storage). There's an example app that can be used for initial testing on the device which should allow basic operations to the database [here](brodybits/cordova-sqlite-storage-starter-app).
2. Reverse engineer the OruxMaps Sqlite format and understand how to get a specific tile according to a given X,Y,Z coordinates.
3. Once we can read the file there will be a need to implement a tile provider for openlayers, described somewhat [here](https://github.com/openlayers/openlayers/issues/3707).
4. If all the above are working there will be a need to wire this through the layers sidebar navigation to allow users to download a file or use a file that is already on the device.

**Comment by HarelM** [comment]
https://www.google.com/amp/s/mobilegeo.wordpress.com/2013/06/07/mbtiles-and-openlayers/amp/
This is an interesting piece on exactly what we need, I think.

**Comment by zstadler** [comment]
As far as I understand, this example needs to be converted from raster tiles to vector tiles.

**Comment by HarelM** [comment]
Seems about right, this explains why I couldn't find where the style is being applied. I'm not sure how to use this code for vector tiles, but it will be fun to research :-)

**Comment by HarelM** [comment]
The following issue might show a way to use vector tiles with custom source, there's a codepen there that might be good:

https://github.com/openlayers/openlayers/issues/7342

**Comment by HarelM** [comment]
In order to insert a mbtiles to websql and "fool" chrome to think it is part of the site the following steps are needed:
1. write the following line in the initialization function of the app:
```
let db = openDatabase("tiles", 1.0, "tiles_db", 100 * 1024 * 1024, (database) => {
            console.log("DB opened!");
        });
```
This will create a database in chrome's application data folder, somewhere here:
C:\Users\my-user\AppData\Local\Google\Chrome\User Data\Default\databases\http_localhost_58231
Now the file can be replaced with the mbtiles file and chrome will be able to access it using the method above.

When this will be matured the following library maybe of use:
https://github.com/orbitaloop/WebSqlSync

**Comment by HarelM** [comment]
This is the code I manged to get close to showing the tiles:
But I was unable to convert the blob data (pbf) to openlayers features.
@zstadler do you know if the data inside the mbtiles blobs is gzipped or not?
```ts
let offlineTileLayer = new layer.VectorTile({
	renderOrder: null,
	source: new source.VectorTile({
		projection: "EPSG:3857",
		format: new format.MVT(),
		tileLoadFunction: (vectorTile: VectorTile, url: string) => {
			console.log(vectorTile, url);
			vectorTile.setLoader(() => {});
			let db = openDatabase("tiles", 1.0, "tiles_db", 100 * 1024 * 1024);
			db.transaction((tx) => {
				let tileCoord = vectorTile.getTileCoord();
				console.log(tileCoord);
				let ymax = 1 << tileCoord[0];
				let params = [tileCoord[0], tileCoord[1], ymax + tileCoord[2] - 1];
				console.log(params);
				tx.executeSql("SELECT tile_data FROM tiles WHERE zoom_level = ? AND tile_column = ? AND tile_row = ?  limit 1",
					params,
					(q, results) => {
						if (results.rows.length === 1) {
							console.log(new format.MVT().readFeatures(new Blob([results.rows[0].tile_data])));
							//vectorTile.setFeatures((vectorTile.getFormat() as format.MVT).readFeatures(results.rows[0].tile_data));
						}
						console.log("td:", results.rows.length);
					},
					(error) => {
						console.error("##execQuerySingleResult: " + error);
					}
				);
			});
			console.log('load tile');
		},
		tileUrlFunction: (c) => {
			return '/' + c[0] + '/' + c[1] + '/' + c[2] + '.pbf';
		}
		//url: "{z}/{x}/{y}.pbf",
		//maxZoom: 14,
		//url: 'https://ahocevar.com/geoserver/gwc/service/tms/1.0.0/ne:ne_10m_admin_0_countries@EPSG%3A900913@pbf/{z}/{x}/{-y}.pbf',
		//url: 'https://israelhiking.osm.org.il/tiles/{z}/{x}/{y}.png',
	}),
	style: new style.Style({
		stroke: new style.Stroke({
			color: "gray",
			width: 2
		}),
		fill: new style.Fill({
			color: 'rgba(20,20,20,0.9)'
		})
	})
});
```

**Comment by zstadler** [comment]
OL has built-in support for PBF format. They call it MVT, which probably stands for "Mapbox Vector Tiles".

See, for example, the [code from here](https://openlayers.org/en/latest/examples/mapbox-vector-tiles.html) that uses pbf tiles from a URL.

```javascript
      var map = new Map({
        layers: [
          new VectorTileLayer({
            declutter: true,
            source: new VectorTileSource({
              attributions: '© <a href="https://www.mapbox.com/map-feedback/">Mapbox</a> ' +
                '© <a href="https://www.openstreetmap.org/copyright">' +
                'OpenStreetMap contributors</a>',
              format: new MVT(),
              url: 'https://{a-d}.tiles.mapbox.com/v4/mapbox.mapbox-streets-v6/' +
                  '{z}/{x}/{y}.vector.pbf?access_token=' + key
            }),
            style: createMapboxStreetsV6Style(Style, Fill, Stroke, Icon, Text)
          })
        ],
        target: 'map',
        view: new View({
          center: [0, 0],
          zoom: 2
        })
      });
```

**Comment by HarelM** [comment]
Final code - with a lot of hacks (and no proper style).
Parking this feature until beta is completed, therefore placing the code here (or maybe layer I'll create a branch for it).
```ts
let offlineTileLayer = new layer.VectorTile({
	renderOrder: null,
	source: new source.VectorTile({
		projection: "EPSG:3857",
		format: new format.MVT(),
		tileLoadFunction: (vectorTile: VectorTile, url: string) => {
			vectorTile.setLoader(() => {});
			let db = openDatabase("tiles", 1.0, "tiles_db", 100 * 1024 * 1024);
			db.transaction((tx) => {
				let tileCoord = vectorTile.getTileCoord();
				let ymax = 1 << tileCoord[0];
				let params = [tileCoord[0], tileCoord[1], ymax + tileCoord[2]];
				tx.executeSql("SELECT hex(tile_data) as tile_data FROM tiles WHERE zoom_level = ? AND tile_column = ? AND tile_row = ? limit 1",
					params,
					(_, results) => {
						if (results.rows.length !== 1) {
							return;
						}
						let tileData = results.rows.item(0).tile_data;
						var binData = new Uint8Array(tileData.match(/.{1,2}/g).map(byte => parseInt(byte, 16)));
						let isGzipped = binData[0] === 0x1f && binData[1] === 0x8b;
						if (isGzipped) {
							binData = pako.inflate(binData);
						}
						var sourceFormat = vectorTile.getFormat() as format.MVT;
						vectorTile.setProjection(sourceFormat.readProjection(binData));
						vectorTile.setFeatures(sourceFormat.readFeatures(binData));
					},
					(error) => {
						console.error(`Failed executing sql query: ${error}`);
					}
				);
			});
		},
		tileUrlFunction: (c) => {
			return `/${c[0]}/${c[1]}/${c[2]}.pbf`;
		}
	}),
	style: new style.Style({
		stroke: new style.Stroke({
			color: "gray",
			width: 2
		}),
		fill: new style.Fill({
			color: "rgba(20,20,20,0.9)"
		})
	})
});
this.host.instance.addLayer(offlineTileLayer);
```

Will generate this awesome image:
![image](https://user-images.githubusercontent.com/3269297/50705274-eff28a80-1062-11e9-8496-cb0375d14fa5.png)

**Comment by HarelM** [comment]
I'm looking into this project:
https://github.com/oscarfonts/mapbox-gl-cordova-offline
Also this issue:
https://github.com/mapbox/mapbox-gl-js/issues/2920

**Comment by HarelM** [comment]
I'm happy to announce that I can see a map offline in my browser! :-)
Stuff that should be addressed for the initial offline version:
1. Hill shading?
2. Contours?
3. fonts
4. Sprite
5. JSON style
6. Save route to the device without using the server?

Stuff that will be split to other issues:
1. POIs - see, sync, update, create
2. Search - probably not as good as elasticsearch but should work reasonably
3. "Save as" - without using the server and GPSBabel etc - assuming we want to make our app stronger I'm not entirely sure this is truly required.
4. Routing and snapping - probably far down the road, not sure it's a required offline feature

Probably forgot other stuff...

**Comment by HarelM** [comment]
https://pouchdb.com/2016/04/28/prebuilt-databases-with-pouchdb.html
An interesting article on pouchDB which we already use and prebuilt database.

**Comment by HarelM** [comment]
A very interesting article about mabpox-gl and PouchDB.
https://blog.mapbox.com/mapping-moving-objects-with-mapbox-and-a-self-driving-bus-named-olli-f6281e046b1c
Seems like the synchronization of CouchDB in the server and PouchDB in the client is a very powerful tool that we might be able to use in order to sync the data that we want to have available offline.
Having said that, CouchDB and PouchDB do not seem to have a strong geo-spatial solution...

**Comment by zstadler** [comment]
> 
> 
> A very interesting article about mabpox-gl and PouchDB.
> https://blog.mapbox.com/mapping-moving-objects-with-mapbox-and-a-self-driving-bus-named-olli-f6281e046b1c
> Seems like the synchronization of CouchDB in the server and PouchDB in the client is a very powerful tool that we might be able to use in order to sync the data that we want to have available offline.
> Having said that, CouchDB and PouchDB do not seem to have a strong geo-spatial solution...

The article says:

> we’ll use PouchDB in what I call “mirror mode”. Instead of using PouchDB as an in-browser database we’ll just use it as a helper client library to talk to our remote database.

It is not clear to me if the local PouchDB can (a) avoid storing the entire remote DB, (b) be able to serve the local app while disconnected from the remote, and (c) be able to perform partial clean local data without affecting the remote DB.

**Comment by HarelM** [comment]
Another interesting article about an approach called "Offline First".
https://medium.com/@BradleyHolt/from-mobile-first-to-offline-first-3d9968c000f8
In it there's a link to an offline map app that uses pouchdb, leaflet and mapbox:
https://github.com/ibm-watson-data-lab/fieldwork
Seems like it's worth digging into it.

**Comment by HarelM** [comment]
Things I would like to finish as part of this issue, other items probably should have their own issue in order to discuss them there since this feature is already too long:
1. Support offline POI images - low resolution.
2. Make sure add/update POI was not broken as part of this change.
3. Define UX for offline - i.e. what the user would see when the app knows it is offline (now supported).

**Comment by zstadler** [comment]
Things would allow me to use the IHM app as my primary off-road navigation app are:

1. Maintain reliable track recording when the app is in the background for a full day.
2. Allow switching between North-up and Direction-up map orientation when following the GPS position or recording a track.
3. Require confirmation before a recording is stopped.
4. The "Follow GPS" button should not stop a recording. When recording is active, it should enable/disable following the GPS and rotating the map (if applicable).

Other requests may come up once the above is fixed and further real-life testing the IHM app is done.

**Comment by HarelM** [comment]
Remaining for this issue before closing it:
1. Make sure add/update POI was not broken as part of this change.
2. Make sure server interval update is keeping the database up-to-date (so that rebuild results are identical).
2. Add elevation and ITM grid data to POIs (should work the same for online and offline and reduce server calls).
3. Source image link should be local and not remote to present the relevant icon for link or hide links.

Other issues:
1. Allow saving to regular file when offline (currently the file is created in the server since it uploads images to imgur and does the conversion to GPX there).
2. Conversion from of public POIs' features without using the server ("+" sign) - this should be more simple.
3. Refresh map when returning from offline to online - I'm not sure this is easily possible...
4. Offline editing of public POIs and sync when going back to online.
5. Offline routing - huge effort, not sure what's the use case that justify it.
6. Offline search - large effort, not sure the use case of searching while offline justifies it.
7. Offline save as - I don't think it's needed.
8. Offline share creation - not sure how this will work, probably not needed.
9. Offline user shares/traces interaction - medium effort - not sure it is justified.

I believe these are all the abilities of the site that needs the server right now.

**Comment by HarelM** [comment]
Current implementation allows initial testing of offline maps and POIs, no further development is expected as part of this feature. Further development will be split to other issues as needed.

**Comment by zstadler** [comment]
I don't know if this is related to the refactoring, but...

The English version of the site has a Wikipedia POI [here](https://israelhiking.osm.org.il/map/20.00/32.0608/34.7642) for which there is no OSM node. There is no such POI in the Hebrew version of the site. Both Wikipedia languages have an Image.

Ref:
- [English Wikipedia entry
](https://en.wikipedia.org/wiki/Suzanne_Dellal_Center_for_Dance_and_Theater)
- [Hebrew Wikipedia entry](https://he.wikipedia.org/wiki/%D7%9E%D7%A8%D7%9B%D7%96_%D7%A1%D7%95%D7%96%D7%9F_%D7%93%D7%9C%D7%9C)

**Comment by HarelM** [comment]
The refactoring might have affected this, but this issue is now resolved. It will be better to open another issue on this subject so this won't get lost.
There are actually two OSM elements that should be linked to the above Wikipedia entries:
Not really sure how to map fix this right:
https://www.openstreetmap.org/node/5605113504
https://www.openstreetmap.org/way/218656641
Feel free to fix the mapping first so we can see how the merge behaves with a correct mapping.
