### ISSUE TITLE
Support universal links on mobile device

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#784]
## Feature
Assuming #782 will create an app using cordova the following is a great way to open the app with the relevant content:
https://github.com/e-imaxina/cordova-plugin-deeplinks

**Comment by zstadler** [comment]
In particular, add the app to the "Open with" list of applications for `gpx` and `twl` files.

**Comment by HarelM** [comment]
Need to look into the following plug-in (there are several forks of it, this is the original):
https://github.com/j3k0/cordova-plugin-openwith
