### ISSUE TITLE
Show coordinates for public POIs

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#785]
## What I expect to happen
Be able to show the coordinates of a public POI

## What really happened
Currently, one can only see the coordinates of private POIs. As a result, in order to see the coordinates of a public POI one has to
1. Add the public POI as a private POI
2. Click on the newly-added POI
3. Click on the "coordinates" button
4. Optional: delete the temporary private POI

**Comment by HarelM** [comment]
Since ITM coordinates require additional call to the server I decided to remove them from public POI. latitude longitude should be enough, I also don't want to take too much space for that.
