### ISSUE TITLE
Allow opening of a specific POI in a group

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#787]
## What I expect to happen
When several nearby POIs are grouped, and the mouse hovers the group's icon, it will be possible to click on a specific POI name in order to open it.  
For example, allow clicking on each of the POIs in the list below
![image](https://user-images.githubusercontent.com/1304610/44306799-9aad2980-a39e-11e8-97b7-ce0cd9eb33fb.png)

## What really happened
The list disappears as soon as the mouse is moved to one of its items. As a result, the group must be separated, and the appropriate POI located in the zoomed-in map:
![image](https://user-images.githubusercontent.com/1304610/44306822-1a3af880-a39f-11e8-90bf-d7a3ac0c6011.png)

## What I did that caused the issue - step by step
1. Enable all POI layers
2. Open https://israelhiking.osm.org.il/map/15/32.4661/35.5398
3. Hover the mouse on the group in the center of the map
4. Try to click on one of the item in the list

**Comment by HarelM** [comment]
Might be possible if we migrate to OpenLayers. Pending #669 decision.

**Comment by HarelM** [comment]
Changing UX of hover on cluster due to Openlayer migration.
This means that clicking on a cluster will simply open this popup instead of zooming in which the user can easily do by clicking the + or using touch.
