### ISSUE TITLE
Finding missing OSM trails fails

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#792]
## Bug in the website
After uploading an OSM recording and pressing the magnifying glass I get the following Error message:
Http failure response for https://israelhiking.osm.org.il/api/osm/?url=https://www.openstreetmap.org/api/0.6/gpx/2792362/data: 500 Internal Server Error

**Comment by HarelM** [comment]
Can you make this recording public? or upload the file here? I don't have access to it.

**Comment by valleyofdawn** [comment]
https://www.openstreetmap.org/user/valleyofdawn/traces/2792362

**Comment by valleyofdawn** [comment]
Now public

**Comment by HarelM** [comment]
Issue was caused be a jump at the beginning of the recording - a recently added code to ignoe GPS jumps was not bullet proof - now fixed, will be published soon.

**Comment by HarelM** [comment]
Issue is described below, waiting for a release fix.
https://github.com/NetTopologySuite/NetTopologySuite.IO.GPX/issues/28
