### ISSUE TITLE
.GPX files doesn't load

### ISSUE THREAD

**Issue by ronhl** [IsraelHikingMap/Site#794]
## What I expect to happen
I try to load previously saved .GPX files.

## What really happened
 The site responds "לא ניתן למצוא מידע גיאוגרפי בקובץ..."
Some files do load, but the title is missing

## What I did that caused the issue - step by step
nothing. all I did was the same as last week.

## My environment
* Operating System and version: tried on various systems
* Web Browser and version: tried on various browsers

## Thing I think the developers should know, images, links etc.
I add 3 files as examples:
03-04 - loads with no problem
30 - loads, but title is corrupted
55-56 doesn't load at all
[קבצי דוגמה.zip](https://github.com/IsraelHikingMap/Site/files/2346614/default.zip)

**Comment by HarelM** [comment]
Thanks for reporting! 
We'll take a look at it in the next days, hopefully.

**Comment by HarelM** [comment]
@gavze, @ronhl Thanks for reporting!

**Comment by HarelM** [comment]
@ronhl @gavze Where did you get these files? They were certainly not created using IHM site.
Seems that the "creator" field is empty and that's what's causing this error.
I'll see if I can have this fixed but meantime please contact the site/app you got this files from and let them know that the files they create have issues.

**Comment by HarelM** [comment]
Sorry, this is due to a bug in the old code of the site.
Please use the following site to open and save the GPX file to be able to open it back in IHM.
Sorry for the inconvenience...
http://www.gpxeditor.co.uk/

**Comment by HarelM** [comment]
@ronhl @gavze The site was updated with a fix to solve this.
No need to do anything manually now.
