### ISSUE TITLE
Allow adding POI pictures directly from the device camera

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#799]
## Feature
This is yet another spin-off of #782.
Allow adding a picture to a POI straight from the camera on android device with cordova
It seems that Chorme does this out of the box.
Camera related SO questions:
https://stackoverflow.com/questions/35090461/using-camera-on-phonegap-app-with-only-html-input-without-camera-api
https://stackoverflow.com/questions/26381050/choose-camera-in-file-upload-in-cordova-application-on-android-without-using-cor
https://stackoverflow.com/questions/21523544/html-file-input-control-with-capture-and-accept-attributes-works-wrong

Seems like this is an annoying issue.
Some possible solutions that needs to be tested:
1. Use crosswalk?
https://crosswalk-project.org/documentation/cordova.html
2.  add all the following plug-ins:
 * cordova-plugin-camera
 * cordova-plugin-media-capture
 * cordova-plugin-device
 * cordova-plugin-file
 * cordova-plugin-media
3. 1+2?

**Comment by HarelM** [comment]
I have tried 2 and it didn't work on its own.
I couldn't make 1 work locally due to compilation issues :-/
See here:
https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/issues/205

**Comment by HarelM** [comment]
The following is even worse :-(
https://www.ipragmatech.com/fix-html5-file-input-cordova-android/

**Comment by HarelM** [comment]
Maybe [cocoon](cocoon.io) is an option?? I'm getting tired of this nonsense...
This also have a JS hack that might work:
https://blog.kiprosh.com/photo-upload-from-phone-gallery-or-phone-camera-in-ember-cordova-application/

**Comment by sputn1k** [comment]
@HarelM looks like we are in the same boat here -.- been struggling to get this to work for days now. I have tried Cocoon but if I build with Webview, Webview+, Canvas+ etc - But compile fails

Any luck with workarounds? I have compiled a Cordova app with crosswalk but did nothing? input file does not trigger the Camera overlay from the webview.

**Comment by sputn1k** [comment]
@HarelM I just managed to get this working with Crosswalk!!! been at it for days now.. can't believe this bug! was a nightmare to sort out... The only thing that works with Cordova framework was Crosswalk browser. 

On the page I am loading in I'm using - 
`<input type="file" accept="image/*" capture="capture" />`

Also, make sure you are loading in the crosswalk browser and not the default Android webview with InAppBrowser etc. 

I'm using to launch it - 
`window.open('http://example.com', '_self');`

Make sure all the permissions are set in the **AndroidManifest.xml** - 
    ```
<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-feature android:name="android.hardware.location.gps" />
    <uses-feature android:name="android.hardware.camera.autofocus" />
    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera.back" />
    <uses-feature android:name="android.hardware.camera.front" />
```

From what I have read you need - **android.permission.WRITE_EXTERNAL_STORAGE** 

Config settings after installing the plugin I am using in **config.xml** - 
```
<plugin name="cordova-plugin-crosswalk-webview" spec="^2.4.0">
        <variable name="XWALK_VERSION" value="23+" />
        <variable name="XWALK_LITEVERSION" value="xwalk_core_library_canary:17+" />
        <variable name="XWALK_COMMANDLINE" value="--disable-pull-to-refresh-effect" />
        <variable name="XWALK_MODE" value="embedded" />
        <variable name="XWALK_MULTIPLEAPK" value="true" />
        <variable name="XWALK_COMMANDLINE" value="--disable-gpu-rasterization" />
    </plugin>
```

**Comment by HarelM** [comment]
Do you have a repo I can have a look at? Compilation with crosswalk failed when I tried it... :-/
Which android sdk are you building against?

**Comment by sputn1k** [comment]
@HarelM nope sorry it's a private clients repo. 

I didnt change the Android SDK version - 
`<uses-sdk android:minSdkVersion="16" android:targetSdkVersion="23" />`

**Comment by sputn1k** [comment]
Crosswalk is your way out. Get that working and it's your way out.

**Comment by HarelM** [comment]
Did you follow the gradle hack above in order to make the crosswalk compilation work? Our did it work out of the box for you?

**Comment by sputn1k** [comment]
@HarelM No I didn't from what I recall, just followed this - https://crosswalk-project.org/documentation/cordova.html

**Comment by HarelM** [comment]
:-/ ok, thanks! I'll keep at it. we probably have different environments and targets if this worked for you and doesn't for me...

**Comment by HarelM** [comment]
BTW, how did you get to read this issue?

**Comment by sputn1k** [comment]
Linked through from somewhere else cant remember. When searching for workarounds on the issue.

**Comment by HarelM** [comment]
I'm added the following plugin to overcome crosswalk compilation issues:
cordova-android-support-gradle-release
After successfully compiling with crosswalk this issue seems to be fixed but crosswalk generates other issues:
1. Something related to the multiple apk generated by crosswalk (I'll probably need to sign them all):
https://stackoverflow.com/questions/28706892/how-can-i-publish-to-play-store-the-x86-and-arm-apks-of-my-cordova-crosswalk-app
2. When I debug the app on my device it tells me that I need to install crosswalk project service x64, I would like to avoid asking this from my users if possible.

@sputn1k did you encounter those issues?

**Comment by HarelM** [comment]
There's an issue about the project service x64 here:
https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/issues/203
Seems like the solution is to set `<preference name="xwalkMultipleApk" value="false" />`.
Or manually installing the armv7 apk for debug and uploading armv7 and x86 apks to the store.
Interesting stuff... ish...

**Comment by HarelM** [comment]
Crosswalk performance are just horrible. Need to understand if this is related to my code or crosswalk's.

**Comment by sputn1k** [comment]
@HarelM Crosswalk performance was bad? I'm surprised seemed to run faster here, but I am testing on an emulator. 

What do you mean by angular directive? Your app is Cordova Angular (or a website loading into a wrapper)?

**Comment by HarelM** [comment]
Im using cordova as a wrapper to my site with limited native capabilities.
See the following commit to what I did:
https://github.com/IsraelHikingMap/Site/commit/5d1e58f45cf45de01bd1371890de15b746100a83
After that I just added the ability to take a picture from the gallery using my ui infra.

**Comment by HarelM** [comment]
When I tested crosswalk on my device it hanged. I'm not sure why, but it didn't happen prior to the crosswalk switch. And also 20 mb for a feature of 20 lines of code seems like an overkill...
