### ISSUE TITLE
Ergonomic improvements for app navigation:

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#801]
## Feature
Speaking from a POV of a MTbiker running the app on a handlebar-mounted smartphone while riding (challenging but not un-common scenario)

1)	The buttons are smallish and hard to press accurately. In the mobile site I can increase their size, not in the app. A 50% increase in width would be welcome.
2)	The “stop recording” button is next to the “return to current position” button. I mis-pressed it a few times, cutting my recording into several segments, which was frustrating. Even though they belong together thematically, I would separate them.
3) There is no compelling reason to hide the "record" button till the "locate" button is pressed. It makes it hard for first-time users to start navigating with the app.
4) It is hard to immediately tell what is a planned route and what is a recorded track, and it is hard to understand what is happening when they overlap. SInce planned routes should not obscure map features I suggest the default would be wide and semi-transparent, recordings could be narrow and opaque. See example.
![image](https://user-images.githubusercontent.com/689201/45481475-48b8b300-b754-11e8-877c-0e46f45ab6e5.png)

**Comment by HarelM** [comment]
I understand your concerns but bikers are far from the only users this app has, I think we shouldn't look at it from this pinhole.

**Comment by valleyofdawn** [comment]
Maybe. Point 3 and 4 are universal, though. Increasing button size would also improve legibility.

**Comment by HarelM** [comment]
> There is no compelling reason to hide the "record" button till the "locate" button is pressed. It makes it hard for first-time users to start navigating with the app.

I don't agree - unless we decide to remove this button completely when using mobile device you need to make the GPS find you first.
I don't think most users need to record their outdoor experience so this is again advanced usage which revels according to context, much like other advanced features.

I agree with @zstadler about the size of the buttons, it's crowded as it is, making the larger will render the map useless...

**Comment by valleyofdawn** [comment]
I think people will use the app to navigate, otherwise why bother downloading an app when you get the same functionality from the mobile site.  Recording would probably be the most common activity on the app (unlike changing the language :) ) and should therefore be easily discoverable and require just one button press. 
I think the "locate me" button should also be always there. Pressing the record button should first center the location and then start the recording. 
I see your point about the button size. Too large is no good, so is too little. I think the sweet spot is a little larger to be comfortable. Please indulge me with the small space between the buttons, though.
How about the different default appearance of planned routes and recordings though?

**Comment by niryariv** [comment]
If I may suggest a UX solution:

1. Make the buttons bigger.

2. Tapping an area of the map without buttons in it makes the buttons slide out. Tapping again makes them slide back in. ("Tap" meaning a single finger tap, to differentiate from zooming or panning actions)

In the future perhaps consider a record mode which keeps the relevant buttons on the map in all views.

**Comment by valleyofdawn** [comment]
Specifically I suggest using red (FF0000) solid line for the recording. No ant column. 100% opacity. 25% width. It should appear on top of planned routes.
Also it should end with a directional arrow, not an end point icon. 
Red is good since it has a high contrast with most backgrounds and corresponds with the "record" button.
For a planned route I suggest using blue (0000FF) line either with an ant column or arrows. 50% opacity.

**Comment by valleyofdawn** [comment]
Yes, it might not work well on red biking paths either. Purple paths are
more numerous. Pink is just plain ugly.
By 25% I meant the location on the width slider with 100 being the thickest.

>

**Comment by valleyofdawn** [comment]
After some testing, dark orange may be less confusing for the recording.

**Comment by HarelM** [comment]
@valleyofdawn can you send the hex color for the orange?
Also, I think most of the requirements in this feature are implemented in the beta version. Can you confirm?

**Comment by valleyofdawn** [comment]
Closing in favor of detailed issues
