### ISSUE TITLE
Sign in to OSM using Google account fails

### ISSUE THREAD

**Issue by ATGardner** [IsraelHikingMap/Site#803]
## Bug/Feature
I have just installed the app, and tapped on the 'sad face' icon at the top right. In the browser window that opened, I tapped on the "G" icon at the bottom, like I always do when I need to sign into my OSM account (either from the IsraelHiking website, or any other website/app)

## What I expect to happen
I expected the sign in to succeed, and to have my OSM user logged into your app

## What really happened
I got the following error screen:
![image](https://user-images.githubusercontent.com/538720/45487727-e2d62680-b767-11e8-802a-2b1da677420a.png)

## My environment
* Operating System and version: Android 6.0 running on MIUI Global 9.6.1 on Redmi Note 4
* Web Browser and version: I'm not sure which WebView version my phone is currently using.

**Comment by zstadler** [comment]
If I read the error message correctly, it is a restriction imposed by Google for security reasons and that this login approach is available only available within approved browsers and not from apps.

Moreover, the login page where the "G" symbol exists is the OSM page and we do not have any control on its contents.

Please login using your OSM user id.

P.S.,
You may wish to open a bug report with OSM so that the "G" button is not shown for unsupported "User-Agent"s

**Comment by ATGardner** [comment]
I looked around in SO and found some suggestions - If I understand correctly, you can try sending a different UserAgent to the OSM login page. I'm not sure if this is a valid solution, or just a hack.
https://stackoverflow.com/questions/40591090/403-error-thats-an-error-error-disallowed-useragent

Another solution might be to initiate the entire login in a browser window, instead of an internal WebView. This might be a more stable approach.
https://stackoverflow.com/questions/48717573/403-disallowed-useragent-solution-for-website-android-and-ios-app

**Comment by HarelM** [comment]
Opening the phone's browser doesn't work as I need to listen to the url change in order to get the auth details, this can probably be fixed if the app knew to listen when the phone surf to a specific address, but it's a huge pain to test it and implement it.
Changing the user agent seems like a hack, I'm not sure I want to go down this path...
Bottom line, I suggest to use regular OSM credentials...

**Comment by HarelM** [comment]
This is now open too much time without anyone stepping up to try and fix this.
Since there's a workaround using regular OSM credentials and "forgot my password" flow I closing this.
If anyone in the future would like to handle this please be my guest.

**Comment by HarelM** [comment]
https://github.com/RocketChat/Rocket.Chat.Cordova/issues/159
This might help - setting override user agent.

**Comment by HarelM** [comment]
Seems like InAppBrowser plugin has this support for overriding user agent of the browser it opens.
Worth testing...
@ATGardner Will you be able to test this if I create an app with this configuration?

**Comment by ATGardner** [comment]
Yeah, I'd be happy to give it a go

**Comment by HarelM** [comment]
@ATGardner Can you check the following version to see if it works?
https://ci.appveyor.com/project/IsraelHikingHost/site/builds/30530775/job/x5aiqvjmi7v4r7s0/artifacts
Also worth checking that regular sign-in works as well.

**Comment by ATGardner** [comment]
I uninstalled the store version of the app, and installed the APK from the link you posted.
When I tried logging in, and selected the Google icon, I did get to the login page of Google. However, I am using 2fa with a physical key, and Google advanced protection, and after entering my username and password, on the following screen I got "this browser does not support security keys", so I can't actually finish logging in using Google.
But I expect this will work for someone else with a simpler Google account security settings. Maybe someone else can give it a go.

I was able to sign in with the standard osm username and password.

**Comment by HarelM** [comment]
Thanks for your time! I can't find a lot of info regarding 2fa with physical key and webview, besides articles saying it's not possible.
I believe the main case described here in the initial post is now solved so I'm closing this issue, as I believe it applies to most users.
Also there's a workaround to use OSM credentials.
Thanks again!

**Comment by HarelM** [comment]
Sorry, I need to revert this due to side effects it causes. see #1152.

**Comment by HarelM** [comment]
When the following PR might be resolved I might be able to support this request.
https://github.com/apache/cordova-plugin-inappbrowser/pull/581

**Comment by HarelM** [comment]
It seems that this issue caused the app to be removed from the play store.
While we managed to get the app back to the play store the issue still exists.
It also might affect the impression of users interacting with the app for the first time.
After a long trial and error I think I found a solution for this:
in-app-browser still has the problem with the user agent (more than 2 years now, I don't expect it to be fixed unfortunately).
But I think it will be possible to do it with the cordova-plugin-oauth and a custom scheme.
Current problems that I found and I need to fix:
1. Collision with the deeplinks plugin
2. Missing support for androidx

**Comment by HarelM** [comment]
Missing androidx support was handled by a fork (and a PR: https://github.com/AyogoHealth/cordova-plugin-oauth/pull/23).
Collision with deeplinks was fixed by adding to the deep links the custom scheme.
This still need to be tested on iOS to see that the login flow works as expected there.

**Comment by HarelM** [comment]
It seems that the fix I made is crashing on iOS for some reason :-(
I need to debug it and see what's wrong there...
