### ISSUE TITLE
[App] Notification icon has a typo

### ISSUE THREAD

**Issue by ATGardner** [IsraelHikingMap/Site#804]
## What I expect to happen
The notification should read
"רצה ברקע"

## What really happened
The notification has
"רצה בקרע"

## My environment
* Operating System and version: Android 6.0 running on MIUI Global 9.6.1 on Redmi Note 4
* Web Browser and version: I'm not sure which WebView version my phone is currently using.

**Comment by zstadler** [comment]
The translation was corrected.

Thanks for reporting!
