### ISSUE TITLE
אפליקציה חדשה

### ISSUE THREAD

**Issue by odedshilo** [IsraelHikingMap/Site#806]
## Bug/Feature
(Delete the non-relevant)
האייקון של האפליקציה זהה לאייקון של האתר המוכר
## What I expect to happen
עדיף אייקון שונה לאפליקציה מהאייקון של האתר

## My environment
* Operating System and version:
* Web Browser and version:

**Comment by zstadler** [comment]
This issue report was probably created by mistake.

If not, please edit the original post and add the requested information.
