### ISSUE TITLE
Map record is zigzag

### ISSUE THREAD

**Issue by onzd** [IsraelHikingMap/Site#808]
## Bug/Feature
(Delete the non-relevant)

## My environment
* Operating System and version:
* Web Browser and version:

## Thing I think the developers should know, images, links etc.

https://israelhiking.osm.org.il/share/4CqLlDFm3z

**Comment by zstadler** [comment]
The application is recording the location that the GPS sends "as-is". It does not filter or smooth the recorded track.

It seems like the problematic section of the track was recorded under trees and between buildings where GPS reception may have been poor and created these "jumps". 

![image](https://user-images.githubusercontent.com/1304610/45495255-90066a00-b77b-11e8-82f8-22df3a1da697.png)

**Comment by onzd** [comment]
Thanks you are right next time i will chek in open fileds

בתאריך 13 בספט׳ 2018 17:39,‏ "zstadler" <notifications@github.com> כתב:

**Comment by zstadler** [comment]
Thank you for your report!
