### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by yargolan** [IsraelHikingMap/Site#809]
## Bug
typo

## What I expect to happen
רצה ברקע

## What really happened
רצה בקרע

## What I did that caused the issue - step by step
בדיקת האפליקציות שרצות כרגע על המכשיר

## My environment
* Operating System and version: Android 8.0.0
* Web Browser and version: n/a

## Thing I think the developers should know, images, links etc.
אין עליכם. אחלה אפליקציה, מחפש באגים נוספים...

**Comment by zstadler** [comment]
This issue was already reported and fixed in #804 
Thanks for the report!
