### ISSUE TITLE
Waypoint too obtrusive

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#81]
IMHO, when sharing routes (in a small iFrame) or on a cellular screen the waypoints/route nodes are too obtrusive. They block the view. Smaller round points would do better.
I think in terms of convention, drop marks are used more for interest points and round nodes for waypoints, which are technical elements and should not call the viewers attention to anything. See for instance directions on google maps. I'm not even sure they are needed at all, since you can pull random dots on the course and drag them around. Some people are not aware of that option.

**Comment by HarelM** [comment]
I have tried it, in a previous version, when the route way point marker is smaller you can't click on it in order to remove it or drag-move it. Reducing the size is not an options.
Changing from a drop to a circle for way points is a possibility but would not help solving this issue.

**Comment by HarelM** [comment]
Since you select a route point for navigation the fact that you have a drop help you know where you set the routing points, placing a circle would obscure where you want the routing to go through.

**Comment by valleyofdawn** [comment]
Sorry, but why should clicking be a problem? The active area for clicking could be exactly the same, it's only the visual element that needs to be smaller (though still noticeable) so that it doesn't block the view.
I can see the point in using drops when using touchscreens, just make them smaller.

**Comment by HarelM** [comment]
I'm not planning on starting to insert transparent elements to the map behind the icon, it was hard enough to make the current icon appear in the right place.
I think the route sharing looks fine, reducing the size of the markers will not help a lot in your case as there are too many markers in the same area.

**Comment by zstadler** [comment]
I think #valleyofdawn proposed to replace the waypoint icon with a new icon
with the same width and height in pixels, but with a smaller non
transparent icon picture in it.
I can create it if you agree to this direction.

**Comment by HarelM** [comment]
I'm not using an image for the marker icon, I'm using font awesome library with html and css, it's much faster and allows me to set the color as I want, this is not possible with an image. But it does not allow a lot of manipulation like images does.

**Comment by HarelM** [comment]
I don't have a good way of solving this without splitting the client into mobile and desktop separate clients. This will have to do...
