### ISSUE TITLE
text slide / overlap

### ISSUE THREAD

**Issue by yargolan** [IsraelHikingMap/Site#810]
## What I expect to happen
Multiple words should be one near the other

## What really happened
Text overlaps and cannot be read

## What I did that caused the issue - step by step
Add a new POI.
Change its icon
try to save

## My environment
* Operating System and version:
Samsung 8, Android 8.0.0

## Thing I think the developers should know, images, links etc.
I'd appreciate if you could show me how to add screenshots to the bug report

**Comment by zstadler** [comment]
Screenshots and other files can be attached after switching to the desktop site here

![screenshot_20180913-184731](https://user-images.githubusercontent.com/1304610/45499706-9c8fc000-b785-11e8-940b-63e6e2cc8ffb.jpg)

**Comment by yargolan** [comment]
![screenshot_20180913-183519_israel hiking map](https://user-images.githubusercontent.com/5415524/45502056-9f8daf00-b78b-11e8-9456-0c2f400d0c70.jpg)

**Comment by yargolan** [comment]
Please take a look on the lower part of the picture.
thanks
