### ISSUE TITLE
Open Menu wishlist 

### ISSUE THREAD

**Issue by 4Z1ZV** [IsraelHikingMap/Site#812]
## Feature
Display only relevant file types. (i.e twl, gpx, etc).

Enable selection of file types.

## My environment
* Operating System and version:
* Web Browser and version:

**Comment by HarelM** [comment]
Thanks for taking the time and reporting this feature request.
Seems like this is not fully supported by the technology we are using.
However, I think the following issue should facilitate for the required behavior: #784 - when selecting a file the application will suggest itself as a possibility to open it.
