### ISSUE TITLE
DropBox support

### ISSUE THREAD

**Issue by 4Z1ZV** [IsraelHikingMap/Site#813]
## Feature
Enable selection of files from DropBox.

## My environment
* Operating System and version:
* Web Browser and version:

**Comment by HarelM** [comment]
Can you please add a screen shot of an application that does that and show what you expect to see with this app.
If the phone doesn't support choosing files from dropbox I don't see how our app will be able to select those files.
If the files are located in your file system you should be able to pick them up, wouldn't you?

**Comment by HarelM** [comment]
This is now open for too long without a response.
I believe this is a duplicate of #844
I'll add a comment there regarding dropbox support, or more precisely, chrome extension that will work for both dropbox and google drive.
