### ISSUE TITLE
 : כשטוענים מסלול, המפה לא עוברת לאזור המסלול.

### ISSUE THREAD

**Issue by bentzp** [IsraelHikingMap/Site#814]
## Bug/Feature
: כשטוענים מסלול, המפה לא עוברת לאזור המסלול.
Delete the non-relevant)

## My environment
* Operating System and version:
* Web Browser and version:

**Comment by HarelM** [comment]
Please provide the relevant file and elaborate on the exact steps you did that cause this issue.
Thanks for taking the time and reporting this issue!

**Comment by bentzp** [comment]
הבעיה נפתרה.
איתור המקום gps היה פתוח. כשסגרתי אותו הבעיה נפתרה.
תודה

בנצי

בתאריך שבת, 15 בספט׳ 2018, 16:53, מאת Harel M ‏<notifications@github.com>:
