### ISSUE TITLE
Wikipedia link jambled in Hebrew

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#817]
## What I expect to happen
When opening a private POI using the Hebrew interface and pressing the coordinate button I expect the Wikipedia coords to apear like in the english version:
{{Coord|31.6512|35.0049|display=|type:landmark}}

## What really happened
They appear like this:

![image](https://user-images.githubusercontent.com/689201/45612989-6f852b00-ba6d-11e8-850d-5be33cadc241.png)

and when copied to Wikipedia produce an error.

## My environment
Chrome on windows 10.

## Comments
I'd rather have a copy button without showing the code. would keep a cleaner dialog box and simplify copying.

**Comment by HarelM** [comment]
Related to #785 - this should have the same UX in both cases.
>I'd rather have a copy button without showing the code. would keep a cleaner dialog box and simplify copying.

I agree.

**Comment by HarelM** [comment]
Sorry, I'm removing Wikipedia completely from private POI.
Wikipedia editors shouldn't have any issues copy the coordinates and place them in the right Wikipedia article with the right annotation. The type is probably incorrect and the display is empty.
I'll change the order of the coordinates so it'll be easier to copy them.
