### ISSUE TITLE
Support file association on mobile device

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#820]
## Feature
Split #784 into this in order to split check-ins and ability to test.
When clicking on a `gpx` or `twl` file open IHM application with the file loaded. 

## Thing I think the developers should know, images, links etc.
Need to look into the following plug-in (there are several forks of it, this is the original):
https://github.com/j3k0/cordova-plugin-openwith

**Comment by zstadler** [comment]
@HarelM,
Would this issue also cover `gpx`, `kml` and `twl` URLs, or would you prefer a separate issue for URLs?

**Comment by zstadler** [comment]
Please ignore the URL request.

It looks like Firefox uses different application lists when opening a file just after completing a download  and when opening the file from [about:downloads](about:downloads).

Since Chrome is OK, I'm assuming it's a Firefox bug.

**Comment by zstadler** [comment]
Removing twl support has implications on the project's relevance to off-roading in Israel. 

It deserves a separate issue for discussion, if you want to explore this direction.

**Comment by HarelM** [comment]
Watching both
https://github.com/apache/cordova-cli/issues/357
And 
https://github.com/j3k0/cordova-plugin-openwith/issues/45

**Comment by HarelM** [comment]
@zstadler @valleyofdawn Seems like the last check-in fixed this issue.
Closing. Please install the latest version and let me know if it works as expected.
