### ISSUE TITLE
Can't save gpx to phone 

### ISSUE THREAD

**Issue by nadavheimann** [IsraelHikingMap/Site#824]
## Bug
(Delete the non-relevant)

## What I expect to happen
Gpx file save on the my android 

## What really happened
Noting 

## What I did that caused the issue - step by step
Open sheard course, save as, doesn't heppen nothing 

## My environment
* Operating System and version:
* Web Browser and version:

**Comment by HarelM** [comment]
Thanks for reporting! Save as should probably not exist for mobile device...

**Comment by zstadler** [comment]
"Save as" is valuable on the mobile device to communicate with other apps that need different formats as well as sharing and sending through various channels.
