### ISSUE TITLE
Automatically return to current position after panning

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#826]
## Feature
When in GPS active mode it would be useful to automatically go back to center.
After 20 seconds it would be useful if the map automatically centers back to the current position.

**Comment by valleyofdawn** [comment]
##Bug
This feature stopped working
##To see the bug
In the app
1) Click current location and wait for a fix
2) Pan the screen to a different location
3) Wait 
5) Nothing happens

**Comment by HarelM** [comment]
Yup, Thanks for reopening this issue. I wanted to make sure all the related stuff of following and keeping north up are working as expected before adding this back.
Wasn't sure this was an important feature, but If you reopened it then it means it is.
I'll fix it in next commit.

**Comment by HarelM** [comment]
@zstadler @valleyofdawn please check this with latest version including all scenarios related to panning the map, rotating. keeping north up, keep follow GPS mode and all that with recording. Thanks!
Feel free to report here or in #1096.

**Comment by valleyofdawn** [comment]
Thanks! Seems like the creation of the Android artefact failed in AppVeyor.
