### ISSUE TITLE
Simplify showing an external route

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#83]
Perhaps allow pasting the link in the share box.
Users have no way to discover this feature.

**Comment by HarelM** [comment]
I was thinking of writing about it in the help or in the github documentation, but I'm not sure how useful this feature is, you can always download the file and open it with the file open button...
Also this feature currently is very limited to sites that supports CORS.
regardless, I'll think of a way, I think it should be implemented when I have a good server side support so I can send either a url or a file and the server will return the relevant geojson.
