### ISSUE TITLE
When searching for a trail the drop down list cover the option to switch to 4X4 road

### ISSUE THREAD

**Issue by Moshe81** [IsraelHikingMap/Site#835]
## Bug/Feature
(Delete the non-relevant)
Bug
## What I expect to happen
I will be able to filter for Bycycle/Foot/Car even when the list is shown

## What really happened
I only see foot option and I can not change to 4X4
I do not see the trail for 4X4 I only see the bicycle option - actually it does not have any impact so maybe I dont know how to use it - but any way I dont think it should shift when the search option is highlighted
## What I did that caused the issue - step by step
Type on the search text box "ירושלים"
you will get a list of items
now try to filter for 4X4 items

you will not see this iteam as the drop down list hide it 

![image](https://user-images.githubusercontent.com/29856634/46045576-c1d9e200-c126-11e8-9da2-eaa35300a393.png)

## My environment
* Operating System and version:
Windows 10  English version
Latest Chrom
* Web Browser and version:

**Comment by HarelM** [comment]
I think you miss interpreted the meaning of this button.
When opening the point-to-point search you can choose two locations and ask for a route between them.
This is not a search filter.
You can filter what's presented on the map by using the layers pane on the left, under public routes.
