### ISSUE TITLE
Small enhancements to directional search results

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#836]
## What I expect to happen
Be able to modify a route that was created by a search.

## What really happened
The route cannot be edited. The origin and destination locations cannot be changed. Intermediate points cannot be added. Instead, click-and-drag on the route pans the map.

## What I did that caused the issue - step by step
1. Click the search button
2. Click the "+" for route search
3. Type "יוטבתה" as the origin and select "יטבתה, מחוז הדרום" from the drop-down list
4. Type "שחרות" as the destination ans select "שחרות, מחוז הדרום" from the drop-down list
5. Click on the left arrow to search for a route
6. Click on the route edit button
7. try to modify the route

**Comment by HarelM** [comment]
This is a read-only search results mode.
Did you try clicking the + to add it to your private routes?

**Comment by zstadler** [comment]
I did not realize that the "שחרות, מחוז הדרום" pop-up was referring to the route. I assumed it was referring to the destination and ignored it.

![image](https://user-images.githubusercontent.com/1304610/46207726-0507a100-c331-11e8-914f-ec510c4f141f.png)

Similarly, clicking on the origin POI shows "יטבתה, מחוז הדרום" 

![image](https://user-images.githubusercontent.com/1304610/46208598-e5be4300-c333-11e8-8d34-07c0189ff24f.png)

I suggest:
1. The title in the pop-up will be same as the route name after clicking the "+" button. In this example: 
    "יטבתה, מחוז הדרום-שחרות, מחוז הדרום" or "מסלול: יטבתה, מחוז הדרום-שחרות, מחוז הדרום"
    <img width="33%" src="https://user-images.githubusercontent.com/1304610/46208068-2a48df00-c332-11e8-96c8-3eda3e058529.png">
2. The pop-up will be placed at the start of the route
3. A click on the origin or the destination will show this pop-up
4. A click anywhere on the route will show this pop-up

**Comment by HarelM** [comment]
I don't understand what is suggested and how it's different than what there is today.
Can you please describe the feature request using the following template:
As a user I world like to ... So that I'll be able to...?

**Comment by HarelM** [comment]
@zstadler, I'm currently rewriring this due to #669. The only diff required here is the text on the marker popup?
Route click is not planned for this feature, it's extremely hard to click on a route so it won't be implemented due to UX considerations.

**Comment by zstadler** [comment]
Changing the title of the pop-up is one thing. That pop-up also appears when clicking on the origin and destination markers.

I also requested that initially (after performing the search) the pop-up will appear on the origin (יוטבתה) rather than the destination (שחרות)

Implementation of a click on the route is not a priority and can be avoided for complexity reasons.

**Comment by HarelM** [comment]
Still need to implement click, and maybe change the Icon of the start and end points.
