### ISSUE TITLE
POI's "details dot" is language independent

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#837]
## What I expect to happen
The "details dot" to show on a POI icon only if it has a picture or description in the current language.

## What really happened
When in Hebrew mode, the POI icon for "שמיר" (Kibbutz Shamir) has a dot, but the POI does not have a picture or a description.

## What I did that caused the issue - step by step
Open https://israelhiking.osm.org.il/poi/OSM/node_278475660?language=he or search for "שמיר" in Hebrew mode.

## My environment
* Operating System and version: Any
* Web Browser and version: Any

## Thing I think the developers should know, images, links etc.

![image](https://user-images.githubusercontent.com/1304610/46254854-6f8a1f80-c49e-11e8-882a-232b385e1cef.png)

Currently the OSM entry for Shamir has a `wikipedia=en:Shamir, Israel` tag. As a result, this information is not shown in Hebrew mode. Perhaps the existence of the dot is caused by the existence of a `wikipedia` tag, regardless of the `en` language in the tag's value.

P.S., after this issue is resolved, I plan to change the `wikipedia` tag to the Hebrew page.

**Comment by HarelM** [comment]
I'm not sure this will be still possible after migration to OpenLayers (#669) as the whole marker concept is different there and it doesn't support html markers, I'll see what I can do though.
This is related to a fix made in #686.

**Comment by HarelM** [comment]
When merging POIs the merge is currently not language specific. The dot will appear in case there's an image, a description or a merged entity.
See the code here:
https://github.com/IsraelHikingMap/Site/blob/bccdebaee9d34ec7ef8446ed585925fea5f46428/IsraelHiking.Common/Extensions/GeoJsonExtensions.cs#L260
Since this code is calculated when the POI is fetched for initial presentation then this info might not be accurate due to language relation.
This might be fixed when migrating to offline POIs by storing all the data in the client side, but I'm not sure it will be the right solution for the site though...
In any case, I don't have a good idea how to solve this right now...

**Comment by HarelM** [comment]
This is no longer relevant after the POI refactoring (#783) since the check for references was removed and all the processing is done before merging.
I looked in the code, I couldn't find a test case since Shamir was fixed (by me apparently... :-/).

**Comment by zstadler** [comment]
I can look for a suitable example using Overpass-Turbo, but it is not clear hat are the conditions for having an English Wikipedia link and no Hebrew link?

I've tried the combination of:
- `wikipedia` tag starts with `en:`
- No `wikidate`, `image`, or `description` tags
- The Wikipedia page dos not have an Hebrew version (manually checked)

I've found [this one](https://israelhiking.osm.org.il/poi/OSM/node_5605113504?language=en), but for some reason, the image from the English Wikipedia page was not taken to the POI layer. Please consider if this is a bug.

As a result, I was unable to check if this issue was resolved.

**Comment by HarelM** [comment]
Yes, the original issue was with a merged OSM-English Wikipedia only entity. The entry in Hebrew had a (קיבוץ) suffix and so it wasn't merged.
Please open a different issue for the odd merge you've found, I'll look into it to see what went wrong.
