### ISSUE TITLE
Got lost warning - display sound when failing to follow a route

### ISSUE THREAD

**Issue by ylivny** [IsraelHikingMap/Site#838]
## What I expect to happen
When loading a route to the map and walking a long the route, I suggest to add a "warn me if I'm lost" button. Once pushed, the device will generate a warning sound if the device is not on the route.

The user will be able to define what is the distance from the path the will yield a warning.

**Comment by HarelM** [comment]
Thanks for the feature suggestion!
What is the use case this feature should solve?
When I hike, I look at the phone occasionally to make sure I'm going the right way, my phone is silent any way so a sound won't help me.
When riding a bike you probably have the app open in front of you and when driving the tablet should probably be open.
So I don't see who will benefit from it... (putting aside the complexity of the needed UI, configuration and implementation which is not trivial).

**Comment by ylivny** [comment]
The use case I see is for hiking.
As you say, when you hike, you look at the phone **occasionally** to make sure you are going the right way. What if you missed a turn and you are going the wrong way? You will only discover it the next time you look at your phone, which might be after a long time.

I suggest to add a possibility to raise an alarm if you are off trail so that you will discover that you took a wrong turn as soon as possible (e.g. when you are 100m off the trail). Sure, for that you will need not to put your phone in silent mode but I am not sure this is a deal breaker.

As I suggested, the distance will be calculated from a loaded route so the application will knoiw where you plan to walk.

**Comment by valleyofdawn** [comment]
I don't think it is a high priority, especially since we don't yet have a designated "route to follow".
But I also see a use case for biking.
When I'm on a long trip I keep my smartphone on the handlebar but the screen is turned off to save battery life. Many, if not most, other bikers carry it in their pocket or backpack to avoid damaging the smartphone in crashes or hard drops.

**Comment by HarelM** [comment]
Closing in favor of #929.

**Comment by HarelM** [comment]
Reopening this issue as #929 will only cover the concept of a route to follow and I would like to handle the concept of sound/vibration in this issue.
Deviation distance will not be configurable to reduce configuration complexity and will be set to 50 meter.
A user will be able to opt in to this feature using the current configuration screen.

**Comment by valleyofdawn** [comment]
I suggest also adding a different "back on course" sound.

**Comment by HarelM** [comment]
This is now implemented in the foreground only, will be released to production soon.
In order to be able to do it in the background the background geo-location plugin should be altered to facilitate for following a route. I don't see this happening with the resources we have.

**Comment by valleyofdawn** [comment]
Not working for me. I get the orange circle disappear from the planned route, or route deleted, and receive no beep or vibration. Done in the foreground. Attaching log.
[Report_2020-05-15_09-35-19.971_.zip](https://github.com/IsraelHikingMap/Site/files/4638075/Report_2020-05-15_09-35-19.971_.zip)
Version 9.0.160 of the app on Android.

**Comment by valleyofdawn** [comment]
Really don't know What else I can say.
I planned a route. Followed it, saw the orange circle on the height profile. Moved more than 50 m away from it. Saw the fix disappear, received no beep or vibration.
Also, I planned a route, saw the fix. deleted it as suggested, and got no beep.
What else do you need to know?
Do you want me to create a new log with the second scenario?

**Comment by valleyofdawn** [comment]
Turns out the option was not selected under advanced settings.
Sorry.
Will try it again in the field later.
