### ISSUE TITLE
Lookout feature - tell users what they see in the distance

### ISSUE THREAD

**Issue by ylivny** [IsraelHikingMap/Site#839]
## Feature
I don't really know what location-related information is available to the developers, but I assume that the following 3 can be accessed:
1) current location
2) direction (the direction to which I point the device)
3) horizontal angle 

If this is correct then using these pieces of information it is possible to implement a feature that will tell to the user what he/she sees in the distance.

The user pressed a designated button and then points with the device to a location (as if it was a binocular) and the application will mark on the map the area that was pointed.

**Comment by HarelM** [comment]
Thanks for the suggestion.
Can you please elaborate how will the user benefit from it?
Assuming #669 and #800 will be implemented the user can see on the map where the phone is pointing to. Is this a duplicate then?

**Comment by ylivny** [comment]
Indeed, if there will be an arrow pointing to the direction of the phone it can assist in identifying what one sees in the distance. However, sometimes there are multiple elements in the same direction (e.g. several villages, some are visible and some are not due to topography).

It will be cool if you could point to a specific direction and using the horizontal status of the device the map will present something like heat map of the things that you see in that direction depending on your elevation, the topography, and on the elevation of elements in that direction

**Comment by HarelM** [comment]
There will be probably other apps that can do it, using augmented reality etc. I think the linked issues will be enough for this app.
Since I'm not planning on creating a native app due to maintenance overhead I don't see how this will be implemented.
Unless someone is planning on giving a hand with the development.
Closing, sorry...

**Comment by ylivny** [comment]
I understand.
If I'll have some free time in the future I might offer a hand on this (or other features).

Thanks anyway
