### ISSUE TITLE
Missing "x" (close) for most pop-up windows

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#84]
Add "x" [Close] button at the top-right corner of the pop-up windows for the "?" [Help], "i" [Info], [Save as], and [Share] buttons, similar to the "x" in the [Route Statistics] pop-up window.
Currently, pop-up windows can only be closed by clicking again on the button that opened them.

**Comment by HarelM** [comment]
The only one that has a close button is the one you can be dragged around.
But since it's not much of a work I can put it in in one of the releases...

**Comment by valleyofdawn** [comment]
+1 for x's. The way you close them now is not intuitive.

**Comment by HarelM** [comment]
Published, Enjoy!
