### ISSUE TITLE
Can't delete a partially-uploaded POI

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#840]
## What I expect to happen
When I start uploading a POI to OSM but do not save it, I expect 
1) for it to revert to a private POI, rather than a public one
2) being able to delete it.
## What really happened
It permanently remains on the map with the icon of an OSM POI.

## What I did that caused the issue - step by step
Create a private POI
Hit the upload button
Hit close (without hitting save first!)
Try to remove the new POI from the map by clicking the POI and then clear
Fail

## My environment
Chrome on Win10

**Comment by HarelM** [comment]
I need to revise the entire upload new POI flow, it has some issues in it. This is related to changes I made to support opening poi from link with the application.
Thanks for reporting!
