### ISSUE TITLE
Changes in track definition box

### ISSUE THREAD

**Issue by ronhl** [IsraelHikingMap/Site#841]
## Bug/Feature
The track definition box in the site changed from the previous detailed one to a very simple one.
The options to change the path width and opacity were removed, along with the tools to delete, create markers, change navigation, jump to path and save.
Is this intentional?

## What I expect to happen
old (good and detailed) box on the left, new (simple) box on the right
![image](https://user-images.githubusercontent.com/42948764/46389378-1eff0600-c6da-11e8-96dd-f70c281bea1f.png)

## My environment
* Operating System and version:
* Web Browser and version:

**Comment by HarelM** [comment]
Please enable advance mode again (toggle button at the top of the layers control).

**Comment by ronhl** [comment]
Thank you.
Was the default changed?

**Comment by HarelM** [comment]
No, I replaced the mechanism so the value got reset to default (which is off), I'll probably change it again soon so bare in mind that you might need to toggle it again in the near future.
Sorry.

**Comment by ronhl** [comment]
OK. Other than that, you are doing a great job.
