### ISSUE TITLE
Enlarge map in app

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#842]
## Feature
In modern smartphone the DPI is typically higher than on monitors, the map features appear small and hard to read, especially on the move. Street name for exmaple are practically illegible until you go beyond the 16 zoom into "digital zoom"
I suggest showing the maps by default at a 2x digital zoom to clarify details on smartphone screens.

**Comment by HarelM** [comment]
This is probably not an issue only on mobile devices but on desktop as well - remember the mobile first approach.
I propose to fix this in the map tiles and not in the website client.

**Comment by HarelM** [comment]
Closing as I don't think this should be handled in the client.
