### ISSUE TITLE
Zoom using sound buttons

### ISSUE THREAD

**Issue by mishikuno** [IsraelHikingMap/Site#843]
Feature

## What I expect to happen
possible to zoom in and out the map with sound buttons 

## What really happened
you must zoom with fingers on the screen

**Comment by valleyofdawn** [comment]
Former Orux users would know this.
Low priority I think.

**Comment by HarelM** [comment]
I'm not planning to do it since most user will not know this feature exist, and no one has pitched in to do it. Closing...
