### ISSUE TITLE
Correct legend locations

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#845]
## Bug
Due to map updates, some legend entries no longer show the intended objects. Other legend items need to or added or removed. 

- Location update
   - [ ] red trail (marked trails, hiking map only)
   - [ ] path (tracks and paths)
   - [ ] dry riverbed (water)
   - [ ] secondary (roads, increase zoom level for MTB map)
   - [ ] tertiary (roads)
   - [ ] water tower (water)
   - [ ] attraction (poi, MTB map only)
   - [ ] holy place (poi, avoid attraction overlap in mtb map) 
   - [ ] supermarket (poi, MTB map only)
   - [ ] toilets (poi, MTB map only)
   - [ ] sand (areas)
   - [ ] grass(areas)
   - [ ] quarry (areas, re-position to mtb's icon)
   - [ ] construction site (areas, re-position to mtb's icon)
- Missing entries
   - [ ] water tank (water, add to both maps)
   - [ ] river (water, exists, add to hiking map)
- Remove entries
   - [ ] playground (POI, remove from hiking map)
   - [ ] Both maps no longer distinguish between residential and unclassified (including living_street, service, and road types). There should be one entry for both with the title "Residential or other road" - "רחוב או כביש אחר". The location should be taken from the current residential entry.
- Change order
   - [ ] move low-speed after residential (roads, impacts MTB map only)
   - [ ] move cemetery into POI category

**Comment by zstadler** [comment]
Updated locations table

| Entry |Latitude, Longitude | Zoom |
|---|---|---|
|red trail|33.288602, 35.74152914|15|
|path|31.298556, 35.264225|16|
|dry riverbed|31.218711, 34.759026|15|
|water tank|33.0754925, 35.1646104|16|
|water tower|32.248446, 34.926639|16|
|primary|31.7449610, 34.861808|14|
|secondary|31.7422, 34.7209|14|
|tertiary|29.786839, 35.002484|16|
|attraction|31.011766, 34.508008|16|
|holy place |32.814602, 34.9871233|15|
|supermarket|32.4326800, 34.9219280|16|
|toilets|31.0162196, 34.7610432|16|
|sand|31.746489, 34.602857|16|
|grass|32.112186, 34.916375|16|
|quarry|31.232381, 35.204895|16|
|construction site|30.980369, 34.922879|15|

**Comment by valleyofdawn** [comment]
I have a few additions, what do you do to get the co-ordinates now that they're gone from the POI dialog?

**Comment by HarelM** [comment]
Both private and pivlic pois have coordinates...

**Comment by valleyofdawn** [comment]
Where?
![image](https://user-images.githubusercontent.com/689201/47615060-a01ba400-dab2-11e8-80e5-8639f1e41b62.png)

**Comment by HarelM** [comment]
In the readonly mode - exit editing and click on the poi.

**Comment by valleyofdawn** [comment]
Thanks.
This is a little non-intuitive and requires several clicks (6 to be exact) for people wanting to figure out the co-ordinates of a place.

**Comment by HarelM** [comment]
Sounds about the right complexity. I have never used the coordinates for anything.
If you try and look in the osm iD editor you'd have even harder time finding it.
I wouldn't expect this comment from someone who keeps arguing we should simplify the UI - this is the cost of UI simplification. I stand by it.

**Comment by valleyofdawn** [comment]
On the other hand, in [CalTopo](https://caltopo.com) or Amud Anan, which have similar functionality as our site, it requires zero clicks.
If we think a feature is not useful, we should drop it, not make it unreasonably cumbersome to use.

**Comment by zstadler** [comment]
I use this feature regularly. IMHO, the info is useful also in edit mode.

**Comment by HarelM** [comment]
I fail to see the use case for regular, non advance, users.

**Comment by HarelM** [comment]
Coordinates discussion is related to #846. Feel free to comment there. let's not continue it here.
@zstadler feel free to update the openlayers branch with the new info, I'm guessing some of the points are new as I haven't found them with a simple search.
`info-sidebar.component.ts`

**Comment by HarelM** [comment]
@zstadler I have merged #669 to stable, feel free to update the location of the legend points.

**Comment by valleyofdawn** [comment]
Entry | Category | Latitude, Longitude | Zoom
-- | -- | -- | --
red trail |   | 33.288602, 35.74152914 | 15
water tank |   | 33.0754925, 35.1646104 | 16
water tower |   | 32.248446, 34.926639 | 16
primary |   | 31.7449610, 34.861808 | 14
secondary |   | 31.7422, 34.7209 | 14
tertiary |   | 29.786839, 35.002484 | 16
attraction |   | 31.011766, 34.508008 | 16
supermarket |   | 32.4326800, 34.9219280 | 16
toilets |   | 31.0162196, 34.7610432 | 16
sand |   | 31.746489, 34.602857 | 16
grass |   | 32.112186, 34.916375 | 16
quarry |   | 31.232381, 35.204895 | 16
construction site |   | 30.980369, 34.922879 | 15

MTB Map
Entry | Category | Latitude, Longitude | Zoom
-- | -- | -- | --
path | Tracks and Paths | 32.640789, 34.965041 | 16
Dry riverbed | water | 31.24348, 34.833312 |  
Synagogue | Points of Interest | 31.765309, 35.211828 | 16
Holy place | Points of Interest | 32.697452, 35.016088 | 15
Sport facility | Points of Interest | 32.464677, 34.951415 | 16
Attraction | Points of Interest | 31.83382, 34.865947 | 16
Bike Shop | Amenities | 31.869133, 34.821149 | 16
First aid | Amenities | 32.08311°, 34.890392° | 15
Nature reserve | Borders and Special Areas | 31.582219°, 34.590261° | 16
Military base | Borders and Special Areas | 31.767649, 34.72199 | 16
Firing Zone | Borders and Special Areas | 31.176825, 34.526918 | 15

Power line and playground make more sense under amenities than under POIs
military area no longer needed
Maybe add minefield where one is going to be?

**Comment by zstadler** [comment]
###Legend-related
The existing zoom for Dry riverbed will be preserved.

Playground is indeed an amenity. It should show only on the MTB legend.

Power Lines are a navigation aid. Much like antennas, they are of no other interest. The group title can be modified to "Points of Interests and Navigation Aids" to be more accurate. This is, IMO, an unnecessarily long title.

Military areas, include practice areas and everything else, which is more than only `military=barracks`. Nothing changed with the recent mapping of additional practice areas and the existing titles captures this correctly.

###Map-related
Sport Center is not part of the "Unify icons between MTB and IHM" issue [#160](https://github.com/IsraelHikingMap/Map/issues/160) resolution. It makes more sense to unify with Playground.

**Comment by valleyofdawn** [comment]
I'll consider unifying playgrounds and sport facilities, although it's hard to think of an icon that would capture both. (Both are places you are likely to find drinking water BTW - that's why they are there).

We now have two different area shadings for firing zones and the rest. We should differentiate this in the legend somehow. You can figure out the correct names. Apart from bases and minefields what else is out there. 

I'm fine with the rest of your comments.

**Comment by zstadler** [comment]
#### Updated location locations

Entry | Location | Zoom | Comment
-- | -- | -- | --
Red Trail | `lat: 33.288602, lng: 35.74152914` | 15
Path | `lat: 32.640789, lng: 34.965041` | 16 | Moved
Dry Riverbed | `lat: 31.24348, lng: 34.833312` | 16
Water Tank | `lat: 33.0754925, lng: 35.1646104` | 16 | New
Water Tower | `lat: 32.248446, lng: 34.926639` | 16
Primary | `lat: 31.7449610, lng: 34.861808` | 14
Secondary | `lat: 31.7422, lng: 34.7209` | 14
Tertiary | `lat: 29.786839, lng: 35.002484` | 16
Attraction | `lat: 31.83382, lng: 34.865947` | 16 | MTB Only
Synagogue | `lat: 31.765309, lng: 35.211828` | 16
Holy Place | `lat: 32.697452, lng: 35.016088` | 15
Sport facility |  `lat: 32.464677, lng: 34.951415` | 16 | New, MTB Only
Nature reserve | `lat: 31.582219, lng: 34.590261` | 16
Military Area | `lat: 31.214912, lng: 34.65281` | 16 | Moved
Practice Area | `lat: 31.204708, lng: 31.204708` | 15 | New, Moved
Bike Shop | `lat: 31.869133, lng: 34.821149` | 16 | MTB Only
First Aid | `lat: 32.08311, lng: 34.890392` | 15 | MTB Only
Supermarket | `lat: 32.4326800, lng: 34.9219280` | 16 | MTB Only
Toilets | `lat: 31.0162196, lng: 34.7610432` | 16 | MTB Only
Grass | `lat: 32.112186, lng: 34.916375` | 16 | MTB Only
Sand | `lat: 31.746489, lng: 34.602857` | 16
Quarry | `lat: 31.232381, lng: 35.204895` | 16
Construction Site | `lat: 30.980369, lng: 34.922879` | 15 | MTB Only

#### Other changes
- Move Playground to Amenities category
- Remove Lift Gate
- Add Bollards to MTB legend
- Discuss the new Sport Center icon as a replacement for the Playground icon
