### ISSUE TITLE
Add coordinates button when in POI edit mode

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#846]
## What I expect to happen
As a user I would like to be able to see the coordinates of a private POI even when I'm in POI edit mode.
For example, I've added a POI and I want to see its coordinates, or I moved a private POI and I'd like to see the new coordinates.

## What really happened
The coordinates button is available only when in read-only mode

## What I did that caused the issue - step by step
1. Enter POI edit mode
2. Create a new POI
3. No coordinates button is available for the new POI
4. Turn-off the POI edit mode
5. Click on the POI
6. Click on the coordinates button to see the coordinates.

## Thing I think the developers should know, images, links etc.
Editing a new POI:

![image](https://user-images.githubusercontent.com/1304610/46568585-22032c00-c950-11e8-8965-c94f1b0b1a2f.png)

Viewing an existing POI:

![image](https://user-images.githubusercontent.com/1304610/46568608-71e1f300-c950-11e8-815e-6fceb4ba367b.png)

**Comment by HarelM** [comment]
This was solved as part of #669 and #933.
