### ISSUE TITLE
stay in position when clicking a POI\route

### ISSUE THREAD

**Issue by Shemesh** [IsraelHikingMap/Site#847]
## What I expect to happen
when clicking a POI or a route keep the map in position\zoom the user set.

## What really happened
currently when clicking a POI or a route the map is automatically zooming in and moving position to center and zoom on that point. 

this is kind of annoyance (UX wise) because i already choose an area to watch, i only want to see the information of a point, without the map deciding what's good for me.

TODA.

**Comment by HarelM** [comment]
Thanks for taking the time and opening this issue.
While you might not agree with it there's a logic to center the POI when opening it - you can hover on it in case you do not want to fully open it.
Nevertheless, I understand your requirement/frustration.
I'm currently working on #669 and there's a lot of changes involved related to it, I'll keep this issue in mind.

**Comment by HarelM** [comment]
Looking back at this, I still think this is the right behavior... Closing...
