### ISSUE TITLE
KM marks malfunction when recording a track

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#849]
## What I expect to happen
When enabling the KM marks I expect them to show the correct kilometrage I've covered.

## What really happened
Km marks  start at my current position, take a straight line to the starting position and then follow the route. (See image and note difference from height profile)

![screenshot_20181011-074224_israel hiking map](https://user-images.githubusercontent.com/689201/46831802-06af7b00-cdad-11e8-9ba4-67bf27b8bdda.jpg)

**Comment by HarelM** [comment]
Not planning of fixing this before migrating to openlayers.
Please make sure to test this behavior once I finish the migration.

**Comment by HarelM** [comment]
Seems like this is solved in beta site.

**Comment by HarelM** [comment]
Fixed while working on #669.
