### ISSUE TITLE
Create short URLs for sharing

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#85]
Using client-side JavaScript, as described at 
http://stackoverflow.com/questions/4760538/using-only-javascript-to-shrink-urls-using-the-bit-ly-api

**Comment by HarelM** [comment]
When using this from client side only, one can "hijack" the API_KEY and use it, not that it concern me too much, but still. the correct way to do it is with server side.
but if there is a server side we can always create our own mechanism that will get the route shorten, no real need for bit-ly...

**Comment by HarelM** [comment]
Whooo... that was a hard one...

**Comment by zstadler** [comment]
No Pain, No Gain :-)
