### ISSUE TITLE
Improve legibility of height profile in app and mobile site

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#854]
Feature
The Height profile is squashed vertically in app and mobile site. This makes it hard to read the heights and assess the slope visually.
We can utilize the bottom of the screen and move the stats around to achieve a better result. See image.
![default](https://user-images.githubusercontent.com/689201/47613690-99823200-da9c-11e8-850d-7ed43f865c4b.png)

**Comment by valleyofdawn** [comment]
It would be useful, when recording a track, to also show the time elapsed and the current speed.
As shown below:
![image](https://user-images.githubusercontent.com/689201/50524930-35520d80-0ae1-11e9-8461-88b37fd4c867.png)

**Comment by valleyofdawn** [comment]
Harel M said:
This makes this panel too crowded.
Can you live without the total elevation and drop while recording? If so I might be able to replace them. But this should be handled as part #854 and taken into consideration.
Please close this one or the other issue as they are on the same subject.

**Comment by valleyofdawn** [comment]
I can live without the total descent but not without the total ascent.
Alternatively we can dedicate a button to open a separate panel (the size of the height profile but without a graph) with all the relevant stats. (e.g. average speed etc.).

**Comment by HarelM** [comment]
I tend to think it's an overkill...
Most statistics are not really interesting in most cases for most users.
In any case, please provide a full description of how you would like to see this panel when collapse and expanded including the new features. You might want to use advanced mode here as well...

**Comment by valleyofdawn** [comment]
![image](https://user-images.githubusercontent.com/689201/50540628-fe8dfd00-0b9d-11e9-81e2-2ba371aed410.png)

**Comment by valleyofdawn** [comment]
The pie chart icon would appear when recording is activated. Pressing it would show this panel. Pressing it again, or the X would collapse it. The numbers are big on purpose, for legibility on the go.
Granted, this is geared toward cyclists, but they are an important demographic we serve. Especially since other Israeli apps focus on other groups.

**Comment by valleyofdawn** [comment]
Less wasteful:
![image](https://user-images.githubusercontent.com/689201/50541005-71e73d00-0ba5-11e9-9482-05fe7d1b63a7.png)

**Comment by HarelM** [comment]
I don't understand where the height graph is when this is on.
Does this appear only when recording? Why changing the current icons, I believe they are clear enough.
Average speed and current speed is confusing and most user wouldn't be able to understand the difference.
Which part of this is available on desktop? How will is look? Will you have a full screen button there as well?
As I asked, please provide a fully detailed description of this feature, the above screenshots are lacking...

**Comment by valleyofdawn** [comment]
This is a separate window than the height graph.
There is no point showing them together since the data partially overlaps. 
This, is covers the height profile icon. To see the height profile you should close this window and open the height graph.
I added this because you said it's too crowded for the permanent stats display at the bottom.
The think is, with planned routes there is no time dimension. Once you start recording, there is, and more statistics come into play. 
As I indicated. When there is no recording the pie-chart icon is hidden. 
When you start recording, the pie chart icon appears alongside the graph icon. 
Once pressed it opens the above window, covering the bottom of the screen, including the height profile.
I agree that the speed and average speed icons are similar, it would be easy to tell which is which when you stop. If you have a suggestion for the avg. speed icon let me know.

**Comment by HarelM** [comment]
It doesn't make sense to put this button there, and the pie chart is not intuitive.
Again, this does not take into consideration the earlier request and does not explain how a user should interact with it.
Meaning, I'll have to define it myself and you would probably disagree.
As I said many times, recording well not be part of the desktop site. Having said that, there's nothing preventing me from opening a route and checking hiw much time it took.
The only way to procewd IMHO is for you to create a powerpoint presetstion with the required UX. failing to do so will mean you are fine with whatever I decide to do.

**Comment by valleyofdawn** [comment]
I can fiddle with the ppt mockup tomorrow.
Where would it make sense to put the button, then?

בתאריך שבת, 29 בדצמ׳ 2018, 21:31, מאת Harel M <notifications@github.com>:

**Comment by HarelM** [comment]
The icon is not the problem, the fact that there are two things that are almost identical is.
I would consider letting go of avg speed.
Regarding the button - it would make sense to allow a user that would like to see more details to do so in the context of the current statistic.
I would place such a button at the end of three stats - clicking it would change the statistics window to show these extra values instead of the graph, this will require another button to switch back.
Note that the bottom of the screen can't be used for two "reports" without the ability to let the user switch between the two, preferably inside this space.
This is just an idea, and probably how I would've implement it...

**Comment by valleyofdawn** [comment]
I can see your reasoning. Will try to figure out a way to do it.

**Comment by HarelM** [comment]
If you can't make the difference between them more prominent I won't be able to add them both.
Also, I'm not planning on changing the current icons and their location or font size, it takes to much time and has little benefit. You are welcome to learn css and improve them.

**Comment by valleyofdawn** [comment]
![average speed](https://user-images.githubusercontent.com/689201/50547958-12446c80-0c4d-11e9-8cb7-7a40cca5ff8a.png)
Some ideas. Or we can go with a descriptive text instead of icons, since space is less of an issue.

**Comment by HarelM** [comment]
There's no place for a descriptive text and I fear these icons will not look too different in their planned size (those with the gauge), the gaossian is not intuitive for me...
Maybe we can place "<##.#>" to better show the difference?

**Comment by valleyofdawn** [comment]
I'm running out of ideas. Frankly I don't think the icon issue is a deal-breaker. The user would learn which is which through the values.
![speed](https://user-images.githubusercontent.com/689201/50838429-a6f24d00-1366-11e9-9a97-6bd3abf7a857.png)

**Comment by HarelM** [comment]
What about my suggestion to surround the numbers and use the same icon?

**Comment by valleyofdawn** [comment]
1) I don't mind using "<##.#>" to stress the difference, or we could use "~##.#"
2) We still need 2 different icons to convey the meaning as well.
3) We should also decide on the format of the numbers - maybe show seconds only in trips below an hour and hours above it.
4) What do we show when there are no time data? Only the bottom row in the table, or an empty row above it?

**Comment by valleyofdawn** [comment]
Good. We'll go with my last icon suggestion then?
Let me know if you need any SVGs or PNGs and their dimensions.

**Comment by valleyofdawn** [comment]
Also I think it would be cool and save button presses if whatever configuration (table or graph) was opened last appeared as the icon of the "route statistics" button and open when pressed.
If I'm not clear I can produce an interactive ppt mock-up.

**Comment by HarelM** [comment]
Last icons remind me of fuel, I like the avg and its counterpart better.
I'll need svg of them, and the table icon.
Correct me if I'm wrong but in graph mode the length etc are not shown any more?

**Comment by valleyofdawn** [comment]
I can see what you mean about the fuel guage.
How about the shape of the first guage and the concept of the second?
Yes, the stats are missing from the graph on purpose.

**Comment by HarelM** [comment]
Maybe I do need a ppt with how it would look.
Please consider the following use cases:
On mobile
On desktop
When GPS is not active
When GPS is active
When recording

**Comment by valleyofdawn** [comment]
[speed.svg.txt](https://github.com/IsraelHikingMap/Site/files/2769021/speed.svg.txt)
[Average speed.svg.txt](https://github.com/IsraelHikingMap/Site/files/2769022/Average.speed.svg.txt)
[Time.svg.txt](https://github.com/IsraelHikingMap/Site/files/2769025/Time.svg.txt)

**Comment by valleyofdawn** [comment]
Here's a mock-up presentation. Didn't have time to differentiate between active recording and past recording, but I think this part should be straight-forward.
Also I didn't replace the icons.
[טבלת נתוני הקלטה.pptx](https://github.com/IsraelHikingMap/Site/files/2769646/default.pptx)

**Comment by HarelM** [comment]
Thanks, but I need to know what you have planned for the desktop version, in regular and expanded state, as least.

**Comment by HarelM** [comment]
I've added the relevant code to calculate the needed statistics, waiting on the UI definition to start changing the UI.

**Comment by valleyofdawn** [comment]
Regarding the web versions.
The mobile version should look like the app one.
The PC version should not expand the window when in stats-table mode.

**Comment by HarelM** [comment]
@valleyofdawn The mobile version of the app will be like the app, no problem.
So let me know if I understand correctly:
The desktop site height profile window will look like the mobile app. when using the expand mode the table button will be disabled and when using the table mode the expand button will be disabled?
Did you take into consideration the fact that when planning a route with the height bar open on desktop the user will not be able to see the route length and other statistics? I tend to think this is a degradation in UX...
Might be better to have a short conversation on this on the phone...

**Comment by HarelM** [comment]
According to #948 there's a request to add a slope graph.
I personally think this is an overkill for most users, but adding a small button to switch between height and slope shouldn't be too hard.

**Comment by valleyofdawn** [comment]
Attached is an interactive ppt with the behavior in the web version.
[stats for app.pptx](https://github.com/IsraelHikingMap/Site/files/2952019/stats.for.app.pptx)

**Comment by HarelM** [comment]
This is the proposed solution to this issue, after a long time trying to implement the relevant style:
![image](https://user-images.githubusercontent.com/3269297/54206373-dd705380-44e0-11e9-8213-142c8597e7c1.png)
![image](https://user-images.githubusercontent.com/3269297/54206404-e7925200-44e0-11e9-8300-c33b581e647f.png)
I'll see if I can style it a bit better but no guarantees - it takes a very long time to make everything move to the right place and then it breaks when checking out mobile... :-(

**Comment by valleyofdawn** [comment]
If possible, please increase the font size. This is meant to be read on the move and the extra white space is wasteful and unsightly.

**Comment by HarelM** [comment]
On mobile device is will look better, I'm wondering if to invest more time in styling this for desktop only, as I see no real added value there.
In any case, I'm thinking on adding back the statistics under the graph in desktop as there's enough space for both of them. I'll continue playing with it until I find it pleasing I guess...
![image](https://user-images.githubusercontent.com/3269297/54312662-26f39800-45e0-11e9-9d68-48607cb0fad3.png)

**Comment by HarelM** [comment]
> You are also missing the X axis on the height graph.

Thanks!
>ש rather than שע is the conventional way to denote hours. Is it minutes:seconds till 59 min?

Fixed and yes.

>If possible, please increase the font size

Done.

**Comment by HarelM** [comment]
@valleyofdawn assuming the following build won't fail, please see if this is what you aimed for:
https://ci.appveyor.com/project/IsraelHikingHost/site/builds/23087193/job/l72ql25ts5k4wjee

**Comment by HarelM** [comment]
#948 was not implemented as part of this issue since it is not as small as I thought.

**Comment by valleyofdawn** [comment]
The problem as I see it is that, unlike the height graph, which is by definition smooth, the slope graph has a very high frequency, making it totally illegible in longer routes.
If we think a graph can have up n min/max points to be legible, than we should take the whole length and divide it into n sections with a slope calculated to each.
