### ISSUE TITLE
OpenLayers site beta - bugs and design improvements

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#857]
#
Bugs 
1)	No tooltips for the reorient (B&W arrow) button.
2)	Base maps do not need a transparency slider.
3)	The transparency slider should be green, not yellow. (maps and overlays properties dialog boxes)
4)	Showing ESRI servers will be dearly missed, for feature servers and non-standard maps servers. It’s worth exploring a solution 
5)	Changing the icon for private POIs doesn’t work
6)	Private POI display edit doesn’t work (the pen icon is non-responsive)
7)	Show coordinates of private POI – height doesn’t show
8)	In a reasonably long track, showing all WPTs on the track froze the site.  I would so away with this very advanced feature rather than handle it.
9)	When updating an existing shared track. The thumbnail presented at the final dialog is not updated.
10)	In non-edit mode. Hovering over a track doesn’t show the position on the height profile.
11)	When opening a geo-tagged image. It goes to the right location but doesn’t show a POI with the image.
12)	Clearing a track with the x button doesn’t remove it from the private track list.
13)	In the legend, in several categories (e.g. points of interest), the examples cover the text, making the legend useless.
14)	When searching for a route, e.g. a MTB relation, it doesn’t show its course until you chose “add as track”.
Design improvements
1)	When opening a GPX file it opens by default with a very thin, barely visible black line.
2)	Maps and overlays properties dialog box is busy – self-evident elements should be removed
3)	Using the asterisk in the GUI is weird. You see it in online forms, not user interfaces
4)	Private POI only opens when you click on the drop icon. Should work when clicking the description as well.
5)	Table of icons for private POIs too dense.

6)	Auto-return to current position is unneeded when viewing the map or planning a route on a PC. It happens even as you interact with the maps and is disruptive. Should work only when recording a track/navigating.
7)	Show/hide public POIs (eye button) shouldn’t close the list of POIs, we have the collapse button (arrow) for that and this behavior makes it harder to control the POIs you want to show. Same with public tracks.
8)	The convention for collapsible lists is for the collapse button to be before the item list, not after it. I keep expecting the positions of the + and ^ buttons to be reversed and I mis-press the + button.
9)	These features should only appear with “advanced options” on. 
a.	Add map, add layer, Add route (“+” buttons)
b.	Cut route, reverse route
10)	Private POI display
a.	The up-arrow is non-intuitive for close, and the tooltip says "פחות"
b.	I find the camera icon to be too offensive. Maybe go with an empty frame with a smaller camera icon inside. Also I can improve the icon. Maybe lose it altogether.
11)	In the clean feature dialog (X button) the list is too loosely spaced, reduce the space between lines.
12)	When dragging a WPT is stays behind and only updates its position when you release.
13)	Reverse track – This feature is useful where it is located (at the end nodes of tracks) but hard to find. Maybe also put it at the track properties dialog.
14)	Crawling ants effects was cool. Maybe replace it with arrows?
15)	All newly opened GPX tracks appear black, rather than go through subsequent colors.

**Comment by zstadler** [comment]
- [ ] When selecting a search result, the location icon does not show on the map
- [ ] When the window/screen is small and narrow, the route statistics, scale bar, and the IHM logo are partially hidden below the buttons
- [ ] The standard OSM map is drawn below the base map

**Comment by HarelM** [comment]
I have moved most of what's here to #669.
I'm currently ignoring issue that existed before openlayers migration such as 9 & 19.
You are welcome to open these items as separate issues.
If you think something is missing please comment there.
I'll update the site after I'll fix some of the issues.
