### ISSUE TITLE
Javascript Background Geolocation

### ISSUE THREAD

**Issue by RichardMaher** [IsraelHikingMap/Site#858]
WRT https://github.com/w3c/ServiceWorker/issues/745 which I have been band from, please download and run (albeit in the foreground) https://github.com/RichardMaher/Brotkrumen

Then please ask W3C and UA developers by the ServiceWorker.TravelManager is not being implemented.

**Comment by HarelM** [comment]
I have seen some of your posts, and I generally agree.
However, I have no clue who's responsible for implementing this and have serious doubts it will be implemented soon, So I see no other option besides using Cordova as far as I can see.
When this will be implemented I can consider switching to PWA, but I think this technology is not ready yet for production purposes as it misses some of the basic aspects of using the HW's such as file system, no-sql database, and of course your favorite - geo-location...
