### ISSUE TITLE
http://osm.org.il/IsraelHiking/IsraelMTBmap.html is gone

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#86]

**Comment by HarelM** [comment]
I don't want to support two sites. Do you have a suggestion what can we do? Even if I add the file back it won't work because I moved ask the js files...

**Comment by HarelM** [comment]
Will be fixed and part of issue #87

**Comment by zstadler** [comment]
Could it be an HTML file that includes the Israel Hiking HTML file and just
modifies the default, or move the shared code into a 3rd file and have the
Israel Hiking and Israel MTB files source the 3rd file and just set the
default.

**Comment by HarelM** [comment]
It's a bit more complicated than that. Wouldn't it be simpler to just redirect to the regular url with map=MTB? this way when sharing it will always point to the index.html.

**Comment by zstadler** [comment]
Your original idea was to create a page that will automatically use the MTB
map.
I think that the redirection will do that, but I'm not 100% familiar with
the details.
