### ISSUE TITLE
ESRI layers support under OpenLayers

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#860]
## Feature

This issue aims at collecting the information for the potential support of ESRI layers under OpenLayers.
In particular, ESRI server URLs that do not use the `{x}`, `{y}`, and `{z}` parameters.

### ESRI Map Server
Use the [`export`](https://developers.arcgis.com/rest/services-reference/export-map.htm) API to retrieve raster data with the following steps:
1. Check the server capabilities:
   GET `<baseurl>/?f=json`
    where `<baseurl>` is the user-provided map address. 

2. Send an export request: 
   GET `<baseurl>/export?bbox=<bbox>&size=<width>,<height>&dpi=96&format=<format>&transparent=true&bboxSR=3857&imageSR=3857&f=json`
   where
   - `<bbox>` is the bounding box of the map in EPSG 3857 coordinates
   - `<width>` and `<height>` are taken from the map size in pixels
   - `<format>` is one of the image formats listed in the `supportedImageFormatTypes` attribute of the step 1 response. 
      Note that the native format is usually the first value in the comma-separated list. For example, `PNG32` in the case of a `PNG32,PNG24,PNG,JPG,DIB,TIFF,EMF,PS,PDF,GIF,SVG,SVGZ,BMP` attribute value.
3. download the image:
   GET the URL given by the `href` attribute the step 2

### ESRI Feature Server
Feature server provide vector data. They usually are capable of providing GeoJSON output. However, the feature drawing description language is very rich and may require significant resources to implement the openlayers-equivalent of [esri-leaflet-renderers](/Esri/esri-leaflet-renderers)

1. Check the server capabilities:
   GET `<baseurl>/?f=json`
    where `<baseurl>` is the user-provided map address. 
   - Supported query output formats are listed in the `supportedQueryFormats` attribute.
   - Drawing information for the features is described by the `DrawingInfo` attribute. 

2. Retrieve the features using the [`Query`](https://developers.arcgis.com/rest/services-reference/query-feature-service-.htm) API:
   GET `<baseurl>/query?returnGeometry=true&where=1=1&outSr=4326&outFields=*&inSr=4326&geometry={"xmin":<xmin>,"ymin":<ymin>,"xmax":<xmax>,"ymax":<ymax>,"spatialReference":{"wkid":4326}}&geometryType=esriGeometryEnvelope&spatialRel=esriSpatialRelIntersects&geometryPrecision=6&f=geojson`
   where
   - `<baseurl>` is the user-provided map address.
   - `<xmin>`, `<ymin>`, `<xmax>`, and `<ymax>` are taken from the map bounding box in WGS84 (EPSG 4326) coordinates.

**Comment by jgravois** [comment]
@HarelM i don't know of any projects to simplify working with Esri services in OpenLayers.

**Comment by jgravois** [comment]
you can find a couple examples of a Leaflet map that displays a custom CRS to load Esri services in projections other than web mercator here:

* http://esri.github.io/esri-leaflet/examples/non-mercator-projection.html
* http://esri.github.io/esri-leaflet/examples/non-mercator-projection-2.html

**Comment by HarelM** [comment]
Currently the only code I'm using for ESRI layers is to add `tiles/{z}/{y}/{x}` which is extremely naive. The above example from the site's facebook group doesn't work with this suffix. It did work however with leaflet-esri without any non-mercator projection stuff...
I'm not sure how to proceed here as I don't even know where to start in order to support any of this in OpenLayers... :-(

**Comment by zstadler** [comment]
Another direction for exploring is

https://openlayers.org/en/latest/apidoc/module-ol_source_ImageArcGISRest-ImageArcGISRest.html

**Comment by zstadler** [comment]
An example is available a

https://openlayers.org/en/latest/examples/arcgis-image.html

Its description says:

> This example shows how to use a dynamic ArcGIS REST MapService. This source type supports Map and Image Services. For dyamic ArcGIS services.

**Comment by zstadler** [comment]
I've created [an example](https://jsfiddle.net/c7vgxwon/) where OpenLayers shows two ESRI MapServices: Orthophoto base map and a Geology overlay.

Feature Services are not supported. IMO, they are low priority.

**Comment by HarelM** [comment]
I don't see the overlay, am I missing something?
Also how can I determine from URL that the user provides which type to use - image or tile?

**Comment by jgravois** [comment]
you should only use image if tiles either
1. aren't present
2. were cooked in a different [CRS](https://en.wikipedia.org/wiki/Spatial_reference_system) than the map you want to display.

**Comment by HarelM** [comment]
@jgravois Thanks for the info, but how I can know that given the user only sets a URL?

**Comment by HarelM** [comment]
@jgravois thanks again!!
To reduce complexity and maintenance what is planned for this feature is to use `TileArcGISRest` source without all the capabilities such as features server or different CRS.
If we decide in the future that the extra capabilities have value for our users and that it's worth the effort we will open a separate issue.

**Comment by zstadler** [comment]
For the record, this also fixed the bug reported in #795
