### ISSUE TITLE
All overlays open upon login in beta

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#862]
## What I expect to happen
Only overlays that were open when I last left the site/app to open

## What really happened
All the custom layers opened

## What I did that caused the issue - step by step
Logged in to OSM, returned to site/app.

## My environment
Beta version from December 5th 2018
Chrome on either PC or smartphone and app.
## Thing I think the developers should know, images, links etc.
![image](https://user-images.githubusercontent.com/689201/49503653-a571c880-f880-11e8-80a9-2011074d1f05.png)

**Comment by HarelM** [comment]
This should happen only once. nevertheless, I have updated the code to default all layers to be hidden upon first upgrade to beta.
