### ISSUE TITLE
map rotation also zooms in/out in beta

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#863]
## What I expect to happen
When holding the shift and moving the cursor I expected the zoom to stay constant

## What really happened
Depending on the exact position of the cursor the map also zoomed in or out on top of rotating

We have enough ways to control zoom, and it would make sense to disable the shift-zooming feature to get better control of the map rotation.

**Comment by HarelM** [comment]
Not planning on fixing this as this is how openlayers works - same experience as two fingers mobile pitch.
