### ISSUE TITLE
Allow switching routes by clicking them in view mode

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#864]
## Feature
When the interface is on view mode (pencil tool not selected), clicking on the map is not functional.
It would be useful if clicking on a route would bring it to focus. Would simplify viewing height profiles combining/splitting etc. Currently this requires many clicks through the maps/layers window.

**Comment by HarelM** [comment]
While this is a nice addition, clicking a route is very hard using the mouse and most people wouldn't try it so the UX for this is not great.
See my comments here: #836.
Most people probably use a single route, if they don't they probably have the sidebar open so it's not that may clicks...
Closing... sorry.
