### ISSUE TITLE
Direction arrows obscure track in low zooms. (beta)

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#868]
## Feature
When zooming out from a track the direction arrows jumble up and cover up the track.
Consider reducing their size or hiding them in low zooms. 
![image](https://user-images.githubusercontent.com/689201/49506893-f1743b80-f887-11e8-8cd4-efbf8d5c55b7.png)

**Comment by HarelM** [comment]
I don't see any value in implementing this - Zooming in is something that you would need to do regardless if the direction arrows obscure the route or not...
Besides that, implementation is complex and error prone. I prefer not to do it - please consider closing it.

**Comment by HarelM** [comment]
According to https://github.com/openlayers/openlayers/issues/9065 ant path is possible! :-)
Using this example:
https://codesandbox.io/s/kkqo051ryo

Only simplified - need only one style (just the dash array).
With dash: `[30 10]`, increment 1 rate 40.
