### ISSUE TITLE
The sharing URL for the MTB map shows the Hiking map 

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#87]
To reproduce:
1. Open the map at any location, say [here](http://osm.org.il/IsraelHiking/#/14/32.6642/35.0816?markers=&Route_1=)
2. Change the background map to the "Israel MTB map"
3. Open the "share" dialog
4. Click on the sharing URL
5. The newly opened page does not show the MTB map

**Comment by HarelM** [comment]
True, I'm not sure how to fix it. Do you have a suggestion?

**Comment by zstadler** [comment]
I suggest a background name will be added as another parameter to the URL. For example: 
http://osm.org.il/IsraelHiking/#/14/32.6642/35.0816?map=IHM&markers=&Route_1=
or
http://osm.org.il/IsraelHiking/#/14/32.6642/35.0816?map=MTB&markers=&Route_1=

Alternatively, the background URL can be added, similar to how the OSM iD editor receives the Israel Hiking background URL.

**Comment by HarelM** [comment]
That's a good idea as it won't break current links.

**Comment by HarelM** [comment]
I Used baselayer instead of map in the url.
