### ISSUE TITLE
Printing the map creates a distortion (beta)

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#871]
## What I expect to happen
Printing the map would preserve the x-y ratio

## What really happened
The map was distorted to fit the printed page 

## What I did that caused the issue - step by step
Clicked the print button from the web page
Selected a printer (e.g. PDF)
Set the layout to portrait (it also happens in landscape but is less noticeable)
## My environment
* Operating System and version: win 10
* Web Browser and version: Latest Chrome 

## Thing I think the developers should know, images, links etc.
[Israel Hiking Map.pdf](https://github.com/IsraelHikingMap/Site/files/2648901/Israel.Hiking.Map.pdf)

**Comment by HarelM** [comment]
Please add this to the exiting bug about printing and does this one.

**Comment by valleyofdawn** [comment]
#722 ?

**Comment by HarelM** [comment]
Yes.
