### ISSUE TITLE
No default maps in app beta

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#879]
## What I expect to happen
When I log into the App I expect to see the 3 default maps in the maps and overlays window
## What really happened
The 3 maps are missing. No map is selected for viewing, the map showing is the first on the lisy

## What I did that caused the issue - step by step
As above

## My environment
* Operating System and version: Android 8.00 on SM-G930F
* App beta version 8.068

## Thing I think the developers should know, images, links etc.
![image](https://user-images.githubusercontent.com/689201/49730971-8f01ad80-fc82-11e8-9e8b-66eb7f340d90.png)

**Comment by HarelM** [comment]
This is not relevant only to app, removing app label.
