### ISSUE TITLE
Cannot reroute a complete route.

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#88]
To reproduce:
1. Find an un-routed gpx file or download the GPX file from http://www.shvoongmap.co.il/Default.aspx?track=gezer
2. Upload the track
Notice:
1. The track is not routed
2. Clicking the routing button on and off has no effect on the track

**Comment by zstadler** [comment]
For some tracks, like the above, it looks like routing is executed, but does not always succeed. 
For other tracks, it looks like routing is not executed.

For example, the GPX file below:

<?xml version="1.0" encoding="UTF-8"?>
<gpx xmlns="Amud Anan http://amudanan.co.il/" version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/0 http://www.topografix.com/GPX/1/0/gpx.xsd"><trk><name>Amud Anan</name><trkseg><trkpt lon="35.489743384994" lat="33.049098018452"/><trkpt lon="35.503853791749" lat="33.039426464813"/><trkpt lon="35.507288923421" lat="33.039066547091"/><trkpt lon="35.509176482227" lat="33.040071796596"/><trkpt lon="35.513428149265" lat="33.037482662172"/><trkpt lon="35.513518835014" lat="33.035859483208"/><trkpt lon="35.515274303303" lat="33.035828079888"/><trkpt lon="35.522014306117" lat="33.031726696681"/><trkpt lon="35.522738175136" lat="33.030606819036"/><trkpt lon="35.52484833218" lat="33.03100716562"/><trkpt lon="35.529904271468" lat="33.029064586755"/><trkpt lon="35.530384619024" lat="33.031614981245"/><trkpt lon="35.530161030844" lat="33.029027852128"/><trkpt lon="35.533258887186" lat="33.027333668891"/><trkpt lon="35.534329382991" lat="33.027366913372"/><trkpt lon="35.537374438597" lat="33.023048987842"/><trkpt lon="35.545013718682" lat="33.019530030124"/><trkpt lon="35.547721538885" lat="33.022299681015"/><trkpt lon="35.549307186439" lat="33.025460079143"/><trkpt lon="35.550719223449" lat="33.025248796803"/><trkpt lon="35.552520199335" lat="33.02323313193"/><trkpt lon="35.552177974261" lat="33.020574240018"/><trkpt lon="35.55836604011" lat="33.018338828356"/><trkpt lon="35.561149021756" lat="33.018412063897"/><trkpt lon="35.565184676838" lat="33.015966045334"/><trkpt lon="35.563429558868" lat="33.013338301931"/><trkpt lon="35.565010655862" lat="33.015281299096"/><trkpt lon="35.56909147298" lat="33.016071920838"/><trkpt lon="35.572652316431" lat="33.033382004748"/><trkpt lon="35.571795363624" lat="33.046151734211"/><trkpt lon="35.572480390067" lat="33.046113652306"/><trkpt lon="35.57238961178" lat="33.042299989974"/><trkpt lon="35.585608968068" lat="33.04183658394"/><trkpt lon="35.586689430732" lat="33.041652954842"/><trkpt lon="35.596296533748" lat="33.042624005337"/><trkpt lon="35.600852623558" lat="33.046405521474"/><trkpt lon="35.606128141897" lat="33.048200956111"/><trkpt lon="35.609904510931" lat="33.047557608566"/><trkpt lon="35.61428391865" lat="33.049995764114"/><trkpt lon="35.618833397947" lat="33.052117627411"/><trkpt lon="35.618700453658" lat="33.053452488296"/><trkpt lon="35.625648228518" lat="33.053239904916"/><trkpt lon="35.622048355992" lat="33.066361750909"/><trkpt lon="35.623377252606" lat="33.066582707397"/><trkpt lon="35.629299489906" lat="33.044355446978"/><trkpt lon="35.629382021334" lat="33.043705988438"/><trkpt lon="35.630034895235" lat="33.041440659192"/><trkpt lon="35.627503066208" lat="33.040322214974"/><trkpt lon="35.626342616773" lat="33.039424503513"/><trkpt lon="35.62685594312" lat="33.039314572216"/><trkpt lon="35.630245534659" lat="33.040718632343"/><trkpt lon="35.629985145789" lat="33.039998210708"/><trkpt lon="35.629604410342" lat="33.038737216217"/><trkpt lon="35.631486935246" lat="33.036188178969"/><trkpt lon="35.631317746816" lat="33.027731398036"/><trkpt lon="35.628957245979" lat="33.024313215468"/><trkpt lon="35.628737658831" lat="33.0231598638"/><trkpt lon="35.628742540709" lat="33.019706569531"/><trkpt lon="35.629131846293" lat="33.018307705785"/><trkpt lon="35.630240759597" lat="33.015211307584"/><trkpt lon="35.629132052104" lat="33.013880653493"/><trkpt lon="35.629855979606" lat="33.013084747603"/><trkpt lon="35.651188067014" lat="33.011540627767"/><trkpt lon="35.673585030279" lat="33.025316707766"/><trkpt lon="35.698178477784" lat="32.990121172649"/><trkpt lon="35.702013860607" lat="32.99292809419"/><trkpt lon="35.702094671448" lat="32.99398269051"/><trkpt lon="35.702588165196" lat="32.994215150598"/><trkpt lon="35.703342151432" lat="32.99510476563"/><trkpt lon="35.703285606447" lat="32.996466466229"/><trkpt lon="35.702992748534" lat="32.997666814548"/><trkpt lon="35.703786124571" lat="32.999845612086"/><trkpt lon="35.704697982225" lat="33.000256718576"/><trkpt lon="35.707804796016" lat="33.000902438049"/><trkpt lon="35.713804803109" lat="33.0078297468"/><trkpt lon="35.726504435048" lat="33.010960101514"/><trkpt lon="35.728868252868" lat="33.010742825302"/><trkpt lon="35.731783672842" lat="33.006105162995"/><trkpt lon="35.737837187195" lat="33.003762262446"/><trkpt lon="35.738733332694" lat="33.001531392682"/><trkpt lon="35.741136834698" lat="33.000844864969"/><trkpt lon="35.740447873798" lat="33.000162578845"/><trkpt lon="35.741306130407" lat="33.000528565044"/><trkpt lon="35.741999020541" lat="32.998325593591"/><trkpt lon="35.75049225193" lat="32.990913380605"/><trkpt lon="35.750111520995" lat="32.986415873476"/></trkseg></trk></gpx>

**Comment by HarelM** [comment]
When uploading a track the track is loaded as-is and points are added along the track (around 20 points).
In order to use the routing you'll need to "move" point along the route to force the app to route a segment.
I'm not sure this is a bug.
I can add a toast saying that routing failed if needed, currently if you click F12 you'll see an error message when it does, but this is mainly for my debugging.

**Comment by zstadler** [comment]
I'm not sure I understand your point.

My understanding of our original use cases, is that the origin on the track
(loaded or entered) is orthogonal to its routing mode.

I do not believe that moving points, and therefore modifying the track, is
an appropriate way to get a loaded track routed. I also think that routing
a loaded track is an important feature of the site that can also draw
visitors.

P.S., what is a "toast"!?

**Comment by HarelM** [comment]
Toast is the definition in android for the pop-up messages that fade away. it is also used in web pages.
I see you point. The only option I see to solve this is to add another button that will reroute all points.
but it will completely remove the route you loaded.
Not sure I have a good idea for this.

**Comment by HarelM** [comment]
I'll try and think of a way to allow the user to reroute the entire route/disable routing.

**Comment by HarelM** [comment]
Moved routing per point to advanced settings.

**Comment by valleyofdawn** [comment]
Okay. But please leave it as the default setting.
The scenario for manual section within an auto routed course is much more common and based on several comments in lay forums people can't find this option.
