### ISSUE TITLE
Directional rotation too sensitive

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#881]
## What I expect to happen
The heading should remain relatively stable until a significant turn is mad
## What really happened
The maps rotates continuously creating a distracting user experience

## What I did that caused the issue - step by step
Pressed the north/with direction button
Started moving

## My environment
* Operating System and version: Android 8.00 on SM-G930F
* App beta version 8.068

**Comment by HarelM** [comment]
This is very vague. How do you define a significant turn?
When I tested it on the road while driving it showed similar user experience to Waze when looking at map rotation animation. I had no issues using it when walking - the fact the the map direction is constantly updating creates a nice feeling, in my opinion.

**Comment by valleyofdawn** [comment]
There should be a minimum of say 2 seconds or 10 meters of movement in a direction that is more than 15% off from the previous direction.
Is it filtered at all right now or reacts to each positional reading?

**Comment by HarelM** [comment]
I don't see a good reason to complicate it that much. Currently it is not filtered at all - i.e. changes every second.

**Comment by HarelM** [comment]
I used it now for a short walk, and I now see your point. I'll try a simple 3 points moving average and see if it solves the issue.

**Comment by HarelM** [comment]
Looking at this again, I think the complexity of implementation is not worth the risk - I feel OK with the current user experience. @valleyofdawn can I close this one?

**Comment by valleyofdawn** [comment]
I don't know about the complexity of the implementation.  I've heard from
Keren too that it is problematic. We can ask more users.
Maybe the experience is different for hikers and bikers.
A related issue - the map should stop rotating if it was dragged to a
different location. This indicates the user wants to stabsly examine
another area of the map.

בתאריך יום ו׳, 18 בינו׳ 2019, 17:58, מאת Harel M <notifications@github.com>:

**Comment by HarelM** [comment]
The related issue deserves an issue of its own, please open a separate one.
I don't think asking many users will help in this case. Please try and better define what is a distracting user experience.
About asking someone if the map rotation is distracting: I don't believe someone would answer something other than yes - it's a leading question - facebook users have yet to raise this issue in the other hand.

**Comment by valleyofdawn** [comment]
I'll open a new issue.
Let's wait then and see if the sensitivity thing spontaneously shows up in the beta feedback when we ask for it.

**Comment by HarelM** [comment]
@valleyofdawn can I close this issue? I don't think the complexity is worth the effort, and I feel good with the following experience.

**Comment by HarelM** [comment]
No response. Closing.
