### ISSUE TITLE
Current position marker lags

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#882]
## What I expect to happen
The recorded track should be continuously drawn

## What really happened
The position of the cursor updates every 50 m or so even though the track drown is smooth.
This makes it easy to miss turns and creates a frustrating user experience.
## What I did that caused the issue - step by step
Planned a route and closed the edit mode (not sure if necessary)
Pressed the locate button
Pressed the record button
Started moving

## My environment
* Operating System and version: Android 8.00 on SM-G930F
* App beta version 8.068

**Comment by HarelM** [comment]
Yet another duplicate of #876
