### ISSUE TITLE
Track points are lost when sharing a loaded track

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#89]
To reproduce:
1. Find an un-routed gpx file or download the GPX file from http://www.shvoongmap.co.il/Default.aspx?track=gezer
2. Upload the track
3. click on the share button
4. Click on the share link
Notice:
1. The track point pins are gone, including the start and end icons
2. Clicking the routing button on and off has no effect on the track

**Comment by HarelM** [comment]
Can't reproduce. when I load a file, and click the share link the poi are there and along with the start and end point.
The routing button does not re-route the track it only allows you to choose how to handle current sengment if you move a POI and how to handle newly added points.

**Comment by zstadler** [comment]
Strange...
Did you try it with the file in the issue description?

When I load it in both Firefox and IE, the "Marks=" entry in the URL is
empty, and the marks are gone when it is used.

Here is a screenshot showing the gezer track after loading the GPX file
with marks on it, and no marks in the sharing URL:

[image: Inline image 1]

**Comment by HarelM** [comment]
I couldn't get the site to work, I just loaded a gpx file I had on my PC. can you send it by mail?
The inline image is not shown in Github...

**Comment by HarelM** [comment]
Good spotting, Thanks!
