### ISSUE TITLE
Add a "reverse route" button in route editing menu

### ISSUE THREAD

**Issue by OrBin** [IsraelHikingMap/Site#891]
## Feature
Add a "reverse route" button in route editing menu.

## What I expect to happen
I'd expect to have a "reverse route" button in the editing menu (where the routing type buttons are).

## What really happened
I didn't find such a button. Actually, I wanted to request such a feature or even implement it, but then I've found that there is such a button when you click on the last route point, which is very counterintuitive.

## My environment
* Operating System and version: Linux (KDE Neon 5.14)
* Web Browser and version: Google Chrome 70.0.3538.77 (Official Build) (64-bit)

**Comment by HarelM** [comment]
Latest beta version has this implemented :-)
Hopefully, I'll be able to roll out a public beta and after that deploy this in production.

**Comment by OrBin** [comment]
Nice! Thanks :)

**Comment by HarelM** [comment]
If you are interested in helping out, there's a lot of stuff to do in this project :-)
