### ISSUE TITLE
Cannot add a picture to a POI

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#892]
## What I expect to happen
Attach a photo to a POI

## What really happened
The picture is not added

## What I did that caused the issue - step by step
1. Create a POI
2. Click on the camera icon
3. Add a picture from the gallery or the camera
4. The camera icon is not replaced by the picture

## My environment
* Operating System and version: App
* Web Browser and version: 

## Thing I think the developers should know, images, links etc.
- The issue also applies to public POIs
- The beta version for web browsers is working well

**Comment by HarelM** [comment]
Related to this issue, I believe:
https://github.com/hMatoba/piexifjs/issues/52
Has to do with the location info parsing of the image.
A revert of piexifjs the upgrade is probably the bet bet here...
