### ISSUE TITLE
Change GPS location icon

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#893]
## What I expect to happen
I expect to get an indication of my direction of movement while I record a track in the app

## What really happened
The recorded track ends with a red circle indicating "end of route"

I suggest using an orange arrow (same as active recording line) with a white halo. 
Something along these lines
![arrow](https://user-images.githubusercontent.com/689201/50478144-52e78000-09d8-11e9-85a1-8caa2d4f13c1.png)
Let me know if you need an SVG

**Comment by HarelM** [comment]
Please supply transparent png in the right size.
The definition above does not explain the entire UX - should the crosshairs apper too? What happens when clicking on it - today it allows to add a poi.

**Comment by HarelM** [comment]
I don't think this is a good UX - one of the most common poi editing we are taking about is adding a poi in the current location, making it easy and fast is important IMHO.
I'm not sure what the current icon size is, do whatever looks good for you...
I think the crosshairs is better than arrow head as it doesn't obscure the current location. I tend to think now, after thinking about it some more that this is only relevant when north up is active- in the other xase the map will point up to the route direction, no real need for an arrow...

**Comment by valleyofdawn** [comment]
I tend to disagree. I believe adding a POI would be a relatively rare action. We can snap it to the current location if the POI was clicked close to it. This would be a surprising result of clicking the arrow for most users. 
Having an arrow is an easy cue that your are recording, and having it up is a reminder that the map is not north-up. If it obscures too much we can show the outline only. like so:
![route](https://user-images.githubusercontent.com/689201/50481151-a95cba80-09e8-11e9-9291-ae5b96d4ec59.png)

**Comment by valleyofdawn** [comment]
For future reference, the cross-hairs icon is 78x78 px on my FHD smartphone screen.

**Comment by HarelM** [comment]
This is the current behavior, you can't ignore it since it doesn't suites you.
When suggesting new UX I expect to take into consideration what the user is already familiar with.
I think the transparent arrow head is a good middle ground.

**Comment by valleyofdawn** [comment]
I'd say I'm a pretty active user of the website and I didn't know this behavior. 
Users are more likely to 1) use current position 2) touch the screen with the app than the site.
I feel this would be confusing UI behavior for most of them. 
If it's dear to you than it's not a big issue.

**Comment by zstadler** [comment]
The issue, IMHO, is about showing the movement direction while following the GPS position. It should not matter if track recoding is active or not. This behavior is common in navigation apps such as Maps.me, Oruxmaps, and more. 

I agree that a rotating arrow is very useful. In a simple intuitive way it shows the direction provided by the GPS. Moreover, it is the only way to show the movement direction in North-up mode without recording. 

I agree that the arrow icon should not be filled in order to minimize hiding of the map.

**Comment by valleyofdawn** [comment]
![arrow](https://user-images.githubusercontent.com/689201/50484657-525fe100-09fa-11e9-91ce-5bb829580a71.png)
I think these dimensions should work

**Comment by valleyofdawn** [comment]
So zstadler, are you saying we shouldn't use the cross-hairs at all?

**Comment by HarelM** [comment]
As a side note, we always had GPS direction.
In any case - the bottom line of this feature request is the the GPS icon will rotate according to the direction.
Recording route color is covered in #894.
