### ISSUE TITLE
Improve recording route visibility

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#894]
## What I expect to happen
As a new user navigating with the app I expect to be able to tell what is my recorded track and what is  the route I am following. I expect the latter to be semi-transparent so that it doesn't obscure map features, and directional. 

## What really happened
The recording and followed route have the same appearance and change colors based on usage history.

ZStadler and I I suggest using orange (ff6600ff) solid line for the recording. No ant column. 100% opacity. 25% width. It should appear on top of planned routes.

For a planned route we suggest using a blue (0000FF) line either with an ant column or a series of arrow heads. 50% opacity.

**Comment by valleyofdawn** [comment]
That's a shame. Maybe a periodical arrowhead icon then?
In the meantime, a thick semi-transparent line would do.

**Comment by HarelM** [comment]
I don't see any added value in showing the direction of the route white recording - you are recording - you should know when you are and where you are going.
I'm ignoring this in this feature request. Let's try and keep this issue focused.
Also please remember that this is not going to replace orux.

**Comment by valleyofdawn** [comment]
I agree it's low priority. I think it's useful for orientation when you see just a portion of the planned route and whenever a route crosses over itself.

**Comment by zstadler** [comment]
Knowing the direction of the original route is useful in cases of complex routes and when joining a planned route at some middle point.

There is no value in showing the direction of the active recording.

I agree this is a shame that open layers  does not support such annotation and that this is a low-priority issue.

**Comment by HarelM** [comment]
Planning only to address recorded route in this issue.
Please open a different one for following route, although I have little faith I'll do it since followed route is not well defined and is usually based on a share or an exiting route, which has its color defined by the user and I have little interest in touching it. As far as I see it - following route is just a planned route no need to complicate it. Making it more complex might confuse the user as create an unexpected and bad UX...

**Comment by HarelM** [comment]
Changed to 6 for recording and 7 for default planning.

**Comment by valleyofdawn** [comment]
Thanks,  what was it before?

**Comment by HarelM** [comment]
3 and 4.
