### ISSUE TITLE
Remove precision range circle below a certain threshold

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#897]
## What I expect to happen
When in tracking mode and with a good GPS signal, I don't expect to see the precision range circle

## What really happened
It contracts to a tiny blue dot that is not useful or has a clear purpose, and is somewhat confusing and obstructing. 

I suggest not showing it if the accuracy is better than, say, 20 m.

**Comment by zstadler** [comment]
For me it makes a different at all perecisions

**Comment by HarelM** [comment]
I agree, closing...
