### ISSUE TITLE
Move arrowhead cursor to bottom 3rd position when direction up is switched on

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#898]
## Feature
When it tracking mode and with direction up users are likely to care more about what is ahead than what is behind them.  I suggest that when both north up and the record button are pressed that the arrowhead cursor be moved to the bottom 3rd or 4th position. There should be space enough left for the height graph to show, though.

**Comment by zstadler** [comment]
IMO, button order should be fixed in order to create a consistent user experience

**Comment by HarelM** [comment]
These are the two mapbox threads about this requirement:
https://github.com/mapbox/mapbox-gl-js/issues/1740
https://github.com/mapbox/mapbox-gl-js/issues/4268
There are some solutions there, I don't know which of them will work, all hacks since this is not implemented in mapbox yet.
Since I don't think this is relevant for all users (mainly not for me) I can add a configuration options as part of #1145, but I believe this only progresses us towards a complex and unfriendly app...
Please consider closing this feature request.

**Comment by zstadler** [comment]
Having used today the tilt option of the vector maps while following the GPS, I can see a significant value for this request in this user flow.

**Comment by HarelM** [comment]
I would like to avoid another configuration option.
Do you agree to change the bahavior without the option to turn it off: i.e. When GPS is tracking and following user heading the cursor should be at the bottom part?Assuming I can make it happen code wise.

**Comment by HarelM** [comment]
@valleyofdawn Please try and install the latest version 8.6.19 (or later) and let me know if this does the trick.
Things to test:
1. Regular GPS following
2. GPS following with fixed north up
3. GPS following while standing still
4. Other scenarios you have in mind

I have added an offset of 100 pixels, if you feel it should be lower let me know.

**Comment by HarelM** [comment]
I think this is good enough from the test I made. It has its gliches when returning to center but overall I think it's a nice addition.

**Comment by zstadler** [comment]
The new cursor position is an improvement in course-up follow mode, but there is still a significant part of the screen which hosts the area behind. It is especially evident when using map tilt to get even longer-range view.

I would prefer to see the cursor as low as 100 pixel or so from the bottom of the screen.

I also noticed that moving the cursor to the bottom is useful when the map tilted, **not rotating**, and the view is towards the next section of the planned route.
