### ISSUE TITLE
When recording, add time and speed to the stats

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#899]
## Feature

It would be useful, when recording a track, to also show the time elapsed and the current speed.
As shown below:
![image](https://user-images.githubusercontent.com/689201/50519319-f3b26a00-0ac2-11e9-8836-d3130b81eb02.png)

**Comment by HarelM** [comment]
This makes this panel too crowded.
Can you live without the total elevation and drop while recording? If so I might be able to replace them. But this should be handled as part #854 and taken into consideration.
Please close this one or the other issue as they are on the same subject.
