### ISSUE TITLE
No height statistics for loaded track

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#90]
To reproduce:
1. Find an un-routed gpx file or download the GPX file from http://www.shvoongmap.co.il/Default.aspx?track=gezer
2. Upload the track
Notice
1. The statistics window has no height info: graph, gain, and loss

**Comment by HarelM** [comment]
That's true. My only concern is that getting all this info on loaded tracks might take time and cause the user to wait while the height data is fetched.

**Comment by zstadler** [comment]
Can it be done in the background, after the route is shown on the map?

**Comment by HarelM** [comment]
done in the background.
