### ISSUE TITLE
Height profile text flickers

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#900]
## The text showing the heights in the profile flickers when recording a track.
The rest of the text in the window is stable.

## What I did that caused the issue - step by step
Started recording.
Opened the height profile.
looked at the text.

## My environment
* Android app

**Comment by HarelM** [comment]
I doubt there's something I can do about it, this text is rendered the same as the other texts in this window...
Can you record a video of this happening?

**Comment by valleyofdawn** [comment]
Can't recreate this at home. Will try again in motion.

**Comment by HarelM** [comment]
Any updates on this? Weer you able to reproduce? if not please close this issue.

**Comment by HarelM** [comment]
@valleyofdawn can I close this one?

**Comment by valleyofdawn** [comment]
Yes please

**Comment by valleyofdawn** [comment]
Couldn't recreate bug
