### ISSUE TITLE
Missing tiles while GPS is following

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#903]
## What I expect to happen
I expect all the tiles to be present as soon as the map rotates with the direction of movements

## What really happened
They are often missing (appear white) or taken from the cache at a lower resolution.

## What I did that caused the issue - step by step
Recorded a track on my car with the direction up turned on.

## My environment
Android app version 8.0.116
## Thing I think the developers should know, images, links etc.
It's not a question of tile availability as:
1) cellular data signal was strong
2) manually rotating, dragging or resizing the map resulted in the tiles immediately loading
Perhaps the experience would be smoother if more tiles around the current position are loaded in preparation for movement and rotation.

**Comment by HarelM** [comment]
I have no control over this.
I don't think you would know if mobile data is not storing enough.
Not planning on fixing this as the solution is better offline capabilities.

**Comment by HarelM** [comment]
I think this is related to the following settings:
https://gis.stackexchange.com/questions/147008/allow-new-tiles-to-be-loaded-while-dragging-map/147042

**Comment by HarelM** [comment]
@valleyofdawn please take the latest version (once build finished) and make sure this fixes the issue, I'm 90% sure the change I made will fix it.
