### ISSUE TITLE
Encode slope in route color

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#91]
Very useful when planning a route. No need to look in the height profile.
Used in a few application, but to the best of my knowledge not in websites.
![d7a9d7a7d795d7a4d799d7aa1](https://cloud.githubusercontent.com/assets/689201/9736632/0bbc0e24-564b-11e5-8f64-fb627c91c76e.jpg)

**Comment by HarelM** [comment]
I'm Probably not going to implement it.but it's a nice suggestion.

**Comment by HarelM** [comment]
This will prevent the usage of colors for routes (unless you define it as a toggle button). it also requires to split the path into small segments each with the relevant color - in general very complicated with relatively small value.
