### ISSUE TITLE
Draw mileage markers every n-th KM according to scale

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#910]
## What I expect to happen
When showing mileage markers on a route, they should not overlap. 

## What really happened
Mileage markers are drawn every KM, regardless of map scale. They should be drawn at larger intervals as the users zooms out and at shorter intervals when the user zooms in.

## What I did that caused the issue - step by step
Draw a long route. Turn on mileage markers from the altitude profile window. Zoom out.

## My environment
Chrome, Windows

**Comment by valleyofdawn** [comment]
Totally agree, it makes this useful feature useless (and ugly) in low zooms.

**Comment by valleyofdawn** [comment]
Zoom 0-6: 100 km
Zoom 7-8: 50 km
Zoom 9-10: 10 km
Zoom 11-12: 5 km
Zoom>12: 1km
