### ISSUE TITLE
Improve current location arrowhead behavior at low zoom and high speed

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#911]
## What I expect to happen
I expect the current location arrowhead to move smoothly forward at all situations when tracking 

## What really happened
When using at low zoom at higher speeds (car) it visibly lurches forward intermittently

## What I did that caused the issue - step by step
To achieve the effect in its extreme form:
Zoomed in to 16
Started recording track
Drove car at 100 KMH
Watched the cursor

## My environment
App on Android

## Thing I think the developers should know, images, links etc.
This is a purely aesthetic issue - would give the user a smoother experience.
Maybe sample the position more frequently at the above conditions
Maybe animate the cursor movement between positions.

**Comment by HarelM** [comment]
The sampling is one per second, I don't think it should be higher.
I'll see if I can animate the cursor position movement but I have little faith it's possible.
In case it's not, I'll close this issue as a limitation of the framework.

**Comment by HarelM** [comment]
Might be possible:
https://openlayers.org/en/latest/examples/feature-move-animation.html

**Comment by zstadler** [comment]
The [location update](https://github.com/IsraelHikingMap/Site/blob/1032658b7dd9f9150b2f9fd5002c56d8bad456de/IsraelHiking.Web/sources/application/components/location.component.ts#L274-L276) is using `view.animate` where the default [`easing`](https://openlayers.org/en/latest/apidoc/module-ol_easing.html) is `inAndOut` - "Start slow, speed up, and then slow down again". The default `duration` is 1 second. As a result, GPS position updates are translated to a rhythm of speed-up and slow-down every second.

While the `inAndOut` animation is appropriate for major map updates, such as pan-and-zoom to a POI or a search result, continuous map update based on the GPS updates would probably look better using `linear` easing.

**Comment by HarelM** [comment]
I can't find a good example in the mapbox documentation to understand how to do it, and also I think the current implementation is good enough.
I'm tending towards closing this issue...

**Comment by zstadler** [comment]
We can discuss this when you are available.

**Comment by valleyofdawn** [comment]
low priority. Can be closed.
