### ISSUE TITLE
Point and select a route

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#912]
## Feature

Multiple routes used to be a feature reserved to advanced users.
Now we keep old routes on the screen and they add up quickly.
To remove each of them a user has to go through  5 clicks and look deep in the interface they might not know well.
Specifically, they need to press
1. Layers
2. Private routes
3. Properties
4. Delete
5. Layers
I suggest instead that clicking on a route, when not in editing mode, would select the route for editing and thus allow the user to immediately press the "clear button"

**Comment by HarelM** [comment]
If I understand correctly the purpose of this feature is to be able to delete routes when you have many.
A delete all button was added as part of #888.
Also opening a share will remove all old routes much like it does today. #875.
I still think clicking a route is a bad user experience as I explained many times before.
I see no reason to keep this issue open assuming the above two are implemented.
See how #888 looks:
![image](https://user-images.githubusercontent.com/3269297/50902911-f39c5d80-1424-11e9-86c9-43660cadbcc3.png)

**Comment by valleyofdawn** [comment]
I looked for similar old issues and couldn't find them. Do you remember where you discussed your dislike for clicking routes?
It would serve also quicker manipulation of inverting, cutting ans splicing tracks.
I think the delete all is not as good because it's deep in the interface and adds another button.
You can experiment with a similar interface here:
https://drive.google.com/open?id=1m9dTxKIdp98lrpDlX-kj_fG62Bw&usp=sharing

**Comment by HarelM** [comment]
Layers sidebar is not considered deep in the interface, IMO, and I don't think multiple routes will become heavily uses due to how #875 will work.
On the other hand, the complexity of adding a single click to handle routes along side private poi, public poi, traces, directional search etc, is high and I still don't see the value in adding it - reducing 2 clicks is a very low value in comparison to its complexity.

**Comment by valleyofdawn** [comment]
If by complexity you refer to coding it - then there is nothing I can comment, because I wouldn't know.
If by complexity you mean UX, then I beg to differ.
All the above elements are clickable and the user would come to expect them to be editable upon clicking.
The tracks are not clickable and they thus make an exception that defies the user expectations.
For basic users who only have one route - clicking it won't have any effect anyway.
For users who try to delete, manipulate, compare or combine routes, clicking an inactive one would change  the colors of the tools on the right which would immediately make sense. Users would also benefit from more screen space to work with without the sidebar present.

**Comment by HarelM** [comment]
Coding complexity and how to handle clicks when there are multiple elements in the same place...

**Comment by HarelM** [comment]
I'll see if I can find an easy implementation, otherwise I'll close it again.

**Comment by HarelM** [comment]
Switching between routes does not automatically change the edit mode. I'm keeping this behavior aligned. i.e. when clicking on route in the map and when clicking on it in the layers sidebar the results will be the same.
