### ISSUE TITLE
Save As button is missing in the new 8.0 beta

### ISSUE THREAD

**Issue by davidih** [IsraelHikingMap/Site#915]
## Bug
(Delete the non-relevant)

## My environment
* Operating System and version:
* Web Browser and version:

**Comment by HarelM** [comment]
This is now part of the advanced features - setting advanced will add this button to the main interface.
![image](https://user-images.githubusercontent.com/3269297/51106315-13040380-17f4-11e9-9bd3-2d42f7b7955e.png)

**Comment by davidih** [comment]
Is there a motivation for that? I use to send shared links to non-technical friends who are using the save as button to save it as a GPS route or as twl to use it in their GPS. They are not OSM members and don't understand too much in these issues.
Is it only to save space?

**Comment by HarelM** [comment]
The motivating is to reduce the complexity of the UI.
We have an app nowand the default exported file is a valid GPX file.
Non-technical users can use our app.
If you are using an app that doesn't support this format and you use save-as you are an advanced user by definition.
If your friends doesn't care about OSM this is definitely a nudge in the right direction in my point of view.

**Comment by davidih** [comment]
Thanks Harel. These people use Garmin devices or flight navigation apps. I'm trying to bring them in and convince them to use IHM to plan routes for them and for their friends. 
I understand that you see the picture differently. Anyway, I appreciate the work that is done to improve IHM.

**Comment by HarelM** [comment]
Further discussion can be seen here: #797.
Closing...
