### ISSUE TITLE
Better define the undo behavior

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#922]
## What I expect to happen
1. Be able to add and edit POIs while recording a track, including the ability to undo
2. Avoid accidental removal of recorded track points
3. The "undo" button should not affect the track recording results. Instead, only manual actions should be reverted:
   - POI editing activities
   - Editing of the recorded track after the recording has finished, at least as long as this activity is allowed.

## What really happened
While recording a track, it is possible to add POIs to the track, and it's a good thing.
However, it is practically impossible to use the "undo" button in this scenario. For example, when adding a POI while recording a drive, the point location is incorrect or multiple point were added as a result of a rough road. Clicking the "undo" button removes recorded track points instead of correcting the last POI action. Moreover, a new track point is added to the undo stack every second.

## What I did that caused the issue - step by step
- Start a recording while someone else is driving
- Touch the screen to add a POI
- Press the "undo" button

## My environment
* Operating System and version: mobile app

**Comment by HarelM** [comment]
I think it will be easier just to disable undo while recording.
Skipping undo operations proved to be problematic, I can elaborate on the phone if it interests you.

**Comment by zstadler** [comment]
Users would expect to be able to reliably add POIs and modify them while recording, and this includes the ability to undo a mistake.
I've experienced the need to use undo for POI operations while recording.

**Comment by HarelM** [comment]
As a temporary fix, undo will be disabled when recording.
Keeping this issue open to better define undo behavior in general.

**Comment by HarelM** [comment]
Recording and route editing were split to support this.
