### ISSUE TITLE
תצוגת גרף גבהים של המסלול המתוכנן, בזמן הקלטה

### ISSUE THREAD

**Issue by rnativ** [IsraelHikingMap/Site#923]
## What I expect to happen
אפשרות לראות את גרף הגבהים של המסלול המתוכנן
לדעתי זה מה שמעניין בזמן הניווט

## What really happened
כרגע ניתן להציג את גרף הגבהים המוקלט בלבד

## My environment
* Operating System and version: android

**Comment by valleyofdawn** [comment]
I believe he meant seeing the current location on the planned route.
This is how you know what climbs and descents are ahead.
This may need to await implementing a "follow route" feature down the line.
Or, if you could select the "followed route" while still recording, show the position on the route to which your current position is closest to.

**Comment by HarelM** [comment]
Closing this in favor of #929.
