### ISSUE TITLE
Pinching the map should not drag POIs

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#926]
## What I expect to happen
When I pinched the map while track editing was on  I expected it to zoom in or out.

## What really happened
One of my fingers touched a POI and dragged it, changing the planned track.

## What I did that caused the issue - step by step
1) planned a track
2) kept it at edit mode
3) pinched out the screen with 1 finger touching the route.

## suggestion
If we can detect that the screen is touched in 2 rather than 1 point, POI dragging should be inactivated.

## My environment
app/mobile site

**Comment by HarelM** [comment]
I don't have a good idea how to solve this.
Opened a question/feature request in OL repository:
https://github.com/openlayers/openlayers/issues/9138
