### ISSUE TITLE
Cannot activate expert mode on Firefox 56.0.2

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#927]
## What really happened
Clicking the "expert mode" checkbox in the beta site has no effect: the checkbos remains unchecked and the expert capabilities are unavailable.

## What I did that caused the issue - step by step
- login
- click the "expert mode" checkbox

## My environment
* Operating System and version: Win 10 home
* Web Browser and version: Firefox 56.0.2 (64-bit)

## Thing I think the developers should know, images, links etc.
- I've tried:
   - logging out and in
   - Ctrl-F5 refresh
- No errors on the developers console
- Things work fine on Chrome

**Comment by HarelM** [comment]
Seems like a different behavior between FF and Chrome.
Nice catch!
https://stackoverflow.com/questions/31092439/click-on-checkbox-inside-a-button-element-firefox-issue
Worth checking all the menus that are in the app - mainly the share menus on public POI and shares dialog.
