### ISSUE TITLE
Height profile below sea level

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#93]
Uses zero as baseline. Looks funny.

**Comment by HarelM** [comment]
This isn't really telling me what's wrong you know... Please elaborate/send a link/upload a picture.

**Comment by valleyofdawn** [comment]
OK, look at the height profile of [this.]
(http://osm.org.il/Israel%20Hiking/index.html#/15/32.7059/35.6267?baselayer=Israel_Hiking_Map&markers=&Route_0=h,32.6911,35.5324;h,32.6891,35.5947;h,32.7091,35.6450)

**Comment by HarelM** [comment]
Let me know if you find a property here that you think will do it:
https://developers.google.com/chart/interactive/docs/gallery/areachart?hl=en
I'm not sure it's possible...

**Comment by valleyofdawn** [comment]
Sorry, couldn't. It's no big deal anyway.

**Comment by HarelM** [comment]
Neither could I...

**Comment by zstadler** [comment]
Setting the areaOpacity to 0 perhaps?

**Comment by HarelM** [comment]
This will just cause the background to disappear - which will make the area chart a line chart, and I do like the area style...
