### ISSUE TITLE
Increase radius for POI merge

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#930]
## What I expect to happen
Enable additional merges between POIs of different sources

## What really happened
Location accuracy in some sources is low and POI merge is not performed as a result of a large distance from the OSM location.

## What I did that caused the issue - step by step
See [עין מודע](https://israelhiking.osm.org.il/share/VK5RZUIGtA)

**Comment by HarelM** [comment]
I think the data should be updated and not the code in this case, if the distance tolerance is too large we might end up merging things that should not be merged...
I've update the tolerance one from 100 to 200 meter, but I don't feel comfortable raising it more...

**Comment by zstadler** [comment]
As we see in several examples other sites' inaccuracy is way more than 200 meters. 
The difference for עין מודע above is almost 500 meters. OSM POIs imported from "GEOnet" had an initial accuracy of "minutes" at the time. (One minute of latitude is 1 nautical mile - almost 2 Km)

I cannot think of any example of POIs with same name and type that are less than 1 Km away that should *not* get merged. Most likely, the same also holds for a 10 Km radius.

Nevertheless, we always take the OSM location which is where the POI would show on the map, so the inaccuracy of the 3rd part's location is of no concern.

**Comment by HarelM** [comment]
I have changed the configuration to use 1/60 (1 minute) threshold.
I currently can't think of a reason why this threshold is problematic, but let's see how it changes the results (I might be wrong but I have a hunch there can be issues with larger threshold which I had when implementing this and can't remember now...).
In any case, this can be changed in the configuration file of the site and not only in the code using `mergePointsOfInterestThreshold` key and the value is in lat-lon delta (and not in meters).
