### ISSUE TITLE
Photos in POIs not properly oriented

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#932]
## What I expect to happen
When I take a picture for a private POI I expect it to appear properly oriented

## What really happened
They appear up-side-down or sideways, depending on how I took the picture

## What I did that caused the issue - step by step
Manually added a POI.
Took a picture
Approved it
Looked at the orientation

## My environment
App on android
## Thing I think the developers should know, images, links etc.

![image](https://user-images.githubusercontent.com/689201/51632009-eae47500-1f56-11e9-90fd-9f66125d54bf.png)

**Comment by HarelM** [comment]
I'm unable to reproduce it on my device.
Also, I did not change the code that resize and rotates the image.
Please see if this happens also in mobile site, both beta and non beta.
Chances are that your picture has an incorrect orientation value.

**Comment by valleyofdawn** [comment]
It doesn't happen on the mobile site.
The images have the correct orientation when viewed in the gallery.
Samsung note 9.

**Comment by HarelM** [comment]
Can you try and see if you can open the site with the phone's default browser (probably Samsung internet) and see if this issue happens there?
I have no clue what can cause this, maybe I can create a debug version for you to test it with. I'll see what I can do...

**Comment by valleyofdawn** [comment]
Looks OK in the default browser as well.

**Comment by HarelM** [comment]
@valleyofdawn please try and install the version that will be created in the following build:
https://ci.appveyor.com/project/IsraelHikingHost/site/builds/21870824/job/23bnsfda4u9miqa0
It should popup messages when importing the image to private POI.
The most important message is the "orientation before ...", let me know once you test it what are the popup saying.

**Comment by valleyofdawn** [comment]
Orientation before undefined

**Comment by HarelM** [comment]
Is this the only message you are getting? Should be around 3...
Also, if this is the case, no wonder the site doesn't change orientation.
Can you I'll upload the image to this thread as well?

**Comment by valleyofdawn** [comment]
1 resizing image and fixing orientation
2 uploading image
3 Orientation before undefined
![img_20190205_233435](https://user-images.githubusercontent.com/689201/52307401-31988d00-29a3-11e9-8ecd-ed1054263897.jpg)

**Comment by valleyofdawn** [comment]
Interestingly, when shown on google photos it is correctly oriented. unlike above.

**Comment by HarelM** [comment]
Seems like the image above has no orientation data and no location data, but it might be the way github works.
Can you send me a mail with the original image?

**Comment by HarelM** [comment]
OK, I'm able to reproduce the issue with the above image using my android app (doesn't reproduce on my desktop though).
There's also a strange behavior that the camera icon is begin pressed when adding a private POI, I'll look into it as well...

**Comment by HarelM** [comment]
I have opened a separate bug related to camera icon behavior in the dialog: #956

**Comment by HarelM** [comment]
I have no clue what to do here...
The info is there, I'm just not getting it when the code runs inside the cordova app...
https://github.com/hMatoba/piexifjs/issues/60
I hope @hMatoba might be able to help...

**Comment by HarelM** [comment]
I have also tried using another exif library: `exif-js` but I get the same results - when using desktop version the file has all the relevant data and when using the same library in cordova app, there's no data returned from the image...
This is very strange... Not sure what to do here...

**Comment by zstadler** [comment]
According to #238, the issue applies to public POIs too

**Comment by HarelM** [comment]
It seems that this issue is related to the camera plugin used by the app to get photos from the photos library.
The relevant issue is this one:
https://github.com/apache/cordova-plugin-camera/issues/329
Although seems to be closed I still see the issue occur when using the version from the repository and not from npm.
Fortunately, exif data is not so important when selecting an image for private or public POI and the above issue has allowed me to find a workaround :-)
