### ISSUE TITLE
Assiciate `kmz` files with the app

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#934]
## What I expect to happen
The app to be listed for opening `kmz` files

## What really happened
`kmz` files can be opened from within the app. Trying to open a `kmz` file from a directory or another app fails.

## What I did that caused the issue - step by step
Click on a `kmz` file from a file explorer, mail, or Dropbox

**Comment by zstadler** [comment]
https://stackoverflow.com/a/39316622

**Comment by zstadler** [comment]
Resolved by d8194e8d49fa5cddb309d56d0aed163843f80b45

**Comment by zstadler** [comment]
Examples for use in testing:

http://www.gpsvisualizer.com/download/convert/20190124140754-52095-data.gpx

http://www.gpsvisualizer.com/display/20190124140456-52095-map.kml

http://www.gpsvisualizer.com/display/20190124140109-52095-map.kmz

**Comment by HarelM** [comment]
Resolved by PR #937.
