### ISSUE TITLE
Overlay transparency slider fails in beta site

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#935]
## What I expect to happen
Transparency slider should work for custom overlays

## What really happened
1) sliding screws up the window
2) It doesn't change the transparency value
3) it turns off the overlay

## My environment
Web site on chrome

**Comment by HarelM** [comment]
Screwing the window exists also in non-beta site... :-(

**Comment by HarelM** [comment]
Also not related the recent fix (ESRI) as far as I can tell - it is related to click propagation that causes a click on the row which changes the visibility.
Propagation is an easy fix, not sure what to do with the slider though...

**Comment by valleyofdawn** [comment]
Maybe a vertical slider?

**Comment by HarelM** [comment]
Related to this issue which is still not solved:
https://github.com/angular/material2/issues/6959

**Comment by HarelM** [comment]
I'll see if it's possible to use the vertical one on the left side of the map.
