### ISSUE TITLE
No cursor while GPS is active

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#939]
## What I expect to happen
Show cursor at current position when the GPS is active, whether recording or not. 

## What really happened
The cursor is not showing 

## What I did that caused the issue - step by step
Click on the "show position" button 

## My environment
App build IHM_signed_8.0.177.apk

## Thing I think the developers should know, images, links etc.

![screenshot_20190126-094606](https://user-images.githubusercontent.com/1304610/51784357-19797000-2150-11e9-93c2-74adaee5dc8e.png)

**Comment by HarelM** [comment]
I have verified this is caused by the changes made in #860 by installing the versions around that change and making sure the bug does not exist before the change and exists after the change.
Related to zIndex changes.
