### ISSUE TITLE
Site UI has changed to English

### ISSUE THREAD

**Issue by arieltolkachov** [IsraelHikingMap/Site#940]
## What I expect to happen
The UI of the site is expected to be in Hebrew, same as it was prior to the last deployment on Jan 26th

## What really happened
Site UI is in English

## What I did that caused the issue - step by step
Nothing. Appeared itself after site deployment on Jan 26th. Just to be on the safe side I made sure that Hebrew is chosen in the language menu (see screenshot attached). It had no effect. 

## My environment
* Operating System and version:
MacOS 10.14.3
* Web Browser and version:
Safari 12.0.3 and Chrome 71

## Thing I think the developers should know, images, links etc.
![image](https://user-images.githubusercontent.com/384229/51797595-04174b00-220f-11e9-9c40-abba76b3beb5.png)

**Comment by HarelM** [comment]
This is alarming.
Does changing to English and later to Hebrew helps?
Does browsing to the following site helps?
http://israelhiking.osm.org.il/?nocache=1
Can you try it on chrome with incognito mode?
I don't have a mac so I'm having a hard time investigating this issue...

**Comment by arieltolkachov** [comment]
Sure thing. I'm closing the ticket now. 
Of course I can help out with web debugging on MacOS / iOS as needed. Just ping me upon need. I have both Mac and iPhone I can help with.
