### ISSUE TITLE
Missing map tiles for some ESRI sources

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#942]
## Performance and Reliability

The current support for ESRI map sources uses OpenLayers' [`TileLayer`](https://openlayers.org/en/latest/apidoc/module-ol_layer_Tile-TileLayer.html) with a [`TileArcGISRest`](https://openlayers.org/en/latest/apidoc/module-ol_source_TileArcGISRest.html) source that uses the ESRI `export` API. 

This approach enables simple client-side implementation and support of ESRI sources using CRSes other than Web-Mercator such as the New Israeli Grid. 
On the other hand, for some ESRI sources, the transition from the Leaflet infrastructure introduced occurrences of missing map tiles. 

The goal of this issue is to discuss the options to improve the support for ESRI sources while considering reliable communication, performance, and coding complexity.

@jgravois, your view and thoughts would be greatly appreciated!

#### Aspect 1: OpenLayers' `TileLayer` vs. `ImageLayer`
In [a comment on issue #860](https://github.com/IsraelHikingMap/Site/issues/860#issuecomment-456387348) I wrote:

> In the above example, the base map is an ImageLayer and the overlay is a TileLayer. TileLayers have better performance and would be preferred.

The better performance was expected from requesting smaller images from the server, reducing the communication bandwidth to contain missing tiles only, and improving throughput by performing multiple tile downloads in parallel.

Indeed, #860 was implemented using TileLayer. It turns out that some ESRI Map servers perform unreliably with TileLayer. For example, having blank tiles when using `https://gis.shual.org.il/arcgis/rest/services/MAPS/Orto2015v1/MapServer`: 

![image](https://user-images.githubusercontent.com/1304610/51798595-c1a93a80-221d-11e9-9482-1a0e236b6254.png)

For comparison, there were no such issues with this source in the earlier Leaflet infrastructure of the site. That infrastructure downloaded the entire canvas, the equivalent of `ImageLayer`, using a single `export` API request.

Note: Both site versions were used with a 100 Gbps broadband connection.

#### Aspect 2: ESRI export API vs tile access

In [another comment](https://github.com/IsraelHikingMap/Site/issues/860#issuecomment-456953116) @jgravois wrote:

> you should only use image if tiles either
> 1. aren't present
> 2. were cooked in a different [CRS](https://en.wikipedia.org/wiki/Spatial_reference_system) than the map you want to display.

Initially, I thought this comment also refers to the "OpenLayers' `TileLayer` vs. `ImageLayer`" aspect.
I now believe it actually refers to the map download the MapServer - using tiles with  `MapServer/tile/{z}/{y}/{x}` URLs vs. the use of the `export` API.

If this new understanding is correct, the current implementation does not follow the above recommendation. By always using the `export` API, the client side has simpler client-side code that avoids the evaluation of the two conditions on the server capabilities. AFAIK, similar code to is not available as part of OpenLayers' ESRI support.

@jgravois, I wonder what are the drawbacks of using the `export` API that lead to your recommendation and if it has anything to do with the missing tiles.

#### 1. Retry after download failures
The client could be enhanced to identify image download failures and retry.
- Failed download should also be identified in case of zero response size and a 200 HTTP response code:
   ![image](https://user-images.githubusercontent.com/1304610/51799191-464c8680-2227-11e9-8ca0-094434eb3d34.png)
- Such retry mechanism may also be useful for non-ESRI sources in slow and unreliable network connection

#### 2. Use `ImageArcGISRest` sources
It seems like this source type will restore the client-server communication as was with Leaflet. 
- The drawbacks are not well understood.
- The expected performance degradation is currently only theoretical.

## What I did that caused the issue - step by step
- Add `https://gis.shual.org.il/arcgis/rest/services/MAPS/Orto2015v1/MapServer` as a new base layer.
- Zoom to level 16.
- Switch to a different base map and return to this base map. 
   - This will avoid the use of cached tiles from lower zoom levels.
- Pan the map several times by small amounts.

## My environment
* Operating System and version: Win 10 Home
* Web Browser and version: Firefox and Chrome
* Land-based broadband internet connection

**Comment by jgravois** [comment]
> I wonder what are the drawbacks of using the `export` API that lead to your recommendation and if it has anything to do with the missing tiles.

the drawback of using export is that asking the server to generate a (possibly reprojected) image on the fly takes a lot longer than fetching tiles from a cache.

missing tiles are evidence that something is wrong with the published service.

**Comment by HarelM** [comment]
@zstadler any reason to keep this issue open?

**Comment by zstadler** [comment]
I was unable to reproduce the issue in the beta site. 
Closing
