### ISSUE TITLE
Site is not working as expected on iOS

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#943]
## What I expect to happen
Site should load with route

## What really happened
Site doesn't load at all

## What I did that caused the issue - step by step
Share a route with a link
Open link on a mobile device

## My environment
* Operating System and version:
iPhone and apparently Android devices as well

* Web Browser and version:
Safari and Chrome

## Thing I think the developers should know, images, links etc.
This link, for example, doesn't load from mobile: https://israelhiking.osm.org.il/share/QxVAZ2xaCE

**Comment by HarelM** [comment]
I have used the above share on my android device and was able to see the route (ניסיון).
@zstadler @valleyofdawn can you test this as well?
I don't have an iPhone to debug this though...
Is there an error message appearing or just the loading screen is not replaced by the site itself?
Better if you share a screenshot or short video.

**Comment by oriori** [comment]
The loading screen is not replaced by the site itself.
I was reported the problem by two other Android users who were unable to open a link I sent them.

**Comment by HarelM** [comment]
Is the link you send them is the link above?
The only way to debug what happens is to connect the android device to the PC and open chrome inspect and look at the error message.
I doubt most people would be able to do it so I'll need a way to reproduce it on my device...

**Comment by HarelM** [comment]
@oriori 
Please see if the following helps:
1. navigate to https://israelhiking.osm.org.il/
2. click refresh
3. click on the share that doesn't work.

I see some issues with the browser's cache in some cases that might explain this, maybe...

**Comment by oriori** [comment]
I tried to follow your recommendations but now (first time I tried since
the new version) the site fails to load at all on my iphone. Both safari
and chrome. Tried to reload. Tried in private/incognito mode. It’s always
the same. The site keeps loading and nothing happens. On  safari I get a
message “this webpage was reloaded because a problem occurred”.

**Comment by oriori** [comment]
Correction: the two android users I mentioned before are actually iphone
users. Sorry for the confusion.
So: on Android everything is ok, on iPhones the site doesn’t load.

**Comment by zstadler** [comment]
This is in line with my experiments:
- iPhone: Safari
- iPad: Safari, Chrome, and Chrome incognito

**Comment by HarelM** [comment]
@arieltolkachov can you validate this report? any chance you can remote connect to chrome and write here the relevant browser error message?

**Comment by HarelM** [comment]
I'll try to follow these instruction and see if I can manage to debug my iPad using Windows...
https://washamdev.com/debug-a-website-in-ios-safari-on-windows/

**Comment by HarelM** [comment]
I've created the following site to allow sourcemap etc.
https://israelhiking.osm.org.il/debug/
If anyone can plug an iPhone or iPad to a Mac and use developer tools to see the console it would help a lot.
I was not able to make my MacOS virtual machine recognize my iPad nor able to use the above link to connect to it... :-((

**Comment by arieltolkachov** [comment]
OKay I was able to connect my iPhone to a debugger through MacOS. Opening the regular home page (http://israelhiking.osm.org.il) shows no errors, it is just stuck on line (see screenshot attached). 

<img width="1552" alt="screen shot 2019-01-27 at 22 28 32" src="https://user-images.githubusercontent.com/384229/51806552-c4d71180-2283-11e9-87ea-5a5412fe6415.png">

Trying to open http://israelhiking.osm.org.il/debug crashes my MacOS Safari debugger, not sure how you managed to do that (-: 

If you want to run a screen sharing session ping me directly and I will give you my direct phone number / Skype ID.

**Comment by HarelM** [comment]
I'm now able to debug my iPad using chrome on windows and safari on the iPad.
I also see that it gets stuck in the initialization without any error, I have no clue why.
I'll create a version with a lot of logs and publish it to see what I get.
If this doesn't help I'll rollback to previous version and setup a debug session with you to see how to solve this.
Thanks for the willingness to help out!

**Comment by HarelM** [comment]
Related issue:
https://github.com/pouchdb-community/worker-pouch/issues/53
A possible workaround would be to disable this on iOS,,,

**Comment by HarelM** [comment]
I have made a commit to a fix for the hand problem but now I see that all the icons for single POIs are missing from the map (not the buttons).
Need further investigation, meanwhile, I have reverted to the previous version.

**Comment by HarelM** [comment]
Yet another issue with the profile menu described here:
https://github.com/angular/material2/issues/11677
https://github.com/angular/material2/issues/13130
https://github.com/angular/material2/issues/11366
I'll try the suggested workarounds.
