### ISSUE TITLE
Add a "remove all routes" button/option

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#944]
Feature

## What I expect to happen
A new instance of the website should start clean. Since it keeps the routes from the previous instance, the user should be given the option to "clean" all the data. Otherwise the user has to manually remove all the loaded data., This is especially annoying when there are more multiple routes loaded.

The remove all the data option should be easily accessible (ie, one click). However, care should be taken to prevent cases where users accidentally erase all the data. If after opening a new window, the first action of the user is to to erase everything, the data should be erased without asking the user for a confirmation. Otherwise user should be asked again before erasing everything.

**Comment by HarelM** [comment]
When there are more than 3 routes a delete all routes button will appear.
See issue #888.
Also when opening a share the routes are cleaned as well.
