### ISSUE TITLE
Optimize energy management

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#947]
## Feature
If and when we differentiate the app and site then a top priority for the app is energy management.
This topic is uninteresting to hikers and 4x4 drivers but is absolutely critical to mountain bikers – which seem to be our largest section of users.
There is no way riders will use the app if they lose the battery after 3 hours of use or if they constantly have to fiddle with the power key and lock screen while riding.
I suggest a “save energy” item in the setting under the profile – it will sample the GPS less frequently, allow only off-line maps and, most importantly, darken the screen to its faintest after 30 seconds of inactivity (until touched again).

**Comment by HarelM** [comment]
This might be required for this:
https://github.com/mgcrea/cordova-plugin-brightness
Having said that, It's extremely difficult to optimize the energy management from a cordova app...

**Comment by valleyofdawn** [comment]
> Having said that, It's extremely difficult to optimize the energy management from a cordova app...

"Extremely difficult" is a fit challenge for a developer known to do the impossible

**Comment by HarelM** [comment]
With the relevant time and relevant resources everything is possible :-)

**Comment by HarelM** [comment]
Also this article that uses state management for idle checking:
https://itnext.io/inactivity-auto-logout-w-angular-and-ngrx-3bcb2fd7983f
And these two libraries that require maintainers:
https://www.npmjs.com/package/angular-user-idle
https://www.npmjs.com/package/bn-ng-idle
https://www.npmjs.com/package/@ng-idle/core

**Comment by HarelM** [comment]
I'm not planning on implementing everything described in the begging as part of this feature as I don't fully agree with the requirements. I'm planning on implementing only the screen darkening part.

**Comment by HarelM** [comment]
The only one that truely worked from the above was `ng-idle`.

**Comment by HarelM** [comment]
@valleyofdawn I need you to thoroughly test this. I'm not sure the screen is dark enough although I set the value to 0.01 when it should be between 0 and 1 so I'm not sure I can decrease it.
timeout is 30 sec by using "advanced" options and "battery optimization".

**Comment by valleyofdawn** [comment]
The overall functionality is good. Thank you for addressing this fast.
The screen is definitely dark enough. Not even visible in direct sunlight.

## Bug
When leaving the app for more than 30 seconds, the auto dim stops working.

## Steps to see the bug:
1) Open the IHM app
2) Turn the battery optimization on
3) Move to another app, without closing IHM
4) Spend more than 30 seconds with IHM in the background
5) Move back to IHM and wait 30 sec
6) The screen won't dim.

When you close the app and relaunch it the dimming behavior goes back to normal

**Comment by HarelM** [comment]
Can you experiment with it a bit and see if this is the only case it fails? If I leave the app for less than 30 seconds it works as expected?

**Comment by valleyofdawn** [comment]
I'll experiment further.
If I leave the app for 15 seconds and return, it dims after 15 seconds.

**Comment by valleyofdawn** [comment]
The feature seems stable within the app no matter what you through at it.
When leaving the app (also by simply turning the screen off) for more than 30 secs it stops working.

**Comment by HarelM** [comment]
@valleyofdawn I think I was able to reproduce the issue, and after the fix I added I was not able to reproduce it, so let me know if this fixes it.

**Comment by valleyofdawn** [comment]
I thought you solved the problem, but with longer periods in the background it is still there.
Sorry. 
Try turning the screen off for 2 minutes and see if dimming still works.

**Comment by HarelM** [comment]
This is not working as expected on iOS: When placing IHM in the background and returning to it the device is dimmed.
 Reopening... :-/

**Comment by HarelM** [comment]
Current workaround will be to disable this feature on iOS until I get a better understanding of the root cause and debug process.
