### ISSUE TITLE
Hebrew strings not loaded

### ISSUE THREAD

**Issue by amiad** [IsraelHikingMap/Site#953]
## Bug/Feature
Since last update Hebrew strings not loaded and all the site is in English.

## What I expect to happen
I Want to see Hebrew in the site.

## What really happened
All the site is in English.

## My environment
* Operating System and version: Arch Linux
* Web Browser and version: Firefox 66.0b4 (64-bit)

**Comment by HarelM** [comment]
This is due to browser caching.
You can click shift+F5 to do a hard refresh.
Nevertheless, I'll keep this issue in order to fix this once and for all.
