### ISSUE TITLE
Unable to load GPX file

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#957]
## What I expect to happen
The file should open

## What really happened
It fails to open

## What I did that caused the issue - step by step
Open the following file:
[2340gps.gpx.txt](https://github.com/IsraelHikingMap/Site/files/2835329/2340gps.gpx.txt)

## My environment
* Operating System and version: Win 7
* Web Browser and version: Chrome

## Thing I think the developers should know, images, links etc.
Might be related to a recent fix...

**Comment by airbreather** [comment]
I can confirm that this file is unreadable using NetTopologySuite.IO.GPX 0.3.2 and readable as of 0.4.0 when setting the [new reader flag](https://nettopologysuite.github.io/NetTopologySuite.IO.GPX/api/NetTopologySuite.IO.GpxReaderSettings.html#NetTopologySuite_IO_GpxReaderSettings_IgnoreBadDateTime) to `true`.
