### ISSUE TITLE
Unable to open share that doesn't contain routes

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#958]
## What I expect to happen
Share should open

## What really happened
Error when opening the share

## What I did that caused the issue - step by step
Open the following share:
https://israelhiking.osm.org.il/share/FiIdS778Yp

## My environment
* Operating System and version:
* Web Browser and version:

## Thing I think the developers should know, images, links etc.
Related to a fix made for #955

**Comment by zstadler** [comment]
The https://israelhiking.osm.org.il/share/IlnqaCb4tm share includes an overlay and a new base map.
When opening the share, in the app or a browser, the IHM overlay is not activated.

**Comment by HarelM** [comment]
I don't see how this is related to this issue.
Can you please open a separate issue with all the relevant info (what you described above is probably enough).
