### ISSUE TITLE
לא ניתן לשמור קובץ שהועלה לאפליקציה ושהתקבל במייל או בקישור

### ISSUE THREAD

**Issue by zoharw** [IsraelHikingMap/Site#959]
:מעביר את הבעיה שהעלתי בפייסבוק לפה
הכנתי מסלול על המחשב (ווידוס 10+כרום) ודרך שיתוף את הקישור שלחתי לטלפון  , פתחתי באפליקציה וכשניסיתי לשמור כקובץ או שמור בשם ... קבלתי הודעה "לא ניתן לשמור את הקובץ..." , ניסיתי במצב עריכה (ה"עיפרון" פעיל) וגם במצב שהעריכה סגורה. 
במחשב הוא נישמר.
פתחתי בכרום שבטלפון את האתר (לא באפליקציה) העלתי את הקובץ וכאן כן ניתן היה לשמור כקובץ בכל תצורה.
ניסיתי גם בטלפון סלולרי אחר ואותה בעיה
הקישור שיתוף שנשלח הוא
 https://israelhiking.osm.org.il/share/llAV82g0J7 

זו תמונת ההודעה שלא ניתן לשמור 
![default](https://user-images.githubusercontent.com/47401290/52375585-b3062300-2a68-11e9-9eec-28354070940b.jpg)
 בברכה
זהר ויסברג

**Comment by HarelM** [comment]
מה בדיוק הפעולות שאתה עושה?
אני עשיתי את הפעולות הבאות:
1. לחצתי על הקישור הנ"ל
2. הטלפון שאל אותי אם לפתוח בעזרת האפליקציה או כרום.
3. בחרתי באפליקציה וחיכיתי לסיום הטעינה
4. לחצתי על שמירה וזה אמר שזה נשמר בהצלחה.

**Comment by zstadler** [comment]
האם במקרה העברת את האפליקציה ממקום ההתקנה המקורי לכרטיס הזכרון שהוספת למכשיר

הדבר אפשרי בחלק מגרסאות האנדרואיד

**Comment by zoharw** [comment]
קבלתי קישור בווטסאפ
תמונה 1
כשלחצתי עליו נשאלתי איך לפתוח תמונה 2
לחצתי על האפליקציה ונפתחה תמונה 3
לחתי על השמירה , הדיסק, וקבלתי שלא ניתן ... תמונה 4


בתאריך יום ה׳, 7 בפבר׳ 2019, 10:08, מאת Harel M <notifications@github.com>:

**Comment by zoharw** [comment]
לא העברתי,  האפליקציה נמצאת בזכרון הפנימי בטלפון

בתאריך יום ה׳, 7 בפבר׳ 2019, 11:30, מאת zstadler <notifications@github.com>:

**Comment by HarelM** [comment]
תודה רבה על הרספונסיביות!
אם אני שאלח לך אפליקציה עם הודאת שגיאה יותר מפורטת יש סיכוי שתתקין אותה?
אני מצטער שאין לי רעיון יותר טוב כרגע, אבל אני לא מצליח לשחזר את זה על המכשיר שלי...

**Comment by zoharw** [comment]
כן, אנסה קודם בטלפון המישני
   ב  ב  ר  כ  ה
זהר          ויסברג
Zohar Wissberg
  0545609760


‫בתאריך יום ה׳, 7 בפבר׳ 2019 ב-12:04 מאת ‪Harel M‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by zoharw** [comment]
הראל
נראה לי שעליתי על הבעיה
נזכרתי שלפני כשנה וחצי עשיתם עידכון וקישורים לא נפתחו לי ואז עליתי שיש איזה
שינוי בכיתוב
כנראה שקישורים שנעשו לפני העידכון האחרון מהשבוע שעשיתם לא מצליח לשמור,
בדקתי כמה.
ולעומת זאת קישורים חדשים של מסלולים חדשים  אפשר :) גם ניסיתי כמה ונשמרו
אבדוק שוב כשאחזור בערב ואם תהיה שוב בעיה הודיע.
   ב  ב  ר  כ  ה
זהר          ויסברג
Zohar Wissberg
  0545609760


‫בתאריך יום ה׳, 7 בפבר׳ 2019 ב-12:44 מאת ‪zohar wissberg‬‏ <‪
zowi.zohar@gmail.com‬‏>:‬

**Comment by HarelM** [comment]
נשמע מוזר מה שאתה מתאר.
בעיקרון, אם קישור נפתח אז אתה אמור להיות מסוגל לשמור אותו לקובץ.
בכל מקרה אם יש לך קישור שלא נפתח נשמח לדעת, אולי יש דרך לסדר את זה.
אני אנסה ליצור גרסת בדיקות מתאימה ולשלוח אליה קישור כאן בימים הקרובים.

**Comment by zoharw** [comment]
1.הבוקר בדקתי את שני הקישורים הבעיתיים עם חבר , אצלו נשמר ואז חקדתי שישלח
אלי את הקישור , פתחתי והצלחתי לשמור כקובץ, כך שהבעיה כנראה אצלי בשני
הטלפונים שלי .

2. לגבי הכתובות של הקישור אשלח יותר מאוחר.
3. בכל מקרה תודה  וסליחה על ההטרדה, מצטער.

בתאריך יום ה׳, 7 בפבר׳ 2019, 19:03, מאת Harel M <notifications@github.com>:

**Comment by HarelM** [comment]
שמחנו לעזור.
האם ניתן לסגור את הקריאה?

**Comment by zoharw** [comment]
כן, כי פרט לשני הקישורים הר"מ שעדיין אינני יכול לשמור כקובץ השאר בסדר
https://israelhiking.osm.org.il/share/gGUVz7C1ID

https://israelhiking.osm.org.il/share/ctaollcI9Y
תודה
בתאריך יום ו׳, 8 בפבר׳ 2019, 21:39, מאת Harel M <notifications@github.com>:

**Comment by HarelM** [comment]
מצויין! אני מצליח לשחזר את הבעיה מתוך אחד הקישורים הנ"ל.
הסיבה לבעיה היא ששם המסלול מכיל אותיות שאינן תקינות לשם של קובץ, ולכן לא ניתן לשמור באפליקציה, אך ניתן לשמור באתר.
תודה רבה על כל המידע!
נעלה תיקון לבעיה בימים הקרובים...
