### ISSUE TITLE
Opened share is zoomed-out w.r.t. the shared map

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#961]
## What I expect to happen
Zoom level to be maintained when opening a share

## What really happened
Opened share is zoomed-out w.r.t. the shared map. There is an additional zoom-out with each subsequent share update.

## What I did that caused the issue - step by step
- Create a share
- Click on the resulting link. The share will be opened in a new tab and zoom-out.
- Update the current share without changing anything
- Click on the resulting link. The share will be opened in a new tab and zoom-out again.
- Repeat as needed

## My environment
* Operating System and version: Win 10 Home
* Web Browser and version: Chrome, Firefox

## Thing I think the developers should know, images, links etc.
Initial share:

![image](https://user-images.githubusercontent.com/1304610/52400586-373bc300-2ac8-11e9-8fc4-2b89fb739af5.png)

Map zooms-out when share is opened:

![image](https://user-images.githubusercontent.com/1304610/52400652-68b48e80-2ac8-11e9-95ed-62aef52b48e0.png)

Notice the "10 km" scale vs. the original "5 km" scale

**Comment by HarelM** [comment]
I've seen this yesterday too, it is related to the fit function of openlayers, not sure I want to reverse engineer it...
The bounding envelope is stored in the share and the following is what is used to fit the screen:
https://github.com/IsraelHikingMap/Site/blob/870acec7ae3248efea6bde3e1896a4954268f8ca/IsraelHiking.Web/sources/application/services/fit-bounds.service.ts#L18

It might be that the padding is not needed in this case, maybe a flag in this case can fix this.
If not, I'm not sure it's worth the needed hack..

**Comment by HarelM** [comment]
The fix is a bit hacking but this seems like the easiest way.
@zstadler keep in mind that different screen sizes will behave differently - the share is keeping the bounding box of the current screen (in terms of lat-lon), not the center and the zoom so you might get a different zoom level when using a device with a different screen size - I believe the current implementation is the right approach.
