### ISSUE TITLE
Add info about build number

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#962]
## What I expect to happen
A user ability to provide the unique build id can facilitate clearer issue reporting.
This could be the provided by Appveyor (preferred), or the Git hash (less...)

I suggest this info will be shown in small font at the bottom of the "about" pane.

**Comment by zstadler** [comment]
According to [AppVeyor documentation](https://www.appveyor.com/docs/environment-variables/), the  `APPVEYOR_BUILD_VERSION` environment variable hold the required info at build time.

**Comment by HarelM** [comment]
The app had this built in in the android system. The site is almost always using the latest version. I'm not sure this is needed...

**Comment by zstadler** [comment]
Accessing the build info on the android system is complex for the majority of users.

@HarelM,
This proposal is intended to assist you in the maintenance work. If it will not help you, then please feel free to close this issue.

**Comment by HarelM** [comment]
In most cases this is not an interesting info.
Nevertheless, there should be a way for a user to report a problem so that I'll be able to understand what happened or at least get an initial idea.
@zstadler 
I'll close this one in favor of #963, feel free to add your suggestions there.

**Comment by zstadler** [comment]
@HarelM, I trust you to include in #963 all the information you'll fine useful.
