### ISSUE TITLE
All routes and POI are opened by default in shares 

### ISSUE THREAD

**Issue by davidih** [IsraelHikingMap/Site#967]
## Bug
(Delete the non-relevant)

## What I expect to happen
When I share a map with my own info, I don't want to see other POI and routes, 

## What really happened
When I open any share route or map, all the default poi and routes are enabled by default even if they were disabled when I created the share. It wasn't like that in the previous versions. It is very annoying since it clutters the whole view. 

## What I did that caused the issue - step by step
Open a new incognito browser.
Open any share.
All the default poi and routes are enabled and cover the whole map.

## My environment
*Windows 10:
* Web Browser and version: Chrome, Edge

**Comment by HarelM** [comment]
Public pois and routes are not part of the share, they never were.
We have changed the default to show them, but users who turn them of will not see them when seeing a share they receive.
I don't see a good reason to change this default as we what users to know public poi exist.

**Comment by davidih** [comment]
I think it's a  wrong UX decision. The whole idea of sharing is that I want the other user to get exactly what I have. If I wanted him to see other information I would add it to the share. We should assume that the other user is not an expert and now when I want to share him what I have, he gets a cluttered screen which doesn't resemble what I wanted him to have. I think you should fix it and go back to the original behavior.

**Comment by HarelM** [comment]
You are entitled to your opinion. One of the things we wish to improve is the data related to public pois which is lacking.
The fact that we used to hide it is one of the  main reasons, IMHO.
This is a fundamental part of this app. Since I know you are using it for different purpose I can't fully take into consideration your biased opinion...

**Comment by davidih** [comment]
I'm not sure I'm biased. I appreciate the hard work that you are doing and I understand that it was not originally meant for flying but I use it also for other purposes, for example, when I share a bike route, I don't want to see other info that I didn't share. The right UX solution IMHO is to share the exact situation including the whole settings. This way, you can show the POIs by default but share only what you want to share. I'm sure that as with the Save As button, other users will also complain about this behavior.

**Comment by HarelM** [comment]
There's a thumbs up feature here at Github, if others users will find it useful they are free to +1 this request.
I see you're point, but I don't fully agree with it, there are some things that are not part of the share as they are considered part of the user preferences, such as the UI language and advanced mode.
If you plan to follow a bike route it will benefit you in most cases to know if there's an interesting location near by that's worth going to.
Sharing is mostly about the route and the map.
I'll keep this issue open to see if anyone else is interested in it.

**Comment by zstadler** [comment]
I've added a thumbs-up.

Adding POIs to a share is a change from the original WYSIWYG intention of creating shares. This intention is behind adding visible overlays to the share and excluding hidden overlays and routes from it.

Here is an example of the visual difference between the intention and the result:

| ![image](https://user-images.githubusercontent.com/1304610/52535888-7d10b980-2d5c-11e9-826c-bcb4480b53ed.png) | ![image](https://user-images.githubusercontent.com/1304610/52535904-a7fb0d80-2d5c-11e9-9436-3057d188f5b3.png) |
|:-:|:-:|
| View of shared map | View of received map |

This may also be problematic for 3rd parties that may want to use embedded maps. The additional layers could show items of their competition. 

**Theoretically**, if Nakeb and iNature were in competition, then a Nakeb share would show an iNature icon:

![image](https://user-images.githubusercontent.com/1304610/52535685-1f7b6d80-2d5a-11e9-83c7-c6c15b33c1cf.png)

Some of the options to resolve this issue are:

1. POI and trails icons would not be visible when opening a share. This is essentially restoring the old behavior.
2. Add the visibility of POI and trail layers to the share information, and add them to the WISIWYG approach.
   - Not showing these layers will be the default for old shares
