### ISSUE TITLE
logout button is redundant

### ISSUE THREAD

**Issue by Shemesh** [IsraelHikingMap/Site#969]
once logged in there is no need for the "logout" button, as it exist in the user menu.

**Comment by HarelM** [comment]
I strongly disagree. If I'm using a friend computer or internet-cafe, I would like to be able to logout.
The reason for being two buttons is mainly for UI concerns.
See here (last three comments):
https://github.com/IsraelHikingMap/Site/issues/797

**Comment by HarelM** [comment]
Closing, If there's something needed to add here, please feel free to write here and I'll reopen.
