### ISSUE TITLE
Support vector tiles

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#971]
## Feature
Support vector maps as will be provided by https://github.com/IsraelHikingMap/Map/issues/93

## Thing I think the developers should know, images, links etc.
The current approach to vector maps is based on the [OpenMapTiles](https://github.com/openmaptiles/openmaptiles) approach and includes the use of Mapbox styles for the Hiking and Biking maps.

The [ol-mapbox-style](/openlayers/ol-mapbox-style) repository adds the ability to use Mapbox Style objects with OpenLayers.  It has [several examples](https://unpkg.com/ol-mapbox-style@3.7.1/dist/index.html), including [this demo](https://unpkg.com/ol-mapbox-style@3.7.1/dist/tilejson-vectortile.html) that can show RTL text, such as "גבעתיים" and the nearby "נחל איילון".

**Comment by HarelM** [comment]
To reduce the need for a beta site and to facilitate for easy viewing I have used the following stackblitz:
https://stackblitz.com/edit/angular-openlayers-mapbox
@valleyofdawn @zstadler let me know here if you see any issues there/missing icons/formats/fonts and I'll update the code there.

**Comment by valleyofdawn** [comment]
Focusing on the Canada Park area (15/31.85/35), these are the different products  I see:
![image](https://user-images.githubusercontent.com/689201/52909420-c8612580-3290-11e9-8311-fd2b21a4ada4.png)
vs.
![image](https://user-images.githubusercontent.com/689201/52909450-3dccf600-3291-11e9-8127-6f0d71549239.png)

**Comment by valleyofdawn** [comment]
The main difference:
Better: Hebrew is aligned RTL
Worse:
No hill shading
No contours
No icons for POIs amenities and peaks
No patterns (e.g. orchards)
No background color
No dashed pattern of tracks
Font difference (the one on  Stackblitz  looks like frank Ruhl

**Comment by HarelM** [comment]
Thanks! Can you add the relevant styling code that is used for things that are different?

**Comment by valleyofdawn** [comment]
I believe it is not using the data sources described in the metadata of il-MTB.json
Sprites refers to the icons and patterns
Glyphs refers to the fonts used:

    "hillshading": {
      "type": "raster",
      "url": "https://klokantech.tilehosting.com/data/hillshades.json?key=tXme5cuqgrCqdPoZHqyn",
      "tileSize": 256
    },
    "contours": {
      "type": "vector",
      "url": "https://klokantech.tilehosting.com/data/contours.json?key=tXme5cuqgrCqdPoZHqyn"
    }
  },
  "sprite": "https://raw.githubusercontent.com/IsraelHikingMap/VectorMap/master/Icons/publish/sprite",
  "glyphs": "https://orangemug.github.io/font-glyphs/glyphs/{fontstack}/{range}.pbf",

**Comment by zstadler** [comment]
In order to add contours and hill-shading, the `map.layers` array should be constructed from the members of the style's `sources`.
The `url` of each source is a link to a TileJSON file that would be opened using `ol/format/TopoJSON`

The TileJSON includes the vector tiles source, the `sprite` (icons), and the `glyph` (font).

**Comment by HarelM** [comment]
I can't use the file that contains everything and just apply it due to the fact that the tiles are served over http and not https.
Is there a way to fix that using a proxy in the styles and server json file?
Here's what I use for the tiles address, but it would make things a lot easier if I could just use the entire file instead of decomposing it.
`https://cors-anywhere.herokuapp.com/http://31.154.215.180:8080/data/v3/{z}/{x}/{y}.pbf`

**Comment by HarelM** [comment]
@zstadler @valleyofdawn I have updated the code in stackblitz to show hill shading and contours, icon, patterns and fonts, please take a look at it.
Seems there's a problem with the contours I do not fully understand, I suggest to use simpler rules right now, to see that it works, if it does then complicate the rules as I can't think of why it wouldn't work right now...
Seems like the style of the hill shading will not apply without serving everything in https. I currently need to deconstruct the style json file and build the layers myself which is what is causing this.

Besides the contours and hill shading please let me know what doesn't work and add a snippet of the relevant code in the style file.

**Comment by HarelM** [comment]
Layers order should be as follows:
1. areas without water
2. hill shading
3. contours
4. water and other lines and points
There's might be a conflict with how vector tiles work in openlayers though.

**Comment by valleyofdawn** [comment]
In the latest version of the demo (18.2) several issues were addressed.
Remaining issues:
Contours do not appear.
Hillshading is above water.
No dashed pattern of tracks: 
    {
      "id": "road_track-cladding",
      "type": "line",
      "source": "IHM",
      "source-layer": "transportation",
      "minzoom": 14,
      "maxzoom": 24,
      "filter": [
        "all",
        ["==", "$type", "LineString"],
        ["==", "class", "track"]
      ],
      "layout": {
        "line-cap": "square",
        "line-join": "bevel",
        "visibility": "visible"
      },
      "paint": {
        "line-color": "rgba(0, 0, 9, 1)",
        **"line-dasharray": [1, 1],**
        "line-width": {"base": 1.55, "stops": [[7, 1], [20, 30]]}
      }

Font difference (the one on Stackblitz looks like frank Ruhl instead of "Open Sans Light" and "Open Sans Bold" used throughout the style.

**Comment by HarelM** [comment]
@valleyofdawn I see two track styling in the provided json file:
```json
{
      "id": "road_track-cladding",
      "type": "line",
      "source": "IHM",
      "source-layer": "transportation",
      "minzoom": 14,
      "maxzoom": 24,
      "filter": [
        "all",
        ["==", "$type", "LineString"],
        ["==", "class", "track"]
      ],
      "layout": {
        "line-cap": "square",
        "line-join": "bevel",
        "visibility": "visible"
      },
      "paint": {
        "line-color": "rgba(0, 0, 9, 1)",
        "line-dasharray": [1, 1],
        "line-width": {"base": 1.55, "stops": [[7, 1], [20, 30]]}
      }
    },
    {
      "id": "road_track",
      "type": "line",
      "source": "IHM",
      "source-layer": "transportation",
      "minzoom": 12,
      "maxzoom": 24,
      "filter": [
        "all",
        ["==", "$type", "LineString"],
        ["==", "class", "track"]
      ],
      "layout": {
        "line-cap": "round",
        "line-join": "bevel",
        "visibility": "visible"
      },
      "paint": {
        "line-color": "rgba(245, 245, 248, 1)",
        "line-dasharray": [1000],
        "line-width": {"base": 1.55, "stops": [[7, 0.5], [20, 15]]}
      }
    },
```
It might be that their order is causing one to disappear beneath the other.
Can you check what happens if you only use one of them?

> The name tags do not appear under POIs and cover the icons in peaks.

Can you attach the relevant example from the json file?

**Comment by HarelM** [comment]
The text translate doesn't seem to be supported yet which might explain the issue with the text and icon:
https://github.com/openlayers/ol-mapbox-style/issues/134

**Comment by valleyofdawn** [comment]
Regarding the double This was done to achieve this appearance of the track. It's a white narrow line on top of a wider dashed black line.
![image](https://user-images.githubusercontent.com/689201/52949102-0428e780-3384-11e9-96a4-2880bb05cfb2.png)

**Comment by valleyofdawn** [comment]
Should I, in the mean time' move the icon up instead of the text down?
It is not ideal as people expect the icon, not the text, to mark the exact location.

**Comment by HarelM** [comment]
> Should I, in the mean time, move the icon up instead of the text down?

I would advise to wait a bit and see if this can be resolved in the translator.

> Regarding the double track definition...

I know what you would like to achieve, but I want to see what are the limitations of the translator - so let's try and use a dashed black line to make sure it works (without the white one), afterwards we'll try and make it more complex.

**Comment by valleyofdawn** [comment]
I want to see what are the limitations of the translator - so let's try and use a dashed black line to make sure it works (without the white one), afterwards we'll try and make it more complex.

I turned the inner white line invisible. Does the renderer support 
      "layout": {
        "visibility": "invisible"

**Comment by zstadler** [comment]
FYI, in the hiking map, each side will have a separate dashed line, since each side can have a different color.
https://github.com/IsraelHikingMap/VectorMap/blob/master/Styles/IHM.json#L86-L121

**Comment by HarelM** [comment]
@valleyofdawn see the comment in https://github.com/openlayers/ol-mapbox-style/issues/134
You can use [text-offset](https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-text-offset)

**Comment by HarelM** [comment]
@valleyofdawn `"line-dasharray": [1, 1],` doesn't work - please use `"line-dasharray": [1, 2],` instead.
So the only problem left to solve is the incorrect font for the text?

**Comment by HarelM** [comment]
The following address has a local version of the style file under `gl-stlye.ts` that can be changed and viewed on-the-fly:
https://stackblitz.com/edit/angular-openlayers-mapbox-local

**Comment by valleyofdawn** [comment]
Long names along roads get jumbled.
![image](https://user-images.githubusercontent.com/689201/53170553-12c40880-35e9-11e9-8e2b-1f112ff31f38.png)
Should be "שביל הגורל השביעי"

**Comment by HarelM** [comment]
@valleyofdawn can you test if this also happens in English?

**Comment by valleyofdawn** [comment]
No, it's fine in English.

**Comment by valleyofdawn** [comment]
> @valleyofdawn can you test if this also happens in English?

It also happens at low zooms but not high ones.

**Comment by valleyofdawn** [comment]
Background color is not shown. Remains bright white (see comparison screenshots above).

**Comment by HarelM** [comment]
@valleyofdawn which BG color? please elaborate.
@zstadler in continue to our converstation the following package might be useful:
https://github.com/twitchax/AspNetCore.Proxy
I can add it to the configuration file in order to facilitate for multiple addresses.

**Comment by valleyofdawn** [comment]
The style specifies a background color for areas of the map without any land use or natural land cover.
In the il-mtb style it should be light gray, not white as seen in the open layers implementation.

**Comment by HarelM** [comment]
Added the following example that uses files that are temporary on the site server to make sure everything works as expected:
https://stackblitz.com/edit/angular-openlayers-mapbox-https
As can be seen, background exists, which is not surprising since the background code is missing from the other examples.

**Comment by HarelM** [comment]
@valleyofdawn @zstadler 
Latest changes were made to: https://stackblitz.com/edit/angular-openlayers-mapbox only (...-local was not updated yet, let me know if this is still needed).
It includes: 
1. Fix to background
2. Updated tiles address
3. Added Open Sans font
4. Added rotate using shift key

As far as I know the only open issue is with long text following a line in hebrew, right?

**Comment by HarelM** [comment]
I have updated https://stackblitz.com/edit/angular-openlayers-mapbox-local with recent changes in order to be able to show mtb_scale - it seems to work as expected.

**Comment by valleyofdawn** [comment]
Elimination of overlap
Using the Mapbox renderer overlapping icons and labels culled. Not so in the openlayers renderer.
Look for example at the area surrounding the holy sepulcher in Jerusalem.
![image](https://user-images.githubusercontent.com/689201/54052343-d26da880-41ec-11e9-8e76-64ccca415427.png)
![image](https://user-images.githubusercontent.com/689201/54052534-48720f80-41ed-11e9-9774-bf603f723634.png)

**Comment by HarelM** [comment]
I have added `declutter: true` and it seems that it works well as far as I see - you can see how it looks at the regular address:
https://stackblitz.com/edit/angular-openlayers-mapbox

I have opened an issue for openlayers regarding the text following a line, let's see what they answer.
https://github.com/openlayers/openlayers/issues/9309

**Comment by HarelM** [comment]
Implementation of #988 allows the usage of ol-mapbox-style in the site. Let's discuss our next steps regarding vector tiles in our next meeting.

**Comment by valleyofdawn** [comment]
"text-max-angle": 0 didn't make ant difference in the appearance in StackBlitz

**Comment by valleyofdawn** [comment]
Supporting halo for icons.
The MapBox style JSON contains fields for icon halos but it is not implemented by either of the renderers.
Let's try to render the halos on our implementation, like it does for text.
If it doesn't work I'll go back and add them manually to the icons.

"paint": {
"icon-color": "rgba(20, 19, 19, 1)",
"icon-opacity": 1,
"icon-halo-color": "rgba(253, 249, 249, 0)",
"icon-halo-width": 3,

**Comment by HarelM** [comment]
@valleyofdawn I don't understand your last comment regarding icon halos. If this doesn't work with either renderer let's add them to the icon itself, I don't have a way to render halos in the site implementation on stackblitz as far as I know - see documentation [here](https://openlayers.org/en/latest/apidoc/module-ol_style_Icon-Icon.html).

I have updated the stackblitz with the new layer separation to show the following layers order:
1. Areas without water (Areas-IHM source)
2. Hill shading
3. Contours
4. Water and other lines and points (Features-IHM source)

**Comment by valleyofdawn** [comment]
OK. I'll add the halos to the icons manually. The layering looks good.

**Comment by valleyofdawn** [comment]
Halos added

**Comment by valleyofdawn** [comment]
Openlayers 5 supports both MaxAngle and placement:
https://openlayers.org/en/latest/apidoc/module-ol_style_Text.html

**Comment by HarelM** [comment]
I have implemented max-angle in the conversion tool, waiting for them to create a new version with my code.

**Comment by HarelM** [comment]
The following is a mapbox stackblitz to compare performance:
There might be a need to migrate to mapbox in order to support this as it seems that openlayers is working slow on mobile devices.
https://stackblitz.com/edit/ngx-mapbox-gl-imtb

**Comment by HarelM** [comment]
Mapbox seems to have issues with CORS on images (?!) the following might be needed:
https://blog.thunderstrucksolutions.se/asp-net-core-2-0-mvc-cors-and-static-files/

**Comment by HarelM** [comment]
This is no longer relevant due to #997.
