### ISSUE TITLE
Improve performance of share ownership check when update a share

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#972]
## What I expect to happen
update existing link option to be given

## What really happened
The checkbox with the option to share the route under the same link isn't there

## What I did that caused the issue - step by step
Load a shared route from your library
Share the route by clicking the share button

## My environment
* Operating System and version: Win 10
* Web Browser and version: Chrome

**Comment by HarelM** [comment]
How did you load the route? using the  + or the eye button?
Using the + would only add the route to your private routes while using the eye would open the share for editing and re-sharing.
You can also simply click the share button in the shares menu if the only thing you want to do is get the share address.

**Comment by oriori** [comment]
With the eye button. I want to update the route, not just share it again.

**Comment by oriori** [comment]
correction: The option to update the route is there. It just takes a long
time for it to appear.

**Comment by HarelM** [comment]
This is in order to make sure you are the owner of the share.
Can I close this?

**Comment by oriori** [comment]
It takes 5-10 seconds for the option box to appear. This another example of the sluggishness of the new version. In the old version, the option box appeared almost immediately. If the sluggishness of the new version is not a bug, then close this.

**Comment by zstadler** [comment]
@HarelM, Perhaps the ownership can be verified when the share is opened rather than when an update is requested? This way, the user would not experience a delay.

**Comment by HarelM** [comment]
@oriori thanks for the info, probably related to how many shares you have - I don't have a lot so I'm not experiencing this delay.
@zstadler sure, the ownership check can be simplified - instead of doing a round trip to the server just verify the user id of the share matches the current user id.
Bottom line, I'll improve the performance.
