### ISSUE TITLE
Changing the type of a waypoint in a route changes the type of the following segment as well

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#973]
## What I expect to happen
when moving or adding a point to a route, the selected routing type (walking/cycling/driving/straight line) should be applied only to the segment ending in the point (between the point and the previous one). 

## What really happened
The routing type is also applied to the segment between the point and the next one.

## What I did that caused the issue - step by step
Create a route.
Add two points in cycling mode.
Add a new point along the route in between the two existing points in straight line mode.

## My environment
* Operating System and version: Win 10 
* Web Browser and version: Chrome

## Thing I think the developers should know, images, links etc.
Only in the new version

**Comment by HarelM** [comment]
Solution should take into consideration the following issue as well: #976
