### ISSUE TITLE
Background map for OSM editing doesn't transfer correctly from IHM

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#974]
## What I expect to happen
When I use the Strava heat map as a base map and hit "edit OSM map", I expect it to appear as the background of the iD editor.
https://israelhiking.osm.org.il/share/qYhPNr5cWR

## What really happened
The background in iD is jumbled because 512x512 tiles are used instead of 256.
This is because instead of the tile address:
https://heatmap-external-a.strava.com/tiles-auth/ride/red/{z}/{x}/{y}.png?px=256
it uses the address:
https://heatmap-external-a.strava.com/tiles-auth/ride/red/{z}/{x}/{y}.pngpx=256
missing the "?"
It can be corrected manually and then shows up correctly.
Strava data is a very useful, and legal, source for editing OSM.

**Comment by HarelM** [comment]
I don't have a strava user so I'll have a hard time testing this.
Does the following works for you:
https://www.openstreetmap.org/edit#background=custom:https%3A%2F%2Fheatmap-external-a.strava.com%2Ftiles-auth%2Fride%2Fred%2F%7Bz%7D%2F%7Bx%7D%2F%7By%7D.png%3Fpx%3D256&map=14/29.753016936503556/34.94226035437011

In the above address - the strava address is encoded to remove problematic characters such as "?".
If this doesn't work please open a bug in iD as I have no clue how to solve this according to what they expect to receive...

**Comment by valleyofdawn** [comment]
It works. The "?" was transferred and the background looks good.
