### ISSUE TITLE
"Eretz Ha-Maayanot" site is down

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#983]
## Bug
Springs linked to hamaayanot.co.il return a 503 error.
I suspect the site has been closed.
Perhaps we should remove them temporarily until we know for sure.
e.g.
https://israelhiking.osm.org.il/poi/OSM/node_1295048583?language=he
which is linked to 
http://www.hamaayanot.co.il/home/index.php?page=4&mayan=49736

**Comment by zstadler** [comment]
In this example, the link is taken directly from the `website` tag. OSM may have other broken links.

I'm not sure what you are suggesting.

**Comment by valleyofdawn** [comment]
Wasn't it us who added those links automatically via scraping?

**Comment by HarelM** [comment]
I'll remove the file from the server. When updating an OSM element that is linked the values are saved in the OSM element, which is what probably happened in this case. Invalid links should be removed from OSM like other invalid data.

**Comment by valleyofdawn** [comment]
Wasn't it us who added those links automatically via scraping?

**Comment by HarelM** [comment]
Yes. But it was not added to osm database, only to our site unless a user edited the entry on the site which causes a merge and stores the metered entity to OSM.

**Comment by HarelM** [comment]
Removed, will not be available tomorrow.
