### ISSUE TITLE
Better merger of Wikipedia and OSM place names

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#987]
## Feature

Wikipedia articles about places with names that also have a common meaning end with an explanation in parentheses. 
Thus the wiki equivalent of the OSM "פטיש" is "(פטיש (מושב", OSM's "חולדה" is Wiki's "(חולדה (קיבוץ"
Other such suffixes are: יישוב, יישוב קהילתי, עיר, היאחזות נח"ל
The result is failure of tens of places in Israel to merge resulting in "2" symbols instead of place icons in the relevant overlay.
I suggest the algorithm identifies such cases and merges them
![image](https://user-images.githubusercontent.com/689201/53723080-985c7980-3e6f-11e9-9e00-a2caa34467cd.png)

**Comment by HarelM** [comment]
I find it very calming to merge them manually :-) takes only a few clicks.
I'll take a look at it never-the-less...

**Comment by HarelM** [comment]
Looking back at this, I think we should run a script to find those places, and add the relevant data to OSM once instead of running this algorithm every time we rebuild the POIs database.
Adding this logic to the algorithm will only make it run slower, those places do not tend to appear rapidly...

**Comment by zstadler** [comment]
IMHO, there is no need for a script. The script cannot make automatic updates, therefore it is just a way to find problematic places

Anyone can search for a candidate text, such as "(מושב)", that is not expected in an OSM name, find the problematic Wikipedia entries, and add them to OSM.

I've used this approach in [changeset 69703343](https://www.openstreetmap.org/changeset/69703343).

**Comment by HarelM** [comment]
I think we agree, I'm referring to a one time script that can semi-manually fix there entries places - finding those places can probably be done using turbo overpass turbo and fixing them is a matter of 1 hour max, IMHO.
Can I close tis issue then?

As a side note, in case this interest you, the site is adding two Wikipedia tags: wiki=he:place and wiki:he=place as there's no official version I could find to tell me which is the correct one and this way feels that it properly supports multilingual...

**Comment by zstadler** [comment]
@HarelM [wrote](https://github.com/IsraelHikingMap/Site/issues/987#issuecomment-487667010):
> As a side note, in case this interest you, the site is adding two Wikipedia tags: wiki=he:place and wiki:he=place as there's no official version I could find to tell me which is the correct one and this way feels that it properly supports multilingual...

The [wiki page](https://wiki.openstreetmap.org/wiki/Key:wikipedia#Secondary_languages) is quite clear, at least in my eyes

> **In almost all cases, a single wikipedia tag as described above is sufficient.** Data users can access articles in other languages where available using Wikipedia's interlanguage links. If interlanguage links are missing, this should usually be fixed within wikipedia. 

For rare cases where secondary languages are required, and it lists a few examples, it says
> In these circumstances use the format _`wikipedia:lang=page title`_ for the secondary languages. 

From the above it seems clear that the The `wikipedia:lang` tag should be used only for the additional "secondary" languages and only in the rare situations that justify their addition.

**Comment by HarelM** [comment]
While you are allowed to change your opinion, you wrote something else here: #616.
I followed your advise (or what I understood for it) while implementing and I see no reason to open this discussion again, I'm sorry I did.
In any case, this does not answer my question: "Can I close this issue then?"
I believe this issue can be manually solved in less time it will take to code or discuss it.

**Comment by zstadler** [comment]
The OSM-Wikipedia merge ignores Wikipedia tags on `place` polygons.
For example, the polygon for [ברק](https://www.openstreetmap.org/way/617494236) has a `place=village` tag and a `wikipedia` tag
![image](https://user-images.githubusercontent.com/1304610/56955145-39eb0900-6b49-11e9-90f3-45bd65b46428.png)

The polygon is shown on the map as part of the search results, as well as a separate Wikipedia POI:

![image](https://user-images.githubusercontent.com/1304610/56954829-7e29d980-6b48-11e9-9f2b-41cc87c76156.png)

As for `wikipedia` tags for secondary languages, I have misunderstood the OSM documentation when I wrote my comment in #616.

**Comment by zstadler** [comment]
This issue is not about handling of Wikipedia URLs entered as "Website" when editing a public POI.

The aspect of _writing_ `wikipedia*` tags is relevant here only in the sense that it is expected to be compatible with the reading of such tags as part of the merge of Wikipedia and OSM places.

**Comment by HarelM** [comment]
There's a deeper problem which I have no intention on opening here about place nodes and place polygons in OSM.
IHM currently updates and gets its information from the place node and not from the place polygon (assuming both exist) - meaning the polygon is only used to present the shape and its tags are ignored.
If you think there's an issue related to this please open a separate issue.
Again this is not related to this issue.
> P.S., I have misunderstood the OSM documentation when I wrote my comment in #616.

I have understood it the way you did back then, and I still think it's the right solution, again, not related to this issue too.
Closing this issue as this discussion is it constantly derailing.

**Comment by zstadler** [comment]
I agree about **current** priorities. 
I agree to disagree on the required functionality.

**Comment by zstadler** [comment]
I do not want to re-open this issue. Yet, for the record, OSMOSE flags the use of `wikipedia=he:*` and `wikipedia:he=*` as duplicate tagging.

![image](https://user-images.githubusercontent.com/1304610/88103269-715c3000-cba9-11ea-80a1-3d6cc013c1a2.png)

For the above example open [this link](http://osmose.openstreetmap.fr/en/map/#zoom=14&lat=31.35502&lon=35.30894&item=xxxx&level=1%2C2%2C3&tags=wikipedia&fixable=) and click on the green marker.

OSMOSE suggested fix is to remove the `wikipedia:he=*` tag
<img width="632" alt="2020-07-21 23_33_18-Osmose - Map" src="https://user-images.githubusercontent.com/1304610/88104192-c3ea1c00-cbaa-11ea-81f9-3452811320e0.png">
