### ISSUE TITLE
Return the option to see cumulative gain/loss for parts of the route

### ISSUE THREAD

**Issue by ATGardner** [IsraelHikingMap/Site#989]
## What I expect to happen
The previous elevation chart displayed the cumulative gain/loss of the marked route. Clicking and dragging the mouse pointer over it would select part of that route, and display those statistics (along with the total distance) to this partial route. It was very handy, IMHO.

## What really happened
The new elevation chart displays the statistics on a different panel, so it's not visible when selecting a section of the route.

## My environment
* Operating System and version:
* Web Browser and version:

**Comment by ATGardner** [comment]
I just noticed that if I select a section of the trail, then switch over to the statistics table, I see the statistics for my current selection. So I guess that solves my issue. Sorry.

**Comment by HarelM** [comment]
This is an awkward experience, also when returning to the graph the selection is lost but it is still selected if going back to the stats.
I'll think of a way to properly solve this.
Thanks for reporting this issue.

**Comment by ATGardner** [comment]
Maybe just displaying some floating popover statistics (gain/loss/distance) when hovering over a selected section?

**Comment by HarelM** [comment]
Proposed solution: no hover when dragging, and the stats are presented below the chart, allowing the user to clear them:
![image](https://user-images.githubusercontent.com/3269297/54568086-a4ebe080-49de-11e9-8ef4-715ff81cac97.png)
