### ISSUE TITLE
Coordinates for POIs

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#99]
Could be useful if clicking on a POI would show you its coordinates  in the Israel grid.

**Comment by HarelM** [comment]
This is a relatively simple calculation. where would you position this data?

**Comment by valleyofdawn** [comment]
When you click on a POI, in the test box.

**Comment by HarelM** [comment]
Need to convert the following code to JS/C#:
https://github.com/IsraelHikingMap/Map/blob/master/Scripts/Maperipy/CreateITMGridOsm.py
