### ISSUE TITLE
add stats - average speed in last km & average moving speed

### ISSUE THREAD

**Issue by amiad** [IsraelHikingMap/Site#993]
## Feature
<div dir="rtl">
כדאי להוסיף לסטטיסטיקות מהירות ממוצעת בקילומטר האחרון (או מרחק קצר אחר) ומהירות ממוצעת בתנועה.

מהירות ממוצעת למרחק קצר נותנת מושג יותר מדויק על מהירות התנועה מאשר נתון המהירות הרגעי שמשתנה כל כמה שניות.

מהירות ממוצעת בתנועה מתעלמת מההפסקות שפחות רלוונטיות למהירות. באפליקציות אחרות (למשל My Tracks) הנתון הזה מופיע ומשמעותי.
</div>

**Comment by HarelM** [comment]
אני לא חושב שכדאי להוסיף עוד סטטיסטיקות. שש זה יותר ממספיק לדעתי.
לגבי שאר ההצעות, אני לא בטוח שהסיבוך הנוסף בקוד בתחזוקה שווה את המאמץ.
תוכל לפרט איזה ערך מוסף זה למשתמש שמצדיק את השינוי?

**Comment by amiad** [comment]
<div dir="rtl">
אני מציע להחליף את המהירות הנוכחית במהירות ממוצעת למרחק קצר אחרון כדי לתת מידע מדויק יותר שלא מתחלף כל שניה.

מהירות ממוצעת בתנועה ועזרת כדי לדעת את הקצב לא כולל הפסקות. כך אפשר לדעת מה הקצב האמתי שבו הלכת בלי להתחשב בעצירה לקפה או עצירות אחרות. כך אפשר לדעת אם צריך להגביר את הקצב למשל.
</div>

**Comment by valleyofdawn** [comment]
בתצורה הנוכחית יש 6 סלוטים לסטטיסטיקה בטבלה. אם נרחיב אותם לשמונה נשלם בפחות קריאות בתנועה - לא בטוח שכדאי. 
מהירות בתנועה היא נתון שמעניין ספורטאים. אפשר גם גובה נוכחי כדי להשלים נתון בשורה השניה. אם זה לא מסובך כדאי בהחלט למצע מהירויות ב-5 שניות האחרונות, כדי להשיג יותר יציבות.

**Comment by HarelM** [comment]
אני לא רואה פה ערך מוסף למשתמש שמצדיק פיתוח, מצטער.
תודה רבה על הנכונות לפתוח דיון בנושא :-)
