### ISSUE TITLE
Deleting all tracks when in view mode

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#994]
## Feature
I suggest the "x" button for deleting routes should also be visible when no routes are selected.
When pressed it would immediately show a warning   "This will remove all tracks and points, are you sure?" and delete them all if approved.
It simplifies the UX and puts "delete all" in a position relevant to all tracks, not just the active one.
See for instance:
https://www.facebook.com/groups/994960670559126/2119140788141103/?comment_id=2119154534806395

**Comment by HarelM** [comment]
@zstadler please approve - changes in the main interface requires the consent of all of us.

**Comment by zstadler** [comment]
Agreed
