### ISSUE TITLE
Design suggestions

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#995]
![design suggestions](https://user-images.githubusercontent.com/689201/54747747-63bf2080-4bd8-11e9-8875-a244bf784f38.png)

**Comment by HarelM** [comment]
I've changed the undo.
I do not agree about the other comments.
Also, much like other stuff, the right way to solve it is by hiring a designer.
Please close this issue.

**Comment by valleyofdawn** [comment]
Until we can hire a designer we can discuss our design preferences and reach an agreement.
Please explain why you disagree with the other comments before I close this issue.

**Comment by HarelM** [comment]
It's a subjective matter and I di nit agree, sorry. I have explained my preferences in other issues. I hate repeating myself.

**Comment by valleyofdawn** [comment]
You have  explained your preferences only  regarding some of these.
It's not all subjective. How visible the language icon is in low rez clearly depends on how small  its elements are. Nobody would think it's ideal for two radio buttons to touch one another.

**Comment by HarelM** [comment]
This discussion is not going anywhere.
Closing...
