### ISSUE TITLE
Broken link to an OSM user, probably after the user name was changed

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#996]
## What really happened
Link to last editor in OSM is broken

## What I did that caused the issue - step by step
1. Open https://israelhiking.osm.org.il/poi/OSM/node_3655428695
2. Open the link to the last editor in OSM:
    > [ألبرشت شونكا](https://www.openstreetmap.org/user/%D8%A3%D9%84%D8%A8%D8%B1%D8%B4%D8%AA%20%D8%B4%D9%88%D9%86%D9%83%D8%A7) - 01/01/2018
3. The result is "The user ألبرشت شونكا does not exist"

## Thing I think the developers should know, images, links etc.
- When opening [node 3655428695](https://www.openstreetmap.org/node/3655428695) in OSM, the user name is different:
   > Edited about 1 year ago by [سامبا](https://www.openstreetmap.org/user/%D8%B3%D8%A7%D9%85%D8%A8%D8%A7)

   and the link goes to a valid user page.

- I seem to recall that the "invalid" user name used to be a valid name. It is possible that the user has changed the user-name associated with the user-id, and that for some reason, IHM still gets the old name. 
- I believe this is a low priority bug.

**Comment by HarelM** [comment]
I think this was an OSM file issue - the link is OK now. The link is coming from the OSM file, I just convert the name to a link.
Can I close this one?

**Comment by zstadler** [comment]
Seems to be fixed
