### ISSUE TITLE
Migrate to mapbox

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#997]
## Infra
As part of the effort to implement #971 we have seen the the peformance of openlayer isn't good enough for detailed map. therefore we need to migrate the code from open layers to mapbox...

 - [x] line animation
 - [x] start and end green-red markers
 - [x] traces
 - [x] recording color
 - [x] handle drag end of marker - click should not happen
 - [x] location marker
 - [x] move hard-coded string to resources
 - [x] clean poi edit interaction class
 - [x] ~overlay order when select-deselect?~
 - [x] default glyph and sprite
 - [x] close popup of cluster after click
 - [x] remove all references to openlayers
 - [x] remove all `aol-...` html references
 - [x] controls css
 - [x] add arcgis support?
 - [x] add rtl support
 - [x] pointer counter check for touch
 - [x] touch events for route planning
 - [x] fix icons sprite address
 - [x] allow hebrew fonts using https://github.com/orangemug/font-glyphs
 - [x] Gps arrow is missing in mobile app.
 - [x] Rotation should use animation when GPS is on.
 - [x] When finishing recording the route should refresh to match the right color.
 - [x] Hebrew doesn't work well in cordova - probably related to finding the local file.
 - [x] Remove attribution when selecting a vector layer as it occupies the statistics space
 - [x] ~allow usage of fonts offline?~ will be addressed as part of offline support feature
 - [x] bring back snappings
 - [x] ~improve route editing performance~ ignoring this for now as it's reasonable

**Comment by HarelM** [comment]
Playground:
https://stackblitz.com/edit/angular-ngx-mapbox-ihm

**Comment by HarelM** [comment]
Also this will probably be needed to support integer zoom levels:
https://github.com/mapbox/mapbox-gl-js/issues/1695

**Comment by zstadler** [comment]
> Also this will probably be needed to support integer zoom levels:
mapbox/mapbox-gl-js#1695

IMHO, having non-integer zoom levels is a benefit for the user. On a small screen,  integers zoom levels could be either too small or too large. Non-integer zoom levels are also beneficial when trying to fit a route to the screen size.

On the other hand, using integer zoom levels for the on-screen buttons is probably the right thing to do.

**Comment by valleyofdawn** [comment]
RTL support entry point:
https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-rtl-text/

**Comment by HarelM** [comment]
Ant-path animation for mapbox - very similar to how openlayers work:
https://jsfiddle.net/2mws8y3q/

**Comment by HarelM** [comment]
Drag a point - needed for editing:
https://docs.mapbox.com/mapbox-gl-js/example/drag-a-point/

**Comment by HarelM** [comment]
Click on a layer to get the right feature to do something:
https://docs.mapbox.com/mapbox-gl-js/example/popup-on-click/

**Comment by HarelM** [comment]
@valleyofdawn @zstadler FYI: it seems like there can be only one sprite for the map:
See here:
https://github.com/mapbox/mapbox-gl-js/issues/4086
And here:
https://stackoverflow.com/questions/36867301/multiple-icon-sprites-with-mapbox-gl-js
Same goes for the font stack.
I suggest to create a sprite that will serve both IHM and IMTBM as add it to the site.

**Comment by zstadler** [comment]
Yes, the existing sprite is intended for both maps and includes the union of the required icons.

**Comment by HarelM** [comment]
Houston, we have a problem:
Just ran into this issue:
https://github.com/mapbox/mapbox-gl-js/issues/2171
It mean we won't be able to support external tile server that do not support CORS, which is a big problem...

**Comment by HarelM** [comment]
Initial app testing:
Gps arrow is missing.
Rotation should use animation when GPS is on.
When finishing recording the route sound refresh to match the right color.
Vector layer is empty.

**Comment by valleyofdawn** [comment]
The "record" button is still present in the web version.
The "northing" button rotates the map back to "north up" but doesn't straiten the map pitch.

**Comment by zstadler** [comment]
Cannot view the PEF map
`http://213.8.25.66/arcgis/rest/services/BaseMaps/PEFMap/MapServer`
 
No `GET` requests for tiles in this map source.

**Comment by HarelM** [comment]
See my comment above related to CORS, it might also be related to the fact that this server is not secured (https). But I'm writing these lines without proper debug so I might be wrong...

**Comment by zstadler** [comment]
> The "northing" button rotates the map back to "north up" but doesn't straiten the map pitch.

The map pitch can be easily reset with a pitch-down gesture (ctrl-mouse-drag down).
I'm not sure the "northing" button should change the map pitch.

**Comment by valleyofdawn** [comment]
> The map pitch can be easily reset with a pitch-down gesture (ctrl-mouse-drag down).
> I'm not sure the "northing" button should change the map pitch.
It's a minor issue, but I'm used to this convention from other apps, save a few secs.

**Comment by HarelM** [comment]
@zstadler I have added the following code in order to support arcgis:
https://github.com/IsraelHikingMap/Site/blob/9a95c3b305086a312d14c9bacf8717ac8ac3e262/IsraelHiking.Web/sources/application/components/map/automatic-layer-presentation.component.ts#L79
Which should export the right piece of the map and present it.
I think the PEF server doesn't fully supports this feature at it returns transparent tiles.
The code above might be incorrect too, but I'm not an ArgGIS expert, if you think the address change is incorrect or should be altered please let me know - this was a trail and error on my behalf to make an ArcGIS example work...

**Comment by HarelM** [comment]
Furthermore related to PEF:
I was able to switch to mixed content in my desktop browser and I was able to get the map working.
The following turned from an error to a warning:
`Cross-Origin Read Blocking (CORB) blocked cross-origin response http://213.8.25.66/arcgis/rest/services/BaseMaps/PEFMap/MapServer/ with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.`
So there's no doubt it is related to the difference openlayers and mapbox fetch images.
I'm not sure how to solve this, I couldn't find anything in the docs to indicate how to workaround this.
Adding `https://cors-anywhere.herokuapp.com/` doesn't help too for some reason, it might be that ArcGIS actively blocks this...
![image](https://user-images.githubusercontent.com/3269297/56831977-40d8f980-6873-11e9-97e9-00c80c18c40c.png)

**Comment by HarelM** [comment]
The following address seems to workaround all the issues I've mentioned:
https://cors-anywhere.herokuapp.com/http://213.8.25.66/arcgis/rest/services/BaseMaps/PEFMap/MapServer/tile/{z}/{y}/{x}

**Comment by zstadler** [comment]
Great!

I don't know why the `cors-anywhere.herokuapp.com` prefix didn't work for me when I tried it. Perhaps there was some typing error.

I suggest the client will add a `https://cors-anywhere.herokuapp.com/` prefix to every `http` source in a user-invisible way.

**Comment by HarelM** [comment]
That's a great idea! implemented, yet to be released.

**Comment by valleyofdawn** [comment]
Overall very robust and bug-free.

1. Custom maps: http doesn’t work - only https.
2. Some https custom maps won't show either. Such as: מנדטורית שנות הארבעים, Strava heatmaps and several orthophotos. 
3. The CORSanywhere workaround works just in  some of the cases
4. Image POIs  - the text overlaps with the image. (see below)
5. The legend doesn’t work with the vector map 
![image](https://user-images.githubusercontent.com/689201/56852631-362b6c80-6926-11e9-8c9c-657f7664411d.png)

**Comment by HarelM** [comment]
CORS anywhere will fix (some) http maps - I'm afraid there's nothing more I can do.
I've fixed the legend.
I can't reproduce the text image and the text overlap, this is how I see it on my desktop:
Tested both FF and Chrome, do you have special settings on your PC?
![image](https://user-images.githubusercontent.com/3269297/56853679-d20fa500-6933-11e9-8333-e75b4996610f.png)

**Comment by HarelM** [comment]
Never mind, when image has no icon the text overlaps. I'll fix it.

**Comment by HarelM** [comment]
Branch was merged to master, all pending issues have been resolved, beta site was updated with latest changes.
Please open separate issues for stuff we find from no on...
