### ISSUE TITLE
Make POI labels less obscuring

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#998]
## Feature

As they stand, the POI labels cover a lot of the trail.
Things we can do to improve things:
1) use a smaller font
2) use semi-transparent background
3) move them behind the routes.

See example for suggestion 1 and 2
![POI](https://user-images.githubusercontent.com/689201/55383412-cb5a6180-5530-11e9-8ac8-a20ebb3a21ad.png)

**Comment by HarelM** [comment]
Related to #933.
We do not agree what should be the right UX in general.
Please add a persevering there with all the required information.
