### ISSUE TITLE
City names overlapped by roads

### ISSUE THREAD

**Issue by arieltolkachov** [IsraelHikingMap/Site#999]
## Bug
(Delete the non-relevant)

## What I expect to happen
City names are visible as top layer on the map

## What really happened
City names are hidden behind map elements like roads
![Screen Shot 2019-04-08 at 11 58 56](https://user-images.githubusercontent.com/384229/55712252-14aa2580-59f7-11e9-806f-d56949ba4c4c.png)

## What I did that caused the issue - step by step
Opened up the map. Nothing special. 

## My environment
* Operating System and version: MacOS 10.14.4
* Web Browser and version: Safari 12.1 + Firefox 66 (64 bit)

## Thing I think the developers should know, images, links etc.
Not reproducible on Chrome 73

**Comment by HarelM** [comment]
Are you sure you do not have the trails overlay turned on?
Can you post a screenshot of your layers menu?

**Comment by arieltolkachov** [comment]
I haven’t seen an option to manage the layers. So if this is the case, please let me know.
Here is the screenshot of the maps / layers menu:
[cid:image001.png@01D4EE04.B580E430]

**Comment by HarelM** [comment]
Screenshot didn't make it to github :-(

**Comment by arieltolkachov** [comment]
![Screen Shot 2019-04-08 at 12 13 38](https://user-images.githubusercontent.com/384229/55717018-17117d00-5a01-11e9-8e83-5825343399a1.png)

**Comment by HarelM** [comment]
שכבת מסלולי אופניים השקופה דלוקה מעל שכבת מפת האופניים הפתוחה.
תכבה אותה והבעיה תפתר.
